IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_MOVIMIENTODECAJA_CIERREDELDIA_MOVIMIENTODECAJA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_MOVIMIENTODECAJA_CIERREDELDIA_MOVIMIENTODECAJA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_MOVIMIENTODECAJA_CIERREDELDIA_MOVIMIENTODECAJA]
( @BaseDeDatos varchar(8),
	@MOVIMIENTODECAJA_VALOR_DESDE varchar(5),
	@MOVIMIENTODECAJA_VALOR_HASTA varchar(5),
	@MOVIMIENTODECAJA_FECHACOMPROBANTE_DESDE datetime,
	@MOVIMIENTODECAJA_FECHACOMPROBANTE_HASTA datetime,
	@MOVIMIENTODECAJA_NUMEROCOMPROBANTE_DESDE numeric(9, 0),
	@MOVIMIENTODECAJA_NUMEROCOMPROBANTE_HASTA numeric(9, 0),
	@MOVIMIENTODECAJA_PUNTODEVENTA_DESDE numeric(4, 0),
	@MOVIMIENTODECAJA_PUNTODEVENTA_HASTA numeric(4, 0),
	@MOVIMIENTODECAJA_SECUENCIA_DESDE varchar(2),
	@MOVIMIENTODECAJA_SECUENCIA_HASTA varchar(2),
	@MOVIMIENTODECAJA_FECHA_DESDE datetime,
	@MOVIMIENTODECAJA_FECHA_HASTA datetime,
	@MOVIMIENTODECAJA_CAJAAUDITORIA_DESDE numeric(10, 0),
	@MOVIMIENTODECAJA_CAJAAUDITORIA_HASTA numeric(10, 0),
	@MOVIMIENTODECAJA_FECHACAJA_DESDE datetime,
	@MOVIMIENTODECAJA_FECHACAJA_HASTA datetime,
	@MOVIMIENTODECAJA_HORA_DESDE varchar(8),
	@MOVIMIENTODECAJA_HORA_HASTA varchar(8),
	@MOVIMIENTODECAJA_CAJAESTADO_DESDE numeric(2, 0),
	@MOVIMIENTODECAJA_CAJAESTADO_HASTA numeric(2, 0),
	@MOVIMIENTODECAJA_MONTO_DESDE numeric(15, 2),
	@MOVIMIENTODECAJA_MONTO_HASTA numeric(15, 2),
	@MOVIMIENTODECAJA_DESCRIPCION_DESDE varchar(50),
	@MOVIMIENTODECAJA_DESCRIPCION_HASTA varchar(50),
	@MOVIMIENTODECAJA_COTIZACION_DESDE numeric(15, 5),
	@MOVIMIENTODECAJA_COTIZACION_HASTA numeric(15, 5),
	@CAJAESTADO_29_CAJAESTADO_DESCRIPCION_DESDE varchar(40),
	@CAJAESTADO_29_CAJAESTADO_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_10061_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_10061_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_10060_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_10060_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_10059_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_10059_TIPO_DESCRIPCION_HASTA varchar(50),
	@VALOR_9910_VALOR_DESCRIPCION_DESDE varchar(40),
	@VALOR_9910_VALOR_DESCRIPCION_HASTA varchar(40),
	@VENDEDOR_9920_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_9920_VENDEDOR_NOMBRE_HASTA varchar(60),
	@SUCURSAL_10056_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_10056_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_10056_LINEA_DESDE varchar(10),
	@SUCURSAL_10056_LINEA_HASTA varchar(10),
	@SUCURSAL_10056_TIPO_DESDE varchar(10),
	@SUCURSAL_10056_TIPO_HASTA varchar(10),
	@SUCURSAL_10056_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_10056_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_10056_CODIGO_DESDE varchar(10),
	@SUCURSAL_10056_CODIGO_HASTA varchar(10),
	@MOVIMIENTODECAJA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@MOVIMIENTODECAJA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@MOVIMIENTODECAJA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@MOVIMIENTODECAJA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@MOVIMIENTODECAJA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@MOVIMIENTODECAJA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@MOVIMIENTODECAJA_FECHAALTAFW_DESDE datetime,
	@MOVIMIENTODECAJA_FECHAALTAFW_HASTA datetime,
	@MOVIMIENTODECAJA_FECHAEXPO_DESDE datetime,
	@MOVIMIENTODECAJA_FECHAEXPO_HASTA datetime,
	@MOVIMIENTODECAJA_FECHAIMPO_DESDE datetime,
	@MOVIMIENTODECAJA_FECHAIMPO_HASTA datetime,
	@MOVIMIENTODECAJA_FECHAMODIFICACIONFW_DESDE datetime,
	@MOVIMIENTODECAJA_FECHAMODIFICACIONFW_HASTA datetime,
	@MOVIMIENTODECAJA_FECHATRANSFERENCIA_DESDE datetime,
	@MOVIMIENTODECAJA_FECHATRANSFERENCIA_HASTA datetime,
	@MOVIMIENTODECAJA_HORAALTAFW_DESDE varchar(8),
	@MOVIMIENTODECAJA_HORAALTAFW_HASTA varchar(8),
	@MOVIMIENTODECAJA_HORAEXPO_DESDE varchar(8),
	@MOVIMIENTODECAJA_HORAEXPO_HASTA varchar(8),
	@MOVIMIENTODECAJA_HORAIMPO_DESDE varchar(8),
	@MOVIMIENTODECAJA_HORAIMPO_HASTA varchar(8),
	@MOVIMIENTODECAJA_HORAMODIFICACIONFW_DESDE varchar(8),
	@MOVIMIENTODECAJA_HORAMODIFICACIONFW_HASTA varchar(8),
	@MOVIMIENTODECAJA_SERIEALTAFW_DESDE varchar(7),
	@MOVIMIENTODECAJA_SERIEALTAFW_HASTA varchar(7),
	@MOVIMIENTODECAJA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@MOVIMIENTODECAJA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@MOVIMIENTODECAJA_USUARIOALTAFW_DESDE varchar(100),
	@MOVIMIENTODECAJA_USUARIOALTAFW_HASTA varchar(100),
	@MOVIMIENTODECAJA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@MOVIMIENTODECAJA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@MOVIMIENTODECAJA_VERSIONALTAFW_DESDE varchar(13),
	@MOVIMIENTODECAJA_VERSIONALTAFW_HASTA varchar(13),
	@MOVIMIENTODECAJA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@MOVIMIENTODECAJA_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_movimientodecaja.idmovi, 38, ' ' ) as varchar( 46 ) ) as MOVIMIENTODECAJA__Grupo,
	@basededatos as MOVIMIENTODECAJA__BD,
	c_MOVIMIENTODECAJA.IDMOVI as MOVIMIENTODECAJA_IdMovi,
	case when c_movimientodecaja.fechacompr = '01/01/1900 00:00:00' then null else c_movimientodecaja.fechacompr end as MOVIMIENTODECAJA_FechaCompr,
	c_MOVIMIENTODECAJA.NUMCOMP as MOVIMIENTODECAJA_NumComp,
	c_MOVIMIENTODECAJA.PTOVTA as MOVIMIENTODECAJA_PtoVta,
	c_MOVIMIENTODECAJA.FACTSEC as MOVIMIENTODECAJA_FactSec,
	case when c_movimientodecaja.fecha = '01/01/1900 00:00:00' then null else c_movimientodecaja.fecha end as MOVIMIENTODECAJA_Fecha,
	c_MOVIMIENTODECAJA.IDCAJAAUDI as MOVIMIENTODECAJA_IdCajaAudi,
	case when c_movimientodecaja.fechacaja = '01/01/1900 00:00:00' then null else c_movimientodecaja.fechacaja end as MOVIMIENTODECAJA_FechaCaja,
	c_MOVIMIENTODECAJA.HORA as MOVIMIENTODECAJA_Hora,
	c_MOVIMIENTODECAJA.IDCAJA as MOVIMIENTODECAJA_IDCaja,
	c_MOVIMIENTODECAJA.MONTO as MOVIMIENTODECAJA_Monto,
	c_MOVIMIENTODECAJA.DESCRIP as MOVIMIENTODECAJA_Descrip,
	c_MOVIMIENTODECAJA.COTIZ as MOVIMIENTODECAJA_Cotiz,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_MOVIMIENTODECAJA.BDALTAFW as MOVIMIENTODECAJA_BDALTAFW,
	c_MOVIMIENTODECAJA.BDMODIFW as MOVIMIENTODECAJA_BDMODIFW,
	c_MOVIMIENTODECAJA.ESTTRANS as MOVIMIENTODECAJA_ESTTRANS,
	case when c_movimientodecaja.faltafw = '01/01/1900 00:00:00' then null else c_movimientodecaja.faltafw end as MOVIMIENTODECAJA_FALTAFW,
	case when c_movimientodecaja.fecexpo = '01/01/1900 00:00:00' then null else c_movimientodecaja.fecexpo end as MOVIMIENTODECAJA_FECEXPO,
	case when c_movimientodecaja.fecimpo = '01/01/1900 00:00:00' then null else c_movimientodecaja.fecimpo end as MOVIMIENTODECAJA_FECIMPO,
	case when c_movimientodecaja.fmodifw = '01/01/1900 00:00:00' then null else c_movimientodecaja.fmodifw end as MOVIMIENTODECAJA_FMODIFW,
	case when c_movimientodecaja.fectrans = '01/01/1900 00:00:00' then null else c_movimientodecaja.fectrans end as MOVIMIENTODECAJA_FECTRANS,
	c_MOVIMIENTODECAJA.HALTAFW as MOVIMIENTODECAJA_HALTAFW,
	c_MOVIMIENTODECAJA.HORAEXPO as MOVIMIENTODECAJA_HORAEXPO,
	c_MOVIMIENTODECAJA.HORAIMPO as MOVIMIENTODECAJA_HORAIMPO,
	c_MOVIMIENTODECAJA.HMODIFW as MOVIMIENTODECAJA_HMODIFW,
	c_MOVIMIENTODECAJA.SALTAFW as MOVIMIENTODECAJA_SALTAFW,
	c_MOVIMIENTODECAJA.SMODIFW as MOVIMIENTODECAJA_SMODIFW,
	c_MOVIMIENTODECAJA.UALTAFW as MOVIMIENTODECAJA_UALTAFW,
	c_MOVIMIENTODECAJA.UMODIFW as MOVIMIENTODECAJA_UMODIFW,
	c_MOVIMIENTODECAJA.VALTAFW as MOVIMIENTODECAJA_VALTAFW,
	c_MOVIMIENTODECAJA.VMODIFW as MOVIMIENTODECAJA_VMODIFW,
	c_MOVIMIENTODECAJA.ZADSFW as MOVIMIENTODECAJA_ZADSFW,
	cast( c_movimientodecaja.compcliente as varchar( 10 ) ) as MOVIMIENTODECAJA_ClienteVirtual,
	cast( c_movimientodecaja.compdescripcliente as varchar( 185 ) ) as MOVIMIENTODECAJA_DescripClienteVirtual,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as MOVIMIENTODECAJA__SUCURSAL,
	cast( c_movimientodecaja.idcompcaja as varchar( 2 ) ) as MOVIMIENTODECAJA_TipoComp,
	cast( case when c_movimientodecaja.accion= 'a' then 'nuevo ' else case when c_movimientodecaja.accion= 'm' then 'modificar ' else case when c_movimientodecaja.accion= 'b' then 'eliminar ' else space(10) end end end as varchar( 10 ) ) as MOVIMIENTODECAJA_Accion,
	cast( case when c_movimientodecaja.monto< 0 then  c_movimientodecaja.monto else  0 end as numeric( 15, 2 ) ) as MOVIMIENTODECAJA_Egreso,
	cast( case when c_movimientodecaja.monto> 0 then  c_movimientodecaja.monto else  0 end as numeric( 15, 2 ) ) as MOVIMIENTODECAJA_Ingreso,
	cast( funciones.identificadordecomprobanteparalistado(funciones.obtenertipocomprobantesygruposdecaja(c_movimientodecaja.tipocomp), c_movimientodecaja.fletra, c_movimientodecaja.ptovta, c_movimientodecaja.numcomp) as varchar( 20 ) ) as MOVIMIENTODECAJA_ComprobanteVirtual,
	cast( case when funciones.obtenertipocomprobantesygruposdecaja(c_movimientodecaja.tipocomp) in(8,9,10) then(select top(1) clnom from zoologic.prov where clcod = c_compcompras.fperson) else 
	(case when c_movimientodecaja.tipocomp = 13 then c_recibo.FCLIENTE 
	else
	(case when c_movimientodecaja.tipocomp = 62 then C_PROVEEDOR.CLNOM
	else 
	(case when c_movimientodecaja.tipocomp = 82 then C_PROVEEDOROP.CLNOM
	else 
	c_compventas.fcliente end) end)end)end  as varchar( 100 ) ) as MOVIMIENTODECAJA_ClienteProveedor,
	cast( case when funciones.obtenertipocomprobantesygruposdecaja(c_movimientodecaja.tipocomp) in(8,9,10)
	 then c_compcompras.fobs
	 else 
	 (case when c_movimientodecaja.tipocomp = 13
	 then c_recibo.FOBS 
	 else 
	 (case when c_movimientodecaja.tipocomp = 6 
	 then c_CompCaj.COBS 
	 else
	 (case when c_movimientodecaja.tipocomp = 82 
	 then c_Compago.FOBS 
	 else
	 (case when c_movimientodecaja.tipocomp = 62
	 then concat(c_pago.FOBS,'', c_pago.FOPOBS)
	 else
	 c_compventas.fobs end)end)end) end) end as varchar( 250 ) ) as MOVIMIENTODECAJA_ObservacionesVirtual,
	cast( c_movimientodecaja.compconcepto as varchar( 10 ) ) as MOVIMIENTODECAJA_Concepto,	 
	C_VALOR.CLSMONET as VALOR_CLSMONET,
	cast( funciones.obtenermonedadeunvalor(c_valor.clcod) as varchar( 20 ) ) as MOVIMIENTODECAJA_DescripcionMoneda,
	cast( c_movimientodecaja.compcotiz as numeric( 15, 5 ) ) as MOVIMIENTODECAJA_CotizacionComprobante,
	c_MOVIMIENTODECAJA.IDVALOR as MOVIMIENTODECAJA_idValor,
	cast( c_movimientodecaja.compvend as varchar( 10 ) ) as MOVIMIENTODECAJA_IdVendedor,
	cast( c_movimientodecaja.compobservacion as varchar( 250 ) ) as MOVIMIENTODECAJA_Observacion,
	C_CAJAESTADO.DESCRIP as CAJAESTADO_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_VALOR.CLNOM as VALOR_CLNOM,
	C_VENDEDOR.CLNOM as VENDEDOR_CLNOM,
	C_CAJAESTADO.NUMCAJA as CAJAESTADO_NumCaja,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_VALOR.CLCOD as VALOR_CLCOD,
	C_VENDEDOR.CLCOD as VENDEDOR_CLCOD
 from ( select cast( Funciones.ObtenerIdentificadorComprobanteComprobantesYGruposDeCaja( TIPOCOMP ) as varchar( 3 ) ) as IdCompCaja, cast( Funciones.ObtenerTipoComprobantesYGruposDeCaja( TIPOCOMP ) as numeric( 4, 0 ) ) as FactTipo, cast( Funciones.ObtenerLetraComprobantesYGruposDeCaja( TIPOCOMP ) as char( 1 ) ) as FLetra, cast( case when ( PTOVTA = 0 ) then null else PTOVTA end as numeric( 4, 0 ) ) as PtoVtaAlta, cast( Funciones.ObtenerDescriptorComprobanteComprobantesYGruposDeCaja( TIPOCOMP ) as varchar( 50 ) ) as DescriptorComp, cast( Funciones.ObtenerDescripcionDelComprobanteComprobantesYGruposDeCaja( TIPOCOMP ) as varchar( 50 ) ) as DescripcionComp, cast( Funciones.ObtenerGrupoDeInformeComprobantesYGruposDeCaja( TIPOCOMP ) as varchar( 10 ) ) as GrupoDeInforme, cast( Funciones.ObtenerCotizacionDesdeUnComprobante( FACTSEC, Funciones.ObtenerTipoComprobantesYGruposDeCaja( TIPOCOMP ), Funciones.ObtenerLetraComprobantesYGruposDeCaja( TIPOCOMP ), PTOVTA, NUMCOMP ) as numeric( 15, 5 ) ) as CompCotiz, cast( Funciones.ObtenerGUIDDelComprobanteDeVentaAsociadoAlMovimientoDeCaja( TIPOCOMP, PTOVTA, IDCAJA, NUMCOMP, FACTSEC, ACCION ) as char( 38 ) ) as CompGUID, cast( Funciones.ObtenerVendedorDelComprobanteDeVentaAsociadoAlMovimientoDeCaja( TIPOCOMP, PTOVTA, IDCAJA, NUMCOMP, FACTSEC, ACCION ) as char( 10 ) ) as CompVEND, cast( Funciones.ObtenerConceptoDelComprobanteAsociadoAlMovimientoDeCaja(NUMCOMP) as char( 10 ) ) as CompConcepto, cast( Funciones.ObtenerTablaDeOrigenDelRegistroComprobantesYGruposDeCaja( TIPOCOMP ) as varchar( 20 ) ) as CompTabla, cast( case when row_number() over( partition by fecha, tipocomp, ptovta, idcaja, numcomp, factsec order by timestamp ) = 1 then 1 else 0 end as bit ) as MuestraInfoComp, cast( sum( MONTO * COTIZ ) over( partition by fecha, tipocomp, ptovta, idcaja, numcomp, factsec ) as numeric( 20, 5 ) ) as MovCajaPorComp, cast( Funciones.ObtenerObservacionDelComprobanteDeVentaAsociadoAlMovimientoDeCaja( TIPOCOMP, PTOVTA, IDCAJA, NUMCOMP, FACTSEC, ACCION ) as char( 250 ) ) as CompObservacion,
 cast( Funciones.ObtenerClienteDelComprobanteDeVentaAsociadoAlMovimientoDeCaja( TIPOCOMP, PTOVTA, IDCAJA, NUMCOMP, FACTSEC, ACCION ) as char( 10 ) ) as CompCLIENTE, cast( Funciones.ObtenerDescripClienteDelComprobanteDeVentaAsociadoAlMovimientoDeCaja( TIPOCOMP, PTOVTA, IDCAJA, NUMCOMP, FACTSEC, ACCION ) as char( 185 ) ) as CompDESCRIPCLIENTE,
 * from ZooLogic.MOVCAJA) as c_MOVIMIENTODECAJA
left join Listados.Vista_ComprobanteC as c_compCompras on c_compCompras.FACTTIPO = funciones.obtenertipocomprobantesygruposdecaja(c_movimientodecaja.TIPOCOMP) and c_compCompras.FLETRA = c_movimientodecaja.fletra and c_compCompras.FPTOVEN = c_movimientodecaja.ptovta and c_compCompras.FNUMCOMP = c_movimientodecaja.numcomp
left join zoologic.COMPROBANTEV as c_CompVentas on c_CompVentas.FACTTIPO = funciones.obtenertipocomprobantesygruposdecaja(c_movimientodecaja.TIPOCOMP) and c_CompVentas.FLETRA = c_movimientodecaja.fletra and c_CompVentas.FPTOVEN = c_movimientodecaja.ptovta and c_CompVentas.FNUMCOMP = c_movimientodecaja.numcomp
left join zoologic.COMCAJ as c_CompCaj on c_CompCaj.NUMERO = c_movimientodecaja.numcomp and c_movimientodecaja.TIPOCOMP = 6
left join zoologic.COMPPAGO as c_Compago on c_compago.NUMERO = c_movimientodecaja.NUMCOMP and c_MOVIMIENTODECAJA.TIPOCOMP = 82
left join  zoologic.PAGO as c_pago on c_pago.FNUMCOMP = c_movimientodecaja.NUMCOMP and  c_movimientodecaja.TIPOCOMP = 62
left join zoologic.RECIBO as c_recibo on c_recibo.FACTTIPO = funciones.obtenertipocomprobantesygruposdecaja(c_movimientodecaja.TIPOCOMP) and c_recibo.FPTOVEN = c_movimientodecaja.ptovta and c_recibo.FNUMCOMP = c_movimientodecaja.numcomp
left join ZooLogic.CAJAESTA as C_CAJAESTADO on C_CAJAESTADO.NUMCAJA = C_MOVIMIENTODECAJA.IDCAJA and 0 = Funciones.empty( C_MOVIMIENTODECAJA.IDCAJA )
left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
left join ZooLogic.XVAL as C_VALOR on C_VALOR.CLCOD = C_MOVIMIENTODECAJA.IDVALOR and 0 = Funciones.empty( C_MOVIMIENTODECAJA.IDVALOR )
left join ZooLogic.VEN as C_VENDEDOR on C_VENDEDOR.CLCOD = cast( c_movimientodecaja.compvend as varchar( 10 ) ) and 0 = Funciones.empty( cast( c_movimientodecaja.compvend as varchar( 10 ) ) )
left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_VALOR.CLSMONET and 0 = Funciones.empty( C_VALOR.CLSMONET )
left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
left join ZooLogic.PROV as C_PROVEEDOR on C_PROVEEDOR.CLCOD = C_PAGO.FPERSON 
left join ZooLogic.PROV as C_PROVEEDOROP on C_PROVEEDOROP.CLCOD = C_COMPAGO.FPERSON
where ( 1=1 ) and 
	( ( @MOVIMIENTODECAJA_VALOR_DESDE is null ) OR ( c_MOVIMIENTODECAJA.idValor >= @MOVIMIENTODECAJA_VALOR_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_VALOR_HASTA is null ) OR ( c_MOVIMIENTODECAJA.idValor <= @MOVIMIENTODECAJA_VALOR_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHACOMPROBANTE_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FechaCompr >= @MOVIMIENTODECAJA_FECHACOMPROBANTE_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHACOMPROBANTE_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FechaCompr <= @MOVIMIENTODECAJA_FECHACOMPROBANTE_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_NUMEROCOMPROBANTE_DESDE is null ) OR ( c_MOVIMIENTODECAJA.NumComp >= @MOVIMIENTODECAJA_NUMEROCOMPROBANTE_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_NUMEROCOMPROBANTE_HASTA is null ) OR ( c_MOVIMIENTODECAJA.NumComp <= @MOVIMIENTODECAJA_NUMEROCOMPROBANTE_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_PUNTODEVENTA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.PtoVta >= @MOVIMIENTODECAJA_PUNTODEVENTA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_PUNTODEVENTA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.PtoVta <= @MOVIMIENTODECAJA_PUNTODEVENTA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_SECUENCIA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FactSec >= @MOVIMIENTODECAJA_SECUENCIA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_SECUENCIA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FactSec <= @MOVIMIENTODECAJA_SECUENCIA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.Fecha >= @MOVIMIENTODECAJA_FECHA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.Fecha <= @MOVIMIENTODECAJA_FECHA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_CAJAAUDITORIA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.IdCajaAudi >= @MOVIMIENTODECAJA_CAJAAUDITORIA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_CAJAAUDITORIA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.IdCajaAudi <= @MOVIMIENTODECAJA_CAJAAUDITORIA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHACAJA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FechaCaja >= @MOVIMIENTODECAJA_FECHACAJA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHACAJA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FechaCaja <= @MOVIMIENTODECAJA_FECHACAJA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_HORA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.Hora >= @MOVIMIENTODECAJA_HORA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_HORA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.Hora <= @MOVIMIENTODECAJA_HORA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_CAJAESTADO_DESDE is null ) OR ( c_MOVIMIENTODECAJA.IDCaja >= @MOVIMIENTODECAJA_CAJAESTADO_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_CAJAESTADO_HASTA is null ) OR ( c_MOVIMIENTODECAJA.IDCaja <= @MOVIMIENTODECAJA_CAJAESTADO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_MONTO_DESDE is null ) OR ( c_MOVIMIENTODECAJA.Monto >= @MOVIMIENTODECAJA_MONTO_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_MONTO_HASTA is null ) OR ( c_MOVIMIENTODECAJA.Monto <= @MOVIMIENTODECAJA_MONTO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_DESCRIPCION_DESDE is null ) OR ( c_MOVIMIENTODECAJA.Descrip >= @MOVIMIENTODECAJA_DESCRIPCION_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_DESCRIPCION_HASTA is null ) OR ( c_MOVIMIENTODECAJA.Descrip <= @MOVIMIENTODECAJA_DESCRIPCION_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_COTIZACION_DESDE is null ) OR ( c_MOVIMIENTODECAJA.Cotiz >= @MOVIMIENTODECAJA_COTIZACION_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_COTIZACION_HASTA is null ) OR ( c_MOVIMIENTODECAJA.Cotiz <= @MOVIMIENTODECAJA_COTIZACION_HASTA ) ) and 
	( ( @CAJAESTADO_29_CAJAESTADO_DESCRIPCION_DESDE is null ) OR ( C_CAJAESTADO.Descrip >= @CAJAESTADO_29_CAJAESTADO_DESCRIPCION_DESDE ) ) and 
	( ( @CAJAESTADO_29_CAJAESTADO_DESCRIPCION_HASTA is null ) OR ( C_CAJAESTADO.Descrip <= @CAJAESTADO_29_CAJAESTADO_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_10061_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_10061_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_10061_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_10061_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_10060_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_10060_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_10060_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_10060_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_10059_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_10059_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_10059_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_10059_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VALOR_9910_VALOR_DESCRIPCION_DESDE is null ) OR ( C_VALOR.CLNOM >= @VALOR_9910_VALOR_DESCRIPCION_DESDE ) ) and 
	( ( @VALOR_9910_VALOR_DESCRIPCION_HASTA is null ) OR ( C_VALOR.CLNOM <= @VALOR_9910_VALOR_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_9920_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR.CLNOM >= @VENDEDOR_9920_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_9920_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR.CLNOM <= @VENDEDOR_9920_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @SUCURSAL_10056_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_10056_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_10056_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_10056_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_10056_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_10056_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_10056_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_10056_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_10056_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_10056_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_10056_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_10056_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_10056_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_10056_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_10056_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_10056_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_10056_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_10056_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_10056_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_10056_CODIGO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.BDALTAFW >= @MOVIMIENTODECAJA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.BDALTAFW <= @MOVIMIENTODECAJA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.BDMODIFW >= @MOVIMIENTODECAJA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.BDMODIFW <= @MOVIMIENTODECAJA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.ESTTRANS >= @MOVIMIENTODECAJA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.ESTTRANS <= @MOVIMIENTODECAJA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAALTAFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FALTAFW >= @MOVIMIENTODECAJA_FECHAALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAALTAFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FALTAFW <= @MOVIMIENTODECAJA_FECHAALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAEXPO_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FECEXPO >= @MOVIMIENTODECAJA_FECHAEXPO_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAEXPO_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FECEXPO <= @MOVIMIENTODECAJA_FECHAEXPO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAIMPO_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FECIMPO >= @MOVIMIENTODECAJA_FECHAIMPO_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAIMPO_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FECIMPO <= @MOVIMIENTODECAJA_FECHAIMPO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FMODIFW >= @MOVIMIENTODECAJA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FMODIFW <= @MOVIMIENTODECAJA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_FECHATRANSFERENCIA_DESDE is null ) OR ( c_MOVIMIENTODECAJA.FECTRANS >= @MOVIMIENTODECAJA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_FECHATRANSFERENCIA_HASTA is null ) OR ( c_MOVIMIENTODECAJA.FECTRANS <= @MOVIMIENTODECAJA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_HORAALTAFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.HALTAFW >= @MOVIMIENTODECAJA_HORAALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_HORAALTAFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.HALTAFW <= @MOVIMIENTODECAJA_HORAALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_HORAEXPO_DESDE is null ) OR ( c_MOVIMIENTODECAJA.HORAEXPO >= @MOVIMIENTODECAJA_HORAEXPO_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_HORAEXPO_HASTA is null ) OR ( c_MOVIMIENTODECAJA.HORAEXPO <= @MOVIMIENTODECAJA_HORAEXPO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_HORAIMPO_DESDE is null ) OR ( c_MOVIMIENTODECAJA.HORAIMPO >= @MOVIMIENTODECAJA_HORAIMPO_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_HORAIMPO_HASTA is null ) OR ( c_MOVIMIENTODECAJA.HORAIMPO <= @MOVIMIENTODECAJA_HORAIMPO_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_HORAMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.HMODIFW >= @MOVIMIENTODECAJA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_HORAMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.HMODIFW <= @MOVIMIENTODECAJA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_SERIEALTAFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.SALTAFW >= @MOVIMIENTODECAJA_SERIEALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_SERIEALTAFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.SALTAFW <= @MOVIMIENTODECAJA_SERIEALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.SMODIFW >= @MOVIMIENTODECAJA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.SMODIFW <= @MOVIMIENTODECAJA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_USUARIOALTAFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.UALTAFW >= @MOVIMIENTODECAJA_USUARIOALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_USUARIOALTAFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.UALTAFW <= @MOVIMIENTODECAJA_USUARIOALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.UMODIFW >= @MOVIMIENTODECAJA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.UMODIFW <= @MOVIMIENTODECAJA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_VERSIONALTAFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.VALTAFW >= @MOVIMIENTODECAJA_VERSIONALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_VERSIONALTAFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.VALTAFW <= @MOVIMIENTODECAJA_VERSIONALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTODECAJA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTODECAJA.VMODIFW >= @MOVIMIENTODECAJA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTODECAJA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTODECAJA.VMODIFW <= @MOVIMIENTODECAJA_VERSIONMODIFICACIONFW_HASTA ) )

)