IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_RECIBO_ITEMVALORES]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_RECIBO_ITEMVALORES];
GO;

CREATE FUNCTION [Listados].[GENERICO_RECIBO_ITEMVALORES]
( @BaseDeDatos varchar(8),
	@RECIBO_CLIENTE_DESDE varchar(10),
	@RECIBO_CLIENTE_HASTA varchar(10),
	@RECIBO_VENDEDOR_DESDE varchar(10),
	@RECIBO_VENDEDOR_HASTA varchar(10),
	@RECIBO_MONEDACOMPROBANTE_DESDE varchar(10),
	@RECIBO_MONEDACOMPROBANTE_HASTA varchar(10),
	@RECIBO_CLIENTEDESCRIPCION_DESDE varchar(185),
	@RECIBO_CLIENTEDESCRIPCION_HASTA varchar(185),
	@RECIBO_LETRA_DESDE varchar(1),
	@RECIBO_LETRA_HASTA varchar(1),
	@RECIBO_PUNTODEVENTA_DESDE numeric(4, 0),
	@RECIBO_PUNTODEVENTA_HASTA numeric(4, 0),
	@RECIBO_NUMERO_DESDE numeric(8, 0),
	@RECIBO_NUMERO_HASTA numeric(8, 0),
	@RECIBO_FECHA_DESDE datetime,
	@RECIBO_FECHA_HASTA datetime,
	@RECIBO_TOTAL_DESDE numeric(15, 2),
	@RECIBO_TOTAL_HASTA numeric(15, 2),
	@CLIENTE_21_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_21_CLIENTE_NOMBRE_HASTA varchar(185),
	@VENDEDOR_77_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_77_VENDEDOR_NOMBRE_HASTA varchar(60),
	@MONEDA_78_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_78_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_22_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_22_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_37_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_37_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_39_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_39_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_45_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_45_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_46_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_46_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_49_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_49_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_50_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_50_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_56_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_56_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_57_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_57_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_58_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_58_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_59_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_59_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_61_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_61_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_64_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_64_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_73_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_73_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_9144_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9144_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9144_LINEA_DESDE varchar(10),
	@SUCURSAL_9144_LINEA_HASTA varchar(10),
	@SUCURSAL_9144_TIPO_DESDE varchar(10),
	@SUCURSAL_9144_TIPO_HASTA varchar(10),
	@SUCURSAL_9144_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9144_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_21_VENDEDOR_DESDE varchar(10),
	@CLIENTE_21_VENDEDOR_HASTA varchar(10),
	@CLIENTE_21_CALLE_DESDE varchar(70),
	@CLIENTE_21_CALLE_HASTA varchar(70),
	@CLIENTE_21_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_21_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_21_CUIT_DESDE varchar(15),
	@CLIENTE_21_CUIT_HASTA varchar(15),
	@CLIENTE_21_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_21_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_21_EMAIL_DESDE varchar(250),
	@CLIENTE_21_EMAIL_HASTA varchar(250),
	@CLIENTE_21_FAX_DESDE varchar(20),
	@CLIENTE_21_FAX_HASTA varchar(20),
	@CLIENTE_21_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_21_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_21_IMAGEN_DESDE varchar(180),
	@CLIENTE_21_IMAGEN_HASTA varchar(180),
	@CLIENTE_21_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_21_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_21_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_21_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_21_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_21_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_21_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_21_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_21_PAIS_DESDE varchar(3),
	@CLIENTE_21_PAIS_HASTA varchar(3),
	@CLIENTE_21_PISO_DESDE varchar(3),
	@CLIENTE_21_PISO_HASTA varchar(3),
	@CLIENTE_21_PROVINCIA_DESDE varchar(2),
	@CLIENTE_21_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_40_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_21_TELEFONO_DESDE varchar(30),
	@CLIENTE_21_TELEFONO_HASTA varchar(30),
	@CLIENTE_21_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_21_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_21_MOVIL_DESDE varchar(30),
	@CLIENTE_21_MOVIL_HASTA varchar(30),
	@CLIENTE_21_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_21_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_21_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_21_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_21_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_21_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_21_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_21_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_21_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_21_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_21_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_21_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_21_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_21_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_21_ESTADOCIVIL varchar(13),
	@CLIENTE_21_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_21_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_21_SEXO varchar(10),
	@CLIENTE_21_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_21_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_21_RUT_DESDE varchar(12),
	@CLIENTE_21_RUT_HASTA varchar(12),
	@CLIENTE_21_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_21_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_21_TIPOCLI_DESDE varchar(10),
	@CLIENTE_21_TIPOCLI_HASTA varchar(10),
	@CLIENTE_21_CATEGCLI_DESDE varchar(10),
	@CLIENTE_21_CATEGCLI_HASTA varchar(10),
	@CLIENTE_21_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_21_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_21_SUJETOVINCULADO bit,
	@CLIENTE_21_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_21_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_21_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_21_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_21_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_21_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_21_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_21_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_21_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_21_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_21_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_21_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_21_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_21_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_21_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_21_APELLIDO_DESDE varchar(60),
	@CLIENTE_21_APELLIDO_HASTA varchar(60),
	@CLIENTE_21_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_21_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_21_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_21_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_21_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_21_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_21_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_21_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_21_TASACEROAPLICA bit,
	@CLIENTE_21_INACTIVOFW bit,
	@SUCURSAL_9144_CODIGO_DESDE varchar(10),
	@SUCURSAL_9144_CODIGO_HASTA varchar(10),
	@RECIBO_FECHAALTAFW_DESDE datetime,
	@RECIBO_FECHAALTAFW_HASTA datetime,
	@RECIBO_HORAALTAFW_DESDE varchar(8),
	@RECIBO_HORAALTAFW_HASTA varchar(8),
	@RECIBO_BASEDEDATOSALTAFW_DESDE varchar(8),
	@RECIBO_BASEDEDATOSALTAFW_HASTA varchar(8),
	@RECIBO_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@RECIBO_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@RECIBO_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@RECIBO_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@RECIBO_FECHAEXPO_DESDE datetime,
	@RECIBO_FECHAEXPO_HASTA datetime,
	@RECIBO_FECHAIMPO_DESDE datetime,
	@RECIBO_FECHAIMPO_HASTA datetime,
	@RECIBO_FECHAMODIFICACIONFW_DESDE datetime,
	@RECIBO_FECHAMODIFICACIONFW_HASTA datetime,
	@RECIBO_FECHATRANSFERENCIA_DESDE datetime,
	@RECIBO_FECHATRANSFERENCIA_HASTA datetime,
	@RECIBO_HORAEXPO_DESDE varchar(8),
	@RECIBO_HORAEXPO_HASTA varchar(8),
	@RECIBO_HORAIMPO_DESDE varchar(8),
	@RECIBO_HORAIMPO_HASTA varchar(8),
	@RECIBO_HORAMODIFICACIONFW_DESDE varchar(8),
	@RECIBO_HORAMODIFICACIONFW_HASTA varchar(8),
	@RECIBO_SERIEALTAFW_DESDE varchar(7),
	@RECIBO_SERIEALTAFW_HASTA varchar(7),
	@RECIBO_SERIEMODIFICACIONFW_DESDE varchar(7),
	@RECIBO_SERIEMODIFICACIONFW_HASTA varchar(7),
	@RECIBO_USUARIOALTAFW_DESDE varchar(100),
	@RECIBO_USUARIOALTAFW_HASTA varchar(100),
	@RECIBO_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@RECIBO_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@RECIBO_VERSIONALTAFW_DESDE varchar(13),
	@RECIBO_VERSIONALTAFW_HASTA varchar(13),
	@RECIBO_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@RECIBO_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemvalores.jjnum, 38, ' ' ) as varchar( 46 ) ) as ITEMVALORES__Grupo,
	@basededatos as ITEMVALORES__BD,
	c_ITEMVALORES.JJNUM as ITEMVALORES_JJNUM,
	case when c_itemvalores.jjfe = '01/01/1900 00:00:00' then null else c_itemvalores.jjfe end as ITEMVALORES_JJFE,
	case when c_itemvalores.jjfecha = '01/01/1900 00:00:00' then null else c_itemvalores.jjfecha end as ITEMVALORES_JJfecha,
	cast( power(-1, c_itemvalores.signo)*c_itemvalores.jjm as numeric( 15, 2 ) ) as ITEMVALORES_JJM,
	c_ITEMVALORES.NROCHEQUE as ITEMVALORES_NroCheque,
	c_ITEMVALORES.NROINTERNO as ITEMVALORES_NroInterno,
	cast( power(-1, c_itemvalores.signo)*c_itemvalores.pesos as numeric( 15, 2 ) ) as ITEMVALORES_Pesos,
	c_ITEMVALORES.JJCO as ITEMVALORES_JJCO,
	c_ITEMVALORES.JJDE as ITEMVALORES_JJDE,
	case when c_itemvalores.fechcoti = '01/01/1900 00:00:00' then null else c_itemvalores.fechcoti end as ITEMVALORES_FechCoti,
	c_ITEMVALORES.COTIZA as ITEMVALORES_Cotiza,
	c_ITEMVALORES.PORCDESREC as ITEMVALORES_porcdesrec,
	c_ITEMVALORES.MONDESREC as ITEMVALORES_mondesrec,
	c_ITEMVALORES.ESVUELTO as ITEMVALORES_esvuelto,
	cast( power(-1, c_itemvalores.signo)*c_itemvalores.jjrecib as numeric( 15, 2 ) ) as ITEMVALORES_JJRecib,
	cast( power(-1, c_itemvalores.signo)*c_itemvalores.recpesos as numeric( 15, 2 ) ) as ITEMVALORES_RecPesos,
	cast( power(-1, c_itemvalores.signo)*c_itemvalores.montosiste as numeric( 15, 2 ) ) as ITEMVALORES_Montosiste,
	c_ITEMVALORES.NROITEM as ITEMVALORES_NroItem,
	cast( ' ' as varchar( 254 ) ) as ITEMVALORES_1_ResumenValorVirtual,
	C_CHEQUE.COBSS as CHEQUE_cObss,
	C_VALOR.CLNOM as VALOR_CLNOM,
	C_CHEQUE.CCOD as CHEQUE_cCod,
	C_VALOR.CLCOD as VALOR_CLCOD
 from ZooLogic.VAL as c_ITEMVALORES
 --
 left join Listados.Vista_InformacionDeValores as C_INFOVALOR on C_INFOVALOR.IDITEM = c_ITEMVALORES.IDITEM
 --
 left join ZooLogic.CHEQUE as C_CHEQUE on C_CHEQUE.CCOD = C_ITEMVALORES.NROCHEQUE and 0 = Funciones.empty( C_ITEMVALORES.NROCHEQUE )
 left join ZooLogic.XVAL as C_VALOR on C_VALOR.CLCOD = C_ITEMVALORES.JJCO and 0 = Funciones.empty( C_ITEMVALORES.JJCO )
 inner join ZooLogic.RECIBO as C_RECIBO_CABECERA on C_RECIBO_CABECERA.CODIGO = C_ITEMVALORES.JJNUM
 left join ZooLogic.CLI as C_CLIENTE_CABECERA on C_CLIENTE_CABECERA.CLCOD = C_RECIBO_CABECERA.FPERSON and 0 = Funciones.empty( C_RECIBO_CABECERA.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO_CABECERA on C_CONDICIONDEPAGO_CABECERA.CLCOD = C_CLIENTE_CABECERA.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB_CABECERA on C_DATOSADICIONALESSIPRIB_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO_CABECERA on C_DESCUENTO_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO61_CABECERA on C_IMPUESTO61_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO64_CABECERA on C_IMPUESTO64_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLPERGAN and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS_CABECERA on C_LISTADEPRECIOS_CABECERA.LPR_NUMERO = C_CLIENTE_CABECERA.CLLISPREC and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLLISPREC )
 left join ZooLogic.MONEDA as C_MONEDA_CABECERA on C_MONEDA_CABECERA.CODIGO = C_RECIBO_CABECERA.MONEDA and 0 = Funciones.empty( C_RECIBO_CABECERA.MONEDA )
 left join ZooLogic.PAISES as C_PAISES_CABECERA on C_PAISES_CABECERA.PCOD = C_CLIENTE_CABECERA.CLPAIS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA_CABECERA on C_PROVINCIA_CABECERA.PRV_COD = C_CLIENTE_CABECERA.CLPRV and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL_CABECERA on C_SITUACIONFISCAL_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLIVA and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL_CABECERA on C_SUCURSAL_CABECERA.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE_CABECERA on C_TIPOCLIENTE_CABECERA.TCCOD = C_CLIENTE_CABECERA.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL_CABECERA on C_TIPOSUCURSAL_CABECERA.TCOD = C_SUCURSAL_CABECERA.TIPO and 0 = Funciones.empty( C_SUCURSAL_CABECERA.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA_CABECERA on C_TRANSPORTISTA_CABECERA.TRCOD = C_CLIENTE_CABECERA.CLTRANS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR22_CABECERA on C_VENDEDOR22_CABECERA.CLCOD = C_CLIENTE_CABECERA.CLVEND and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLVEND )
 left join ZooLogic.VEN as C_VENDEDOR77_CABECERA on C_VENDEDOR77_CABECERA.CLCOD = C_RECIBO_CABECERA.FVEN and 0 = Funciones.empty( C_RECIBO_CABECERA.FVEN )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA_CABECERA on C_NOMBREDEFANTASIA_CABECERA.NFCOD = C_CLIENTE_CABECERA.CLCODFANT and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE_CABECERA on C_CATEGORIACLIENTE_CABECERA.CGCOD = C_CLIENTE_CABECERA.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE_CABECERA on C_CLASIFICACIONCLIENTE_CABECERA.CLACOD = C_CLIENTE_CABECERA.CLCLAS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCLAS )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL_CABECERA on C_LINEASUCURSAL_CABECERA.LSCOD = C_SUCURSAL_CABECERA.LINEA and 0 = Funciones.empty( C_SUCURSAL_CABECERA.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION_CABECERA on C_SEGMENTACION_CABECERA.SCOD = C_SUCURSAL_CABECERA.SEG and 0 = Funciones.empty( C_SUCURSAL_CABECERA.SEG )
 where ( not 1 = funciones.empty( c_recibo_cabecera.codigo ) and c_recibo_cabecera.facttipo = 13 ) and 
	( ( @RECIBO_CLIENTE_DESDE is null ) OR ( C_RECIBO_CABECERA.FPerson >= @RECIBO_CLIENTE_DESDE ) ) and 
	( ( @RECIBO_CLIENTE_HASTA is null ) OR ( C_RECIBO_CABECERA.FPerson <= @RECIBO_CLIENTE_HASTA ) ) and 
	( ( @RECIBO_VENDEDOR_DESDE is null ) OR ( C_RECIBO_CABECERA.FVEN >= @RECIBO_VENDEDOR_DESDE ) ) and 
	( ( @RECIBO_VENDEDOR_HASTA is null ) OR ( C_RECIBO_CABECERA.FVEN <= @RECIBO_VENDEDOR_HASTA ) ) and 
	( ( @RECIBO_MONEDACOMPROBANTE_DESDE is null ) OR ( C_RECIBO_CABECERA.Moneda >= @RECIBO_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @RECIBO_MONEDACOMPROBANTE_HASTA is null ) OR ( C_RECIBO_CABECERA.Moneda <= @RECIBO_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @RECIBO_CLIENTEDESCRIPCION_DESDE is null ) OR ( C_RECIBO_CABECERA.FCLIENTE >= @RECIBO_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @RECIBO_CLIENTEDESCRIPCION_HASTA is null ) OR ( C_RECIBO_CABECERA.FCLIENTE <= @RECIBO_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @RECIBO_LETRA_DESDE is null ) OR ( C_RECIBO_CABECERA.FLETRA >= @RECIBO_LETRA_DESDE ) ) and 
	( ( @RECIBO_LETRA_HASTA is null ) OR ( C_RECIBO_CABECERA.FLETRA <= @RECIBO_LETRA_HASTA ) ) and 
	( ( @RECIBO_PUNTODEVENTA_DESDE is null ) OR ( C_RECIBO_CABECERA.FPTOVEN >= @RECIBO_PUNTODEVENTA_DESDE ) ) and 
	( ( @RECIBO_PUNTODEVENTA_HASTA is null ) OR ( C_RECIBO_CABECERA.FPTOVEN <= @RECIBO_PUNTODEVENTA_HASTA ) ) and 
	( ( @RECIBO_NUMERO_DESDE is null ) OR ( C_RECIBO_CABECERA.FNUMCOMP >= @RECIBO_NUMERO_DESDE ) ) and 
	( ( @RECIBO_NUMERO_HASTA is null ) OR ( C_RECIBO_CABECERA.FNUMCOMP <= @RECIBO_NUMERO_HASTA ) ) and 
	( ( @RECIBO_FECHA_DESDE is null ) OR ( C_RECIBO_CABECERA.FFCH >= @RECIBO_FECHA_DESDE ) ) and 
	( ( @RECIBO_FECHA_HASTA is null ) OR ( C_RECIBO_CABECERA.FFCH <= @RECIBO_FECHA_HASTA ) ) and 
	( ( @RECIBO_TOTAL_DESDE is null ) OR ( C_RECIBO_CABECERA.FTotal >= @RECIBO_TOTAL_DESDE ) ) and 
	( ( @RECIBO_TOTAL_HASTA is null ) OR ( C_RECIBO_CABECERA.FTotal <= @RECIBO_TOTAL_HASTA ) ) and 
	( ( @CLIENTE_21_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNOM >= @CLIENTE_21_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_21_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNOM <= @CLIENTE_21_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @VENDEDOR_77_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR77_CABECERA.CLNOM >= @VENDEDOR_77_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_77_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR77_CABECERA.CLNOM <= @VENDEDOR_77_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @MONEDA_78_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA_CABECERA.Descrip >= @MONEDA_78_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_78_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA_CABECERA.Descrip <= @MONEDA_78_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION_CABECERA.SDES >= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION_CABECERA.SDES <= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES >= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES <= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES >= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES <= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_22_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR22_CABECERA.CLNOM >= @VENDEDOR_22_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_22_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR22_CABECERA.CLNOM <= @VENDEDOR_22_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_37_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES_CABECERA.pdes >= @PAISES_37_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_37_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES_CABECERA.pdes <= @PAISES_37_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_39_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA_CABECERA.PRV_DES >= @PROVINCIA_39_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_39_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA_CABECERA.PRV_DES <= @PROVINCIA_39_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_45_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_45_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_45_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_45_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_46_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE_CABECERA.CLADES >= @CLASIFICACIONCLIENTE_46_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_46_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE_CABECERA.CLADES <= @CLASIFICACIONCLIENTE_46_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_49_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO_CABECERA.Des >= @DESCUENTO_49_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_49_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO_CABECERA.Des <= @DESCUENTO_49_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_50_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA_CABECERA.TRNOM >= @TRANSPORTISTA_50_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_50_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA_CABECERA.TRNOM <= @TRANSPORTISTA_50_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_56_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA_CABECERA.NFCOD >= @NOMBREDEFANTASIA_56_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_56_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA_CABECERA.NFCOD <= @NOMBREDEFANTASIA_56_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_57_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE_CABECERA.TCDES >= @TIPOCLIENTE_57_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_57_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE_CABECERA.TCDES <= @TIPOCLIENTE_57_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_58_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE_CABECERA.CGDes >= @CATEGORIACLIENTE_58_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_58_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE_CABECERA.CGDes <= @CATEGORIACLIENTE_58_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_59_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO_CABECERA.CLNOM >= @CONDICIONDEPAGO_59_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_59_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO_CABECERA.CLNOM <= @CONDICIONDEPAGO_59_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_61_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO61_CABECERA.descrip >= @IMPUESTO_61_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_61_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO61_CABECERA.descrip <= @IMPUESTO_61_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_64_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO64_CABECERA.descrip >= @IMPUESTO_64_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_64_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO64_CABECERA.descrip <= @IMPUESTO_64_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_73_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip >= @DATOSADICIONALESSIPRIB_73_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_73_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip <= @DATOSADICIONALESSIPRIB_73_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.seg >= @SUCURSAL_9144_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.seg <= @SUCURSAL_9144_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9144_LINEA_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Linea >= @SUCURSAL_9144_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9144_LINEA_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Linea <= @SUCURSAL_9144_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9144_TIPO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Tipo >= @SUCURSAL_9144_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9144_TIPO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Tipo <= @SUCURSAL_9144_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.descrip >= @SUCURSAL_9144_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.descrip <= @SUCURSAL_9144_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_21_VENDEDOR_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLVend >= @CLIENTE_21_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_21_VENDEDOR_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLVend <= @CLIENTE_21_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_21_CALLE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCalle >= @CLIENTE_21_CALLE_DESDE ) ) and 
	( ( @CLIENTE_21_CALLE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCalle <= @CLIENTE_21_CALLE_HASTA ) ) and 
	( ( @CLIENTE_21_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCP >= @CLIENTE_21_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_21_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCP <= @CLIENTE_21_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_21_CUIT_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCUIT >= @CLIENTE_21_CUIT_DESDE ) ) and 
	( ( @CLIENTE_21_CUIT_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCUIT <= @CLIENTE_21_CUIT_HASTA ) ) and 
	( ( @CLIENTE_21_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLDEPTO >= @CLIENTE_21_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_21_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLDEPTO <= @CLIENTE_21_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_21_EMAIL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLEMAIL >= @CLIENTE_21_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_21_EMAIL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLEMAIL <= @CLIENTE_21_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_21_FAX_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLFAX >= @CLIENTE_21_FAX_DESDE ) ) and 
	( ( @CLIENTE_21_FAX_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLFAX <= @CLIENTE_21_FAX_HASTA ) ) and 
	( ( @CLIENTE_21_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLFECHA >= @CLIENTE_21_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_21_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLFECHA <= @CLIENTE_21_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_21_IMAGEN_DESDE is null ) OR ( C_CLIENTE_CABECERA.CIMAGEN >= @CLIENTE_21_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_21_IMAGEN_HASTA is null ) OR ( C_CLIENTE_CABECERA.CIMAGEN <= @CLIENTE_21_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_21_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLLOC >= @CLIENTE_21_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_21_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLLOC <= @CLIENTE_21_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_21_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNRODOC >= @CLIENTE_21_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_21_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNRODOC <= @CLIENTE_21_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_21_NUMERO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNro >= @CLIENTE_21_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_21_NUMERO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNro <= @CLIENTE_21_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_21_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPAGEWEB >= @CLIENTE_21_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_21_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPAGEWEB <= @CLIENTE_21_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_21_PAIS_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPAIS >= @CLIENTE_21_PAIS_DESDE ) ) and 
	( ( @CLIENTE_21_PAIS_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPAIS <= @CLIENTE_21_PAIS_HASTA ) ) and 
	( ( @CLIENTE_21_PISO_DESDE is null ) OR ( C_CLIENTE_CABECERA.ClPiso >= @CLIENTE_21_PISO_DESDE ) ) and 
	( ( @CLIENTE_21_PISO_HASTA is null ) OR ( C_CLIENTE_CABECERA.ClPiso <= @CLIENTE_21_PISO_HASTA ) ) and 
	( ( @CLIENTE_21_PROVINCIA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPRV >= @CLIENTE_21_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_21_PROVINCIA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPRV <= @CLIENTE_21_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_40_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL_CABECERA.Descrip = @SITUACIONFISCAL_40_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_21_TELEFONO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTLF >= @CLIENTE_21_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_21_TELEFONO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTLF <= @CLIENTE_21_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_21_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTIPODOC >= @CLIENTE_21_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_21_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTIPODOC <= @CLIENTE_21_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_21_MOVIL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLMovil >= @CLIENTE_21_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_21_MOVIL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLMovil <= @CLIENTE_21_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_21_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTOPECCTE >= @CLIENTE_21_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_21_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTOPECCTE <= @CLIENTE_21_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_21_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLLisPrec >= @CLIENTE_21_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_21_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLLisPrec <= @CLIENTE_21_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_21_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCLAS >= @CLIENTE_21_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_21_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCLAS <= @CLIENTE_21_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_21_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTIPCONV >= @CLIENTE_21_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_21_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTIPCONV <= @CLIENTE_21_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_21_NROIIBB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNROIIBB >= @CLIENTE_21_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_21_NROIIBB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNROIIBB <= @CLIENTE_21_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_21_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCO_DTO >= @CLIENTE_21_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_21_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCO_DTO <= @CLIENTE_21_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_21_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTRANS >= @CLIENTE_21_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_21_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTRANS <= @CLIENTE_21_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_21_ESTADOCIVIL is null ) OR ( C_CLIENTE_CABECERA.Estado = @CLIENTE_21_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_21_HIJOS_DESDE is null ) OR ( C_CLIENTE_CABECERA.Hijos >= @CLIENTE_21_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_21_HIJOS_HASTA is null ) OR ( C_CLIENTE_CABECERA.Hijos <= @CLIENTE_21_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_21_SEXO is null ) OR ( C_CLIENTE_CABECERA.Sexo = @CLIENTE_21_SEXO ) ) and 
	( ( @CLIENTE_21_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE_CABECERA.globalid >= @CLIENTE_21_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_21_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE_CABECERA.globalid <= @CLIENTE_21_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_21_RUT_DESDE is null ) OR ( C_CLIENTE_CABECERA.RUT >= @CLIENTE_21_RUT_DESDE ) ) and 
	( ( @CLIENTE_21_RUT_HASTA is null ) OR ( C_CLIENTE_CABECERA.RUT <= @CLIENTE_21_RUT_HASTA ) ) and 
	( ( @CLIENTE_21_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCODFANT >= @CLIENTE_21_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_21_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCODFANT <= @CLIENTE_21_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_21_TIPOCLI_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTipoCli >= @CLIENTE_21_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_21_TIPOCLI_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTipoCli <= @CLIENTE_21_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_21_CATEGCLI_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCategCli >= @CLIENTE_21_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_21_CATEGCLI_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCategCli <= @CLIENTE_21_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_21_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCONDPAG >= @CLIENTE_21_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_21_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCONDPAG <= @CLIENTE_21_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_21_SUJETOVINCULADO is null ) OR ( C_CLIENTE_CABECERA.CLSujVinc = @CLIENTE_21_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_21_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPERTIVA >= @CLIENTE_21_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_21_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPERTIVA <= @CLIENTE_21_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_21_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE_CABECERA.CLSITGAN = @CLIENTE_21_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_21_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE_CABECERA.EXPERIVA = @CLIENTE_21_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_21_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPERGAN >= @CLIENTE_21_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_21_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPERGAN <= @CLIENTE_21_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_21_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE_CABECERA.EXPERGAN = @CLIENTE_21_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_21_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CODRECOM >= @CLIENTE_21_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_21_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CODRECOM <= @CLIENTE_21_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_21_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.NOMRECOM >= @CLIENTE_21_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_21_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.NOMRECOM <= @CLIENTE_21_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_21_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPRINOM >= @CLIENTE_21_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_21_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPRINOM <= @CLIENTE_21_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_21_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLSEGNOM >= @CLIENTE_21_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_21_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLSEGNOM <= @CLIENTE_21_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_21_APELLIDO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLAPELL >= @CLIENTE_21_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_21_APELLIDO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLAPELL <= @CLIENTE_21_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_21_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE_CABECERA.VHastaIva >= @CLIENTE_21_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_21_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE_CABECERA.VHastaIva <= @CLIENTE_21_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_21_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE_CABECERA.VHastaGan >= @CLIENTE_21_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_21_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE_CABECERA.VHastaGan <= @CLIENTE_21_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_21_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLSIPRIB >= @CLIENTE_21_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_21_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLSIPRIB <= @CLIENTE_21_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_21_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE_CABECERA.PorcenTC >= @CLIENTE_21_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_21_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE_CABECERA.PorcenTC <= @CLIENTE_21_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_21_TASACEROAPLICA is null ) OR ( C_CLIENTE_CABECERA.AplicaTC = @CLIENTE_21_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_21_INACTIVOFW is null ) OR ( C_CLIENTE_CABECERA.InactivoFW = @CLIENTE_21_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9144_CODIGO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.codigo >= @SUCURSAL_9144_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9144_CODIGO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.codigo <= @SUCURSAL_9144_CODIGO_HASTA ) ) and 
	( ( @RECIBO_FECHAALTAFW_DESDE is null ) OR ( C_RECIBO_CABECERA.FAltaFW >= @RECIBO_FECHAALTAFW_DESDE ) ) and 
	( ( @RECIBO_FECHAALTAFW_HASTA is null ) OR ( C_RECIBO_CABECERA.FAltaFW <= @RECIBO_FECHAALTAFW_HASTA ) ) and 
	( ( @RECIBO_HORAALTAFW_DESDE is null ) OR ( C_RECIBO_CABECERA.HAltaFW >= @RECIBO_HORAALTAFW_DESDE ) ) and 
	( ( @RECIBO_HORAALTAFW_HASTA is null ) OR ( C_RECIBO_CABECERA.HAltaFW <= @RECIBO_HORAALTAFW_HASTA ) ) and 
	( ( @RECIBO_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_RECIBO_CABECERA.BDALTAFW >= @RECIBO_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @RECIBO_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_RECIBO_CABECERA.BDALTAFW <= @RECIBO_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @RECIBO_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_RECIBO_CABECERA.BDMODIFW >= @RECIBO_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @RECIBO_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_RECIBO_CABECERA.BDMODIFW <= @RECIBO_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @RECIBO_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_RECIBO_CABECERA.ESTTRANS >= @RECIBO_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @RECIBO_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_RECIBO_CABECERA.ESTTRANS <= @RECIBO_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @RECIBO_FECHAEXPO_DESDE is null ) OR ( C_RECIBO_CABECERA.FECEXPO >= @RECIBO_FECHAEXPO_DESDE ) ) and 
	( ( @RECIBO_FECHAEXPO_HASTA is null ) OR ( C_RECIBO_CABECERA.FECEXPO <= @RECIBO_FECHAEXPO_HASTA ) ) and 
	( ( @RECIBO_FECHAIMPO_DESDE is null ) OR ( C_RECIBO_CABECERA.FECIMPO >= @RECIBO_FECHAIMPO_DESDE ) ) and 
	( ( @RECIBO_FECHAIMPO_HASTA is null ) OR ( C_RECIBO_CABECERA.FECIMPO <= @RECIBO_FECHAIMPO_HASTA ) ) and 
	( ( @RECIBO_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_RECIBO_CABECERA.FMODIFW >= @RECIBO_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @RECIBO_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_RECIBO_CABECERA.FMODIFW <= @RECIBO_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @RECIBO_FECHATRANSFERENCIA_DESDE is null ) OR ( C_RECIBO_CABECERA.FECTRANS >= @RECIBO_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @RECIBO_FECHATRANSFERENCIA_HASTA is null ) OR ( C_RECIBO_CABECERA.FECTRANS <= @RECIBO_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @RECIBO_HORAEXPO_DESDE is null ) OR ( C_RECIBO_CABECERA.HORAEXPO >= @RECIBO_HORAEXPO_DESDE ) ) and 
	( ( @RECIBO_HORAEXPO_HASTA is null ) OR ( C_RECIBO_CABECERA.HORAEXPO <= @RECIBO_HORAEXPO_HASTA ) ) and 
	( ( @RECIBO_HORAIMPO_DESDE is null ) OR ( C_RECIBO_CABECERA.HORAIMPO >= @RECIBO_HORAIMPO_DESDE ) ) and 
	( ( @RECIBO_HORAIMPO_HASTA is null ) OR ( C_RECIBO_CABECERA.HORAIMPO <= @RECIBO_HORAIMPO_HASTA ) ) and 
	( ( @RECIBO_HORAMODIFICACIONFW_DESDE is null ) OR ( C_RECIBO_CABECERA.HMODIFW >= @RECIBO_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @RECIBO_HORAMODIFICACIONFW_HASTA is null ) OR ( C_RECIBO_CABECERA.HMODIFW <= @RECIBO_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @RECIBO_SERIEALTAFW_DESDE is null ) OR ( C_RECIBO_CABECERA.SALTAFW >= @RECIBO_SERIEALTAFW_DESDE ) ) and 
	( ( @RECIBO_SERIEALTAFW_HASTA is null ) OR ( C_RECIBO_CABECERA.SALTAFW <= @RECIBO_SERIEALTAFW_HASTA ) ) and 
	( ( @RECIBO_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_RECIBO_CABECERA.SMODIFW >= @RECIBO_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @RECIBO_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_RECIBO_CABECERA.SMODIFW <= @RECIBO_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @RECIBO_USUARIOALTAFW_DESDE is null ) OR ( C_RECIBO_CABECERA.UALTAFW >= @RECIBO_USUARIOALTAFW_DESDE ) ) and 
	( ( @RECIBO_USUARIOALTAFW_HASTA is null ) OR ( C_RECIBO_CABECERA.UALTAFW <= @RECIBO_USUARIOALTAFW_HASTA ) ) and 
	( ( @RECIBO_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_RECIBO_CABECERA.UMODIFW >= @RECIBO_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @RECIBO_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_RECIBO_CABECERA.UMODIFW <= @RECIBO_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @RECIBO_VERSIONALTAFW_DESDE is null ) OR ( C_RECIBO_CABECERA.VALTAFW >= @RECIBO_VERSIONALTAFW_DESDE ) ) and 
	( ( @RECIBO_VERSIONALTAFW_HASTA is null ) OR ( C_RECIBO_CABECERA.VALTAFW <= @RECIBO_VERSIONALTAFW_HASTA ) ) and 
	( ( @RECIBO_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_RECIBO_CABECERA.VMODIFW >= @RECIBO_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @RECIBO_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_RECIBO_CABECERA.VMODIFW <= @RECIBO_VERSIONMODIFICACIONFW_HASTA ) )

)