IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[VAL_ITEMVALORESAENT]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[VAL_ITEMVALORESAENT];
GO;

CREATE FUNCTION [Listados].[VAL_ITEMVALORESAENT]
(
	@ITEMVALORES_FECHA_DESDE datetime,
	@ITEMVALORES_FECHA_HASTA datetime
)
RETURNS TABLE
AS
RETURN
(
select
	c_CANJEDECUPONESAENT.FALTAFW + convert( datetime, c_CANJEDECUPONESAENT.HALTAFW) as MARCATEMPORAL,
	3 as ORDEN,
	c_ITEMVALORESAENT.COTIZA,
	c_ITEMVALORESAENT.CUPON,
	c_ITEMVALORESAENT.FECHCOTI,
	c_ITEMVALORESAENT.CUPON as GUIDCUPON,
	c_ITEMVALORESAENT.IDCAJA,
	c_ITEMVALORESAENT.JJCO,
	c_ITEMVALORESAENT.JJCOTIZ,
	c_ITEMVALORESAENT.JJDE,
	c_CANJEDECUPONESAENT.FECHA as JJFE,
	c_CANJEDECUPONESAENT.FECHA as JJFECHA,
	c_ITEMVALORESAENT.JJM,
	c_CANJEDECUPONESAENT.CODIGO as JJNUM,
	c_CANJEDECUPONESAENT.FACTTIPO as JJT,
	c_ITEMVALORESAENT.JJTOTFAC,
	c_ITEMVALORESAENT.JJTOTFAC as JJRECIB,
	cast(0 as numeric(1, 0)) as JJTURNO,
	c_CANJEDECUPONESAENT.VENDEDOR as JJVEN,
	c_CANJEDECUPONESAENT.FLETRA as LETRA,
	c_ITEMVALORESAENT.NROCHEQUE,
	c_ITEMVALORESAENT.NROCHPROP,
	cast('' as varchar(10)) as NRODOC,
	c_ITEMVALORESAENT.NROINTERNO,
	c_ITEMVALORESAENT.NROITEM,
	c_CANJEDECUPONESAENT.NUMERO as NUMCOMPR,
	cast(0 as bit) as PERMVUELTO,
	cast(0 as bit) as PERSCOMP,
	c_ITEMVALORESAENT.PESOS,
	c_ITEMVALORESAENT.MONTOSISTE,
	c_ITEMVALORESAENT.PESOS as RECPESOS,
	c_CANJEDECUPONESAENT.FPTOVEN as PTOVENTA,
	cast(0 as numeric(12, 2)) as RECMONTO,
	cast(0 as numeric(6, 2)) as RECPORC,
	cast(0 as numeric(12, 2)) as RECSINIMP,
	cast(0 as numeric(12, 2)) as RECSINPER,
	cast('' as varchar(10)) as REDONDEO,
	c_ITEMVALORESAENT.SIGNO,
	upper(c_ITEMVALORESAENT.TIPCOMP) as TIPCOMP,
	c_ITEMVALORESAENT.TIPO as TIPODOC,
	cast('' as char(38)) as VALECAMBIO,
	c_ITEMVALORESAENT.AUTORIZADO,
	c_ITEMVALORESAENT.CODIGO as IDITEM,
	cast(0 as numeric(12, 2)) as DESCMONTO,
	cast(0 as numeric(6, 2)) as DESCPORC,
	cast(0 as numeric(15, 2)) as DESCSINIMP,
	cast(0 as numeric(12, 2)) as MONDESPES,
	cast(0 as numeric(12, 2)) as MONDESREC,
	cast(0 as numeric(12, 2)) as MONRECPES,
	cast(0 as numeric(6, 2 )) as PORCDESREC,
	cast(0 as bit) as EsVuelto,
	c_CANJEDECUPONESAENT.faltafw,
	c_CANJEDECUPONESAENT.HALTAFW,
	c_CANJEDECUPONESAENT.BDALTAFW,
	c_CANJEDECUPONESAENT.BDMODIFW,
	c_CANJEDECUPONESAENT.ESTTRANS,
	c_CANJEDECUPONESAENT.fecexpo,
	c_CANJEDECUPONESAENT.fecimpo, 
	c_CANJEDECUPONESAENT.fmodifw,
	c_CANJEDECUPONESAENT.fectrans,
	c_CANJEDECUPONESAENT.HORAEXPO,
	c_CANJEDECUPONESAENT.HORAIMPO,
	c_CANJEDECUPONESAENT.HMODIFW,
	c_CANJEDECUPONESAENT.SALTAFW, 
	c_CANJEDECUPONESAENT.SMODIFW, 
	c_CANJEDECUPONESAENT.UALTAFW, 
	c_CANJEDECUPONESAENT.UMODIFW, 
	c_CANJEDECUPONESAENT.VALTAFW, 
	c_CANJEDECUPONESAENT.VMODIFW, 
	c_CANJEDECUPONESAENT.ZADSFW 
from ZooLogic.CANJECUPONESENT as c_ITEMVALORESAENT
	left join ZooLogic.CANJECUPONES as c_CANJEDECUPONESAENT on c_CANJEDECUPONESAENT.CODIGO = c_ITEMVALORESAENT.CODIGO
where ( c_CANJEDECUPONESAENT.ANULADO = 0 ) and
	( ( @ITEMVALORES_FECHA_DESDE is null ) OR ( c_CANJEDECUPONESAENT.FECHA >= @ITEMVALORES_FECHA_DESDE ) ) and 
	( ( @ITEMVALORES_FECHA_HASTA is null ) OR ( c_CANJEDECUPONESAENT.FECHA <= @ITEMVALORES_FECHA_HASTA ) )
)