IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[VistaIntegraValores]') AND type = N'V')
	DROP VIEW [Listados].[VistaIntegraValores];
GO;

CREATE VIEW [Listados].[VistaIntegraValores] AS
(
select
	Valores.Origen,
	Valores.JJNUM,
	Valores.JJCotiz,
	Valores.JJFE,
	Valores.JJfecha,
	Valores.Letra,
	Valores.JJM as JJM,
	Valores.NroDoc,
	Valores.NroItem,
	Valores.NroCheque,
	Valores.NroCupon,
	Valores.NroInterno,
	Valores.NroTarjeta,
	Valores.NumCompr,
	Valores.Pesos as Pesos,
	Valores.PtoVenta,
	Valores.Signo,
	Valores.JJT,
	Valores.TipoDoc,
	Valores.TIPCOMP,
	Valores.JJTotFac as JJTotFac,
	Valores.JJTurno,
	Valores.JJCO,
	Valores.JJDE,
	Valores.JJVen,
	Valores.JJRecib,
	Valores.FechCoti,
	Valores.Cotiza,
	Valores.recporc,
	Valores.recsinimp as recsinimp,
	Valores.recsinper as recsinper,
	Valores.ValeCambio,
	Valores.IdCaja,
	Valores.NroChProp,
	Valores.CondPago,
	Valores.ESVUELTO 
from
	(
		select
			'VENTAS'																as Origen,	--Indica el origen del registro
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM * power( -1, SIGNO )												as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS * power( -1, SIGNO )												as Pesos,
			PTOVENTA 																as PtoVenta,
			power( -1, SIGNO )														as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC * power( -1, SIGNO )											as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			JJRecib * power( -1, SIGNO )											as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			RECPORC 																as recporc,
			RECSINIMP * power( -1, SIGNO )											as recsinimp,
			RECSINPER * power( -1, SIGNO )											as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			CONDPAGO 																as CondPago,
			ESVUELTO																as ESVUELTO 
		from ZooLogic.VAL
		union all
		select
			'COMPRAS_FC'															as Origen,
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM * power( -1, SIGNO )												as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS * power( -1, SIGNO )													as Pesos,
			PTOVENTA 																as PtoVenta,
			power( -1, SIGNO )														as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC * power( -1, SIGNO )											as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			0		 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			JRECPORC 																as recporc,
			JRECMNTSI * power( -1, SIGNO )											as recsinimp,
			JRRECSPERC * power( -1, SIGNO )											as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			CONDPAGO 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.VALFACCOMP
		union all
		select
			'COMPRAS_NC'															as Origen,
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM * power( -1, SIGNO )												as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS * power( -1, SIGNO )													as Pesos,
			PTOVENTA 																as PtoVenta,
			power( -1, SIGNO )														as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC * power( -1, SIGNO )											as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			0		 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			JRECPORC 																as recporc,
			JRECMNTSI * power( -1, SIGNO )											as recsinimp,
			JRRECSPERC * power( -1, SIGNO )											as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			CONDPAGO 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.VALNCCOMP
		union all
		select
			'COMPRAS_ND'															as Origen,
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM * power( -1, SIGNO )												as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS * power( -1, SIGNO )												as Pesos,
			PTOVENTA 																as PtoVenta,
			power( -1, SIGNO )														as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC * power( -1, SIGNO )											as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			0		 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			JRECPORC 																as recporc,
			JRECMNTSI * power( -1, SIGNO )											as recsinimp,
			JRRECSPERC * power( -1, SIGNO )											as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			CONDPAGO 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.VALNDCOMP
		union all
		select
			'PAGOS'																	as Origen,
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM * power( -1, SIGNO )												as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS * power( -1, SIGNO )												as Pesos,
			PTOVENTA 																as PtoVenta,
			power( -1, SIGNO )														as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC * power( -1, SIGNO )											as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			0		 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			JRECPORC 																as recporc,
			JRECMNTSI * power( -1, SIGNO )											as recsinimp,
			JRRECSPERC * power( -1, SIGNO )											as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			null	 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.PAGOVAL
		union all
		select
			'CAJA'																	as Origen,
			CODDETVAL																as JJNUM,
			COTIZA	 																as JJCotiz,
			case when FECHA = '01/01/1900 00:00:00' then null else FECHA end 		as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			null 																	as Letra,
			MONTO																	as JJM,
			null 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE	 															as NroCheque,
			null	 																as NroCupon,
			NROINTERNO 																as NroInterno,
			null	 																as NroTarjeta,
			null	 																as NumCompr,
			COTIZA * CTOTAL															as Pesos,
			null 																	as PtoVenta,
			1																		as Signo,
			TIPO 																	as JJT,
			null																	as TipoDoc,
			null	 																as TIPCOMP,
			null 																	as JJTotFac,
			null 																	as JJTurno,
			CODVAL 																	as JJCO,
			DESCRIP																	as JJDE,
			null 																	as JJVen,
			0		 																as JJRecib,
			null																 	as FechCoti,
			COTIZA 																	as Cotiza,
			null 																	as recporc,
			null	  																as recsinimp,
			null	 																as recsinper,
			null 																	as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			null	 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.COMPCAJADET
		union all


		select
			'CANJEVALORES'															as Origen,
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM																		as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS																	as Pesos,
			PTOVENTA 																as PtoVenta,
			1	 																	as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC 																as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			PESOS	 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			JRECPORC 																as recporc,
			JRECMNTSI  																as recsinimp,
			JRRECSPERC 																as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			null	 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.CANJECUPONESDET
		union all
		select
			'CANJEVALORES'															as Origen,
			codigo 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM																		as JJM,
			'' 																		as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS																	as Pesos,
			0	 																	as PtoVenta,
			-1 																		as Signo,
			JJT 																	as JJT,
			''	 																	as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC																as JJTotFac,
			null 																	as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			''	 																	as JJVen,
			PESOS	 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			null	 																as recporc,
			null	  																as recsinimp,
			null	 																as recsinper,
			null 																	as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			null	 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.CANJECUPONESENT

		union all

		select
			'OTROSPAGOS'															as Origen,
			JJNUM 																	as JJNUM,
			JJCOTIZ 																as JJCotiz,
			case when jjfe = '01/01/1900 00:00:00' then null else jjfe end 			as JJFE,
			case when jjfecha = '01/01/1900 00:00:00' then null else jjfecha end 	as JJfecha,
			LETRA 																	as Letra,
			JJM * power( -1, SIGNO )												as JJM,
			NRODOC 																	as NroDoc,
			NROITEM 																as NroItem,
			NROCHEQUE 																as NroCheque,
			NROCUPON 																as NroCupon,
			NROINTERNO 																as NroInterno,
			NROTARJETA 																as NroTarjeta,
			NUMCOMPR 																as NumCompr,
			PESOS * power( -1, SIGNO )												as Pesos,
			PTOVENTA 																as PtoVenta,
			power( -1, SIGNO )														as Signo,
			JJT 																	as JJT,
			TIPODOC 																as TipoDoc,
			TIPCOMP 																as TIPCOMP,
			JJTOTFAC * power( -1, SIGNO )											as JJTotFac,
			JJTURNO 																as JJTurno,
			JJCO 																	as JJCO,
			JJDE 																	as JJDE,
			JJVEN 																	as JJVen,
			0		 																as JJRecib,
			case when fechcoti = '01/01/1900 00:00:00' then null else fechcoti end 	as FechCoti,
			COTIZA 																	as Cotiza,
			JRECPORC 																as recporc,
			JRECMNTSI * power( -1, SIGNO )											as recsinimp,
			JRRECSPERC * power( -1, SIGNO )											as recsinper,
			VALECAMBIO 																as ValeCambio,
			IDCAJA 																	as IdCaja,
			NROCHPROP 																as NroChProp,
			null	 																as CondPago,
			0																		as ESVUELTO 
		from ZooLogic.VALCOMPPAGO vcp

	) as Valores
);
