IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_PRECIODEARTICULO_PRECIODEARTICULO]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_PRECIODEARTICULO_PRECIODEARTICULO];
GO;

CREATE FUNCTION [Listados].[GENERICO_PRECIODEARTICULO_PRECIODEARTICULO]
( @BaseDeDatos varchar(8),
	@PRECIODEARTICULO_CODIGO_DESDE varchar(46),
	@PRECIODEARTICULO_CODIGO_HASTA varchar(46),
	@PRECIODEARTICULO_ARTICULO_DESDE varchar(15),
	@PRECIODEARTICULO_ARTICULO_HASTA varchar(15),
	@PRECIODEARTICULO_COLOR_DESDE varchar(6),
	@PRECIODEARTICULO_COLOR_HASTA varchar(6),
	@PRECIODEARTICULO_TALLE_DESDE varchar(5),
	@PRECIODEARTICULO_TALLE_HASTA varchar(5),
	@PRECIODEARTICULO_LISTADEPRECIO_DESDE varchar(6),
	@PRECIODEARTICULO_LISTADEPRECIO_HASTA varchar(6),
	@PRECIODEARTICULO_PRECIODIRECTO_DESDE numeric(15, 2),
	@PRECIODEARTICULO_PRECIODIRECTO_HASTA numeric(15, 2),
	@PRECIODEARTICULO_FECHAVIGENCIA_DESDE datetime,
	@PRECIODEARTICULO_FECHAVIGENCIA_HASTA datetime,
	@ARTICULO_9_ARTICULO_DESCRIPCION_DESDE varchar(100),
	@ARTICULO_9_ARTICULO_DESCRIPCION_HASTA varchar(100),
	@COLOR_51_COLOR_DESCRIPCION_DESDE varchar(50),
	@COLOR_51_COLOR_DESCRIPCION_HASTA varchar(50),
	@TALLE_53_TALLE_DESCRIPCION_DESDE varchar(50),
	@TALLE_53_TALLE_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_11139_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_11139_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_11138_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_11138_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_11137_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_11137_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_10_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_10_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@TEMPORADA_16_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_16_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_17_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_17_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_18_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_18_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_19_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_19_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_20_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_20_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_21_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_21_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_22_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_22_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_23_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_23_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_25_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_25_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@PALETADECOLORES_29_PALETADECOLORES_DESCRIPCION_DESDE varchar(40),
	@PALETADECOLORES_29_PALETADECOLORES_DESCRIPCION_HASTA varchar(40),
	@CURVADETALLES_30_CURVADETALLES_DESCRIPCION_DESDE varchar(40),
	@CURVADETALLES_30_CURVADETALLES_DESCRIPCION_HASTA varchar(40),
	@NOMENCLADORARBA_32_NOMENCLADOR_DESCRIPCION_DESDE varchar(150),
	@NOMENCLADORARBA_32_NOMENCLADOR_DESCRIPCION_HASTA varchar(150),
	@MARCA_49_MARCA_DESCRIPCION_DESDE varchar(100),
	@MARCA_49_MARCA_DESCRIPCION_HASTA varchar(100),
	@SUCURSAL_11134_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_11134_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_11134_LINEA_DESDE varchar(10),
	@SUCURSAL_11134_LINEA_HASTA varchar(10),
	@SUCURSAL_11134_TIPO_DESDE varchar(10),
	@SUCURSAL_11134_TIPO_HASTA varchar(10),
	@SUCURSAL_11134_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_11134_DESCRIPCION_HASTA varchar(50),
	@ARTICULO_9_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_9_PROVEEDOR_HASTA varchar(10),
	@ARTICULO_9_CONDICIONIVAVENTAS numeric(1, 0),
	@ARTICULO_9_PORCENTAJEIVAVENTAS_DESDE numeric(5, 2),
	@ARTICULO_9_PORCENTAJEIVAVENTAS_HASTA numeric(5, 2),
	@ARTICULO_9_IMAGEN_DESDE varchar(180),
	@ARTICULO_9_IMAGEN_HASTA varchar(180),
	@ARTICULO_9_TEMPORADA_DESDE varchar(5),
	@ARTICULO_9_TEMPORADA_HASTA varchar(5),
	@ARTICULO_9_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_9_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_9_FAMILIA_DESDE varchar(10),
	@ARTICULO_9_FAMILIA_HASTA varchar(10),
	@ARTICULO_9_MATERIAL_DESDE varchar(10),
	@ARTICULO_9_MATERIAL_HASTA varchar(10),
	@ARTICULO_9_LINEA_DESDE varchar(10),
	@ARTICULO_9_LINEA_HASTA varchar(10),
	@ARTICULO_9_GRUPO_DESDE varchar(10),
	@ARTICULO_9_GRUPO_HASTA varchar(10),
	@ARTICULO_9_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_9_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_9_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_9_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_9_ANO_DESDE numeric(4, 0),
	@ARTICULO_9_ANO_HASTA numeric(4, 0),
	@ARTICULO_9_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_9_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_9_CONDICIONIVACOMPRAS numeric(1, 0),
	@ARTICULO_9_PORCENTAJEIVACOMPRAS_DESDE numeric(5, 2),
	@ARTICULO_9_PORCENTAJEIVACOMPRAS_HASTA numeric(5, 2),
	@ARTICULO_9_COMPORTAMIENTO numeric(1, 0),
	@ARTICULO_9_PALETADECOLORES_DESDE varchar(10),
	@ARTICULO_9_PALETADECOLORES_HASTA varchar(10),
	@ARTICULO_9_CURVADETALLES_DESDE varchar(10),
	@ARTICULO_9_CURVADETALLES_HASTA varchar(10),
	@ARTICULO_9_NOCOMERCIALIZABLE_DESDE datetime,
	@ARTICULO_9_NOCOMERCIALIZABLE_HASTA datetime,
	@ARTICULO_9_NOMENCLADOR_DESDE varchar(6),
	@ARTICULO_9_NOMENCLADOR_HASTA varchar(6),
	@ARTICULO_9_NOPERMITEDEVOLUCIONES bit,
	@ARTICULO_9_IMPRIMEDESPACHO bit,
	@ARTICULO_9_PORCENTAJEIMPUESTOINTERNO_DESDE numeric(5, 2),
	@ARTICULO_9_PORCENTAJEIMPUESTOINTERNO_HASTA numeric(5, 2),
	@ARTICULO_9_RESTRINGIRDESCUENTOS bit,
	@ARTICULO_9_PESO_DESDE numeric(11, 3),
	@ARTICULO_9_PESO_HASTA numeric(11, 3),
	@ARTICULO_9_LARGO_DESDE numeric(11, 2),
	@ARTICULO_9_LARGO_HASTA numeric(11, 2),
	@ARTICULO_9_ANCHO_DESDE numeric(11, 2),
	@ARTICULO_9_ANCHO_HASTA numeric(11, 2),
	@ARTICULO_9_ALTO_DESDE numeric(11, 2),
	@ARTICULO_9_ALTO_HASTA numeric(11, 2),
	@ARTICULO_9_REQUIERECCOSTO_DESDE numeric(1, 0),
	@ARTICULO_9_REQUIERECCOSTO_HASTA numeric(1, 0),
	@ARTICULO_9_NOPUBLICARENECOMMERCE bit,
	@ARTICULO_9_IMPORTADO bit,
	@ARTICULO_9_DESCRIPCIONADICIONAL_DESDE varchar(254),
	@ARTICULO_9_DESCRIPCIONADICIONAL_HASTA varchar(254),
	@ARTICULO_9_SOLOPROMOYKIT bit,
	@ARTICULO_9_RESTRINGIRARTICULO_DESDE datetime,
	@ARTICULO_9_RESTRINGIRARTICULO_HASTA datetime,
	@ARTICULO_9_MARCA_DESDE varchar(30),
	@ARTICULO_9_MARCA_HASTA varchar(30),
	@ARTICULO_9_PERCEPCIONIVARG5329 numeric(1, 0),
	@SUCURSAL_11134_CODIGO_DESDE varchar(10),
	@SUCURSAL_11134_CODIGO_HASTA varchar(10),
	@PRECIODEARTICULO_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@PRECIODEARTICULO_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@PRECIODEARTICULO_FECHAEXPO_DESDE datetime,
	@PRECIODEARTICULO_FECHAEXPO_HASTA datetime,
	@PRECIODEARTICULO_FECHAIMPO_DESDE datetime,
	@PRECIODEARTICULO_FECHAIMPO_HASTA datetime,
	@PRECIODEARTICULO_FECHATRANSFERENCIA_DESDE datetime,
	@PRECIODEARTICULO_FECHATRANSFERENCIA_HASTA datetime,
	@PRECIODEARTICULO_VERSIONALTAFW_DESDE varchar(13),
	@PRECIODEARTICULO_VERSIONALTAFW_HASTA varchar(13),
	@PRECIODEARTICULO_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@PRECIODEARTICULO_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@PRECIODEARTICULO_FECHAMODIFICACIONFW_DESDE datetime,
	@PRECIODEARTICULO_FECHAMODIFICACIONFW_HASTA datetime,
	@ARTICULO_FECHAALTAFW_DESDE datetime,
	@ARTICULO_FECHAALTAFW_HASTA datetime,
	@Parametro1 varchar(max),
	@Parametro2 varchar(max),
	@Parametro3 varchar(max),
	@Parametro4 varchar(max),
	@Parametro5 varchar(max),
	@Parametro6 int )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_preciodearticulo.codigo, 38, ' ' ) as varchar( 46 ) ) as PRECIODEARTICULO__Grupo,
	@basededatos as PRECIODEARTICULO__BD,
	cast( @parametro6 as numeric( 1, 0 ) ) as PRECIODEARTICULO_MostrarPreciosEnCero,
	c_PRECIODEARTICULO.CODIGO as PRECIODEARTICULO_CODIGO,
	c_PRECIODEARTICULO.ARTICULO as PRECIODEARTICULO_ARTICULO,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	c_PRECIODEARTICULO.CCOLOR as PRECIODEARTICULO_cColor,
	cast( funciones.obtenerordenenlapaletadecolores(c_preciodearticulo.articulo, c_preciodearticulo.ccolor, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as PRECIODEARTICULO_OrdenPaletaColores,
	c_PRECIODEARTICULO.TALLE as PRECIODEARTICULO_Talle,
	cast( funciones.obtenerordenenlacurvadetalle(c_preciodearticulo.articulo, c_preciodearticulo.talle, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as PRECIODEARTICULO_OrdenCurvaTalles,
	c_PRECIODEARTICULO.LISTAPRE as PRECIODEARTICULO_LISTAPRE,
	c_PRECIODEARTICULO.PDIRECTO as PRECIODEARTICULO_PDIRECTO,
	case when c_preciodearticulo.fechavig = '01/01/1900 00:00:00' then null else c_preciodearticulo.fechavig end as PRECIODEARTICULO_FECHAVIG,
	c_PRECIODEARTICULO.OBS as PRECIODEARTICULO_Obs,
	cast( case when c_articulo.tipagrupub<= 1 then upper('todos') when c_articulo.tipagrupub= 2 then upper('ninguno') else stuff((select '; '+rtrim(agrup) from zoologic.agrupubart where codigo = rtrim(c_articulo.artcod) order by agrup for xml path('')),1,2,'') end as varchar( 254 ) ) as ARTICULO_FiltroDePublicacionesVirtual,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_ARTICULO.ARTCONIVA as ARTICULO_ARTCONIVA,
	C_ARTICULO.ARTPORIVA as ARTICULO_ARTPORIVA,
	C_ARTICULO.AOBS as ARTICULO_AObs,
	C_ARTICULO.ATEMPORADA as ARTICULO_ATEMPORADA,
	C_ARTICULO.UNIMED as ARTICULO_UniMed,
	C_ARTICULO.FAMILIA as ARTICULO_Familia,
	C_ARTICULO.MAT as ARTICULO_Mat,
	C_ARTICULO.LINEA as ARTICULO_Linea,
	C_ARTICULO.GRUPO as ARTICULO_Grupo,
	C_ARTICULO.CATEARTI as ARTICULO_CateArti,
	C_ARTICULO.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	C_ARTICULO.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ARTIVA as ARTICULO_ARTIVA,
	C_ARTICULO.ANX2 as ARTICULO_ANX2,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	C_ARTICULO.PALCOL as ARTICULO_PalCol,
	C_ARTICULO.CURTALL as ARTICULO_Curtall,
	case when c_articulo.nocom = '01/01/1900 00:00:00' then null else c_articulo.nocom end as ARTICULO_NOCOM,
	C_ARTICULO.ARTNARBA as ARTICULO_ARTNARBA,
	C_ARTICULO.ARTNODEVO as ARTICULO_ARTNODEVO,
	C_ARTICULO.ESIMPDES as ARTICULO_EsImpDes,
	C_ARTICULO.IMPINTERNO as ARTICULO_impinterno,
	C_ARTICULO.ARTSINDES as ARTICULO_ArtSinDes,
	C_ARTICULO.ARTPESO as ARTICULO_ARTPESO,
	C_ARTICULO.ARTLARGO as ARTICULO_ARTLARGO,
	C_ARTICULO.ARTANCHO as ARTICULO_ARTANCHO,
	C_ARTICULO.ARTALTO as ARTICULO_ARTALTO,
	C_ARTICULO.REQCCOSTO as ARTICULO_ReqCCosto,
	C_ARTICULO.PUBECOM as ARTICULO_PubEcom,
	C_ARTICULO.IMPORTADO as ARTICULO_Importado,
	C_ARTICULO.ARTDESADIC as ARTICULO_ARTDESADIC,
	C_ARTICULO.PROMOYKIT as ARTICULO_PromoYKit,
	C_ARTICULO.DESECOHTML as ARTICULO_DesEcoHTML,
	C_ARTICULO.DESECO as ARTICULO_DesEco,
	case when c_articulo.artrest = '01/01/1900 00:00:00' then null else c_articulo.artrest end as ARTICULO_ArtRest,
	C_ARTICULO.MARCA as ARTICULO_Marca,
	C_ARTICULO.ARTPERCEP as ARTICULO_ArtPercep,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_PRECIODEARTICULO.ESTTRANS as PRECIODEARTICULO_ESTTRANS,
	case when c_preciodearticulo.fecexpo = '01/01/1900 00:00:00' then null else c_preciodearticulo.fecexpo end as PRECIODEARTICULO_FECEXPO,
	case when c_preciodearticulo.fecimpo = '01/01/1900 00:00:00' then null else c_preciodearticulo.fecimpo end as PRECIODEARTICULO_FECIMPO,
	case when c_preciodearticulo.fectrans = '01/01/1900 00:00:00' then null else c_preciodearticulo.fectrans end as PRECIODEARTICULO_FECTRANS,
	c_PRECIODEARTICULO.VALTAFW as PRECIODEARTICULO_VALTAFW,
	c_PRECIODEARTICULO.VMODIFW as PRECIODEARTICULO_VMODIFW,
	c_PRECIODEARTICULO.ZADSFW as PRECIODEARTICULO_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as PRECIODEARTICULO__SUCURSAL,
	cast( funciones.obtenerpreciodelacombinacionconvigencia(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, c_PRECIODEARTICULO.listapre, @parametro1, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioVirtual,
	@parametro1 as PRECIODEARTICULO_FechaVigenciaVirtual,
	cast( 0 as numeric( 15, 2 ) ) as PRECIODEARTICULO_FiltroDePrecioVirtual,
	case when c_PRECIODEARTICULO.pCalculado = 1 then
		funciones.eselpreciovigentealafecha(c_preciodearticulo.codigo, c_preciodearticulo.listabase, c_preciodearticulo.articulo, c_preciodearticulo.ccolor, c_preciodearticulo.talle, @parametro1 )
	else
		funciones.eselpreciovigentealafecha(c_preciodearticulo.codigo, c_preciodearticulo.listapre, c_preciodearticulo.articulo, c_preciodearticulo.ccolor, c_preciodearticulo.talle, @parametro1 )
	end as PRECIODEARTICULO_PrecioVigente, 
	cast( @parametro2 as varchar( 6 ) ) as PRECIODEARTICULO_CodigoDeLista1Virtual,
	@parametro3 as PRECIODEARTICULO_VigenciaParaLista1Virtual,
	cast( funciones.obtenerpreciodelacombinacionconosinimpuestosalafecha(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro2, 1, @parametro3, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioParaVigenciaL1CIVirtual,
	cast( funciones.obtenerpreciodelacombinacionconosinimpuestosalafecha(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro2, 0, @parametro3, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioParaVigenciaL1SIVirtual,
	cast( funciones.obtenerpreciodelacombinacionconvigencia(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro2, @parametro3, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioParaVigenciaL1Virtual,
	cast( @parametro4 as varchar( 6 ) ) as PRECIODEARTICULO_CodigoDeLista2Virtual,
	@parametro5 as PRECIODEARTICULO_VigenciaParaLista2Virtual,
	cast( funciones.obtenerpreciodelacombinacionconosinimpuestosalafecha(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro4, 1, @parametro5, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioParaVigenciaL2CIVirtual,
	cast( funciones.obtenerpreciodelacombinacionconosinimpuestosalafecha(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro4, 0, @parametro5, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioParaVigenciaL2SIVirtual,
	cast( funciones.obtenerpreciodelacombinacionconvigencia(c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro4, @parametro5, 0 ) as numeric( 15, 2 ) ) as PRECIODEARTICULO_PrecioParaVigenciaL2Virtual,
	funciones.participadelacomparaciondeprecios(c_PRECIODEARTICULO.codigo, c_PRECIODEARTICULO.articulo, c_PRECIODEARTICULO.ccolor, c_PRECIODEARTICULO.talle, @parametro2, @parametro3, @parametro4, @parametro5) as PRECIODEARTICULO_ParticipaEnLaComparacionDePreciosVirtual,
	case when c_preciodearticulo.faltafw = '01/01/1900 00:00:00' then null else c_preciodearticulo.faltafw end as PRECIODEARTICULO_FALTAFW,
	c_PRECIODEARTICULO.HALTAFW as PRECIODEARTICULO_HALTAFW,
	c_PRECIODEARTICULO.HORAEXPO as PRECIODEARTICULO_HORAEXPO,
	c_PRECIODEARTICULO.HORAIMPO as PRECIODEARTICULO_HORAIMPO,
	c_PRECIODEARTICULO.HMODIFW as PRECIODEARTICULO_HMODIFW,
	c_PRECIODEARTICULO.UALTAFW as PRECIODEARTICULO_UALTAFW,
	c_PRECIODEARTICULO.UMODIFW as PRECIODEARTICULO_UMODIFW,
	c_PRECIODEARTICULO.BDALTAFW as PRECIODEARTICULO_BDALTAFW,
	c_PRECIODEARTICULO.BDMODIFW as PRECIODEARTICULO_BDMODIFW,
	c_PRECIODEARTICULO.SALTAFW as PRECIODEARTICULO_SALTAFW,
	c_PRECIODEARTICULO.SMODIFW as PRECIODEARTICULO_SMODIFW,
	case when c_preciodearticulo.fmodifw = '01/01/1900 00:00:00' then null else c_preciodearticulo.fmodifw end as PRECIODEARTICULO_FMODIFW,
	case when c_articulo.faltafw = '01/01/1900 00:00:00' then null else c_articulo.faltafw end as ARTICULO_FALTAFW,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_LISTADEPRECIOS.LPR_NOMBRE as LISTADEPRECIOS_LPR_NOMBRE,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVEEDOR.CLNOM as PROVEEDOR_CLNOM,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_PALETADECOLORES.DESCRIP as PALETADECOLORES_Descrip,
	C_CURVADETALLES.DESCRIP as CURVADETALLES_Descrip,
	C_NOMENCLADORARBA.NMCDES as NOMENCLADORARBA_NMCDES,
	C_MARCA.DESCRIP as MARCA_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_CURVADETALLES.CODIGO as CURVADETALLES_Codigo,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS.LPR_NUMERO as LISTADEPRECIOS_LPR_NUMERO,
	C_MARCA.CODIGO as MARCA_Codigo,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_NOMENCLADORARBA.NMCCOD as NOMENCLADORARBA_NMCCOD,
	C_PALETADECOLORES.CODIGO as PALETADECOLORES_Codigo,
	C_PROVEEDOR.CLCOD as PROVEEDOR_CLCOD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from funciones.PropagarPreciosATodasLasCombinaciones(@Parametro1, @Parametro6) as c_PRECIODEARTICULO --Reemplaza a la tabla PRECIOAR
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = c_PRECIODEARTICULO.ARTICULO and c_ARTICULO.BLOQREG = 0
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = C_ARTICULO.CATEARTI and 0 = Funciones.empty( C_ARTICULO.CATEARTI )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = C_ARTICULO.CLASIFART and 0 = Funciones.empty( C_ARTICULO.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_PRECIODEARTICULO.CCOLOR and 0 = Funciones.empty( C_PRECIODEARTICULO.CCOLOR )
 left join ZooLogic.CTALLE as C_CURVADETALLES on C_CURVADETALLES.CODIGO = C_ARTICULO.CURTALL and 0 = Funciones.empty( C_ARTICULO.CURTALL )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS on C_LISTADEPRECIOS.LPR_NUMERO = C_PRECIODEARTICULO.LISTAPRE and 0 = Funciones.empty( C_PRECIODEARTICULO.LISTAPRE )
 left join ZooLogic.MARCAS as C_MARCA on C_MARCA.CODIGO = C_ARTICULO.MARCA and 0 = Funciones.empty( C_ARTICULO.MARCA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.NMCARBA as C_NOMENCLADORARBA on C_NOMENCLADORARBA.NMCCOD = C_ARTICULO.ARTNARBA and 0 = Funciones.empty( C_ARTICULO.ARTNARBA )
 left join ZooLogic.PCOLOR as C_PALETADECOLORES on C_PALETADECOLORES.CODIGO = C_ARTICULO.PALCOL and 0 = Funciones.empty( C_ARTICULO.PALCOL )
 left join ZooLogic.PROV as C_PROVEEDOR on C_PROVEEDOR.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_PRECIODEARTICULO.TALLE and 0 = Funciones.empty( C_PRECIODEARTICULO.TALLE )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = C_ARTICULO.UNIMED and 0 = Funciones.empty( C_ARTICULO.UNIMED )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where
	( ( @PRECIODEARTICULO_CODIGO_DESDE is null ) OR ( c_PRECIODEARTICULO.CODIGO >= @PRECIODEARTICULO_CODIGO_DESDE ) ) and 
	( ( @PRECIODEARTICULO_CODIGO_HASTA is null ) OR ( c_PRECIODEARTICULO.CODIGO <= @PRECIODEARTICULO_CODIGO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_ARTICULO_DESDE is null ) OR ( c_PRECIODEARTICULO.ARTICULO >= @PRECIODEARTICULO_ARTICULO_DESDE ) ) and 
	( ( @PRECIODEARTICULO_ARTICULO_HASTA is null ) OR ( c_PRECIODEARTICULO.ARTICULO <= @PRECIODEARTICULO_ARTICULO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_COLOR_DESDE is null ) OR ( c_PRECIODEARTICULO.cColor >= @PRECIODEARTICULO_COLOR_DESDE ) ) and 
	( ( @PRECIODEARTICULO_COLOR_HASTA is null ) OR ( c_PRECIODEARTICULO.cColor <= @PRECIODEARTICULO_COLOR_HASTA ) ) and 
	( ( @PRECIODEARTICULO_TALLE_DESDE is null ) OR ( c_PRECIODEARTICULO.Talle >= @PRECIODEARTICULO_TALLE_DESDE ) ) and 
	( ( @PRECIODEARTICULO_TALLE_HASTA is null ) OR ( c_PRECIODEARTICULO.Talle <= @PRECIODEARTICULO_TALLE_HASTA ) ) and 
	( ( @PRECIODEARTICULO_LISTADEPRECIO_DESDE is null ) OR ( c_PRECIODEARTICULO.LISTAPRE >= @PRECIODEARTICULO_LISTADEPRECIO_DESDE ) ) and 
	( ( @PRECIODEARTICULO_LISTADEPRECIO_HASTA is null ) OR ( c_PRECIODEARTICULO.LISTAPRE <= @PRECIODEARTICULO_LISTADEPRECIO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_PRECIODIRECTO_DESDE is null ) OR ( c_PRECIODEARTICULO.PDIRECTO >= @PRECIODEARTICULO_PRECIODIRECTO_DESDE ) ) and 
	( ( @PRECIODEARTICULO_PRECIODIRECTO_HASTA is null ) OR ( c_PRECIODEARTICULO.PDIRECTO <= @PRECIODEARTICULO_PRECIODIRECTO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_FECHAVIGENCIA_DESDE is null ) OR ( c_PRECIODEARTICULO.FECHAVIG >= @PRECIODEARTICULO_FECHAVIGENCIA_DESDE ) ) and 
	( ( @PRECIODEARTICULO_FECHAVIGENCIA_HASTA is null ) OR ( c_PRECIODEARTICULO.FECHAVIG <= @PRECIODEARTICULO_FECHAVIGENCIA_HASTA ) ) and 
	( ( @ARTICULO_9_ARTICULO_DESCRIPCION_DESDE is null ) OR ( C_ARTICULO.ARTDES >= @ARTICULO_9_ARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @ARTICULO_9_ARTICULO_DESCRIPCION_HASTA is null ) OR ( C_ARTICULO.ARTDES <= @ARTICULO_9_ARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @COLOR_51_COLOR_DESCRIPCION_DESDE is null ) OR ( C_COLOR.COLDES >= @COLOR_51_COLOR_DESCRIPCION_DESDE ) ) and 
	( ( @COLOR_51_COLOR_DESCRIPCION_HASTA is null ) OR ( C_COLOR.COLDES <= @COLOR_51_COLOR_DESCRIPCION_HASTA ) ) and 
	( ( @TALLE_53_TALLE_DESCRIPCION_DESDE is null ) OR ( C_TALLE.Descrip >= @TALLE_53_TALLE_DESCRIPCION_DESDE ) ) and 
	( ( @TALLE_53_TALLE_DESCRIPCION_HASTA is null ) OR ( C_TALLE.Descrip <= @TALLE_53_TALLE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE >= @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE <= @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_11139_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_11139_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_11139_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_11139_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_11138_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_11138_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_11138_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_11138_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_11137_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_11137_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_11137_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_11137_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_10_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR.CLNOM >= @PROVEEDOR_10_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_10_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR.CLNOM <= @PROVEEDOR_10_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @TEMPORADA_16_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_16_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_16_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_16_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_17_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_17_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_17_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_17_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_18_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_18_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_18_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_18_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_19_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_19_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_19_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_19_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_20_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_20_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_20_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_20_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_21_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_21_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_21_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_21_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_22_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_22_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_22_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_22_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_23_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_23_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_23_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_23_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_25_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_25_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_25_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_25_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @PALETADECOLORES_29_PALETADECOLORES_DESCRIPCION_DESDE is null ) OR ( C_PALETADECOLORES.Descrip >= @PALETADECOLORES_29_PALETADECOLORES_DESCRIPCION_DESDE ) ) and 
	( ( @PALETADECOLORES_29_PALETADECOLORES_DESCRIPCION_HASTA is null ) OR ( C_PALETADECOLORES.Descrip <= @PALETADECOLORES_29_PALETADECOLORES_DESCRIPCION_HASTA ) ) and 
	( ( @CURVADETALLES_30_CURVADETALLES_DESCRIPCION_DESDE is null ) OR ( C_CURVADETALLES.Descrip >= @CURVADETALLES_30_CURVADETALLES_DESCRIPCION_DESDE ) ) and 
	( ( @CURVADETALLES_30_CURVADETALLES_DESCRIPCION_HASTA is null ) OR ( C_CURVADETALLES.Descrip <= @CURVADETALLES_30_CURVADETALLES_DESCRIPCION_HASTA ) ) and 
	( ( @NOMENCLADORARBA_32_NOMENCLADOR_DESCRIPCION_DESDE is null ) OR ( C_NOMENCLADORARBA.NMCDES >= @NOMENCLADORARBA_32_NOMENCLADOR_DESCRIPCION_DESDE ) ) and 
	( ( @NOMENCLADORARBA_32_NOMENCLADOR_DESCRIPCION_HASTA is null ) OR ( C_NOMENCLADORARBA.NMCDES <= @NOMENCLADORARBA_32_NOMENCLADOR_DESCRIPCION_HASTA ) ) and 
	( ( @MARCA_49_MARCA_DESCRIPCION_DESDE is null ) OR ( C_MARCA.Descrip >= @MARCA_49_MARCA_DESCRIPCION_DESDE ) ) and 
	( ( @MARCA_49_MARCA_DESCRIPCION_HASTA is null ) OR ( C_MARCA.Descrip <= @MARCA_49_MARCA_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_11134_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_11134_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_11134_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_11134_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_11134_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_11134_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_11134_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_11134_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_11134_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_11134_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_11134_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_11134_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_11134_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_11134_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_11134_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_11134_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_9_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_9_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_9_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_9_PROVEEDOR_HASTA ) ) and 
	( ( @ARTICULO_9_CONDICIONIVAVENTAS is null ) OR ( C_ARTICULO.ARTCONIVA = @ARTICULO_9_CONDICIONIVAVENTAS ) ) and 
	( ( @ARTICULO_9_PORCENTAJEIVAVENTAS_DESDE is null ) OR ( C_ARTICULO.ARTPORIVA >= @ARTICULO_9_PORCENTAJEIVAVENTAS_DESDE ) ) and 
	( ( @ARTICULO_9_PORCENTAJEIVAVENTAS_HASTA is null ) OR ( C_ARTICULO.ARTPORIVA <= @ARTICULO_9_PORCENTAJEIVAVENTAS_HASTA ) ) and 
	( ( @ARTICULO_9_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_9_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_9_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_9_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_9_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_9_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_9_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_9_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_9_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_9_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_9_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_9_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_9_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_9_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_9_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_9_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_9_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_9_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_9_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_9_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_9_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_9_LINEA_DESDE ) ) and 
	( ( @ARTICULO_9_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_9_LINEA_HASTA ) ) and 
	( ( @ARTICULO_9_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_9_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_9_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_9_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_9_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_9_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_9_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_9_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_9_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_9_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_9_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_9_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_9_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_9_ANO_DESDE ) ) and 
	( ( @ARTICULO_9_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_9_ANO_HASTA ) ) and 
	( ( @ARTICULO_9_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_9_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_9_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_9_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_9_CONDICIONIVACOMPRAS is null ) OR ( C_ARTICULO.ARTIVA = @ARTICULO_9_CONDICIONIVACOMPRAS ) ) and 
	( ( @ARTICULO_9_PORCENTAJEIVACOMPRAS_DESDE is null ) OR ( C_ARTICULO.ANX2 >= @ARTICULO_9_PORCENTAJEIVACOMPRAS_DESDE ) ) and 
	( ( @ARTICULO_9_PORCENTAJEIVACOMPRAS_HASTA is null ) OR ( C_ARTICULO.ANX2 <= @ARTICULO_9_PORCENTAJEIVACOMPRAS_HASTA ) ) and 
	( ( @ARTICULO_9_COMPORTAMIENTO is null ) OR ( C_ARTICULO.ASTOCK = @ARTICULO_9_COMPORTAMIENTO ) ) and 
	( ( @ARTICULO_9_PALETADECOLORES_DESDE is null ) OR ( C_ARTICULO.PalCol >= @ARTICULO_9_PALETADECOLORES_DESDE ) ) and 
	( ( @ARTICULO_9_PALETADECOLORES_HASTA is null ) OR ( C_ARTICULO.PalCol <= @ARTICULO_9_PALETADECOLORES_HASTA ) ) and 
	( ( @ARTICULO_9_CURVADETALLES_DESDE is null ) OR ( C_ARTICULO.Curtall >= @ARTICULO_9_CURVADETALLES_DESDE ) ) and 
	( ( @ARTICULO_9_CURVADETALLES_HASTA is null ) OR ( C_ARTICULO.Curtall <= @ARTICULO_9_CURVADETALLES_HASTA ) ) and 
	( ( @ARTICULO_9_NOCOMERCIALIZABLE_DESDE is null ) OR ( C_ARTICULO.NOCOM >= @ARTICULO_9_NOCOMERCIALIZABLE_DESDE ) ) and 
	( ( @ARTICULO_9_NOCOMERCIALIZABLE_HASTA is null ) OR ( C_ARTICULO.NOCOM <= @ARTICULO_9_NOCOMERCIALIZABLE_HASTA ) ) and 
	( ( @ARTICULO_9_NOMENCLADOR_DESDE is null ) OR ( C_ARTICULO.ARTNARBA >= @ARTICULO_9_NOMENCLADOR_DESDE ) ) and 
	( ( @ARTICULO_9_NOMENCLADOR_HASTA is null ) OR ( C_ARTICULO.ARTNARBA <= @ARTICULO_9_NOMENCLADOR_HASTA ) ) and 
	( ( @ARTICULO_9_NOPERMITEDEVOLUCIONES is null ) OR ( C_ARTICULO.ARTNODEVO = @ARTICULO_9_NOPERMITEDEVOLUCIONES ) ) and 
	( ( @ARTICULO_9_IMPRIMEDESPACHO is null ) OR ( C_ARTICULO.EsImpDes = @ARTICULO_9_IMPRIMEDESPACHO ) ) and 
	( ( @ARTICULO_9_PORCENTAJEIMPUESTOINTERNO_DESDE is null ) OR ( C_ARTICULO.impinterno >= @ARTICULO_9_PORCENTAJEIMPUESTOINTERNO_DESDE ) ) and 
	( ( @ARTICULO_9_PORCENTAJEIMPUESTOINTERNO_HASTA is null ) OR ( C_ARTICULO.impinterno <= @ARTICULO_9_PORCENTAJEIMPUESTOINTERNO_HASTA ) ) and 
	( ( @ARTICULO_9_RESTRINGIRDESCUENTOS is null ) OR ( C_ARTICULO.ArtSinDes = @ARTICULO_9_RESTRINGIRDESCUENTOS ) ) and 
	( ( @ARTICULO_9_PESO_DESDE is null ) OR ( C_ARTICULO.ARTPESO >= @ARTICULO_9_PESO_DESDE ) ) and 
	( ( @ARTICULO_9_PESO_HASTA is null ) OR ( C_ARTICULO.ARTPESO <= @ARTICULO_9_PESO_HASTA ) ) and 
	( ( @ARTICULO_9_LARGO_DESDE is null ) OR ( C_ARTICULO.ARTLARGO >= @ARTICULO_9_LARGO_DESDE ) ) and 
	( ( @ARTICULO_9_LARGO_HASTA is null ) OR ( C_ARTICULO.ARTLARGO <= @ARTICULO_9_LARGO_HASTA ) ) and 
	( ( @ARTICULO_9_ANCHO_DESDE is null ) OR ( C_ARTICULO.ARTANCHO >= @ARTICULO_9_ANCHO_DESDE ) ) and 
	( ( @ARTICULO_9_ANCHO_HASTA is null ) OR ( C_ARTICULO.ARTANCHO <= @ARTICULO_9_ANCHO_HASTA ) ) and 
	( ( @ARTICULO_9_ALTO_DESDE is null ) OR ( C_ARTICULO.ARTALTO >= @ARTICULO_9_ALTO_DESDE ) ) and 
	( ( @ARTICULO_9_ALTO_HASTA is null ) OR ( C_ARTICULO.ARTALTO <= @ARTICULO_9_ALTO_HASTA ) ) and 
	( ( @ARTICULO_9_REQUIERECCOSTO_DESDE is null ) OR ( C_ARTICULO.ReqCCosto >= @ARTICULO_9_REQUIERECCOSTO_DESDE ) ) and 
	( ( @ARTICULO_9_REQUIERECCOSTO_HASTA is null ) OR ( C_ARTICULO.ReqCCosto <= @ARTICULO_9_REQUIERECCOSTO_HASTA ) ) and 
	( ( @ARTICULO_9_NOPUBLICARENECOMMERCE is null ) OR ( C_ARTICULO.PubEcom = @ARTICULO_9_NOPUBLICARENECOMMERCE ) ) and 
	( ( @ARTICULO_9_IMPORTADO is null ) OR ( C_ARTICULO.Importado = @ARTICULO_9_IMPORTADO ) ) and 
	( ( @ARTICULO_9_DESCRIPCIONADICIONAL_DESDE is null ) OR ( C_ARTICULO.ARTDESADIC >= @ARTICULO_9_DESCRIPCIONADICIONAL_DESDE ) ) and 
	( ( @ARTICULO_9_DESCRIPCIONADICIONAL_HASTA is null ) OR ( C_ARTICULO.ARTDESADIC <= @ARTICULO_9_DESCRIPCIONADICIONAL_HASTA ) ) and 
	( ( @ARTICULO_9_SOLOPROMOYKIT is null ) OR ( C_ARTICULO.PromoYKit = @ARTICULO_9_SOLOPROMOYKIT ) ) and 
	( ( @ARTICULO_9_RESTRINGIRARTICULO_DESDE is null ) OR ( C_ARTICULO.ArtRest >= @ARTICULO_9_RESTRINGIRARTICULO_DESDE ) ) and 
	( ( @ARTICULO_9_RESTRINGIRARTICULO_HASTA is null ) OR ( C_ARTICULO.ArtRest <= @ARTICULO_9_RESTRINGIRARTICULO_HASTA ) ) and 
	( ( @ARTICULO_9_MARCA_DESDE is null ) OR ( C_ARTICULO.Marca >= @ARTICULO_9_MARCA_DESDE ) ) and 
	( ( @ARTICULO_9_MARCA_HASTA is null ) OR ( C_ARTICULO.Marca <= @ARTICULO_9_MARCA_HASTA ) ) and 
	( ( @ARTICULO_9_PERCEPCIONIVARG5329 is null ) OR ( C_ARTICULO.ArtPercep = @ARTICULO_9_PERCEPCIONIVARG5329 ) ) and 
	( ( @SUCURSAL_11134_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_11134_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_11134_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_11134_CODIGO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_PRECIODEARTICULO.ESTTRANS >= @PRECIODEARTICULO_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @PRECIODEARTICULO_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_PRECIODEARTICULO.ESTTRANS <= @PRECIODEARTICULO_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @PRECIODEARTICULO_FECHAEXPO_DESDE is null ) OR ( c_PRECIODEARTICULO.FECEXPO >= @PRECIODEARTICULO_FECHAEXPO_DESDE ) ) and 
	( ( @PRECIODEARTICULO_FECHAEXPO_HASTA is null ) OR ( c_PRECIODEARTICULO.FECEXPO <= @PRECIODEARTICULO_FECHAEXPO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_FECHAIMPO_DESDE is null ) OR ( c_PRECIODEARTICULO.FECIMPO >= @PRECIODEARTICULO_FECHAIMPO_DESDE ) ) and 
	( ( @PRECIODEARTICULO_FECHAIMPO_HASTA is null ) OR ( c_PRECIODEARTICULO.FECIMPO <= @PRECIODEARTICULO_FECHAIMPO_HASTA ) ) and 
	( ( @PRECIODEARTICULO_FECHATRANSFERENCIA_DESDE is null ) OR ( c_PRECIODEARTICULO.FECTRANS >= @PRECIODEARTICULO_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @PRECIODEARTICULO_FECHATRANSFERENCIA_HASTA is null ) OR ( c_PRECIODEARTICULO.FECTRANS <= @PRECIODEARTICULO_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @PRECIODEARTICULO_VERSIONALTAFW_DESDE is null ) OR ( c_PRECIODEARTICULO.VALTAFW >= @PRECIODEARTICULO_VERSIONALTAFW_DESDE ) ) and 
	( ( @PRECIODEARTICULO_VERSIONALTAFW_HASTA is null ) OR ( c_PRECIODEARTICULO.VALTAFW <= @PRECIODEARTICULO_VERSIONALTAFW_HASTA ) ) and 
	( ( @PRECIODEARTICULO_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_PRECIODEARTICULO.VMODIFW >= @PRECIODEARTICULO_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @PRECIODEARTICULO_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_PRECIODEARTICULO.VMODIFW <= @PRECIODEARTICULO_VERSIONMODIFICACIONFW_HASTA ) ) and 
	( ( @PRECIODEARTICULO_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_PRECIODEARTICULO.FMODIFW >= @PRECIODEARTICULO_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @PRECIODEARTICULO_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_PRECIODEARTICULO.FMODIFW <= @PRECIODEARTICULO_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @ARTICULO_FECHAALTAFW_DESDE is null ) OR ( C_ARTICULO.FALTAFW >= @ARTICULO_FECHAALTAFW_DESDE ) ) and 
	( ( @ARTICULO_FECHAALTAFW_HASTA is null ) OR ( C_ARTICULO.FALTAFW <= @ARTICULO_FECHAALTAFW_HASTA ) )

)