IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_FACTURA_VENTAS_ITEMARTICULOSVENTAS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_FACTURA_VENTAS_ITEMARTICULOSVENTAS];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_FACTURA_VENTAS_ITEMARTICULOSVENTAS]
( @BaseDeDatos varchar(8),
	@FACTURA_DESPACHOS_DESDE varchar(254),
	@FACTURA_DESPACHOS_HASTA varchar(254),
	@DATOSADICIONALESCOMPROBANTESA_1_SUSCRIBE numeric(2, 0),
	@DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_DESDE varchar(2),
	@DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_HASTA varchar(2),
	@DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_DESDE varchar(10),
	@DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_HASTA varchar(10),
	@MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_DESDE varchar(70),
	@MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_HASTA varchar(70),
	@FACTURA_VENDEDOR_DESDE varchar(10),
	@FACTURA_VENDEDOR_HASTA varchar(10),
	@FACTURA_CLIENTE_DESDE varchar(10),
	@FACTURA_CLIENTE_HASTA varchar(10),
	@FACTURA_TIPOCOMPROBANTE numeric(2, 0),
	@FACTURA_ANULADO bit,
	@FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE varchar(10),
	@FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA varchar(10),
	@FACTURA_NROOPECOMMERCE_DESDE varchar(254),
	@FACTURA_NROOPECOMMERCE_HASTA varchar(254),
	@FACTURA_CLIENTEDESCRIPCION_DESDE varchar(185),
	@FACTURA_CLIENTEDESCRIPCION_HASTA varchar(185),
	@FACTURA_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURA_MONEDACOMPROBANTE_HASTA varchar(10),
	@FACTURA_LISTADEPRECIOS_DESDE varchar(6),
	@FACTURA_LISTADEPRECIOS_HASTA varchar(6),
	@FACTURA_EMAIL_DESDE varchar(250),
	@FACTURA_EMAIL_HASTA varchar(250),
	@FACTURA_LETRA_DESDE varchar(1),
	@FACTURA_LETRA_HASTA varchar(1),
	@FACTURA_PUNTODEVENTA_DESDE numeric(4, 0),
	@FACTURA_PUNTODEVENTA_HASTA numeric(4, 0),
	@FACTURA_NUMERO_DESDE numeric(8, 0),
	@FACTURA_NUMERO_HASTA numeric(8, 0),
	@FACTURA_FECHA_DESDE datetime,
	@FACTURA_FECHA_HASTA datetime,
	@FACTURA_COTIZACION_DESDE numeric(15, 5),
	@FACTURA_COTIZACION_HASTA numeric(15, 5),
	@FACTURA_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@FACTURA_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@FACTURA_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@FACTURA_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@CLIENTE_2_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_2_CLIENTE_NOMBRE_HASTA varchar(185),
	@MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE varchar(50),
	@MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA varchar(50),
	@MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9249_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9249_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9248_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9248_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_3_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_3_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_18_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_18_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@PROVINCIA_96_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_96_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_102_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_102_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@VENDEDOR_9111_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_9111_VENDEDOR_NOMBRE_HASTA varchar(60),
	@SUCURSAL_9245_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9245_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9245_LINEA_DESDE varchar(10),
	@SUCURSAL_9245_LINEA_HASTA varchar(10),
	@SUCURSAL_9245_TIPO_DESDE varchar(10),
	@SUCURSAL_9245_TIPO_HASTA varchar(10),
	@SUCURSAL_9245_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9245_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_2_VENDEDOR_DESDE varchar(10),
	@CLIENTE_2_VENDEDOR_HASTA varchar(10),
	@CLIENTE_2_CALLE_DESDE varchar(250),
	@CLIENTE_2_CALLE_HASTA varchar(250),
	@CLIENTE_2_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_2_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_2_CUIT_DESDE varchar(15),
	@CLIENTE_2_CUIT_HASTA varchar(15),
	@CLIENTE_2_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_2_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_2_EMAIL_DESDE varchar(250),
	@CLIENTE_2_EMAIL_HASTA varchar(250),
	@CLIENTE_2_FAX_DESDE varchar(20),
	@CLIENTE_2_FAX_HASTA varchar(20),
	@CLIENTE_2_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_2_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_2_IMAGEN_DESDE varchar(180),
	@CLIENTE_2_IMAGEN_HASTA varchar(180),
	@CLIENTE_2_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_2_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_2_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_2_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_2_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_2_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_2_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_2_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_2_PAIS_DESDE varchar(3),
	@CLIENTE_2_PAIS_HASTA varchar(3),
	@CLIENTE_2_PISO_DESDE varchar(3),
	@CLIENTE_2_PISO_HASTA varchar(3),
	@CLIENTE_2_PROVINCIA_DESDE varchar(2),
	@CLIENTE_2_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_2_TELEFONO_DESDE varchar(30),
	@CLIENTE_2_TELEFONO_HASTA varchar(30),
	@CLIENTE_2_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_2_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_2_MOVIL_DESDE varchar(30),
	@CLIENTE_2_MOVIL_HASTA varchar(30),
	@CLIENTE_2_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_2_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_2_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_2_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_2_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_2_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_2_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_2_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_2_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_2_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_2_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_2_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_2_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_2_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_2_ESTADOCIVIL varchar(13),
	@CLIENTE_2_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_2_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_2_SEXO varchar(10),
	@CLIENTE_2_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_2_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_2_RUT_DESDE varchar(12),
	@CLIENTE_2_RUT_HASTA varchar(12),
	@CLIENTE_2_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_2_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_2_TIPOCLI_DESDE varchar(10),
	@CLIENTE_2_TIPOCLI_HASTA varchar(10),
	@CLIENTE_2_CATEGCLI_DESDE varchar(10),
	@CLIENTE_2_CATEGCLI_HASTA varchar(10),
	@CLIENTE_2_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_2_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_2_SUJETOVINCULADO bit,
	@CLIENTE_2_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_2_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_2_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_2_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_2_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_2_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_2_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_2_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_2_APELLIDO_DESDE varchar(60),
	@CLIENTE_2_APELLIDO_HASTA varchar(60),
	@CLIENTE_2_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_2_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_2_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_2_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_2_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_2_TASACEROAPLICA bit,
	@CLIENTE_2_INACTIVOFW bit,
	@MOTIVODESCUENTOYDEVOLUCION_64_TIPO numeric(1, 0),
	@VENDEDOR_9111_CODIGOPOSTAL_DESDE varchar(8),
	@VENDEDOR_9111_CODIGOPOSTAL_HASTA varchar(8),
	@VENDEDOR_9111_CALLE_DESDE varchar(70),
	@VENDEDOR_9111_CALLE_HASTA varchar(70),
	@VENDEDOR_9111_NRODOCUMENTO_DESDE varchar(10),
	@VENDEDOR_9111_NRODOCUMENTO_HASTA varchar(10),
	@VENDEDOR_9111_EMAIL_DESDE varchar(250),
	@VENDEDOR_9111_EMAIL_HASTA varchar(250),
	@VENDEDOR_9111_FECHAINGRESO_DESDE datetime,
	@VENDEDOR_9111_FECHAINGRESO_HASTA datetime,
	@VENDEDOR_9111_FECHANACIMIENTO_DESDE datetime,
	@VENDEDOR_9111_FECHANACIMIENTO_HASTA datetime,
	@VENDEDOR_9111_IMAGEN_DESDE varchar(180),
	@VENDEDOR_9111_IMAGEN_HASTA varchar(180),
	@VENDEDOR_9111_LOCALIDAD_DESDE varchar(70),
	@VENDEDOR_9111_LOCALIDAD_HASTA varchar(70),
	@VENDEDOR_9111_PROVINCIA_DESDE varchar(2),
	@VENDEDOR_9111_PROVINCIA_HASTA varchar(2),
	@VENDEDOR_9111_TELEFONO_DESDE varchar(30),
	@VENDEDOR_9111_TELEFONO_HASTA varchar(30),
	@VENDEDOR_9111_TIPODOCUMENTO_DESDE varchar(2),
	@VENDEDOR_9111_TIPODOCUMENTO_HASTA varchar(2),
	@VENDEDOR_9111_NUMERO_DESDE numeric(5, 0),
	@VENDEDOR_9111_NUMERO_HASTA numeric(5, 0),
	@VENDEDOR_9111_PISO_DESDE varchar(3),
	@VENDEDOR_9111_PISO_HASTA varchar(3),
	@VENDEDOR_9111_DEPARTAMENTO_DESDE varchar(3),
	@VENDEDOR_9111_DEPARTAMENTO_HASTA varchar(3),
	@VENDEDOR_9111_PAIS_DESDE varchar(3),
	@VENDEDOR_9111_PAIS_HASTA varchar(3),
	@VENDEDOR_9111_FECHAEGRESO_DESDE datetime,
	@VENDEDOR_9111_FECHAEGRESO_HASTA datetime,
	@VENDEDOR_9111_MOVIL_DESDE varchar(30),
	@VENDEDOR_9111_MOVIL_HASTA varchar(30),
	@VENDEDOR_9111_CLASIFICACION_DESDE varchar(10),
	@VENDEDOR_9111_CLASIFICACION_HASTA varchar(10),
	@VENDEDOR_9111_DESCUENTOPREFERENTE_DESDE varchar(10),
	@VENDEDOR_9111_DESCUENTOPREFERENTE_HASTA varchar(10),
	@VENDEDOR_9111_INACTIVOFW bit,
	@SUCURSAL_9245_CODIGO_DESDE varchar(10),
	@SUCURSAL_9245_CODIGO_HASTA varchar(10),
	@FACTURA_FECHAALTAFW_DESDE datetime,
	@FACTURA_FECHAALTAFW_HASTA datetime,
	@FACTURA_HORAALTAFW_DESDE varchar(8),
	@FACTURA_HORAALTAFW_HASTA varchar(8),
	@FACTURA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@FACTURA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@FACTURA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@FACTURA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@FACTURA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@FACTURA_FECHAEXPO_DESDE datetime,
	@FACTURA_FECHAEXPO_HASTA datetime,
	@FACTURA_FECHAIMPO_DESDE datetime,
	@FACTURA_FECHAIMPO_HASTA datetime,
	@FACTURA_FECHAMODIFICACIONFW_DESDE datetime,
	@FACTURA_FECHAMODIFICACIONFW_HASTA datetime,
	@FACTURA_FECHATRANSFERENCIA_DESDE datetime,
	@FACTURA_FECHATRANSFERENCIA_HASTA datetime,
	@FACTURA_HORAEXPO_DESDE varchar(8),
	@FACTURA_HORAEXPO_HASTA varchar(8),
	@FACTURA_HORAIMPO_DESDE varchar(8),
	@FACTURA_HORAIMPO_HASTA varchar(8),
	@FACTURA_HORAMODIFICACIONFW_DESDE varchar(8),
	@FACTURA_HORAMODIFICACIONFW_HASTA varchar(8),
	@FACTURA_SERIEALTAFW_DESDE varchar(7),
	@FACTURA_SERIEALTAFW_HASTA varchar(7),
	@FACTURA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@FACTURA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@FACTURA_USUARIOALTAFW_DESDE varchar(100),
	@FACTURA_USUARIOALTAFW_HASTA varchar(100),
	@FACTURA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@FACTURA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@FACTURA_VERSIONALTAFW_DESDE varchar(13),
	@FACTURA_VERSIONALTAFW_HASTA varchar(13),
	@FACTURA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@FACTURA_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max),
	@Parametro2 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticulosventas.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSVENTAS__Grupo,
	@basededatos as ITEMARTICULOSVENTAS__BD,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticulosventas.fart, c_itemarticulosventas.ccolor, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSVENTAS_1_OrdenPaletaColores,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticulosventas.fart, c_itemarticulosventas.talle, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSVENTAS_1_OrdenCurvaTalles,
	cast( c_itemarticulosventas.fcant*c_factura_cabecera.signomov as numeric( 9, 3 ) ) as ITEMARTICULOSVENTAS_FCANT,
	cast( c_itemarticulosventas.fmonto*c_factura_cabecera.signomov as numeric( 15, 2 ) ) as ITEMARTICULOSVENTAS_FMONTO,
	cast( c_itemarticulosventas.fcfi*c_factura_cabecera.signomov*-1 as numeric( 7, 2 ) ) as ITEMARTICULOSVENTAS_FCFI,
	c_ITEMARTICULOSVENTAS.FART as ITEMARTICULOSVENTAS_FART,
	c_ITEMARTICULOSVENTAS.FTXT as ITEMARTICULOSVENTAS_FTXT,
	c_ITEMARTICULOSVENTAS.CODIGO as ITEMARTICULOSVENTAS_CODIGO,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.fcfitot as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_FCFITot,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.fneto as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_FNETO,
	c_ITEMARTICULOSVENTAS.PRUNCONIMP as ITEMARTICULOSVENTAS_prunconimp,
	c_ITEMARTICULOSVENTAS.FPRECIO as ITEMARTICULOSVENTAS_FPRECIO,
	c_ITEMARTICULOSVENTAS.PRUNSINIMP as ITEMARTICULOSVENTAS_Prunsinimp,
	c_ITEMARTICULOSVENTAS.CCOLOR as ITEMARTICULOSVENTAS_cColor,
	c_ITEMARTICULOSVENTAS.FCOLTXT as ITEMARTICULOSVENTAS_FCOLTXT,
	c_ITEMARTICULOSVENTAS.TALLE as ITEMARTICULOSVENTAS_Talle,
	c_ITEMARTICULOSVENTAS.EQUIV as ITEMARTICULOSVENTAS_Equiv,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.mntdes as numeric( 12, 2 ) ) as ITEMARTICULOSVENTAS_MNTDES,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.mntprecci as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPRECCI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.mntptot as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPTOT,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.mntpper as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPPER,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.mntpdesci as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPDESCI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.mntprecsi as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPRECSI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.mntpdessi as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPDESSI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.mntpiva as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPIVA,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.mnpdsi as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_MNPDSI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.mndesci as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_MNDESCI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*-1*c_itemarticulosventas.mndessi as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_MNDESSI,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.fbruto as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_FBruto,
	c_ITEMARTICULOSVENTAS.TASAIMPINT as ITEMARTICULOSVENTAS_tasaimpint,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.impinterno as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_impinterno,
	cast( c_factura_cabecera.signomov*c_factura_cabecera.cotiz*c_itemarticulosventas.mntpint as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPINT,
	c_ITEMARTICULOSVENTAS.MOTDEVOL as ITEMARTICULOSVENTAS_MotDevol,
	c_ITEMARTICULOSVENTAS.MOTDESCU as ITEMARTICULOSVENTAS_MotDescu,
	c_ITEMARTICULOSVENTAS.CODAUTDJCP as ITEMARTICULOSVENTAS_CodAutDJCP,
	c_ITEMARTICULOSVENTAS.NROITEM as ITEMARTICULOSVENTAS_NroItem,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_EQUIVALENCIA.CCODIGO as EQUIVALENCIA_cCodigo,
	C_MOTIVODESCUENTOYDEVOLUCION149.DESCRIP as MOTIVODESCUENTOYDEVOLUCION149_Descrip,
	C_MOTIVODESCUENTOYDEVOLUCION150.DESCRIP as MOTIVODESCUENTOYDEVOLUCION150_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_MOTIVODESCUENTOYDEVOLUCION149.CODIGO as MOTIVODESCUENTOYDEVOLUCION149_Codigo,
	C_MOTIVODESCUENTOYDEVOLUCION150.CODIGO as MOTIVODESCUENTOYDEVOLUCION150_Codigo,
	C_TALLE.CODIGO as TALLE_Codigo
 from ZooLogic.COMPROBANTEVDET as c_ITEMARTICULOSVENTAS
 left join ZooLogic.EQUI as C_EQUIVALENCIA on C_EQUIVALENCIA.CCODIGO = C_ITEMARTICULOSVENTAS.EQUIV and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.EQUIV )
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSVENTAS.FART and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.FART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSVENTAS.CCOLOR and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.CCOLOR )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION149 on C_MOTIVODESCUENTOYDEVOLUCION149.CODIGO = C_ITEMARTICULOSVENTAS.MOTDEVOL and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.MOTDEVOL )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION150 on C_MOTIVODESCUENTOYDEVOLUCION150.CODIGO = C_ITEMARTICULOSVENTAS.MOTDESCU and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.MOTDESCU )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSVENTAS.TALLE and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.TALLE )
 inner join ZooLogic.COMPROBANTEV as C_FACTURA_CABECERA on C_FACTURA_CABECERA.CODIGO = C_ITEMARTICULOSVENTAS.CODIGO
 left join ZooLogic.AFIP3668 as C_DATOSADICIONALESCOMPROBANTESA_CABECERA on C_DATOSADICIONALESCOMPROBANTESA_CABECERA.CODCOMP = C_FACTURA_CABECERA.CODIGO and 0 = Funciones.empty( C_FACTURA_CABECERA.CODIGO )
 left join ZooLogic.CLI as C_CLIENTE_CABECERA on C_CLIENTE_CABECERA.CLCOD = C_FACTURA_CABECERA.FPERSON and 0 = Funciones.empty( C_FACTURA_CABECERA.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO_CABECERA on C_CONDICIONDEPAGO_CABECERA.CLCOD = C_CLIENTE_CABECERA.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB_CABECERA on C_DATOSADICIONALESSIPRIB_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO30_CABECERA on C_DESCUENTO30_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO42_CABECERA on C_IMPUESTO42_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO45_CABECERA on C_IMPUESTO45_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLPERGAN and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS26_CABECERA on C_LISTADEPRECIOS26_CABECERA.LPR_NUMERO = C_CLIENTE_CABECERA.CLLISPREC and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLLISPREC )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS109_CABECERA on C_LISTADEPRECIOS109_CABECERA.LPR_NUMERO = C_FACTURA_CABECERA.CODLISTA and 0 = Funciones.empty( C_FACTURA_CABECERA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA_CABECERA on C_MONEDA_CABECERA.CODIGO = C_FACTURA_CABECERA.MONEDA and 0 = Funciones.empty( C_FACTURA_CABECERA.MONEDA )
 left join ORGANIZACION.MOTADICA as C_MOTIVODATOSADICIONALESCOMPROBANTESA_CABECERA on C_MOTIVODATOSADICIONALESCOMPROBANTESA_CABECERA.CODIGO = C_DATOSADICIONALESCOMPROBANTESA_CABECERA.MOTIVO and 0 = Funciones.empty( C_DATOSADICIONALESCOMPROBANTESA_CABECERA.MOTIVO )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION64_CABECERA on C_MOTIVODESCUENTOYDEVOLUCION64_CABECERA.CODIGO = C_FACTURA_CABECERA.MOTDESCDEV and 0 = Funciones.empty( C_FACTURA_CABECERA.MOTDESCDEV )
 left join ZooLogic.PAISES as C_PAISES18_CABECERA on C_PAISES18_CABECERA.PCOD = C_CLIENTE_CABECERA.CLPAIS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA20_CABECERA on C_PROVINCIA20_CABECERA.PRV_COD = C_CLIENTE_CABECERA.CLPRV and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL_CABECERA on C_SITUACIONFISCAL_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLIVA and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL_CABECERA on C_SUCURSAL_CABECERA.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE_CABECERA on C_TIPOCLIENTE_CABECERA.TCCOD = C_CLIENTE_CABECERA.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL_CABECERA on C_TIPOSUCURSAL_CABECERA.TCOD = C_SUCURSAL_CABECERA.TIPO and 0 = Funciones.empty( C_SUCURSAL_CABECERA.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA_CABECERA on C_TRANSPORTISTA_CABECERA.TRCOD = C_CLIENTE_CABECERA.CLTRANS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR3_CABECERA on C_VENDEDOR3_CABECERA.CLCOD = C_CLIENTE_CABECERA.CLVEND and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLVEND )
 left join ZooLogic.VEN as C_VENDEDOR9111_CABECERA on C_VENDEDOR9111_CABECERA.CLCOD = C_FACTURA_CABECERA.FVEN and 0 = Funciones.empty( C_FACTURA_CABECERA.FVEN )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA_CABECERA on C_NOMBREDEFANTASIA_CABECERA.NFCOD = C_CLIENTE_CABECERA.CLCODFANT and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE_CABECERA on C_CATEGORIACLIENTE_CABECERA.CGCOD = C_CLIENTE_CABECERA.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE_CABECERA on C_CLASIFICACIONCLIENTE_CABECERA.CLACOD = C_CLIENTE_CABECERA.CLCLAS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCLAS )
 left join ZooLogic.CLASVEND as C_CLASIFICACIONVENDEDOR_CABECERA on C_CLASIFICACIONVENDEDOR_CABECERA.CLACOD = C_VENDEDOR3_CABECERA.CLAS and 0 = Funciones.empty( C_VENDEDOR3_CABECERA.CLAS )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO106_CABECERA on C_DESCUENTO106_CABECERA.CODIGO = C_VENDEDOR3_CABECERA.CLDESC and 0 = Funciones.empty( C_VENDEDOR3_CABECERA.CLDESC )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL_CABECERA on C_LINEASUCURSAL_CABECERA.LSCOD = C_SUCURSAL_CABECERA.LINEA and 0 = Funciones.empty( C_SUCURSAL_CABECERA.LINEA )
 left join ZooLogic.PAISES as C_PAISES102_CABECERA on C_PAISES102_CABECERA.PCOD = C_VENDEDOR3_CABECERA.PPAIS and 0 = Funciones.empty( C_VENDEDOR3_CABECERA.PPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA96_CABECERA on C_PROVINCIA96_CABECERA.PRV_COD = C_VENDEDOR3_CABECERA.CLPRV and 0 = Funciones.empty( C_VENDEDOR3_CABECERA.CLPRV )
 left join ORGANIZACION.SECOD as C_SEGMENTACION_CABECERA on C_SEGMENTACION_CABECERA.SCOD = C_SUCURSAL_CABECERA.SEG and 0 = Funciones.empty( C_SUCURSAL_CABECERA.SEG )
 where ( ( case when @parametro1 = '' or @parametro1 = 'todos' then 1 else 0 end = 1 ) or (case when @parametro1 = 'sinpromo' then 0 else 1 end = coalesce( ( select top 1 1 from zoologic.promdet as ap where ap.codigo = c_factura_cabecera.codigo ), 0) ) ) and 
	( ( case when @parametro2 = '' or @parametro2 = 'todos' then 0 else -1 end = 0 )
	 or ( case when @parametro2 = 'posterior' then 1 else -1 end = c_factura_cabecera.entregapos ) 
	 or ( case when @parametro2 = 'inmediata' then c_factura_cabecera.entregapos else -1 end in (0,2) )
	 or ( case when @Parametro2 = 'venta continua' then 3 else -1 end = c_factura_cabecera.entregapos ) ) and
	--( ( @FACTURA_DESPACHOS_DESDE is null ) OR ( C_FACTURA_CABECERA.Despachos >= @FACTURA_DESPACHOS_DESDE ) ) and 
	--( ( @FACTURA_DESPACHOS_HASTA is null ) OR ( C_FACTURA_CABECERA.Despachos <= @FACTURA_DESPACHOS_HASTA ) ) and 
	( ( @FACTURA_DESPACHOS_DESDE is null ) OR (Funciones.Alltrim(c_factura_cabecera.Despachos) LIKE '%' + Funciones.Alltrim(@FACTURA_DESPACHOS_DESDE) + '%') ) and
	( ( @DATOSADICIONALESCOMPROBANTESA_1_SUSCRIBE is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA_CABECERA.Suscribe = @DATOSADICIONALESCOMPROBANTESA_1_SUSCRIBE ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_DESDE is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA_CABECERA.Tipodoc >= @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_DESDE ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_HASTA is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA_CABECERA.Tipodoc <= @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_HASTA ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_DESDE is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA_CABECERA.NroDoc >= @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_DESDE ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_HASTA is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA_CABECERA.NroDoc <= @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_HASTA ) ) and 
	( ( @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_DESDE is null ) OR ( C_MOTIVODATOSADICIONALESCOMPROBANTESA_CABECERA.Descrip >= @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_HASTA is null ) OR ( C_MOTIVODATOSADICIONALESCOMPROBANTESA_CABECERA.Descrip <= @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_HASTA ) ) and 
	( ( @FACTURA_VENDEDOR_DESDE is null ) OR ( C_FACTURA_CABECERA.FVEN >= @FACTURA_VENDEDOR_DESDE ) ) and 
	( ( @FACTURA_VENDEDOR_HASTA is null ) OR ( C_FACTURA_CABECERA.FVEN <= @FACTURA_VENDEDOR_HASTA ) ) and 
	( ( @FACTURA_CLIENTE_DESDE is null ) OR ( C_FACTURA_CABECERA.FPerson >= @FACTURA_CLIENTE_DESDE ) ) and 
	( ( @FACTURA_CLIENTE_HASTA is null ) OR ( C_FACTURA_CABECERA.FPerson <= @FACTURA_CLIENTE_HASTA ) ) and 
	( C_FACTURA_CABECERA.FACTTIPO in ( 1, 2, 3, 4, 5, 6, 27, 28, 29, 33, 35, 36, 47, 48, 49, 51, 52, 53, 54, 55, 56 ) ) and 
	( ( @FACTURA_TIPOCOMPROBANTE is null ) OR ( ( -2 = @FACTURA_TIPOCOMPROBANTE ) AND ( C_FACTURA_CABECERA.FACTTIPO in ( 2, 5, 6, 51, 52, 53 ) ) ) OR ( ( -3 = @FACTURA_TIPOCOMPROBANTE ) AND ( C_FACTURA_CABECERA.FACTTIPO in ( 1, 3, 4 ) ) ) OR ( ( -4 = @FACTURA_TIPOCOMPROBANTE ) AND ( C_FACTURA_CABECERA.FACTTIPO in ( 27, 28, 29, 33, 35, 36, 54, 55, 56 ) ) ) OR ( ( -5 = @FACTURA_TIPOCOMPROBANTE ) AND ( C_FACTURA_CABECERA.FACTTIPO in ( 47, 48, 49 ) ) ) OR ( C_FACTURA_CABECERA.FACTTIPO = @FACTURA_TIPOCOMPROBANTE ) ) and 
	( ( @FACTURA_ANULADO is null ) OR ( C_FACTURA_CABECERA.Anulado = @FACTURA_ANULADO ) ) and 
	( ( @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE is null ) OR ( C_FACTURA_CABECERA.MotDescDev >= @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE ) ) and 
	( ( @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA is null ) OR ( C_FACTURA_CABECERA.MotDescDev <= @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA ) ) and 
	( ( @FACTURA_NROOPECOMMERCE_DESDE is null ) OR ( C_FACTURA_CABECERA.OPEcomm >= @FACTURA_NROOPECOMMERCE_DESDE ) ) and 
	( ( @FACTURA_NROOPECOMMERCE_HASTA is null ) OR ( C_FACTURA_CABECERA.OPEcomm <= @FACTURA_NROOPECOMMERCE_HASTA ) ) and 
	( ( @FACTURA_CLIENTEDESCRIPCION_DESDE is null ) OR ( C_FACTURA_CABECERA.FCLIENTE >= @FACTURA_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @FACTURA_CLIENTEDESCRIPCION_HASTA is null ) OR ( C_FACTURA_CABECERA.FCLIENTE <= @FACTURA_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @FACTURA_MONEDACOMPROBANTE_DESDE is null ) OR ( C_FACTURA_CABECERA.Moneda >= @FACTURA_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURA_MONEDACOMPROBANTE_HASTA is null ) OR ( C_FACTURA_CABECERA.Moneda <= @FACTURA_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @FACTURA_LISTADEPRECIOS_DESDE is null ) OR ( C_FACTURA_CABECERA.CodLista >= @FACTURA_LISTADEPRECIOS_DESDE ) ) and 
	( ( @FACTURA_LISTADEPRECIOS_HASTA is null ) OR ( C_FACTURA_CABECERA.CodLista <= @FACTURA_LISTADEPRECIOS_HASTA ) ) and 
	( ( @FACTURA_EMAIL_DESDE is null ) OR ( C_FACTURA_CABECERA.Email >= @FACTURA_EMAIL_DESDE ) ) and 
	( ( @FACTURA_EMAIL_HASTA is null ) OR ( C_FACTURA_CABECERA.Email <= @FACTURA_EMAIL_HASTA ) ) and 
	( ( @FACTURA_LETRA_DESDE is null ) OR ( C_FACTURA_CABECERA.FLETRA >= @FACTURA_LETRA_DESDE ) ) and 
	( ( @FACTURA_LETRA_HASTA is null ) OR ( C_FACTURA_CABECERA.FLETRA <= @FACTURA_LETRA_HASTA ) ) and 
	( ( @FACTURA_PUNTODEVENTA_DESDE is null ) OR ( C_FACTURA_CABECERA.FPTOVEN >= @FACTURA_PUNTODEVENTA_DESDE ) ) and 
	( ( @FACTURA_PUNTODEVENTA_HASTA is null ) OR ( C_FACTURA_CABECERA.FPTOVEN <= @FACTURA_PUNTODEVENTA_HASTA ) ) and 
	( ( @FACTURA_NUMERO_DESDE is null ) OR ( C_FACTURA_CABECERA.FNUMCOMP >= @FACTURA_NUMERO_DESDE ) ) and 
	( ( @FACTURA_NUMERO_HASTA is null ) OR ( C_FACTURA_CABECERA.FNUMCOMP <= @FACTURA_NUMERO_HASTA ) ) and 
	( ( @FACTURA_FECHA_DESDE is null ) OR ( C_FACTURA_CABECERA.FFCH >= @FACTURA_FECHA_DESDE ) ) and 
	( ( @FACTURA_FECHA_HASTA is null ) OR ( C_FACTURA_CABECERA.FFCH <= @FACTURA_FECHA_HASTA ) ) and 
	( ( @FACTURA_COTIZACION_DESDE is null ) OR ( C_FACTURA_CABECERA.Cotiz >= @FACTURA_COTIZACION_DESDE ) ) and 
	( ( @FACTURA_COTIZACION_HASTA is null ) OR ( C_FACTURA_CABECERA.Cotiz <= @FACTURA_COTIZACION_HASTA ) ) and 
	( ( @FACTURA_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_FACTURA_CABECERA.FPODES >= @FACTURA_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @FACTURA_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_FACTURA_CABECERA.FPODES <= @FACTURA_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @FACTURA_RECARGOPORCENTAJE_DESDE is null ) OR ( C_FACTURA_CABECERA.RecPor >= @FACTURA_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @FACTURA_RECARGOPORCENTAJE_HASTA is null ) OR ( C_FACTURA_CABECERA.RecPor <= @FACTURA_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNOM >= @CLIENTE_2_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNOM <= @CLIENTE_2_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION64_CABECERA.Descrip >= @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION64_CABECERA.Descrip <= @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA ) ) and 
	( ( @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA_CABECERA.Descrip >= @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA_CABECERA.Descrip <= @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS109_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS109_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION_CABECERA.SDES >= @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION_CABECERA.SDES <= @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9249_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES >= @LINEASUCURSAL_9249_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9249_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES <= @LINEASUCURSAL_9249_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES >= @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES <= @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR3_CABECERA.CLNOM >= @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR3_CABECERA.CLNOM <= @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES18_CABECERA.pdes >= @PAISES_18_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES18_CABECERA.pdes <= @PAISES_18_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA20_CABECERA.PRV_DES >= @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA20_CABECERA.PRV_DES <= @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS26_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS26_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE_CABECERA.CLADES >= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE_CABECERA.CLADES <= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO30_CABECERA.Des >= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO30_CABECERA.Des <= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA_CABECERA.TRNOM >= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA_CABECERA.TRNOM <= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA_CABECERA.NFCOD >= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA_CABECERA.NFCOD <= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE_CABECERA.TCDES >= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE_CABECERA.TCDES <= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE_CABECERA.CGDes >= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE_CABECERA.CGDes <= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO_CABECERA.CLNOM >= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO_CABECERA.CLNOM <= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO42_CABECERA.descrip >= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO42_CABECERA.descrip <= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO45_CABECERA.descrip >= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO45_CABECERA.descrip <= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip >= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip <= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_96_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA96_CABECERA.PRV_DES >= @PROVINCIA_96_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_96_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA96_CABECERA.PRV_DES <= @PROVINCIA_96_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_102_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES102_CABECERA.pdes >= @PAISES_102_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_102_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES102_CABECERA.pdes <= @PAISES_102_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONVENDEDOR_CABECERA.CLADES >= @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONVENDEDOR_CABECERA.CLADES <= @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO106_CABECERA.Des >= @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO106_CABECERA.Des <= @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_9111_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLNOM >= @VENDEDOR_9111_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_9111_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLNOM <= @VENDEDOR_9111_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @SUCURSAL_9245_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.seg >= @SUCURSAL_9245_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9245_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.seg <= @SUCURSAL_9245_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9245_LINEA_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Linea >= @SUCURSAL_9245_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9245_LINEA_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Linea <= @SUCURSAL_9245_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9245_TIPO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Tipo >= @SUCURSAL_9245_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9245_TIPO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Tipo <= @SUCURSAL_9245_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9245_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.descrip >= @SUCURSAL_9245_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9245_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.descrip <= @SUCURSAL_9245_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_2_VENDEDOR_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLVend >= @CLIENTE_2_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_2_VENDEDOR_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLVend <= @CLIENTE_2_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_2_CALLE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCalle >= @CLIENTE_2_CALLE_DESDE ) ) and 
	( ( @CLIENTE_2_CALLE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCalle <= @CLIENTE_2_CALLE_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCP >= @CLIENTE_2_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCP <= @CLIENTE_2_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_2_CUIT_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCUIT >= @CLIENTE_2_CUIT_DESDE ) ) and 
	( ( @CLIENTE_2_CUIT_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCUIT <= @CLIENTE_2_CUIT_HASTA ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLDEPTO >= @CLIENTE_2_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLDEPTO <= @CLIENTE_2_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_EMAIL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLEMAIL >= @CLIENTE_2_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_2_EMAIL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLEMAIL <= @CLIENTE_2_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_2_FAX_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLFAX >= @CLIENTE_2_FAX_DESDE ) ) and 
	( ( @CLIENTE_2_FAX_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLFAX <= @CLIENTE_2_FAX_HASTA ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLFECHA >= @CLIENTE_2_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLFECHA <= @CLIENTE_2_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_2_IMAGEN_DESDE is null ) OR ( C_CLIENTE_CABECERA.CIMAGEN >= @CLIENTE_2_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_2_IMAGEN_HASTA is null ) OR ( C_CLIENTE_CABECERA.CIMAGEN <= @CLIENTE_2_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLLOC >= @CLIENTE_2_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLLOC <= @CLIENTE_2_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNRODOC >= @CLIENTE_2_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNRODOC <= @CLIENTE_2_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_NUMERO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNro >= @CLIENTE_2_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_2_NUMERO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNro <= @CLIENTE_2_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPAGEWEB >= @CLIENTE_2_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPAGEWEB <= @CLIENTE_2_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_2_PAIS_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPAIS >= @CLIENTE_2_PAIS_DESDE ) ) and 
	( ( @CLIENTE_2_PAIS_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPAIS <= @CLIENTE_2_PAIS_HASTA ) ) and 
	( ( @CLIENTE_2_PISO_DESDE is null ) OR ( C_CLIENTE_CABECERA.ClPiso >= @CLIENTE_2_PISO_DESDE ) ) and 
	( ( @CLIENTE_2_PISO_HASTA is null ) OR ( C_CLIENTE_CABECERA.ClPiso <= @CLIENTE_2_PISO_HASTA ) ) and 
	( ( @CLIENTE_2_PROVINCIA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPRV >= @CLIENTE_2_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_2_PROVINCIA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPRV <= @CLIENTE_2_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL_CABECERA.Descrip = @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_2_TELEFONO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTLF >= @CLIENTE_2_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_2_TELEFONO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTLF <= @CLIENTE_2_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTIPODOC >= @CLIENTE_2_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTIPODOC <= @CLIENTE_2_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_MOVIL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLMovil >= @CLIENTE_2_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_2_MOVIL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLMovil <= @CLIENTE_2_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTOPECCTE >= @CLIENTE_2_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTOPECCTE <= @CLIENTE_2_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLLisPrec >= @CLIENTE_2_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLLisPrec <= @CLIENTE_2_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCLAS >= @CLIENTE_2_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCLAS <= @CLIENTE_2_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTIPCONV >= @CLIENTE_2_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTIPCONV <= @CLIENTE_2_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_2_NROIIBB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNROIIBB >= @CLIENTE_2_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_2_NROIIBB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNROIIBB <= @CLIENTE_2_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCO_DTO >= @CLIENTE_2_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCO_DTO <= @CLIENTE_2_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTRANS >= @CLIENTE_2_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTRANS <= @CLIENTE_2_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_2_ESTADOCIVIL is null ) OR ( C_CLIENTE_CABECERA.Estado = @CLIENTE_2_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_2_HIJOS_DESDE is null ) OR ( C_CLIENTE_CABECERA.Hijos >= @CLIENTE_2_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_2_HIJOS_HASTA is null ) OR ( C_CLIENTE_CABECERA.Hijos <= @CLIENTE_2_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_2_SEXO is null ) OR ( C_CLIENTE_CABECERA.Sexo = @CLIENTE_2_SEXO ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE_CABECERA.globalid >= @CLIENTE_2_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE_CABECERA.globalid <= @CLIENTE_2_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_2_RUT_DESDE is null ) OR ( C_CLIENTE_CABECERA.RUT >= @CLIENTE_2_RUT_DESDE ) ) and 
	( ( @CLIENTE_2_RUT_HASTA is null ) OR ( C_CLIENTE_CABECERA.RUT <= @CLIENTE_2_RUT_HASTA ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCODFANT >= @CLIENTE_2_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCODFANT <= @CLIENTE_2_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCLI_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTipoCli >= @CLIENTE_2_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCLI_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTipoCli <= @CLIENTE_2_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CATEGCLI_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCategCli >= @CLIENTE_2_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_2_CATEGCLI_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCategCli <= @CLIENTE_2_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCONDPAG >= @CLIENTE_2_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCONDPAG <= @CLIENTE_2_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_2_SUJETOVINCULADO is null ) OR ( C_CLIENTE_CABECERA.CLSujVinc = @CLIENTE_2_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPERTIVA >= @CLIENTE_2_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPERTIVA <= @CLIENTE_2_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_2_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE_CABECERA.CLSITGAN = @CLIENTE_2_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE_CABECERA.EXPERIVA = @CLIENTE_2_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPERGAN >= @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPERGAN <= @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE_CABECERA.EXPERGAN = @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CODRECOM >= @CLIENTE_2_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CODRECOM <= @CLIENTE_2_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.NOMRECOM >= @CLIENTE_2_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.NOMRECOM <= @CLIENTE_2_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPRINOM >= @CLIENTE_2_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPRINOM <= @CLIENTE_2_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLSEGNOM >= @CLIENTE_2_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLSEGNOM <= @CLIENTE_2_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_APELLIDO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLAPELL >= @CLIENTE_2_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_2_APELLIDO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLAPELL <= @CLIENTE_2_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE_CABECERA.VHastaIva >= @CLIENTE_2_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE_CABECERA.VHastaIva <= @CLIENTE_2_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE_CABECERA.VHastaGan >= @CLIENTE_2_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE_CABECERA.VHastaGan <= @CLIENTE_2_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLSIPRIB >= @CLIENTE_2_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLSIPRIB <= @CLIENTE_2_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE_CABECERA.PorcenTC >= @CLIENTE_2_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE_CABECERA.PorcenTC <= @CLIENTE_2_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROAPLICA is null ) OR ( C_CLIENTE_CABECERA.AplicaTC = @CLIENTE_2_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_2_INACTIVOFW is null ) OR ( C_CLIENTE_CABECERA.InactivoFW = @CLIENTE_2_INACTIVOFW ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_64_TIPO is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION64_CABECERA.Tipo = @MOTIVODESCUENTOYDEVOLUCION_64_TIPO ) ) and 
	( ( @VENDEDOR_9111_CODIGOPOSTAL_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLCP >= @VENDEDOR_9111_CODIGOPOSTAL_DESDE ) ) and 
	( ( @VENDEDOR_9111_CODIGOPOSTAL_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLCP <= @VENDEDOR_9111_CODIGOPOSTAL_HASTA ) ) and 
	( ( @VENDEDOR_9111_CALLE_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLDIR >= @VENDEDOR_9111_CALLE_DESDE ) ) and 
	( ( @VENDEDOR_9111_CALLE_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLDIR <= @VENDEDOR_9111_CALLE_HASTA ) ) and 
	( ( @VENDEDOR_9111_NRODOCUMENTO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLNRODOC >= @VENDEDOR_9111_NRODOCUMENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_NRODOCUMENTO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLNRODOC <= @VENDEDOR_9111_NRODOCUMENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_EMAIL_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLEMAIL >= @VENDEDOR_9111_EMAIL_DESDE ) ) and 
	( ( @VENDEDOR_9111_EMAIL_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLEMAIL <= @VENDEDOR_9111_EMAIL_HASTA ) ) and 
	( ( @VENDEDOR_9111_FECHAINGRESO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLFING >= @VENDEDOR_9111_FECHAINGRESO_DESDE ) ) and 
	( ( @VENDEDOR_9111_FECHAINGRESO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLFING <= @VENDEDOR_9111_FECHAINGRESO_HASTA ) ) and 
	( ( @VENDEDOR_9111_FECHANACIMIENTO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLFECHA >= @VENDEDOR_9111_FECHANACIMIENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_FECHANACIMIENTO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLFECHA <= @VENDEDOR_9111_FECHANACIMIENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_IMAGEN_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CIMAGEN >= @VENDEDOR_9111_IMAGEN_DESDE ) ) and 
	( ( @VENDEDOR_9111_IMAGEN_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CIMAGEN <= @VENDEDOR_9111_IMAGEN_HASTA ) ) and 
	( ( @VENDEDOR_9111_LOCALIDAD_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLLOC >= @VENDEDOR_9111_LOCALIDAD_DESDE ) ) and 
	( ( @VENDEDOR_9111_LOCALIDAD_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLLOC <= @VENDEDOR_9111_LOCALIDAD_HASTA ) ) and 
	( ( @VENDEDOR_9111_PROVINCIA_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLPRV >= @VENDEDOR_9111_PROVINCIA_DESDE ) ) and 
	( ( @VENDEDOR_9111_PROVINCIA_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLPRV <= @VENDEDOR_9111_PROVINCIA_HASTA ) ) and 
	( ( @VENDEDOR_9111_TELEFONO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLTLF >= @VENDEDOR_9111_TELEFONO_DESDE ) ) and 
	( ( @VENDEDOR_9111_TELEFONO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLTLF <= @VENDEDOR_9111_TELEFONO_HASTA ) ) and 
	( ( @VENDEDOR_9111_TIPODOCUMENTO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLTIPODOC >= @VENDEDOR_9111_TIPODOCUMENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_TIPODOCUMENTO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLTIPODOC <= @VENDEDOR_9111_TIPODOCUMENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_NUMERO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLNUM >= @VENDEDOR_9111_NUMERO_DESDE ) ) and 
	( ( @VENDEDOR_9111_NUMERO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLNUM <= @VENDEDOR_9111_NUMERO_HASTA ) ) and 
	( ( @VENDEDOR_9111_PISO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLPISO >= @VENDEDOR_9111_PISO_DESDE ) ) and 
	( ( @VENDEDOR_9111_PISO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLPISO <= @VENDEDOR_9111_PISO_HASTA ) ) and 
	( ( @VENDEDOR_9111_DEPARTAMENTO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLDEPTO >= @VENDEDOR_9111_DEPARTAMENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_DEPARTAMENTO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLDEPTO <= @VENDEDOR_9111_DEPARTAMENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_PAIS_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.PPAIS >= @VENDEDOR_9111_PAIS_DESDE ) ) and 
	( ( @VENDEDOR_9111_PAIS_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.PPAIS <= @VENDEDOR_9111_PAIS_HASTA ) ) and 
	( ( @VENDEDOR_9111_FECHAEGRESO_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLFEGR >= @VENDEDOR_9111_FECHAEGRESO_DESDE ) ) and 
	( ( @VENDEDOR_9111_FECHAEGRESO_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLFEGR <= @VENDEDOR_9111_FECHAEGRESO_HASTA ) ) and 
	( ( @VENDEDOR_9111_MOVIL_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLTLFM >= @VENDEDOR_9111_MOVIL_DESDE ) ) and 
	( ( @VENDEDOR_9111_MOVIL_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLTLFM <= @VENDEDOR_9111_MOVIL_HASTA ) ) and 
	( ( @VENDEDOR_9111_CLASIFICACION_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLAS >= @VENDEDOR_9111_CLASIFICACION_DESDE ) ) and 
	( ( @VENDEDOR_9111_CLASIFICACION_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLAS <= @VENDEDOR_9111_CLASIFICACION_HASTA ) ) and 
	( ( @VENDEDOR_9111_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_VENDEDOR9111_CABECERA.CLDESC >= @VENDEDOR_9111_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @VENDEDOR_9111_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_VENDEDOR9111_CABECERA.CLDESC <= @VENDEDOR_9111_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @VENDEDOR_9111_INACTIVOFW is null ) OR ( C_VENDEDOR9111_CABECERA.InactivoFW = @VENDEDOR_9111_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9245_CODIGO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.codigo >= @SUCURSAL_9245_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9245_CODIGO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.codigo <= @SUCURSAL_9245_CODIGO_HASTA ) ) and 
	( ( @FACTURA_FECHAALTAFW_DESDE is null ) OR ( C_FACTURA_CABECERA.FAltaFW >= @FACTURA_FECHAALTAFW_DESDE ) ) and 
	( ( @FACTURA_FECHAALTAFW_HASTA is null ) OR ( C_FACTURA_CABECERA.FAltaFW <= @FACTURA_FECHAALTAFW_HASTA ) ) and 
	( ( @FACTURA_HORAALTAFW_DESDE is null ) OR ( C_FACTURA_CABECERA.HAltaFW >= @FACTURA_HORAALTAFW_DESDE ) ) and 
	( ( @FACTURA_HORAALTAFW_HASTA is null ) OR ( C_FACTURA_CABECERA.HAltaFW <= @FACTURA_HORAALTAFW_HASTA ) ) and 
	( ( @FACTURA_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_FACTURA_CABECERA.BDALTAFW >= @FACTURA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @FACTURA_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_FACTURA_CABECERA.BDALTAFW <= @FACTURA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA_CABECERA.BDMODIFW >= @FACTURA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA_CABECERA.BDMODIFW <= @FACTURA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_FACTURA_CABECERA.ESTTRANS >= @FACTURA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_FACTURA_CABECERA.ESTTRANS <= @FACTURA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURA_FECHAEXPO_DESDE is null ) OR ( C_FACTURA_CABECERA.FECEXPO >= @FACTURA_FECHAEXPO_DESDE ) ) and 
	( ( @FACTURA_FECHAEXPO_HASTA is null ) OR ( C_FACTURA_CABECERA.FECEXPO <= @FACTURA_FECHAEXPO_HASTA ) ) and 
	( ( @FACTURA_FECHAIMPO_DESDE is null ) OR ( C_FACTURA_CABECERA.FECIMPO >= @FACTURA_FECHAIMPO_DESDE ) ) and 
	( ( @FACTURA_FECHAIMPO_HASTA is null ) OR ( C_FACTURA_CABECERA.FECIMPO <= @FACTURA_FECHAIMPO_HASTA ) ) and 
	( ( @FACTURA_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA_CABECERA.FMODIFW >= @FACTURA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA_CABECERA.FMODIFW <= @FACTURA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_FECHATRANSFERENCIA_DESDE is null ) OR ( C_FACTURA_CABECERA.FECTRANS >= @FACTURA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURA_FECHATRANSFERENCIA_HASTA is null ) OR ( C_FACTURA_CABECERA.FECTRANS <= @FACTURA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURA_HORAEXPO_DESDE is null ) OR ( C_FACTURA_CABECERA.HORAEXPO >= @FACTURA_HORAEXPO_DESDE ) ) and 
	( ( @FACTURA_HORAEXPO_HASTA is null ) OR ( C_FACTURA_CABECERA.HORAEXPO <= @FACTURA_HORAEXPO_HASTA ) ) and 
	( ( @FACTURA_HORAIMPO_DESDE is null ) OR ( C_FACTURA_CABECERA.HORAIMPO >= @FACTURA_HORAIMPO_DESDE ) ) and 
	( ( @FACTURA_HORAIMPO_HASTA is null ) OR ( C_FACTURA_CABECERA.HORAIMPO <= @FACTURA_HORAIMPO_HASTA ) ) and 
	( ( @FACTURA_HORAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA_CABECERA.HMODIFW >= @FACTURA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_HORAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA_CABECERA.HMODIFW <= @FACTURA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_SERIEALTAFW_DESDE is null ) OR ( C_FACTURA_CABECERA.SALTAFW >= @FACTURA_SERIEALTAFW_DESDE ) ) and 
	( ( @FACTURA_SERIEALTAFW_HASTA is null ) OR ( C_FACTURA_CABECERA.SALTAFW <= @FACTURA_SERIEALTAFW_HASTA ) ) and 
	( ( @FACTURA_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA_CABECERA.SMODIFW >= @FACTURA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA_CABECERA.SMODIFW <= @FACTURA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_USUARIOALTAFW_DESDE is null ) OR ( C_FACTURA_CABECERA.UALTAFW >= @FACTURA_USUARIOALTAFW_DESDE ) ) and 
	( ( @FACTURA_USUARIOALTAFW_HASTA is null ) OR ( C_FACTURA_CABECERA.UALTAFW <= @FACTURA_USUARIOALTAFW_HASTA ) ) and 
	( ( @FACTURA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA_CABECERA.UMODIFW >= @FACTURA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA_CABECERA.UMODIFW <= @FACTURA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_VERSIONALTAFW_DESDE is null ) OR ( C_FACTURA_CABECERA.VALTAFW >= @FACTURA_VERSIONALTAFW_DESDE ) ) and 
	( ( @FACTURA_VERSIONALTAFW_HASTA is null ) OR ( C_FACTURA_CABECERA.VALTAFW <= @FACTURA_VERSIONALTAFW_HASTA ) ) and 
	( ( @FACTURA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA_CABECERA.VMODIFW >= @FACTURA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA_CABECERA.VMODIFW <= @FACTURA_VERSIONMODIFICACIONFW_HASTA ) )

)