IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_MOVIMIENTOBANCARIO_MOVIMIENTOBANCARIO]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_MOVIMIENTOBANCARIO_MOVIMIENTOBANCARIO];
GO;

CREATE FUNCTION [Listados].[GENERICO_MOVIMIENTOBANCARIO_MOVIMIENTOBANCARIO]
( @BaseDeDatos varchar(8),
	@CUENTABANCARIA_21_NUMERO_DESDE varchar(15),
	@CUENTABANCARIA_21_NUMERO_HASTA varchar(15),
	@CUENTABANCARIA_21_MONEDACUENTA_DESDE varchar(10),
	@CUENTABANCARIA_21_MONEDACUENTA_HASTA varchar(10),
	@MOVIMIENTOBANCARIO_IDENTIFICADOR_DESDE varchar(20),
	@MOVIMIENTOBANCARIO_IDENTIFICADOR_HASTA varchar(20),
	@MOVIMIENTOBANCARIO_CUENTABANCARIA_DESDE varchar(5),
	@MOVIMIENTOBANCARIO_CUENTABANCARIA_HASTA varchar(5),
	@MOVIMIENTOBANCARIO_ORDEN_DESDE numeric(5, 0),
	@MOVIMIENTOBANCARIO_ORDEN_HASTA numeric(5, 0),
	@MOVIMIENTOBANCARIO_FECHA_DESDE datetime,
	@MOVIMIENTOBANCARIO_FECHA_HASTA datetime,
	@MOVIMIENTOBANCARIO_HORA_DESDE varchar(5),
	@MOVIMIENTOBANCARIO_HORA_HASTA varchar(5),
	@MOVIMIENTOBANCARIO_CONCEPTO_DESDE varchar(10),
	@MOVIMIENTOBANCARIO_CONCEPTO_HASTA varchar(10),
	@MOVIMIENTOBANCARIO_REFERENCIA_DESDE varchar(100),
	@MOVIMIENTOBANCARIO_REFERENCIA_HASTA varchar(100),
	@MOVIMIENTOBANCARIO_DATOADICIONAL1_DESDE varchar(50),
	@MOVIMIENTOBANCARIO_DATOADICIONAL1_HASTA varchar(50),
	@MOVIMIENTOBANCARIO_DATOADICIONAL2_DESDE varchar(50),
	@MOVIMIENTOBANCARIO_DATOADICIONAL2_HASTA varchar(50),
	@MOVIMIENTOBANCARIO_DATOADICIONAL3_DESDE varchar(50),
	@MOVIMIENTOBANCARIO_DATOADICIONAL3_HASTA varchar(50),
	@MOVIMIENTOBANCARIO_NUMERO_DESDE numeric(10, 0),
	@MOVIMIENTOBANCARIO_NUMERO_HASTA numeric(10, 0),
	@MOVIMIENTOBANCARIO_IMPORTE_DESDE numeric(15, 2),
	@MOVIMIENTOBANCARIO_IMPORTE_HASTA numeric(15, 2),
	@MOVIMIENTOBANCARIO_SALDO_DESDE numeric(15, 2),
	@MOVIMIENTOBANCARIO_SALDO_HASTA numeric(15, 2),
	@CUENTABANCARIA_21_CUENTABANCARIA_DESCRIPCION_DESDE varchar(40),
	@CUENTABANCARIA_21_CUENTABANCARIA_DESCRIPCION_HASTA varchar(40),
	@CONCEPTOENTIDADFINANCIERA_25_CONCEPTO_CONCEPTO_DESDE varchar(100),
	@CONCEPTOENTIDADFINANCIERA_25_CONCEPTO_CONCEPTO_HASTA varchar(100),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA varchar(50),
	@MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE varchar(40),
	@MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_9144_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9144_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9144_LINEA_DESDE varchar(10),
	@SUCURSAL_9144_LINEA_HASTA varchar(10),
	@SUCURSAL_9144_TIPO_DESDE varchar(10),
	@SUCURSAL_9144_TIPO_HASTA varchar(10),
	@SUCURSAL_9144_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9144_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9144_CODIGO_DESDE varchar(10),
	@SUCURSAL_9144_CODIGO_HASTA varchar(10),
	@MOVIMIENTOBANCARIO_BASEDEDATOSALTAFW_DESDE varchar(8),
	@MOVIMIENTOBANCARIO_BASEDEDATOSALTAFW_HASTA varchar(8),
	@MOVIMIENTOBANCARIO_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@MOVIMIENTOBANCARIO_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@MOVIMIENTOBANCARIO_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@MOVIMIENTOBANCARIO_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@MOVIMIENTOBANCARIO_FECHAALTAFW_DESDE datetime,
	@MOVIMIENTOBANCARIO_FECHAALTAFW_HASTA datetime,
	@MOVIMIENTOBANCARIO_FECHAEXPO_DESDE datetime,
	@MOVIMIENTOBANCARIO_FECHAEXPO_HASTA datetime,
	@MOVIMIENTOBANCARIO_FECHAIMPO_DESDE datetime,
	@MOVIMIENTOBANCARIO_FECHAIMPO_HASTA datetime,
	@MOVIMIENTOBANCARIO_FECHAMODIFICACIONFW_DESDE datetime,
	@MOVIMIENTOBANCARIO_FECHAMODIFICACIONFW_HASTA datetime,
	@MOVIMIENTOBANCARIO_FECHATRANSFERENCIA_DESDE datetime,
	@MOVIMIENTOBANCARIO_FECHATRANSFERENCIA_HASTA datetime,
	@MOVIMIENTOBANCARIO_HORAALTAFW_DESDE varchar(8),
	@MOVIMIENTOBANCARIO_HORAALTAFW_HASTA varchar(8),
	@MOVIMIENTOBANCARIO_HORAEXPO_DESDE varchar(8),
	@MOVIMIENTOBANCARIO_HORAEXPO_HASTA varchar(8),
	@MOVIMIENTOBANCARIO_HORAIMPO_DESDE varchar(8),
	@MOVIMIENTOBANCARIO_HORAIMPO_HASTA varchar(8),
	@MOVIMIENTOBANCARIO_HORAMODIFICACIONFW_DESDE varchar(8),
	@MOVIMIENTOBANCARIO_HORAMODIFICACIONFW_HASTA varchar(8),
	@MOVIMIENTOBANCARIO_SERIEALTAFW_DESDE varchar(7),
	@MOVIMIENTOBANCARIO_SERIEALTAFW_HASTA varchar(7),
	@MOVIMIENTOBANCARIO_SERIEMODIFICACIONFW_DESDE varchar(7),
	@MOVIMIENTOBANCARIO_SERIEMODIFICACIONFW_HASTA varchar(7),
	@MOVIMIENTOBANCARIO_USUARIOALTAFW_DESDE varchar(100),
	@MOVIMIENTOBANCARIO_USUARIOALTAFW_HASTA varchar(100),
	@MOVIMIENTOBANCARIO_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@MOVIMIENTOBANCARIO_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@MOVIMIENTOBANCARIO_VERSIONALTAFW_DESDE varchar(13),
	@MOVIMIENTOBANCARIO_VERSIONALTAFW_HASTA varchar(13),
	@MOVIMIENTOBANCARIO_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@MOVIMIENTOBANCARIO_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_movimientobancario.codigo, 38, ' ' ) as varchar( 46 ) ) as MOVIMIENTOBANCARIO__Grupo,
	@basededatos as MOVIMIENTOBANCARIO__BD,
	c_MOVIMIENTOBANCARIO.CODIGO as MOVIMIENTOBANCARIO_Codigo,
	c_MOVIMIENTOBANCARIO.CTABANC as MOVIMIENTOBANCARIO_CtaBanc,
	c_MOVIMIENTOBANCARIO.ORDEN as MOVIMIENTOBANCARIO_Orden,
	case when c_movimientobancario.fecha = '01/01/1900 00:00:00' then null else c_movimientobancario.fecha end as MOVIMIENTOBANCARIO_Fecha,
	c_MOVIMIENTOBANCARIO.HORA as MOVIMIENTOBANCARIO_Hora,
	c_MOVIMIENTOBANCARIO.CONCEPTO as MOVIMIENTOBANCARIO_Concepto,
	c_MOVIMIENTOBANCARIO.REFE as MOVIMIENTOBANCARIO_Refe,
	c_MOVIMIENTOBANCARIO.DATAD1 as MOVIMIENTOBANCARIO_DatAd1,
	c_MOVIMIENTOBANCARIO.DATAD2 as MOVIMIENTOBANCARIO_DatAd2,
	c_MOVIMIENTOBANCARIO.DATAD3 as MOVIMIENTOBANCARIO_DatAd3,
	c_MOVIMIENTOBANCARIO.NUMERO as MOVIMIENTOBANCARIO_Numero,
	c_MOVIMIENTOBANCARIO.IMPORTE as MOVIMIENTOBANCARIO_Importe,
	c_MOVIMIENTOBANCARIO.SALDO as MOVIMIENTOBANCARIO_Saldo,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_MOVIMIENTOBANCARIO.BDALTAFW as MOVIMIENTOBANCARIO_BDALTAFW,
	c_MOVIMIENTOBANCARIO.BDMODIFW as MOVIMIENTOBANCARIO_BDMODIFW,
	c_MOVIMIENTOBANCARIO.ESTTRANS as MOVIMIENTOBANCARIO_ESTTRANS,
	case when c_movimientobancario.faltafw = '01/01/1900 00:00:00' then null else c_movimientobancario.faltafw end as MOVIMIENTOBANCARIO_FALTAFW,
	case when c_movimientobancario.fecexpo = '01/01/1900 00:00:00' then null else c_movimientobancario.fecexpo end as MOVIMIENTOBANCARIO_FECEXPO,
	case when c_movimientobancario.fecimpo = '01/01/1900 00:00:00' then null else c_movimientobancario.fecimpo end as MOVIMIENTOBANCARIO_FECIMPO,
	case when c_movimientobancario.fmodifw = '01/01/1900 00:00:00' then null else c_movimientobancario.fmodifw end as MOVIMIENTOBANCARIO_FMODIFW,
	case when c_movimientobancario.fectrans = '01/01/1900 00:00:00' then null else c_movimientobancario.fectrans end as MOVIMIENTOBANCARIO_FECTRANS,
	c_MOVIMIENTOBANCARIO.HALTAFW as MOVIMIENTOBANCARIO_HALTAFW,
	c_MOVIMIENTOBANCARIO.HORAEXPO as MOVIMIENTOBANCARIO_HORAEXPO,
	c_MOVIMIENTOBANCARIO.HORAIMPO as MOVIMIENTOBANCARIO_HORAIMPO,
	c_MOVIMIENTOBANCARIO.HMODIFW as MOVIMIENTOBANCARIO_HMODIFW,
	c_MOVIMIENTOBANCARIO.SALTAFW as MOVIMIENTOBANCARIO_SALTAFW,
	c_MOVIMIENTOBANCARIO.SMODIFW as MOVIMIENTOBANCARIO_SMODIFW,
	c_MOVIMIENTOBANCARIO.UALTAFW as MOVIMIENTOBANCARIO_UALTAFW,
	c_MOVIMIENTOBANCARIO.UMODIFW as MOVIMIENTOBANCARIO_UMODIFW,
	c_MOVIMIENTOBANCARIO.VALTAFW as MOVIMIENTOBANCARIO_VALTAFW,
	c_MOVIMIENTOBANCARIO.VMODIFW as MOVIMIENTOBANCARIO_VMODIFW,
	c_MOVIMIENTOBANCARIO.ZADSFW as MOVIMIENTOBANCARIO_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as MOVIMIENTOBANCARIO__SUCURSAL,
	C_CUENTABANCARIA.CBNUM as CUENTABANCARIA_CBNum,
	C_CUENTABANCARIA.CBMONEDA as CUENTABANCARIA_CBMoneda,
	C_CUENTABANCARIA.CBDES as CUENTABANCARIA_CBDes,
	CASE WHEN 0=Funciones.Empty(C_CONCEPTOENTIDADFINANCIERA.DESCRI) THEN C_CONCEPTOENTIDADFINANCIERA.DESCRI ELSE C_CONCEPTOENTIDADFINANCIERA.CONCEPTO END AS CONCEPTOENTIDADFINANCIERA_Concepto,
	C_CONCEPTOENTIDADFINANCIERA.DESCRI as CONCEPTOENTIDADFINANCIERA_Descripcion,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_CONCEPTOENTIDADFINANCIERA.CODIGO as CONCEPTOENTIDADFINANCIERA_Codigo,
	C_CUENTABANCARIA.CBCOD as CUENTABANCARIA_CBCod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD
 from ZooLogic.MOVBANC as c_MOVIMIENTOBANCARIO
 left join ZooLogic.CONENTFIN as C_CONCEPTOENTIDADFINANCIERA on C_CONCEPTOENTIDADFINANCIERA.CODIGO = C_MOVIMIENTOBANCARIO.CONCEPTO and 0 = Funciones.empty( C_MOVIMIENTOBANCARIO.CONCEPTO )
 left join ZooLogic.CTABAN as C_CUENTABANCARIA on C_CUENTABANCARIA.CBCOD = C_MOVIMIENTOBANCARIO.CTABANC and 0 = Funciones.empty( C_MOVIMIENTOBANCARIO.CTABANC )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_CUENTABANCARIA.CBMONEDA and 0 = Funciones.empty( C_CUENTABANCARIA.CBMONEDA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( not 1 = funciones.empty( c_movimientobancario.codigo ) ) and 
	( ( @CUENTABANCARIA_21_NUMERO_DESDE is null ) OR ( C_CUENTABANCARIA.CBNum >= @CUENTABANCARIA_21_NUMERO_DESDE ) ) and 
	( ( @CUENTABANCARIA_21_NUMERO_HASTA is null ) OR ( C_CUENTABANCARIA.CBNum <= @CUENTABANCARIA_21_NUMERO_HASTA ) ) and 
	( ( @CUENTABANCARIA_21_MONEDACUENTA_DESDE is null ) OR ( C_CUENTABANCARIA.CBMoneda >= @CUENTABANCARIA_21_MONEDACUENTA_DESDE ) ) and 
	( ( @CUENTABANCARIA_21_MONEDACUENTA_HASTA is null ) OR ( C_CUENTABANCARIA.CBMoneda <= @CUENTABANCARIA_21_MONEDACUENTA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_IDENTIFICADOR_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Codigo >= @MOVIMIENTOBANCARIO_IDENTIFICADOR_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_IDENTIFICADOR_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Codigo <= @MOVIMIENTOBANCARIO_IDENTIFICADOR_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_CUENTABANCARIA_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.CtaBanc >= @MOVIMIENTOBANCARIO_CUENTABANCARIA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_CUENTABANCARIA_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.CtaBanc <= @MOVIMIENTOBANCARIO_CUENTABANCARIA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_ORDEN_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Orden >= @MOVIMIENTOBANCARIO_ORDEN_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_ORDEN_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Orden <= @MOVIMIENTOBANCARIO_ORDEN_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHA_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Fecha >= @MOVIMIENTOBANCARIO_FECHA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHA_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Fecha <= @MOVIMIENTOBANCARIO_FECHA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORA_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Hora >= @MOVIMIENTOBANCARIO_HORA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORA_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Hora <= @MOVIMIENTOBANCARIO_HORA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_CONCEPTO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Concepto >= @MOVIMIENTOBANCARIO_CONCEPTO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_CONCEPTO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Concepto <= @MOVIMIENTOBANCARIO_CONCEPTO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_REFERENCIA_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Refe >= @MOVIMIENTOBANCARIO_REFERENCIA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_REFERENCIA_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Refe <= @MOVIMIENTOBANCARIO_REFERENCIA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_DATOADICIONAL1_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.DatAd1 >= @MOVIMIENTOBANCARIO_DATOADICIONAL1_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_DATOADICIONAL1_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.DatAd1 <= @MOVIMIENTOBANCARIO_DATOADICIONAL1_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_DATOADICIONAL2_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.DatAd2 >= @MOVIMIENTOBANCARIO_DATOADICIONAL2_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_DATOADICIONAL2_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.DatAd2 <= @MOVIMIENTOBANCARIO_DATOADICIONAL2_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_DATOADICIONAL3_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.DatAd3 >= @MOVIMIENTOBANCARIO_DATOADICIONAL3_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_DATOADICIONAL3_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.DatAd3 <= @MOVIMIENTOBANCARIO_DATOADICIONAL3_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_NUMERO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Numero >= @MOVIMIENTOBANCARIO_NUMERO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_NUMERO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Numero <= @MOVIMIENTOBANCARIO_NUMERO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_IMPORTE_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Importe >= @MOVIMIENTOBANCARIO_IMPORTE_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_IMPORTE_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Importe <= @MOVIMIENTOBANCARIO_IMPORTE_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_SALDO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.Saldo >= @MOVIMIENTOBANCARIO_SALDO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_SALDO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.Saldo <= @MOVIMIENTOBANCARIO_SALDO_HASTA ) ) and 
	( ( @CUENTABANCARIA_21_CUENTABANCARIA_DESCRIPCION_DESDE is null ) OR ( C_CUENTABANCARIA.CBDes >= @CUENTABANCARIA_21_CUENTABANCARIA_DESCRIPCION_DESDE ) ) and 
	( ( @CUENTABANCARIA_21_CUENTABANCARIA_DESCRIPCION_HASTA is null ) OR ( C_CUENTABANCARIA.CBDes <= @CUENTABANCARIA_21_CUENTABANCARIA_DESCRIPCION_HASTA ) ) and 
	( ( @CONCEPTOENTIDADFINANCIERA_25_CONCEPTO_CONCEPTO_DESDE is null ) OR ( C_CONCEPTOENTIDADFINANCIERA.Concepto >= @CONCEPTOENTIDADFINANCIERA_25_CONCEPTO_CONCEPTO_DESDE ) ) and 
	( ( @CONCEPTOENTIDADFINANCIERA_25_CONCEPTO_CONCEPTO_HASTA is null ) OR ( C_CONCEPTOENTIDADFINANCIERA.Concepto <= @CONCEPTOENTIDADFINANCIERA_25_CONCEPTO_CONCEPTO_HASTA ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9144_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9144_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9144_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9144_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9144_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9144_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9144_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9144_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9144_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9144_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9144_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9144_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9144_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9144_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9144_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9144_CODIGO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.BDALTAFW >= @MOVIMIENTOBANCARIO_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.BDALTAFW <= @MOVIMIENTOBANCARIO_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.BDMODIFW >= @MOVIMIENTOBANCARIO_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.BDMODIFW <= @MOVIMIENTOBANCARIO_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.ESTTRANS >= @MOVIMIENTOBANCARIO_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.ESTTRANS <= @MOVIMIENTOBANCARIO_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAALTAFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.FALTAFW >= @MOVIMIENTOBANCARIO_FECHAALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAALTAFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.FALTAFW <= @MOVIMIENTOBANCARIO_FECHAALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAEXPO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.FECEXPO >= @MOVIMIENTOBANCARIO_FECHAEXPO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAEXPO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.FECEXPO <= @MOVIMIENTOBANCARIO_FECHAEXPO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAIMPO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.FECIMPO >= @MOVIMIENTOBANCARIO_FECHAIMPO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAIMPO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.FECIMPO <= @MOVIMIENTOBANCARIO_FECHAIMPO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.FMODIFW >= @MOVIMIENTOBANCARIO_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.FMODIFW <= @MOVIMIENTOBANCARIO_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHATRANSFERENCIA_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.FECTRANS >= @MOVIMIENTOBANCARIO_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_FECHATRANSFERENCIA_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.FECTRANS <= @MOVIMIENTOBANCARIO_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAALTAFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.HALTAFW >= @MOVIMIENTOBANCARIO_HORAALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAALTAFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.HALTAFW <= @MOVIMIENTOBANCARIO_HORAALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAEXPO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.HORAEXPO >= @MOVIMIENTOBANCARIO_HORAEXPO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAEXPO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.HORAEXPO <= @MOVIMIENTOBANCARIO_HORAEXPO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAIMPO_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.HORAIMPO >= @MOVIMIENTOBANCARIO_HORAIMPO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAIMPO_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.HORAIMPO <= @MOVIMIENTOBANCARIO_HORAIMPO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.HMODIFW >= @MOVIMIENTOBANCARIO_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_HORAMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.HMODIFW <= @MOVIMIENTOBANCARIO_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_SERIEALTAFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.SALTAFW >= @MOVIMIENTOBANCARIO_SERIEALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_SERIEALTAFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.SALTAFW <= @MOVIMIENTOBANCARIO_SERIEALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.SMODIFW >= @MOVIMIENTOBANCARIO_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.SMODIFW <= @MOVIMIENTOBANCARIO_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_USUARIOALTAFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.UALTAFW >= @MOVIMIENTOBANCARIO_USUARIOALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_USUARIOALTAFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.UALTAFW <= @MOVIMIENTOBANCARIO_USUARIOALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.UMODIFW >= @MOVIMIENTOBANCARIO_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.UMODIFW <= @MOVIMIENTOBANCARIO_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_VERSIONALTAFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.VALTAFW >= @MOVIMIENTOBANCARIO_VERSIONALTAFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_VERSIONALTAFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.VALTAFW <= @MOVIMIENTOBANCARIO_VERSIONALTAFW_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_MOVIMIENTOBANCARIO.VMODIFW >= @MOVIMIENTOBANCARIO_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_MOVIMIENTOBANCARIO.VMODIFW <= @MOVIMIENTOBANCARIO_VERSIONMODIFICACIONFW_HASTA ) )

)