IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_REQUERIMIENTODECOMPRA_ITEMARTICULOSREQCOMPRA_ITEMARTICULOSREQCOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_REQUERIMIENTODECOMPRA_ITEMARTICULOSREQCOMPRA_ITEMARTICULOSREQCOMPRA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_REQUERIMIENTODECOMPRA_ITEMARTICULOSREQCOMPRA_ITEMARTICULOSREQCOMPRA]
( @BaseDeDatos varchar(8),
	@REQUERIMIENTODECOMPRA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@REQUERIMIENTODECOMPRA_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@ITEMARTICULOSREQCOMPRA_ARTICULO_DESDE varchar(15),
	@ITEMARTICULOSREQCOMPRA_ARTICULO_HASTA varchar(15),
	@ITEMARTICULOSREQCOMPRA_ARTICULODETALLE_DESDE varchar(100),
	@ITEMARTICULOSREQCOMPRA_ARTICULODETALLE_HASTA varchar(100),
	@ITEMARTICULOSREQCOMPRA_COLOR_DESDE varchar(6),
	@ITEMARTICULOSREQCOMPRA_COLOR_HASTA varchar(6),
	@ITEMARTICULOSREQCOMPRA_COLORDETALLE_DESDE varchar(50),
	@ITEMARTICULOSREQCOMPRA_COLORDETALLE_HASTA varchar(50),
	@ITEMARTICULOSREQCOMPRA_TALLE_DESDE varchar(5),
	@ITEMARTICULOSREQCOMPRA_TALLE_HASTA varchar(5),
	@ITEMARTICULOSREQCOMPRA_CANTIDAD_DESDE numeric(8, 2),
	@ITEMARTICULOSREQCOMPRA_CANTIDAD_HASTA numeric(8, 2),
	@ITEMARTICULOSREQCOMPRA_PRECIO_DESDE numeric(14, 4),
	@ITEMARTICULOSREQCOMPRA_PRECIO_HASTA numeric(14, 4),
	@ITEMARTICULOSREQCOMPRA_DESCUENTO_DESDE numeric(7, 2),
	@ITEMARTICULOSREQCOMPRA_DESCUENTO_HASTA numeric(7, 2),
	@ITEMARTICULOSREQCOMPRA_MONTODESCUENTO_DESDE numeric(12, 2),
	@ITEMARTICULOSREQCOMPRA_MONTODESCUENTO_HASTA numeric(12, 2),
	@ITEMARTICULOSREQCOMPRA_MONTO_DESDE numeric(15, 2),
	@ITEMARTICULOSREQCOMPRA_MONTO_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_CODIGO_DESDE varchar(38),
	@REQUERIMIENTODECOMPRA_1_CODIGO_HASTA varchar(38),
	@REQUERIMIENTODECOMPRA_1_PROVEEDOR_DESDE varchar(10),
	@REQUERIMIENTODECOMPRA_1_PROVEEDOR_HASTA varchar(10),
	@REQUERIMIENTODECOMPRA_1_LISTADEPRECIOS_DESDE varchar(6),
	@REQUERIMIENTODECOMPRA_1_LISTADEPRECIOS_HASTA varchar(6),
	@REQUERIMIENTODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE varchar(5),
	@REQUERIMIENTODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA varchar(5),
	@REQUERIMIENTODECOMPRA_1_MOTIVO_DESDE varchar(3),
	@REQUERIMIENTODECOMPRA_1_MOTIVO_HASTA varchar(3),
	@REQUERIMIENTODECOMPRA_1_LETRA_DESDE varchar(1),
	@REQUERIMIENTODECOMPRA_1_LETRA_HASTA varchar(1),
	@REQUERIMIENTODECOMPRA_1_PUNTODEVENTA_DESDE numeric(4, 0),
	@REQUERIMIENTODECOMPRA_1_PUNTODEVENTA_HASTA numeric(4, 0),
	@REQUERIMIENTODECOMPRA_1_NUMERO_DESDE numeric(8, 0),
	@REQUERIMIENTODECOMPRA_1_NUMERO_HASTA numeric(8, 0),
	@REQUERIMIENTODECOMPRA_1_FECHA_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHA_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_COTIZACION_DESDE numeric(15, 5),
	@REQUERIMIENTODECOMPRA_1_COTIZACION_HASTA numeric(15, 5),
	@REQUERIMIENTODECOMPRA_1_FECHAVENCIMIENTO_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAVENCIMIENTO_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@REQUERIMIENTODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@REQUERIMIENTODECOMPRA_1_DESCUENTO_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_DESCUENTO_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@REQUERIMIENTODECOMPRA_1_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@REQUERIMIENTODECOMPRA_1_RECARGOMONTO_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_RECARGOMONTO_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_RECARGOMONTO2_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_RECARGOMONTO2_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_IMPUESTOS_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_IMPUESTOS_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_TOTALIMPUESTOS_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_TOTALIMPUESTOS_HASTA numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_TOTAL_DESDE numeric(15, 2),
	@REQUERIMIENTODECOMPRA_1_TOTAL_HASTA numeric(15, 2),
	@PROVEEDOR_76_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_76_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@LISTADEPRECIOS_120_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_120_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CONDICIONDEPAGO_121_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_121_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA varchar(100),
	@MOTIVO_122_MOTIVO_DESCRIPCION_DESDE varchar(40),
	@MOTIVO_122_MOTIVO_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_8148_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_8148_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_8147_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_8147_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_12_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_12_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_13_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_13_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE varchar(40),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA varchar(40),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE varchar(150),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA varchar(150),
	@MARCA_42_MARCA_DESCRIPCION_DESDE varchar(100),
	@MARCA_42_MARCA_DESCRIPCION_HASTA varchar(100),
	@PROVINCIA_79_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_79_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_95_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_95_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_97_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_97_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_99_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_99_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_102_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_102_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_104_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_104_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_105_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_105_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_106_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_106_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_115_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_115_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_8144_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_8144_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_8144_LINEA_DESDE varchar(10),
	@SUCURSAL_8144_LINEA_HASTA varchar(10),
	@SUCURSAL_8144_TIPO_DESDE varchar(10),
	@SUCURSAL_8144_TIPO_HASTA varchar(10),
	@SUCURSAL_8144_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_8144_DESCRIPCION_HASTA varchar(50),
	@ARTICULO_2_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_2_PROVEEDOR_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVAVENTAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA numeric(5, 2),
	@ARTICULO_2_IMAGEN_DESDE varchar(180),
	@ARTICULO_2_IMAGEN_HASTA varchar(180),
	@ARTICULO_2_TEMPORADA_DESDE varchar(5),
	@ARTICULO_2_TEMPORADA_HASTA varchar(5),
	@ARTICULO_2_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_2_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_2_FAMILIA_DESDE varchar(10),
	@ARTICULO_2_FAMILIA_HASTA varchar(10),
	@ARTICULO_2_MATERIAL_DESDE varchar(10),
	@ARTICULO_2_MATERIAL_HASTA varchar(10),
	@ARTICULO_2_LINEA_DESDE varchar(10),
	@ARTICULO_2_LINEA_HASTA varchar(10),
	@ARTICULO_2_GRUPO_DESDE varchar(10),
	@ARTICULO_2_GRUPO_HASTA varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_2_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_2_ANO_DESDE numeric(4, 0),
	@ARTICULO_2_ANO_HASTA numeric(4, 0),
	@ARTICULO_2_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_2_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVACOMPRAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA numeric(5, 2),
	@ARTICULO_2_COMPORTAMIENTO numeric(1, 0),
	@ARTICULO_2_PALETADECOLORES_DESDE varchar(10),
	@ARTICULO_2_PALETADECOLORES_HASTA varchar(10),
	@ARTICULO_2_CURVADETALLES_DESDE varchar(10),
	@ARTICULO_2_CURVADETALLES_HASTA varchar(10),
	@ARTICULO_2_NOCOMERCIALIZABLE_DESDE datetime,
	@ARTICULO_2_NOCOMERCIALIZABLE_HASTA datetime,
	@ARTICULO_2_NOMENCLADOR_DESDE varchar(6),
	@ARTICULO_2_NOMENCLADOR_HASTA varchar(6),
	@ARTICULO_2_NOPERMITEDEVOLUCIONES bit,
	@ARTICULO_2_IMPRIMEDESPACHO bit,
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA numeric(5, 2),
	@ARTICULO_2_RESTRINGIRDESCUENTOS bit,
	@ARTICULO_2_PESO_DESDE numeric(11, 3),
	@ARTICULO_2_PESO_HASTA numeric(11, 3),
	@ARTICULO_2_LARGO_DESDE numeric(11, 2),
	@ARTICULO_2_LARGO_HASTA numeric(11, 2),
	@ARTICULO_2_ANCHO_DESDE numeric(11, 2),
	@ARTICULO_2_ANCHO_HASTA numeric(11, 2),
	@ARTICULO_2_ALTO_DESDE numeric(11, 2),
	@ARTICULO_2_ALTO_HASTA numeric(11, 2),
	@ARTICULO_2_REQUIERECCOSTO_DESDE numeric(1, 0),
	@ARTICULO_2_REQUIERECCOSTO_HASTA numeric(1, 0),
	@ARTICULO_2_NOPUBLICARENECOMMERCE bit,
	@ARTICULO_2_IMPORTADO bit,
	@ARTICULO_2_DESCRIPCIONADICIONAL_DESDE varchar(254),
	@ARTICULO_2_DESCRIPCIONADICIONAL_HASTA varchar(254),
	@ARTICULO_2_SOLOPROMOYKIT bit,
	@ARTICULO_2_RESTRINGIRARTICULO_DESDE datetime,
	@ARTICULO_2_RESTRINGIRARTICULO_HASTA datetime,
	@ARTICULO_2_MARCA_DESDE varchar(30),
	@ARTICULO_2_MARCA_HASTA varchar(30),
	@ARTICULO_2_PERCEPCIONIVARG5329 numeric(1, 0),
	@PROVEEDOR_76_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_76_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_76_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_76_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_76_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_76_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_76_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_76_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_76_FAX_DESDE varchar(60),
	@PROVEEDOR_76_FAX_HASTA varchar(60),
	@PROVEEDOR_76_EMAIL_DESDE varchar(250),
	@PROVEEDOR_76_EMAIL_HASTA varchar(250),
	@PROVEEDOR_76_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_76_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_84_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_76_CUIT_DESDE varchar(15),
	@PROVEEDOR_76_CUIT_HASTA varchar(15),
	@PROVEEDOR_76_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_76_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_76_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_76_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_76_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_76_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_76_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_76_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_76_CALLE_DESDE varchar(70),
	@PROVEEDOR_76_CALLE_HASTA varchar(70),
	@PROVEEDOR_76_PISO_DESDE varchar(3),
	@PROVEEDOR_76_PISO_HASTA varchar(3),
	@PROVEEDOR_76_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_76_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_76_PAIS_DESDE varchar(3),
	@PROVEEDOR_76_PAIS_HASTA varchar(3),
	@PROVEEDOR_76_MOVIL_DESDE varchar(30),
	@PROVEEDOR_76_MOVIL_HASTA varchar(30),
	@PROVEEDOR_76_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_76_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_76_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_76_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_76_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_76_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_76_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_76_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_76_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_76_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_76_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_76_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_76_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_76_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_76_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_76_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_76_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_76_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_76_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_76_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_76_EMPLEADOR bit,
	@PROVEEDOR_76_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_76_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_76_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_76_SUJETOVINCULADO bit,
	@PROVEEDOR_76_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_76_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_76_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_76_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_76_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_76_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_76_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_76_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_76_TASACEROAPLICA bit,
	@PROVEEDOR_76_RUT_DESDE varchar(12),
	@PROVEEDOR_76_RUT_HASTA varchar(12),
	@PROVEEDOR_76_INACTIVOFW bit,
	@SUCURSAL_8144_CODIGO_DESDE varchar(10),
	@SUCURSAL_8144_CODIGO_HASTA varchar(10),
	@ITEMARTICULOSREQCOMPRA_NROITEM_DESDE numeric(5, 0),
	@ITEMARTICULOSREQCOMPRA_NROITEM_HASTA numeric(5, 0),
	@REQUERIMIENTODECOMPRA_1_FECHAALTAFW_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAALTAFW_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_HORAALTAFW_DESDE varchar(8),
	@REQUERIMIENTODECOMPRA_1_HORAALTAFW_HASTA varchar(8),
	@REQUERIMIENTODECOMPRA_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@REQUERIMIENTODECOMPRA_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@REQUERIMIENTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@REQUERIMIENTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@REQUERIMIENTODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@REQUERIMIENTODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@REQUERIMIENTODECOMPRA_1_FECHAEXPO_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAEXPO_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAIMPO_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAIMPO_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAMODIFICACIONFW_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHAMODIFICACIONFW_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_FECHATRANSFERENCIA_DESDE datetime,
	@REQUERIMIENTODECOMPRA_1_FECHATRANSFERENCIA_HASTA datetime,
	@REQUERIMIENTODECOMPRA_1_HORAEXPO_DESDE varchar(8),
	@REQUERIMIENTODECOMPRA_1_HORAEXPO_HASTA varchar(8),
	@REQUERIMIENTODECOMPRA_1_HORAIMPO_DESDE varchar(8),
	@REQUERIMIENTODECOMPRA_1_HORAIMPO_HASTA varchar(8),
	@REQUERIMIENTODECOMPRA_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@REQUERIMIENTODECOMPRA_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@REQUERIMIENTODECOMPRA_1_SERIEALTAFW_DESDE varchar(7),
	@REQUERIMIENTODECOMPRA_1_SERIEALTAFW_HASTA varchar(7),
	@REQUERIMIENTODECOMPRA_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@REQUERIMIENTODECOMPRA_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@REQUERIMIENTODECOMPRA_1_USUARIOALTAFW_DESDE varchar(100),
	@REQUERIMIENTODECOMPRA_1_USUARIOALTAFW_HASTA varchar(100),
	@REQUERIMIENTODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@REQUERIMIENTODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@REQUERIMIENTODECOMPRA_1_VERSIONALTAFW_DESDE varchar(13),
	@REQUERIMIENTODECOMPRA_1_VERSIONALTAFW_HASTA varchar(13),
	@REQUERIMIENTODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@REQUERIMIENTODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
with ConjuntoBase as
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticulosreqcompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSREQCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSREQCOMPRA__BD,
	/* Campos requeridos para las consultas derivadas */
	c_ITEMARTICULOSREQCOMPRA.CODIGO,
	c_ITEMARTICULOSREQCOMPRA.IDITEM,
	c_ITEMARTICULOSREQCOMPRA.AFE_COD,
	c_ITEMARTICULOSREQCOMPRA.AFESALDO,
	c_ITEMARTICULOSREQCOMPRA.FCANT,
	C_REQUERIMIENTODECOMPRA.FACTTIPO,
	/*------------------------------------------------*/
	c_ITEMARTICULOSREQCOMPRA.CODIGO as ITEMARTICULOSREQCOMPRA_CODIGO,
	c_ITEMARTICULOSREQCOMPRA.FART as ITEMARTICULOSREQCOMPRA_FART,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	c_ITEMARTICULOSREQCOMPRA.FTXT as ITEMARTICULOSREQCOMPRA_FTXT,
	c_ITEMARTICULOSREQCOMPRA.FCOLO as ITEMARTICULOSREQCOMPRA_FCOLO,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticulosreqcompra.fart, c_itemarticulosreqcompra.fcolo, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSREQCOMPRA_OrdenPaletaColores,
	c_ITEMARTICULOSREQCOMPRA.FCOTXT as ITEMARTICULOSREQCOMPRA_FCOTXT,
	c_ITEMARTICULOSREQCOMPRA.FTALL as ITEMARTICULOSREQCOMPRA_FTALL,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticulosreqcompra.fart, c_itemarticulosreqcompra.ftall, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSREQCOMPRA_OrdenCurvaTalles,
	c_ITEMARTICULOSREQCOMPRA.FCANT as ITEMARTICULOSREQCOMPRA_FCANT,
	c_ITEMARTICULOSREQCOMPRA.FPRECIO as ITEMARTICULOSREQCOMPRA_FPRECIO,
	c_ITEMARTICULOSREQCOMPRA.FCFI as ITEMARTICULOSREQCOMPRA_FCFI,
	c_ITEMARTICULOSREQCOMPRA.MNTDES as ITEMARTICULOSREQCOMPRA_MNTDES,
	c_ITEMARTICULOSREQCOMPRA.FMONTO as ITEMARTICULOSREQCOMPRA_FMONTO,
	C_REQUERIMIENTODECOMPRA.CODIGO as REQUERIMIENTODECOMPRA_CODIGO,
	C_REQUERIMIENTODECOMPRA.FPERSON as REQUERIMIENTODECOMPRA_FPerson,
	C_PROVEEDOR76.CIMAGEN as PROVEEDOR76_CIMAGEN,
	C_REQUERIMIENTODECOMPRA.CODLISTA as REQUERIMIENTODECOMPRA_CodLista,
	C_REQUERIMIENTODECOMPRA.CONDPAGO as REQUERIMIENTODECOMPRA_CONDPAGO,
	C_REQUERIMIENTODECOMPRA.MOTIVO as REQUERIMIENTODECOMPRA_MOTIVO,
	C_REQUERIMIENTODECOMPRA.FLETRA as REQUERIMIENTODECOMPRA_FLETRA,
	C_REQUERIMIENTODECOMPRA.FPTOVEN as REQUERIMIENTODECOMPRA_FPTOVEN,
	C_REQUERIMIENTODECOMPRA.FNUMCOMP as REQUERIMIENTODECOMPRA_FNUMCOMP,
	case when c_requerimientodecompra.ffch = '01/01/1900 00:00:00' then null else c_requerimientodecompra.ffch end as REQUERIMIENTODECOMPRA_FFCH,
	C_REQUERIMIENTODECOMPRA.COTIZ as REQUERIMIENTODECOMPRA_Cotiz,
	case when c_requerimientodecompra.ffchvenc = '01/01/1900 00:00:00' then null else c_requerimientodecompra.ffchvenc end as REQUERIMIENTODECOMPRA_FFCHVENC,
	C_REQUERIMIENTODECOMPRA.FPODES as REQUERIMIENTODECOMPRA_FPODES,
	C_REQUERIMIENTODECOMPRA.FDESCU as REQUERIMIENTODECOMPRA_fDescu,
	C_REQUERIMIENTODECOMPRA.FOBS as REQUERIMIENTODECOMPRA_FObs,
	C_REQUERIMIENTODECOMPRA.FMTDES3 as REQUERIMIENTODECOMPRA_FMTDES3,
	C_REQUERIMIENTODECOMPRA.RECPOR as REQUERIMIENTODECOMPRA_RecPor,
	C_REQUERIMIENTODECOMPRA.MR as REQUERIMIENTODECOMPRA_MR,
	C_REQUERIMIENTODECOMPRA.RECMONTO2 as REQUERIMIENTODECOMPRA_RecMonto2,
	C_REQUERIMIENTODECOMPRA.FIMPUESTO as REQUERIMIENTODECOMPRA_fImpuesto,
	C_REQUERIMIENTODECOMPRA.TOTIMPUE as REQUERIMIENTODECOMPRA_totimpue,
	C_REQUERIMIENTODECOMPRA.FTOTAL as REQUERIMIENTODECOMPRA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_ARTICULO.ARTCONIVA as ARTICULO_ARTCONIVA,
	C_ARTICULO.ARTPORIVA as ARTICULO_ARTPORIVA,
	C_ARTICULO.AOBS as ARTICULO_AObs,
	C_ARTICULO.ATEMPORADA as ARTICULO_ATEMPORADA,
	C_ARTICULO.UNIMED as ARTICULO_UniMed,
	C_ARTICULO.FAMILIA as ARTICULO_Familia,
	C_ARTICULO.MAT as ARTICULO_Mat,
	C_ARTICULO.LINEA as ARTICULO_Linea,
	C_ARTICULO.GRUPO as ARTICULO_Grupo,
	C_ARTICULO.CATEARTI as ARTICULO_CateArti,
	C_ARTICULO.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	C_ARTICULO.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ARTIVA as ARTICULO_ARTIVA,
	C_ARTICULO.ANX2 as ARTICULO_ANX2,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	C_ARTICULO.PALCOL as ARTICULO_PalCol,
	C_ARTICULO.CURTALL as ARTICULO_Curtall,
	case when c_articulo.nocom = '01/01/1900 00:00:00' then null else c_articulo.nocom end as ARTICULO_NOCOM,
	C_ARTICULO.ARTNARBA as ARTICULO_ARTNARBA,
	C_ARTICULO.ARTNODEVO as ARTICULO_ARTNODEVO,
	C_ARTICULO.ESIMPDES as ARTICULO_EsImpDes,
	C_ARTICULO.IMPINTERNO as ARTICULO_impinterno,
	C_ARTICULO.ARTSINDES as ARTICULO_ArtSinDes,
	C_ARTICULO.ARTPESO as ARTICULO_ARTPESO,
	C_ARTICULO.ARTLARGO as ARTICULO_ARTLARGO,
	C_ARTICULO.ARTANCHO as ARTICULO_ARTANCHO,
	C_ARTICULO.ARTALTO as ARTICULO_ARTALTO,
	C_ARTICULO.REQCCOSTO as ARTICULO_ReqCCosto,
	C_ARTICULO.PUBECOM as ARTICULO_PubEcom,
	C_ARTICULO.IMPORTADO as ARTICULO_Importado,
	C_ARTICULO.ARTDESADIC as ARTICULO_ARTDESADIC,
	C_ARTICULO.PROMOYKIT as ARTICULO_PromoYKit,
	C_ARTICULO.DESECOHTML as ARTICULO_DesEcoHTML,
	C_ARTICULO.DESECO as ARTICULO_DesEco,
	case when c_articulo.artrest = '01/01/1900 00:00:00' then null else c_articulo.artrest end as ARTICULO_ArtRest,
	C_ARTICULO.MARCA as ARTICULO_Marca,
	C_ARTICULO.ARTPERCEP as ARTICULO_ArtPercep,
	C_PROVEEDOR76.CLLOC as PROVEEDOR76_CLLOC,
	C_PROVEEDOR76.CLCP as PROVEEDOR76_CLCP,
	C_PROVEEDOR76.CLPRV as PROVEEDOR76_CLPRV,
	C_PROVEEDOR76.CLTLF as PROVEEDOR76_CLTLF,
	C_PROVEEDOR76.CLFAX as PROVEEDOR76_CLFAX,
	C_PROVEEDOR76.CLEMAIL as PROVEEDOR76_CLEMAIL,
	C_PROVEEDOR76.CLPAGEWEB as PROVEEDOR76_CLPAGEWEB,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_PROVEEDOR76.CLCUIT as PROVEEDOR76_CLCUIT,
	C_PROVEEDOR76.CLOBS as PROVEEDOR76_CLOBS,
	C_PROVEEDOR76.CLTIPODOC as PROVEEDOR76_CLTIPODOC,
	C_PROVEEDOR76.CLNRODOC as PROVEEDOR76_CLNRODOC,
	C_PROVEEDOR76.PNUMERO as PROVEEDOR76_PNUMERO,
	C_PROVEEDOR76.PCALLE as PROVEEDOR76_PCALLE,
	C_PROVEEDOR76.PPISO as PROVEEDOR76_PPISO,
	C_PROVEEDOR76.PDEPTO as PROVEEDOR76_PDEPTO,
	C_PROVEEDOR76.PPAIS as PROVEEDOR76_PPAIS,
	C_PROVEEDOR76.TLFM as PROVEEDOR76_TLFM,
	C_PROVEEDOR76.CLAS as PROVEEDOR76_CLAS,
	case when c_proveedor76.clfecha = '01/01/1900 00:00:00' then null else c_proveedor76.clfecha end as PROVEEDOR76_CLFECHA,
	C_PROVEEDOR76.CLCONDPAG as PROVEEDOR76_CLCONDPAG,
	C_PROVEEDOR76.CLTIPCONV as PROVEEDOR76_CLTIPCONV,
	C_PROVEEDOR76.CLNROIIBB as PROVEEDOR76_CLNROIIBB,
	C_PROVEEDOR76.CLLISTPRE as PROVEEDOR76_CLLISTPRE,
	C_PROVEEDOR76.CLSITGAN as PROVEEDOR76_CLSITGAN,
	C_PROVEEDOR76.CLRETGAN as PROVEEDOR76_CLRETGAN,
	C_PROVEEDOR76.CLRETSUSS as PROVEEDOR76_CLRETSUSS,
	C_PROVEEDOR76.CLRETIVA as PROVEEDOR76_CLRETIVA,
	C_PROVEEDOR76.CLOBJIVA as PROVEEDOR76_CLOBJIVA,
	C_PROVEEDOR76.CLEMPLEAD as PROVEEDOR76_CLEMPLEAD,
	C_PROVEEDOR76.EXRETGAN as PROVEEDOR76_EXRETGAN,
	C_PROVEEDOR76.EXRETIVA as PROVEEDOR76_EXRETIVA,
	C_PROVEEDOR76.EXRETSUSS as PROVEEDOR76_EXRETSUSS,
	C_PROVEEDOR76.CLSUJVINC as PROVEEDOR76_CLSujVinc,
	case when c_proveedor76.pvhastaiva = '01/01/1900 00:00:00' then null else c_proveedor76.pvhastaiva end as PROVEEDOR76_PVHastaIva,
	case when c_proveedor76.pvhastagan = '01/01/1900 00:00:00' then null else c_proveedor76.pvhastagan end as PROVEEDOR76_PVHastaGan,
	C_PROVEEDOR76.CLSIPRIB as PROVEEDOR76_CLSIPRIB,
	C_PROVEEDOR76.PORCENTC as PROVEEDOR76_PorcenTC,
	C_PROVEEDOR76.APLICATC as PROVEEDOR76_AplicaTC,
	C_PROVEEDOR76.RUT as PROVEEDOR76_RUT,
	C_PROVEEDOR76.INACTIVOFW as PROVEEDOR76_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMARTICULOSREQCOMPRA.NROITEM as ITEMARTICULOSREQCOMPRA_NroItem,
	case when c_requerimientodecompra.faltafw = '01/01/1900 00:00:00' then null else c_requerimientodecompra.faltafw end as REQUERIMIENTODECOMPRA_FAltaFW,
	C_REQUERIMIENTODECOMPRA.HALTAFW as REQUERIMIENTODECOMPRA_HAltaFW,
	C_REQUERIMIENTODECOMPRA.BDALTAFW as REQUERIMIENTODECOMPRA_BDALTAFW,
	C_REQUERIMIENTODECOMPRA.BDMODIFW as REQUERIMIENTODECOMPRA_BDMODIFW,
	C_REQUERIMIENTODECOMPRA.ESTTRANS as REQUERIMIENTODECOMPRA_ESTTRANS,
	case when c_requerimientodecompra.fecexpo = '01/01/1900 00:00:00' then null else c_requerimientodecompra.fecexpo end as REQUERIMIENTODECOMPRA_FECEXPO,
	case when c_requerimientodecompra.fecimpo = '01/01/1900 00:00:00' then null else c_requerimientodecompra.fecimpo end as REQUERIMIENTODECOMPRA_FECIMPO,
	case when c_requerimientodecompra.fmodifw = '01/01/1900 00:00:00' then null else c_requerimientodecompra.fmodifw end as REQUERIMIENTODECOMPRA_FMODIFW,
	case when c_requerimientodecompra.fectrans = '01/01/1900 00:00:00' then null else c_requerimientodecompra.fectrans end as REQUERIMIENTODECOMPRA_FECTRANS,
	C_REQUERIMIENTODECOMPRA.HORAEXPO as REQUERIMIENTODECOMPRA_HORAEXPO,
	C_REQUERIMIENTODECOMPRA.HORAIMPO as REQUERIMIENTODECOMPRA_HORAIMPO,
	C_REQUERIMIENTODECOMPRA.HMODIFW as REQUERIMIENTODECOMPRA_HMODIFW,
	C_REQUERIMIENTODECOMPRA.SALTAFW as REQUERIMIENTODECOMPRA_SALTAFW,
	C_REQUERIMIENTODECOMPRA.SMODIFW as REQUERIMIENTODECOMPRA_SMODIFW,
	C_REQUERIMIENTODECOMPRA.UALTAFW as REQUERIMIENTODECOMPRA_UALTAFW,
	C_REQUERIMIENTODECOMPRA.UMODIFW as REQUERIMIENTODECOMPRA_UMODIFW,
	C_REQUERIMIENTODECOMPRA.VALTAFW as REQUERIMIENTODECOMPRA_VALTAFW,
	C_REQUERIMIENTODECOMPRA.VMODIFW as REQUERIMIENTODECOMPRA_VMODIFW,
	C_REQUERIMIENTODECOMPRA.ZADSFW as REQUERIMIENTODECOMPRA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMARTICULOSREQCOMPRA__SUCURSAL,
	cast( funciones.identificadordecomprobanteparalistado(c_requerimientodecompra.facttipo, c_requerimientodecompra.fletra, c_requerimientodecompra.fptoven, c_requerimientodecompra.fnumcomp) as varchar( 20 ) ) as REQUERIMIENTODECOMPRA_1_ComprobanteVirtual,
	C_REQUERIMIENTODECOMPRA.MONEDA as REQUERIMIENTODECOMPRA_Moneda,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_PROVEEDOR76.CLNOM as PROVEEDOR76_CLNOM,
	C_LISTADEPRECIOS120.LPR_NOMBRE as LISTADEPRECIOS120_LPR_NOMBRE,
	C_CONDICIONDEPAGO121.CLNOM as CONDICIONDEPAGO121_CLNOM,
	C_MOTIVO.MOTDES as MOTIVO_MOTDES,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVEEDOR3.CLNOM as PROVEEDOR3_CLNOM,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_PALETADECOLORES.DESCRIP as PALETADECOLORES_Descrip,
	C_CURVADETALLES.DESCRIP as CURVADETALLES_Descrip,
	C_NOMENCLADORARBA.NMCDES as NOMENCLADORARBA_NMCDES,
	C_MARCA.DESCRIP as MARCA_Descrip,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_PROVEEDOR76.CLIVA as PROVEEDOR76_CLIVA,
	C_PAISES.PDES as PAISES_pdes,
	C_CLASIFICACIONPROVEEDOR.CLADES as CLASIFICACIONPROVEEDOR_CLADES,
	C_CONDICIONDEPAGO99.CLNOM as CONDICIONDEPAGO99_CLNOM,
	C_LISTADEPRECIOS102.LPR_NOMBRE as LISTADEPRECIOS102_LPR_NOMBRE,
	C_IMPUESTO104.DESCRIP as IMPUESTO104_descrip,
	C_IMPUESTO105.DESCRIP as IMPUESTO105_descrip,
	C_IMPUESTO106.DESCRIP as IMPUESTO106_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_CLASIFICACIONPROVEEDOR.CLACOD as CLASIFICACIONPROVEEDOR_CLACOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_CONDICIONDEPAGO99.CLCOD as CONDICIONDEPAGO99_CLCOD,
	C_CONDICIONDEPAGO121.CLCOD as CONDICIONDEPAGO121_CLCOD,
	C_CURVADETALLES.CODIGO as CURVADETALLES_Codigo,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_IMPUESTO104.CODIGO as IMPUESTO104_codigo,
	C_IMPUESTO105.CODIGO as IMPUESTO105_codigo,
	C_IMPUESTO106.CODIGO as IMPUESTO106_codigo,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS102.LPR_NUMERO as LISTADEPRECIOS102_LPR_NUMERO,
	C_LISTADEPRECIOS120.LPR_NUMERO as LISTADEPRECIOS120_LPR_NUMERO,
	C_MARCA.CODIGO as MARCA_Codigo,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_MOTIVO.MOTCOD as MOTIVO_MOTCOD,
	C_NOMENCLADORARBA.NMCCOD as NOMENCLADORARBA_NMCCOD,
	C_PAISES.PCOD as PAISES_pcod,
	C_PALETADECOLORES.CODIGO as PALETADECOLORES_Codigo,
	C_PROVEEDOR3.CLCOD as PROVEEDOR3_CLCOD,
	C_PROVEEDOR76.CLCOD as PROVEEDOR76_CLCOD,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from ZooLogic.REQCOMPRADET as c_ITEMARTICULOSREQCOMPRA
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSREQCOMPRA.FART and 0 = Funciones.empty( C_ITEMARTICULOSREQCOMPRA.FART )
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = C_ARTICULO.CATEARTI and 0 = Funciones.empty( C_ARTICULO.CATEARTI )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = C_ARTICULO.CLASIFART and 0 = Funciones.empty( C_ARTICULO.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSREQCOMPRA.FCOLO and 0 = Funciones.empty( C_ITEMARTICULOSREQCOMPRA.FCOLO )
 left join ZooLogic.CTALLE as C_CURVADETALLES on C_CURVADETALLES.CODIGO = C_ARTICULO.CURTALL and 0 = Funciones.empty( C_ARTICULO.CURTALL )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.MARCAS as C_MARCA on C_MARCA.CODIGO = C_ARTICULO.MARCA and 0 = Funciones.empty( C_ARTICULO.MARCA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.NMCARBA as C_NOMENCLADORARBA on C_NOMENCLADORARBA.NMCCOD = C_ARTICULO.ARTNARBA and 0 = Funciones.empty( C_ARTICULO.ARTNARBA )
 left join ZooLogic.PCOLOR as C_PALETADECOLORES on C_PALETADECOLORES.CODIGO = C_ARTICULO.PALCOL and 0 = Funciones.empty( C_ARTICULO.PALCOL )
 left join ZooLogic.PROV as C_PROVEEDOR3 on C_PROVEEDOR3.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ZooLogic.REQCOMPRA as C_REQUERIMIENTODECOMPRA on C_REQUERIMIENTODECOMPRA.CODIGO = C_ITEMARTICULOSREQCOMPRA.CODIGO and 0 = Funciones.empty( C_ITEMARTICULOSREQCOMPRA.CODIGO )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSREQCOMPRA.FTALL and 0 = Funciones.empty( C_ITEMARTICULOSREQCOMPRA.FTALL )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = C_ARTICULO.UNIMED and 0 = Funciones.empty( C_ARTICULO.UNIMED )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO121 on C_CONDICIONDEPAGO121.CLCOD = C_REQUERIMIENTODECOMPRA.CONDPAGO and 0 = Funciones.empty( C_REQUERIMIENTODECOMPRA.CONDPAGO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS120 on C_LISTADEPRECIOS120.LPR_NUMERO = C_REQUERIMIENTODECOMPRA.CODLISTA and 0 = Funciones.empty( C_REQUERIMIENTODECOMPRA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_REQUERIMIENTODECOMPRA.MONEDA and 0 = Funciones.empty( C_REQUERIMIENTODECOMPRA.MONEDA )
 left join ZooLogic.MOTIVO as C_MOTIVO on C_MOTIVO.MOTCOD = C_REQUERIMIENTODECOMPRA.MOTIVO and 0 = Funciones.empty( C_REQUERIMIENTODECOMPRA.MOTIVO )
 left join ZooLogic.PROV as C_PROVEEDOR76 on C_PROVEEDOR76.CLCOD = C_REQUERIMIENTODECOMPRA.FPERSON and 0 = Funciones.empty( C_REQUERIMIENTODECOMPRA.FPERSON )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_PROVEEDOR76.CLPRV and 0 = Funciones.empty( C_PROVEEDOR76.CLPRV )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_PROVEEDOR76.CLIVA and 0 = Funciones.empty( C_PROVEEDOR76.CLIVA )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR on C_CLASIFICACIONPROVEEDOR.CLACOD = C_PROVEEDOR76.CLAS and 0 = Funciones.empty( C_PROVEEDOR76.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO99 on C_CONDICIONDEPAGO99.CLCOD = C_PROVEEDOR76.CLCONDPAG and 0 = Funciones.empty( C_PROVEEDOR76.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_PROVEEDOR76.CLSIPRIB and 0 = Funciones.empty( C_PROVEEDOR76.CLSIPRIB )
 left join ZooLogic.IMPUESTO as C_IMPUESTO104 on C_IMPUESTO104.CODIGO = C_PROVEEDOR76.CLRETGAN and 0 = Funciones.empty( C_PROVEEDOR76.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO105 on C_IMPUESTO105.CODIGO = C_PROVEEDOR76.CLRETSUSS and 0 = Funciones.empty( C_PROVEEDOR76.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO106 on C_IMPUESTO106.CODIGO = C_PROVEEDOR76.CLRETIVA and 0 = Funciones.empty( C_PROVEEDOR76.CLRETIVA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS102 on C_LISTADEPRECIOS102.LPR_NUMERO = C_PROVEEDOR76.CLLISTPRE and 0 = Funciones.empty( C_PROVEEDOR76.CLLISTPRE )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_PROVEEDOR76.PPAIS and 0 = Funciones.empty( C_PROVEEDOR76.PPAIS )
 where ( 1=1 ) and 
( not 1 = funciones.empty( c_itemarticulosreqcompra.codigo ) and ( not 1 = funciones.empty( c_requerimientodecompra.codigo ) and c_requerimientodecompra.facttipo = 42 ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.Moneda >= @REQUERIMIENTODECOMPRA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.Moneda <= @REQUERIMIENTODECOMPRA_1_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_ARTICULO_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FART >= @ITEMARTICULOSREQCOMPRA_ARTICULO_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_ARTICULO_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FART <= @ITEMARTICULOSREQCOMPRA_ARTICULO_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_ARTICULODETALLE_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FTXT >= @ITEMARTICULOSREQCOMPRA_ARTICULODETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_ARTICULODETALLE_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FTXT <= @ITEMARTICULOSREQCOMPRA_ARTICULODETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_COLOR_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCOLO >= @ITEMARTICULOSREQCOMPRA_COLOR_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_COLOR_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCOLO <= @ITEMARTICULOSREQCOMPRA_COLOR_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_COLORDETALLE_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCOTXT >= @ITEMARTICULOSREQCOMPRA_COLORDETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_COLORDETALLE_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCOTXT <= @ITEMARTICULOSREQCOMPRA_COLORDETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_TALLE_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FTALL >= @ITEMARTICULOSREQCOMPRA_TALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_TALLE_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FTALL <= @ITEMARTICULOSREQCOMPRA_TALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_CANTIDAD_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCANT >= @ITEMARTICULOSREQCOMPRA_CANTIDAD_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_CANTIDAD_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCANT <= @ITEMARTICULOSREQCOMPRA_CANTIDAD_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_PRECIO_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FPRECIO >= @ITEMARTICULOSREQCOMPRA_PRECIO_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_PRECIO_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FPRECIO <= @ITEMARTICULOSREQCOMPRA_PRECIO_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_DESCUENTO_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCFI >= @ITEMARTICULOSREQCOMPRA_DESCUENTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_DESCUENTO_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FCFI <= @ITEMARTICULOSREQCOMPRA_DESCUENTO_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_MONTODESCUENTO_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.MNTDES >= @ITEMARTICULOSREQCOMPRA_MONTODESCUENTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_MONTODESCUENTO_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.MNTDES <= @ITEMARTICULOSREQCOMPRA_MONTODESCUENTO_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_MONTO_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FMONTO >= @ITEMARTICULOSREQCOMPRA_MONTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_MONTO_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.FMONTO <= @ITEMARTICULOSREQCOMPRA_MONTO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_CODIGO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.CODIGO >= @REQUERIMIENTODECOMPRA_1_CODIGO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_CODIGO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.CODIGO <= @REQUERIMIENTODECOMPRA_1_CODIGO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_PROVEEDOR_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FPerson >= @REQUERIMIENTODECOMPRA_1_PROVEEDOR_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_PROVEEDOR_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FPerson <= @REQUERIMIENTODECOMPRA_1_PROVEEDOR_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_LISTADEPRECIOS_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.CodLista >= @REQUERIMIENTODECOMPRA_1_LISTADEPRECIOS_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_LISTADEPRECIOS_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.CodLista <= @REQUERIMIENTODECOMPRA_1_LISTADEPRECIOS_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.CONDPAGO >= @REQUERIMIENTODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.CONDPAGO <= @REQUERIMIENTODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_MOTIVO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.MOTIVO >= @REQUERIMIENTODECOMPRA_1_MOTIVO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_MOTIVO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.MOTIVO <= @REQUERIMIENTODECOMPRA_1_MOTIVO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_LETRA_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FLETRA >= @REQUERIMIENTODECOMPRA_1_LETRA_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_LETRA_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FLETRA <= @REQUERIMIENTODECOMPRA_1_LETRA_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_PUNTODEVENTA_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FPTOVEN >= @REQUERIMIENTODECOMPRA_1_PUNTODEVENTA_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_PUNTODEVENTA_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FPTOVEN <= @REQUERIMIENTODECOMPRA_1_PUNTODEVENTA_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_NUMERO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FNUMCOMP >= @REQUERIMIENTODECOMPRA_1_NUMERO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_NUMERO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FNUMCOMP <= @REQUERIMIENTODECOMPRA_1_NUMERO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHA_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FFCH >= @REQUERIMIENTODECOMPRA_1_FECHA_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHA_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FFCH <= @REQUERIMIENTODECOMPRA_1_FECHA_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_COTIZACION_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.Cotiz >= @REQUERIMIENTODECOMPRA_1_COTIZACION_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_COTIZACION_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.Cotiz <= @REQUERIMIENTODECOMPRA_1_COTIZACION_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAVENCIMIENTO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FFCHVENC >= @REQUERIMIENTODECOMPRA_1_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAVENCIMIENTO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FFCHVENC <= @REQUERIMIENTODECOMPRA_1_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FPODES >= @REQUERIMIENTODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FPODES <= @REQUERIMIENTODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_DESCUENTO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.fDescu >= @REQUERIMIENTODECOMPRA_1_DESCUENTO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_DESCUENTO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.fDescu <= @REQUERIMIENTODECOMPRA_1_DESCUENTO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FMTDES3 >= @REQUERIMIENTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FMTDES3 <= @REQUERIMIENTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_RECARGOPORCENTAJE_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.RecPor >= @REQUERIMIENTODECOMPRA_1_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_RECARGOPORCENTAJE_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.RecPor <= @REQUERIMIENTODECOMPRA_1_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_RECARGOMONTO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.MR >= @REQUERIMIENTODECOMPRA_1_RECARGOMONTO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_RECARGOMONTO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.MR <= @REQUERIMIENTODECOMPRA_1_RECARGOMONTO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_RECARGOMONTO2_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.RecMonto2 >= @REQUERIMIENTODECOMPRA_1_RECARGOMONTO2_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_RECARGOMONTO2_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.RecMonto2 <= @REQUERIMIENTODECOMPRA_1_RECARGOMONTO2_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_IMPUESTOS_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.fImpuesto >= @REQUERIMIENTODECOMPRA_1_IMPUESTOS_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_IMPUESTOS_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.fImpuesto <= @REQUERIMIENTODECOMPRA_1_IMPUESTOS_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_TOTALIMPUESTOS_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.totimpue >= @REQUERIMIENTODECOMPRA_1_TOTALIMPUESTOS_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_TOTALIMPUESTOS_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.totimpue <= @REQUERIMIENTODECOMPRA_1_TOTALIMPUESTOS_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_TOTAL_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FTotal >= @REQUERIMIENTODECOMPRA_1_TOTAL_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_TOTAL_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FTotal <= @REQUERIMIENTODECOMPRA_1_TOTAL_HASTA ) ) and 
	( ( @PROVEEDOR_76_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR76.CLNOM >= @PROVEEDOR_76_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_76_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR76.CLNOM <= @PROVEEDOR_76_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @LISTADEPRECIOS_120_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS120.LPR_NOMBRE >= @LISTADEPRECIOS_120_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_120_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS120.LPR_NOMBRE <= @LISTADEPRECIOS_120_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_121_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO121.CLNOM >= @CONDICIONDEPAGO_121_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_121_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO121.CLNOM <= @CONDICIONDEPAGO_121_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @MOTIVO_122_MOTIVO_DESCRIPCION_DESDE is null ) OR ( C_MOTIVO.MOTDES >= @MOTIVO_122_MOTIVO_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVO_122_MOTIVO_DESCRIPCION_HASTA is null ) OR ( C_MOTIVO.MOTDES <= @MOTIVO_122_MOTIVO_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_8148_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_8148_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_8148_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_8148_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR3.CLNOM >= @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR3.CLNOM <= @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_13_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_13_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_14_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_14_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE is null ) OR ( C_PALETADECOLORES.Descrip >= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA is null ) OR ( C_PALETADECOLORES.Descrip <= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE is null ) OR ( C_CURVADETALLES.Descrip >= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA is null ) OR ( C_CURVADETALLES.Descrip <= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE is null ) OR ( C_NOMENCLADORARBA.NMCDES >= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA is null ) OR ( C_NOMENCLADORARBA.NMCDES <= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_DESDE is null ) OR ( C_MARCA.Descrip >= @MARCA_42_MARCA_DESCRIPCION_DESDE ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_HASTA is null ) OR ( C_MARCA.Descrip <= @MARCA_42_MARCA_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_79_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_79_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_79_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_79_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_95_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_95_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_95_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_95_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_97_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES >= @CLASIFICACIONPROVEEDOR_97_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_97_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES <= @CLASIFICACIONPROVEEDOR_97_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_99_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO99.CLNOM >= @CONDICIONDEPAGO_99_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_99_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO99.CLNOM <= @CONDICIONDEPAGO_99_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_102_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS102.LPR_NOMBRE >= @LISTADEPRECIOS_102_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_102_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS102.LPR_NOMBRE <= @LISTADEPRECIOS_102_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_104_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO104.descrip >= @IMPUESTO_104_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_104_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO104.descrip <= @IMPUESTO_104_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_105_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO105.descrip >= @IMPUESTO_105_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_105_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO105.descrip <= @IMPUESTO_105_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_106_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO106.descrip >= @IMPUESTO_106_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_106_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO106.descrip <= @IMPUESTO_106_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_115_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_115_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_115_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_115_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_8144_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_8144_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_8144_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_8144_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_8144_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_8144_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_8144_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_8144_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_8144_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_8144_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_8144_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_8144_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_8144_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_8144_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_8144_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_8144_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_2_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_2_PROVEEDOR_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVAVENTAS is null ) OR ( C_ARTICULO.ARTCONIVA = @ARTICULO_2_CONDICIONIVAVENTAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE is null ) OR ( C_ARTICULO.ARTPORIVA >= @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA is null ) OR ( C_ARTICULO.ARTPORIVA <= @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA ) ) and 
	( ( @ARTICULO_2_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_2_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_2_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_2_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_2_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_2_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_2_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_2_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_2_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_2_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_2_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_2_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_2_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_2_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_2_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_2_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_2_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_2_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_2_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_2_LINEA_DESDE ) ) and 
	( ( @ARTICULO_2_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_2_LINEA_HASTA ) ) and 
	( ( @ARTICULO_2_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_2_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_2_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_2_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_2_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_2_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_2_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_2_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_2_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_2_ANO_DESDE ) ) and 
	( ( @ARTICULO_2_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_2_ANO_HASTA ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_2_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_2_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVACOMPRAS is null ) OR ( C_ARTICULO.ARTIVA = @ARTICULO_2_CONDICIONIVACOMPRAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE is null ) OR ( C_ARTICULO.ANX2 >= @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA is null ) OR ( C_ARTICULO.ANX2 <= @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA ) ) and 
	( ( @ARTICULO_2_COMPORTAMIENTO is null ) OR ( C_ARTICULO.ASTOCK = @ARTICULO_2_COMPORTAMIENTO ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_DESDE is null ) OR ( C_ARTICULO.PalCol >= @ARTICULO_2_PALETADECOLORES_DESDE ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_HASTA is null ) OR ( C_ARTICULO.PalCol <= @ARTICULO_2_PALETADECOLORES_HASTA ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_DESDE is null ) OR ( C_ARTICULO.Curtall >= @ARTICULO_2_CURVADETALLES_DESDE ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_HASTA is null ) OR ( C_ARTICULO.Curtall <= @ARTICULO_2_CURVADETALLES_HASTA ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_DESDE is null ) OR ( C_ARTICULO.NOCOM >= @ARTICULO_2_NOCOMERCIALIZABLE_DESDE ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_HASTA is null ) OR ( C_ARTICULO.NOCOM <= @ARTICULO_2_NOCOMERCIALIZABLE_HASTA ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_DESDE is null ) OR ( C_ARTICULO.ARTNARBA >= @ARTICULO_2_NOMENCLADOR_DESDE ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_HASTA is null ) OR ( C_ARTICULO.ARTNARBA <= @ARTICULO_2_NOMENCLADOR_HASTA ) ) and 
	( ( @ARTICULO_2_NOPERMITEDEVOLUCIONES is null ) OR ( C_ARTICULO.ARTNODEVO = @ARTICULO_2_NOPERMITEDEVOLUCIONES ) ) and 
	( ( @ARTICULO_2_IMPRIMEDESPACHO is null ) OR ( C_ARTICULO.EsImpDes = @ARTICULO_2_IMPRIMEDESPACHO ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE is null ) OR ( C_ARTICULO.impinterno >= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA is null ) OR ( C_ARTICULO.impinterno <= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA ) ) and 
	( ( @ARTICULO_2_RESTRINGIRDESCUENTOS is null ) OR ( C_ARTICULO.ArtSinDes = @ARTICULO_2_RESTRINGIRDESCUENTOS ) ) and 
	( ( @ARTICULO_2_PESO_DESDE is null ) OR ( C_ARTICULO.ARTPESO >= @ARTICULO_2_PESO_DESDE ) ) and 
	( ( @ARTICULO_2_PESO_HASTA is null ) OR ( C_ARTICULO.ARTPESO <= @ARTICULO_2_PESO_HASTA ) ) and 
	( ( @ARTICULO_2_LARGO_DESDE is null ) OR ( C_ARTICULO.ARTLARGO >= @ARTICULO_2_LARGO_DESDE ) ) and 
	( ( @ARTICULO_2_LARGO_HASTA is null ) OR ( C_ARTICULO.ARTLARGO <= @ARTICULO_2_LARGO_HASTA ) ) and 
	( ( @ARTICULO_2_ANCHO_DESDE is null ) OR ( C_ARTICULO.ARTANCHO >= @ARTICULO_2_ANCHO_DESDE ) ) and 
	( ( @ARTICULO_2_ANCHO_HASTA is null ) OR ( C_ARTICULO.ARTANCHO <= @ARTICULO_2_ANCHO_HASTA ) ) and 
	( ( @ARTICULO_2_ALTO_DESDE is null ) OR ( C_ARTICULO.ARTALTO >= @ARTICULO_2_ALTO_DESDE ) ) and 
	( ( @ARTICULO_2_ALTO_HASTA is null ) OR ( C_ARTICULO.ARTALTO <= @ARTICULO_2_ALTO_HASTA ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_DESDE is null ) OR ( C_ARTICULO.ReqCCosto >= @ARTICULO_2_REQUIERECCOSTO_DESDE ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_HASTA is null ) OR ( C_ARTICULO.ReqCCosto <= @ARTICULO_2_REQUIERECCOSTO_HASTA ) ) and 
	( ( @ARTICULO_2_NOPUBLICARENECOMMERCE is null ) OR ( C_ARTICULO.PubEcom = @ARTICULO_2_NOPUBLICARENECOMMERCE ) ) and 
	( ( @ARTICULO_2_IMPORTADO is null ) OR ( C_ARTICULO.Importado = @ARTICULO_2_IMPORTADO ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE is null ) OR ( C_ARTICULO.ARTDESADIC >= @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA is null ) OR ( C_ARTICULO.ARTDESADIC <= @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA ) ) and 
	( ( @ARTICULO_2_SOLOPROMOYKIT is null ) OR ( C_ARTICULO.PromoYKit = @ARTICULO_2_SOLOPROMOYKIT ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_DESDE is null ) OR ( C_ARTICULO.ArtRest >= @ARTICULO_2_RESTRINGIRARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_HASTA is null ) OR ( C_ARTICULO.ArtRest <= @ARTICULO_2_RESTRINGIRARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_MARCA_DESDE is null ) OR ( C_ARTICULO.Marca >= @ARTICULO_2_MARCA_DESDE ) ) and 
	( ( @ARTICULO_2_MARCA_HASTA is null ) OR ( C_ARTICULO.Marca <= @ARTICULO_2_MARCA_HASTA ) ) and 
	( ( @ARTICULO_2_PERCEPCIONIVARG5329 is null ) OR ( C_ARTICULO.ArtPercep = @ARTICULO_2_PERCEPCIONIVARG5329 ) ) and 
	( ( @PROVEEDOR_76_LOCALIDAD_DESDE is null ) OR ( C_PROVEEDOR76.CLLOC >= @PROVEEDOR_76_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_76_LOCALIDAD_HASTA is null ) OR ( C_PROVEEDOR76.CLLOC <= @PROVEEDOR_76_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_76_CODIGOPOSTAL_DESDE is null ) OR ( C_PROVEEDOR76.CLCP >= @PROVEEDOR_76_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_76_CODIGOPOSTAL_HASTA is null ) OR ( C_PROVEEDOR76.CLCP <= @PROVEEDOR_76_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_76_PROVINCIA_DESDE is null ) OR ( C_PROVEEDOR76.CLPRV >= @PROVEEDOR_76_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_76_PROVINCIA_HASTA is null ) OR ( C_PROVEEDOR76.CLPRV <= @PROVEEDOR_76_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_76_TELEFONO_DESDE is null ) OR ( C_PROVEEDOR76.CLTLF >= @PROVEEDOR_76_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_76_TELEFONO_HASTA is null ) OR ( C_PROVEEDOR76.CLTLF <= @PROVEEDOR_76_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_76_FAX_DESDE is null ) OR ( C_PROVEEDOR76.CLFAX >= @PROVEEDOR_76_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_76_FAX_HASTA is null ) OR ( C_PROVEEDOR76.CLFAX <= @PROVEEDOR_76_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_76_EMAIL_DESDE is null ) OR ( C_PROVEEDOR76.CLEMAIL >= @PROVEEDOR_76_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_76_EMAIL_HASTA is null ) OR ( C_PROVEEDOR76.CLEMAIL <= @PROVEEDOR_76_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_76_PAGINAWEB_DESDE is null ) OR ( C_PROVEEDOR76.CLPAGEWEB >= @PROVEEDOR_76_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_76_PAGINAWEB_HASTA is null ) OR ( C_PROVEEDOR76.CLPAGEWEB <= @PROVEEDOR_76_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_84_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_84_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_76_CUIT_DESDE is null ) OR ( C_PROVEEDOR76.CLCUIT >= @PROVEEDOR_76_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_76_CUIT_HASTA is null ) OR ( C_PROVEEDOR76.CLCUIT <= @PROVEEDOR_76_CUIT_HASTA ) ) and 
	( ( @PROVEEDOR_76_TIPODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR76.CLTIPODOC >= @PROVEEDOR_76_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_76_TIPODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR76.CLTIPODOC <= @PROVEEDOR_76_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_76_NRODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR76.CLNRODOC >= @PROVEEDOR_76_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_76_NRODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR76.CLNRODOC <= @PROVEEDOR_76_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_76_IMAGEN_DESDE is null ) OR ( C_PROVEEDOR76.CIMAGEN >= @PROVEEDOR_76_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_76_IMAGEN_HASTA is null ) OR ( C_PROVEEDOR76.CIMAGEN <= @PROVEEDOR_76_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_76_NUMERO_DESDE is null ) OR ( C_PROVEEDOR76.PNUMERO >= @PROVEEDOR_76_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_76_NUMERO_HASTA is null ) OR ( C_PROVEEDOR76.PNUMERO <= @PROVEEDOR_76_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_76_CALLE_DESDE is null ) OR ( C_PROVEEDOR76.PCALLE >= @PROVEEDOR_76_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_76_CALLE_HASTA is null ) OR ( C_PROVEEDOR76.PCALLE <= @PROVEEDOR_76_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_76_PISO_DESDE is null ) OR ( C_PROVEEDOR76.PPISO >= @PROVEEDOR_76_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_76_PISO_HASTA is null ) OR ( C_PROVEEDOR76.PPISO <= @PROVEEDOR_76_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_76_DEPARTAMENTO_DESDE is null ) OR ( C_PROVEEDOR76.PDEPTO >= @PROVEEDOR_76_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_76_DEPARTAMENTO_HASTA is null ) OR ( C_PROVEEDOR76.PDEPTO <= @PROVEEDOR_76_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_76_PAIS_DESDE is null ) OR ( C_PROVEEDOR76.PPAIS >= @PROVEEDOR_76_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_76_PAIS_HASTA is null ) OR ( C_PROVEEDOR76.PPAIS <= @PROVEEDOR_76_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_76_MOVIL_DESDE is null ) OR ( C_PROVEEDOR76.TLFM >= @PROVEEDOR_76_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_76_MOVIL_HASTA is null ) OR ( C_PROVEEDOR76.TLFM <= @PROVEEDOR_76_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_76_CLASIFICACION_DESDE is null ) OR ( C_PROVEEDOR76.CLAS >= @PROVEEDOR_76_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_76_CLASIFICACION_HASTA is null ) OR ( C_PROVEEDOR76.CLAS <= @PROVEEDOR_76_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_76_FECHANACIMIENTO_DESDE is null ) OR ( C_PROVEEDOR76.CLFECHA >= @PROVEEDOR_76_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_76_FECHANACIMIENTO_HASTA is null ) OR ( C_PROVEEDOR76.CLFECHA <= @PROVEEDOR_76_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_76_CONDICIONDEPAGO_DESDE is null ) OR ( C_PROVEEDOR76.CLCONDPAG >= @PROVEEDOR_76_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_76_CONDICIONDEPAGO_HASTA is null ) OR ( C_PROVEEDOR76.CLCONDPAG <= @PROVEEDOR_76_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_76_TIPOCONVENIO_DESDE is null ) OR ( C_PROVEEDOR76.CLTIPCONV >= @PROVEEDOR_76_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_76_TIPOCONVENIO_HASTA is null ) OR ( C_PROVEEDOR76.CLTIPCONV <= @PROVEEDOR_76_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_76_NROIIBB_DESDE is null ) OR ( C_PROVEEDOR76.CLNROIIBB >= @PROVEEDOR_76_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_76_NROIIBB_HASTA is null ) OR ( C_PROVEEDOR76.CLNROIIBB <= @PROVEEDOR_76_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_76_LISTADEPRECIO_DESDE is null ) OR ( C_PROVEEDOR76.CLLISTPRE >= @PROVEEDOR_76_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_76_LISTADEPRECIO_HASTA is null ) OR ( C_PROVEEDOR76.CLLISTPRE <= @PROVEEDOR_76_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_76_SITUACIONGANANCIAS is null ) OR ( C_PROVEEDOR76.CLSITGAN = @PROVEEDOR_76_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_76_RETENCIONGANANCIAS_DESDE is null ) OR ( C_PROVEEDOR76.CLRETGAN >= @PROVEEDOR_76_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_76_RETENCIONGANANCIAS_HASTA is null ) OR ( C_PROVEEDOR76.CLRETGAN <= @PROVEEDOR_76_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_76_RETENCIONSUSS_DESDE is null ) OR ( C_PROVEEDOR76.CLRETSUSS >= @PROVEEDOR_76_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_76_RETENCIONSUSS_HASTA is null ) OR ( C_PROVEEDOR76.CLRETSUSS <= @PROVEEDOR_76_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_76_RETENCIONIVA_DESDE is null ) OR ( C_PROVEEDOR76.CLRETIVA >= @PROVEEDOR_76_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_76_RETENCIONIVA_HASTA is null ) OR ( C_PROVEEDOR76.CLRETIVA <= @PROVEEDOR_76_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_76_OBJETOIVA is null ) OR ( C_PROVEEDOR76.CLOBJIVA = @PROVEEDOR_76_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_76_EMPLEADOR is null ) OR ( C_PROVEEDOR76.CLEMPLEAD = @PROVEEDOR_76_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_76_EXCLUIDORETENCIONGANANCIAS is null ) OR ( C_PROVEEDOR76.EXRETGAN = @PROVEEDOR_76_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_76_EXCLUIDORETENCIONIVA is null ) OR ( C_PROVEEDOR76.EXRETIVA = @PROVEEDOR_76_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_76_EXCLUIDORETENCIONSUSS is null ) OR ( C_PROVEEDOR76.EXRETSUSS = @PROVEEDOR_76_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_76_SUJETOVINCULADO is null ) OR ( C_PROVEEDOR76.CLSujVinc = @PROVEEDOR_76_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_76_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_PROVEEDOR76.PVHastaIva >= @PROVEEDOR_76_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_76_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_PROVEEDOR76.PVHastaIva <= @PROVEEDOR_76_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_76_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_PROVEEDOR76.PVHastaGan >= @PROVEEDOR_76_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_76_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_PROVEEDOR76.PVHastaGan <= @PROVEEDOR_76_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_76_CODIGOSIPRIB_DESDE is null ) OR ( C_PROVEEDOR76.CLSIPRIB >= @PROVEEDOR_76_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_76_CODIGOSIPRIB_HASTA is null ) OR ( C_PROVEEDOR76.CLSIPRIB <= @PROVEEDOR_76_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_76_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR76.PorcenTC >= @PROVEEDOR_76_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_76_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR76.PorcenTC <= @PROVEEDOR_76_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_76_TASACEROAPLICA is null ) OR ( C_PROVEEDOR76.AplicaTC = @PROVEEDOR_76_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_76_RUT_DESDE is null ) OR ( C_PROVEEDOR76.RUT >= @PROVEEDOR_76_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_76_RUT_HASTA is null ) OR ( C_PROVEEDOR76.RUT <= @PROVEEDOR_76_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_76_INACTIVOFW is null ) OR ( C_PROVEEDOR76.InactivoFW = @PROVEEDOR_76_INACTIVOFW ) ) and 
	( ( @SUCURSAL_8144_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_8144_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_8144_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_8144_CODIGO_HASTA ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_NROITEM_DESDE is null ) OR ( c_ITEMARTICULOSREQCOMPRA.NroItem >= @ITEMARTICULOSREQCOMPRA_NROITEM_DESDE ) ) and 
	( ( @ITEMARTICULOSREQCOMPRA_NROITEM_HASTA is null ) OR ( c_ITEMARTICULOSREQCOMPRA.NroItem <= @ITEMARTICULOSREQCOMPRA_NROITEM_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAALTAFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FAltaFW >= @REQUERIMIENTODECOMPRA_1_FECHAALTAFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAALTAFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FAltaFW <= @REQUERIMIENTODECOMPRA_1_FECHAALTAFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAALTAFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.HAltaFW >= @REQUERIMIENTODECOMPRA_1_HORAALTAFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAALTAFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.HAltaFW <= @REQUERIMIENTODECOMPRA_1_HORAALTAFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.BDALTAFW >= @REQUERIMIENTODECOMPRA_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.BDALTAFW <= @REQUERIMIENTODECOMPRA_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.BDMODIFW >= @REQUERIMIENTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.BDMODIFW <= @REQUERIMIENTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.ESTTRANS >= @REQUERIMIENTODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.ESTTRANS <= @REQUERIMIENTODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAEXPO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FECEXPO >= @REQUERIMIENTODECOMPRA_1_FECHAEXPO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAEXPO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FECEXPO <= @REQUERIMIENTODECOMPRA_1_FECHAEXPO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAIMPO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FECIMPO >= @REQUERIMIENTODECOMPRA_1_FECHAIMPO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAIMPO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FECIMPO <= @REQUERIMIENTODECOMPRA_1_FECHAIMPO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FMODIFW >= @REQUERIMIENTODECOMPRA_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FMODIFW <= @REQUERIMIENTODECOMPRA_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.FECTRANS >= @REQUERIMIENTODECOMPRA_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.FECTRANS <= @REQUERIMIENTODECOMPRA_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAEXPO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.HORAEXPO >= @REQUERIMIENTODECOMPRA_1_HORAEXPO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAEXPO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.HORAEXPO <= @REQUERIMIENTODECOMPRA_1_HORAEXPO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAIMPO_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.HORAIMPO >= @REQUERIMIENTODECOMPRA_1_HORAIMPO_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAIMPO_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.HORAIMPO <= @REQUERIMIENTODECOMPRA_1_HORAIMPO_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.HMODIFW >= @REQUERIMIENTODECOMPRA_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.HMODIFW <= @REQUERIMIENTODECOMPRA_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_SERIEALTAFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.SALTAFW >= @REQUERIMIENTODECOMPRA_1_SERIEALTAFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_SERIEALTAFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.SALTAFW <= @REQUERIMIENTODECOMPRA_1_SERIEALTAFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.SMODIFW >= @REQUERIMIENTODECOMPRA_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.SMODIFW <= @REQUERIMIENTODECOMPRA_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_USUARIOALTAFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.UALTAFW >= @REQUERIMIENTODECOMPRA_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_USUARIOALTAFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.UALTAFW <= @REQUERIMIENTODECOMPRA_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.UMODIFW >= @REQUERIMIENTODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.UMODIFW <= @REQUERIMIENTODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_VERSIONALTAFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.VALTAFW >= @REQUERIMIENTODECOMPRA_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_VERSIONALTAFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.VALTAFW <= @REQUERIMIENTODECOMPRA_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_REQUERIMIENTODECOMPRA.VMODIFW >= @REQUERIMIENTODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @REQUERIMIENTODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_REQUERIMIENTODECOMPRA.VMODIFW <= @REQUERIMIENTODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA ) )
)
, ComprobantesAfectantes as
	(
	select 
		  dc.IDITEM
		, dc.FCANT
		, Afecta.AFETIPOCOM
		, Afecta.AFECTA
		, Afecta.CODIGO
	from ( select CODIGO, AFECTA, CODINTER, AFETIPOCOM from ZooLogic.COMPAFE where AFETIPO = 'Afectante' ) Afecta
		inner join ( select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.REQCOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.SOLCOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.PRECOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.FACCOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.NCCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.REMCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.PEDCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.CANCOMPRADET
					) dc on Afecta.CODIGO = dc.AFE_COD and Afecta.AFECTA = dc.CODIGO
	where 1=1
	)
, ComprobantesRelacionadosAux( IDITEM, CODIGO, Cantidad, Tipo, TipoAfectado, Secuencia, SecuenciaAfectada, Afectado, Nivel ) as
	(
		select Principal.IDITEM,
			Principal.CODIGO,
			Principal.FCANT,
			Principal.FACTTIPO,
			cast( 0 as numeric(2,0)),
			cast( case
				when Principal.FACTTIPO = 42 then 1 -- Requerimiento
				when Principal.FACTTIPO = 39 then 2 -- Solicitud
				when Principal.FACTTIPO = 30 then 3 -- Presupuesto
				when Principal.FACTTIPO = 38 then 4	-- Pedido
				when Principal.FACTTIPO = 40 then 5	-- Remito
				when Principal.FACTTIPO =  8 then 6	-- Facturas
				else 7
			end as numeric(2, 0)),
			cast( 0 as numeric(2,0)),
			Principal.CODIGO,
			0 as nivel
		from ( select CODIGO, IDITEM, FACTTIPO, FCANT from ConjuntoBase ) as Principal

		union all

		select Anterior.IDITEM,
			Anterior.CODIGO,
			Afecta.FCANT,
			Afecta.AFETIPOCOM,
			Anterior.Tipo,
			cast(case 
				when Afecta.AFETIPOCOM = 42 then 1 -- Requerimiento
				when Afecta.AFETIPOCOM = 39 then 2 -- Solicitud
				when Afecta.AFETIPOCOM = 30 then 3 -- Presupuesto
				when Afecta.AFETIPOCOM = 38 then 4 -- Pedido
				when Afecta.AFETIPOCOM = 40 then 5 -- Remito
				when Afecta.AFETIPOCOM =  8 then 6 -- Facturas
				when Afecta.AFETIPOCOM in (41, 10) and Anterior.TipoAfectado != 41 then -case 
																					when Anterior.Tipo = 42 then 1
																					when Anterior.Tipo = 39 then 2
																					when Anterior.Tipo = 30 then 3
																					when Anterior.Tipo = 38 then 4
																					when Anterior.Tipo = 40 then 5
																					when Anterior.Tipo =  8 then 6
																				else 7
																			end
			else 7
			end as numeric(2, 0)),
			cast(case 
				when Anterior.Tipo = 42 then 1
				when Anterior.Tipo = 39 then 2
				when Anterior.Tipo = 30 then 3
				when Anterior.Tipo = 38 then 4
				when Anterior.Tipo = 40 then 5
				when Anterior.Tipo =  8 then 6
			else 7
			end as numeric(2, 0)),
			Afecta.AFECTA,
			Anterior.nivel + 1
		from ComprobantesRelacionadosAux as Anterior
			inner join ComprobantesAfectantes Afecta on Anterior.Afectado = Afecta.CODIGO and Anterior.IDITEM = Afecta.IDITEM
	where 1=1
			and Anterior.nivel < 7
	)
, CantidadesDistribuidas as
	(
		select cantidades.CODIGO, cantidades.IDITEM
			, case cantidades.Secuencia          when  1								then cantidades.cantidad else 0 end as ConfirmadoS1
			, case cantidades.Secuencia          when -1								then cantidades.cantidad else 0 end as CanceladoS1
			, case when cantidades.SecuenciaAfectada = 1 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS1
			, case cantidades.Secuencia          when  2								then cantidades.cantidad else 0 end as ConfirmadoS2
			, case cantidades.Secuencia          when -2								then cantidades.cantidad else 0 end as CanceladoS2
			, case when cantidades.SecuenciaAfectada = 2 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS2
			, case cantidades.Secuencia          when  3								then cantidades.cantidad else 0 end as ConfirmadoS3
			, case cantidades.Secuencia          when -3								then cantidades.cantidad else 0 end as CanceladoS3
			, case when cantidades.SecuenciaAfectada = 3 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS3
			, case cantidades.Secuencia          when  4								then cantidades.cantidad else 0 end as ConfirmadoS4
			, case cantidades.Secuencia          when -4								then cantidades.cantidad else 0 end as CanceladoS4
			, case when cantidades.SecuenciaAfectada = 4 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS4
			, case cantidades.Secuencia          when  5								then cantidades.cantidad else 0 end as ConfirmadoS5
			, case cantidades.Secuencia          when -5								then cantidades.cantidad else 0 end as CanceladoS5
			, case when cantidades.SecuenciaAfectada = 5 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS5
			, case cantidades.Secuencia          when  6								then cantidades.cantidad else 0 end as ConfirmadoS6
			, case cantidades.Secuencia          when -6								then cantidades.cantidad else 0 end as CanceladoS6
			, case when cantidades.SecuenciaAfectada = 6 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS6
			, case cantidades.Secuencia          when  7								then cantidades.cantidad else 0 end as ConfirmadoS7
			, case cantidades.Secuencia          when -7								then cantidades.cantidad else 0 end as CanceladoS7
			, case when cantidades.SecuenciaAfectada = 7 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS7
		from ComprobantesRelacionadosAux cantidades
	)
, ResumenDeCantidades as
	(
	select CODIGO, IDITEM
		, cast( sum( ConfirmadoS1 ) as numeric( 9, 3 ) )							as confirmadorequerimiento
		, cast( sum( CanceladoS1 ) as numeric( 9, 3 ) )								as canceladorequerimiento
		, cast( sum( AfectadoS1 ) as numeric( 9, 3 ) )								as afectadorequerimiento
		, cast( sum( ConfirmadoS1 - CanceladoS1 - AfectadoS1 ) as numeric( 9, 3 ) ) as pendientesolicitud
		, cast( sum( ConfirmadoS2 ) as numeric( 9, 3 ) )							as confirmadosolicitud
		, cast( sum( CanceladoS2 ) as numeric( 9, 3 ) )								as canceladosolicitud
		, cast( sum( AfectadoS2 ) as numeric( 9, 3 ) )								as afectadosolicitud
		, cast( sum( ConfirmadoS2 - CanceladoS2 - AfectadoS2 ) as numeric( 9, 3 ) ) as pendientepresupuesto
		, cast( sum( ConfirmadoS3 ) as numeric( 9, 3 ) )							as confirmadopresupuesto
		, cast( sum( CanceladoS3 ) as numeric( 9, 3 ) )								as canceladopresupuesto
		, cast( sum( AfectadoS3 ) as numeric( 9, 3 ) )								as afectadopresupuesto
		, cast( sum( ConfirmadoS3 - CanceladoS3 - AfectadoS3 ) as numeric( 9, 3 ) ) as pendientepedido
		, cast( sum( ConfirmadoS4 ) as numeric( 9, 3 ) )							as confirmadopedido
		, cast( sum( CanceladoS4 ) as numeric( 9, 3 ) )								as canceladopedido
		, cast( sum( AfectadoS4 ) as numeric( 9, 3 ) )								as afectadopedido
		, cast( sum( ConfirmadoS4 - CanceladoS4 - AfectadoS4 ) as numeric( 9, 3 ) ) as pendienteremito
		, cast( sum( ConfirmadoS5 ) as numeric( 9, 3 ) )							as confirmadoremito
		, cast( sum( CanceladoS5 ) as numeric( 9, 3 ) )								as canceladoremito
		, cast( sum( AfectadoS5 ) as numeric( 9, 3 ) )								as afectadoremito
		, cast( sum( ConfirmadoS5 - CanceladoS5 - AfectadoS5 ) as numeric( 9, 3 ) ) as pendientefactura
		, cast( sum( ConfirmadoS6 ) as numeric( 9, 3 ) )							as confirmadofactura
		, cast( sum( CanceladoS6 ) as numeric( 9, 3 ) )								as canceladofactura
		, cast( sum( AfectadoS6 ) as numeric( 9, 3 ) )								as afectadofactura
		, cast( sum( ConfirmadoS7 ) as numeric( 9, 3 ) )							as confirmadonotas
		, cast( sum( CanceladoS7 ) as numeric( 9, 3 ) )								as canceladonotas
		, cast( sum( AfectadoS7 ) as numeric( 9, 3 ) )								as afectadonotas
	from CantidadesDistribuidas
	group by CODIGO, IDITEM
	)
Select cb.*, 
	cast( rc.confirmadorequerimiento	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CantidadTramo0Virtual,
	cast( rc.canceladorequerimiento		as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CancelaTramo0Virtual,
	cast( rc.pendientesolicitud		as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_PendienteTramo1Virtual,
	cast( rc.confirmadosolicitud	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CantidadTramo1Virtual,
	cast( rc.canceladosolicitud		as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CancelaTramo1Virtual,
	cast( rc.pendientepresupuesto	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_PendienteTramo2Virtual,
	cast( rc.confirmadopresupuesto	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CantidadTramo2Virtual,
	cast( rc.canceladopresupuesto	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CancelaTramo2Virtual,
	cast( rc.pendientepedido	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_PendienteTramo3Virtual,
	cast( rc.confirmadopedido	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CantidadTramo3Virtual,
	cast( rc.canceladopedido	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CancelaTramo3Virtual,
	cast( rc.pendienteremito	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_PendienteTramo4Virtual,
	cast( rc.confirmadoremito	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CantidadTramo4Virtual,
	cast( rc.canceladoremito	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CancelaTramo4Virtual,
	cast( rc.pendientefactura	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_PendienteTramo5Virtual,
	cast( rc.confirmadofactura	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CantidadTramo5Virtual,
	cast( rc.canceladofactura	as numeric( 9, 3 ) ) as ITEMARTICULOSREQCOMPRA_CancelaTramo5Virtual
from ConjuntoBase cb
	left join ResumenDeCantidades rc on cb.CODIGO = rc.CODIGO and cb.IDITEM = rc.IDITEM