IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_STOCKCOMBINACION_STOCKCOMBINACION]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_STOCKCOMBINACION_STOCKCOMBINACION];
GO;

CREATE FUNCTION [Listados].[GENERICO_STOCKCOMBINACION_STOCKCOMBINACION]
( @BaseDeDatos varchar(8),
	@STOCKCOMBINACION_CODIGO_DESDE varchar(26),
	@STOCKCOMBINACION_CODIGO_HASTA varchar(26),
	@STOCKCOMBINACION_ARTICULO_DESDE varchar(15),
	@STOCKCOMBINACION_ARTICULO_HASTA varchar(15),
	@STOCKCOMBINACION_COLOR_DESDE varchar(6),
	@STOCKCOMBINACION_COLOR_HASTA varchar(6),
	@STOCKCOMBINACION_TALLE_DESDE varchar(5),
	@STOCKCOMBINACION_TALLE_HASTA varchar(5),
	@STOCKCOMBINACION_MINREPOSICION_DESDE numeric(16, 3),
	@STOCKCOMBINACION_MINREPOSICION_HASTA numeric(16, 3),
	@STOCKCOMBINACION_MAXREPOSICION_DESDE numeric(16, 3),
	@STOCKCOMBINACION_MAXREPOSICION_HASTA numeric(16, 3),
	@STOCKCOMBINACION_ENTRANSITO_DESDE numeric(16, 3),
	@STOCKCOMBINACION_ENTRANSITO_HASTA numeric(16, 3),
	@ARTICULO_2_ARTICULO_DESCRIPCION_DESDE varchar(100),
	@ARTICULO_2_ARTICULO_DESCRIPCION_HASTA varchar(100),
	@COLOR_43_COLOR_DESCRIPCION_DESDE varchar(50),
	@COLOR_43_COLOR_DESCRIPCION_HASTA varchar(50),
	@TALLE_45_TALLE_DESCRIPCION_DESDE varchar(50),
	@TALLE_45_TALLE_DESCRIPCION_HASTA varchar(50),
	@SEGMENTACION_10109_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_10109_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_10108_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_10108_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_10107_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_10107_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_12_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_12_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_13_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_13_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@PALETADECOLORES_21_PALETADECOLORES_DESCRIPCION_DESDE varchar(40),
	@PALETADECOLORES_21_PALETADECOLORES_DESCRIPCION_HASTA varchar(40),
	@CURVADETALLES_22_CURVADETALLES_DESCRIPCION_DESDE varchar(40),
	@CURVADETALLES_22_CURVADETALLES_DESCRIPCION_HASTA varchar(40),
	@NOMENCLADORARBA_24_NOMENCLADOR_DESCRIPCION_DESDE varchar(150),
	@NOMENCLADORARBA_24_NOMENCLADOR_DESCRIPCION_HASTA varchar(150),
	@MARCA_41_MARCA_DESCRIPCION_DESDE varchar(100),
	@MARCA_41_MARCA_DESCRIPCION_HASTA varchar(100),
	@SUCURSAL_10104_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_10104_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_10104_LINEA_DESDE varchar(10),
	@SUCURSAL_10104_LINEA_HASTA varchar(10),
	@SUCURSAL_10104_TIPO_DESDE varchar(10),
	@SUCURSAL_10104_TIPO_HASTA varchar(10),
	@SUCURSAL_10104_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_10104_DESCRIPCION_HASTA varchar(50),
	@ARTICULO_2_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_2_PROVEEDOR_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVAVENTAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA numeric(5, 2),
	@ARTICULO_2_IMAGEN_DESDE varchar(180),
	@ARTICULO_2_IMAGEN_HASTA varchar(180),
	@ARTICULO_2_TEMPORADA_DESDE varchar(5),
	@ARTICULO_2_TEMPORADA_HASTA varchar(5),
	@ARTICULO_2_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_2_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_2_FAMILIA_DESDE varchar(10),
	@ARTICULO_2_FAMILIA_HASTA varchar(10),
	@ARTICULO_2_MATERIAL_DESDE varchar(10),
	@ARTICULO_2_MATERIAL_HASTA varchar(10),
	@ARTICULO_2_LINEA_DESDE varchar(10),
	@ARTICULO_2_LINEA_HASTA varchar(10),
	@ARTICULO_2_GRUPO_DESDE varchar(10),
	@ARTICULO_2_GRUPO_HASTA varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_2_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_2_ANO_DESDE numeric(4, 0),
	@ARTICULO_2_ANO_HASTA numeric(4, 0),
	@ARTICULO_2_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_2_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVACOMPRAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA numeric(5, 2),
	@ARTICULO_2_PALETADECOLORES_DESDE varchar(10),
	@ARTICULO_2_PALETADECOLORES_HASTA varchar(10),
	@ARTICULO_2_CURVADETALLES_DESDE varchar(10),
	@ARTICULO_2_CURVADETALLES_HASTA varchar(10),
	@ARTICULO_2_NOCOMERCIALIZABLE_DESDE datetime,
	@ARTICULO_2_NOCOMERCIALIZABLE_HASTA datetime,
	@ARTICULO_2_NOMENCLADOR_DESDE varchar(6),
	@ARTICULO_2_NOMENCLADOR_HASTA varchar(6),
	@ARTICULO_2_NOPERMITEDEVOLUCIONES bit,
	@ARTICULO_2_IMPRIMEDESPACHO bit,
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA numeric(5, 2),
	@ARTICULO_2_RESTRINGIRDESCUENTOS bit,
	@ARTICULO_2_PESO_DESDE numeric(11, 3),
	@ARTICULO_2_PESO_HASTA numeric(11, 3),
	@ARTICULO_2_LARGO_DESDE numeric(11, 2),
	@ARTICULO_2_LARGO_HASTA numeric(11, 2),
	@ARTICULO_2_ANCHO_DESDE numeric(11, 2),
	@ARTICULO_2_ANCHO_HASTA numeric(11, 2),
	@ARTICULO_2_ALTO_DESDE numeric(11, 2),
	@ARTICULO_2_ALTO_HASTA numeric(11, 2),
	@ARTICULO_2_REQUIERECCOSTO_DESDE numeric(1, 0),
	@ARTICULO_2_REQUIERECCOSTO_HASTA numeric(1, 0),
	@ARTICULO_2_NOPUBLICARENECOMMERCE bit,
	@ARTICULO_2_IMPORTADO bit,
	@ARTICULO_2_DESCRIPCIONADICIONAL_DESDE varchar(254),
	@ARTICULO_2_DESCRIPCIONADICIONAL_HASTA varchar(254),
	@ARTICULO_2_SOLOPROMOYKIT bit,
	@ARTICULO_2_RESTRINGIRARTICULO_DESDE datetime,
	@ARTICULO_2_RESTRINGIRARTICULO_HASTA datetime,
	@ARTICULO_2_MARCA_DESDE varchar(30),
	@ARTICULO_2_MARCA_HASTA varchar(30),
	@ARTICULO_2_PERCEPCIONIVARG5329 numeric(1, 0),
	@SUCURSAL_10104_CODIGO_DESDE varchar(10),
	@SUCURSAL_10104_CODIGO_HASTA varchar(10),
	@STOCKCOMBINACION_BASEDEDATOSALTAFW_DESDE varchar(8),
	@STOCKCOMBINACION_BASEDEDATOSALTAFW_HASTA varchar(8),
	@STOCKCOMBINACION_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@STOCKCOMBINACION_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@STOCKCOMBINACION_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@STOCKCOMBINACION_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@STOCKCOMBINACION_FECHAEXPO_DESDE datetime,
	@STOCKCOMBINACION_FECHAEXPO_HASTA datetime,
	@STOCKCOMBINACION_FECHAIMPO_DESDE datetime,
	@STOCKCOMBINACION_FECHAIMPO_HASTA datetime,
	@STOCKCOMBINACION_FECHAMODIFICACIONFW_DESDE datetime,
	@STOCKCOMBINACION_FECHAMODIFICACIONFW_HASTA datetime,
	@STOCKCOMBINACION_FECHATRANSFERENCIA_DESDE datetime,
	@STOCKCOMBINACION_FECHATRANSFERENCIA_HASTA datetime,
	@STOCKCOMBINACION_HORAALTAFW_DESDE varchar(8),
	@STOCKCOMBINACION_HORAALTAFW_HASTA varchar(8),
	@STOCKCOMBINACION_HORAEXPO_DESDE varchar(8),
	@STOCKCOMBINACION_HORAEXPO_HASTA varchar(8),
	@STOCKCOMBINACION_HORAIMPO_DESDE varchar(8),
	@STOCKCOMBINACION_HORAIMPO_HASTA varchar(8),
	@STOCKCOMBINACION_HORAMODIFICACIONFW_DESDE varchar(8),
	@STOCKCOMBINACION_HORAMODIFICACIONFW_HASTA varchar(8),
	@STOCKCOMBINACION_SERIEALTAFW_DESDE varchar(7),
	@STOCKCOMBINACION_SERIEALTAFW_HASTA varchar(7),
	@STOCKCOMBINACION_SERIEMODIFICACIONFW_DESDE varchar(7),
	@STOCKCOMBINACION_SERIEMODIFICACIONFW_HASTA varchar(7),
	@STOCKCOMBINACION_USUARIOALTAFW_DESDE varchar(100),
	@STOCKCOMBINACION_USUARIOALTAFW_HASTA varchar(100),
	@STOCKCOMBINACION_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@STOCKCOMBINACION_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@STOCKCOMBINACION_VERSIONALTAFW_DESDE varchar(13),
	@STOCKCOMBINACION_VERSIONALTAFW_HASTA varchar(13),
	@STOCKCOMBINACION_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@STOCKCOMBINACION_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@ARTICULO_FECHAALTAFW_DESDE datetime,
	@ARTICULO_FECHAALTAFW_HASTA datetime,
	@STOCKCOMBINACION_ENTREGAPEN_DESDE numeric(15, 2),
	@STOCKCOMBINACION_ENTREGAPEN_HASTA numeric(15, 2),
	@Parametro1 varchar(max),
	@Parametro2 varchar(max),
	@Parametro3 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select * from (
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_stockcombinacion.cocod, 38, ' ' ) as varchar( 46 ) ) as STOCKCOMBINACION__Grupo,
	@basededatos as STOCKCOMBINACION__BD,
	c_STOCKCOMBINACION.COCOD as STOCKCOMBINACION_COCOD,
	c_STOCKCOMBINACION.COART as STOCKCOMBINACION_COART,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	c_STOCKCOMBINACION.COCOL as STOCKCOMBINACION_COCOL,
	cast( funciones.obtenerordenenlapaletadecolores(C_STOCKCOMBINACION.COART, C_STOCKCOMBINACION.COCOL, C_STOCKCOMBINACION.PALCOL, C_STOCKCOMBINACION.GRUPO) as numeric( 3, 0 ) ) as STOCKCOMBINACION_OrdenPaletaColores,
	c_STOCKCOMBINACION.TALLE as STOCKCOMBINACION_Talle,
	cast( funciones.obtenerordenenlacurvadetalle(C_STOCKCOMBINACION.COART, C_STOCKCOMBINACION.TALLE, C_STOCKCOMBINACION.CURTALL, C_STOCKCOMBINACION.GRUPO) as numeric( 3, 0 ) ) as STOCKCOMBINACION_OrdenCurvaTalles,
	c_STOCKCOMBINACION.MINREPO as STOCKCOMBINACION_MinRepo,
	c_STOCKCOMBINACION.MAXREPO as STOCKCOMBINACION_MaxRepo,
	c_STOCKCOMBINACION.ENTRANSITO as STOCKCOMBINACION_EnTransito,
	cast( case when c_articulo.tipagrupub<= 1 then upper('todos') when c_articulo.tipagrupub= 2 then upper('ninguno') else stuff((select '; '+rtrim(agrup) from zoologic.agrupubart where codigo = rtrim(c_STOCKCOMBINACION.COART) order by agrup for xml path('')),1,2,'') end as varchar( 254 ) ) as ARTICULO_FiltroDePublicacionesVirtual,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_ARTICULO.ARTCONIVA as ARTICULO_ARTCONIVA,
	C_ARTICULO.ARTPORIVA as ARTICULO_ARTPORIVA,
	C_ARTICULO.AOBS as ARTICULO_AObs,
	c_STOCKCOMBINACION.ATEMPORADA as ARTICULO_ATEMPORADA,
	c_STOCKCOMBINACION.UNIMED as ARTICULO_UniMed,
	c_STOCKCOMBINACION.FAMILIA as ARTICULO_Familia,
	c_STOCKCOMBINACION.MAT as ARTICULO_Mat,
	c_STOCKCOMBINACION.LINEA as ARTICULO_Linea,
	c_STOCKCOMBINACION.GRUPO as ARTICULO_Grupo,
	c_STOCKCOMBINACION.CATEARTI as ARTICULO_CateArti,
	c_STOCKCOMBINACION.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	c_STOCKCOMBINACION.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ARTIVA as ARTICULO_ARTIVA,
	C_ARTICULO.ANX2 as ARTICULO_ANX2,
	c_STOCKCOMBINACION.PALCOL as ARTICULO_PalCol,
	c_STOCKCOMBINACION.CURTALL as ARTICULO_Curtall,
	case when c_articulo.nocom = '01/01/1900 00:00:00' then null else c_articulo.nocom end as ARTICULO_NOCOM,
	c_STOCKCOMBINACION.ARTNARBA as ARTICULO_ARTNARBA,
	C_ARTICULO.ARTNODEVO as ARTICULO_ARTNODEVO,
	C_ARTICULO.ESIMPDES as ARTICULO_EsImpDes,
	C_ARTICULO.IMPINTERNO as ARTICULO_impinterno,
	C_ARTICULO.ARTSINDES as ARTICULO_ArtSinDes,
	C_ARTICULO.ARTPESO as ARTICULO_ARTPESO,
	C_ARTICULO.ARTLARGO as ARTICULO_ARTLARGO,
	C_ARTICULO.ARTANCHO as ARTICULO_ARTANCHO,
	C_ARTICULO.ARTALTO as ARTICULO_ARTALTO,
	C_ARTICULO.REQCCOSTO as ARTICULO_ReqCCosto,
	C_ARTICULO.PUBECOM as ARTICULO_PubEcom,
	C_ARTICULO.IMPORTADO as ARTICULO_Importado,
	C_ARTICULO.ARTDESADIC as ARTICULO_ARTDESADIC,
	C_ARTICULO.PROMOYKIT as ARTICULO_PromoYKit,
	C_ARTICULO.DESECOHTML as ARTICULO_DesEcoHTML,
	C_ARTICULO.DESECO as ARTICULO_DesEco,
	case when c_articulo.artrest = '01/01/1900 00:00:00' then null else c_articulo.artrest end as ARTICULO_ArtRest,
	C_ARTICULO.MARCA as ARTICULO_Marca,
	C_ARTICULO.ARTPERCEP as ARTICULO_ArtPercep,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_STOCKCOMBINACION.BDALTAFW as STOCKCOMBINACION_BDALTAFW,
	c_STOCKCOMBINACION.BDMODIFW as STOCKCOMBINACION_BDMODIFW,
	c_STOCKCOMBINACION.ESTTRANS as STOCKCOMBINACION_ESTTRANS,
	case when c_stockcombinacion.fecexpo = '01/01/1900 00:00:00' then null else c_stockcombinacion.fecexpo end as STOCKCOMBINACION_FECEXPO,
	case when c_stockcombinacion.fecimpo = '01/01/1900 00:00:00' then null else c_stockcombinacion.fecimpo end as STOCKCOMBINACION_FECIMPO,
	case when c_stockcombinacion.fmodifw = '01/01/1900 00:00:00' then null else c_stockcombinacion.fmodifw end as STOCKCOMBINACION_FMODIFW,
	case when c_stockcombinacion.fectrans = '01/01/1900 00:00:00' then null else c_stockcombinacion.fectrans end as STOCKCOMBINACION_FECTRANS,
	c_STOCKCOMBINACION.HALTAFW as STOCKCOMBINACION_HALTAFW,
	c_STOCKCOMBINACION.HORAEXPO as STOCKCOMBINACION_HORAEXPO,
	c_STOCKCOMBINACION.HORAIMPO as STOCKCOMBINACION_HORAIMPO,
	c_STOCKCOMBINACION.HMODIFW as STOCKCOMBINACION_HMODIFW,
	c_STOCKCOMBINACION.SALTAFW as STOCKCOMBINACION_SALTAFW,
	c_STOCKCOMBINACION.SMODIFW as STOCKCOMBINACION_SMODIFW,
	c_STOCKCOMBINACION.UALTAFW as STOCKCOMBINACION_UALTAFW,
	c_STOCKCOMBINACION.UMODIFW as STOCKCOMBINACION_UMODIFW,
	c_STOCKCOMBINACION.VALTAFW as STOCKCOMBINACION_VALTAFW,
	c_STOCKCOMBINACION.VMODIFW as STOCKCOMBINACION_VMODIFW,
	c_STOCKCOMBINACION.ZADSFW as STOCKCOMBINACION_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as STOCKCOMBINACION__SUCURSAL,
	cast( c_STOCKCOMBINACION.PEDIDO   + c_STOCKCOMBINACION.PREPARADO as numeric( 15, 2 ) ) as STOCKCOMBINACION_PedidoVirtual,
	cast( c_STOCKCOMBINACION.COMPCPR as numeric( 15, 2 ) ) as STOCKCOMBINACION_PedidoComprasVirtual,
 	cast( case when @parametro1 = 'stock' then c_stockcombinacion.cocant - case when Funciones.ObtenerSiHabilitaStockSeniado() = 1 then c_stockcombinacion.seniado else 0 end when @parametro1 = 'entransito' then C_STOCKCOMBINACION.ENTRANSITO else C_STOCKCOMBINACION.COCANT + C_STOCKCOMBINACION.ENTRANSITO - case when Funciones.ObtenerSiHabilitaStockSeniado() = 1 then c_stockcombinacion.seniado else 0 end end - coalesce( c_STOCKCOMBINACION.PEDIDO, 0 ) - coalesce( c_STOCKCOMBINACION.PREPARADO, 0) - coalesce( c_STOCKCOMBINACION.EntregaPen, 0) as numeric( 16, 3 ) ) as STOCKCOMBINACION_DisponibleVirtual, -- Para considerar el stock señado: goParametros.ColorYTalle.GestionDeVentas.HabilitaStockSeniado y goParametros.Felino.Generales.HabilitaControlStock
	cast( coalesce( c_STOCKCOMBINACION.COMPCPR, 0 ) + case when @parametro1 = 'stock' then c_stockcombinacion.cocant when @parametro1 = 'entransito' then c_stockcombinacion.entransito else c_stockcombinacion.cocant + c_stockcombinacion.entransito END - coalesce( c_STOCKCOMBINACION.PEDIDO, 0 ) as numeric( 16, 3 ) ) as STOCKCOMBINACION_UtilizableVirtual,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	cast( case when sum(case when @parametro1 = 'stock' then C_STOCKCOMBINACION.COCANT when @parametro1 = 'entransito' then C_STOCKCOMBINACION.ENTRANSITO else C_STOCKCOMBINACION.COCANT+C_STOCKCOMBINACION.ENTRANSITO end) over(partition by @basededatos) = 0 then 0 else case when @parametro1 = 'stock' then C_STOCKCOMBINACION.COCANT when @parametro1 = 'entransito' then C_STOCKCOMBINACION.ENTRANSITO else C_STOCKCOMBINACION.COCANT+C_STOCKCOMBINACION.ENTRANSITO END / sum(case when @parametro1 = 'stock' then C_STOCKCOMBINACION.COCANT when @parametro1 = 'entransito' then C_STOCKCOMBINACION.ENTRANSITO else C_STOCKCOMBINACION.COCANT+C_STOCKCOMBINACION.ENTRANSITO end) over(partition by @basededatos)*100 end as numeric( 12, 4 ) ) as STOCKCOMBINACION_PesoPorcentualCantidad,
	cast( @parametro1 as varchar( 8 ) ) as STOCKCOMBINACION_TipoStockVirtual,
	cast( C_STOCKCOMBINACION.COCANT+C_STOCKCOMBINACION.ENTRANSITO as numeric( 16, 3 ) ) as STOCKCOMBINACION_CantidadTotalVirtual,
	cast( case when @parametro1 = 'stock' then C_STOCKCOMBINACION.COCANT when @parametro1 = 'entransito' then C_STOCKCOMBINACION.ENTRANSITO else C_STOCKCOMBINACION.COCANT+C_STOCKCOMBINACION.ENTRANSITO end as numeric( 16, 3 ) ) as STOCKCOMBINACION_COCANT,
	cast( C_STOCKCOMBINACION.COCANT as numeric( 16, 3 ) ) as STOCKCOMBINACION_CantidadFisicaVirtual,
	convert(date, @parametro2) as STOCKCOMBINACION_FechaDeStockVirtual,
	cast( case when @parametro2 = '' or convert(date, @parametro2) = convert(date, funciones.datetime()) then C_STOCKCOMBINACION.COCANT else funciones.obtenerstockdelacombinacionalafecha(C_STOCKCOMBINACION.COART, C_STOCKCOMBINACION.COCOL, C_STOCKCOMBINACION.TALLE, @parametro2) end as numeric( 16, 3 ) ) as STOCKCOMBINACION_CantidadAFechaVirtual,
	cast( c_stockcombinacion.seniado as numeric( 16, 3 ) ) as STOCKCOMBINACION_SeniadoVirtual,
	cast( funciones.ObtenerFechaUltimaVentaPorArticuloCombinacion(C_STOCKCOMBINACION.COART, C_STOCKCOMBINACION.COCOL, C_STOCKCOMBINACION.TALLE,@Parametro3) as date ) as STOCKCOMBINACION_FechaUltimaVentaVirtual,
	cast( case when @Parametro3 = '' then '1' end as numeric( 1, 0 ) ) as STOCKCOMBINACION_CriterioArticuloVirtual,
	case when c_articulo.faltafw = '01/01/1900 00:00:00' then null else c_articulo.faltafw end as ARTICULO_FALTAFW,
	case when c_stockcombinacion.faltafw = '01/01/1900 00:00:00' then null else c_stockcombinacion.faltafw end as STOCKCOMBINACION_FALTAFW,
	c_STOCKCOMBINACION.ENTREGAPEN as STOCKCOMBINACION_EntregaPen,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVEEDOR.CLNOM as PROVEEDOR_CLNOM,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_PALETADECOLORES.DESCRIP as PALETADECOLORES_Descrip,
	C_CURVADETALLES.DESCRIP as CURVADETALLES_Descrip,
	C_NOMENCLADORARBA.NMCDES as NOMENCLADORARBA_NMCDES,
	C_MARCA.DESCRIP as MARCA_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_CURVADETALLES.CODIGO as CURVADETALLES_Codigo,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MARCA.CODIGO as MARCA_Codigo,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_NOMENCLADORARBA.NMCCOD as NOMENCLADORARBA_NMCCOD,
	C_PALETADECOLORES.CODIGO as PALETADECOLORES_Codigo,
	C_PROVEEDOR.CLCOD as PROVEEDOR_CLCOD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from [Listados].[Vista_COMBExtendida] as c_STOCKCOMBINACION
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_STOCKCOMBINACION.COART and 0 = Funciones.empty( C_STOCKCOMBINACION.COART )
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = c_STOCKCOMBINACION.CATEARTI and 0 = Funciones.empty( c_STOCKCOMBINACION.CATEARTI )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = c_STOCKCOMBINACION.CLASIFART and 0 = Funciones.empty( c_STOCKCOMBINACION.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_STOCKCOMBINACION.COCOL and 0 = Funciones.empty( C_STOCKCOMBINACION.COCOL )
 left join ZooLogic.CTALLE as C_CURVADETALLES on C_CURVADETALLES.CODIGO = C_ARTICULO.CURTALL and 0 = Funciones.empty( C_ARTICULO.CURTALL )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.MARCAS as C_MARCA on C_MARCA.CODIGO = C_ARTICULO.MARCA and 0 = Funciones.empty( C_ARTICULO.MARCA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.NMCARBA as C_NOMENCLADORARBA on C_NOMENCLADORARBA.NMCCOD = C_ARTICULO.ARTNARBA and 0 = Funciones.empty( C_ARTICULO.ARTNARBA )
 left join ZooLogic.PCOLOR as C_PALETADECOLORES on C_PALETADECOLORES.CODIGO = C_ARTICULO.PALCOL and 0 = Funciones.empty( C_ARTICULO.PALCOL )
 left join ZooLogic.PROV as C_PROVEEDOR on C_PROVEEDOR.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_STOCKCOMBINACION.TALLE and 0 = Funciones.empty( C_STOCKCOMBINACION.TALLE )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = c_STOCKCOMBINACION.UNIMED and 0 = Funciones.empty( c_STOCKCOMBINACION.UNIMED )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where	
	--( ( @STOCKCOMBINACION_FECHAALTAFW_DESDE is null ) OR ( funciones.ObtenerFechaUltimaVentaPorArticuloCombinacion(C_STOCKCOMBINACION.COART, C_STOCKCOMBINACION.COCOL, C_STOCKCOMBINACION.TALLE,@Parametro3) >= @STOCKCOMBINACION_FECHAALTAFW_DESDE ) ) and 
	--( ( @STOCKCOMBINACION_FECHAALTAFW_HASTA is null ) OR ( funciones.ObtenerFechaUltimaVentaPorArticuloCombinacion(C_STOCKCOMBINACION.COART, C_STOCKCOMBINACION.COCOL, C_STOCKCOMBINACION.TALLE,@Parametro3) <= @STOCKCOMBINACION_FECHAALTAFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_CODIGO_DESDE is null ) OR ( c_STOCKCOMBINACION.COCOD >= @STOCKCOMBINACION_CODIGO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_CODIGO_HASTA is null ) OR ( c_STOCKCOMBINACION.COCOD <= @STOCKCOMBINACION_CODIGO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_ARTICULO_DESDE is null ) OR ( c_STOCKCOMBINACION.COART >= @STOCKCOMBINACION_ARTICULO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_ARTICULO_HASTA is null ) OR ( c_STOCKCOMBINACION.COART <= @STOCKCOMBINACION_ARTICULO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_COLOR_DESDE is null ) OR ( c_STOCKCOMBINACION.COCOL >= @STOCKCOMBINACION_COLOR_DESDE ) ) and 
	( ( @STOCKCOMBINACION_COLOR_HASTA is null ) OR ( c_STOCKCOMBINACION.COCOL <= @STOCKCOMBINACION_COLOR_HASTA ) ) and 
	( ( @STOCKCOMBINACION_TALLE_DESDE is null ) OR ( c_STOCKCOMBINACION.Talle >= @STOCKCOMBINACION_TALLE_DESDE ) ) and 
	( ( @STOCKCOMBINACION_TALLE_HASTA is null ) OR ( c_STOCKCOMBINACION.Talle <= @STOCKCOMBINACION_TALLE_HASTA ) ) and 
	( ( @STOCKCOMBINACION_MINREPOSICION_DESDE is null ) OR ( c_STOCKCOMBINACION.MinRepo >= @STOCKCOMBINACION_MINREPOSICION_DESDE ) ) and 
	( ( @STOCKCOMBINACION_MINREPOSICION_HASTA is null ) OR ( c_STOCKCOMBINACION.MinRepo <= @STOCKCOMBINACION_MINREPOSICION_HASTA ) ) and 
	( ( @STOCKCOMBINACION_MAXREPOSICION_DESDE is null ) OR ( c_STOCKCOMBINACION.MaxRepo >= @STOCKCOMBINACION_MAXREPOSICION_DESDE ) ) and 
	( ( @STOCKCOMBINACION_MAXREPOSICION_HASTA is null ) OR ( c_STOCKCOMBINACION.MaxRepo <= @STOCKCOMBINACION_MAXREPOSICION_HASTA ) ) and 
	( ( @STOCKCOMBINACION_ENTRANSITO_DESDE is null ) OR ( c_STOCKCOMBINACION.EnTransito >= @STOCKCOMBINACION_ENTRANSITO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_ENTRANSITO_HASTA is null ) OR ( c_STOCKCOMBINACION.EnTransito <= @STOCKCOMBINACION_ENTRANSITO_HASTA ) ) and 
	( ( @ARTICULO_2_ARTICULO_DESCRIPCION_DESDE is null ) OR ( C_ARTICULO.ARTDES >= @ARTICULO_2_ARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @ARTICULO_2_ARTICULO_DESCRIPCION_HASTA is null ) OR ( C_ARTICULO.ARTDES <= @ARTICULO_2_ARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @COLOR_43_COLOR_DESCRIPCION_DESDE is null ) OR ( C_COLOR.COLDES >= @COLOR_43_COLOR_DESCRIPCION_DESDE ) ) and 
	( ( @COLOR_43_COLOR_DESCRIPCION_HASTA is null ) OR ( C_COLOR.COLDES <= @COLOR_43_COLOR_DESCRIPCION_HASTA ) ) and 
	( ( @TALLE_45_TALLE_DESCRIPCION_DESDE is null ) OR ( C_TALLE.Descrip >= @TALLE_45_TALLE_DESCRIPCION_DESDE ) ) and 
	( ( @TALLE_45_TALLE_DESCRIPCION_HASTA is null ) OR ( C_TALLE.Descrip <= @TALLE_45_TALLE_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_10109_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_10109_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_10109_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_10109_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_10108_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_10108_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_10108_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_10108_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_10107_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_10107_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_10107_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_10107_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR.CLNOM >= @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR.CLNOM <= @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_13_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_13_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_14_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_14_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @PALETADECOLORES_21_PALETADECOLORES_DESCRIPCION_DESDE is null ) OR ( C_PALETADECOLORES.Descrip >= @PALETADECOLORES_21_PALETADECOLORES_DESCRIPCION_DESDE ) ) and 
	( ( @PALETADECOLORES_21_PALETADECOLORES_DESCRIPCION_HASTA is null ) OR ( C_PALETADECOLORES.Descrip <= @PALETADECOLORES_21_PALETADECOLORES_DESCRIPCION_HASTA ) ) and 
	( ( @CURVADETALLES_22_CURVADETALLES_DESCRIPCION_DESDE is null ) OR ( C_CURVADETALLES.Descrip >= @CURVADETALLES_22_CURVADETALLES_DESCRIPCION_DESDE ) ) and 
	( ( @CURVADETALLES_22_CURVADETALLES_DESCRIPCION_HASTA is null ) OR ( C_CURVADETALLES.Descrip <= @CURVADETALLES_22_CURVADETALLES_DESCRIPCION_HASTA ) ) and 
	( ( @NOMENCLADORARBA_24_NOMENCLADOR_DESCRIPCION_DESDE is null ) OR ( C_NOMENCLADORARBA.NMCDES >= @NOMENCLADORARBA_24_NOMENCLADOR_DESCRIPCION_DESDE ) ) and 
	( ( @NOMENCLADORARBA_24_NOMENCLADOR_DESCRIPCION_HASTA is null ) OR ( C_NOMENCLADORARBA.NMCDES <= @NOMENCLADORARBA_24_NOMENCLADOR_DESCRIPCION_HASTA ) ) and 
	( ( @MARCA_41_MARCA_DESCRIPCION_DESDE is null ) OR ( C_MARCA.Descrip >= @MARCA_41_MARCA_DESCRIPCION_DESDE ) ) and 
	( ( @MARCA_41_MARCA_DESCRIPCION_HASTA is null ) OR ( C_MARCA.Descrip <= @MARCA_41_MARCA_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_10104_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_10104_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_10104_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_10104_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_10104_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_10104_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_10104_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_10104_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_10104_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_10104_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_10104_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_10104_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_10104_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_10104_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_10104_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_10104_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_2_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_2_PROVEEDOR_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVAVENTAS is null ) OR ( C_ARTICULO.ARTCONIVA = @ARTICULO_2_CONDICIONIVAVENTAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE is null ) OR ( C_ARTICULO.ARTPORIVA >= @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA is null ) OR ( C_ARTICULO.ARTPORIVA <= @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA ) ) and 
	( ( @ARTICULO_2_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_2_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_2_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_2_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_2_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_2_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_2_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_2_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_2_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_2_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_2_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_2_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_2_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_2_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_2_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_2_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_2_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_2_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_2_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_2_LINEA_DESDE ) ) and 
	( ( @ARTICULO_2_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_2_LINEA_HASTA ) ) and 
	( ( @ARTICULO_2_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_2_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_2_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_2_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_2_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_2_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_2_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_2_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_2_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_2_ANO_DESDE ) ) and 
	( ( @ARTICULO_2_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_2_ANO_HASTA ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_2_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_2_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVACOMPRAS is null ) OR ( C_ARTICULO.ARTIVA = @ARTICULO_2_CONDICIONIVACOMPRAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE is null ) OR ( C_ARTICULO.ANX2 >= @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA is null ) OR ( C_ARTICULO.ANX2 <= @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_DESDE is null ) OR ( C_ARTICULO.PalCol >= @ARTICULO_2_PALETADECOLORES_DESDE ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_HASTA is null ) OR ( C_ARTICULO.PalCol <= @ARTICULO_2_PALETADECOLORES_HASTA ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_DESDE is null ) OR ( C_ARTICULO.Curtall >= @ARTICULO_2_CURVADETALLES_DESDE ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_HASTA is null ) OR ( C_ARTICULO.Curtall <= @ARTICULO_2_CURVADETALLES_HASTA ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_DESDE is null ) OR ( C_ARTICULO.NOCOM >= @ARTICULO_2_NOCOMERCIALIZABLE_DESDE ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_HASTA is null ) OR ( C_ARTICULO.NOCOM <= @ARTICULO_2_NOCOMERCIALIZABLE_HASTA ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_DESDE is null ) OR ( C_ARTICULO.ARTNARBA >= @ARTICULO_2_NOMENCLADOR_DESDE ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_HASTA is null ) OR ( C_ARTICULO.ARTNARBA <= @ARTICULO_2_NOMENCLADOR_HASTA ) ) and 
	( ( @ARTICULO_2_NOPERMITEDEVOLUCIONES is null ) OR ( C_ARTICULO.ARTNODEVO = @ARTICULO_2_NOPERMITEDEVOLUCIONES ) ) and 
	( ( @ARTICULO_2_IMPRIMEDESPACHO is null ) OR ( C_ARTICULO.EsImpDes = @ARTICULO_2_IMPRIMEDESPACHO ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE is null ) OR ( C_ARTICULO.impinterno >= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA is null ) OR ( C_ARTICULO.impinterno <= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA ) ) and 
	( ( @ARTICULO_2_RESTRINGIRDESCUENTOS is null ) OR ( C_ARTICULO.ArtSinDes = @ARTICULO_2_RESTRINGIRDESCUENTOS ) ) and 
	( ( @ARTICULO_2_PESO_DESDE is null ) OR ( C_ARTICULO.ARTPESO >= @ARTICULO_2_PESO_DESDE ) ) and 
	( ( @ARTICULO_2_PESO_HASTA is null ) OR ( C_ARTICULO.ARTPESO <= @ARTICULO_2_PESO_HASTA ) ) and 
	( ( @ARTICULO_2_LARGO_DESDE is null ) OR ( C_ARTICULO.ARTLARGO >= @ARTICULO_2_LARGO_DESDE ) ) and 
	( ( @ARTICULO_2_LARGO_HASTA is null ) OR ( C_ARTICULO.ARTLARGO <= @ARTICULO_2_LARGO_HASTA ) ) and 
	( ( @ARTICULO_2_ANCHO_DESDE is null ) OR ( C_ARTICULO.ARTANCHO >= @ARTICULO_2_ANCHO_DESDE ) ) and 
	( ( @ARTICULO_2_ANCHO_HASTA is null ) OR ( C_ARTICULO.ARTANCHO <= @ARTICULO_2_ANCHO_HASTA ) ) and 
	( ( @ARTICULO_2_ALTO_DESDE is null ) OR ( C_ARTICULO.ARTALTO >= @ARTICULO_2_ALTO_DESDE ) ) and 
	( ( @ARTICULO_2_ALTO_HASTA is null ) OR ( C_ARTICULO.ARTALTO <= @ARTICULO_2_ALTO_HASTA ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_DESDE is null ) OR ( C_ARTICULO.ReqCCosto >= @ARTICULO_2_REQUIERECCOSTO_DESDE ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_HASTA is null ) OR ( C_ARTICULO.ReqCCosto <= @ARTICULO_2_REQUIERECCOSTO_HASTA ) ) and 
	( ( @ARTICULO_2_NOPUBLICARENECOMMERCE is null ) OR ( C_ARTICULO.PubEcom = @ARTICULO_2_NOPUBLICARENECOMMERCE ) ) and 
	( ( @ARTICULO_2_IMPORTADO is null ) OR ( C_ARTICULO.Importado = @ARTICULO_2_IMPORTADO ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE is null ) OR ( C_ARTICULO.ARTDESADIC >= @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA is null ) OR ( C_ARTICULO.ARTDESADIC <= @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA ) ) and 
	( ( @ARTICULO_2_SOLOPROMOYKIT is null ) OR ( C_ARTICULO.PromoYKit = @ARTICULO_2_SOLOPROMOYKIT ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_DESDE is null ) OR ( C_ARTICULO.ArtRest >= @ARTICULO_2_RESTRINGIRARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_HASTA is null ) OR ( C_ARTICULO.ArtRest <= @ARTICULO_2_RESTRINGIRARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_MARCA_DESDE is null ) OR ( C_ARTICULO.Marca >= @ARTICULO_2_MARCA_DESDE ) ) and 
	( ( @ARTICULO_2_MARCA_HASTA is null ) OR ( C_ARTICULO.Marca <= @ARTICULO_2_MARCA_HASTA ) ) and 
	( ( @ARTICULO_2_PERCEPCIONIVARG5329 is null ) OR ( C_ARTICULO.ArtPercep = @ARTICULO_2_PERCEPCIONIVARG5329 ) ) and 
	( ( @SUCURSAL_10104_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_10104_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_10104_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_10104_CODIGO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_STOCKCOMBINACION.BDALTAFW >= @STOCKCOMBINACION_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_STOCKCOMBINACION.BDALTAFW <= @STOCKCOMBINACION_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_STOCKCOMBINACION.BDMODIFW >= @STOCKCOMBINACION_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_STOCKCOMBINACION.BDMODIFW <= @STOCKCOMBINACION_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_STOCKCOMBINACION.ESTTRANS >= @STOCKCOMBINACION_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @STOCKCOMBINACION_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_STOCKCOMBINACION.ESTTRANS <= @STOCKCOMBINACION_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @STOCKCOMBINACION_FECHAEXPO_DESDE is null ) OR ( c_STOCKCOMBINACION.FECEXPO >= @STOCKCOMBINACION_FECHAEXPO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_FECHAEXPO_HASTA is null ) OR ( c_STOCKCOMBINACION.FECEXPO <= @STOCKCOMBINACION_FECHAEXPO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_FECHAIMPO_DESDE is null ) OR ( c_STOCKCOMBINACION.FECIMPO >= @STOCKCOMBINACION_FECHAIMPO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_FECHAIMPO_HASTA is null ) OR ( c_STOCKCOMBINACION.FECIMPO <= @STOCKCOMBINACION_FECHAIMPO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_STOCKCOMBINACION.FMODIFW >= @STOCKCOMBINACION_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_STOCKCOMBINACION.FMODIFW <= @STOCKCOMBINACION_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_FECHATRANSFERENCIA_DESDE is null ) OR ( c_STOCKCOMBINACION.FECTRANS >= @STOCKCOMBINACION_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @STOCKCOMBINACION_FECHATRANSFERENCIA_HASTA is null ) OR ( c_STOCKCOMBINACION.FECTRANS <= @STOCKCOMBINACION_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @STOCKCOMBINACION_HORAALTAFW_DESDE is null ) OR ( c_STOCKCOMBINACION.HALTAFW >= @STOCKCOMBINACION_HORAALTAFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_HORAALTAFW_HASTA is null ) OR ( c_STOCKCOMBINACION.HALTAFW <= @STOCKCOMBINACION_HORAALTAFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_HORAEXPO_DESDE is null ) OR ( c_STOCKCOMBINACION.HORAEXPO >= @STOCKCOMBINACION_HORAEXPO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_HORAEXPO_HASTA is null ) OR ( c_STOCKCOMBINACION.HORAEXPO <= @STOCKCOMBINACION_HORAEXPO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_HORAIMPO_DESDE is null ) OR ( c_STOCKCOMBINACION.HORAIMPO >= @STOCKCOMBINACION_HORAIMPO_DESDE ) ) and 
	( ( @STOCKCOMBINACION_HORAIMPO_HASTA is null ) OR ( c_STOCKCOMBINACION.HORAIMPO <= @STOCKCOMBINACION_HORAIMPO_HASTA ) ) and 
	( ( @STOCKCOMBINACION_HORAMODIFICACIONFW_DESDE is null ) OR ( c_STOCKCOMBINACION.HMODIFW >= @STOCKCOMBINACION_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_HORAMODIFICACIONFW_HASTA is null ) OR ( c_STOCKCOMBINACION.HMODIFW <= @STOCKCOMBINACION_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_SERIEALTAFW_DESDE is null ) OR ( c_STOCKCOMBINACION.SALTAFW >= @STOCKCOMBINACION_SERIEALTAFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_SERIEALTAFW_HASTA is null ) OR ( c_STOCKCOMBINACION.SALTAFW <= @STOCKCOMBINACION_SERIEALTAFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_STOCKCOMBINACION.SMODIFW >= @STOCKCOMBINACION_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_STOCKCOMBINACION.SMODIFW <= @STOCKCOMBINACION_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_USUARIOALTAFW_DESDE is null ) OR ( c_STOCKCOMBINACION.UALTAFW >= @STOCKCOMBINACION_USUARIOALTAFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_USUARIOALTAFW_HASTA is null ) OR ( c_STOCKCOMBINACION.UALTAFW <= @STOCKCOMBINACION_USUARIOALTAFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_STOCKCOMBINACION.UMODIFW >= @STOCKCOMBINACION_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_STOCKCOMBINACION.UMODIFW <= @STOCKCOMBINACION_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_VERSIONALTAFW_DESDE is null ) OR ( c_STOCKCOMBINACION.VALTAFW >= @STOCKCOMBINACION_VERSIONALTAFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_VERSIONALTAFW_HASTA is null ) OR ( c_STOCKCOMBINACION.VALTAFW <= @STOCKCOMBINACION_VERSIONALTAFW_HASTA ) ) and 
	( ( @STOCKCOMBINACION_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_STOCKCOMBINACION.VMODIFW >= @STOCKCOMBINACION_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @STOCKCOMBINACION_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_STOCKCOMBINACION.VMODIFW <= @STOCKCOMBINACION_VERSIONMODIFICACIONFW_HASTA ) ) and
	( ( @STOCKCOMBINACION_ENTREGAPEN_DESDE is null ) OR ( c_STOCKCOMBINACION.EntregaPen >= @STOCKCOMBINACION_ENTREGAPEN_DESDE ) ) and 
	( ( @STOCKCOMBINACION_ENTREGAPEN_HASTA is null ) OR ( c_STOCKCOMBINACION.EntregaPen <= @STOCKCOMBINACION_ENTREGAPEN_HASTA ) )	
	) Resultado 
	where 
		( (Resultado.STOCKCOMBINACION_FechaUltimaVentaVirtual is null ) or ( @ARTICULO_FECHAALTAFW_DESDE is null ) OR ( Resultado.STOCKCOMBINACION_FechaUltimaVentaVirtual >= @ARTICULO_FECHAALTAFW_DESDE ) ) and 
		( (Resultado.STOCKCOMBINACION_FechaUltimaVentaVirtual is null ) or ( @ARTICULO_FECHAALTAFW_HASTA is null ) OR ( Resultado.STOCKCOMBINACION_FechaUltimaVentaVirtual <= @ARTICULO_FECHAALTAFW_HASTA ) ) 

)