IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_PROMOCION_PROMOCION]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_PROMOCION_PROMOCION];
GO;

CREATE FUNCTION [Listados].[GENERICO_PROMOCION_PROMOCION]
( @BaseDeDatos varchar(8),
	@PROMOCION_CODIGO_DESDE varchar(15),
	@PROMOCION_CODIGO_HASTA varchar(15),
	@PROMOCION_TIPO_DESDE numeric(1, 0),
	@PROMOCION_TIPO_HASTA numeric(1, 0),
	@PROMOCION_REDONDEO_DESDE varchar(10),
	@PROMOCION_REDONDEO_HASTA varchar(10),
	@PROMOCION_DESCRIPCION_DESDE varchar(200),
	@PROMOCION_DESCRIPCION_HASTA varchar(200),
	@PROMOCION_FECHADESDE_DESDE datetime,
	@PROMOCION_FECHADESDE_HASTA datetime,
	@PROMOCION_FECHAHASTA_DESDE datetime,
	@PROMOCION_FECHAHASTA_HASTA datetime,
	@PROMOCION_HORADESDE_DESDE varchar(8),
	@PROMOCION_HORADESDE_HASTA varchar(8),
	@PROMOCION_HORAHASTA_DESDE varchar(8),
	@PROMOCION_HORAHASTA_HASTA varchar(8),
	@REDONDEODEPRECIOS_22_REDONDEO_DESCRIPCION_DESDE varchar(100),
	@REDONDEODEPRECIOS_22_REDONDEO_DESCRIPCION_HASTA varchar(100),
	@SEGMENTACION_9151_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9151_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9150_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9150_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9149_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9149_TIPO_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9146_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9146_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9146_LINEA_DESDE varchar(10),
	@SUCURSAL_9146_LINEA_HASTA varchar(10),
	@SUCURSAL_9146_TIPO_DESDE varchar(10),
	@SUCURSAL_9146_TIPO_HASTA varchar(10),
	@SUCURSAL_9146_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9146_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9146_CODIGO_DESDE varchar(10),
	@SUCURSAL_9146_CODIGO_HASTA varchar(10),
	@PROMOCION_BASEDEDATOSALTAFW_DESDE varchar(8),
	@PROMOCION_BASEDEDATOSALTAFW_HASTA varchar(8),
	@PROMOCION_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@PROMOCION_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@PROMOCION_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@PROMOCION_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@PROMOCION_FECHAALTAFW_DESDE datetime,
	@PROMOCION_FECHAALTAFW_HASTA datetime,
	@PROMOCION_FECHAEXPO_DESDE datetime,
	@PROMOCION_FECHAEXPO_HASTA datetime,
	@PROMOCION_FECHAIMPO_DESDE datetime,
	@PROMOCION_FECHAIMPO_HASTA datetime,
	@PROMOCION_FECHAMODIFICACIONFW_DESDE datetime,
	@PROMOCION_FECHAMODIFICACIONFW_HASTA datetime,
	@PROMOCION_FECHATRANSFERENCIA_DESDE datetime,
	@PROMOCION_FECHATRANSFERENCIA_HASTA datetime,
	@PROMOCION_HORAALTAFW_DESDE varchar(8),
	@PROMOCION_HORAALTAFW_HASTA varchar(8),
	@PROMOCION_HORAEXPO_DESDE varchar(8),
	@PROMOCION_HORAEXPO_HASTA varchar(8),
	@PROMOCION_HORAIMPO_DESDE varchar(8),
	@PROMOCION_HORAIMPO_HASTA varchar(8),
	@PROMOCION_HORAMODIFICACIONFW_DESDE varchar(8),
	@PROMOCION_HORAMODIFICACIONFW_HASTA varchar(8),
	@PROMOCION_SERIEALTAFW_DESDE varchar(7),
	@PROMOCION_SERIEALTAFW_HASTA varchar(7),
	@PROMOCION_SERIEMODIFICACIONFW_DESDE varchar(7),
	@PROMOCION_SERIEMODIFICACIONFW_HASTA varchar(7),
	@PROMOCION_USUARIOALTAFW_DESDE varchar(100),
	@PROMOCION_USUARIOALTAFW_HASTA varchar(100),
	@PROMOCION_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@PROMOCION_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@PROMOCION_VERSIONALTAFW_DESDE varchar(13),
	@PROMOCION_VERSIONALTAFW_HASTA varchar(13),
	@PROMOCION_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@PROMOCION_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max),
	@Parametro2 varchar(max),
	@Parametro3 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_promocion.codigo, 38, ' ' ) as varchar( 46 ) ) as PROMOCION__Grupo,
	@basededatos as PROMOCION__BD,
	c_PROMOCION.CODIGO as PROMOCION_Codigo,
	c_PROMOCION.TIPO as PROMOCION_Tipo,
	c_PROMOCION.REDONDEO as PROMOCION_Redondeo,
	c_PROMOCION.DESCRIP as PROMOCION_Descrip,
	case when c_promocion.fecdesde = '01/01/1900 00:00:00' then null else c_promocion.fecdesde end as PROMOCION_FecDesde,
	case when c_promocion.fechasta = '01/01/1900 00:00:00' then null else c_promocion.fechasta end as PROMOCION_FecHasta,
	c_PROMOCION.HORADESDE as PROMOCION_HoraDesde,
	c_PROMOCION.HORAHASTA as PROMOCION_HoraHasta,
	cast( case when c_promocion.tipagrupub<= 1 then upper('todos') when c_promocion.tipagrupub= 2 then upper('ninguno') else stuff((select '; '+rtrim(agrup) from zoologic.agrupubpr0 where codigo = rtrim(c_promocion.codigo) order by agrup for xml path('')),1,2,'') end as varchar( 254 ) ) as PROMOCION_FiltroDePublicacionesVirtual,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_PROMOCION.BDALTAFW as PROMOCION_BDALTAFW,
	c_PROMOCION.BDMODIFW as PROMOCION_BDMODIFW,
	c_PROMOCION.ESTTRANS as PROMOCION_ESTTRANS,
	case when c_promocion.faltafw = '01/01/1900 00:00:00' then null else c_promocion.faltafw end as PROMOCION_FALTAFW,
	case when c_promocion.fecexpo = '01/01/1900 00:00:00' then null else c_promocion.fecexpo end as PROMOCION_FECEXPO,
	case when c_promocion.fecimpo = '01/01/1900 00:00:00' then null else c_promocion.fecimpo end as PROMOCION_FECIMPO,
	case when c_promocion.fmodifw = '01/01/1900 00:00:00' then null else c_promocion.fmodifw end as PROMOCION_FMODIFW,
	case when c_promocion.fectrans = '01/01/1900 00:00:00' then null else c_promocion.fectrans end as PROMOCION_FECTRANS,
	c_PROMOCION.HALTAFW as PROMOCION_HALTAFW,
	c_PROMOCION.HORAEXPO as PROMOCION_HORAEXPO,
	c_PROMOCION.HORAIMPO as PROMOCION_HORAIMPO,
	c_PROMOCION.HMODIFW as PROMOCION_HMODIFW,
	c_PROMOCION.SALTAFW as PROMOCION_SALTAFW,
	c_PROMOCION.SMODIFW as PROMOCION_SMODIFW,
	c_PROMOCION.UALTAFW as PROMOCION_UALTAFW,
	c_PROMOCION.UMODIFW as PROMOCION_UMODIFW,
	c_PROMOCION.VALTAFW as PROMOCION_VALTAFW,
	c_PROMOCION.VMODIFW as PROMOCION_VMODIFW,
	c_PROMOCION.ZADSFW as PROMOCION_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as PROMOCION__SUCURSAL,
	cast( funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'diassemana', c_promocion.tipo) as varchar( 120 ) ) as PROMOCION_DiasDeLaSemanaVirtual,
	case when(funciones.datetime() between c_promocion.fecdesde and c_promocion.fechasta) then cast(1 as bit) else cast(0 as bit) end as PROMOCION_FILTROVIGENCIAPORFECHAVIRTUAL,
	funciones.ctot('') as PROMOCION_FiltroVigenciaEnElPeriodoVirtual,
	cast( @parametro3 as varchar( 60 ) ) as PROMOCION_DescripcionTipoVirtual,
	cast( funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'maskcondicion', c_promocion.tipo)+funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'filtrocondicion', c_promocion.tipo) as varchar( 2000 ) ) as PROMOCION_CondicionVirtual,
	cast( funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'maskbeneficio', c_promocion.tipo)+funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'masktopedescuento', c_promocion.tipo)+funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'MASKCUOTASSINRECARGO', c_promocion.tipo)+funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'TIPOPRECIO', c_promocion.tipo)+funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'FILTROBENEFICIO', c_promocion.tipo)+funciones.obtenerinformaciondepromocion(c_promocion.codigo, 'LISTADEPRECIOS', c_promocion.tipo) as varchar( 250 ) ) as PROMOCION_BeneficioVirtual,
	C_REDONDEODEPRECIOS.DESCRIP as REDONDEODEPRECIOS_descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_REDONDEODEPRECIOS.CODIGO as REDONDEODEPRECIOS_codigo,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD
 from ZooLogic.PROMOS as c_PROMOCION
 left join ZooLogic.REDO as C_REDONDEODEPRECIOS on C_REDONDEODEPRECIOS.CODIGO = C_PROMOCION.REDONDEO and 0 = Funciones.empty( C_PROMOCION.REDONDEO )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( funciones.zpromocionvigenteenelperiodo( @parametro1,  @parametro2 ,  fecdesde,  fechasta ) = 1 ) and 
    	( ( case when @parametro3 is null then 1 	
			else ( case when @parametro3 = '0' or @Parametro3 = '' or @parametro3 = 'todos' then 1 
				else ( case when CONVERT(NUMERIC, @parametro3 ) = c_PROMOCION.TIPO  then 1 else 0 end ) end ) end ) = 1 ) and
	( ( @PROMOCION_CODIGO_DESDE is null ) OR ( c_PROMOCION.Codigo >= @PROMOCION_CODIGO_DESDE ) ) and 
	( ( @PROMOCION_CODIGO_HASTA is null ) OR ( c_PROMOCION.Codigo <= @PROMOCION_CODIGO_HASTA ) ) and 
	( ( @PROMOCION_TIPO_DESDE is null ) OR ( c_PROMOCION.Tipo >= @PROMOCION_TIPO_DESDE ) ) and 
	( ( @PROMOCION_TIPO_HASTA is null ) OR ( c_PROMOCION.Tipo <= @PROMOCION_TIPO_HASTA ) ) and 
	( ( @PROMOCION_REDONDEO_DESDE is null ) OR ( c_PROMOCION.Redondeo >= @PROMOCION_REDONDEO_DESDE ) ) and 
	( ( @PROMOCION_REDONDEO_HASTA is null ) OR ( c_PROMOCION.Redondeo <= @PROMOCION_REDONDEO_HASTA ) ) and 
	( ( @PROMOCION_DESCRIPCION_DESDE is null ) OR ( c_PROMOCION.Descrip >= @PROMOCION_DESCRIPCION_DESDE ) ) and 
	( ( @PROMOCION_DESCRIPCION_HASTA is null ) OR ( c_PROMOCION.Descrip <= @PROMOCION_DESCRIPCION_HASTA ) ) and 
	( ( @PROMOCION_FECHADESDE_DESDE is null ) OR ( c_PROMOCION.FecDesde >= @PROMOCION_FECHADESDE_DESDE ) ) and 
	( ( @PROMOCION_FECHADESDE_HASTA is null ) OR ( c_PROMOCION.FecDesde <= @PROMOCION_FECHADESDE_HASTA ) ) and 
	( ( @PROMOCION_FECHAHASTA_DESDE is null ) OR ( c_PROMOCION.FecHasta >= @PROMOCION_FECHAHASTA_DESDE ) ) and 
	( ( @PROMOCION_FECHAHASTA_HASTA is null ) OR ( c_PROMOCION.FecHasta <= @PROMOCION_FECHAHASTA_HASTA ) ) and 
	( ( @PROMOCION_HORADESDE_DESDE is null ) OR ( c_PROMOCION.HoraDesde >= @PROMOCION_HORADESDE_DESDE ) ) and 
	( ( @PROMOCION_HORADESDE_HASTA is null ) OR ( c_PROMOCION.HoraDesde <= @PROMOCION_HORADESDE_HASTA ) ) and 
	( ( @PROMOCION_HORAHASTA_DESDE is null ) OR ( c_PROMOCION.HoraHasta >= @PROMOCION_HORAHASTA_DESDE ) ) and 
	( ( @PROMOCION_HORAHASTA_HASTA is null ) OR ( c_PROMOCION.HoraHasta <= @PROMOCION_HORAHASTA_HASTA ) ) and 
	( ( @REDONDEODEPRECIOS_22_REDONDEO_DESCRIPCION_DESDE is null ) OR ( C_REDONDEODEPRECIOS.descrip >= @REDONDEODEPRECIOS_22_REDONDEO_DESCRIPCION_DESDE ) ) and 
	( ( @REDONDEODEPRECIOS_22_REDONDEO_DESCRIPCION_HASTA is null ) OR ( C_REDONDEODEPRECIOS.descrip <= @REDONDEODEPRECIOS_22_REDONDEO_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9151_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9151_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9151_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9151_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9150_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9150_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9150_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9150_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9149_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9149_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9149_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9149_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9146_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9146_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9146_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9146_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9146_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9146_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9146_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9146_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9146_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9146_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9146_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9146_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9146_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9146_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9146_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9146_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9146_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9146_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9146_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9146_CODIGO_HASTA ) ) and 
	( ( @PROMOCION_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_PROMOCION.BDALTAFW >= @PROMOCION_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @PROMOCION_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_PROMOCION.BDALTAFW <= @PROMOCION_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @PROMOCION_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_PROMOCION.BDMODIFW >= @PROMOCION_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @PROMOCION_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_PROMOCION.BDMODIFW <= @PROMOCION_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @PROMOCION_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_PROMOCION.ESTTRANS >= @PROMOCION_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @PROMOCION_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_PROMOCION.ESTTRANS <= @PROMOCION_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @PROMOCION_FECHAALTAFW_DESDE is null ) OR ( c_PROMOCION.FALTAFW >= @PROMOCION_FECHAALTAFW_DESDE ) ) and 
	( ( @PROMOCION_FECHAALTAFW_HASTA is null ) OR ( c_PROMOCION.FALTAFW <= @PROMOCION_FECHAALTAFW_HASTA ) ) and 
	( ( @PROMOCION_FECHAEXPO_DESDE is null ) OR ( c_PROMOCION.FECEXPO >= @PROMOCION_FECHAEXPO_DESDE ) ) and 
	( ( @PROMOCION_FECHAEXPO_HASTA is null ) OR ( c_PROMOCION.FECEXPO <= @PROMOCION_FECHAEXPO_HASTA ) ) and 
	( ( @PROMOCION_FECHAIMPO_DESDE is null ) OR ( c_PROMOCION.FECIMPO >= @PROMOCION_FECHAIMPO_DESDE ) ) and 
	( ( @PROMOCION_FECHAIMPO_HASTA is null ) OR ( c_PROMOCION.FECIMPO <= @PROMOCION_FECHAIMPO_HASTA ) ) and 
	( ( @PROMOCION_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_PROMOCION.FMODIFW >= @PROMOCION_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @PROMOCION_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_PROMOCION.FMODIFW <= @PROMOCION_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @PROMOCION_FECHATRANSFERENCIA_DESDE is null ) OR ( c_PROMOCION.FECTRANS >= @PROMOCION_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @PROMOCION_FECHATRANSFERENCIA_HASTA is null ) OR ( c_PROMOCION.FECTRANS <= @PROMOCION_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @PROMOCION_HORAALTAFW_DESDE is null ) OR ( c_PROMOCION.HALTAFW >= @PROMOCION_HORAALTAFW_DESDE ) ) and 
	( ( @PROMOCION_HORAALTAFW_HASTA is null ) OR ( c_PROMOCION.HALTAFW <= @PROMOCION_HORAALTAFW_HASTA ) ) and 
	( ( @PROMOCION_HORAEXPO_DESDE is null ) OR ( c_PROMOCION.HORAEXPO >= @PROMOCION_HORAEXPO_DESDE ) ) and 
	( ( @PROMOCION_HORAEXPO_HASTA is null ) OR ( c_PROMOCION.HORAEXPO <= @PROMOCION_HORAEXPO_HASTA ) ) and 
	( ( @PROMOCION_HORAIMPO_DESDE is null ) OR ( c_PROMOCION.HORAIMPO >= @PROMOCION_HORAIMPO_DESDE ) ) and 
	( ( @PROMOCION_HORAIMPO_HASTA is null ) OR ( c_PROMOCION.HORAIMPO <= @PROMOCION_HORAIMPO_HASTA ) ) and 
	( ( @PROMOCION_HORAMODIFICACIONFW_DESDE is null ) OR ( c_PROMOCION.HMODIFW >= @PROMOCION_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @PROMOCION_HORAMODIFICACIONFW_HASTA is null ) OR ( c_PROMOCION.HMODIFW <= @PROMOCION_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @PROMOCION_SERIEALTAFW_DESDE is null ) OR ( c_PROMOCION.SALTAFW >= @PROMOCION_SERIEALTAFW_DESDE ) ) and 
	( ( @PROMOCION_SERIEALTAFW_HASTA is null ) OR ( c_PROMOCION.SALTAFW <= @PROMOCION_SERIEALTAFW_HASTA ) ) and 
	( ( @PROMOCION_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_PROMOCION.SMODIFW >= @PROMOCION_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @PROMOCION_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_PROMOCION.SMODIFW <= @PROMOCION_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @PROMOCION_USUARIOALTAFW_DESDE is null ) OR ( c_PROMOCION.UALTAFW >= @PROMOCION_USUARIOALTAFW_DESDE ) ) and 
	( ( @PROMOCION_USUARIOALTAFW_HASTA is null ) OR ( c_PROMOCION.UALTAFW <= @PROMOCION_USUARIOALTAFW_HASTA ) ) and 
	( ( @PROMOCION_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_PROMOCION.UMODIFW >= @PROMOCION_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @PROMOCION_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_PROMOCION.UMODIFW <= @PROMOCION_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @PROMOCION_VERSIONALTAFW_DESDE is null ) OR ( c_PROMOCION.VALTAFW >= @PROMOCION_VERSIONALTAFW_DESDE ) ) and 
	( ( @PROMOCION_VERSIONALTAFW_HASTA is null ) OR ( c_PROMOCION.VALTAFW <= @PROMOCION_VERSIONALTAFW_HASTA ) ) and 
	( ( @PROMOCION_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_PROMOCION.VMODIFW >= @PROMOCION_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @PROMOCION_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_PROMOCION.VMODIFW <= @PROMOCION_VERSIONMODIFICACIONFW_HASTA ) )

)