IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_FACTURADECOMPRA_COMPRAS_ITEMARTICULOSCOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_FACTURADECOMPRA_COMPRAS_ITEMARTICULOSCOMPRA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_FACTURADECOMPRA_COMPRAS_ITEMARTICULOSCOMPRA]
( @BaseDeDatos varchar(8),
	@FACTURADECOMPRA_TOTALCANTIDAD_DESDE numeric(16, 3),
	@FACTURADECOMPRA_TOTALCANTIDAD_HASTA numeric(16, 3),
	@FACTURADECOMPRA_TIPOCOMPROBANTE numeric(2, 0),
	@FACTURADECOMPRA_TIPOCOMPROBANTERG1361 numeric(2, 0),
	@FACTURADECOMPRA_LETRA_DESDE varchar(2),
	@FACTURADECOMPRA_LETRA_HASTA varchar(2),
	@FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_DESDE numeric(5, 0),
	@FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_HASTA numeric(5, 0),
	@FACTURADECOMPRA_NUMERO_DESDE numeric(8, 0),
	@FACTURADECOMPRA_NUMERO_HASTA numeric(8, 0),
	@FACTURADECOMPRA_PUNTODEVENTA_DESDE numeric(4, 0),
	@FACTURADECOMPRA_PUNTODEVENTA_HASTA numeric(4, 0),
	@FACTURADECOMPRA_PROVEEDOR_DESDE varchar(10),
	@FACTURADECOMPRA_PROVEEDOR_HASTA varchar(10),
	@FACTURADECOMPRA_NUMINT_DESDE numeric(10, 0),
	@FACTURADECOMPRA_NUMINT_HASTA numeric(10, 0),
	@FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_DESDE varchar(5),
	@FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_HASTA varchar(5),
	@FACTURADECOMPRA_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURADECOMPRA_MONEDACOMPROBANTE_HASTA varchar(10),
	@FACTURADECOMPRA_LISTADEPRECIOS_DESDE varchar(6),
	@FACTURADECOMPRA_LISTADEPRECIOS_HASTA varchar(6),
	@FACTURADECOMPRA_REMITO_DESDE varchar(16),
	@FACTURADECOMPRA_REMITO_HASTA varchar(16),
	@FACTURADECOMPRA_FECHA_DESDE datetime,
	@FACTURADECOMPRA_FECHA_HASTA datetime,
	@FACTURADECOMPRA_FECHAFACTURA_DESDE datetime,
	@FACTURADECOMPRA_FECHAFACTURA_HASTA datetime,
	@FACTURADECOMPRA_COTIZACION_DESDE numeric(15, 5),
	@FACTURADECOMPRA_COTIZACION_HASTA numeric(15, 5),
	@FACTURADECOMPRA_FECHAVENCIMIENTO_DESDE datetime,
	@FACTURADECOMPRA_FECHAVENCIMIENTO_HASTA datetime,
	@FACTURADECOMPRA_CAI_DESDE numeric(14, 0),
	@FACTURADECOMPRA_CAI_HASTA numeric(14, 0),
	@FACTURADECOMPRA_FECHAVTOCAI_DESDE datetime,
	@FACTURADECOMPRA_FECHAVTOCAI_HASTA datetime,
	@FACTURADECOMPRA_CENTRODECOSTO_DESDE varchar(20),
	@FACTURADECOMPRA_CENTRODECOSTO_HASTA varchar(20),
	@FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_DESDE varchar(20),
	@FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_HASTA varchar(20),
	@FACTURADECOMPRA_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@FACTURADECOMPRA_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_DESDE numeric(15, 2),
	@FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_HASTA numeric(15, 2),
	@FACTURADECOMPRA_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@FACTURADECOMPRA_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@PROVEEDOR_29_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_29_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA varchar(100),
	@MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_DESDE varchar(150),
	@CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_HASTA varchar(150),
	@DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_DESDE varchar(150),
	@DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_HASTA varchar(150),
	@SEGMENTACION_284_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_284_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_283_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_283_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_282_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_282_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVINCIA_32_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_32_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_48_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_48_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_59_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_59_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_279_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_279_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_279_LINEA_DESDE varchar(10),
	@SUCURSAL_279_LINEA_HASTA varchar(10),
	@SUCURSAL_279_TIPO_DESDE varchar(10),
	@SUCURSAL_279_TIPO_HASTA varchar(10),
	@SUCURSAL_279_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_279_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_29_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_29_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_29_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_29_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_29_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_29_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_29_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_29_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_29_FAX_DESDE varchar(60),
	@PROVEEDOR_29_FAX_HASTA varchar(60),
	@PROVEEDOR_29_EMAIL_DESDE varchar(250),
	@PROVEEDOR_29_EMAIL_HASTA varchar(250),
	@PROVEEDOR_29_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_29_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_37_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_29_CUIT_DESDE varchar(15),
	@PROVEEDOR_29_CUIT_HASTA varchar(15),
	@PROVEEDOR_29_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_29_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_29_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_29_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_29_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_29_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_29_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_29_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_29_CALLE_DESDE varchar(70),
	@PROVEEDOR_29_CALLE_HASTA varchar(70),
	@PROVEEDOR_29_PISO_DESDE varchar(3),
	@PROVEEDOR_29_PISO_HASTA varchar(3),
	@PROVEEDOR_29_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_29_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_29_PAIS_DESDE varchar(3),
	@PROVEEDOR_29_PAIS_HASTA varchar(3),
	@PROVEEDOR_29_MOVIL_DESDE varchar(30),
	@PROVEEDOR_29_MOVIL_HASTA varchar(30),
	@PROVEEDOR_29_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_29_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_29_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_29_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_29_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_29_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_29_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_29_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_29_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_29_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_29_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_29_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_29_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_29_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_29_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_29_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_29_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_29_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_29_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_29_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_29_EMPLEADOR bit,
	@PROVEEDOR_29_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_29_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_29_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_29_SUJETOVINCULADO bit,
	@PROVEEDOR_29_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_29_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_29_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_29_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_29_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_29_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_29_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_29_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_29_TASACEROAPLICA bit,
	@PROVEEDOR_29_RUT_DESDE varchar(12),
	@PROVEEDOR_29_RUT_HASTA varchar(12),
	@PROVEEDOR_29_INACTIVOFW bit,
	@SUCURSAL_279_CODIGO_DESDE varchar(10),
	@SUCURSAL_279_CODIGO_HASTA varchar(10),
	@FACTURADECOMPRA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@FACTURADECOMPRA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@FACTURADECOMPRA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@FACTURADECOMPRA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@FACTURADECOMPRA_FECHAALTAFW_DESDE datetime,
	@FACTURADECOMPRA_FECHAALTAFW_HASTA datetime,
	@FACTURADECOMPRA_FECHAEXPO_DESDE datetime,
	@FACTURADECOMPRA_FECHAEXPO_HASTA datetime,
	@FACTURADECOMPRA_FECHAIMPO_DESDE datetime,
	@FACTURADECOMPRA_FECHAIMPO_HASTA datetime,
	@FACTURADECOMPRA_FECHAMODIFICACIONFW_DESDE datetime,
	@FACTURADECOMPRA_FECHAMODIFICACIONFW_HASTA datetime,
	@FACTURADECOMPRA_FECHATRANSFERENCIA_DESDE datetime,
	@FACTURADECOMPRA_FECHATRANSFERENCIA_HASTA datetime,
	@FACTURADECOMPRA_HORAALTAFW_DESDE varchar(8),
	@FACTURADECOMPRA_HORAALTAFW_HASTA varchar(8),
	@FACTURADECOMPRA_HORAEXPO_DESDE varchar(8),
	@FACTURADECOMPRA_HORAEXPO_HASTA varchar(8),
	@FACTURADECOMPRA_HORAIMPO_DESDE varchar(8),
	@FACTURADECOMPRA_HORAIMPO_HASTA varchar(8),
	@FACTURADECOMPRA_HORAMODIFICACIONFW_DESDE varchar(8),
	@FACTURADECOMPRA_HORAMODIFICACIONFW_HASTA varchar(8),
	@FACTURADECOMPRA_SERIEALTAFW_DESDE varchar(7),
	@FACTURADECOMPRA_SERIEALTAFW_HASTA varchar(7),
	@FACTURADECOMPRA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@FACTURADECOMPRA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@FACTURADECOMPRA_USUARIOALTAFW_DESDE varchar(100),
	@FACTURADECOMPRA_USUARIOALTAFW_HASTA varchar(100),
	@FACTURADECOMPRA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@FACTURADECOMPRA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@FACTURADECOMPRA_VERSIONALTAFW_DESDE varchar(13),
	@FACTURADECOMPRA_VERSIONALTAFW_HASTA varchar(13),
	@FACTURADECOMPRA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@FACTURADECOMPRA_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticuloscompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSCOMPRA__BD,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticuloscompra.fart, c_itemarticuloscompra.fcolo, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSCOMPRA_1_OrdenPaletaColores,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticuloscompra.fart, c_itemarticuloscompra.ftall, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSCOMPRA_1_OrdenCurvaTalles,
	c_ITEMARTICULOSCOMPRA.FART as ITEMARTICULOSCOMPRA_FART,
	c_ITEMARTICULOSCOMPRA.FTXT as ITEMARTICULOSCOMPRA_FTXT,
	cast( c_facturadecompra_cabecera.signomov*-1*c_itemarticuloscompra.fcant as numeric( 9, 3 ) ) as ITEMARTICULOSCOMPRA_FCANT,
	c_ITEMARTICULOSCOMPRA.CODIGO as ITEMARTICULOSCOMPRA_CODIGO,
	c_ITEMARTICULOSCOMPRA.FCOLO as ITEMARTICULOSCOMPRA_FCOLO,
	c_ITEMARTICULOSCOMPRA.FCOTXT as ITEMARTICULOSCOMPRA_FCOTXT,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.fcfi as numeric( 7, 2 ) ) as ITEMARTICULOSCOMPRA_FCFI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.fcfitot as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_FCFITot,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.fmonto as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_FMONTO,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.fneto as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_FNETO,
	c_ITEMARTICULOSCOMPRA.FPRECIO as ITEMARTICULOSCOMPRA_FPRECIO,
	c_ITEMARTICULOSCOMPRA.FTALL as ITEMARTICULOSCOMPRA_FTALL,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.mntdes as numeric( 12, 2 ) ) as ITEMARTICULOSCOMPRA_MNTDES,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.mntprecci as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPRECCI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.mntptot as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPTOT,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.mntpper as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPPER,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.mntpdesci as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPDESCI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.mntprecsi as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPRECSI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.mntpdessi as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPDESSI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.mntpiva as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPIVA,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.mnpdsi as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_MNPDSI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.mndesci as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_MNDESCI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*c_itemarticuloscompra.mndessi as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_MNDESSI,
	cast( c_facturadecompra_cabecera.signomov*c_facturadecompra_cabecera.cotiz*-1*c_itemarticuloscompra.fbruto as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_FBruto,
	case when funciones.empty( c_ITEMARTICULOSCOMPRA.CCOSTO ) = 1 then C_FACTURADECOMPRA_CABECERA.CCOSTO else c_ITEMARTICULOSCOMPRA.CCOSTO end as ITEMARTICULOSCOMPRA_CCOSTO,
	c_ITEMARTICULOSCOMPRA.NROITEM as ITEMARTICULOSCOMPRA_NroItem,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	case when funciones.empty( c_ITEMARTICULOSCOMPRA.CCOSTO ) = 1 then C_CENTRODECOSTO_CABECERA.COSDES else C_CENTRODECOSTO.COSDES end as CENTRODECOSTO_COSDES,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	case when funciones.empty( c_ITEMARTICULOSCOMPRA.CCOSTO ) = 1 then C_CENTRODECOSTO_CABECERA.COSCOD else C_CENTRODECOSTO.COSCOD end as CENTRODECOSTO_COSCOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_TALLE.CODIGO as TALLE_Codigo
 from (Select fart,ftxt,fcant,codigo,fcolo,fcotxt,fcfi,fcfitot,fkit,famate,fmonto,fmtocfi,fmtodto1,fmtoiva,fneto,nroitem,fx2,fporcfi,fpordto1,fporiva,prunconimp,fprecio,prunsinimp,fprun,ftall,fn11,funid,ciditem,iditemorig,afenroitem,afetipocom,afeletra,afeptoven,afenumcom,afecant,afesaldo,acondivac,aporcivac,procstock,afets,equiv,mntdes,mntprecci,mntptot,mntpper,mntpdesci,mntprecsi,mntpdessi,mntpiva,seniacance,mnpdsi,mndesci,mndessi,afe_cod,usarplista,fbruto,ajucimp,ajusimp,dccosto,ccosto,iditem,comp from ZooLogic.FACCOMPRADET union all Select fart,ftxt,fcant,codigo,fcolo,fcotxt,fcfi,fcfitot,fkit,famate,fmonto,fmtocfi,fmtodto1,fmtoiva,fneto,nroitem,fx2,fporcfi,fpordto1,fporiva,prunconimp,fprecio,prunsinimp,fprun,ftall,fn11,funid,ciditem,iditemorig,afenroitem,afetipocom,afeletra,afeptoven,afenumcom,afecant,afesaldo,acondivac,aporcivac,procstock,afets,equiv,mntdes,mntprecci,mntptot,mntpper,mntpdesci,mntprecsi,mntpdessi,mntpiva,seniacance,mnpdsi,mndesci,mndessi,afe_cod,usarplista,fbruto,ajucimp,ajusimp,dccosto,ccosto,iditem,comp from ZooLogic.NCCOMPRADET union all Select fart,ftxt,fcant,codigo,fcolo,fcotxt,fcfi,fcfitot,fkit,famate,fmonto,fmtocfi,fmtodto1,fmtoiva,fneto,nroitem,fx2,fporcfi,fpordto1,fporiva,prunconimp,fprecio,prunsinimp,fprun,ftall,fn11,funid,ciditem,iditemorig,afenroitem,afetipocom,afeletra,afeptoven,afenumcom,afecant,afesaldo,acondivac,aporcivac,procstock,afets,equiv,mntdes,mntprecci,mntptot,mntpper,mntpdesci,mntprecsi,mntpdessi,mntpiva,seniacance,mnpdsi,mndesci,mndessi,afe_cod,usarplista,fbruto,ajucimp,ajusimp,dccosto,ccosto,iditem,comp from ZooLogic.NDCOMPRADET)  as c_ITEMARTICULOSCOMPRA
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSCOMPRA.FART and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.FART )
 left join ZooLogic.CCOSTO as C_CENTRODECOSTO on C_CENTRODECOSTO.COSCOD = C_ITEMARTICULOSCOMPRA.CCOSTO and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.CCOSTO )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSCOMPRA.FCOLO and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.FCOLO )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSCOMPRA.FTALL and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.FTALL )
 inner join (Select fperson,numint,fcompfis,ffch,fd2,fhora,fimpuesto,fletra,codlista,moneda,fdescu,fnumcomp,fobs,fpodes,fptoven,simbmon,sitfiscpro,fsubtot,fsubton,facttipo,ftotal,fturno,fvuelto,signomov,anulado,condivalp,fcuit,idvuelto,desauto,subtotcisi,subtotsisi,fmtdes1,fpodes1,fmtdes2,fpodes2,fmtdes3,recpor,recmnto,recmnto1,recmnto2,recmntosi,recmntosi1,recmntosi2,desmntosi,desmntosi1,desmntosi2,desmntosi3,totimpue,totrecar,totdesc,totrecarsi,totdescsi,idcaja,codigo,ffchfac,ffchvenc,nroremito,condpago,fvtocai,ncai,tcrg1361,cotiz,monsis,recmonto1,recmonto2,mr,totalcant,impman,disccos,ccosto,fptovenext,bdaltafw,bdmodifw,esttrans,faltafw,fecexpo,fecimpo,fmodifw,fectrans,haltafw,horaexpo,horaimpo,hmodifw,saltafw,smodifw,ualtafw,umodifw,valtafw,vmodifw,zadsfw from ZooLogic.FACCOMPRA union all Select fperson,numint,fcompfis,ffch,fd2,fhora,fimpuesto,fletra,codlista,moneda,fdescu,fnumcomp,fobs,fpodes,fptoven,simbmon,sitfiscpro,fsubtot,fsubton,facttipo,ftotal,fturno,fvuelto,signomov,anulado,condivalp,fcuit,idvuelto,desauto,subtotcisi,subtotsisi,fmtdes1,fpodes1,fmtdes2,fpodes2,fmtdes3,recpor,recmnto,recmnto1,recmnto2,recmntosi,recmntosi1,recmntosi2,desmntosi,desmntosi1,desmntosi2,desmntosi3,totimpue,totrecar,totdesc,totrecarsi,totdescsi,idcaja,codigo,ffchfac,ffchvenc,nroremito,condpago,fvtocai,ncai,tcrg1361,cotiz,monsis,recmonto1,recmonto2,mr,totalcant,impman,disccos,ccosto,fptovenext,bdaltafw,bdmodifw,esttrans,faltafw,fecexpo,fecimpo,fmodifw,fectrans,haltafw,horaexpo,horaimpo,hmodifw,saltafw,smodifw,ualtafw,umodifw,valtafw,vmodifw,zadsfw from ZooLogic.NCCOMPRA union all Select fperson,numint,fcompfis,ffch,fd2,fhora,fimpuesto,fletra,codlista,moneda,fdescu,fnumcomp,fobs,fpodes,fptoven,simbmon,sitfiscpro,fsubtot,fsubton,facttipo,ftotal,fturno,fvuelto,signomov,anulado,condivalp,fcuit,idvuelto,desauto,subtotcisi,subtotsisi,fmtdes1,fpodes1,fmtdes2,fpodes2,fmtdes3,recpor,recmnto,recmnto1,recmnto2,recmntosi,recmntosi1,recmntosi2,desmntosi,desmntosi1,desmntosi2,desmntosi3,totimpue,totrecar,totdesc,totrecarsi,totdescsi,idcaja,codigo,ffchfac,ffchvenc,nroremito,condpago,fvtocai,ncai,tcrg1361,cotiz,monsis,recmonto1,recmonto2,mr,totalcant,impman,disccos,ccosto,fptovenext,bdaltafw,bdmodifw,esttrans,faltafw,fecexpo,fecimpo,fmodifw,fectrans,haltafw,horaexpo,horaimpo,hmodifw,saltafw,smodifw,ualtafw,umodifw,valtafw,vmodifw,zadsfw from ZooLogic.NDCOMPRA)  as C_FACTURADECOMPRA_CABECERA on C_FACTURADECOMPRA_CABECERA.CODIGO = C_ITEMARTICULOSCOMPRA.CODIGO
 left join ZooLogic.CCOSTO as C_CENTRODECOSTO_CABECERA on C_CENTRODECOSTO_CABECERA.COSCOD = C_FACTURADECOMPRA_CABECERA.CCOSTO and 0 = Funciones.empty( C_FACTURADECOMPRA_CABECERA.CCOSTO )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO74_CABECERA on C_CONDICIONDEPAGO74_CABECERA.CLCOD = C_FACTURADECOMPRA_CABECERA.CONDPAGO and 0 = Funciones.empty( C_FACTURADECOMPRA_CABECERA.CONDPAGO )
 left join ZooLogic.DCCOSTO as C_DISTRIBUCIONCENTRODECOSTO_CABECERA on C_DISTRIBUCIONCENTRODECOSTO_CABECERA.CODIGO = C_FACTURADECOMPRA_CABECERA.DISCCOS and 0 = Funciones.empty( C_FACTURADECOMPRA_CABECERA.DISCCOS )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS76_CABECERA on C_LISTADEPRECIOS76_CABECERA.LPR_NUMERO = C_FACTURADECOMPRA_CABECERA.CODLISTA and 0 = Funciones.empty( C_FACTURADECOMPRA_CABECERA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA_CABECERA on C_MONEDA_CABECERA.CODIGO = C_FACTURADECOMPRA_CABECERA.MONEDA and 0 = Funciones.empty( C_FACTURADECOMPRA_CABECERA.MONEDA )
 left join ZooLogic.PROV as C_PROVEEDOR_CABECERA on C_PROVEEDOR_CABECERA.CLCOD = C_FACTURADECOMPRA_CABECERA.FPERSON and 0 = Funciones.empty( C_FACTURADECOMPRA_CABECERA.FPERSON )
 left join ZooLogic.PROVINCI as C_PROVINCIA_CABECERA on C_PROVINCIA_CABECERA.PRV_COD = C_PROVEEDOR_CABECERA.CLPRV and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL_CABECERA on C_SITUACIONFISCAL_CABECERA.CODIGO = C_PROVEEDOR_CABECERA.CLIVA and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL_CABECERA on C_SUCURSAL_CABECERA.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL_CABECERA on C_TIPOSUCURSAL_CABECERA.TCOD = C_SUCURSAL_CABECERA.TIPO and 0 = Funciones.empty( C_SUCURSAL_CABECERA.TIPO )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR_CABECERA on C_CLASIFICACIONPROVEEDOR_CABECERA.CLACOD = C_PROVEEDOR_CABECERA.CLAS and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO52_CABECERA on C_CONDICIONDEPAGO52_CABECERA.CLCOD = C_PROVEEDOR_CABECERA.CLCONDPAG and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB_CABECERA on C_DATOSADICIONALESSIPRIB_CABECERA.CODIGO = C_PROVEEDOR_CABECERA.CLSIPRIB and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLSIPRIB )
 left join ZooLogic.IMPUESTO as C_IMPUESTO57_CABECERA on C_IMPUESTO57_CABECERA.CODIGO = C_PROVEEDOR_CABECERA.CLRETGAN and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO58_CABECERA on C_IMPUESTO58_CABECERA.CODIGO = C_PROVEEDOR_CABECERA.CLRETSUSS and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO59_CABECERA on C_IMPUESTO59_CABECERA.CODIGO = C_PROVEEDOR_CABECERA.CLRETIVA and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLRETIVA )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL_CABECERA on C_LINEASUCURSAL_CABECERA.LSCOD = C_SUCURSAL_CABECERA.LINEA and 0 = Funciones.empty( C_SUCURSAL_CABECERA.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS55_CABECERA on C_LISTADEPRECIOS55_CABECERA.LPR_NUMERO = C_PROVEEDOR_CABECERA.CLLISTPRE and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.CLLISTPRE )
 left join ZooLogic.PAISES as C_PAISES_CABECERA on C_PAISES_CABECERA.PCOD = C_PROVEEDOR_CABECERA.PPAIS and 0 = Funciones.empty( C_PROVEEDOR_CABECERA.PPAIS )
 left join ORGANIZACION.SECOD as C_SEGMENTACION_CABECERA on C_SEGMENTACION_CABECERA.SCOD = C_SUCURSAL_CABECERA.SEG and 0 = Funciones.empty( C_SUCURSAL_CABECERA.SEG )
 where ( 1=1 ) and 
	( ( @FACTURADECOMPRA_TOTALCANTIDAD_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.TotalCant >= @FACTURADECOMPRA_TOTALCANTIDAD_DESDE ) ) and 
	( ( @FACTURADECOMPRA_TOTALCANTIDAD_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.TotalCant <= @FACTURADECOMPRA_TOTALCANTIDAD_HASTA ) ) and 
	( C_FACTURADECOMPRA_CABECERA.FACTTIPO in ( 8, 9, 10 ) ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FACTTIPO = @FACTURADECOMPRA_TIPOCOMPROBANTE ) ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTERG1361 is null ) OR ( C_FACTURADECOMPRA_CABECERA.tcrg1361 = @FACTURADECOMPRA_TIPOCOMPROBANTERG1361 ) ) and 
	( ( @FACTURADECOMPRA_LETRA_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FLETRA >= @FACTURADECOMPRA_LETRA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_LETRA_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FLETRA <= @FACTURADECOMPRA_LETRA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPTOVENEXT >= @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPTOVENEXT <= @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_NUMERO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FNUMCOMP >= @FACTURADECOMPRA_NUMERO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_NUMERO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FNUMCOMP <= @FACTURADECOMPRA_NUMERO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTA_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPTOVEN >= @FACTURADECOMPRA_PUNTODEVENTA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTA_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPTOVEN <= @FACTURADECOMPRA_PUNTODEVENTA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PROVEEDOR_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPerson >= @FACTURADECOMPRA_PROVEEDOR_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PROVEEDOR_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPerson <= @FACTURADECOMPRA_PROVEEDOR_HASTA ) ) and 
	( ( @FACTURADECOMPRA_NUMINT_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.NumInt >= @FACTURADECOMPRA_NUMINT_DESDE ) ) and 
	( ( @FACTURADECOMPRA_NUMINT_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.NumInt <= @FACTURADECOMPRA_NUMINT_HASTA ) ) and 
	( ( @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.CONDPAGO >= @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.CONDPAGO <= @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_HASTA ) ) and 
	( ( @FACTURADECOMPRA_MONEDACOMPROBANTE_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.Moneda >= @FACTURADECOMPRA_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_MONEDACOMPROBANTE_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.Moneda <= @FACTURADECOMPRA_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @FACTURADECOMPRA_LISTADEPRECIOS_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.CodLista >= @FACTURADECOMPRA_LISTADEPRECIOS_DESDE ) ) and 
	( ( @FACTURADECOMPRA_LISTADEPRECIOS_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.CodLista <= @FACTURADECOMPRA_LISTADEPRECIOS_HASTA ) ) and 
	( ( @FACTURADECOMPRA_REMITO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.NROREMITO >= @FACTURADECOMPRA_REMITO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_REMITO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.NROREMITO <= @FACTURADECOMPRA_REMITO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHA_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FFCH >= @FACTURADECOMPRA_FECHA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHA_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FFCH <= @FACTURADECOMPRA_FECHA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAFACTURA_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FFCHFAC >= @FACTURADECOMPRA_FECHAFACTURA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAFACTURA_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FFCHFAC <= @FACTURADECOMPRA_FECHAFACTURA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_COTIZACION_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.Cotiz >= @FACTURADECOMPRA_COTIZACION_DESDE ) ) and 
	( ( @FACTURADECOMPRA_COTIZACION_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.Cotiz <= @FACTURADECOMPRA_COTIZACION_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAVENCIMIENTO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FFCHVENC >= @FACTURADECOMPRA_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAVENCIMIENTO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FFCHVENC <= @FACTURADECOMPRA_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_CAI_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.NCAI >= @FACTURADECOMPRA_CAI_DESDE ) ) and 
	( ( @FACTURADECOMPRA_CAI_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.NCAI <= @FACTURADECOMPRA_CAI_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAVTOCAI_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FVTOCAI >= @FACTURADECOMPRA_FECHAVTOCAI_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAVTOCAI_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FVTOCAI <= @FACTURADECOMPRA_FECHAVTOCAI_HASTA ) ) and 
	( ( @FACTURADECOMPRA_CENTRODECOSTO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.CCosto >= @FACTURADECOMPRA_CENTRODECOSTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_CENTRODECOSTO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.CCosto <= @FACTURADECOMPRA_CENTRODECOSTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.DisCCos >= @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.DisCCos <= @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPODES >= @FACTURADECOMPRA_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FPODES <= @FACTURADECOMPRA_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FMTDES3 >= @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_DESDE ) ) and 
	( ( @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FMTDES3 <= @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_HASTA ) ) and 
	( ( @FACTURADECOMPRA_RECARGOPORCENTAJE_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.RecPor >= @FACTURADECOMPRA_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_RECARGOPORCENTAJE_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.RecPor <= @FACTURADECOMPRA_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @PROVEEDOR_29_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLNOM >= @PROVEEDOR_29_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_29_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLNOM <= @PROVEEDOR_29_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO74_CABECERA.CLNOM >= @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO74_CABECERA.CLNOM <= @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA_CABECERA.Descrip >= @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA_CABECERA.Descrip <= @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS76_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS76_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_DESDE is null ) OR ( C_CENTRODECOSTO.COSDES >= @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_DESDE ) ) and 
	( ( @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_HASTA is null ) OR ( C_CENTRODECOSTO.COSDES <= @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_HASTA ) ) and 
	( ( @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_DESDE is null ) OR ( C_DISTRIBUCIONCENTRODECOSTO_CABECERA.Descrip >= @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_DESDE ) ) and 
	( ( @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_HASTA is null ) OR ( C_DISTRIBUCIONCENTRODECOSTO_CABECERA.Descrip <= @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_HASTA ) ) and 
	( ( @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION_CABECERA.SDES >= @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION_CABECERA.SDES <= @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_283_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES >= @LINEASUCURSAL_283_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_283_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES <= @LINEASUCURSAL_283_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_282_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES >= @TIPOSUCURSAL_282_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_282_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES <= @TIPOSUCURSAL_282_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_32_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA_CABECERA.PRV_DES >= @PROVINCIA_32_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_32_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA_CABECERA.PRV_DES <= @PROVINCIA_32_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_48_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES_CABECERA.pdes >= @PAISES_48_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_48_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES_CABECERA.pdes <= @PAISES_48_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR_CABECERA.CLADES >= @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR_CABECERA.CLADES <= @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO52_CABECERA.CLNOM >= @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO52_CABECERA.CLNOM <= @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS55_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS55_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO57_CABECERA.descrip >= @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO57_CABECERA.descrip <= @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO58_CABECERA.descrip >= @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO58_CABECERA.descrip <= @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO59_CABECERA.descrip >= @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO59_CABECERA.descrip <= @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip >= @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip <= @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_279_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.seg >= @SUCURSAL_279_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_279_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.seg <= @SUCURSAL_279_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_279_LINEA_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Linea >= @SUCURSAL_279_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_279_LINEA_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Linea <= @SUCURSAL_279_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_279_TIPO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Tipo >= @SUCURSAL_279_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_279_TIPO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Tipo <= @SUCURSAL_279_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_279_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.descrip >= @SUCURSAL_279_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_279_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.descrip <= @SUCURSAL_279_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_29_LOCALIDAD_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLLOC >= @PROVEEDOR_29_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_29_LOCALIDAD_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLLOC <= @PROVEEDOR_29_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_29_CODIGOPOSTAL_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLCP >= @PROVEEDOR_29_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_29_CODIGOPOSTAL_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLCP <= @PROVEEDOR_29_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_29_PROVINCIA_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLPRV >= @PROVEEDOR_29_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_29_PROVINCIA_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLPRV <= @PROVEEDOR_29_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_29_TELEFONO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLTLF >= @PROVEEDOR_29_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_29_TELEFONO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLTLF <= @PROVEEDOR_29_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_29_FAX_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLFAX >= @PROVEEDOR_29_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_29_FAX_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLFAX <= @PROVEEDOR_29_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_29_EMAIL_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLEMAIL >= @PROVEEDOR_29_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_29_EMAIL_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLEMAIL <= @PROVEEDOR_29_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_29_PAGINAWEB_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLPAGEWEB >= @PROVEEDOR_29_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_29_PAGINAWEB_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLPAGEWEB <= @PROVEEDOR_29_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_37_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL_CABECERA.Descrip = @SITUACIONFISCAL_37_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_29_CUIT_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLCUIT >= @PROVEEDOR_29_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_29_CUIT_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLCUIT <= @PROVEEDOR_29_CUIT_HASTA ) ) and 
	( ( @PROVEEDOR_29_TIPODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLTIPODOC >= @PROVEEDOR_29_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_TIPODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLTIPODOC <= @PROVEEDOR_29_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_NRODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLNRODOC >= @PROVEEDOR_29_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_NRODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLNRODOC <= @PROVEEDOR_29_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_IMAGEN_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CIMAGEN >= @PROVEEDOR_29_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_29_IMAGEN_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CIMAGEN <= @PROVEEDOR_29_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_29_NUMERO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PNUMERO >= @PROVEEDOR_29_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_29_NUMERO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PNUMERO <= @PROVEEDOR_29_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_29_CALLE_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PCALLE >= @PROVEEDOR_29_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_29_CALLE_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PCALLE <= @PROVEEDOR_29_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_29_PISO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PPISO >= @PROVEEDOR_29_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_29_PISO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PPISO <= @PROVEEDOR_29_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_29_DEPARTAMENTO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PDEPTO >= @PROVEEDOR_29_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_DEPARTAMENTO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PDEPTO <= @PROVEEDOR_29_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_PAIS_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PPAIS >= @PROVEEDOR_29_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_29_PAIS_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PPAIS <= @PROVEEDOR_29_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_29_MOVIL_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.TLFM >= @PROVEEDOR_29_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_29_MOVIL_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.TLFM <= @PROVEEDOR_29_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_29_CLASIFICACION_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLAS >= @PROVEEDOR_29_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_29_CLASIFICACION_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLAS <= @PROVEEDOR_29_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_29_FECHANACIMIENTO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLFECHA >= @PROVEEDOR_29_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_FECHANACIMIENTO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLFECHA <= @PROVEEDOR_29_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_CONDICIONDEPAGO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLCONDPAG >= @PROVEEDOR_29_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_29_CONDICIONDEPAGO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLCONDPAG <= @PROVEEDOR_29_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_29_TIPOCONVENIO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLTIPCONV >= @PROVEEDOR_29_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_29_TIPOCONVENIO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLTIPCONV <= @PROVEEDOR_29_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_29_NROIIBB_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLNROIIBB >= @PROVEEDOR_29_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_29_NROIIBB_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLNROIIBB <= @PROVEEDOR_29_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_29_LISTADEPRECIO_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLLISTPRE >= @PROVEEDOR_29_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_29_LISTADEPRECIO_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLLISTPRE <= @PROVEEDOR_29_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_29_SITUACIONGANANCIAS is null ) OR ( C_PROVEEDOR_CABECERA.CLSITGAN = @PROVEEDOR_29_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_29_RETENCIONGANANCIAS_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLRETGAN >= @PROVEEDOR_29_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_29_RETENCIONGANANCIAS_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLRETGAN <= @PROVEEDOR_29_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_29_RETENCIONSUSS_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLRETSUSS >= @PROVEEDOR_29_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_29_RETENCIONSUSS_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLRETSUSS <= @PROVEEDOR_29_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_29_RETENCIONIVA_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLRETIVA >= @PROVEEDOR_29_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_29_RETENCIONIVA_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLRETIVA <= @PROVEEDOR_29_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_29_OBJETOIVA is null ) OR ( C_PROVEEDOR_CABECERA.CLOBJIVA = @PROVEEDOR_29_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_29_EMPLEADOR is null ) OR ( C_PROVEEDOR_CABECERA.CLEMPLEAD = @PROVEEDOR_29_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_29_EXCLUIDORETENCIONGANANCIAS is null ) OR ( C_PROVEEDOR_CABECERA.EXRETGAN = @PROVEEDOR_29_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_29_EXCLUIDORETENCIONIVA is null ) OR ( C_PROVEEDOR_CABECERA.EXRETIVA = @PROVEEDOR_29_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_29_EXCLUIDORETENCIONSUSS is null ) OR ( C_PROVEEDOR_CABECERA.EXRETSUSS = @PROVEEDOR_29_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_29_SUJETOVINCULADO is null ) OR ( C_PROVEEDOR_CABECERA.CLSujVinc = @PROVEEDOR_29_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PVHastaIva >= @PROVEEDOR_29_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PVHastaIva <= @PROVEEDOR_29_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PVHastaGan >= @PROVEEDOR_29_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PVHastaGan <= @PROVEEDOR_29_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_29_CODIGOSIPRIB_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.CLSIPRIB >= @PROVEEDOR_29_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_29_CODIGOSIPRIB_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.CLSIPRIB <= @PROVEEDOR_29_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_29_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.PorcenTC >= @PROVEEDOR_29_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_29_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.PorcenTC <= @PROVEEDOR_29_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_29_TASACEROAPLICA is null ) OR ( C_PROVEEDOR_CABECERA.AplicaTC = @PROVEEDOR_29_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_29_RUT_DESDE is null ) OR ( C_PROVEEDOR_CABECERA.RUT >= @PROVEEDOR_29_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_29_RUT_HASTA is null ) OR ( C_PROVEEDOR_CABECERA.RUT <= @PROVEEDOR_29_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_29_INACTIVOFW is null ) OR ( C_PROVEEDOR_CABECERA.InactivoFW = @PROVEEDOR_29_INACTIVOFW ) ) and 
	( ( @SUCURSAL_279_CODIGO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.codigo >= @SUCURSAL_279_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_279_CODIGO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.codigo <= @SUCURSAL_279_CODIGO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.BDALTAFW >= @FACTURADECOMPRA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.BDALTAFW <= @FACTURADECOMPRA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.BDMODIFW >= @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.BDMODIFW <= @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.ESTTRANS >= @FACTURADECOMPRA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.ESTTRANS <= @FACTURADECOMPRA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FALTAFW >= @FACTURADECOMPRA_FECHAALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FALTAFW <= @FACTURADECOMPRA_FECHAALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAEXPO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FECEXPO >= @FACTURADECOMPRA_FECHAEXPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAEXPO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FECEXPO <= @FACTURADECOMPRA_FECHAEXPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAIMPO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FECIMPO >= @FACTURADECOMPRA_FECHAIMPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAIMPO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FECIMPO <= @FACTURADECOMPRA_FECHAIMPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FMODIFW >= @FACTURADECOMPRA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FMODIFW <= @FACTURADECOMPRA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHATRANSFERENCIA_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.FECTRANS >= @FACTURADECOMPRA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHATRANSFERENCIA_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.FECTRANS <= @FACTURADECOMPRA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.HALTAFW >= @FACTURADECOMPRA_HORAALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.HALTAFW <= @FACTURADECOMPRA_HORAALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAEXPO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.HORAEXPO >= @FACTURADECOMPRA_HORAEXPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAEXPO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.HORAEXPO <= @FACTURADECOMPRA_HORAEXPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAIMPO_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.HORAIMPO >= @FACTURADECOMPRA_HORAIMPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAIMPO_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.HORAIMPO <= @FACTURADECOMPRA_HORAIMPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.HMODIFW >= @FACTURADECOMPRA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.HMODIFW <= @FACTURADECOMPRA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_SERIEALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.SALTAFW >= @FACTURADECOMPRA_SERIEALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_SERIEALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.SALTAFW <= @FACTURADECOMPRA_SERIEALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.SMODIFW >= @FACTURADECOMPRA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.SMODIFW <= @FACTURADECOMPRA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_USUARIOALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.UALTAFW >= @FACTURADECOMPRA_USUARIOALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_USUARIOALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.UALTAFW <= @FACTURADECOMPRA_USUARIOALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.UMODIFW >= @FACTURADECOMPRA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.UMODIFW <= @FACTURADECOMPRA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_VERSIONALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.VALTAFW >= @FACTURADECOMPRA_VERSIONALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_VERSIONALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.VALTAFW <= @FACTURADECOMPRA_VERSIONALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA_CABECERA.VMODIFW >= @FACTURADECOMPRA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA_CABECERA.VMODIFW <= @FACTURADECOMPRA_VERSIONMODIFICACIONFW_HASTA ) )

)