IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_CTACTE_VENCIMIENTO_SEGMENTADO_CTACTE]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_CTACTE_VENCIMIENTO_SEGMENTADO_CTACTE];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_CTACTE_VENCIMIENTO_SEGMENTADO_CTACTE]
( @BaseDeDatos varchar(8),
	@CTACTE_CLIENTE_DESDE varchar(10),
	@CTACTE_CLIENTE_HASTA varchar(10),
	@CLIENTE_2980_BASEDEDATOSALTAFW_DESDE varchar(8),
	@CLIENTE_2980_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURA_3050_VENDEDOR_DESDE varchar(10),
	@FACTURA_3050_VENDEDOR_HASTA varchar(10),
	@VENDEDOR_3060_NOMBRE_DESDE varchar(60),
	@VENDEDOR_3060_NOMBRE_HASTA varchar(60),
	@FACTURA_3050_OBS_DESDE varchar(250),
	@FACTURA_3050_OBS_HASTA varchar(250),
	@CTACTE_CODIGO_DESDE varchar(48),
	@CTACTE_CODIGO_HASTA varchar(48),
	@CTACTE_MONEDA_DESDE varchar(10),
	@CTACTE_MONEDA_HASTA varchar(10),
	@CTACTE_LETRA_DESDE varchar(1),
	@CTACTE_LETRA_HASTA varchar(1),
	@CTACTE_PUNTODEVENTA_DESDE numeric(4, 0),
	@CTACTE_PUNTODEVENTA_HASTA numeric(4, 0),
	@CTACTE_NUMERO_DESDE numeric(8, 0),
	@CTACTE_NUMERO_HASTA numeric(8, 0),
	@CTACTE_SECUENCIA_DESDE varchar(2),
	@CTACTE_SECUENCIA_HASTA varchar(2),
	@CTACTE_FECHAVENCIMIENTO_DESDE datetime,
	@CTACTE_FECHAVENCIMIENTO_HASTA datetime,
	@CTACTE_TIPODECOMPROBANTE_DESDE numeric(2, 0),
	@CTACTE_TIPODECOMPROBANTE_HASTA numeric(2, 0),
	@CTACTE_FECHA_DESDE datetime,
	@CTACTE_FECHA_HASTA datetime,
	@CTACTE_VALOR_DESDE varchar(5),
	@CTACTE_VALOR_HASTA varchar(5),
	@CTACTE_SIGNODEMOVIMIENTO_DESDE numeric(2, 0),
	@CTACTE_SIGNODEMOVIMIENTO_HASTA numeric(2, 0),
	@MONEDA_2_MONEDA_DESCRIPCION_DESDE varchar(40),
	@MONEDA_2_MONEDA_DESCRIPCION_HASTA varchar(40),
	@VALOR_83_VALOR_DESCRIPCION_DESDE varchar(40),
	@VALOR_83_VALOR_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_3489_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_3489_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_3488_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_3488_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_3487_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_3487_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_21_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_21_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_36_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_36_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_38_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_38_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_44_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_44_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_45_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_45_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_48_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_48_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_49_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_49_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_55_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_55_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_56_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_56_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_57_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_57_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_58_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_58_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_60_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_60_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_63_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_63_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_72_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_72_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@CLIENTE_2980_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_2980_CLIENTE_NOMBRE_HASTA varchar(185),
	@SUCURSAL_3484_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_3484_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_3484_LINEA_DESDE varchar(10),
	@SUCURSAL_3484_LINEA_HASTA varchar(10),
	@SUCURSAL_3484_TIPO_DESDE varchar(10),
	@SUCURSAL_3484_TIPO_HASTA varchar(10),
	@SUCURSAL_3484_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_3484_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_2980_VENDEDOR_DESDE varchar(10),
	@CLIENTE_2980_VENDEDOR_HASTA varchar(10),
	@CLIENTE_2980_CALLE_DESDE varchar(250),
	@CLIENTE_2980_CALLE_HASTA varchar(250),
	@CLIENTE_2980_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_2980_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_2980_CUIT_DESDE varchar(15),
	@CLIENTE_2980_CUIT_HASTA varchar(15),
	@CLIENTE_2980_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_2980_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_2980_EMAIL_DESDE varchar(250),
	@CLIENTE_2980_EMAIL_HASTA varchar(250),
	@CLIENTE_2980_FAX_DESDE varchar(20),
	@CLIENTE_2980_FAX_HASTA varchar(20),
	@CLIENTE_2980_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_2980_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_2980_IMAGEN_DESDE varchar(180),
	@CLIENTE_2980_IMAGEN_HASTA varchar(180),
	@CLIENTE_2980_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_2980_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_2980_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_2980_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_2980_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_2980_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_2980_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_2980_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_2980_PAIS_DESDE varchar(3),
	@CLIENTE_2980_PAIS_HASTA varchar(3),
	@CLIENTE_2980_PISO_DESDE varchar(3),
	@CLIENTE_2980_PISO_HASTA varchar(3),
	@CLIENTE_2980_PROVINCIA_DESDE varchar(2),
	@CLIENTE_2980_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_39_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_2980_TELEFONO_DESDE varchar(30),
	@CLIENTE_2980_TELEFONO_HASTA varchar(30),
	@CLIENTE_2980_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_2980_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_2980_MOVIL_DESDE varchar(30),
	@CLIENTE_2980_MOVIL_HASTA varchar(30),
	@CLIENTE_2980_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_2980_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_2980_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_2980_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_2980_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_2980_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_2980_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_2980_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_2980_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_2980_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_2980_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_2980_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_2980_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_2980_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_2980_ESTADOCIVIL varchar(13),
	@CLIENTE_2980_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_2980_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_2980_SEXO varchar(10),
	@CLIENTE_2980_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_2980_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_2980_RUT_DESDE varchar(12),
	@CLIENTE_2980_RUT_HASTA varchar(12),
	@CLIENTE_2980_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_2980_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_2980_TIPOCLI_DESDE varchar(10),
	@CLIENTE_2980_TIPOCLI_HASTA varchar(10),
	@CLIENTE_2980_CATEGCLI_DESDE varchar(10),
	@CLIENTE_2980_CATEGCLI_HASTA varchar(10),
	@CLIENTE_2980_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_2980_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_2980_SUJETOVINCULADO bit,
	@CLIENTE_2980_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_2980_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_2980_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_2980_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_2980_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_2980_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_2980_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_2980_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_2980_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_2980_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_2980_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_2980_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_2980_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_2980_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_2980_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_2980_APELLIDO_DESDE varchar(60),
	@CLIENTE_2980_APELLIDO_HASTA varchar(60),
	@CLIENTE_2980_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_2980_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_2980_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_2980_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_2980_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_2980_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_2980_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_2980_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_2980_TASACEROAPLICA bit,
	@CLIENTE_2980_INACTIVOFW bit,
	@SUCURSAL_3484_CODIGO_DESDE varchar(10),
	@SUCURSAL_3484_CODIGO_HASTA varchar(10),
	@CTACTE_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@CTACTE_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@CTACTE_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@CTACTE_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@CTACTE_FECHAALTAFW_DESDE datetime,
	@CTACTE_FECHAALTAFW_HASTA datetime,
	@CTACTE_FECHAEXPO_DESDE datetime,
	@CTACTE_FECHAEXPO_HASTA datetime,
	@CTACTE_FECHAIMPO_DESDE datetime,
	@CTACTE_FECHAIMPO_HASTA datetime,
	@CTACTE_FECHAMODIFICACIONFW_DESDE datetime,
	@CTACTE_FECHAMODIFICACIONFW_HASTA datetime,
	@CTACTE_FECHATRANSFERENCIA_DESDE datetime,
	@CTACTE_FECHATRANSFERENCIA_HASTA datetime,
	@CTACTE_HORAALTAFW_DESDE varchar(8),
	@CTACTE_HORAALTAFW_HASTA varchar(8),
	@CTACTE_HORAEXPO_DESDE varchar(8),
	@CTACTE_HORAEXPO_HASTA varchar(8),
	@CTACTE_HORAIMPO_DESDE varchar(8),
	@CTACTE_HORAIMPO_HASTA varchar(8),
	@CTACTE_HORAMODIFICACIONFW_DESDE varchar(8),
	@CTACTE_HORAMODIFICACIONFW_HASTA varchar(8),
	@CTACTE_SERIEALTAFW_DESDE varchar(7),
	@CTACTE_SERIEALTAFW_HASTA varchar(7),
	@CTACTE_SERIEMODIFICACIONFW_DESDE varchar(7),
	@CTACTE_SERIEMODIFICACIONFW_HASTA varchar(7),
	@CTACTE_USUARIOALTAFW_DESDE varchar(100),
	@CTACTE_USUARIOALTAFW_HASTA varchar(100),
	@CTACTE_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@CTACTE_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@CTACTE_VERSIONALTAFW_DESDE varchar(13),
	@CTACTE_VERSIONALTAFW_HASTA varchar(13),
	@CTACTE_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@CTACTE_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@CTACTE_BASEDEDATOSALTAFW_DESDE varchar(8),
	@CTACTE_BASEDEDATOSALTAFW_HASTA varchar(8),
	@Parametro1 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_ctacte.codigo, 38, ' ' ) as varchar( 46 ) ) as CTACTE__Grupo,
	@basededatos as CTACTE__BD,
	c_CTACTE.CODIGO as CTACTE_Codigo,
	c_CTACTE.MONEDA as CTACTE_Moneda,
	C_CLIENTE.CIMAGEN as CLIENTE_CIMAGEN,
	c_CTACTE.LETRA as CTACTE_letra,
	c_CTACTE.PTOVTA as CTACTE_ptovta,
	c_CTACTE.NUMERO as CTACTE_numero,
	c_CTACTE.FACTSEC as CTACTE_factsec,
	case when c_ctacte.fechaven = '01/01/1900 00:00:00' then null else c_ctacte.fechaven end as CTACTE_fechaven,
	c_CTACTE.TIPOCOMP as CTACTE_TipoComp,
	case when c_ctacte.fecha = '01/01/1900 00:00:00' then null else c_ctacte.fecha end as CTACTE_Fecha,
	c_CTACTE.VALOR as CTACTE_Valor,
	c_CTACTE.SIGNO as CTACTE_Signo,
	cast( case when c_moneda.tipagrupub<= 1 then upper('todos') when c_moneda.tipagrupub= 2 then upper('ninguno') else stuff((select '; '+rtrim(agrup) from zoologic.agrupubmon where codigo = rtrim(c_moneda.codigo) order by agrup for xml path('')),1,2,'') end as varchar( 254 ) ) as MONEDA_FiltroDePublicacionesVirtual,
	cast( funciones.pertenecealsegmentotemporal(c_ctacte.fechaven, funciones.datetime(), '15',-5,-4,-1)*c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Segmento1,
	cast( funciones.pertenecealsegmentotemporal(c_ctacte.fechaven, funciones.datetime(), '15',-4,-4,-1)*c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Segmento2,
	cast( funciones.pertenecealsegmentotemporal(c_ctacte.fechaven, funciones.datetime(), '15',-3,-4,-1)*c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Segmento3,
	cast( funciones.pertenecealsegmentotemporal(c_ctacte.fechaven, funciones.datetime(), '15',-2,-4,-1)*c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Segmento4,
	cast( funciones.pertenecealsegmentotemporal(c_ctacte.fechaven, funciones.datetime(), '15',-1,-4,-1)*c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Segmento5,
	cast( funciones.pertenecealsegmentotemporal(c_ctacte.fechaven, funciones.datetime(), '15', 0,-4,-1)*c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Segmento6,
	cast( c_ctacte.saldocc*sign(-c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_Haber,
	cast( c_ctacte.saldocc*c_ctacte.signo as numeric( 15, 2 ) ) as CTACTE_SaldoLinea,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CLIENTE.CLVEND as CLIENTE_CLVend,
	C_CLIENTE.CLCALLE as CLIENTE_CLCalle,
	C_CLIENTE.CLCP as CLIENTE_CLCP,
	C_CLIENTE.CLCUIT as CLIENTE_CLCUIT,
	C_CLIENTE.CLDEPTO as CLIENTE_CLDEPTO,
	C_CLIENTE.CLEMAIL as CLIENTE_CLEMAIL,
	C_CLIENTE.CLFAX as CLIENTE_CLFAX,
	case when c_cliente.clfecha = '01/01/1900 00:00:00' then null else c_cliente.clfecha end as CLIENTE_CLFECHA,
	C_CLIENTE.CLLOC as CLIENTE_CLLOC,
	C_CLIENTE.CLNRODOC as CLIENTE_CLNRODOC,
	C_CLIENTE.CLNRO as CLIENTE_CLNro,
	C_CLIENTE.CLOBS as CLIENTE_CLOBS,
	C_CLIENTE.CLPAGEWEB as CLIENTE_CLPAGEWEB,
	C_CLIENTE.CLPAIS as CLIENTE_CLPAIS,
	C_CLIENTE.CLPISO as CLIENTE_ClPiso,
	C_CLIENTE.CLPRV as CLIENTE_CLPRV,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_CLIENTE.CLTLF as CLIENTE_CLTLF,
	C_CLIENTE.CLTIPODOC as CLIENTE_CLTIPODOC,
	C_CLIENTE.CLMOVIL as CLIENTE_CLMovil,
	C_CLIENTE.CLTOPECCTE as CLIENTE_CLTOPECCTE,
	C_CLIENTE.CLLISPREC as CLIENTE_CLLisPrec,
	C_CLIENTE.CLCLAS as CLIENTE_CLCLAS,
	C_CLIENTE.CLTIPCONV as CLIENTE_CLTIPCONV,
	C_CLIENTE.CLNROIIBB as CLIENTE_CLNROIIBB,
	C_CLIENTE.CLCO_DTO as CLIENTE_CLCO_DTO,
	C_CLIENTE.CLTRANS as CLIENTE_CLTRANS,
	C_CLIENTE.ESTADO as CLIENTE_Estado,
	C_CLIENTE.HIJOS as CLIENTE_Hijos,
	C_CLIENTE.SEXO as CLIENTE_Sexo,
	C_CLIENTE.GLOBALID as CLIENTE_globalid,
	C_CLIENTE.RUT as CLIENTE_RUT,
	C_CLIENTE.CLCODFANT as CLIENTE_CLCODFANT,
	C_CLIENTE.CLTIPOCLI as CLIENTE_CLTipoCli,
	C_CLIENTE.CLCATEGCLI as CLIENTE_CLCategCli,
	C_CLIENTE.CLCONDPAG as CLIENTE_CLCONDPAG,
	C_CLIENTE.CLSUJVINC as CLIENTE_CLSujVinc,
	C_CLIENTE.CLPERTIVA as CLIENTE_CLPERTIVA,
	C_CLIENTE.CLSITGAN as CLIENTE_CLSITGAN,
	C_CLIENTE.EXPERIVA as CLIENTE_EXPERIVA,
	C_CLIENTE.CLPERGAN as CLIENTE_CLPERGAN,
	C_CLIENTE.EXPERGAN as CLIENTE_EXPERGAN,
	C_CLIENTE.CODRECOM as CLIENTE_CODRECOM,
	C_CLIENTE.NOMRECOM as CLIENTE_NOMRECOM,
	C_CLIENTE.CLPRINOM as CLIENTE_CLPRINOM,
	C_CLIENTE.CLSEGNOM as CLIENTE_CLSEGNOM,
	C_CLIENTE.CLAPELL as CLIENTE_CLAPELL,
	case when c_cliente.vhastaiva = '01/01/1900 00:00:00' then null else c_cliente.vhastaiva end as CLIENTE_VHastaIva,
	case when c_cliente.vhastagan = '01/01/1900 00:00:00' then null else c_cliente.vhastagan end as CLIENTE_VHastaGan,
	C_CLIENTE.CLSIPRIB as CLIENTE_CLSIPRIB,
	C_CLIENTE.PORCENTC as CLIENTE_PorcenTC,
	C_CLIENTE.APLICATC as CLIENTE_AplicaTC,
	C_CLIENTE.INACTIVOFW as CLIENTE_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_CTACTE.BDMODIFW as CTACTE_BDMODIFW,
	c_CTACTE.ESTTRANS as CTACTE_ESTTRANS,
	case when c_ctacte.faltafw = '01/01/1900 00:00:00' then null else c_ctacte.faltafw end as CTACTE_FALTAFW,
	case when c_ctacte.fecexpo = '01/01/1900 00:00:00' then null else c_ctacte.fecexpo end as CTACTE_FECEXPO,
	case when c_ctacte.fecimpo = '01/01/1900 00:00:00' then null else c_ctacte.fecimpo end as CTACTE_FECIMPO,
	case when c_ctacte.fmodifw = '01/01/1900 00:00:00' then null else c_ctacte.fmodifw end as CTACTE_FMODIFW,
	case when c_ctacte.fectrans = '01/01/1900 00:00:00' then null else c_ctacte.fectrans end as CTACTE_FECTRANS,
	c_CTACTE.HALTAFW as CTACTE_HALTAFW,
	c_CTACTE.HORAEXPO as CTACTE_HORAEXPO,
	c_CTACTE.HORAIMPO as CTACTE_HORAIMPO,
	c_CTACTE.HMODIFW as CTACTE_HMODIFW,
	c_CTACTE.SALTAFW as CTACTE_SALTAFW,
	c_CTACTE.SMODIFW as CTACTE_SMODIFW,
	c_CTACTE.UALTAFW as CTACTE_UALTAFW,
	c_CTACTE.UMODIFW as CTACTE_UMODIFW,
	c_CTACTE.VALTAFW as CTACTE_VALTAFW,
	c_CTACTE.VMODIFW as CTACTE_VMODIFW,
	c_CTACTE.ZADSFW as CTACTE_ZADSFW,
	c_CTACTE.BDALTAFW as CTACTE_BDAltaFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as CTACTE__SUCURSAL,
	c_CTACTE.CLIENTE as CTACTE_Cliente,
	C_CLIENTE.BDALTAFW as CLIENTE_BDALTAFW,
	cast( funciones.identificadordecomprobanteparalistado(c_ctacte.tipocomp, c_ctacte.letra, c_ctacte.ptovta, c_ctacte.numero) as varchar( 100 ) ) as CTACTE_ComprobanteVirtual,
	cast( case when c_ctacte.tipocomp = 13 and c_ctacte.totalcc = 0 then funciones.obtenercantidadcontrapuestaenunreciboconresultadoencero(c_ctacte.codcomp) else c_ctacte.totalcc*sign(c_ctacte.signo+1) end as numeric( 15, 2 ) ) as CTACTE_DebeVirtual,
	cast( case when c_ctacte.tipocomp = 13 and c_ctacte.totalcc = 0 then funciones.obtenercantidadcontrapuestaenunreciboconresultadoencero(c_ctacte.codcomp) else c_ctacte.totalcc*sign(-c_ctacte.signo+1) end as numeric( 15, 2 ) ) as CTACTE_HaberVirtual,
	cast( c_ctacte.saldocc*c_ctacte.signo as numeric( 15, 2 ) ) as CTACTE_SaldoCC,
	cast( c_ctacte.totalcc*c_ctacte.signo as numeric( 15, 2 ) ) as CTACTE_TotalCC,
	c_CTACTE.CODCOMP as CTACTE_CodComp,
	C_FACTURA.FVEN as FACTURA_FVEN,
	C_RECIBO.FVEN as RECIBO_FVEN,
	cast( funciones.obtenercodigovendedor(c_ctacte.tipocomp, c_recibo.fven, c_factura.fven) as varchar( 10 ) ) as CTACTE_VendedorVirtual,
	C_VENDEDOR3060.CLNOM as VENDEDOR3060_CLNOM,
	cast( funciones.obtenerinformaciondeafectacionesenunrecibodeventa(c_ctacte.codcomp, c_ctacte.signo, c_ctacte.totalcc) as varchar( 254 ) ) as CTACTE_AfectacionesVirtual,
	cast( 0 as numeric( 2, 0 ) ) as CTACTE_OrdenVirtual,
	C_MONEDA.SIMBOLO as MONEDA_Simbolo,
	cast(case when c_ctacte.saldocc <> 0 then 1 else 0 end as bit) as CTACTE_ComprobanteConSaldoVirtual,
	cast(case when coalesce(c_ctacte.fechaven, funciones.datetime()) < funciones.datetime() then 1 else 0 end as bit) as CTACTE_ComprobanteVencidoVirtual,
	cast( c_ctacte.saldocc*sign(c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_DebeSobrePendienteVirtual,
	cast( c_ctacte.saldocc*sign(-c_ctacte.signo+1) as numeric( 15, 2 ) ) as CTACTE_HaberSobrePendienteVirtual,
	cast( case when rtrim(c_ctacte.clglobalid) = '' then c_ctacte.cliente else c_ctacte.clglobalid end as varchar( 38 ) ) as CTACTE_ClienteVirtual,
	cast( @parametro1 as numeric( 1, 0 ) ) as CTACTE_IncluirCheques3NoVencVirtual,
	case when C_FACTURA.FOBS is null then C_RECIBO.FOBS else C_FACTURA.FOBS end as FACTURA_FOBS,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_VALOR.CLNOM as VALOR_CLNOM,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_VENDEDOR21.CLNOM as VENDEDOR21_CLNOM,
	C_PAISES.PDES as PAISES_pdes,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_CLIENTE.CLIVA as CLIENTE_CLIVA,
	C_LISTADEPRECIOS.LPR_NOMBRE as LISTADEPRECIOS_LPR_NOMBRE,
	C_CLASIFICACIONCLIENTE.CLADES as CLASIFICACIONCLIENTE_CLADES,
	C_DESCUENTO.DES as DESCUENTO_Des,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_NOMBREDEFANTASIA.NFCOD as NOMBREDEFANTASIA_NFCOD,
	C_TIPOCLIENTE.TCDES as TIPOCLIENTE_TCDES,
	C_CATEGORIACLIENTE.CGDES as CATEGORIACLIENTE_CGDes,
	C_CONDICIONDEPAGO.CLNOM as CONDICIONDEPAGO_CLNOM,
	C_IMPUESTO60.DESCRIP as IMPUESTO60_descrip,
	C_IMPUESTO63.DESCRIP as IMPUESTO63_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_CLIENTE.CLNOM as CLIENTE_CLNOM,
	C_VENDEDOR3070.CLNOM as VENDEDOR3070_CLNOM,
	C_CATEGORIACLIENTE.CGCOD as CATEGORIACLIENTE_CGCod,
	C_CLASIFICACIONCLIENTE.CLACOD as CLASIFICACIONCLIENTE_CLACOD,
	C_CLIENTE.CLCOD as CLIENTE_CLCOD,
	C_CONDICIONDEPAGO.CLCOD as CONDICIONDEPAGO_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DESCUENTO.CODIGO as DESCUENTO_codigo,
	C_FACTURA.CODIGO as FACTURA_CODIGO,
	C_IMPUESTO60.CODIGO as IMPUESTO60_codigo,
	C_IMPUESTO63.CODIGO as IMPUESTO63_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS.LPR_NUMERO as LISTADEPRECIOS_LPR_NUMERO,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_PAISES.PCOD as PAISES_pcod,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_RECIBO.CODIGO as RECIBO_CODIGO,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOCLIENTE.TCCOD as TIPOCLIENTE_TCCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_VALOR.CLCOD as VALOR_CLCOD,
	C_VENDEDOR21.CLCOD as VENDEDOR21_CLCOD,
	C_VENDEDOR3060.CLCOD as VENDEDOR3060_CLCOD,
	C_VENDEDOR3070.CLCOD as VENDEDOR3070_CLCOD
 from ZooLogic.CTACTE as c_CTACTE
 --left join Zoologic.Cli as C_cliente on 
--	( ( c_Cliente.GlobalId = '' and c_CTACTE.clGlobalId = '' and  c_Cliente.CLCOD =  c_CTACTE.Cliente ) 
--	OR ( c_Cliente.GlobalId <> '' and c_CTACTE.clGlobalId <> '' and c_Cliente.GlobalId = c_CTACTE.clGlobalId ) )

	left join
		( Select 2 as nro_linea, * from zoologic.cli where globalid = ''
		  union all
		  Select * from
		( select row_number() over (partition by globalid order by globalid ) nro_linea , * from zoologic.cli ) cl where globalid != '' and nro_linea = 1 ) AS C_cliente on
		      ( 1 - funciones.empty(CLGLOBALID)  = 0 and C_CLIENTE.CLCOD = C_CTACTE.CLIENTE ) 
			or  ( 1 - funciones.empty(CLGLOBALID)  = 1 and  C_CLIENTE.GLOBALID = C_CTACTE.CLGLOBALID ) 

 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO on C_CONDICIONDEPAGO.CLCOD = C_CLIENTE.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_CLIENTE.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO on C_DESCUENTO.CODIGO = C_CLIENTE.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE.CLCO_DTO )
 left join ZooLogic.COMPROBANTEV as C_FACTURA on C_FACTURA.CODIGO = C_CTACTE.CODCOMP and 0 = Funciones.empty( C_CTACTE.CODCOMP )
 left join ZooLogic.IMPUESTO as C_IMPUESTO60 on C_IMPUESTO60.CODIGO = C_CLIENTE.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO63 on C_IMPUESTO63.CODIGO = C_CLIENTE.CLPERGAN and 0 = Funciones.empty( C_CLIENTE.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS on C_LISTADEPRECIOS.LPR_NUMERO = C_CLIENTE.CLLISPREC and 0 = Funciones.empty( C_CLIENTE.CLLISPREC )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_CTACTE.MONEDA and 0 = Funciones.empty( C_CTACTE.MONEDA )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_CLIENTE.CLPAIS and 0 = Funciones.empty( C_CLIENTE.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_CLIENTE.CLPRV and 0 = Funciones.empty( C_CLIENTE.CLPRV )
 left join ZooLogic.RECIBO as C_RECIBO on C_RECIBO.CODIGO = C_CTACTE.CODCOMP and 0 = Funciones.empty( C_CTACTE.CODCOMP )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_CLIENTE.CLIVA and 0 = Funciones.empty( C_CLIENTE.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE on C_TIPOCLIENTE.TCCOD = C_CLIENTE.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_CLIENTE.CLTRANS and 0 = Funciones.empty( C_CLIENTE.CLTRANS )
 left join ZooLogic.XVAL as C_VALOR on C_VALOR.CLCOD = C_CTACTE.VALOR and 0 = Funciones.empty( C_CTACTE.VALOR )
 left join ZooLogic.VEN as C_VENDEDOR21 on C_VENDEDOR21.CLCOD = C_CLIENTE.CLVEND and 0 = Funciones.empty( C_CLIENTE.CLVEND )
 left join ZooLogic.VEN as C_VENDEDOR3060 on C_VENDEDOR3060.CLCOD = C_FACTURA.FVEN and 0 = Funciones.empty( C_FACTURA.FVEN )
 left join ZooLogic.VEN as C_VENDEDOR3070 on C_VENDEDOR3070.CLCOD = C_RECIBO.FVEN and 0 = Funciones.empty( C_RECIBO.FVEN )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA on C_NOMBREDEFANTASIA.NFCOD = C_CLIENTE.CLCODFANT and 0 = Funciones.empty( C_CLIENTE.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE on C_CATEGORIACLIENTE.CGCOD = C_CLIENTE.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE on C_CLASIFICACIONCLIENTE.CLACOD = C_CLIENTE.CLCLAS and 0 = Funciones.empty( C_CLIENTE.CLCLAS )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( c_ctacte.saldocc <> 0 ) and 
	cast( case when rtrim(c_ctacte.clglobalid) = '' then c_ctacte.cliente else c_ctacte.clglobalid end as varchar( 38 ) ) in 
		(select cast( case when rtrim(globalid) = '' then clcod else globalid end  as varchar( 38 ) ) 
			from ZooLogic.cli where CLCOD between coalesce( @CTACTE_CLIENTE_DESDE,'') and coalesce(@CTACTE_CLIENTE_HASTA,'ZZZZZZZZZZ') ) and 
	( ( @CLIENTE_2980_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_CLIENTE.BDALTAFW >= @CLIENTE_2980_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @CLIENTE_2980_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_CLIENTE.BDALTAFW <= @CLIENTE_2980_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURA_3050_VENDEDOR_DESDE is null ) OR ( C_FACTURA.FVEN >= @FACTURA_3050_VENDEDOR_DESDE ) ) and 
	( ( @FACTURA_3050_VENDEDOR_HASTA is null ) OR ( C_FACTURA.FVEN <= @FACTURA_3050_VENDEDOR_HASTA ) ) and 
	( ( @VENDEDOR_3060_NOMBRE_DESDE is null ) OR ( C_VENDEDOR3060.CLNOM >= @VENDEDOR_3060_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_3060_NOMBRE_HASTA is null ) OR ( C_VENDEDOR3060.CLNOM <= @VENDEDOR_3060_NOMBRE_HASTA ) ) and 
	( ( @FACTURA_3050_OBS_DESDE is null ) OR ( C_FACTURA.FObs >= @FACTURA_3050_OBS_DESDE ) ) and 
	( ( @FACTURA_3050_OBS_HASTA is null ) OR ( C_FACTURA.FObs <= @FACTURA_3050_OBS_HASTA ) ) and 
	( ( @CTACTE_CODIGO_DESDE is null ) OR ( c_CTACTE.Codigo >= @CTACTE_CODIGO_DESDE ) ) and 
	( ( @CTACTE_CODIGO_HASTA is null ) OR ( c_CTACTE.Codigo <= @CTACTE_CODIGO_HASTA ) ) and 
	( ( @CTACTE_MONEDA_DESDE is null ) OR ( c_CTACTE.Moneda >= @CTACTE_MONEDA_DESDE ) ) and 
	( ( @CTACTE_MONEDA_HASTA is null ) OR ( c_CTACTE.Moneda <= @CTACTE_MONEDA_HASTA ) ) and 
	( ( @CTACTE_LETRA_DESDE is null ) OR ( c_CTACTE.letra >= @CTACTE_LETRA_DESDE ) ) and 
	( ( @CTACTE_LETRA_HASTA is null ) OR ( c_CTACTE.letra <= @CTACTE_LETRA_HASTA ) ) and 
	( ( @CTACTE_PUNTODEVENTA_DESDE is null ) OR ( c_CTACTE.ptovta >= @CTACTE_PUNTODEVENTA_DESDE ) ) and 
	( ( @CTACTE_PUNTODEVENTA_HASTA is null ) OR ( c_CTACTE.ptovta <= @CTACTE_PUNTODEVENTA_HASTA ) ) and 
	( ( @CTACTE_NUMERO_DESDE is null ) OR ( c_CTACTE.numero >= @CTACTE_NUMERO_DESDE ) ) and 
	( ( @CTACTE_NUMERO_HASTA is null ) OR ( c_CTACTE.numero <= @CTACTE_NUMERO_HASTA ) ) and 
	( ( @CTACTE_SECUENCIA_DESDE is null ) OR ( c_CTACTE.factsec >= @CTACTE_SECUENCIA_DESDE ) ) and 
	( ( @CTACTE_SECUENCIA_HASTA is null ) OR ( c_CTACTE.factsec <= @CTACTE_SECUENCIA_HASTA ) ) and 
	( ( @CTACTE_FECHAVENCIMIENTO_DESDE is null ) OR ( c_CTACTE.fechaven >= @CTACTE_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @CTACTE_FECHAVENCIMIENTO_HASTA is null ) OR ( c_CTACTE.fechaven <= @CTACTE_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @CTACTE_TIPODECOMPROBANTE_DESDE is null ) OR ( c_CTACTE.TipoComp >= @CTACTE_TIPODECOMPROBANTE_DESDE ) ) and 
	( ( @CTACTE_TIPODECOMPROBANTE_HASTA is null ) OR ( c_CTACTE.TipoComp <= @CTACTE_TIPODECOMPROBANTE_HASTA ) ) and 
	( ( @CTACTE_FECHA_DESDE is null ) OR ( c_CTACTE.Fecha >= @CTACTE_FECHA_DESDE ) ) and 
	( ( @CTACTE_FECHA_HASTA is null ) OR ( c_CTACTE.Fecha <= @CTACTE_FECHA_HASTA ) ) and 
	( ( @CTACTE_VALOR_DESDE is null ) OR ( c_CTACTE.Valor >= @CTACTE_VALOR_DESDE ) ) and 
	( ( @CTACTE_VALOR_HASTA is null ) OR ( c_CTACTE.Valor <= @CTACTE_VALOR_HASTA ) ) and 
	( ( @CTACTE_SIGNODEMOVIMIENTO_DESDE is null ) OR ( c_CTACTE.Signo >= @CTACTE_SIGNODEMOVIMIENTO_DESDE ) ) and 
	( ( @CTACTE_SIGNODEMOVIMIENTO_HASTA is null ) OR ( c_CTACTE.Signo <= @CTACTE_SIGNODEMOVIMIENTO_HASTA ) ) and 
	( ( @MONEDA_2_MONEDA_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_2_MONEDA_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_2_MONEDA_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_2_MONEDA_DESCRIPCION_HASTA ) ) and 
	( ( @VALOR_83_VALOR_DESCRIPCION_DESDE is null ) OR ( C_VALOR.CLNOM >= @VALOR_83_VALOR_DESCRIPCION_DESDE ) ) and 
	( ( @VALOR_83_VALOR_DESCRIPCION_HASTA is null ) OR ( C_VALOR.CLNOM <= @VALOR_83_VALOR_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_3489_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_3489_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_3489_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_3489_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_3488_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_3488_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_3488_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_3488_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_3487_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_3487_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_3487_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_3487_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_21_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR21.CLNOM >= @VENDEDOR_21_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_21_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR21.CLNOM <= @VENDEDOR_21_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_36_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_36_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_36_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_36_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_38_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_38_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_38_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_38_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_44_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE >= @LISTADEPRECIOS_44_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_44_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE <= @LISTADEPRECIOS_44_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_45_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES >= @CLASIFICACIONCLIENTE_45_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_45_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES <= @CLASIFICACIONCLIENTE_45_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_48_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO.Des >= @DESCUENTO_48_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_48_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO.Des <= @DESCUENTO_48_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_49_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_49_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_49_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_49_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_55_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA.NFCOD >= @NOMBREDEFANTASIA_55_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_55_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA.NFCOD <= @NOMBREDEFANTASIA_55_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_56_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE.TCDES >= @TIPOCLIENTE_56_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_56_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE.TCDES <= @TIPOCLIENTE_56_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_57_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE.CGDes >= @CATEGORIACLIENTE_57_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_57_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE.CGDes <= @CATEGORIACLIENTE_57_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_58_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO.CLNOM >= @CONDICIONDEPAGO_58_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_58_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO.CLNOM <= @CONDICIONDEPAGO_58_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_60_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO60.descrip >= @IMPUESTO_60_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_60_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO60.descrip <= @IMPUESTO_60_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_63_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO63.descrip >= @IMPUESTO_63_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_63_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO63.descrip <= @IMPUESTO_63_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_72_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_72_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_72_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_72_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_2980_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE.CLNOM >= @CLIENTE_2980_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2980_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE.CLNOM <= @CLIENTE_2980_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @SUCURSAL_3484_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_3484_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_3484_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_3484_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_3484_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_3484_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_3484_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_3484_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_3484_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_3484_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_3484_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_3484_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_3484_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_3484_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_3484_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_3484_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_2980_VENDEDOR_DESDE is null ) OR ( C_CLIENTE.CLVend >= @CLIENTE_2980_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_2980_VENDEDOR_HASTA is null ) OR ( C_CLIENTE.CLVend <= @CLIENTE_2980_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_2980_CALLE_DESDE is null ) OR ( C_CLIENTE.CLCalle >= @CLIENTE_2980_CALLE_DESDE ) ) and 
	( ( @CLIENTE_2980_CALLE_HASTA is null ) OR ( C_CLIENTE.CLCalle <= @CLIENTE_2980_CALLE_HASTA ) ) and 
	( ( @CLIENTE_2980_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE.CLCP >= @CLIENTE_2980_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_2980_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE.CLCP <= @CLIENTE_2980_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_2980_CUIT_DESDE is null ) OR ( C_CLIENTE.CLCUIT >= @CLIENTE_2980_CUIT_DESDE ) ) and 
	( ( @CLIENTE_2980_CUIT_HASTA is null ) OR ( C_CLIENTE.CLCUIT <= @CLIENTE_2980_CUIT_HASTA ) ) and 
	( ( @CLIENTE_2980_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE.CLDEPTO >= @CLIENTE_2980_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_2980_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE.CLDEPTO <= @CLIENTE_2980_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_2980_EMAIL_DESDE is null ) OR ( C_CLIENTE.CLEMAIL >= @CLIENTE_2980_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_2980_EMAIL_HASTA is null ) OR ( C_CLIENTE.CLEMAIL <= @CLIENTE_2980_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_2980_FAX_DESDE is null ) OR ( C_CLIENTE.CLFAX >= @CLIENTE_2980_FAX_DESDE ) ) and 
	( ( @CLIENTE_2980_FAX_HASTA is null ) OR ( C_CLIENTE.CLFAX <= @CLIENTE_2980_FAX_HASTA ) ) and 
	( ( @CLIENTE_2980_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE.CLFECHA >= @CLIENTE_2980_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_2980_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE.CLFECHA <= @CLIENTE_2980_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_2980_IMAGEN_DESDE is null ) OR ( C_CLIENTE.CIMAGEN >= @CLIENTE_2980_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_2980_IMAGEN_HASTA is null ) OR ( C_CLIENTE.CIMAGEN <= @CLIENTE_2980_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_2980_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE.CLLOC >= @CLIENTE_2980_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_2980_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE.CLLOC <= @CLIENTE_2980_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_2980_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLNRODOC >= @CLIENTE_2980_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2980_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLNRODOC <= @CLIENTE_2980_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2980_NUMERO_DESDE is null ) OR ( C_CLIENTE.CLNro >= @CLIENTE_2980_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_2980_NUMERO_HASTA is null ) OR ( C_CLIENTE.CLNro <= @CLIENTE_2980_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_2980_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE.CLPAGEWEB >= @CLIENTE_2980_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_2980_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE.CLPAGEWEB <= @CLIENTE_2980_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_2980_PAIS_DESDE is null ) OR ( C_CLIENTE.CLPAIS >= @CLIENTE_2980_PAIS_DESDE ) ) and 
	( ( @CLIENTE_2980_PAIS_HASTA is null ) OR ( C_CLIENTE.CLPAIS <= @CLIENTE_2980_PAIS_HASTA ) ) and 
	( ( @CLIENTE_2980_PISO_DESDE is null ) OR ( C_CLIENTE.ClPiso >= @CLIENTE_2980_PISO_DESDE ) ) and 
	( ( @CLIENTE_2980_PISO_HASTA is null ) OR ( C_CLIENTE.ClPiso <= @CLIENTE_2980_PISO_HASTA ) ) and 
	( ( @CLIENTE_2980_PROVINCIA_DESDE is null ) OR ( C_CLIENTE.CLPRV >= @CLIENTE_2980_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_2980_PROVINCIA_HASTA is null ) OR ( C_CLIENTE.CLPRV <= @CLIENTE_2980_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_39_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_39_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_2980_TELEFONO_DESDE is null ) OR ( C_CLIENTE.CLTLF >= @CLIENTE_2980_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_2980_TELEFONO_HASTA is null ) OR ( C_CLIENTE.CLTLF <= @CLIENTE_2980_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_2980_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLTIPODOC >= @CLIENTE_2980_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2980_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLTIPODOC <= @CLIENTE_2980_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2980_MOVIL_DESDE is null ) OR ( C_CLIENTE.CLMovil >= @CLIENTE_2980_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_2980_MOVIL_HASTA is null ) OR ( C_CLIENTE.CLMovil <= @CLIENTE_2980_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_2980_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE.CLTOPECCTE >= @CLIENTE_2980_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_2980_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE.CLTOPECCTE <= @CLIENTE_2980_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_2980_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE.CLLisPrec >= @CLIENTE_2980_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_2980_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE.CLLisPrec <= @CLIENTE_2980_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_2980_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE.CLCLAS >= @CLIENTE_2980_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_2980_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE.CLCLAS <= @CLIENTE_2980_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_2980_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE.CLTIPCONV >= @CLIENTE_2980_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_2980_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE.CLTIPCONV <= @CLIENTE_2980_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_2980_NROIIBB_DESDE is null ) OR ( C_CLIENTE.CLNROIIBB >= @CLIENTE_2980_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_2980_NROIIBB_HASTA is null ) OR ( C_CLIENTE.CLNROIIBB <= @CLIENTE_2980_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_2980_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE.CLCO_DTO >= @CLIENTE_2980_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_2980_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE.CLCO_DTO <= @CLIENTE_2980_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_2980_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE.CLTRANS >= @CLIENTE_2980_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_2980_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE.CLTRANS <= @CLIENTE_2980_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_2980_ESTADOCIVIL is null ) OR ( C_CLIENTE.Estado = @CLIENTE_2980_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_2980_HIJOS_DESDE is null ) OR ( C_CLIENTE.Hijos >= @CLIENTE_2980_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_2980_HIJOS_HASTA is null ) OR ( C_CLIENTE.Hijos <= @CLIENTE_2980_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_2980_SEXO is null ) OR ( C_CLIENTE.Sexo = @CLIENTE_2980_SEXO ) ) and 
	( ( @CLIENTE_2980_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE.globalid >= @CLIENTE_2980_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_2980_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE.globalid <= @CLIENTE_2980_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_2980_RUT_DESDE is null ) OR ( C_CLIENTE.RUT >= @CLIENTE_2980_RUT_DESDE ) ) and 
	( ( @CLIENTE_2980_RUT_HASTA is null ) OR ( C_CLIENTE.RUT <= @CLIENTE_2980_RUT_HASTA ) ) and 
	( ( @CLIENTE_2980_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE.CLCODFANT >= @CLIENTE_2980_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_2980_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE.CLCODFANT <= @CLIENTE_2980_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_2980_TIPOCLI_DESDE is null ) OR ( C_CLIENTE.CLTipoCli >= @CLIENTE_2980_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_2980_TIPOCLI_HASTA is null ) OR ( C_CLIENTE.CLTipoCli <= @CLIENTE_2980_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_2980_CATEGCLI_DESDE is null ) OR ( C_CLIENTE.CLCategCli >= @CLIENTE_2980_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_2980_CATEGCLI_HASTA is null ) OR ( C_CLIENTE.CLCategCli <= @CLIENTE_2980_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_2980_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE.CLCONDPAG >= @CLIENTE_2980_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_2980_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE.CLCONDPAG <= @CLIENTE_2980_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_2980_SUJETOVINCULADO is null ) OR ( C_CLIENTE.CLSujVinc = @CLIENTE_2980_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_2980_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE.CLPERTIVA >= @CLIENTE_2980_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_2980_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE.CLPERTIVA <= @CLIENTE_2980_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_2980_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE.CLSITGAN = @CLIENTE_2980_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_2980_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE.EXPERIVA = @CLIENTE_2980_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_2980_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE.CLPERGAN >= @CLIENTE_2980_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_2980_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE.CLPERGAN <= @CLIENTE_2980_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_2980_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE.EXPERGAN = @CLIENTE_2980_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_2980_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.CODRECOM >= @CLIENTE_2980_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2980_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.CODRECOM <= @CLIENTE_2980_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2980_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.NOMRECOM >= @CLIENTE_2980_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2980_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.NOMRECOM <= @CLIENTE_2980_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2980_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE.CLPRINOM >= @CLIENTE_2980_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2980_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE.CLPRINOM <= @CLIENTE_2980_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2980_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE.CLSEGNOM >= @CLIENTE_2980_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2980_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE.CLSEGNOM <= @CLIENTE_2980_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2980_APELLIDO_DESDE is null ) OR ( C_CLIENTE.CLAPELL >= @CLIENTE_2980_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_2980_APELLIDO_HASTA is null ) OR ( C_CLIENTE.CLAPELL <= @CLIENTE_2980_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_2980_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE.VHastaIva >= @CLIENTE_2980_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_2980_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE.VHastaIva <= @CLIENTE_2980_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_2980_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE.VHastaGan >= @CLIENTE_2980_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_2980_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE.VHastaGan <= @CLIENTE_2980_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_2980_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE.CLSIPRIB >= @CLIENTE_2980_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_2980_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE.CLSIPRIB <= @CLIENTE_2980_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_2980_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE.PorcenTC >= @CLIENTE_2980_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_2980_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE.PorcenTC <= @CLIENTE_2980_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_2980_TASACEROAPLICA is null ) OR ( C_CLIENTE.AplicaTC = @CLIENTE_2980_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_2980_INACTIVOFW is null ) OR ( C_CLIENTE.InactivoFW = @CLIENTE_2980_INACTIVOFW ) ) and 
	( ( @SUCURSAL_3484_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_3484_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_3484_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_3484_CODIGO_HASTA ) ) and 
	( ( @CTACTE_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_CTACTE.BDMODIFW >= @CTACTE_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @CTACTE_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_CTACTE.BDMODIFW <= @CTACTE_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @CTACTE_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_CTACTE.ESTTRANS >= @CTACTE_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @CTACTE_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_CTACTE.ESTTRANS <= @CTACTE_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @CTACTE_FECHAALTAFW_DESDE is null ) OR ( c_CTACTE.FALTAFW >= @CTACTE_FECHAALTAFW_DESDE ) ) and 
	( ( @CTACTE_FECHAALTAFW_HASTA is null ) OR ( c_CTACTE.FALTAFW <= @CTACTE_FECHAALTAFW_HASTA ) ) and 
	( ( @CTACTE_FECHAEXPO_DESDE is null ) OR ( c_CTACTE.FECEXPO >= @CTACTE_FECHAEXPO_DESDE ) ) and 
	( ( @CTACTE_FECHAEXPO_HASTA is null ) OR ( c_CTACTE.FECEXPO <= @CTACTE_FECHAEXPO_HASTA ) ) and 
	( ( @CTACTE_FECHAIMPO_DESDE is null ) OR ( c_CTACTE.FECIMPO >= @CTACTE_FECHAIMPO_DESDE ) ) and 
	( ( @CTACTE_FECHAIMPO_HASTA is null ) OR ( c_CTACTE.FECIMPO <= @CTACTE_FECHAIMPO_HASTA ) ) and 
	( ( @CTACTE_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_CTACTE.FMODIFW >= @CTACTE_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @CTACTE_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_CTACTE.FMODIFW <= @CTACTE_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @CTACTE_FECHATRANSFERENCIA_DESDE is null ) OR ( c_CTACTE.FECTRANS >= @CTACTE_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @CTACTE_FECHATRANSFERENCIA_HASTA is null ) OR ( c_CTACTE.FECTRANS <= @CTACTE_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @CTACTE_HORAALTAFW_DESDE is null ) OR ( c_CTACTE.HALTAFW >= @CTACTE_HORAALTAFW_DESDE ) ) and 
	( ( @CTACTE_HORAALTAFW_HASTA is null ) OR ( c_CTACTE.HALTAFW <= @CTACTE_HORAALTAFW_HASTA ) ) and 
	( ( @CTACTE_HORAEXPO_DESDE is null ) OR ( c_CTACTE.HORAEXPO >= @CTACTE_HORAEXPO_DESDE ) ) and 
	( ( @CTACTE_HORAEXPO_HASTA is null ) OR ( c_CTACTE.HORAEXPO <= @CTACTE_HORAEXPO_HASTA ) ) and 
	( ( @CTACTE_HORAIMPO_DESDE is null ) OR ( c_CTACTE.HORAIMPO >= @CTACTE_HORAIMPO_DESDE ) ) and 
	( ( @CTACTE_HORAIMPO_HASTA is null ) OR ( c_CTACTE.HORAIMPO <= @CTACTE_HORAIMPO_HASTA ) ) and 
	( ( @CTACTE_HORAMODIFICACIONFW_DESDE is null ) OR ( c_CTACTE.HMODIFW >= @CTACTE_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @CTACTE_HORAMODIFICACIONFW_HASTA is null ) OR ( c_CTACTE.HMODIFW <= @CTACTE_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @CTACTE_SERIEALTAFW_DESDE is null ) OR ( c_CTACTE.SALTAFW >= @CTACTE_SERIEALTAFW_DESDE ) ) and 
	( ( @CTACTE_SERIEALTAFW_HASTA is null ) OR ( c_CTACTE.SALTAFW <= @CTACTE_SERIEALTAFW_HASTA ) ) and 
	( ( @CTACTE_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_CTACTE.SMODIFW >= @CTACTE_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @CTACTE_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_CTACTE.SMODIFW <= @CTACTE_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @CTACTE_USUARIOALTAFW_DESDE is null ) OR ( c_CTACTE.UALTAFW >= @CTACTE_USUARIOALTAFW_DESDE ) ) and 
	( ( @CTACTE_USUARIOALTAFW_HASTA is null ) OR ( c_CTACTE.UALTAFW <= @CTACTE_USUARIOALTAFW_HASTA ) ) and 
	( ( @CTACTE_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_CTACTE.UMODIFW >= @CTACTE_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @CTACTE_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_CTACTE.UMODIFW <= @CTACTE_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @CTACTE_VERSIONALTAFW_DESDE is null ) OR ( c_CTACTE.VALTAFW >= @CTACTE_VERSIONALTAFW_DESDE ) ) and 
	( ( @CTACTE_VERSIONALTAFW_HASTA is null ) OR ( c_CTACTE.VALTAFW <= @CTACTE_VERSIONALTAFW_HASTA ) ) and 
	( ( @CTACTE_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_CTACTE.VMODIFW >= @CTACTE_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @CTACTE_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_CTACTE.VMODIFW <= @CTACTE_VERSIONMODIFICACIONFW_HASTA ) ) and 
	( ( @CTACTE_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_CTACTE.BDAltaFW >= @CTACTE_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @CTACTE_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_CTACTE.BDAltaFW <= @CTACTE_BASEDEDATOSALTAFW_HASTA ) )

)