IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_CONCILIACIONES_ITEMMOVBANCARIOS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_CONCILIACIONES_ITEMMOVBANCARIOS];
GO;

CREATE FUNCTION [Listados].[GENERICO_CONCILIACIONES_ITEMMOVBANCARIOS]
( @BaseDeDatos varchar(8),
	@CONCILIACIONES_NUMERO_DESDE numeric(8, 0),
	@CONCILIACIONES_NUMERO_HASTA numeric(8, 0),
	@CONCILIACIONES_CUENTABANCARIA_DESDE varchar(5),
	@CONCILIACIONES_CUENTABANCARIA_HASTA varchar(5),
	@CUENTABANCARIA_22_CUENTABANCARIA_DESCRIPCION_DESDE varchar(40),
	@CUENTABANCARIA_22_CUENTABANCARIA_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9338_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9338_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9337_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9337_TIPO_DESCRIPCION_HASTA varchar(50),
	@MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE varchar(40),
	@MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_9334_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9334_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9334_LINEA_DESDE varchar(10),
	@SUCURSAL_9334_LINEA_HASTA varchar(10),
	@SUCURSAL_9334_TIPO_DESDE varchar(10),
	@SUCURSAL_9334_TIPO_HASTA varchar(10),
	@SUCURSAL_9334_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9334_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9334_CODIGO_DESDE varchar(10),
	@SUCURSAL_9334_CODIGO_HASTA varchar(10),
	@CONCILIACIONES_BASEDEDATOSALTAFW_DESDE varchar(8),
	@CONCILIACIONES_BASEDEDATOSALTAFW_HASTA varchar(8),
	@CONCILIACIONES_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@CONCILIACIONES_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@CONCILIACIONES_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@CONCILIACIONES_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@CONCILIACIONES_FECHAALTAFW_DESDE datetime,
	@CONCILIACIONES_FECHAALTAFW_HASTA datetime,
	@CONCILIACIONES_FECHAEXPO_DESDE datetime,
	@CONCILIACIONES_FECHAEXPO_HASTA datetime,
	@CONCILIACIONES_FECHAIMPO_DESDE datetime,
	@CONCILIACIONES_FECHAIMPO_HASTA datetime,
	@CONCILIACIONES_FECHAMODIFICACIONFW_DESDE datetime,
	@CONCILIACIONES_FECHAMODIFICACIONFW_HASTA datetime,
	@CONCILIACIONES_FECHATRANSFERENCIA_DESDE datetime,
	@CONCILIACIONES_FECHATRANSFERENCIA_HASTA datetime,
	@CONCILIACIONES_HORAALTAFW_DESDE varchar(8),
	@CONCILIACIONES_HORAALTAFW_HASTA varchar(8),
	@CONCILIACIONES_HORAEXPO_DESDE varchar(8),
	@CONCILIACIONES_HORAEXPO_HASTA varchar(8),
	@CONCILIACIONES_HORAIMPO_DESDE varchar(8),
	@CONCILIACIONES_HORAIMPO_HASTA varchar(8),
	@CONCILIACIONES_HORAMODIFICACIONFW_DESDE varchar(8),
	@CONCILIACIONES_HORAMODIFICACIONFW_HASTA varchar(8),
	@CONCILIACIONES_SERIEALTAFW_DESDE varchar(7),
	@CONCILIACIONES_SERIEALTAFW_HASTA varchar(7),
	@CONCILIACIONES_SERIEMODIFICACIONFW_DESDE varchar(7),
	@CONCILIACIONES_SERIEMODIFICACIONFW_HASTA varchar(7),
	@CONCILIACIONES_USUARIOALTAFW_DESDE varchar(100),
	@CONCILIACIONES_USUARIOALTAFW_HASTA varchar(100),
	@CONCILIACIONES_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@CONCILIACIONES_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@CONCILIACIONES_VERSIONALTAFW_DESDE varchar(13),
	@CONCILIACIONES_VERSIONALTAFW_HASTA varchar(13),
	@CONCILIACIONES_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@CONCILIACIONES_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@CUENTABANCARIA_22_NUMERO_DESDE varchar(15),
	@CUENTABANCARIA_22_NUMERO_HASTA varchar(15),
	@CUENTABANCARIA_22_MONEDACUENTA_DESDE varchar(10),
	@CUENTABANCARIA_22_MONEDACUENTA_HASTA varchar(10),
	@CONCEPTOENTIDADFINANCIERA_9200_CONCEPTO_CONCEPTO_DESDE varchar(100),
	@CONCEPTOENTIDADFINANCIERA_9200_CONCEPTO_CONCEPTO_HASTA varchar(100),
	@MOVIMIENTOBANCARIO_24_FECHA_DESDE datetime,
	@MOVIMIENTOBANCARIO_24_FECHA_HASTA datetime,
	@MOVIMIENTOBANCARIO_24_NUMERO_DESDE numeric(10, 0),
	@MOVIMIENTOBANCARIO_24_NUMERO_HASTA numeric(10, 0),
	@MOVIMIENTOBANCARIO_24_IMPORTE_DESDE numeric(15, 2),
	@MOVIMIENTOBANCARIO_24_IMPORTE_HASTA numeric(15, 2),
	@MOVIMIENTOBANCARIO_24_CONCEPTO_DESDE varchar(10),
	@MOVIMIENTOBANCARIO_24_CONCEPTO_HASTA varchar(10) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemmovbancarios.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMMOVBANCARIOS__Grupo,
	@basededatos as ITEMMOVBANCARIOS__BD,
	c_ITEMMOVBANCARIOS.CODIGO as ITEMMOVBANCARIOS_Codigo,
	c_ITEMMOVBANCARIOS.MOV as ITEMMOVBANCARIOS_Mov,
	c_ITEMMOVBANCARIOS.NROITEM as ITEMMOVBANCARIOS_NROITEM,
	case when c_movimientobancario.fecha = '01/01/1900 00:00:00' then null else c_movimientobancario.fecha end as MOVIMIENTOBANCARIO_Fecha,
	C_MOVIMIENTOBANCARIO.NUMERO as MOVIMIENTOBANCARIO_Numero,
	C_MOVIMIENTOBANCARIO.IMPORTE as MOVIMIENTOBANCARIO_Importe,
	cast( '' as varchar( 100 ) ) as MOVIMIENTOBANCARIO_24_Descripcion,
	C_MOVIMIENTOBANCARIO.CONCEPTO as MOVIMIENTOBANCARIO_Concepto,
	CASE WHEN 0=Funciones.Empty(C_CONCEPTOENTIDADFINANCIERA.DESCRI) THEN C_CONCEPTOENTIDADFINANCIERA.DESCRI ELSE C_CONCEPTOENTIDADFINANCIERA.CONCEPTO END AS CONCEPTOENTIDADFINANCIERA_Concepto,
	C_CONCEPTOENTIDADFINANCIERA.CODIGO as CONCEPTOENTIDADFINANCIERA_Codigo,
	C_MOVIMIENTOBANCARIO.CODIGO as MOVIMIENTOBANCARIO_Codigo
 from ZooLogic.DETMOVBANC as c_ITEMMOVBANCARIOS
 left join ZooLogic.MOVBANC as C_MOVIMIENTOBANCARIO on C_MOVIMIENTOBANCARIO.CODIGO = C_ITEMMOVBANCARIOS.MOV and 0 = Funciones.empty( C_ITEMMOVBANCARIOS.MOV )
 left join ZooLogic.CONENTFIN as C_CONCEPTOENTIDADFINANCIERA on C_CONCEPTOENTIDADFINANCIERA.CODIGO = C_MOVIMIENTOBANCARIO.CONCEPTO and 0 = Funciones.empty( C_MOVIMIENTOBANCARIO.CONCEPTO )
 inner join ZooLogic.CONCILIACION as C_CONCILIACIONES_CABECERA on C_CONCILIACIONES_CABECERA.CODIGO = C_ITEMMOVBANCARIOS.CODIGO
 left join ZooLogic.CTABAN as C_CUENTABANCARIA_CABECERA on C_CUENTABANCARIA_CABECERA.CBCOD = C_CONCILIACIONES_CABECERA.CTABANC and 0 = Funciones.empty( C_CONCILIACIONES_CABECERA.CTABANC )
 left join ZooLogic.MONEDA as C_MONEDA_CABECERA on C_MONEDA_CABECERA.CODIGO = C_CUENTABANCARIA_CABECERA.CBMONEDA and 0 = Funciones.empty( C_CUENTABANCARIA_CABECERA.CBMONEDA )
 left join ORGANIZACION.SUC as C_SUCURSAL_CABECERA on C_SUCURSAL_CABECERA.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL_CABECERA on C_TIPOSUCURSAL_CABECERA.TCOD = C_SUCURSAL_CABECERA.TIPO and 0 = Funciones.empty( C_SUCURSAL_CABECERA.TIPO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL_CABECERA on C_LINEASUCURSAL_CABECERA.LSCOD = C_SUCURSAL_CABECERA.LINEA and 0 = Funciones.empty( C_SUCURSAL_CABECERA.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION_CABECERA on C_SEGMENTACION_CABECERA.SCOD = C_SUCURSAL_CABECERA.SEG and 0 = Funciones.empty( C_SUCURSAL_CABECERA.SEG )
 where ( not 1 = funciones.empty( c_conciliaciones_cabecera.codigo ) ) and 
	( ( @CONCILIACIONES_NUMERO_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.Numero >= @CONCILIACIONES_NUMERO_DESDE ) ) and 
	( ( @CONCILIACIONES_NUMERO_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.Numero <= @CONCILIACIONES_NUMERO_HASTA ) ) and 
	( ( @CONCILIACIONES_CUENTABANCARIA_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.CtaBanc >= @CONCILIACIONES_CUENTABANCARIA_DESDE ) ) and 
	( ( @CONCILIACIONES_CUENTABANCARIA_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.CtaBanc <= @CONCILIACIONES_CUENTABANCARIA_HASTA ) ) and 
	( ( @CUENTABANCARIA_22_CUENTABANCARIA_DESCRIPCION_DESDE is null ) OR ( C_CUENTABANCARIA_CABECERA.CBDes >= @CUENTABANCARIA_22_CUENTABANCARIA_DESCRIPCION_DESDE ) ) and 
	( ( @CUENTABANCARIA_22_CUENTABANCARIA_DESCRIPCION_HASTA is null ) OR ( C_CUENTABANCARIA_CABECERA.CBDes <= @CUENTABANCARIA_22_CUENTABANCARIA_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION_CABECERA.SDES >= @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION_CABECERA.SDES <= @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9338_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES >= @LINEASUCURSAL_9338_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9338_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES <= @LINEASUCURSAL_9338_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES >= @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES <= @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE is null ) OR ( C_MONEDA_CABECERA.Descrip >= @MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA is null ) OR ( C_MONEDA_CABECERA.Descrip <= @MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9334_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.seg >= @SUCURSAL_9334_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9334_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.seg <= @SUCURSAL_9334_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9334_LINEA_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Linea >= @SUCURSAL_9334_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9334_LINEA_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Linea <= @SUCURSAL_9334_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9334_TIPO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Tipo >= @SUCURSAL_9334_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9334_TIPO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Tipo <= @SUCURSAL_9334_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9334_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.descrip >= @SUCURSAL_9334_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9334_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.descrip <= @SUCURSAL_9334_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9334_CODIGO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.codigo >= @SUCURSAL_9334_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9334_CODIGO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.codigo <= @SUCURSAL_9334_CODIGO_HASTA ) ) and 
	( ( @CONCILIACIONES_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.BDALTAFW >= @CONCILIACIONES_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.BDALTAFW <= @CONCILIACIONES_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.BDMODIFW >= @CONCILIACIONES_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.BDMODIFW <= @CONCILIACIONES_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.ESTTRANS >= @CONCILIACIONES_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @CONCILIACIONES_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.ESTTRANS <= @CONCILIACIONES_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @CONCILIACIONES_FECHAALTAFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.FALTAFW >= @CONCILIACIONES_FECHAALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_FECHAALTAFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.FALTAFW <= @CONCILIACIONES_FECHAALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_FECHAEXPO_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.FECEXPO >= @CONCILIACIONES_FECHAEXPO_DESDE ) ) and 
	( ( @CONCILIACIONES_FECHAEXPO_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.FECEXPO <= @CONCILIACIONES_FECHAEXPO_HASTA ) ) and 
	( ( @CONCILIACIONES_FECHAIMPO_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.FECIMPO >= @CONCILIACIONES_FECHAIMPO_DESDE ) ) and 
	( ( @CONCILIACIONES_FECHAIMPO_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.FECIMPO <= @CONCILIACIONES_FECHAIMPO_HASTA ) ) and 
	( ( @CONCILIACIONES_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.FMODIFW >= @CONCILIACIONES_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.FMODIFW <= @CONCILIACIONES_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_FECHATRANSFERENCIA_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.FECTRANS >= @CONCILIACIONES_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @CONCILIACIONES_FECHATRANSFERENCIA_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.FECTRANS <= @CONCILIACIONES_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @CONCILIACIONES_HORAALTAFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.HALTAFW >= @CONCILIACIONES_HORAALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_HORAALTAFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.HALTAFW <= @CONCILIACIONES_HORAALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_HORAEXPO_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.HORAEXPO >= @CONCILIACIONES_HORAEXPO_DESDE ) ) and 
	( ( @CONCILIACIONES_HORAEXPO_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.HORAEXPO <= @CONCILIACIONES_HORAEXPO_HASTA ) ) and 
	( ( @CONCILIACIONES_HORAIMPO_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.HORAIMPO >= @CONCILIACIONES_HORAIMPO_DESDE ) ) and 
	( ( @CONCILIACIONES_HORAIMPO_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.HORAIMPO <= @CONCILIACIONES_HORAIMPO_HASTA ) ) and 
	( ( @CONCILIACIONES_HORAMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.HMODIFW >= @CONCILIACIONES_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_HORAMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.HMODIFW <= @CONCILIACIONES_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_SERIEALTAFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.SALTAFW >= @CONCILIACIONES_SERIEALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_SERIEALTAFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.SALTAFW <= @CONCILIACIONES_SERIEALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.SMODIFW >= @CONCILIACIONES_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.SMODIFW <= @CONCILIACIONES_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_USUARIOALTAFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.UALTAFW >= @CONCILIACIONES_USUARIOALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_USUARIOALTAFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.UALTAFW <= @CONCILIACIONES_USUARIOALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.UMODIFW >= @CONCILIACIONES_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.UMODIFW <= @CONCILIACIONES_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_VERSIONALTAFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.VALTAFW >= @CONCILIACIONES_VERSIONALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_VERSIONALTAFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.VALTAFW <= @CONCILIACIONES_VERSIONALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES_CABECERA.VMODIFW >= @CONCILIACIONES_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES_CABECERA.VMODIFW <= @CONCILIACIONES_VERSIONMODIFICACIONFW_HASTA ) ) and 
	( ( @CUENTABANCARIA_22_NUMERO_DESDE is null ) OR ( C_CUENTABANCARIA_CABECERA.CBNum >= @CUENTABANCARIA_22_NUMERO_DESDE ) ) and 
	( ( @CUENTABANCARIA_22_NUMERO_HASTA is null ) OR ( C_CUENTABANCARIA_CABECERA.CBNum <= @CUENTABANCARIA_22_NUMERO_HASTA ) ) and 
	( ( @CUENTABANCARIA_22_MONEDACUENTA_DESDE is null ) OR ( C_CUENTABANCARIA_CABECERA.CBMoneda >= @CUENTABANCARIA_22_MONEDACUENTA_DESDE ) ) and 
	( ( @CUENTABANCARIA_22_MONEDACUENTA_HASTA is null ) OR ( C_CUENTABANCARIA_CABECERA.CBMoneda <= @CUENTABANCARIA_22_MONEDACUENTA_HASTA ) ) and 
	( ( @CONCEPTOENTIDADFINANCIERA_9200_CONCEPTO_CONCEPTO_DESDE is null ) OR ( C_CONCEPTOENTIDADFINANCIERA.Concepto >= @CONCEPTOENTIDADFINANCIERA_9200_CONCEPTO_CONCEPTO_DESDE ) ) and 
	( ( @CONCEPTOENTIDADFINANCIERA_9200_CONCEPTO_CONCEPTO_HASTA is null ) OR ( C_CONCEPTOENTIDADFINANCIERA.Concepto <= @CONCEPTOENTIDADFINANCIERA_9200_CONCEPTO_CONCEPTO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_FECHA_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Fecha >= @MOVIMIENTOBANCARIO_24_FECHA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_FECHA_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Fecha <= @MOVIMIENTOBANCARIO_24_FECHA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_NUMERO_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Numero >= @MOVIMIENTOBANCARIO_24_NUMERO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_NUMERO_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Numero <= @MOVIMIENTOBANCARIO_24_NUMERO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_IMPORTE_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Importe >= @MOVIMIENTOBANCARIO_24_IMPORTE_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_IMPORTE_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Importe <= @MOVIMIENTOBANCARIO_24_IMPORTE_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_CONCEPTO_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Concepto >= @MOVIMIENTOBANCARIO_24_CONCEPTO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_24_CONCEPTO_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Concepto <= @MOVIMIENTOBANCARIO_24_CONCEPTO_HASTA ) )

)