IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_SENIA_SENIA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_SENIA_SENIA];
GO;

CREATE FUNCTION [Listados].[GENERICO_SENIA_SENIA]
( @BaseDeDatos varchar(8),
	@SENIA_LETRAORIGEN_DESDE varchar(1),
	@SENIA_LETRAORIGEN_HASTA varchar(1),
	@SENIA_PUNTODEVENTAORIGEN_DESDE numeric(4, 0),
	@SENIA_PUNTODEVENTAORIGEN_HASTA numeric(4, 0),
	@SENIA_NUMEROORIGEN_DESDE numeric(8, 0),
	@SENIA_NUMEROORIGEN_HASTA numeric(8, 0),
	@SENIA_FECHAORIGEN_DESDE datetime,
	@SENIA_FECHAORIGEN_HASTA datetime,
	@SENIA_CSERIEORIGEN_DESDE varchar(10),
	@SENIA_CSERIEORIGEN_HASTA varchar(10),
	@SENIA_CVERSIONORIGEN_DESDE varchar(13),
	@SENIA_CVERSIONORIGEN_HASTA varchar(13),
	@SENIA_CBASEDEDATOSORIGEN_DESDE varchar(8),
	@SENIA_CBASEDEDATOSORIGEN_HASTA varchar(8),
	@SENIA_CLIENTE_DESDE varchar(10),
	@SENIA_CLIENTE_HASTA varchar(10),
	@SENIA_FECHAVENCIMIENTO_DESDE datetime,
	@SENIA_FECHAVENCIMIENTO_HASTA datetime,
	@SENIA_PRECIO_DESDE numeric(15, 2),
	@SENIA_PRECIO_HASTA numeric(15, 2),
	@SENIA_MONEDA_DESDE varchar(10),
	@SENIA_MONEDA_HASTA varchar(10),
	@SENIA_LETRAAFECTANTE_DESDE varchar(1),
	@SENIA_LETRAAFECTANTE_HASTA varchar(1),
	@SENIA_PUNTODEVENTAAFECTANTE_DESDE numeric(4, 0),
	@SENIA_PUNTODEVENTAAFECTANTE_HASTA numeric(4, 0),
	@SENIA_NUMEROAFECTANTE_DESDE numeric(8, 0),
	@SENIA_NUMEROAFECTANTE_HASTA numeric(8, 0),
	@SENIA_FECHAAFECTANTE_DESDE datetime,
	@SENIA_FECHAAFECTANTE_HASTA datetime,
	@SENIA_CSERIEAFECTANTE_DESDE varchar(10),
	@SENIA_CSERIEAFECTANTE_HASTA varchar(10),
	@SENIA_CVERSIONAFECTANTE_DESDE varchar(13),
	@SENIA_CVERSIONAFECTANTE_HASTA varchar(13),
	@SENIA_CBASEDEDATOSAFECTANTE_DESDE varchar(8),
	@SENIA_CBASEDEDATOSAFECTANTE_HASTA varchar(8),
	@SENIA_COMPROBANTEORIGEN_DESDE varchar(38),
	@SENIA_COMPROBANTEORIGEN_HASTA varchar(38),
	@CLIENTE_28_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_28_CLIENTE_NOMBRE_HASTA varchar(185),
	@MONEDA_86_MONEDA_DESCRIPCION_DESDE varchar(40),
	@MONEDA_86_MONEDA_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_29_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_29_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_44_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_44_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_46_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_46_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_52_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_52_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_53_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_53_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_56_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_56_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_57_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_57_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_63_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_63_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_64_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_64_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_65_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_65_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_66_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_66_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_68_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_68_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_71_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_71_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_80_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_80_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@MONEDA_9006_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_9006_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_9144_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9144_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9144_LINEA_DESDE varchar(10),
	@SUCURSAL_9144_LINEA_HASTA varchar(10),
	@SUCURSAL_9144_TIPO_DESDE varchar(10),
	@SUCURSAL_9144_TIPO_HASTA varchar(10),
	@SUCURSAL_9144_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9144_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_28_VENDEDOR_DESDE varchar(10),
	@CLIENTE_28_VENDEDOR_HASTA varchar(10),
	@CLIENTE_28_CALLE_DESDE varchar(250),
	@CLIENTE_28_CALLE_HASTA varchar(250),
	@CLIENTE_28_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_28_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_28_CUIT_DESDE varchar(15),
	@CLIENTE_28_CUIT_HASTA varchar(15),
	@CLIENTE_28_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_28_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_28_EMAIL_DESDE varchar(250),
	@CLIENTE_28_EMAIL_HASTA varchar(250),
	@CLIENTE_28_FAX_DESDE varchar(20),
	@CLIENTE_28_FAX_HASTA varchar(20),
	@CLIENTE_28_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_28_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_28_IMAGEN_DESDE varchar(180),
	@CLIENTE_28_IMAGEN_HASTA varchar(180),
	@CLIENTE_28_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_28_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_28_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_28_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_28_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_28_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_28_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_28_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_28_PAIS_DESDE varchar(3),
	@CLIENTE_28_PAIS_HASTA varchar(3),
	@CLIENTE_28_PISO_DESDE varchar(3),
	@CLIENTE_28_PISO_HASTA varchar(3),
	@CLIENTE_28_PROVINCIA_DESDE varchar(2),
	@CLIENTE_28_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_47_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_28_TELEFONO_DESDE varchar(30),
	@CLIENTE_28_TELEFONO_HASTA varchar(30),
	@CLIENTE_28_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_28_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_28_MOVIL_DESDE varchar(30),
	@CLIENTE_28_MOVIL_HASTA varchar(30),
	@CLIENTE_28_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_28_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_28_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_28_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_28_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_28_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_28_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_28_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_28_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_28_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_28_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_28_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_28_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_28_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_28_ESTADOCIVIL varchar(13),
	@CLIENTE_28_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_28_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_28_SEXO varchar(10),
	@CLIENTE_28_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_28_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_28_RUT_DESDE varchar(12),
	@CLIENTE_28_RUT_HASTA varchar(12),
	@CLIENTE_28_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_28_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_28_TIPOCLI_DESDE varchar(10),
	@CLIENTE_28_TIPOCLI_HASTA varchar(10),
	@CLIENTE_28_CATEGCLI_DESDE varchar(10),
	@CLIENTE_28_CATEGCLI_HASTA varchar(10),
	@CLIENTE_28_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_28_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_28_SUJETOVINCULADO bit,
	@CLIENTE_28_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_28_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_28_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_28_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_28_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_28_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_28_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_28_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_28_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_28_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_28_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_28_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_28_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_28_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_28_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_28_APELLIDO_DESDE varchar(60),
	@CLIENTE_28_APELLIDO_HASTA varchar(60),
	@CLIENTE_28_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_28_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_28_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_28_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_28_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_28_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_28_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_28_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_28_TASACEROAPLICA bit,
	@CLIENTE_28_INACTIVOFW bit,
	@SUCURSAL_9144_CODIGO_DESDE varchar(10),
	@SUCURSAL_9144_CODIGO_HASTA varchar(10),
	@SENIA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@SENIA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@SENIA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@SENIA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@SENIA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@SENIA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@SENIA_FECHAALTAFW_DESDE datetime,
	@SENIA_FECHAALTAFW_HASTA datetime,
	@SENIA_FECHAEXPO_DESDE datetime,
	@SENIA_FECHAEXPO_HASTA datetime,
	@SENIA_FECHAIMPO_DESDE datetime,
	@SENIA_FECHAIMPO_HASTA datetime,
	@SENIA_FECHAMODIFICACIONFW_DESDE datetime,
	@SENIA_FECHAMODIFICACIONFW_HASTA datetime,
	@SENIA_FECHATRANSFERENCIA_DESDE datetime,
	@SENIA_FECHATRANSFERENCIA_HASTA datetime,
	@SENIA_HORAALTAFW_DESDE varchar(8),
	@SENIA_HORAALTAFW_HASTA varchar(8),
	@SENIA_HORAEXPO_DESDE varchar(8),
	@SENIA_HORAEXPO_HASTA varchar(8),
	@SENIA_HORAIMPO_DESDE varchar(8),
	@SENIA_HORAIMPO_HASTA varchar(8),
	@SENIA_HORAMODIFICACIONFW_DESDE varchar(8),
	@SENIA_HORAMODIFICACIONFW_HASTA varchar(8),
	@SENIA_SERIEALTAFW_DESDE varchar(7),
	@SENIA_SERIEALTAFW_HASTA varchar(7),
	@SENIA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@SENIA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@SENIA_USUARIOALTAFW_DESDE varchar(100),
	@SENIA_USUARIOALTAFW_HASTA varchar(100),
	@SENIA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@SENIA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@SENIA_VERSIONALTAFW_DESDE varchar(13),
	@SENIA_VERSIONALTAFW_HASTA varchar(13),
	@SENIA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@SENIA_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@FACTURA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURA_1_MONEDACOMPROBANTE_HASTA varchar(10) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_senia.codigo, 38, ' ' ) as varchar( 46 ) ) as SENIA__Grupo,
	@basededatos as SENIA__BD,
	C_FACTURA.COTIZ as FACTURA_Cotiz,
	c_SENIA.CODIGO as SENIA_Codigo,
	c_SENIA.FLETRA as SENIA_FLETRA,
	c_SENIA.FPTOVEN as SENIA_FPTOVEN,
	c_SENIA.FNUMCOMP as SENIA_FNUMCOMP,
	case when c_senia.fecha = '01/01/1900 00:00:00' then null else c_senia.fecha end as SENIA_Fecha,
	c_SENIA.CSERIE as SENIA_CSERIE,
	c_SENIA.CVERSION as SENIA_CVERSION,
	c_SENIA.CBASEDEDAT as SENIA_cBaseDeDat,
	c_SENIA.CLIENTE as SENIA_Cliente,
	C_CLIENTE.CIMAGEN as CLIENTE_CIMAGEN,
	case when c_senia.fechavenci = '01/01/1900 00:00:00' then null else c_senia.fechavenci end as SENIA_FechaVenci,
	c_SENIA.FPRECIO as SENIA_FPRECIO,
	c_SENIA.MONEDA as SENIA_moneda,
	c_SENIA.FLETRAA as SENIA_FLETRAA,
	c_SENIA.FPTOVENA as SENIA_FPTOVENA,
	c_SENIA.FNUMCOMPA as SENIA_FNUMCOMPA,
	case when c_senia.fechaa = '01/01/1900 00:00:00' then null else c_senia.fechaa end as SENIA_FechaA,
	c_SENIA.CSERIEA as SENIA_CSERIEA,
	c_SENIA.CVERSIONA as SENIA_CVERSIONA,
	c_SENIA.CBDEDATA as SENIA_cBDeDatA,
	c_SENIA.OBS as SENIA_Obs,
	c_SENIA.COMP as SENIA_Comp,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CLIENTE.CLVEND as CLIENTE_CLVend,
	C_CLIENTE.CLCALLE as CLIENTE_CLCalle,
	C_CLIENTE.CLCP as CLIENTE_CLCP,
	C_CLIENTE.CLCUIT as CLIENTE_CLCUIT,
	C_CLIENTE.CLDEPTO as CLIENTE_CLDEPTO,
	C_CLIENTE.CLEMAIL as CLIENTE_CLEMAIL,
	C_CLIENTE.CLFAX as CLIENTE_CLFAX,
	case when c_cliente.clfecha = '01/01/1900 00:00:00' then null else c_cliente.clfecha end as CLIENTE_CLFECHA,
	C_CLIENTE.CLLOC as CLIENTE_CLLOC,
	C_CLIENTE.CLNRODOC as CLIENTE_CLNRODOC,
	C_CLIENTE.CLNRO as CLIENTE_CLNro,
	C_CLIENTE.CLOBS as CLIENTE_CLOBS,
	C_CLIENTE.CLPAGEWEB as CLIENTE_CLPAGEWEB,
	C_CLIENTE.CLPAIS as CLIENTE_CLPAIS,
	C_CLIENTE.CLPISO as CLIENTE_ClPiso,
	C_CLIENTE.CLPRV as CLIENTE_CLPRV,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_CLIENTE.CLTLF as CLIENTE_CLTLF,
	C_CLIENTE.CLTIPODOC as CLIENTE_CLTIPODOC,
	C_CLIENTE.CLMOVIL as CLIENTE_CLMovil,
	C_CLIENTE.CLTOPECCTE as CLIENTE_CLTOPECCTE,
	C_CLIENTE.CLLISPREC as CLIENTE_CLLisPrec,
	C_CLIENTE.CLCLAS as CLIENTE_CLCLAS,
	C_CLIENTE.CLTIPCONV as CLIENTE_CLTIPCONV,
	C_CLIENTE.CLNROIIBB as CLIENTE_CLNROIIBB,
	C_CLIENTE.CLCO_DTO as CLIENTE_CLCO_DTO,
	C_CLIENTE.CLTRANS as CLIENTE_CLTRANS,
	C_CLIENTE.ESTADO as CLIENTE_Estado,
	C_CLIENTE.HIJOS as CLIENTE_Hijos,
	C_CLIENTE.SEXO as CLIENTE_Sexo,
	C_CLIENTE.GLOBALID as CLIENTE_globalid,
	C_CLIENTE.RUT as CLIENTE_RUT,
	C_CLIENTE.CLCODFANT as CLIENTE_CLCODFANT,
	C_CLIENTE.CLTIPOCLI as CLIENTE_CLTipoCli,
	C_CLIENTE.CLCATEGCLI as CLIENTE_CLCategCli,
	C_CLIENTE.CLCONDPAG as CLIENTE_CLCONDPAG,
	C_CLIENTE.CLSUJVINC as CLIENTE_CLSujVinc,
	C_CLIENTE.CLPERTIVA as CLIENTE_CLPERTIVA,
	C_CLIENTE.CLSITGAN as CLIENTE_CLSITGAN,
	C_CLIENTE.EXPERIVA as CLIENTE_EXPERIVA,
	C_CLIENTE.CLPERGAN as CLIENTE_CLPERGAN,
	C_CLIENTE.EXPERGAN as CLIENTE_EXPERGAN,
	C_CLIENTE.CODRECOM as CLIENTE_CODRECOM,
	C_CLIENTE.NOMRECOM as CLIENTE_NOMRECOM,
	C_CLIENTE.CLPRINOM as CLIENTE_CLPRINOM,
	C_CLIENTE.CLSEGNOM as CLIENTE_CLSEGNOM,
	C_CLIENTE.CLAPELL as CLIENTE_CLAPELL,
	case when c_cliente.vhastaiva = '01/01/1900 00:00:00' then null else c_cliente.vhastaiva end as CLIENTE_VHastaIva,
	case when c_cliente.vhastagan = '01/01/1900 00:00:00' then null else c_cliente.vhastagan end as CLIENTE_VHastaGan,
	C_CLIENTE.CLSIPRIB as CLIENTE_CLSIPRIB,
	C_CLIENTE.PORCENTC as CLIENTE_PorcenTC,
	C_CLIENTE.APLICATC as CLIENTE_AplicaTC,
	C_CLIENTE.INACTIVOFW as CLIENTE_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_SENIA.BDALTAFW as SENIA_BDALTAFW,
	c_SENIA.BDMODIFW as SENIA_BDMODIFW,
	c_SENIA.ESTTRANS as SENIA_ESTTRANS,
	case when c_senia.faltafw = '01/01/1900 00:00:00' then null else c_senia.faltafw end as SENIA_FALTAFW,
	case when c_senia.fecexpo = '01/01/1900 00:00:00' then null else c_senia.fecexpo end as SENIA_FECEXPO,
	case when c_senia.fecimpo = '01/01/1900 00:00:00' then null else c_senia.fecimpo end as SENIA_FECIMPO,
	case when c_senia.fmodifw = '01/01/1900 00:00:00' then null else c_senia.fmodifw end as SENIA_FMODIFW,
	case when c_senia.fectrans = '01/01/1900 00:00:00' then null else c_senia.fectrans end as SENIA_FECTRANS,
	c_SENIA.HALTAFW as SENIA_HALTAFW,
	c_SENIA.HORAEXPO as SENIA_HORAEXPO,
	c_SENIA.HORAIMPO as SENIA_HORAIMPO,
	c_SENIA.HMODIFW as SENIA_HMODIFW,
	c_SENIA.SALTAFW as SENIA_SALTAFW,
	c_SENIA.SMODIFW as SENIA_SMODIFW,
	c_SENIA.UALTAFW as SENIA_UALTAFW,
	c_SENIA.UMODIFW as SENIA_UMODIFW,
	c_SENIA.VALTAFW as SENIA_VALTAFW,
	c_SENIA.VMODIFW as SENIA_VMODIFW,
	c_SENIA.ZADSFW as SENIA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as SENIA__SUCURSAL,
	cast( funciones.identificadordecomprobanteparalistado(c_senia.facttipo, c_senia.fletra, c_senia.fptoven, c_senia.fnumcomp) as varchar( 20 ) ) as SENIA_ComprobanteVirtualOrigina,
	cast( funciones.identificadordecomprobanteparalistado(c_senia.facttipoa, c_senia.fletraa, c_senia.fptovena, c_senia.fnumcompa) as varchar( 20 ) ) as SENIA_ComprobanteVirtualCancela,
	C_FACTURA.MONEDA as FACTURA_Moneda,
	cast( c_senia.prunconimp*case when c_factura.cotiz = 0 then 1 else c_factura.cotiz end as numeric( 15, 2 ) ) as SENIA_MontoVirtual,
	C_CLIENTE.CLNOM as CLIENTE_CLNOM,
	C_MONEDA86.DESCRIP as MONEDA86_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_VENDEDOR.CLNOM as VENDEDOR_CLNOM,
	C_PAISES.PDES as PAISES_pdes,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_CLIENTE.CLIVA as CLIENTE_CLIVA,
	C_LISTADEPRECIOS.LPR_NOMBRE as LISTADEPRECIOS_LPR_NOMBRE,
	C_CLASIFICACIONCLIENTE.CLADES as CLASIFICACIONCLIENTE_CLADES,
	C_DESCUENTO.DES as DESCUENTO_Des,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_NOMBREDEFANTASIA.NFCOD as NOMBREDEFANTASIA_NFCOD,
	C_TIPOCLIENTE.TCDES as TIPOCLIENTE_TCDES,
	C_CATEGORIACLIENTE.CGDES as CATEGORIACLIENTE_CGDes,
	C_CONDICIONDEPAGO.CLNOM as CONDICIONDEPAGO_CLNOM,
	C_IMPUESTO68.DESCRIP as IMPUESTO68_descrip,
	C_IMPUESTO71.DESCRIP as IMPUESTO71_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_MONEDA9006.DESCRIP as MONEDA9006_Descrip,
	C_CATEGORIACLIENTE.CGCOD as CATEGORIACLIENTE_CGCod,
	C_CLASIFICACIONCLIENTE.CLACOD as CLASIFICACIONCLIENTE_CLACOD,
	C_CLIENTE.CLCOD as CLIENTE_CLCOD,
	C_CONDICIONDEPAGO.CLCOD as CONDICIONDEPAGO_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DESCUENTO.CODIGO as DESCUENTO_codigo,
	C_FACTURA.CODIGO as FACTURA_CODIGO,
	C_IMPUESTO68.CODIGO as IMPUESTO68_codigo,
	C_IMPUESTO71.CODIGO as IMPUESTO71_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS.LPR_NUMERO as LISTADEPRECIOS_LPR_NUMERO,
	C_MONEDA86.CODIGO as MONEDA86_Codigo,
	C_MONEDA9006.CODIGO as MONEDA9006_Codigo,
	C_PAISES.PCOD as PAISES_pcod,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOCLIENTE.TCCOD as TIPOCLIENTE_TCCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_VENDEDOR.CLCOD as VENDEDOR_CLCOD
 from ZooLogic.SENIA as c_SENIA
 left join ZooLogic.CLI as C_CLIENTE on C_CLIENTE.CLCOD = C_SENIA.CLIENTE and 0 = Funciones.empty( C_SENIA.CLIENTE )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO on C_CONDICIONDEPAGO.CLCOD = C_CLIENTE.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_CLIENTE.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO on C_DESCUENTO.CODIGO = C_CLIENTE.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE.CLCO_DTO )
 left join ZooLogic.COMPROBANTEV as C_FACTURA on C_FACTURA.CODIGO = C_SENIA.COMP and 0 = Funciones.empty( C_SENIA.COMP )
 left join ZooLogic.IMPUESTO as C_IMPUESTO68 on C_IMPUESTO68.CODIGO = C_CLIENTE.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO71 on C_IMPUESTO71.CODIGO = C_CLIENTE.CLPERGAN and 0 = Funciones.empty( C_CLIENTE.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS on C_LISTADEPRECIOS.LPR_NUMERO = C_CLIENTE.CLLISPREC and 0 = Funciones.empty( C_CLIENTE.CLLISPREC )
 left join ZooLogic.MONEDA as C_MONEDA86 on C_MONEDA86.CODIGO = C_SENIA.MONEDA and 0 = Funciones.empty( C_SENIA.MONEDA )
 left join ZooLogic.MONEDA as C_MONEDA9006 on C_MONEDA9006.CODIGO = C_FACTURA.MONEDA and 0 = Funciones.empty( C_FACTURA.MONEDA )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_CLIENTE.CLPAIS and 0 = Funciones.empty( C_CLIENTE.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_CLIENTE.CLPRV and 0 = Funciones.empty( C_CLIENTE.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_CLIENTE.CLIVA and 0 = Funciones.empty( C_CLIENTE.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE on C_TIPOCLIENTE.TCCOD = C_CLIENTE.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_CLIENTE.CLTRANS and 0 = Funciones.empty( C_CLIENTE.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR on C_VENDEDOR.CLCOD = C_CLIENTE.CLVEND and 0 = Funciones.empty( C_CLIENTE.CLVEND )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA on C_NOMBREDEFANTASIA.NFCOD = C_CLIENTE.CLCODFANT and 0 = Funciones.empty( C_CLIENTE.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE on C_CATEGORIACLIENTE.CGCOD = C_CLIENTE.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE on C_CLASIFICACIONCLIENTE.CLACOD = C_CLIENTE.CLCLAS and 0 = Funciones.empty( C_CLIENTE.CLCLAS )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( not 1 = funciones.empty( c_senia.codigo ) ) and 
	( ( @SENIA_LETRAORIGEN_DESDE is null ) OR ( c_SENIA.FLETRA >= @SENIA_LETRAORIGEN_DESDE ) ) and 
	( ( @SENIA_LETRAORIGEN_HASTA is null ) OR ( c_SENIA.FLETRA <= @SENIA_LETRAORIGEN_HASTA ) ) and 
	( ( @SENIA_PUNTODEVENTAORIGEN_DESDE is null ) OR ( c_SENIA.FPTOVEN >= @SENIA_PUNTODEVENTAORIGEN_DESDE ) ) and 
	( ( @SENIA_PUNTODEVENTAORIGEN_HASTA is null ) OR ( c_SENIA.FPTOVEN <= @SENIA_PUNTODEVENTAORIGEN_HASTA ) ) and 
	( ( @SENIA_NUMEROORIGEN_DESDE is null ) OR ( c_SENIA.FNUMCOMP >= @SENIA_NUMEROORIGEN_DESDE ) ) and 
	( ( @SENIA_NUMEROORIGEN_HASTA is null ) OR ( c_SENIA.FNUMCOMP <= @SENIA_NUMEROORIGEN_HASTA ) ) and 
	( ( @SENIA_FECHAORIGEN_DESDE is null ) OR ( c_SENIA.Fecha >= @SENIA_FECHAORIGEN_DESDE ) ) and 
	( ( @SENIA_FECHAORIGEN_HASTA is null ) OR ( c_SENIA.Fecha <= @SENIA_FECHAORIGEN_HASTA ) ) and 
	( ( @SENIA_CSERIEORIGEN_DESDE is null ) OR ( c_SENIA.CSERIE >= @SENIA_CSERIEORIGEN_DESDE ) ) and 
	( ( @SENIA_CSERIEORIGEN_HASTA is null ) OR ( c_SENIA.CSERIE <= @SENIA_CSERIEORIGEN_HASTA ) ) and 
	( ( @SENIA_CVERSIONORIGEN_DESDE is null ) OR ( c_SENIA.CVERSION >= @SENIA_CVERSIONORIGEN_DESDE ) ) and 
	( ( @SENIA_CVERSIONORIGEN_HASTA is null ) OR ( c_SENIA.CVERSION <= @SENIA_CVERSIONORIGEN_HASTA ) ) and 
	( ( @SENIA_CBASEDEDATOSORIGEN_DESDE is null ) OR ( c_SENIA.cBaseDeDat >= @SENIA_CBASEDEDATOSORIGEN_DESDE ) ) and 
	( ( @SENIA_CBASEDEDATOSORIGEN_HASTA is null ) OR ( c_SENIA.cBaseDeDat <= @SENIA_CBASEDEDATOSORIGEN_HASTA ) ) and 
	( ( @SENIA_CLIENTE_DESDE is null ) OR ( c_SENIA.Cliente >= @SENIA_CLIENTE_DESDE ) ) and 
	( ( @SENIA_CLIENTE_HASTA is null ) OR ( c_SENIA.Cliente <= @SENIA_CLIENTE_HASTA ) ) and 
	( ( @SENIA_FECHAVENCIMIENTO_DESDE is null ) OR ( c_SENIA.FechaVenci >= @SENIA_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @SENIA_FECHAVENCIMIENTO_HASTA is null ) OR ( c_SENIA.FechaVenci <= @SENIA_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @SENIA_PRECIO_DESDE is null ) OR ( c_SENIA.FPRECIO >= @SENIA_PRECIO_DESDE ) ) and 
	( ( @SENIA_PRECIO_HASTA is null ) OR ( c_SENIA.FPRECIO <= @SENIA_PRECIO_HASTA ) ) and 
	( ( @SENIA_MONEDA_DESDE is null ) OR ( c_SENIA.moneda >= @SENIA_MONEDA_DESDE ) ) and 
	( ( @SENIA_MONEDA_HASTA is null ) OR ( c_SENIA.moneda <= @SENIA_MONEDA_HASTA ) ) and 
	( ( @SENIA_LETRAAFECTANTE_DESDE is null ) OR ( c_SENIA.FLETRAA >= @SENIA_LETRAAFECTANTE_DESDE ) ) and 
	( ( @SENIA_LETRAAFECTANTE_HASTA is null ) OR ( c_SENIA.FLETRAA <= @SENIA_LETRAAFECTANTE_HASTA ) ) and 
	( ( @SENIA_PUNTODEVENTAAFECTANTE_DESDE is null ) OR ( c_SENIA.FPTOVENA >= @SENIA_PUNTODEVENTAAFECTANTE_DESDE ) ) and 
	( ( @SENIA_PUNTODEVENTAAFECTANTE_HASTA is null ) OR ( c_SENIA.FPTOVENA <= @SENIA_PUNTODEVENTAAFECTANTE_HASTA ) ) and 
	( ( @SENIA_NUMEROAFECTANTE_DESDE is null ) OR ( c_SENIA.FNUMCOMPA >= @SENIA_NUMEROAFECTANTE_DESDE ) ) and 
	( ( @SENIA_NUMEROAFECTANTE_HASTA is null ) OR ( c_SENIA.FNUMCOMPA <= @SENIA_NUMEROAFECTANTE_HASTA ) ) and 
	( ( @SENIA_FECHAAFECTANTE_DESDE is null ) OR ( c_SENIA.FechaA >= @SENIA_FECHAAFECTANTE_DESDE ) ) and 
	( ( @SENIA_FECHAAFECTANTE_HASTA is null ) OR ( c_SENIA.FechaA <= @SENIA_FECHAAFECTANTE_HASTA ) ) and 
	( ( @SENIA_CSERIEAFECTANTE_DESDE is null ) OR ( c_SENIA.CSERIEA >= @SENIA_CSERIEAFECTANTE_DESDE ) ) and 
	( ( @SENIA_CSERIEAFECTANTE_HASTA is null ) OR ( c_SENIA.CSERIEA <= @SENIA_CSERIEAFECTANTE_HASTA ) ) and 
	( ( @SENIA_CVERSIONAFECTANTE_DESDE is null ) OR ( c_SENIA.CVERSIONA >= @SENIA_CVERSIONAFECTANTE_DESDE ) ) and 
	( ( @SENIA_CVERSIONAFECTANTE_HASTA is null ) OR ( c_SENIA.CVERSIONA <= @SENIA_CVERSIONAFECTANTE_HASTA ) ) and 
	( ( @SENIA_CBASEDEDATOSAFECTANTE_DESDE is null ) OR ( c_SENIA.cBDeDatA >= @SENIA_CBASEDEDATOSAFECTANTE_DESDE ) ) and 
	( ( @SENIA_CBASEDEDATOSAFECTANTE_HASTA is null ) OR ( c_SENIA.cBDeDatA <= @SENIA_CBASEDEDATOSAFECTANTE_HASTA ) ) and 
	( ( @SENIA_COMPROBANTEORIGEN_DESDE is null ) OR ( c_SENIA.Comp >= @SENIA_COMPROBANTEORIGEN_DESDE ) ) and 
	( ( @SENIA_COMPROBANTEORIGEN_HASTA is null ) OR ( c_SENIA.Comp <= @SENIA_COMPROBANTEORIGEN_HASTA ) ) and 
	( ( @CLIENTE_28_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE.CLNOM >= @CLIENTE_28_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_28_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE.CLNOM <= @CLIENTE_28_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @MONEDA_86_MONEDA_DESCRIPCION_DESDE is null ) OR ( C_MONEDA86.Descrip >= @MONEDA_86_MONEDA_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_86_MONEDA_DESCRIPCION_HASTA is null ) OR ( C_MONEDA86.Descrip <= @MONEDA_86_MONEDA_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_29_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR.CLNOM >= @VENDEDOR_29_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_29_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR.CLNOM <= @VENDEDOR_29_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_44_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_44_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_44_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_44_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_46_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_46_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_46_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_46_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_52_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE >= @LISTADEPRECIOS_52_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_52_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE <= @LISTADEPRECIOS_52_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_53_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES >= @CLASIFICACIONCLIENTE_53_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_53_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES <= @CLASIFICACIONCLIENTE_53_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_56_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO.Des >= @DESCUENTO_56_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_56_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO.Des <= @DESCUENTO_56_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_57_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_57_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_57_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_57_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_63_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA.NFCOD >= @NOMBREDEFANTASIA_63_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_63_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA.NFCOD <= @NOMBREDEFANTASIA_63_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_64_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE.TCDES >= @TIPOCLIENTE_64_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_64_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE.TCDES <= @TIPOCLIENTE_64_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_65_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE.CGDes >= @CATEGORIACLIENTE_65_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_65_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE.CGDes <= @CATEGORIACLIENTE_65_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_66_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO.CLNOM >= @CONDICIONDEPAGO_66_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_66_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO.CLNOM <= @CONDICIONDEPAGO_66_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_68_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO68.descrip >= @IMPUESTO_68_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_68_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO68.descrip <= @IMPUESTO_68_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_71_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO71.descrip >= @IMPUESTO_71_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_71_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO71.descrip <= @IMPUESTO_71_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_80_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_80_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_80_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_80_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_9006_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA9006.Descrip >= @MONEDA_9006_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_9006_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA9006.Descrip <= @MONEDA_9006_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9144_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9144_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9144_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9144_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9144_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9144_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9144_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9144_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9144_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9144_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9144_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9144_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_28_VENDEDOR_DESDE is null ) OR ( C_CLIENTE.CLVend >= @CLIENTE_28_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_28_VENDEDOR_HASTA is null ) OR ( C_CLIENTE.CLVend <= @CLIENTE_28_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_28_CALLE_DESDE is null ) OR ( C_CLIENTE.CLCalle >= @CLIENTE_28_CALLE_DESDE ) ) and 
	( ( @CLIENTE_28_CALLE_HASTA is null ) OR ( C_CLIENTE.CLCalle <= @CLIENTE_28_CALLE_HASTA ) ) and 
	( ( @CLIENTE_28_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE.CLCP >= @CLIENTE_28_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_28_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE.CLCP <= @CLIENTE_28_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_28_CUIT_DESDE is null ) OR ( C_CLIENTE.CLCUIT >= @CLIENTE_28_CUIT_DESDE ) ) and 
	( ( @CLIENTE_28_CUIT_HASTA is null ) OR ( C_CLIENTE.CLCUIT <= @CLIENTE_28_CUIT_HASTA ) ) and 
	( ( @CLIENTE_28_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE.CLDEPTO >= @CLIENTE_28_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_28_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE.CLDEPTO <= @CLIENTE_28_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_28_EMAIL_DESDE is null ) OR ( C_CLIENTE.CLEMAIL >= @CLIENTE_28_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_28_EMAIL_HASTA is null ) OR ( C_CLIENTE.CLEMAIL <= @CLIENTE_28_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_28_FAX_DESDE is null ) OR ( C_CLIENTE.CLFAX >= @CLIENTE_28_FAX_DESDE ) ) and 
	( ( @CLIENTE_28_FAX_HASTA is null ) OR ( C_CLIENTE.CLFAX <= @CLIENTE_28_FAX_HASTA ) ) and 
	( ( @CLIENTE_28_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE.CLFECHA >= @CLIENTE_28_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_28_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE.CLFECHA <= @CLIENTE_28_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_28_IMAGEN_DESDE is null ) OR ( C_CLIENTE.CIMAGEN >= @CLIENTE_28_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_28_IMAGEN_HASTA is null ) OR ( C_CLIENTE.CIMAGEN <= @CLIENTE_28_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_28_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE.CLLOC >= @CLIENTE_28_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_28_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE.CLLOC <= @CLIENTE_28_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_28_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLNRODOC >= @CLIENTE_28_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_28_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLNRODOC <= @CLIENTE_28_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_28_NUMERO_DESDE is null ) OR ( C_CLIENTE.CLNro >= @CLIENTE_28_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_28_NUMERO_HASTA is null ) OR ( C_CLIENTE.CLNro <= @CLIENTE_28_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_28_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE.CLPAGEWEB >= @CLIENTE_28_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_28_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE.CLPAGEWEB <= @CLIENTE_28_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_28_PAIS_DESDE is null ) OR ( C_CLIENTE.CLPAIS >= @CLIENTE_28_PAIS_DESDE ) ) and 
	( ( @CLIENTE_28_PAIS_HASTA is null ) OR ( C_CLIENTE.CLPAIS <= @CLIENTE_28_PAIS_HASTA ) ) and 
	( ( @CLIENTE_28_PISO_DESDE is null ) OR ( C_CLIENTE.ClPiso >= @CLIENTE_28_PISO_DESDE ) ) and 
	( ( @CLIENTE_28_PISO_HASTA is null ) OR ( C_CLIENTE.ClPiso <= @CLIENTE_28_PISO_HASTA ) ) and 
	( ( @CLIENTE_28_PROVINCIA_DESDE is null ) OR ( C_CLIENTE.CLPRV >= @CLIENTE_28_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_28_PROVINCIA_HASTA is null ) OR ( C_CLIENTE.CLPRV <= @CLIENTE_28_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_47_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_47_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_28_TELEFONO_DESDE is null ) OR ( C_CLIENTE.CLTLF >= @CLIENTE_28_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_28_TELEFONO_HASTA is null ) OR ( C_CLIENTE.CLTLF <= @CLIENTE_28_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_28_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLTIPODOC >= @CLIENTE_28_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_28_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLTIPODOC <= @CLIENTE_28_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_28_MOVIL_DESDE is null ) OR ( C_CLIENTE.CLMovil >= @CLIENTE_28_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_28_MOVIL_HASTA is null ) OR ( C_CLIENTE.CLMovil <= @CLIENTE_28_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_28_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE.CLTOPECCTE >= @CLIENTE_28_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_28_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE.CLTOPECCTE <= @CLIENTE_28_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_28_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE.CLLisPrec >= @CLIENTE_28_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_28_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE.CLLisPrec <= @CLIENTE_28_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_28_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE.CLCLAS >= @CLIENTE_28_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_28_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE.CLCLAS <= @CLIENTE_28_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_28_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE.CLTIPCONV >= @CLIENTE_28_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_28_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE.CLTIPCONV <= @CLIENTE_28_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_28_NROIIBB_DESDE is null ) OR ( C_CLIENTE.CLNROIIBB >= @CLIENTE_28_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_28_NROIIBB_HASTA is null ) OR ( C_CLIENTE.CLNROIIBB <= @CLIENTE_28_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_28_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE.CLCO_DTO >= @CLIENTE_28_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_28_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE.CLCO_DTO <= @CLIENTE_28_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_28_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE.CLTRANS >= @CLIENTE_28_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_28_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE.CLTRANS <= @CLIENTE_28_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_28_ESTADOCIVIL is null ) OR ( C_CLIENTE.Estado = @CLIENTE_28_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_28_HIJOS_DESDE is null ) OR ( C_CLIENTE.Hijos >= @CLIENTE_28_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_28_HIJOS_HASTA is null ) OR ( C_CLIENTE.Hijos <= @CLIENTE_28_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_28_SEXO is null ) OR ( C_CLIENTE.Sexo = @CLIENTE_28_SEXO ) ) and 
	( ( @CLIENTE_28_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE.globalid >= @CLIENTE_28_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_28_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE.globalid <= @CLIENTE_28_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_28_RUT_DESDE is null ) OR ( C_CLIENTE.RUT >= @CLIENTE_28_RUT_DESDE ) ) and 
	( ( @CLIENTE_28_RUT_HASTA is null ) OR ( C_CLIENTE.RUT <= @CLIENTE_28_RUT_HASTA ) ) and 
	( ( @CLIENTE_28_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE.CLCODFANT >= @CLIENTE_28_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_28_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE.CLCODFANT <= @CLIENTE_28_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_28_TIPOCLI_DESDE is null ) OR ( C_CLIENTE.CLTipoCli >= @CLIENTE_28_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_28_TIPOCLI_HASTA is null ) OR ( C_CLIENTE.CLTipoCli <= @CLIENTE_28_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_28_CATEGCLI_DESDE is null ) OR ( C_CLIENTE.CLCategCli >= @CLIENTE_28_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_28_CATEGCLI_HASTA is null ) OR ( C_CLIENTE.CLCategCli <= @CLIENTE_28_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_28_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE.CLCONDPAG >= @CLIENTE_28_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_28_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE.CLCONDPAG <= @CLIENTE_28_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_28_SUJETOVINCULADO is null ) OR ( C_CLIENTE.CLSujVinc = @CLIENTE_28_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_28_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE.CLPERTIVA >= @CLIENTE_28_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_28_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE.CLPERTIVA <= @CLIENTE_28_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_28_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE.CLSITGAN = @CLIENTE_28_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_28_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE.EXPERIVA = @CLIENTE_28_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_28_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE.CLPERGAN >= @CLIENTE_28_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_28_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE.CLPERGAN <= @CLIENTE_28_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_28_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE.EXPERGAN = @CLIENTE_28_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_28_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.CODRECOM >= @CLIENTE_28_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_28_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.CODRECOM <= @CLIENTE_28_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_28_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.NOMRECOM >= @CLIENTE_28_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_28_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.NOMRECOM <= @CLIENTE_28_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_28_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE.CLPRINOM >= @CLIENTE_28_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_28_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE.CLPRINOM <= @CLIENTE_28_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_28_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE.CLSEGNOM >= @CLIENTE_28_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_28_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE.CLSEGNOM <= @CLIENTE_28_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_28_APELLIDO_DESDE is null ) OR ( C_CLIENTE.CLAPELL >= @CLIENTE_28_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_28_APELLIDO_HASTA is null ) OR ( C_CLIENTE.CLAPELL <= @CLIENTE_28_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_28_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE.VHastaIva >= @CLIENTE_28_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_28_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE.VHastaIva <= @CLIENTE_28_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_28_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE.VHastaGan >= @CLIENTE_28_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_28_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE.VHastaGan <= @CLIENTE_28_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_28_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE.CLSIPRIB >= @CLIENTE_28_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_28_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE.CLSIPRIB <= @CLIENTE_28_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_28_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE.PorcenTC >= @CLIENTE_28_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_28_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE.PorcenTC <= @CLIENTE_28_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_28_TASACEROAPLICA is null ) OR ( C_CLIENTE.AplicaTC = @CLIENTE_28_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_28_INACTIVOFW is null ) OR ( C_CLIENTE.InactivoFW = @CLIENTE_28_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9144_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9144_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9144_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9144_CODIGO_HASTA ) ) and 
	( ( @SENIA_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_SENIA.BDALTAFW >= @SENIA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @SENIA_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_SENIA.BDALTAFW <= @SENIA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @SENIA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_SENIA.BDMODIFW >= @SENIA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @SENIA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_SENIA.BDMODIFW <= @SENIA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @SENIA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_SENIA.ESTTRANS >= @SENIA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @SENIA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_SENIA.ESTTRANS <= @SENIA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @SENIA_FECHAALTAFW_DESDE is null ) OR ( c_SENIA.FALTAFW >= @SENIA_FECHAALTAFW_DESDE ) ) and 
	( ( @SENIA_FECHAALTAFW_HASTA is null ) OR ( c_SENIA.FALTAFW <= @SENIA_FECHAALTAFW_HASTA ) ) and 
	( ( @SENIA_FECHAEXPO_DESDE is null ) OR ( c_SENIA.FECEXPO >= @SENIA_FECHAEXPO_DESDE ) ) and 
	( ( @SENIA_FECHAEXPO_HASTA is null ) OR ( c_SENIA.FECEXPO <= @SENIA_FECHAEXPO_HASTA ) ) and 
	( ( @SENIA_FECHAIMPO_DESDE is null ) OR ( c_SENIA.FECIMPO >= @SENIA_FECHAIMPO_DESDE ) ) and 
	( ( @SENIA_FECHAIMPO_HASTA is null ) OR ( c_SENIA.FECIMPO <= @SENIA_FECHAIMPO_HASTA ) ) and 
	( ( @SENIA_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_SENIA.FMODIFW >= @SENIA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @SENIA_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_SENIA.FMODIFW <= @SENIA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @SENIA_FECHATRANSFERENCIA_DESDE is null ) OR ( c_SENIA.FECTRANS >= @SENIA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @SENIA_FECHATRANSFERENCIA_HASTA is null ) OR ( c_SENIA.FECTRANS <= @SENIA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @SENIA_HORAALTAFW_DESDE is null ) OR ( c_SENIA.HALTAFW >= @SENIA_HORAALTAFW_DESDE ) ) and 
	( ( @SENIA_HORAALTAFW_HASTA is null ) OR ( c_SENIA.HALTAFW <= @SENIA_HORAALTAFW_HASTA ) ) and 
	( ( @SENIA_HORAEXPO_DESDE is null ) OR ( c_SENIA.HORAEXPO >= @SENIA_HORAEXPO_DESDE ) ) and 
	( ( @SENIA_HORAEXPO_HASTA is null ) OR ( c_SENIA.HORAEXPO <= @SENIA_HORAEXPO_HASTA ) ) and 
	( ( @SENIA_HORAIMPO_DESDE is null ) OR ( c_SENIA.HORAIMPO >= @SENIA_HORAIMPO_DESDE ) ) and 
	( ( @SENIA_HORAIMPO_HASTA is null ) OR ( c_SENIA.HORAIMPO <= @SENIA_HORAIMPO_HASTA ) ) and 
	( ( @SENIA_HORAMODIFICACIONFW_DESDE is null ) OR ( c_SENIA.HMODIFW >= @SENIA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @SENIA_HORAMODIFICACIONFW_HASTA is null ) OR ( c_SENIA.HMODIFW <= @SENIA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @SENIA_SERIEALTAFW_DESDE is null ) OR ( c_SENIA.SALTAFW >= @SENIA_SERIEALTAFW_DESDE ) ) and 
	( ( @SENIA_SERIEALTAFW_HASTA is null ) OR ( c_SENIA.SALTAFW <= @SENIA_SERIEALTAFW_HASTA ) ) and 
	( ( @SENIA_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_SENIA.SMODIFW >= @SENIA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @SENIA_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_SENIA.SMODIFW <= @SENIA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @SENIA_USUARIOALTAFW_DESDE is null ) OR ( c_SENIA.UALTAFW >= @SENIA_USUARIOALTAFW_DESDE ) ) and 
	( ( @SENIA_USUARIOALTAFW_HASTA is null ) OR ( c_SENIA.UALTAFW <= @SENIA_USUARIOALTAFW_HASTA ) ) and 
	( ( @SENIA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_SENIA.UMODIFW >= @SENIA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @SENIA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_SENIA.UMODIFW <= @SENIA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @SENIA_VERSIONALTAFW_DESDE is null ) OR ( c_SENIA.VALTAFW >= @SENIA_VERSIONALTAFW_DESDE ) ) and 
	( ( @SENIA_VERSIONALTAFW_HASTA is null ) OR ( c_SENIA.VALTAFW <= @SENIA_VERSIONALTAFW_HASTA ) ) and 
	( ( @SENIA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_SENIA.VMODIFW >= @SENIA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @SENIA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_SENIA.VMODIFW <= @SENIA_VERSIONMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_FACTURA.Moneda >= @FACTURA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_FACTURA.Moneda <= @FACTURA_1_MONEDACOMPROBANTE_HASTA ) )

)