IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_DEVOLUCION_ITEMARTICULOSVENTAS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_DEVOLUCION_ITEMARTICULOSVENTAS];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_DEVOLUCION_ITEMARTICULOSVENTAS]
( @BaseDeDatos varchar(8),
	@DEVOLUCION_CLIENTE_DESDE varchar(10),
	@DEVOLUCION_CLIENTE_HASTA varchar(10),
	@DEVOLUCION_SUBTOTALBRUTO_DESDE numeric(15, 4),
	@DEVOLUCION_SUBTOTALBRUTO_HASTA numeric(15, 4),
	@DEVOLUCION_SUBTOTALNETO_DESDE numeric(15, 4),
	@DEVOLUCION_SUBTOTALNETO_HASTA numeric(15, 4),
	@DEVOLUCION_CLIENTEDESCRIPCION_DESDE varchar(185),
	@DEVOLUCION_CLIENTEDESCRIPCION_HASTA varchar(185),
	@DEVOLUCION_VENDEDOR_DESDE varchar(10),
	@DEVOLUCION_VENDEDOR_HASTA varchar(10),
	@DEVOLUCION_LISTADEPRECIOS_DESDE varchar(6),
	@DEVOLUCION_LISTADEPRECIOS_HASTA varchar(6),
	@DEVOLUCION_MOTIVO_DESDE varchar(3),
	@DEVOLUCION_MOTIVO_HASTA varchar(3),
	@DEVOLUCION_REMITO_DESDE varchar(15),
	@DEVOLUCION_REMITO_HASTA varchar(15),
	@DEVOLUCION_LETRA_DESDE varchar(1),
	@DEVOLUCION_LETRA_HASTA varchar(1),
	@DEVOLUCION_PUNTODEVENTA_DESDE numeric(4, 0),
	@DEVOLUCION_PUNTODEVENTA_HASTA numeric(4, 0),
	@DEVOLUCION_NUMERO_DESDE numeric(8, 0),
	@DEVOLUCION_NUMERO_HASTA numeric(8, 0),
	@DEVOLUCION_FECHA_DESDE datetime,
	@DEVOLUCION_FECHA_HASTA datetime,
	@DEVOLUCION_AJUSTESPORREDONDEOS_DESDE numeric(15, 2),
	@DEVOLUCION_AJUSTESPORREDONDEOS_HASTA numeric(15, 2),
	@DEVOLUCION_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@DEVOLUCION_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@DEVOLUCION_DESCUENTO_DESDE numeric(15, 2),
	@DEVOLUCION_DESCUENTO_HASTA numeric(15, 2),
	@DEVOLUCION_RECARGOMONTO1_DESDE numeric(17, 4),
	@DEVOLUCION_RECARGOMONTO1_HASTA numeric(17, 4),
	@DEVOLUCION_IMPUESTOS_DESDE numeric(15, 2),
	@DEVOLUCION_IMPUESTOS_HASTA numeric(15, 2),
	@DEVOLUCION_TOTALIMPUESTOS_DESDE numeric(15, 2),
	@DEVOLUCION_TOTALIMPUESTOS_HASTA numeric(15, 2),
	@DEVOLUCION_TOTALRECARGOSSINIMPUESTOS_DESDE numeric(15, 4),
	@DEVOLUCION_TOTALRECARGOSSINIMPUESTOS_HASTA numeric(15, 4),
	@DEVOLUCION_TOTAL_DESDE numeric(15, 2),
	@DEVOLUCION_TOTAL_HASTA numeric(15, 2),
	@CLIENTE_2_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_2_CLIENTE_NOMBRE_HASTA varchar(185),
	@VENDEDOR_80_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_80_VENDEDOR_NOMBRE_HASTA varchar(60),
	@LISTADEPRECIOS_81_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_81_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@MOTIVO_82_MOTIVO_DESCRIPCION_DESDE varchar(40),
	@MOTIVO_82_MOTIVO_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_3_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_3_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_18_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_18_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_9144_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9144_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9144_LINEA_DESDE varchar(10),
	@SUCURSAL_9144_LINEA_HASTA varchar(10),
	@SUCURSAL_9144_TIPO_DESDE varchar(10),
	@SUCURSAL_9144_TIPO_HASTA varchar(10),
	@SUCURSAL_9144_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9144_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_2_VENDEDOR_DESDE varchar(10),
	@CLIENTE_2_VENDEDOR_HASTA varchar(10),
	@CLIENTE_2_CALLE_DESDE varchar(70),
	@CLIENTE_2_CALLE_HASTA varchar(70),
	@CLIENTE_2_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_2_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_2_CUIT_DESDE varchar(15),
	@CLIENTE_2_CUIT_HASTA varchar(15),
	@CLIENTE_2_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_2_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_2_EMAIL_DESDE varchar(250),
	@CLIENTE_2_EMAIL_HASTA varchar(250),
	@CLIENTE_2_FAX_DESDE varchar(20),
	@CLIENTE_2_FAX_HASTA varchar(20),
	@CLIENTE_2_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_2_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_2_IMAGEN_DESDE varchar(180),
	@CLIENTE_2_IMAGEN_HASTA varchar(180),
	@CLIENTE_2_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_2_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_2_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_2_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_2_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_2_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_2_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_2_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_2_PAIS_DESDE varchar(3),
	@CLIENTE_2_PAIS_HASTA varchar(3),
	@CLIENTE_2_PISO_DESDE varchar(3),
	@CLIENTE_2_PISO_HASTA varchar(3),
	@CLIENTE_2_PROVINCIA_DESDE varchar(2),
	@CLIENTE_2_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_2_TELEFONO_DESDE varchar(30),
	@CLIENTE_2_TELEFONO_HASTA varchar(30),
	@CLIENTE_2_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_2_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_2_MOVIL_DESDE varchar(30),
	@CLIENTE_2_MOVIL_HASTA varchar(30),
	@CLIENTE_2_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_2_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_2_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_2_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_2_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_2_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_2_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_2_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_2_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_2_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_2_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_2_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_2_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_2_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_2_ESTADOCIVIL varchar(13),
	@CLIENTE_2_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_2_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_2_SEXO varchar(10),
	@CLIENTE_2_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_2_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_2_RUT_DESDE varchar(12),
	@CLIENTE_2_RUT_HASTA varchar(12),
	@CLIENTE_2_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_2_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_2_TIPOCLI_DESDE varchar(10),
	@CLIENTE_2_TIPOCLI_HASTA varchar(10),
	@CLIENTE_2_CATEGCLI_DESDE varchar(10),
	@CLIENTE_2_CATEGCLI_HASTA varchar(10),
	@CLIENTE_2_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_2_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_2_SUJETOVINCULADO bit,
	@CLIENTE_2_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_2_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_2_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_2_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_2_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_2_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_2_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_2_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_2_APELLIDO_DESDE varchar(60),
	@CLIENTE_2_APELLIDO_HASTA varchar(60),
	@CLIENTE_2_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_2_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_2_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_2_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_2_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_2_TASACEROAPLICA bit,
	@CLIENTE_2_INACTIVOFW bit,
	@SUCURSAL_9144_CODIGO_DESDE varchar(10),
	@SUCURSAL_9144_CODIGO_HASTA varchar(10),
	@DEVOLUCION_FECHAALTAFW_DESDE datetime,
	@DEVOLUCION_FECHAALTAFW_HASTA datetime,
	@DEVOLUCION_HORAALTAFW_DESDE varchar(8),
	@DEVOLUCION_HORAALTAFW_HASTA varchar(8),
	@DEVOLUCION_BASEDEDATOSALTAFW_DESDE varchar(8),
	@DEVOLUCION_BASEDEDATOSALTAFW_HASTA varchar(8),
	@DEVOLUCION_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@DEVOLUCION_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@DEVOLUCION_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@DEVOLUCION_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@DEVOLUCION_FECHAEXPO_DESDE datetime,
	@DEVOLUCION_FECHAEXPO_HASTA datetime,
	@DEVOLUCION_FECHAIMPO_DESDE datetime,
	@DEVOLUCION_FECHAIMPO_HASTA datetime,
	@DEVOLUCION_FECHAMODIFICACIONFW_DESDE datetime,
	@DEVOLUCION_FECHAMODIFICACIONFW_HASTA datetime,
	@DEVOLUCION_FECHATRANSFERENCIA_DESDE datetime,
	@DEVOLUCION_FECHATRANSFERENCIA_HASTA datetime,
	@DEVOLUCION_HORAEXPO_DESDE varchar(8),
	@DEVOLUCION_HORAEXPO_HASTA varchar(8),
	@DEVOLUCION_HORAIMPO_DESDE varchar(8),
	@DEVOLUCION_HORAIMPO_HASTA varchar(8),
	@DEVOLUCION_HORAMODIFICACIONFW_DESDE varchar(8),
	@DEVOLUCION_HORAMODIFICACIONFW_HASTA varchar(8),
	@DEVOLUCION_SERIEALTAFW_DESDE varchar(7),
	@DEVOLUCION_SERIEALTAFW_HASTA varchar(7),
	@DEVOLUCION_SERIEMODIFICACIONFW_DESDE varchar(7),
	@DEVOLUCION_SERIEMODIFICACIONFW_HASTA varchar(7),
	@DEVOLUCION_USUARIOALTAFW_DESDE varchar(100),
	@DEVOLUCION_USUARIOALTAFW_HASTA varchar(100),
	@DEVOLUCION_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@DEVOLUCION_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@DEVOLUCION_VERSIONALTAFW_DESDE varchar(13),
	@DEVOLUCION_VERSIONALTAFW_HASTA varchar(13),
	@DEVOLUCION_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@DEVOLUCION_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticulosventas.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSVENTAS__Grupo,
	@basededatos as ITEMARTICULOSVENTAS__BD,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticulosventas.fart, c_itemarticulosventas.ccolor, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSVENTAS_1_OrdenPaletaColores,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticulosventas.fart, c_itemarticulosventas.talle, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSVENTAS_1_OrdenCurvaTalles,
	c_ITEMARTICULOSVENTAS.FART as ITEMARTICULOSVENTAS_FART,
	c_ITEMARTICULOSVENTAS.FTXT as ITEMARTICULOSVENTAS_FTXT,
	cast( c_devolucion_cabecera.signomov*c_itemarticulosventas.fcant as numeric( 9, 3 ) ) as ITEMARTICULOSVENTAS_FCANT,
	c_ITEMARTICULOSVENTAS.CODIGO as ITEMARTICULOSVENTAS_CODIGO,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.fcfi as numeric( 7, 2 ) ) as ITEMARTICULOSVENTAS_FCFI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.fcfitot as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_FCFITot,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.fmonto as numeric( 15, 2 ) ) as ITEMARTICULOSVENTAS_FMONTO,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.fneto as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_FNETO,
	c_ITEMARTICULOSVENTAS.PRUNCONIMP as ITEMARTICULOSVENTAS_prunconimp,
	c_ITEMARTICULOSVENTAS.FPRECIO as ITEMARTICULOSVENTAS_FPRECIO,
	c_ITEMARTICULOSVENTAS.PRUNSINIMP as ITEMARTICULOSVENTAS_Prunsinimp,
	c_ITEMARTICULOSVENTAS.CCOLOR as ITEMARTICULOSVENTAS_cColor,
	c_ITEMARTICULOSVENTAS.FCOLTXT as ITEMARTICULOSVENTAS_FCOLTXT,
	c_ITEMARTICULOSVENTAS.TALLE as ITEMARTICULOSVENTAS_Talle,
	c_ITEMARTICULOSVENTAS.EQUIV as ITEMARTICULOSVENTAS_Equiv,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.mntdes as numeric( 12, 2 ) ) as ITEMARTICULOSVENTAS_MNTDES,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.mntprecci as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPRECCI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.mntptot as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPTOT,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.mntpper as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPPER,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.mntpdesci as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPDESCI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.mntprecsi as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPRECSI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.mntpdessi as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPDESSI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.mntpiva as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPIVA,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.mnpdsi as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_MNPDSI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.mndesci as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_MNDESCI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*-1*c_itemarticulosventas.mndessi as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_MNDESSI,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.fbruto as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_FBruto,
	c_ITEMARTICULOSVENTAS.TASAIMPINT as ITEMARTICULOSVENTAS_tasaimpint,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.impinterno as numeric( 15, 4 ) ) as ITEMARTICULOSVENTAS_impinterno,
	cast( c_devolucion_cabecera.signomov*c_devolucion_cabecera.cotiz*c_itemarticulosventas.mntpint as numeric( 17, 4 ) ) as ITEMARTICULOSVENTAS_MNTPINT,
	c_ITEMARTICULOSVENTAS.MOTDEVOL as ITEMARTICULOSVENTAS_MotDevol,
	c_ITEMARTICULOSVENTAS.MOTDESCU as ITEMARTICULOSVENTAS_MotDescu,
	c_ITEMARTICULOSVENTAS.CODAUTDJCP as ITEMARTICULOSVENTAS_CodAutDJCP,
	c_ITEMARTICULOSVENTAS.NROITEM as ITEMARTICULOSVENTAS_NroItem,
	Funciones.IdentificadorDeComprobanteParaListado(c_afectado.AFETIPOCOM, c_afectado.AFELETRA, c_afectado.AFEPTOVEN, c_afectado.AFENUMCOM) as ITEMARTICULOSVENTAS_RemitoVirtual,
	c_afectado.AFEFECHA as ITEMARTICULOSVENTAS_FechaRemitoVirtual,
	c_devolucion_cabecera.ffch as ITEMARTICULOSVENTAS_FechaDevolucionVirtual,
	cast( funciones.diasdevencimiento(c_afectado.AFEFECHA, c_devolucion_cabecera.ffch, @parametro1) as numeric( 6, 0 ) ) as ITEMARTICULOSVENTAS_DiasVencidosVirtual,
	funciones.estavencido(funciones.datetime(), c_devolucion_cabecera.ffch, @parametro1) as ITEMARTICULOSVENTAS_EstaVencidoVirtual,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_EQUIVALENCIA.CCODIGO as EQUIVALENCIA_cCodigo,
	C_MOTIVODESCUENTOYDEVOLUCION121.DESCRIP as MOTIVODESCUENTOYDEVOLUCION121_Descrip,
	C_MOTIVODESCUENTOYDEVOLUCION122.DESCRIP as MOTIVODESCUENTOYDEVOLUCION122_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_MOTIVODESCUENTOYDEVOLUCION121.CODIGO as MOTIVODESCUENTOYDEVOLUCION121_Codigo,
	C_MOTIVODESCUENTOYDEVOLUCION122.CODIGO as MOTIVODESCUENTOYDEVOLUCION122_Codigo,
	C_TALLE.CODIGO as TALLE_Codigo
 from ZooLogic.COMPROBANTEVDET as c_ITEMARTICULOSVENTAS
 left join ZooLogic.EQUI as C_EQUIVALENCIA on C_EQUIVALENCIA.CCODIGO = C_ITEMARTICULOSVENTAS.EQUIV and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.EQUIV )
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSVENTAS.FART and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.FART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSVENTAS.CCOLOR and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.CCOLOR )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION121 on C_MOTIVODESCUENTOYDEVOLUCION121.CODIGO = C_ITEMARTICULOSVENTAS.MOTDEVOL and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.MOTDEVOL )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION122 on C_MOTIVODESCUENTOYDEVOLUCION122.CODIGO = C_ITEMARTICULOSVENTAS.MOTDESCU and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.MOTDESCU )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSVENTAS.TALLE and 0 = Funciones.empty( C_ITEMARTICULOSVENTAS.TALLE )
 inner join ZooLogic.COMPROBANTEV as C_DEVOLUCION_CABECERA on C_DEVOLUCION_CABECERA.CODIGO = C_ITEMARTICULOSVENTAS.CODIGO
 left join zoologic.COMPAFE as c_afectado on c_afectado.AFETIPOCOM = 11 and c_afectado.CODIGO = c_ITEMARTICULOSVENTAS.CODIGO and c_afectado.AFECTA = c_ITEMARTICULOSVENTAS.AFE_COD
 left join ZooLogic.CLI as C_CLIENTE_CABECERA on C_CLIENTE_CABECERA.CLCOD = C_DEVOLUCION_CABECERA.FPERSON and 0 = Funciones.empty( C_DEVOLUCION_CABECERA.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO_CABECERA on C_CONDICIONDEPAGO_CABECERA.CLCOD = C_CLIENTE_CABECERA.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB_CABECERA on C_DATOSADICIONALESSIPRIB_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO_CABECERA on C_DESCUENTO_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO42_CABECERA on C_IMPUESTO42_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO45_CABECERA on C_IMPUESTO45_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLPERGAN and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS26_CABECERA on C_LISTADEPRECIOS26_CABECERA.LPR_NUMERO = C_CLIENTE_CABECERA.CLLISPREC and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLLISPREC )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS81_CABECERA on C_LISTADEPRECIOS81_CABECERA.LPR_NUMERO = C_DEVOLUCION_CABECERA.CODLISTA and 0 = Funciones.empty( C_DEVOLUCION_CABECERA.CODLISTA )
 left join ZooLogic.MOTIVO as C_MOTIVO_CABECERA on C_MOTIVO_CABECERA.MOTCOD = C_DEVOLUCION_CABECERA.MOTIVO and 0 = Funciones.empty( C_DEVOLUCION_CABECERA.MOTIVO )
 left join ZooLogic.PAISES as C_PAISES_CABECERA on C_PAISES_CABECERA.PCOD = C_CLIENTE_CABECERA.CLPAIS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA_CABECERA on C_PROVINCIA_CABECERA.PRV_COD = C_CLIENTE_CABECERA.CLPRV and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL_CABECERA on C_SITUACIONFISCAL_CABECERA.CODIGO = C_CLIENTE_CABECERA.CLIVA and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL_CABECERA on C_SUCURSAL_CABECERA.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE_CABECERA on C_TIPOCLIENTE_CABECERA.TCCOD = C_CLIENTE_CABECERA.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL_CABECERA on C_TIPOSUCURSAL_CABECERA.TCOD = C_SUCURSAL_CABECERA.TIPO and 0 = Funciones.empty( C_SUCURSAL_CABECERA.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA_CABECERA on C_TRANSPORTISTA_CABECERA.TRCOD = C_CLIENTE_CABECERA.CLTRANS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR3_CABECERA on C_VENDEDOR3_CABECERA.CLCOD = C_CLIENTE_CABECERA.CLVEND and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLVEND )
 left join ZooLogic.VEN as C_VENDEDOR80_CABECERA on C_VENDEDOR80_CABECERA.CLCOD = C_DEVOLUCION_CABECERA.FVEN and 0 = Funciones.empty( C_DEVOLUCION_CABECERA.FVEN )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA_CABECERA on C_NOMBREDEFANTASIA_CABECERA.NFCOD = C_CLIENTE_CABECERA.CLCODFANT and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE_CABECERA on C_CATEGORIACLIENTE_CABECERA.CGCOD = C_CLIENTE_CABECERA.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE_CABECERA on C_CLASIFICACIONCLIENTE_CABECERA.CLACOD = C_CLIENTE_CABECERA.CLCLAS and 0 = Funciones.empty( C_CLIENTE_CABECERA.CLCLAS )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL_CABECERA on C_LINEASUCURSAL_CABECERA.LSCOD = C_SUCURSAL_CABECERA.LINEA and 0 = Funciones.empty( C_SUCURSAL_CABECERA.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION_CABECERA on C_SEGMENTACION_CABECERA.SCOD = C_SUCURSAL_CABECERA.SEG and 0 = Funciones.empty( C_SUCURSAL_CABECERA.SEG )
 where ( not 1 = funciones.empty( c_devolucion_cabecera.codigo ) and c_devolucion_cabecera.facttipo = 12 and ( Funciones.EstaVencido(c_afectado.AFEFECHA, c_devolucion_cabecera.ffch, @parametro1) = 1 or c_afectado.CODIGO is null ) ) and 
	( ( @DEVOLUCION_CLIENTE_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FPerson >= @DEVOLUCION_CLIENTE_DESDE ) ) and 
	( ( @DEVOLUCION_CLIENTE_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FPerson <= @DEVOLUCION_CLIENTE_HASTA ) ) and 
	( ( @DEVOLUCION_SUBTOTALBRUTO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FSubTOT >= @DEVOLUCION_SUBTOTALBRUTO_DESDE ) ) and 
	( ( @DEVOLUCION_SUBTOTALBRUTO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FSubTOT <= @DEVOLUCION_SUBTOTALBRUTO_HASTA ) ) and 
	( ( @DEVOLUCION_SUBTOTALNETO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.fSubToN >= @DEVOLUCION_SUBTOTALNETO_DESDE ) ) and 
	( ( @DEVOLUCION_SUBTOTALNETO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.fSubToN <= @DEVOLUCION_SUBTOTALNETO_HASTA ) ) and 
	( ( @DEVOLUCION_CLIENTEDESCRIPCION_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FCLIENTE >= @DEVOLUCION_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @DEVOLUCION_CLIENTEDESCRIPCION_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FCLIENTE <= @DEVOLUCION_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @DEVOLUCION_VENDEDOR_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FVEN >= @DEVOLUCION_VENDEDOR_DESDE ) ) and 
	( ( @DEVOLUCION_VENDEDOR_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FVEN <= @DEVOLUCION_VENDEDOR_HASTA ) ) and 
	( ( @DEVOLUCION_LISTADEPRECIOS_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.CodLista >= @DEVOLUCION_LISTADEPRECIOS_DESDE ) ) and 
	( ( @DEVOLUCION_LISTADEPRECIOS_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.CodLista <= @DEVOLUCION_LISTADEPRECIOS_HASTA ) ) and 
	( ( @DEVOLUCION_MOTIVO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.MOTIVO >= @DEVOLUCION_MOTIVO_DESDE ) ) and 
	( ( @DEVOLUCION_MOTIVO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.MOTIVO <= @DEVOLUCION_MOTIVO_HASTA ) ) and 
	( ( @DEVOLUCION_REMITO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.REMITO >= @DEVOLUCION_REMITO_DESDE ) ) and 
	( ( @DEVOLUCION_REMITO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.REMITO <= @DEVOLUCION_REMITO_HASTA ) ) and 
	( ( @DEVOLUCION_LETRA_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FLETRA >= @DEVOLUCION_LETRA_DESDE ) ) and 
	( ( @DEVOLUCION_LETRA_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FLETRA <= @DEVOLUCION_LETRA_HASTA ) ) and 
	( ( @DEVOLUCION_PUNTODEVENTA_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FPTOVEN >= @DEVOLUCION_PUNTODEVENTA_DESDE ) ) and 
	( ( @DEVOLUCION_PUNTODEVENTA_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FPTOVEN <= @DEVOLUCION_PUNTODEVENTA_HASTA ) ) and 
	( ( @DEVOLUCION_NUMERO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FNUMCOMP >= @DEVOLUCION_NUMERO_DESDE ) ) and 
	( ( @DEVOLUCION_NUMERO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FNUMCOMP <= @DEVOLUCION_NUMERO_HASTA ) ) and 
	( ( @DEVOLUCION_FECHA_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FFCH >= @DEVOLUCION_FECHA_DESDE ) ) and 
	( ( @DEVOLUCION_FECHA_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FFCH <= @DEVOLUCION_FECHA_HASTA ) ) and 
	( ( @DEVOLUCION_AJUSTESPORREDONDEOS_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FAjXRe >= @DEVOLUCION_AJUSTESPORREDONDEOS_DESDE ) ) and 
	( ( @DEVOLUCION_AJUSTESPORREDONDEOS_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FAjXRe <= @DEVOLUCION_AJUSTESPORREDONDEOS_HASTA ) ) and 
	( ( @DEVOLUCION_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FPODES >= @DEVOLUCION_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @DEVOLUCION_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FPODES <= @DEVOLUCION_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @DEVOLUCION_DESCUENTO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.fDescu >= @DEVOLUCION_DESCUENTO_DESDE ) ) and 
	( ( @DEVOLUCION_DESCUENTO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.fDescu <= @DEVOLUCION_DESCUENTO_HASTA ) ) and 
	( ( @DEVOLUCION_RECARGOMONTO1_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.MR1 >= @DEVOLUCION_RECARGOMONTO1_DESDE ) ) and 
	( ( @DEVOLUCION_RECARGOMONTO1_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.MR1 <= @DEVOLUCION_RECARGOMONTO1_HASTA ) ) and 
	( ( @DEVOLUCION_IMPUESTOS_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.fImpuesto >= @DEVOLUCION_IMPUESTOS_DESDE ) ) and 
	( ( @DEVOLUCION_IMPUESTOS_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.fImpuesto <= @DEVOLUCION_IMPUESTOS_HASTA ) ) and 
	( ( @DEVOLUCION_TOTALIMPUESTOS_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.totimpue >= @DEVOLUCION_TOTALIMPUESTOS_DESDE ) ) and 
	( ( @DEVOLUCION_TOTALIMPUESTOS_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.totimpue <= @DEVOLUCION_TOTALIMPUESTOS_HASTA ) ) and 
	( ( @DEVOLUCION_TOTALRECARGOSSINIMPUESTOS_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.totrecarSI >= @DEVOLUCION_TOTALRECARGOSSINIMPUESTOS_DESDE ) ) and 
	( ( @DEVOLUCION_TOTALRECARGOSSINIMPUESTOS_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.totrecarSI <= @DEVOLUCION_TOTALRECARGOSSINIMPUESTOS_HASTA ) ) and 
	( ( @DEVOLUCION_TOTAL_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FTotal >= @DEVOLUCION_TOTAL_DESDE ) ) and 
	( ( @DEVOLUCION_TOTAL_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FTotal <= @DEVOLUCION_TOTAL_HASTA ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNOM >= @CLIENTE_2_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNOM <= @CLIENTE_2_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @VENDEDOR_80_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR80_CABECERA.CLNOM >= @VENDEDOR_80_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_80_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR80_CABECERA.CLNOM <= @VENDEDOR_80_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @LISTADEPRECIOS_81_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS81_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_81_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_81_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS81_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_81_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @MOTIVO_82_MOTIVO_DESCRIPCION_DESDE is null ) OR ( C_MOTIVO_CABECERA.MOTDES >= @MOTIVO_82_MOTIVO_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVO_82_MOTIVO_DESCRIPCION_HASTA is null ) OR ( C_MOTIVO_CABECERA.MOTDES <= @MOTIVO_82_MOTIVO_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION_CABECERA.SDES >= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION_CABECERA.SDES <= @SEGMENTACION_9149_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES >= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES <= @LINEASUCURSAL_9148_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES >= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES <= @TIPOSUCURSAL_9147_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR3_CABECERA.CLNOM >= @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR3_CABECERA.CLNOM <= @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES_CABECERA.pdes >= @PAISES_18_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES_CABECERA.pdes <= @PAISES_18_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA_CABECERA.PRV_DES >= @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA_CABECERA.PRV_DES <= @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS26_CABECERA.LPR_NOMBRE >= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS26_CABECERA.LPR_NOMBRE <= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE_CABECERA.CLADES >= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE_CABECERA.CLADES <= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO_CABECERA.Des >= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO_CABECERA.Des <= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA_CABECERA.TRNOM >= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA_CABECERA.TRNOM <= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA_CABECERA.NFCOD >= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA_CABECERA.NFCOD <= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE_CABECERA.TCDES >= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE_CABECERA.TCDES <= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE_CABECERA.CGDes >= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE_CABECERA.CGDes <= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO_CABECERA.CLNOM >= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO_CABECERA.CLNOM <= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO42_CABECERA.descrip >= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO42_CABECERA.descrip <= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO45_CABECERA.descrip >= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO45_CABECERA.descrip <= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip >= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB_CABECERA.Descrip <= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.seg >= @SUCURSAL_9144_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9144_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.seg <= @SUCURSAL_9144_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9144_LINEA_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Linea >= @SUCURSAL_9144_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9144_LINEA_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Linea <= @SUCURSAL_9144_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9144_TIPO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Tipo >= @SUCURSAL_9144_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9144_TIPO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Tipo <= @SUCURSAL_9144_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.descrip >= @SUCURSAL_9144_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9144_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.descrip <= @SUCURSAL_9144_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_2_VENDEDOR_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLVend >= @CLIENTE_2_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_2_VENDEDOR_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLVend <= @CLIENTE_2_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_2_CALLE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCalle >= @CLIENTE_2_CALLE_DESDE ) ) and 
	( ( @CLIENTE_2_CALLE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCalle <= @CLIENTE_2_CALLE_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCP >= @CLIENTE_2_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCP <= @CLIENTE_2_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_2_CUIT_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCUIT >= @CLIENTE_2_CUIT_DESDE ) ) and 
	( ( @CLIENTE_2_CUIT_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCUIT <= @CLIENTE_2_CUIT_HASTA ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLDEPTO >= @CLIENTE_2_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLDEPTO <= @CLIENTE_2_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_EMAIL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLEMAIL >= @CLIENTE_2_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_2_EMAIL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLEMAIL <= @CLIENTE_2_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_2_FAX_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLFAX >= @CLIENTE_2_FAX_DESDE ) ) and 
	( ( @CLIENTE_2_FAX_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLFAX <= @CLIENTE_2_FAX_HASTA ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLFECHA >= @CLIENTE_2_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLFECHA <= @CLIENTE_2_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_2_IMAGEN_DESDE is null ) OR ( C_CLIENTE_CABECERA.CIMAGEN >= @CLIENTE_2_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_2_IMAGEN_HASTA is null ) OR ( C_CLIENTE_CABECERA.CIMAGEN <= @CLIENTE_2_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLLOC >= @CLIENTE_2_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLLOC <= @CLIENTE_2_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNRODOC >= @CLIENTE_2_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNRODOC <= @CLIENTE_2_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_NUMERO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNro >= @CLIENTE_2_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_2_NUMERO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNro <= @CLIENTE_2_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPAGEWEB >= @CLIENTE_2_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPAGEWEB <= @CLIENTE_2_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_2_PAIS_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPAIS >= @CLIENTE_2_PAIS_DESDE ) ) and 
	( ( @CLIENTE_2_PAIS_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPAIS <= @CLIENTE_2_PAIS_HASTA ) ) and 
	( ( @CLIENTE_2_PISO_DESDE is null ) OR ( C_CLIENTE_CABECERA.ClPiso >= @CLIENTE_2_PISO_DESDE ) ) and 
	( ( @CLIENTE_2_PISO_HASTA is null ) OR ( C_CLIENTE_CABECERA.ClPiso <= @CLIENTE_2_PISO_HASTA ) ) and 
	( ( @CLIENTE_2_PROVINCIA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPRV >= @CLIENTE_2_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_2_PROVINCIA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPRV <= @CLIENTE_2_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL_CABECERA.Descrip = @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_2_TELEFONO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTLF >= @CLIENTE_2_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_2_TELEFONO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTLF <= @CLIENTE_2_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTIPODOC >= @CLIENTE_2_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTIPODOC <= @CLIENTE_2_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_MOVIL_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLMovil >= @CLIENTE_2_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_2_MOVIL_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLMovil <= @CLIENTE_2_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTOPECCTE >= @CLIENTE_2_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTOPECCTE <= @CLIENTE_2_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLLisPrec >= @CLIENTE_2_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLLisPrec <= @CLIENTE_2_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCLAS >= @CLIENTE_2_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCLAS <= @CLIENTE_2_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTIPCONV >= @CLIENTE_2_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTIPCONV <= @CLIENTE_2_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_2_NROIIBB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLNROIIBB >= @CLIENTE_2_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_2_NROIIBB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLNROIIBB <= @CLIENTE_2_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCO_DTO >= @CLIENTE_2_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCO_DTO <= @CLIENTE_2_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTRANS >= @CLIENTE_2_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTRANS <= @CLIENTE_2_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_2_ESTADOCIVIL is null ) OR ( C_CLIENTE_CABECERA.Estado = @CLIENTE_2_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_2_HIJOS_DESDE is null ) OR ( C_CLIENTE_CABECERA.Hijos >= @CLIENTE_2_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_2_HIJOS_HASTA is null ) OR ( C_CLIENTE_CABECERA.Hijos <= @CLIENTE_2_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_2_SEXO is null ) OR ( C_CLIENTE_CABECERA.Sexo = @CLIENTE_2_SEXO ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE_CABECERA.globalid >= @CLIENTE_2_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE_CABECERA.globalid <= @CLIENTE_2_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_2_RUT_DESDE is null ) OR ( C_CLIENTE_CABECERA.RUT >= @CLIENTE_2_RUT_DESDE ) ) and 
	( ( @CLIENTE_2_RUT_HASTA is null ) OR ( C_CLIENTE_CABECERA.RUT <= @CLIENTE_2_RUT_HASTA ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCODFANT >= @CLIENTE_2_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCODFANT <= @CLIENTE_2_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCLI_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLTipoCli >= @CLIENTE_2_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCLI_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLTipoCli <= @CLIENTE_2_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CATEGCLI_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCategCli >= @CLIENTE_2_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_2_CATEGCLI_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCategCli <= @CLIENTE_2_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLCONDPAG >= @CLIENTE_2_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLCONDPAG <= @CLIENTE_2_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_2_SUJETOVINCULADO is null ) OR ( C_CLIENTE_CABECERA.CLSujVinc = @CLIENTE_2_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPERTIVA >= @CLIENTE_2_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPERTIVA <= @CLIENTE_2_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_2_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE_CABECERA.CLSITGAN = @CLIENTE_2_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE_CABECERA.EXPERIVA = @CLIENTE_2_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPERGAN >= @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPERGAN <= @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE_CABECERA.EXPERGAN = @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CODRECOM >= @CLIENTE_2_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CODRECOM <= @CLIENTE_2_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE_CABECERA.NOMRECOM >= @CLIENTE_2_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE_CABECERA.NOMRECOM <= @CLIENTE_2_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLPRINOM >= @CLIENTE_2_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLPRINOM <= @CLIENTE_2_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLSEGNOM >= @CLIENTE_2_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLSEGNOM <= @CLIENTE_2_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_APELLIDO_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLAPELL >= @CLIENTE_2_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_2_APELLIDO_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLAPELL <= @CLIENTE_2_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE_CABECERA.VHastaIva >= @CLIENTE_2_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE_CABECERA.VHastaIva <= @CLIENTE_2_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE_CABECERA.VHastaGan >= @CLIENTE_2_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE_CABECERA.VHastaGan <= @CLIENTE_2_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE_CABECERA.CLSIPRIB >= @CLIENTE_2_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE_CABECERA.CLSIPRIB <= @CLIENTE_2_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE_CABECERA.PorcenTC >= @CLIENTE_2_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE_CABECERA.PorcenTC <= @CLIENTE_2_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROAPLICA is null ) OR ( C_CLIENTE_CABECERA.AplicaTC = @CLIENTE_2_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_2_INACTIVOFW is null ) OR ( C_CLIENTE_CABECERA.InactivoFW = @CLIENTE_2_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9144_CODIGO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.codigo >= @SUCURSAL_9144_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9144_CODIGO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.codigo <= @SUCURSAL_9144_CODIGO_HASTA ) ) and 
	( ( @DEVOLUCION_FECHAALTAFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FAltaFW >= @DEVOLUCION_FECHAALTAFW_DESDE ) ) and 
	( ( @DEVOLUCION_FECHAALTAFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FAltaFW <= @DEVOLUCION_FECHAALTAFW_HASTA ) ) and 
	( ( @DEVOLUCION_HORAALTAFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.HAltaFW >= @DEVOLUCION_HORAALTAFW_DESDE ) ) and 
	( ( @DEVOLUCION_HORAALTAFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.HAltaFW <= @DEVOLUCION_HORAALTAFW_HASTA ) ) and 
	( ( @DEVOLUCION_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.BDALTAFW >= @DEVOLUCION_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @DEVOLUCION_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.BDALTAFW <= @DEVOLUCION_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @DEVOLUCION_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.BDMODIFW >= @DEVOLUCION_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @DEVOLUCION_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.BDMODIFW <= @DEVOLUCION_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @DEVOLUCION_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.ESTTRANS >= @DEVOLUCION_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @DEVOLUCION_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.ESTTRANS <= @DEVOLUCION_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @DEVOLUCION_FECHAEXPO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FECEXPO >= @DEVOLUCION_FECHAEXPO_DESDE ) ) and 
	( ( @DEVOLUCION_FECHAEXPO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FECEXPO <= @DEVOLUCION_FECHAEXPO_HASTA ) ) and 
	( ( @DEVOLUCION_FECHAIMPO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FECIMPO >= @DEVOLUCION_FECHAIMPO_DESDE ) ) and 
	( ( @DEVOLUCION_FECHAIMPO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FECIMPO <= @DEVOLUCION_FECHAIMPO_HASTA ) ) and 
	( ( @DEVOLUCION_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FMODIFW >= @DEVOLUCION_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @DEVOLUCION_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FMODIFW <= @DEVOLUCION_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @DEVOLUCION_FECHATRANSFERENCIA_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.FECTRANS >= @DEVOLUCION_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @DEVOLUCION_FECHATRANSFERENCIA_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.FECTRANS <= @DEVOLUCION_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @DEVOLUCION_HORAEXPO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.HORAEXPO >= @DEVOLUCION_HORAEXPO_DESDE ) ) and 
	( ( @DEVOLUCION_HORAEXPO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.HORAEXPO <= @DEVOLUCION_HORAEXPO_HASTA ) ) and 
	( ( @DEVOLUCION_HORAIMPO_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.HORAIMPO >= @DEVOLUCION_HORAIMPO_DESDE ) ) and 
	( ( @DEVOLUCION_HORAIMPO_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.HORAIMPO <= @DEVOLUCION_HORAIMPO_HASTA ) ) and 
	( ( @DEVOLUCION_HORAMODIFICACIONFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.HMODIFW >= @DEVOLUCION_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @DEVOLUCION_HORAMODIFICACIONFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.HMODIFW <= @DEVOLUCION_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @DEVOLUCION_SERIEALTAFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.SALTAFW >= @DEVOLUCION_SERIEALTAFW_DESDE ) ) and 
	( ( @DEVOLUCION_SERIEALTAFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.SALTAFW <= @DEVOLUCION_SERIEALTAFW_HASTA ) ) and 
	( ( @DEVOLUCION_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.SMODIFW >= @DEVOLUCION_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @DEVOLUCION_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.SMODIFW <= @DEVOLUCION_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @DEVOLUCION_USUARIOALTAFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.UALTAFW >= @DEVOLUCION_USUARIOALTAFW_DESDE ) ) and 
	( ( @DEVOLUCION_USUARIOALTAFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.UALTAFW <= @DEVOLUCION_USUARIOALTAFW_HASTA ) ) and 
	( ( @DEVOLUCION_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.UMODIFW >= @DEVOLUCION_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @DEVOLUCION_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.UMODIFW <= @DEVOLUCION_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @DEVOLUCION_VERSIONALTAFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.VALTAFW >= @DEVOLUCION_VERSIONALTAFW_DESDE ) ) and 
	( ( @DEVOLUCION_VERSIONALTAFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.VALTAFW <= @DEVOLUCION_VERSIONALTAFW_HASTA ) ) and 
	( ( @DEVOLUCION_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_DEVOLUCION_CABECERA.VMODIFW >= @DEVOLUCION_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @DEVOLUCION_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_DEVOLUCION_CABECERA.VMODIFW <= @DEVOLUCION_VERSIONMODIFICACIONFW_HASTA ) )

)