IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_REGISTRODECUENTA_REGISTRODECUENTA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_REGISTRODECUENTA_REGISTRODECUENTA];
GO;

CREATE FUNCTION [Listados].[GENERICO_REGISTRODECUENTA_REGISTRODECUENTA]
( @BaseDeDatos varchar(8),
	@CUENTABANCARIA_20_NUMERO_DESDE varchar(15),
	@CUENTABANCARIA_20_NUMERO_HASTA varchar(15),
	@CUENTABANCARIA_20_MONEDACUENTA_DESDE varchar(10),
	@CUENTABANCARIA_20_MONEDACUENTA_HASTA varchar(10),
	@REGISTRODECUENTA_CODIGO_DESDE varchar(20),
	@REGISTRODECUENTA_CODIGO_HASTA varchar(20),
	@REGISTRODECUENTA_CUENTABANCARIA_DESDE varchar(5),
	@REGISTRODECUENTA_CUENTABANCARIA_HASTA varchar(5),
	@REGISTRODECUENTA_PENDIENTE bit,
	@REGISTRODECUENTA_FECHA_DESDE datetime,
	@REGISTRODECUENTA_FECHA_HASTA datetime,
	@REGISTRODECUENTA_FECHACARGAOPERACION_DESDE datetime,
	@REGISTRODECUENTA_FECHACARGAOPERACION_HASTA datetime,
	@REGISTRODECUENTA_HORA_DESDE varchar(5),
	@REGISTRODECUENTA_HORA_HASTA varchar(5),
	@REGISTRODECUENTA_COMPROBANTE_DESDE varchar(100),
	@REGISTRODECUENTA_COMPROBANTE_HASTA varchar(100),
	@REGISTRODECUENTA_TIPOVALOR numeric(2, 0),
	@REGISTRODECUENTA_IDENTIFICADOR_DESDE varchar(30),
	@REGISTRODECUENTA_IDENTIFICADOR_HASTA varchar(30),
	@REGISTRODECUENTA_CODIGOBANCO_DESDE varchar(30),
	@REGISTRODECUENTA_CODIGOBANCO_HASTA varchar(30),
	@REGISTRODECUENTA_IMPORTE_DESDE numeric(15, 2),
	@REGISTRODECUENTA_IMPORTE_HASTA numeric(15, 2),
	@CUENTABANCARIA_20_CUENTABANCARIA_DESCRIPCION_DESDE varchar(40),
	@CUENTABANCARIA_20_CUENTABANCARIA_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_9261_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9261_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9260_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9260_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9259_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9259_TIPO_DESCRIPCION_HASTA varchar(50),
	@MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE varchar(40),
	@MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_9256_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9256_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9256_LINEA_DESDE varchar(10),
	@SUCURSAL_9256_LINEA_HASTA varchar(10),
	@SUCURSAL_9256_TIPO_DESDE varchar(10),
	@SUCURSAL_9256_TIPO_HASTA varchar(10),
	@SUCURSAL_9256_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9256_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9256_CODIGO_DESDE varchar(10),
	@SUCURSAL_9256_CODIGO_HASTA varchar(10),
	@REGISTRODECUENTA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@REGISTRODECUENTA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@REGISTRODECUENTA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@REGISTRODECUENTA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@REGISTRODECUENTA_FECHAALTAFW_DESDE datetime,
	@REGISTRODECUENTA_FECHAALTAFW_HASTA datetime,
	@REGISTRODECUENTA_FECHAEXPO_DESDE datetime,
	@REGISTRODECUENTA_FECHAEXPO_HASTA datetime,
	@REGISTRODECUENTA_FECHAIMPO_DESDE datetime,
	@REGISTRODECUENTA_FECHAIMPO_HASTA datetime,
	@REGISTRODECUENTA_FECHAMODIFICACIONFW_DESDE datetime,
	@REGISTRODECUENTA_FECHAMODIFICACIONFW_HASTA datetime,
	@REGISTRODECUENTA_FECHATRANSFERENCIA_DESDE datetime,
	@REGISTRODECUENTA_FECHATRANSFERENCIA_HASTA datetime,
	@REGISTRODECUENTA_HORAALTAFW_DESDE varchar(8),
	@REGISTRODECUENTA_HORAALTAFW_HASTA varchar(8),
	@REGISTRODECUENTA_HORAEXPO_DESDE varchar(8),
	@REGISTRODECUENTA_HORAEXPO_HASTA varchar(8),
	@REGISTRODECUENTA_HORAIMPO_DESDE varchar(8),
	@REGISTRODECUENTA_HORAIMPO_HASTA varchar(8),
	@REGISTRODECUENTA_HORAMODIFICACIONFW_DESDE varchar(8),
	@REGISTRODECUENTA_HORAMODIFICACIONFW_HASTA varchar(8),
	@REGISTRODECUENTA_SERIEALTAFW_DESDE varchar(7),
	@REGISTRODECUENTA_SERIEALTAFW_HASTA varchar(7),
	@REGISTRODECUENTA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@REGISTRODECUENTA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@REGISTRODECUENTA_USUARIOALTAFW_DESDE varchar(100),
	@REGISTRODECUENTA_USUARIOALTAFW_HASTA varchar(100),
	@REGISTRODECUENTA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@REGISTRODECUENTA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@REGISTRODECUENTA_VERSIONALTAFW_DESDE varchar(13),
	@REGISTRODECUENTA_VERSIONALTAFW_HASTA varchar(13),
	@REGISTRODECUENTA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@REGISTRODECUENTA_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@REGISTRODECUENTA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@REGISTRODECUENTA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@Parametro1 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_registrodecuenta.codigo, 38, ' ' ) as varchar( 46 ) ) as REGISTRODECUENTA__Grupo,
	@basededatos as REGISTRODECUENTA__BD,
	c_REGISTRODECUENTA.CODIGO as REGISTRODECUENTA_Codigo,
	c_REGISTRODECUENTA.CTABANC as REGISTRODECUENTA_CtaBanc,
	c_REGISTRODECUENTA.PENDIENTE as REGISTRODECUENTA_Pendiente,
	case when c_registrodecuenta.fecha = '01/01/1900 00:00:00' then null else c_registrodecuenta.fecha end as REGISTRODECUENTA_Fecha,
	case when c_registrodecuenta.fechacarga = '01/01/1900 00:00:00' then null else c_registrodecuenta.fechacarga end as REGISTRODECUENTA_FechaCarga,
	c_REGISTRODECUENTA.HORA as REGISTRODECUENTA_Hora,
	c_REGISTRODECUENTA.COMP as REGISTRODECUENTA_Comp,
	c_REGISTRODECUENTA.TIPOVAL as REGISTRODECUENTA_TipoVal,
	c_REGISTRODECUENTA.IDENT as REGISTRODECUENTA_Ident,
	c_REGISTRODECUENTA.CODBCO as REGISTRODECUENTA_CodBco,
	c_REGISTRODECUENTA.IMPORTE as REGISTRODECUENTA_Importe,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_REGISTRODECUENTA.BDMODIFW as REGISTRODECUENTA_BDMODIFW,
	c_REGISTRODECUENTA.ESTTRANS as REGISTRODECUENTA_ESTTRANS,
	case when c_registrodecuenta.faltafw = '01/01/1900 00:00:00' then null else c_registrodecuenta.faltafw end as REGISTRODECUENTA_FALTAFW,
	case when c_registrodecuenta.fecexpo = '01/01/1900 00:00:00' then null else c_registrodecuenta.fecexpo end as REGISTRODECUENTA_FECEXPO,
	case when c_registrodecuenta.fecimpo = '01/01/1900 00:00:00' then null else c_registrodecuenta.fecimpo end as REGISTRODECUENTA_FECIMPO,
	case when c_registrodecuenta.fmodifw = '01/01/1900 00:00:00' then null else c_registrodecuenta.fmodifw end as REGISTRODECUENTA_FMODIFW,
	case when c_registrodecuenta.fectrans = '01/01/1900 00:00:00' then null else c_registrodecuenta.fectrans end as REGISTRODECUENTA_FECTRANS,
	c_REGISTRODECUENTA.HALTAFW as REGISTRODECUENTA_HALTAFW,
	c_REGISTRODECUENTA.HORAEXPO as REGISTRODECUENTA_HORAEXPO,
	c_REGISTRODECUENTA.HORAIMPO as REGISTRODECUENTA_HORAIMPO,
	c_REGISTRODECUENTA.HMODIFW as REGISTRODECUENTA_HMODIFW,
	c_REGISTRODECUENTA.SALTAFW as REGISTRODECUENTA_SALTAFW,
	c_REGISTRODECUENTA.SMODIFW as REGISTRODECUENTA_SMODIFW,
	c_REGISTRODECUENTA.UALTAFW as REGISTRODECUENTA_UALTAFW,
	c_REGISTRODECUENTA.UMODIFW as REGISTRODECUENTA_UMODIFW,
	c_REGISTRODECUENTA.VALTAFW as REGISTRODECUENTA_VALTAFW,
	c_REGISTRODECUENTA.VMODIFW as REGISTRODECUENTA_VMODIFW,
	c_REGISTRODECUENTA.ZADSFW as REGISTRODECUENTA_ZADSFW,
	c_REGISTRODECUENTA.BDALTAFW as REGISTRODECUENTA_BDAltaFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as REGISTRODECUENTA__SUCURSAL,
	C_CUENTABANCARIA.CBNUM as CUENTABANCARIA_CBNum,
	C_CUENTABANCARIA.CBMONEDA as CUENTABANCARIA_CBMoneda,
	cast( funciones.esregistrodecuentaconciliado(c_registrodecuenta.codigo) as varchar( 2 ) ) as REGISTRODECUENTA_ConciliadoVirtual,
	@parametro1 as REGISTRODECUENTA_ConciliadoFiltroVirtual,
	isnull( c_cheque.cFecha, c_chqprop.cfecha ) as REGISTRODECUENTA_FechaPagoChequeVirtual,
	C_CUENTABANCARIA.CBDES as CUENTABANCARIA_CBDes,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_CUENTABANCARIA.CBCOD as CUENTABANCARIA_CBCod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD
 from ZooLogic.REGCTA as c_REGISTRODECUENTA
 left join ZooLogic.CTABAN as C_CUENTABANCARIA on C_CUENTABANCARIA.CBCOD = C_REGISTRODECUENTA.CTABANC and 0 = Funciones.empty( C_REGISTRODECUENTA.CTABANC )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_CUENTABANCARIA.CBMONEDA and 0 = Funciones.empty( C_CUENTABANCARIA.CBMONEDA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 left join [Listados].[VistaIntegraValores] vis on c_REGISTRODECUENTA.IDCOMP = vis.jjnum and (c_REGISTRODECUENTA.ident = vis.nroInterno ) and Funciones.empty(c_REGISTRODECUENTA.ident) = 0
 left join zoologic.CHEQUE c_cheque on c_cheque.ccod = vis.nrocheque
 left join zoologic.CHQPROP c_chqprop on c_chqprop.ccod = vis.nrochprop
 where ( ( ( case when @parametro1 = '' or @parametro1 = 'todos' then 0 else -1 end = 0 ) or ( case when @parametro1 = 'si' then 'si' else 'no' end = funciones.esregistrodecuentaconciliado(c_registrodecuenta.codigo) ) ) ) and 
	( ( @CUENTABANCARIA_20_NUMERO_DESDE is null ) OR ( C_CUENTABANCARIA.CBNum >= @CUENTABANCARIA_20_NUMERO_DESDE ) ) and 
	( ( @CUENTABANCARIA_20_NUMERO_HASTA is null ) OR ( C_CUENTABANCARIA.CBNum <= @CUENTABANCARIA_20_NUMERO_HASTA ) ) and 
	( ( @CUENTABANCARIA_20_MONEDACUENTA_DESDE is null ) OR ( C_CUENTABANCARIA.CBMoneda >= @CUENTABANCARIA_20_MONEDACUENTA_DESDE ) ) and 
	( ( @CUENTABANCARIA_20_MONEDACUENTA_HASTA is null ) OR ( C_CUENTABANCARIA.CBMoneda <= @CUENTABANCARIA_20_MONEDACUENTA_HASTA ) ) and 
	( ( @REGISTRODECUENTA_CODIGO_DESDE is null ) OR ( c_REGISTRODECUENTA.Codigo >= @REGISTRODECUENTA_CODIGO_DESDE ) ) and 
	( ( @REGISTRODECUENTA_CODIGO_HASTA is null ) OR ( c_REGISTRODECUENTA.Codigo <= @REGISTRODECUENTA_CODIGO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_CUENTABANCARIA_DESDE is null ) OR ( c_REGISTRODECUENTA.CtaBanc >= @REGISTRODECUENTA_CUENTABANCARIA_DESDE ) ) and 
	( ( @REGISTRODECUENTA_CUENTABANCARIA_HASTA is null ) OR ( c_REGISTRODECUENTA.CtaBanc <= @REGISTRODECUENTA_CUENTABANCARIA_HASTA ) ) and 
	( ( @REGISTRODECUENTA_PENDIENTE is null ) OR ( c_REGISTRODECUENTA.Pendiente = @REGISTRODECUENTA_PENDIENTE ) ) and 
	( ( @REGISTRODECUENTA_FECHA_DESDE is null ) OR ( c_REGISTRODECUENTA.Fecha >= @REGISTRODECUENTA_FECHA_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHA_HASTA is null ) OR ( c_REGISTRODECUENTA.Fecha <= @REGISTRODECUENTA_FECHA_HASTA ) ) and 
	( ( @REGISTRODECUENTA_FECHACARGAOPERACION_DESDE is null ) OR ( c_REGISTRODECUENTA.FechaCarga >= @REGISTRODECUENTA_FECHACARGAOPERACION_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHACARGAOPERACION_HASTA is null ) OR ( c_REGISTRODECUENTA.FechaCarga <= @REGISTRODECUENTA_FECHACARGAOPERACION_HASTA ) ) and 
	( ( @REGISTRODECUENTA_HORA_DESDE is null ) OR ( c_REGISTRODECUENTA.Hora >= @REGISTRODECUENTA_HORA_DESDE ) ) and 
	( ( @REGISTRODECUENTA_HORA_HASTA is null ) OR ( c_REGISTRODECUENTA.Hora <= @REGISTRODECUENTA_HORA_HASTA ) ) and 
	( ( @REGISTRODECUENTA_COMPROBANTE_DESDE is null ) OR ( c_REGISTRODECUENTA.Comp >= @REGISTRODECUENTA_COMPROBANTE_DESDE ) ) and 
	( ( @REGISTRODECUENTA_COMPROBANTE_HASTA is null ) OR ( c_REGISTRODECUENTA.Comp <= @REGISTRODECUENTA_COMPROBANTE_HASTA ) ) and 
	( ( @REGISTRODECUENTA_TIPOVALOR is null ) OR ( c_REGISTRODECUENTA.TipoVal = @REGISTRODECUENTA_TIPOVALOR ) ) and 
	( ( @REGISTRODECUENTA_IDENTIFICADOR_DESDE is null ) OR ( c_REGISTRODECUENTA.Ident >= @REGISTRODECUENTA_IDENTIFICADOR_DESDE ) ) and 
	( ( @REGISTRODECUENTA_IDENTIFICADOR_HASTA is null ) OR ( c_REGISTRODECUENTA.Ident <= @REGISTRODECUENTA_IDENTIFICADOR_HASTA ) ) and 
	( ( @REGISTRODECUENTA_CODIGOBANCO_DESDE is null ) OR ( c_REGISTRODECUENTA.CodBco >= @REGISTRODECUENTA_CODIGOBANCO_DESDE ) ) and 
	( ( @REGISTRODECUENTA_CODIGOBANCO_HASTA is null ) OR ( c_REGISTRODECUENTA.CodBco <= @REGISTRODECUENTA_CODIGOBANCO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_IMPORTE_DESDE is null ) OR ( c_REGISTRODECUENTA.Importe >= @REGISTRODECUENTA_IMPORTE_DESDE ) ) and 
	( ( @REGISTRODECUENTA_IMPORTE_HASTA is null ) OR ( c_REGISTRODECUENTA.Importe <= @REGISTRODECUENTA_IMPORTE_HASTA ) ) and 
	( ( @CUENTABANCARIA_20_CUENTABANCARIA_DESCRIPCION_DESDE is null ) OR ( C_CUENTABANCARIA.CBDes >= @CUENTABANCARIA_20_CUENTABANCARIA_DESCRIPCION_DESDE ) ) and 
	( ( @CUENTABANCARIA_20_CUENTABANCARIA_DESCRIPCION_HASTA is null ) OR ( C_CUENTABANCARIA.CBDes <= @CUENTABANCARIA_20_CUENTABANCARIA_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9261_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9261_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9261_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9261_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9260_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9260_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9260_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9260_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9259_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9259_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9259_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9259_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_9010_MONEDACUENTA_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_9010_MONEDACUENTA_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9256_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9256_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9256_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9256_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9256_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9256_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9256_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9256_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9256_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9256_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9256_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9256_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9256_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9256_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9256_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9256_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9256_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9256_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9256_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9256_CODIGO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_REGISTRODECUENTA.BDMODIFW >= @REGISTRODECUENTA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_REGISTRODECUENTA.BDMODIFW <= @REGISTRODECUENTA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_REGISTRODECUENTA.ESTTRANS >= @REGISTRODECUENTA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @REGISTRODECUENTA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_REGISTRODECUENTA.ESTTRANS <= @REGISTRODECUENTA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @REGISTRODECUENTA_FECHAALTAFW_DESDE is null ) OR ( c_REGISTRODECUENTA.FALTAFW >= @REGISTRODECUENTA_FECHAALTAFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHAALTAFW_HASTA is null ) OR ( c_REGISTRODECUENTA.FALTAFW <= @REGISTRODECUENTA_FECHAALTAFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_FECHAEXPO_DESDE is null ) OR ( c_REGISTRODECUENTA.FECEXPO >= @REGISTRODECUENTA_FECHAEXPO_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHAEXPO_HASTA is null ) OR ( c_REGISTRODECUENTA.FECEXPO <= @REGISTRODECUENTA_FECHAEXPO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_FECHAIMPO_DESDE is null ) OR ( c_REGISTRODECUENTA.FECIMPO >= @REGISTRODECUENTA_FECHAIMPO_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHAIMPO_HASTA is null ) OR ( c_REGISTRODECUENTA.FECIMPO <= @REGISTRODECUENTA_FECHAIMPO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_REGISTRODECUENTA.FMODIFW >= @REGISTRODECUENTA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_REGISTRODECUENTA.FMODIFW <= @REGISTRODECUENTA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_FECHATRANSFERENCIA_DESDE is null ) OR ( c_REGISTRODECUENTA.FECTRANS >= @REGISTRODECUENTA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @REGISTRODECUENTA_FECHATRANSFERENCIA_HASTA is null ) OR ( c_REGISTRODECUENTA.FECTRANS <= @REGISTRODECUENTA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @REGISTRODECUENTA_HORAALTAFW_DESDE is null ) OR ( c_REGISTRODECUENTA.HALTAFW >= @REGISTRODECUENTA_HORAALTAFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_HORAALTAFW_HASTA is null ) OR ( c_REGISTRODECUENTA.HALTAFW <= @REGISTRODECUENTA_HORAALTAFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_HORAEXPO_DESDE is null ) OR ( c_REGISTRODECUENTA.HORAEXPO >= @REGISTRODECUENTA_HORAEXPO_DESDE ) ) and 
	( ( @REGISTRODECUENTA_HORAEXPO_HASTA is null ) OR ( c_REGISTRODECUENTA.HORAEXPO <= @REGISTRODECUENTA_HORAEXPO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_HORAIMPO_DESDE is null ) OR ( c_REGISTRODECUENTA.HORAIMPO >= @REGISTRODECUENTA_HORAIMPO_DESDE ) ) and 
	( ( @REGISTRODECUENTA_HORAIMPO_HASTA is null ) OR ( c_REGISTRODECUENTA.HORAIMPO <= @REGISTRODECUENTA_HORAIMPO_HASTA ) ) and 
	( ( @REGISTRODECUENTA_HORAMODIFICACIONFW_DESDE is null ) OR ( c_REGISTRODECUENTA.HMODIFW >= @REGISTRODECUENTA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_HORAMODIFICACIONFW_HASTA is null ) OR ( c_REGISTRODECUENTA.HMODIFW <= @REGISTRODECUENTA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_SERIEALTAFW_DESDE is null ) OR ( c_REGISTRODECUENTA.SALTAFW >= @REGISTRODECUENTA_SERIEALTAFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_SERIEALTAFW_HASTA is null ) OR ( c_REGISTRODECUENTA.SALTAFW <= @REGISTRODECUENTA_SERIEALTAFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_REGISTRODECUENTA.SMODIFW >= @REGISTRODECUENTA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_REGISTRODECUENTA.SMODIFW <= @REGISTRODECUENTA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_USUARIOALTAFW_DESDE is null ) OR ( c_REGISTRODECUENTA.UALTAFW >= @REGISTRODECUENTA_USUARIOALTAFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_USUARIOALTAFW_HASTA is null ) OR ( c_REGISTRODECUENTA.UALTAFW <= @REGISTRODECUENTA_USUARIOALTAFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_REGISTRODECUENTA.UMODIFW >= @REGISTRODECUENTA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_REGISTRODECUENTA.UMODIFW <= @REGISTRODECUENTA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_VERSIONALTAFW_DESDE is null ) OR ( c_REGISTRODECUENTA.VALTAFW >= @REGISTRODECUENTA_VERSIONALTAFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_VERSIONALTAFW_HASTA is null ) OR ( c_REGISTRODECUENTA.VALTAFW <= @REGISTRODECUENTA_VERSIONALTAFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_REGISTRODECUENTA.VMODIFW >= @REGISTRODECUENTA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_REGISTRODECUENTA.VMODIFW <= @REGISTRODECUENTA_VERSIONMODIFICACIONFW_HASTA ) ) and 
	( ( @REGISTRODECUENTA_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_REGISTRODECUENTA.BDAltaFW >= @REGISTRODECUENTA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @REGISTRODECUENTA_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_REGISTRODECUENTA.BDAltaFW <= @REGISTRODECUENTA_BASEDEDATOSALTAFW_HASTA ) )

)