IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_PREPARACIONDEMERCADERIA_PREPARACIONDEMERCADERIA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_PREPARACIONDEMERCADERIA_PREPARACIONDEMERCADERIA];
GO;

CREATE FUNCTION [Listados].[GENERICO_PREPARACIONDEMERCADERIA_PREPARACIONDEMERCADERIA]
( @BaseDeDatos varchar(8),
	@PREPARACIONDEMERCADERIA_CLIENTE_DESDE varchar(10),
	@PREPARACIONDEMERCADERIA_CLIENTE_HASTA varchar(10),
	@PREPARACIONDEMERCADERIA_MONEDACOMPROBANTE_DESDE varchar(10),
	@PREPARACIONDEMERCADERIA_MONEDACOMPROBANTE_HASTA varchar(10),
	@PREPARACIONDEMERCADERIA_CLIENTEDESCRIPCION_DESDE varchar(185),
	@PREPARACIONDEMERCADERIA_CLIENTEDESCRIPCION_HASTA varchar(185),
	@PREPARACIONDEMERCADERIA_VENDEDOR_DESDE varchar(10),
	@PREPARACIONDEMERCADERIA_VENDEDOR_HASTA varchar(10),
	@PREPARACIONDEMERCADERIA_LISTADEPRECIOS_DESDE varchar(6),
	@PREPARACIONDEMERCADERIA_LISTADEPRECIOS_HASTA varchar(6),
	@PREPARACIONDEMERCADERIA_FORPAGO_DESDE varchar(5),
	@PREPARACIONDEMERCADERIA_FORPAGO_HASTA varchar(5),
	@PREPARACIONDEMERCADERIA_MOTIVO_DESDE varchar(3),
	@PREPARACIONDEMERCADERIA_MOTIVO_HASTA varchar(3),
	@PREPARACIONDEMERCADERIA_TRANSPORTISTA_DESDE varchar(15),
	@PREPARACIONDEMERCADERIA_TRANSPORTISTA_HASTA varchar(15),
	@PREPARACIONDEMERCADERIA_LETRA_DESDE varchar(1),
	@PREPARACIONDEMERCADERIA_LETRA_HASTA varchar(1),
	@PREPARACIONDEMERCADERIA_PUNTODEVENTA_DESDE numeric(4, 0),
	@PREPARACIONDEMERCADERIA_PUNTODEVENTA_HASTA numeric(4, 0),
	@PREPARACIONDEMERCADERIA_NUMERO_DESDE numeric(8, 0),
	@PREPARACIONDEMERCADERIA_NUMERO_HASTA numeric(8, 0),
	@PREPARACIONDEMERCADERIA_FECHA_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHA_HASTA datetime,
	@PREPARACIONDEMERCADERIA_FECHADEENTREGA_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHADEENTREGA_HASTA datetime,
	@PREPARACIONDEMERCADERIA_MERCADERIACONSIGNACION bit,
	@PREPARACIONDEMERCADERIA_AJUSTESPORREDONDEOS_DESDE numeric(15, 2),
	@PREPARACIONDEMERCADERIA_AJUSTESPORREDONDEOS_HASTA numeric(15, 2),
	@PREPARACIONDEMERCADERIA_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@PREPARACIONDEMERCADERIA_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@PREPARACIONDEMERCADERIA_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@PREPARACIONDEMERCADERIA_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@CLIENTE_2_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_2_CLIENTE_NOMBRE_HASTA varchar(185),
	@MONEDA_58_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_58_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@VENDEDOR_82_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_82_VENDEDOR_NOMBRE_HASTA varchar(60),
	@LISTADEPRECIOS_83_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_83_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CONDICIONDEPAGO_84_FORPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_84_FORPAGO_DESCRIPCION_HASTA varchar(100),
	@MOTIVO_85_MOTIVO_DESCRIPCION_DESDE varchar(40),
	@MOTIVO_85_MOTIVO_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_86_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_86_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_9139_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9139_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9138_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9138_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9137_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9137_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_3_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_3_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_18_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_18_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_9134_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9134_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9134_LINEA_DESDE varchar(10),
	@SUCURSAL_9134_LINEA_HASTA varchar(10),
	@SUCURSAL_9134_TIPO_DESDE varchar(10),
	@SUCURSAL_9134_TIPO_HASTA varchar(10),
	@SUCURSAL_9134_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9134_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_2_VENDEDOR_DESDE varchar(10),
	@CLIENTE_2_VENDEDOR_HASTA varchar(10),
	@CLIENTE_2_CALLE_DESDE varchar(70),
	@CLIENTE_2_CALLE_HASTA varchar(70),
	@CLIENTE_2_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_2_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_2_CUIT_DESDE varchar(15),
	@CLIENTE_2_CUIT_HASTA varchar(15),
	@CLIENTE_2_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_2_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_2_EMAIL_DESDE varchar(250),
	@CLIENTE_2_EMAIL_HASTA varchar(250),
	@CLIENTE_2_FAX_DESDE varchar(20),
	@CLIENTE_2_FAX_HASTA varchar(20),
	@CLIENTE_2_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_2_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_2_IMAGEN_DESDE varchar(180),
	@CLIENTE_2_IMAGEN_HASTA varchar(180),
	@CLIENTE_2_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_2_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_2_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_2_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_2_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_2_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_2_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_2_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_2_PAIS_DESDE varchar(3),
	@CLIENTE_2_PAIS_HASTA varchar(3),
	@CLIENTE_2_PISO_DESDE varchar(3),
	@CLIENTE_2_PISO_HASTA varchar(3),
	@CLIENTE_2_PROVINCIA_DESDE varchar(2),
	@CLIENTE_2_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_2_TELEFONO_DESDE varchar(30),
	@CLIENTE_2_TELEFONO_HASTA varchar(30),
	@CLIENTE_2_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_2_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_2_MOVIL_DESDE varchar(30),
	@CLIENTE_2_MOVIL_HASTA varchar(30),
	@CLIENTE_2_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_2_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_2_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_2_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_2_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_2_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_2_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_2_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_2_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_2_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_2_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_2_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_2_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_2_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_2_ESTADOCIVIL varchar(13),
	@CLIENTE_2_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_2_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_2_SEXO varchar(10),
	@CLIENTE_2_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_2_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_2_RUT_DESDE varchar(12),
	@CLIENTE_2_RUT_HASTA varchar(12),
	@CLIENTE_2_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_2_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_2_TIPOCLI_DESDE varchar(10),
	@CLIENTE_2_TIPOCLI_HASTA varchar(10),
	@CLIENTE_2_CATEGCLI_DESDE varchar(10),
	@CLIENTE_2_CATEGCLI_HASTA varchar(10),
	@CLIENTE_2_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_2_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_2_SUJETOVINCULADO bit,
	@CLIENTE_2_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_2_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_2_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_2_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_2_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_2_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_2_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_2_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_2_APELLIDO_DESDE varchar(60),
	@CLIENTE_2_APELLIDO_HASTA varchar(60),
	@CLIENTE_2_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_2_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_2_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_2_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_2_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_2_TASACEROAPLICA bit,
	@CLIENTE_2_INACTIVOFW bit,
	@SUCURSAL_9134_CODIGO_DESDE varchar(10),
	@SUCURSAL_9134_CODIGO_HASTA varchar(10),
	@PREPARACIONDEMERCADERIA_FECHAALTAFW_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHAALTAFW_HASTA datetime,
	@PREPARACIONDEMERCADERIA_HORAALTAFW_DESDE varchar(8),
	@PREPARACIONDEMERCADERIA_HORAALTAFW_HASTA varchar(8),
	@PREPARACIONDEMERCADERIA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@PREPARACIONDEMERCADERIA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@PREPARACIONDEMERCADERIA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@PREPARACIONDEMERCADERIA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@PREPARACIONDEMERCADERIA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@PREPARACIONDEMERCADERIA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@PREPARACIONDEMERCADERIA_FECHAEXPO_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHAEXPO_HASTA datetime,
	@PREPARACIONDEMERCADERIA_FECHAIMPO_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHAIMPO_HASTA datetime,
	@PREPARACIONDEMERCADERIA_FECHAMODIFICACIONFW_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHAMODIFICACIONFW_HASTA datetime,
	@PREPARACIONDEMERCADERIA_FECHATRANSFERENCIA_DESDE datetime,
	@PREPARACIONDEMERCADERIA_FECHATRANSFERENCIA_HASTA datetime,
	@PREPARACIONDEMERCADERIA_HORAEXPO_DESDE varchar(8),
	@PREPARACIONDEMERCADERIA_HORAEXPO_HASTA varchar(8),
	@PREPARACIONDEMERCADERIA_HORAIMPO_DESDE varchar(8),
	@PREPARACIONDEMERCADERIA_HORAIMPO_HASTA varchar(8),
	@PREPARACIONDEMERCADERIA_HORAMODIFICACIONFW_DESDE varchar(8),
	@PREPARACIONDEMERCADERIA_HORAMODIFICACIONFW_HASTA varchar(8),
	@PREPARACIONDEMERCADERIA_SERIEALTAFW_DESDE varchar(7),
	@PREPARACIONDEMERCADERIA_SERIEALTAFW_HASTA varchar(7),
	@PREPARACIONDEMERCADERIA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@PREPARACIONDEMERCADERIA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@PREPARACIONDEMERCADERIA_USUARIOALTAFW_DESDE varchar(100),
	@PREPARACIONDEMERCADERIA_USUARIOALTAFW_HASTA varchar(100),
	@PREPARACIONDEMERCADERIA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@PREPARACIONDEMERCADERIA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@PREPARACIONDEMERCADERIA_VERSIONALTAFW_DESDE varchar(13),
	@PREPARACIONDEMERCADERIA_VERSIONALTAFW_HASTA varchar(13),
	@PREPARACIONDEMERCADERIA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@PREPARACIONDEMERCADERIA_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_preparaciondemercaderia.codigo, 38, ' ' ) as varchar( 46 ) ) as PREPARACIONDEMERCADERIA__Grupo,
	@basededatos as PREPARACIONDEMERCADERIA__BD,
	c_PREPARACIONDEMERCADERIA.CODIGO as PREPARACIONDEMERCADERIA_CODIGO,
	c_PREPARACIONDEMERCADERIA.FPERSON as PREPARACIONDEMERCADERIA_FPerson,
	C_CLIENTE.CIMAGEN as CLIENTE_CIMAGEN,
	c_PREPARACIONDEMERCADERIA.MONEDA as PREPARACIONDEMERCADERIA_Moneda,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.fsubtot as numeric( 15, 4 ) ) as PREPARACIONDEMERCADERIA_FSubTOT,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.fsubton as numeric( 15, 4 ) ) as PREPARACIONDEMERCADERIA_fSubToN,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.totalcant as numeric( 16, 3 ) ) as PREPARACIONDEMERCADERIA_TotalCant,
	c_PREPARACIONDEMERCADERIA.FCLIENTE as PREPARACIONDEMERCADERIA_FCLIENTE,
	c_PREPARACIONDEMERCADERIA.FVEN as PREPARACIONDEMERCADERIA_FVEN,
	c_PREPARACIONDEMERCADERIA.CODLISTA as PREPARACIONDEMERCADERIA_CodLista,
	c_PREPARACIONDEMERCADERIA.FPAGO as PREPARACIONDEMERCADERIA_FPago,
	c_PREPARACIONDEMERCADERIA.MOTIVO as PREPARACIONDEMERCADERIA_MOTIVO,
	c_PREPARACIONDEMERCADERIA.FTRANSP as PREPARACIONDEMERCADERIA_FTransp,
	c_PREPARACIONDEMERCADERIA.FLETRA as PREPARACIONDEMERCADERIA_FLETRA,
	c_PREPARACIONDEMERCADERIA.FPTOVEN as PREPARACIONDEMERCADERIA_FPTOVEN,
	c_PREPARACIONDEMERCADERIA.FNUMCOMP as PREPARACIONDEMERCADERIA_FNUMCOMP,
	case when c_preparaciondemercaderia.ffch = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.ffch end as PREPARACIONDEMERCADERIA_FFCH,
	case when c_preparaciondemercaderia.ffchent = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.ffchent end as PREPARACIONDEMERCADERIA_FFCHENT,
	c_PREPARACIONDEMERCADERIA.MERCONSIGN as PREPARACIONDEMERCADERIA_MerConsign,
	c_PREPARACIONDEMERCADERIA.FAJXRE as PREPARACIONDEMERCADERIA_FAjXRe,
	c_PREPARACIONDEMERCADERIA.FPODES as PREPARACIONDEMERCADERIA_FPODES,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*-1*c_preparaciondemercaderia.fdescu as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_fDescu,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*-1*c_preparaciondemercaderia.md3 as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_MD3,
	c_PREPARACIONDEMERCADERIA.FOBS as PREPARACIONDEMERCADERIA_FObs,
	c_PREPARACIONDEMERCADERIA.RECPOR as PREPARACIONDEMERCADERIA_RecPor,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.mr as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_MR,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.mr1 as numeric( 17, 4 ) ) as PREPARACIONDEMERCADERIA_MR1,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.mr2 as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_MR2,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.percepcion as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_percepcion,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.fimpuesto as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_fImpuesto,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.gravamen as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_gravamen,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.totimpue as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_totimpue,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*-1*c_preparaciondemercaderia.totdescsi as numeric( 15, 4 ) ) as PREPARACIONDEMERCADERIA_totdescSI,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*-1*c_preparaciondemercaderia.tdci as numeric( 15, 4 ) ) as PREPARACIONDEMERCADERIA_TDCI,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.totrecarsi as numeric( 15, 4 ) ) as PREPARACIONDEMERCADERIA_totrecarSI,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.trci as numeric( 15, 4 ) ) as PREPARACIONDEMERCADERIA_TRCI,
	cast( c_preparaciondemercaderia.signomov*c_preparaciondemercaderia.cotiz*c_preparaciondemercaderia.ftotal as numeric( 15, 2 ) ) as PREPARACIONDEMERCADERIA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CLIENTE.CLVEND as CLIENTE_CLVend,
	C_CLIENTE.CLCALLE as CLIENTE_CLCalle,
	C_CLIENTE.CLCP as CLIENTE_CLCP,
	C_CLIENTE.CLCUIT as CLIENTE_CLCUIT,
	C_CLIENTE.CLDEPTO as CLIENTE_CLDEPTO,
	C_CLIENTE.CLEMAIL as CLIENTE_CLEMAIL,
	C_CLIENTE.CLFAX as CLIENTE_CLFAX,
	case when c_cliente.clfecha = '01/01/1900 00:00:00' then null else c_cliente.clfecha end as CLIENTE_CLFECHA,
	C_CLIENTE.CLLOC as CLIENTE_CLLOC,
	C_CLIENTE.CLNRODOC as CLIENTE_CLNRODOC,
	C_CLIENTE.CLNRO as CLIENTE_CLNro,
	C_CLIENTE.CLOBS as CLIENTE_CLOBS,
	C_CLIENTE.CLPAGEWEB as CLIENTE_CLPAGEWEB,
	C_CLIENTE.CLPAIS as CLIENTE_CLPAIS,
	C_CLIENTE.CLPISO as CLIENTE_ClPiso,
	C_CLIENTE.CLPRV as CLIENTE_CLPRV,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_CLIENTE.CLTLF as CLIENTE_CLTLF,
	C_CLIENTE.CLTIPODOC as CLIENTE_CLTIPODOC,
	C_CLIENTE.CLMOVIL as CLIENTE_CLMovil,
	C_CLIENTE.CLTOPECCTE as CLIENTE_CLTOPECCTE,
	C_CLIENTE.CLLISPREC as CLIENTE_CLLisPrec,
	C_CLIENTE.CLCLAS as CLIENTE_CLCLAS,
	C_CLIENTE.CLTIPCONV as CLIENTE_CLTIPCONV,
	C_CLIENTE.CLNROIIBB as CLIENTE_CLNROIIBB,
	C_CLIENTE.CLCO_DTO as CLIENTE_CLCO_DTO,
	C_CLIENTE.CLTRANS as CLIENTE_CLTRANS,
	C_CLIENTE.ESTADO as CLIENTE_Estado,
	C_CLIENTE.HIJOS as CLIENTE_Hijos,
	C_CLIENTE.SEXO as CLIENTE_Sexo,
	C_CLIENTE.GLOBALID as CLIENTE_globalid,
	C_CLIENTE.RUT as CLIENTE_RUT,
	C_CLIENTE.CLCODFANT as CLIENTE_CLCODFANT,
	C_CLIENTE.CLTIPOCLI as CLIENTE_CLTipoCli,
	C_CLIENTE.CLCATEGCLI as CLIENTE_CLCategCli,
	C_CLIENTE.CLCONDPAG as CLIENTE_CLCONDPAG,
	C_CLIENTE.CLSUJVINC as CLIENTE_CLSujVinc,
	C_CLIENTE.CLPERTIVA as CLIENTE_CLPERTIVA,
	C_CLIENTE.CLSITGAN as CLIENTE_CLSITGAN,
	C_CLIENTE.EXPERIVA as CLIENTE_EXPERIVA,
	C_CLIENTE.CLPERGAN as CLIENTE_CLPERGAN,
	C_CLIENTE.EXPERGAN as CLIENTE_EXPERGAN,
	C_CLIENTE.CODRECOM as CLIENTE_CODRECOM,
	C_CLIENTE.NOMRECOM as CLIENTE_NOMRECOM,
	C_CLIENTE.CLPRINOM as CLIENTE_CLPRINOM,
	C_CLIENTE.CLSEGNOM as CLIENTE_CLSEGNOM,
	C_CLIENTE.CLAPELL as CLIENTE_CLAPELL,
	case when c_cliente.vhastaiva = '01/01/1900 00:00:00' then null else c_cliente.vhastaiva end as CLIENTE_VHastaIva,
	case when c_cliente.vhastagan = '01/01/1900 00:00:00' then null else c_cliente.vhastagan end as CLIENTE_VHastaGan,
	C_CLIENTE.CLSIPRIB as CLIENTE_CLSIPRIB,
	C_CLIENTE.PORCENTC as CLIENTE_PorcenTC,
	C_CLIENTE.APLICATC as CLIENTE_AplicaTC,
	C_CLIENTE.INACTIVOFW as CLIENTE_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	case when c_preparaciondemercaderia.faltafw = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.faltafw end as PREPARACIONDEMERCADERIA_FAltaFW,
	c_PREPARACIONDEMERCADERIA.HALTAFW as PREPARACIONDEMERCADERIA_HAltaFW,
	c_PREPARACIONDEMERCADERIA.BDALTAFW as PREPARACIONDEMERCADERIA_BDALTAFW,
	c_PREPARACIONDEMERCADERIA.BDMODIFW as PREPARACIONDEMERCADERIA_BDMODIFW,
	c_PREPARACIONDEMERCADERIA.ESTTRANS as PREPARACIONDEMERCADERIA_ESTTRANS,
	case when c_preparaciondemercaderia.fecexpo = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.fecexpo end as PREPARACIONDEMERCADERIA_FECEXPO,
	case when c_preparaciondemercaderia.fecimpo = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.fecimpo end as PREPARACIONDEMERCADERIA_FECIMPO,
	case when c_preparaciondemercaderia.fmodifw = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.fmodifw end as PREPARACIONDEMERCADERIA_FMODIFW,
	case when c_preparaciondemercaderia.fectrans = '01/01/1900 00:00:00' then null else c_preparaciondemercaderia.fectrans end as PREPARACIONDEMERCADERIA_FECTRANS,
	c_PREPARACIONDEMERCADERIA.HORAEXPO as PREPARACIONDEMERCADERIA_HORAEXPO,
	c_PREPARACIONDEMERCADERIA.HORAIMPO as PREPARACIONDEMERCADERIA_HORAIMPO,
	c_PREPARACIONDEMERCADERIA.HMODIFW as PREPARACIONDEMERCADERIA_HMODIFW,
	c_PREPARACIONDEMERCADERIA.SALTAFW as PREPARACIONDEMERCADERIA_SALTAFW,
	c_PREPARACIONDEMERCADERIA.SMODIFW as PREPARACIONDEMERCADERIA_SMODIFW,
	c_PREPARACIONDEMERCADERIA.UALTAFW as PREPARACIONDEMERCADERIA_UALTAFW,
	c_PREPARACIONDEMERCADERIA.UMODIFW as PREPARACIONDEMERCADERIA_UMODIFW,
	c_PREPARACIONDEMERCADERIA.VALTAFW as PREPARACIONDEMERCADERIA_VALTAFW,
	c_PREPARACIONDEMERCADERIA.VMODIFW as PREPARACIONDEMERCADERIA_VMODIFW,
	c_PREPARACIONDEMERCADERIA.ZADSFW as PREPARACIONDEMERCADERIA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as PREPARACIONDEMERCADERIA__SUCURSAL,
	cast( funciones.identificadordecomprobanteparalistado(c_preparaciondemercaderia.facttipo, c_preparaciondemercaderia.fletra, c_preparaciondemercaderia.fptoven, c_preparaciondemercaderia.fnumcomp) as varchar( 20 ) ) as PREPARACIONDEMERCADERIA_ComprobanteVirtual,
	C_CLIENTE.CLNOM as CLIENTE_CLNOM,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_VENDEDOR82.CLNOM as VENDEDOR82_CLNOM,
	C_LISTADEPRECIOS83.LPR_NOMBRE as LISTADEPRECIOS83_LPR_NOMBRE,
	C_CONDICIONDEPAGO84.CLNOM as CONDICIONDEPAGO84_CLNOM,
	C_MOTIVO.MOTDES as MOTIVO_MOTDES,
	C_TRANSPORTISTA86.TRNOM as TRANSPORTISTA86_TRNOM,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_VENDEDOR3.CLNOM as VENDEDOR3_CLNOM,
	C_PAISES.PDES as PAISES_pdes,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_CLIENTE.CLIVA as CLIENTE_CLIVA,
	C_LISTADEPRECIOS26.LPR_NOMBRE as LISTADEPRECIOS26_LPR_NOMBRE,
	C_CLASIFICACIONCLIENTE.CLADES as CLASIFICACIONCLIENTE_CLADES,
	C_DESCUENTO.DES as DESCUENTO_Des,
	C_TRANSPORTISTA31.TRNOM as TRANSPORTISTA31_TRNOM,
	C_NOMBREDEFANTASIA.NFCOD as NOMBREDEFANTASIA_NFCOD,
	C_TIPOCLIENTE.TCDES as TIPOCLIENTE_TCDES,
	C_CATEGORIACLIENTE.CGDES as CATEGORIACLIENTE_CGDes,
	C_CONDICIONDEPAGO40.CLNOM as CONDICIONDEPAGO40_CLNOM,
	C_IMPUESTO42.DESCRIP as IMPUESTO42_descrip,
	C_IMPUESTO45.DESCRIP as IMPUESTO45_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_CATEGORIACLIENTE.CGCOD as CATEGORIACLIENTE_CGCod,
	C_CLASIFICACIONCLIENTE.CLACOD as CLASIFICACIONCLIENTE_CLACOD,
	C_CLIENTE.CLCOD as CLIENTE_CLCOD,
	C_CONDICIONDEPAGO40.CLCOD as CONDICIONDEPAGO40_CLCOD,
	C_CONDICIONDEPAGO84.CLCOD as CONDICIONDEPAGO84_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DESCUENTO.CODIGO as DESCUENTO_codigo,
	C_IMPUESTO42.CODIGO as IMPUESTO42_codigo,
	C_IMPUESTO45.CODIGO as IMPUESTO45_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS26.LPR_NUMERO as LISTADEPRECIOS26_LPR_NUMERO,
	C_LISTADEPRECIOS83.LPR_NUMERO as LISTADEPRECIOS83_LPR_NUMERO,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_MOTIVO.MOTCOD as MOTIVO_MOTCOD,
	C_PAISES.PCOD as PAISES_pcod,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOCLIENTE.TCCOD as TIPOCLIENTE_TCCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA31.TRCOD as TRANSPORTISTA31_TRCOD,
	C_TRANSPORTISTA86.TRCOD as TRANSPORTISTA86_TRCOD,
	C_VENDEDOR3.CLCOD as VENDEDOR3_CLCOD,
	C_VENDEDOR82.CLCOD as VENDEDOR82_CLCOD
 from ZooLogic.COMPROBANTEV as c_PREPARACIONDEMERCADERIA
 left join ZooLogic.CLI as C_CLIENTE on C_CLIENTE.CLCOD = C_PREPARACIONDEMERCADERIA.FPERSON and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO40 on C_CONDICIONDEPAGO40.CLCOD = C_CLIENTE.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE.CLCONDPAG )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO84 on C_CONDICIONDEPAGO84.CLCOD = C_PREPARACIONDEMERCADERIA.FPAGO and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.FPAGO )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_CLIENTE.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO on C_DESCUENTO.CODIGO = C_CLIENTE.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO42 on C_IMPUESTO42.CODIGO = C_CLIENTE.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO45 on C_IMPUESTO45.CODIGO = C_CLIENTE.CLPERGAN and 0 = Funciones.empty( C_CLIENTE.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS26 on C_LISTADEPRECIOS26.LPR_NUMERO = C_CLIENTE.CLLISPREC and 0 = Funciones.empty( C_CLIENTE.CLLISPREC )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS83 on C_LISTADEPRECIOS83.LPR_NUMERO = C_PREPARACIONDEMERCADERIA.CODLISTA and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_PREPARACIONDEMERCADERIA.MONEDA and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.MONEDA )
 left join ZooLogic.MOTIVO as C_MOTIVO on C_MOTIVO.MOTCOD = C_PREPARACIONDEMERCADERIA.MOTIVO and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.MOTIVO )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_CLIENTE.CLPAIS and 0 = Funciones.empty( C_CLIENTE.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_CLIENTE.CLPRV and 0 = Funciones.empty( C_CLIENTE.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_CLIENTE.CLIVA and 0 = Funciones.empty( C_CLIENTE.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE on C_TIPOCLIENTE.TCCOD = C_CLIENTE.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA31 on C_TRANSPORTISTA31.TRCOD = C_CLIENTE.CLTRANS and 0 = Funciones.empty( C_CLIENTE.CLTRANS )
 left join ZooLogic.TRA as C_TRANSPORTISTA86 on C_TRANSPORTISTA86.TRCOD = C_PREPARACIONDEMERCADERIA.FTRANSP and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.FTRANSP )
 left join ZooLogic.VEN as C_VENDEDOR3 on C_VENDEDOR3.CLCOD = C_CLIENTE.CLVEND and 0 = Funciones.empty( C_CLIENTE.CLVEND )
 left join ZooLogic.VEN as C_VENDEDOR82 on C_VENDEDOR82.CLCOD = C_PREPARACIONDEMERCADERIA.FVEN and 0 = Funciones.empty( C_PREPARACIONDEMERCADERIA.FVEN )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA on C_NOMBREDEFANTASIA.NFCOD = C_CLIENTE.CLCODFANT and 0 = Funciones.empty( C_CLIENTE.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE on C_CATEGORIACLIENTE.CGCOD = C_CLIENTE.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE on C_CLASIFICACIONCLIENTE.CLACOD = C_CLIENTE.CLCLAS and 0 = Funciones.empty( C_CLIENTE.CLCLAS )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( not 1 = funciones.empty( c_preparaciondemercaderia.codigo ) and c_preparaciondemercaderia.facttipo = 57 ) and 
	( ( @PREPARACIONDEMERCADERIA_CLIENTE_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FPerson >= @PREPARACIONDEMERCADERIA_CLIENTE_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_CLIENTE_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FPerson <= @PREPARACIONDEMERCADERIA_CLIENTE_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_MONEDACOMPROBANTE_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.Moneda >= @PREPARACIONDEMERCADERIA_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_MONEDACOMPROBANTE_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.Moneda <= @PREPARACIONDEMERCADERIA_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_CLIENTEDESCRIPCION_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FCLIENTE >= @PREPARACIONDEMERCADERIA_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_CLIENTEDESCRIPCION_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FCLIENTE <= @PREPARACIONDEMERCADERIA_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_VENDEDOR_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FVEN >= @PREPARACIONDEMERCADERIA_VENDEDOR_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_VENDEDOR_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FVEN <= @PREPARACIONDEMERCADERIA_VENDEDOR_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_LISTADEPRECIOS_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.CodLista >= @PREPARACIONDEMERCADERIA_LISTADEPRECIOS_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_LISTADEPRECIOS_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.CodLista <= @PREPARACIONDEMERCADERIA_LISTADEPRECIOS_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FORPAGO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FPago >= @PREPARACIONDEMERCADERIA_FORPAGO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FORPAGO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FPago <= @PREPARACIONDEMERCADERIA_FORPAGO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_MOTIVO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.MOTIVO >= @PREPARACIONDEMERCADERIA_MOTIVO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_MOTIVO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.MOTIVO <= @PREPARACIONDEMERCADERIA_MOTIVO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_TRANSPORTISTA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FTransp >= @PREPARACIONDEMERCADERIA_TRANSPORTISTA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_TRANSPORTISTA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FTransp <= @PREPARACIONDEMERCADERIA_TRANSPORTISTA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_LETRA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FLETRA >= @PREPARACIONDEMERCADERIA_LETRA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_LETRA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FLETRA <= @PREPARACIONDEMERCADERIA_LETRA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_PUNTODEVENTA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FPTOVEN >= @PREPARACIONDEMERCADERIA_PUNTODEVENTA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_PUNTODEVENTA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FPTOVEN <= @PREPARACIONDEMERCADERIA_PUNTODEVENTA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_NUMERO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FNUMCOMP >= @PREPARACIONDEMERCADERIA_NUMERO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_NUMERO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FNUMCOMP <= @PREPARACIONDEMERCADERIA_NUMERO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FFCH >= @PREPARACIONDEMERCADERIA_FECHA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FFCH <= @PREPARACIONDEMERCADERIA_FECHA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHADEENTREGA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FFCHENT >= @PREPARACIONDEMERCADERIA_FECHADEENTREGA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHADEENTREGA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FFCHENT <= @PREPARACIONDEMERCADERIA_FECHADEENTREGA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_MERCADERIACONSIGNACION is null ) OR ( c_PREPARACIONDEMERCADERIA.MerConsign = @PREPARACIONDEMERCADERIA_MERCADERIACONSIGNACION ) ) and 
	( ( @PREPARACIONDEMERCADERIA_AJUSTESPORREDONDEOS_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FAjXRe >= @PREPARACIONDEMERCADERIA_AJUSTESPORREDONDEOS_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_AJUSTESPORREDONDEOS_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FAjXRe <= @PREPARACIONDEMERCADERIA_AJUSTESPORREDONDEOS_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_PORCENTAJEDESCUENTO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FPODES >= @PREPARACIONDEMERCADERIA_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_PORCENTAJEDESCUENTO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FPODES <= @PREPARACIONDEMERCADERIA_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_RECARGOPORCENTAJE_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.RecPor >= @PREPARACIONDEMERCADERIA_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_RECARGOPORCENTAJE_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.RecPor <= @PREPARACIONDEMERCADERIA_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE.CLNOM >= @CLIENTE_2_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE.CLNOM <= @CLIENTE_2_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @MONEDA_58_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_58_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_58_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_58_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_82_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR82.CLNOM >= @VENDEDOR_82_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_82_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR82.CLNOM <= @VENDEDOR_82_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @LISTADEPRECIOS_83_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS83.LPR_NOMBRE >= @LISTADEPRECIOS_83_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_83_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS83.LPR_NOMBRE <= @LISTADEPRECIOS_83_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_84_FORPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO84.CLNOM >= @CONDICIONDEPAGO_84_FORPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_84_FORPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO84.CLNOM <= @CONDICIONDEPAGO_84_FORPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @MOTIVO_85_MOTIVO_DESCRIPCION_DESDE is null ) OR ( C_MOTIVO.MOTDES >= @MOTIVO_85_MOTIVO_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVO_85_MOTIVO_DESCRIPCION_HASTA is null ) OR ( C_MOTIVO.MOTDES <= @MOTIVO_85_MOTIVO_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_86_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA86.TRNOM >= @TRANSPORTISTA_86_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_86_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA86.TRNOM <= @TRANSPORTISTA_86_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_9139_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9139_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9139_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9139_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9138_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9138_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9138_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9138_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9137_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9137_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9137_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9137_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR3.CLNOM >= @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR3.CLNOM <= @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_18_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_18_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS26.LPR_NOMBRE >= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS26.LPR_NOMBRE <= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES >= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES <= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO.Des >= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO.Des <= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA31.TRNOM >= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA31.TRNOM <= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA.NFCOD >= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA.NFCOD <= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE.TCDES >= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE.TCDES <= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE.CGDes >= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE.CGDes <= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO40.CLNOM >= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO40.CLNOM <= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO42.descrip >= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO42.descrip <= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO45.descrip >= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO45.descrip <= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9134_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9134_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9134_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9134_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9134_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9134_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9134_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9134_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9134_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9134_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9134_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9134_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9134_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9134_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9134_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9134_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_2_VENDEDOR_DESDE is null ) OR ( C_CLIENTE.CLVend >= @CLIENTE_2_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_2_VENDEDOR_HASTA is null ) OR ( C_CLIENTE.CLVend <= @CLIENTE_2_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_2_CALLE_DESDE is null ) OR ( C_CLIENTE.CLCalle >= @CLIENTE_2_CALLE_DESDE ) ) and 
	( ( @CLIENTE_2_CALLE_HASTA is null ) OR ( C_CLIENTE.CLCalle <= @CLIENTE_2_CALLE_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE.CLCP >= @CLIENTE_2_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE.CLCP <= @CLIENTE_2_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_2_CUIT_DESDE is null ) OR ( C_CLIENTE.CLCUIT >= @CLIENTE_2_CUIT_DESDE ) ) and 
	( ( @CLIENTE_2_CUIT_HASTA is null ) OR ( C_CLIENTE.CLCUIT <= @CLIENTE_2_CUIT_HASTA ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE.CLDEPTO >= @CLIENTE_2_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE.CLDEPTO <= @CLIENTE_2_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_EMAIL_DESDE is null ) OR ( C_CLIENTE.CLEMAIL >= @CLIENTE_2_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_2_EMAIL_HASTA is null ) OR ( C_CLIENTE.CLEMAIL <= @CLIENTE_2_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_2_FAX_DESDE is null ) OR ( C_CLIENTE.CLFAX >= @CLIENTE_2_FAX_DESDE ) ) and 
	( ( @CLIENTE_2_FAX_HASTA is null ) OR ( C_CLIENTE.CLFAX <= @CLIENTE_2_FAX_HASTA ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE.CLFECHA >= @CLIENTE_2_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE.CLFECHA <= @CLIENTE_2_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_2_IMAGEN_DESDE is null ) OR ( C_CLIENTE.CIMAGEN >= @CLIENTE_2_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_2_IMAGEN_HASTA is null ) OR ( C_CLIENTE.CIMAGEN <= @CLIENTE_2_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE.CLLOC >= @CLIENTE_2_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE.CLLOC <= @CLIENTE_2_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLNRODOC >= @CLIENTE_2_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLNRODOC <= @CLIENTE_2_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_NUMERO_DESDE is null ) OR ( C_CLIENTE.CLNro >= @CLIENTE_2_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_2_NUMERO_HASTA is null ) OR ( C_CLIENTE.CLNro <= @CLIENTE_2_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE.CLPAGEWEB >= @CLIENTE_2_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE.CLPAGEWEB <= @CLIENTE_2_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_2_PAIS_DESDE is null ) OR ( C_CLIENTE.CLPAIS >= @CLIENTE_2_PAIS_DESDE ) ) and 
	( ( @CLIENTE_2_PAIS_HASTA is null ) OR ( C_CLIENTE.CLPAIS <= @CLIENTE_2_PAIS_HASTA ) ) and 
	( ( @CLIENTE_2_PISO_DESDE is null ) OR ( C_CLIENTE.ClPiso >= @CLIENTE_2_PISO_DESDE ) ) and 
	( ( @CLIENTE_2_PISO_HASTA is null ) OR ( C_CLIENTE.ClPiso <= @CLIENTE_2_PISO_HASTA ) ) and 
	( ( @CLIENTE_2_PROVINCIA_DESDE is null ) OR ( C_CLIENTE.CLPRV >= @CLIENTE_2_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_2_PROVINCIA_HASTA is null ) OR ( C_CLIENTE.CLPRV <= @CLIENTE_2_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_2_TELEFONO_DESDE is null ) OR ( C_CLIENTE.CLTLF >= @CLIENTE_2_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_2_TELEFONO_HASTA is null ) OR ( C_CLIENTE.CLTLF <= @CLIENTE_2_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLTIPODOC >= @CLIENTE_2_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLTIPODOC <= @CLIENTE_2_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_MOVIL_DESDE is null ) OR ( C_CLIENTE.CLMovil >= @CLIENTE_2_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_2_MOVIL_HASTA is null ) OR ( C_CLIENTE.CLMovil <= @CLIENTE_2_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE.CLTOPECCTE >= @CLIENTE_2_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE.CLTOPECCTE <= @CLIENTE_2_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE.CLLisPrec >= @CLIENTE_2_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE.CLLisPrec <= @CLIENTE_2_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE.CLCLAS >= @CLIENTE_2_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE.CLCLAS <= @CLIENTE_2_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE.CLTIPCONV >= @CLIENTE_2_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE.CLTIPCONV <= @CLIENTE_2_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_2_NROIIBB_DESDE is null ) OR ( C_CLIENTE.CLNROIIBB >= @CLIENTE_2_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_2_NROIIBB_HASTA is null ) OR ( C_CLIENTE.CLNROIIBB <= @CLIENTE_2_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE.CLCO_DTO >= @CLIENTE_2_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE.CLCO_DTO <= @CLIENTE_2_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE.CLTRANS >= @CLIENTE_2_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE.CLTRANS <= @CLIENTE_2_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_2_ESTADOCIVIL is null ) OR ( C_CLIENTE.Estado = @CLIENTE_2_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_2_HIJOS_DESDE is null ) OR ( C_CLIENTE.Hijos >= @CLIENTE_2_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_2_HIJOS_HASTA is null ) OR ( C_CLIENTE.Hijos <= @CLIENTE_2_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_2_SEXO is null ) OR ( C_CLIENTE.Sexo = @CLIENTE_2_SEXO ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE.globalid >= @CLIENTE_2_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE.globalid <= @CLIENTE_2_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_2_RUT_DESDE is null ) OR ( C_CLIENTE.RUT >= @CLIENTE_2_RUT_DESDE ) ) and 
	( ( @CLIENTE_2_RUT_HASTA is null ) OR ( C_CLIENTE.RUT <= @CLIENTE_2_RUT_HASTA ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE.CLCODFANT >= @CLIENTE_2_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE.CLCODFANT <= @CLIENTE_2_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCLI_DESDE is null ) OR ( C_CLIENTE.CLTipoCli >= @CLIENTE_2_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCLI_HASTA is null ) OR ( C_CLIENTE.CLTipoCli <= @CLIENTE_2_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CATEGCLI_DESDE is null ) OR ( C_CLIENTE.CLCategCli >= @CLIENTE_2_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_2_CATEGCLI_HASTA is null ) OR ( C_CLIENTE.CLCategCli <= @CLIENTE_2_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE.CLCONDPAG >= @CLIENTE_2_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE.CLCONDPAG <= @CLIENTE_2_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_2_SUJETOVINCULADO is null ) OR ( C_CLIENTE.CLSujVinc = @CLIENTE_2_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE.CLPERTIVA >= @CLIENTE_2_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE.CLPERTIVA <= @CLIENTE_2_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_2_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE.CLSITGAN = @CLIENTE_2_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE.EXPERIVA = @CLIENTE_2_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE.CLPERGAN >= @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE.CLPERGAN <= @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE.EXPERGAN = @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.CODRECOM >= @CLIENTE_2_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.CODRECOM <= @CLIENTE_2_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.NOMRECOM >= @CLIENTE_2_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.NOMRECOM <= @CLIENTE_2_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE.CLPRINOM >= @CLIENTE_2_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE.CLPRINOM <= @CLIENTE_2_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE.CLSEGNOM >= @CLIENTE_2_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE.CLSEGNOM <= @CLIENTE_2_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_APELLIDO_DESDE is null ) OR ( C_CLIENTE.CLAPELL >= @CLIENTE_2_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_2_APELLIDO_HASTA is null ) OR ( C_CLIENTE.CLAPELL <= @CLIENTE_2_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE.VHastaIva >= @CLIENTE_2_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE.VHastaIva <= @CLIENTE_2_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE.VHastaGan >= @CLIENTE_2_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE.VHastaGan <= @CLIENTE_2_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE.CLSIPRIB >= @CLIENTE_2_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE.CLSIPRIB <= @CLIENTE_2_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE.PorcenTC >= @CLIENTE_2_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE.PorcenTC <= @CLIENTE_2_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROAPLICA is null ) OR ( C_CLIENTE.AplicaTC = @CLIENTE_2_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_2_INACTIVOFW is null ) OR ( C_CLIENTE.InactivoFW = @CLIENTE_2_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9134_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9134_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9134_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9134_CODIGO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAALTAFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FAltaFW >= @PREPARACIONDEMERCADERIA_FECHAALTAFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAALTAFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FAltaFW <= @PREPARACIONDEMERCADERIA_FECHAALTAFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAALTAFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.HAltaFW >= @PREPARACIONDEMERCADERIA_HORAALTAFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAALTAFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.HAltaFW <= @PREPARACIONDEMERCADERIA_HORAALTAFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.BDALTAFW >= @PREPARACIONDEMERCADERIA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.BDALTAFW <= @PREPARACIONDEMERCADERIA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.BDMODIFW >= @PREPARACIONDEMERCADERIA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.BDMODIFW <= @PREPARACIONDEMERCADERIA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.ESTTRANS >= @PREPARACIONDEMERCADERIA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.ESTTRANS <= @PREPARACIONDEMERCADERIA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAEXPO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FECEXPO >= @PREPARACIONDEMERCADERIA_FECHAEXPO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAEXPO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FECEXPO <= @PREPARACIONDEMERCADERIA_FECHAEXPO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAIMPO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FECIMPO >= @PREPARACIONDEMERCADERIA_FECHAIMPO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAIMPO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FECIMPO <= @PREPARACIONDEMERCADERIA_FECHAIMPO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FMODIFW >= @PREPARACIONDEMERCADERIA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FMODIFW <= @PREPARACIONDEMERCADERIA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHATRANSFERENCIA_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.FECTRANS >= @PREPARACIONDEMERCADERIA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_FECHATRANSFERENCIA_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.FECTRANS <= @PREPARACIONDEMERCADERIA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAEXPO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.HORAEXPO >= @PREPARACIONDEMERCADERIA_HORAEXPO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAEXPO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.HORAEXPO <= @PREPARACIONDEMERCADERIA_HORAEXPO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAIMPO_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.HORAIMPO >= @PREPARACIONDEMERCADERIA_HORAIMPO_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAIMPO_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.HORAIMPO <= @PREPARACIONDEMERCADERIA_HORAIMPO_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAMODIFICACIONFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.HMODIFW >= @PREPARACIONDEMERCADERIA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_HORAMODIFICACIONFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.HMODIFW <= @PREPARACIONDEMERCADERIA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_SERIEALTAFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.SALTAFW >= @PREPARACIONDEMERCADERIA_SERIEALTAFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_SERIEALTAFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.SALTAFW <= @PREPARACIONDEMERCADERIA_SERIEALTAFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.SMODIFW >= @PREPARACIONDEMERCADERIA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.SMODIFW <= @PREPARACIONDEMERCADERIA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_USUARIOALTAFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.UALTAFW >= @PREPARACIONDEMERCADERIA_USUARIOALTAFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_USUARIOALTAFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.UALTAFW <= @PREPARACIONDEMERCADERIA_USUARIOALTAFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.UMODIFW >= @PREPARACIONDEMERCADERIA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.UMODIFW <= @PREPARACIONDEMERCADERIA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_VERSIONALTAFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.VALTAFW >= @PREPARACIONDEMERCADERIA_VERSIONALTAFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_VERSIONALTAFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.VALTAFW <= @PREPARACIONDEMERCADERIA_VERSIONALTAFW_HASTA ) ) and 
	( ( @PREPARACIONDEMERCADERIA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_PREPARACIONDEMERCADERIA.VMODIFW >= @PREPARACIONDEMERCADERIA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @PREPARACIONDEMERCADERIA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_PREPARACIONDEMERCADERIA.VMODIFW <= @PREPARACIONDEMERCADERIA_VERSIONMODIFICACIONFW_HASTA ) )

)