IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_PICKING_PICKING]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_PICKING_PICKING];
GO;

CREATE FUNCTION [Listados].[GENERICO_PICKING_PICKING]
( @BaseDeDatos varchar(8),
	@PICKING_TIPOCOMPROBANTEORIGEN varchar(40),
	@PICKING_VENDEDOR_DESDE varchar(10),
	@PICKING_VENDEDOR_HASTA varchar(10),
	@PICKING_CLIENTE_DESDE varchar(10),
	@PICKING_CLIENTE_HASTA varchar(10),
	@PICKING_CLIENTEDESCRIPCION_DESDE varchar(185),
	@PICKING_CLIENTEDESCRIPCION_HASTA varchar(185),
	@PICKING_NUMERO_DESDE numeric(8, 0),
	@PICKING_NUMERO_HASTA numeric(8, 0),
	@PICKING_FECHA_DESDE datetime,
	@PICKING_FECHA_HASTA datetime,
	@VENDEDOR_22_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_22_VENDEDOR_NOMBRE_HASTA varchar(60),
	@CLIENTE_23_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_23_CLIENTE_NOMBRE_HASTA varchar(185),
	@SEGMENTACION_9150_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9150_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9149_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9149_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9148_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9148_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_24_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_24_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_39_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_39_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_41_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_41_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_47_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_47_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_48_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_48_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_51_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_51_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_52_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_52_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_58_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_58_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_59_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_59_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_60_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_60_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_63_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_63_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_66_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_66_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_75_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_75_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_9145_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9145_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9145_LINEA_DESDE varchar(10),
	@SUCURSAL_9145_LINEA_HASTA varchar(10),
	@SUCURSAL_9145_TIPO_DESDE varchar(10),
	@SUCURSAL_9145_TIPO_HASTA varchar(10),
	@SUCURSAL_9145_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9145_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_23_VENDEDOR_DESDE varchar(10),
	@CLIENTE_23_VENDEDOR_HASTA varchar(10),
	@CLIENTE_23_CALLE_DESDE varchar(70),
	@CLIENTE_23_CALLE_HASTA varchar(70),
	@CLIENTE_23_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_23_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_23_CUIT_DESDE varchar(15),
	@CLIENTE_23_CUIT_HASTA varchar(15),
	@CLIENTE_23_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_23_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_23_EMAIL_DESDE varchar(250),
	@CLIENTE_23_EMAIL_HASTA varchar(250),
	@CLIENTE_23_FAX_DESDE varchar(20),
	@CLIENTE_23_FAX_HASTA varchar(20),
	@CLIENTE_23_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_23_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_23_IMAGEN_DESDE varchar(180),
	@CLIENTE_23_IMAGEN_HASTA varchar(180),
	@CLIENTE_23_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_23_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_23_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_23_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_23_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_23_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_23_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_23_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_23_PAIS_DESDE varchar(3),
	@CLIENTE_23_PAIS_HASTA varchar(3),
	@CLIENTE_23_PISO_DESDE varchar(3),
	@CLIENTE_23_PISO_HASTA varchar(3),
	@CLIENTE_23_PROVINCIA_DESDE varchar(2),
	@CLIENTE_23_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_42_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_23_TELEFONO_DESDE varchar(30),
	@CLIENTE_23_TELEFONO_HASTA varchar(30),
	@CLIENTE_23_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_23_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_23_MOVIL_DESDE varchar(30),
	@CLIENTE_23_MOVIL_HASTA varchar(30),
	@CLIENTE_23_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_23_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_23_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_23_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_23_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_23_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_23_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_23_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_23_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_23_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_23_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_23_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_23_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_23_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_23_ESTADOCIVIL varchar(13),
	@CLIENTE_23_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_23_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_23_SEXO varchar(10),
	@CLIENTE_23_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_23_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_23_RUT_DESDE varchar(12),
	@CLIENTE_23_RUT_HASTA varchar(12),
	@CLIENTE_23_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_23_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_23_TIPOCLI_DESDE varchar(10),
	@CLIENTE_23_TIPOCLI_HASTA varchar(10),
	@CLIENTE_23_CATEGCLI_DESDE varchar(10),
	@CLIENTE_23_CATEGCLI_HASTA varchar(10),
	@CLIENTE_23_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_23_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_23_SUJETOVINCULADO bit,
	@CLIENTE_23_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_23_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_23_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_23_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_23_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_23_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_23_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_23_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_23_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_23_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_23_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_23_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_23_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_23_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_23_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_23_APELLIDO_DESDE varchar(60),
	@CLIENTE_23_APELLIDO_HASTA varchar(60),
	@CLIENTE_23_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_23_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_23_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_23_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_23_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_23_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_23_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_23_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_23_TASACEROAPLICA bit,
	@CLIENTE_23_INACTIVOFW bit,
	@SUCURSAL_9145_CODIGO_DESDE varchar(10),
	@SUCURSAL_9145_CODIGO_HASTA varchar(10),
	@PICKING_BASEDEDATOSALTAFW_DESDE varchar(8),
	@PICKING_BASEDEDATOSALTAFW_HASTA varchar(8),
	@PICKING_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@PICKING_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@PICKING_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@PICKING_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@PICKING_FECHAALTAFW_DESDE datetime,
	@PICKING_FECHAALTAFW_HASTA datetime,
	@PICKING_FECHAEXPO_DESDE datetime,
	@PICKING_FECHAEXPO_HASTA datetime,
	@PICKING_FECHAIMPO_DESDE datetime,
	@PICKING_FECHAIMPO_HASTA datetime,
	@PICKING_FECHAMODIFICACIONFW_DESDE datetime,
	@PICKING_FECHAMODIFICACIONFW_HASTA datetime,
	@PICKING_FECHATRANSFERENCIA_DESDE datetime,
	@PICKING_FECHATRANSFERENCIA_HASTA datetime,
	@PICKING_HORAALTAFW_DESDE varchar(8),
	@PICKING_HORAALTAFW_HASTA varchar(8),
	@PICKING_HORAEXPO_DESDE varchar(8),
	@PICKING_HORAEXPO_HASTA varchar(8),
	@PICKING_HORAIMPO_DESDE varchar(8),
	@PICKING_HORAIMPO_HASTA varchar(8),
	@PICKING_HORAMODIFICACIONFW_DESDE varchar(8),
	@PICKING_HORAMODIFICACIONFW_HASTA varchar(8),
	@PICKING_SERIEALTAFW_DESDE varchar(7),
	@PICKING_SERIEALTAFW_HASTA varchar(7),
	@PICKING_SERIEMODIFICACIONFW_DESDE varchar(7),
	@PICKING_SERIEMODIFICACIONFW_HASTA varchar(7),
	@PICKING_USUARIOALTAFW_DESDE varchar(100),
	@PICKING_USUARIOALTAFW_HASTA varchar(100),
	@PICKING_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@PICKING_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@PICKING_VERSIONALTAFW_DESDE varchar(13),
	@PICKING_VERSIONALTAFW_HASTA varchar(13),
	@PICKING_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@PICKING_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_picking.codigo, 38, ' ' ) as varchar( 46 ) ) as PICKING__Grupo,
	@basededatos as PICKING__BD,
	c_PICKING.CODIGO as PICKING_Codigo,
	c_PICKING.COMPORIGEN as PICKING_CompOrigen,
	c_PICKING.VENDEDOR as PICKING_Vendedor,
	c_PICKING.FPERSON as PICKING_FPerson,
	C_CLIENTE.CIMAGEN as CLIENTE_CIMAGEN,
	c_PICKING.FCLIENTE as PICKING_FCLIENTE,
	c_PICKING.NUMERO as PICKING_Numero,
	case when c_picking.fecha = '01/01/1900 00:00:00' then null else c_picking.fecha end as PICKING_Fecha,
	c_PICKING.OBS as PICKING_Obs,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CLIENTE.CLVEND as CLIENTE_CLVend,
	C_CLIENTE.CLCALLE as CLIENTE_CLCalle,
	C_CLIENTE.CLCP as CLIENTE_CLCP,
	C_CLIENTE.CLCUIT as CLIENTE_CLCUIT,
	C_CLIENTE.CLDEPTO as CLIENTE_CLDEPTO,
	C_CLIENTE.CLEMAIL as CLIENTE_CLEMAIL,
	C_CLIENTE.CLFAX as CLIENTE_CLFAX,
	case when c_cliente.clfecha = '01/01/1900 00:00:00' then null else c_cliente.clfecha end as CLIENTE_CLFECHA,
	C_CLIENTE.CLLOC as CLIENTE_CLLOC,
	C_CLIENTE.CLNRODOC as CLIENTE_CLNRODOC,
	C_CLIENTE.CLNRO as CLIENTE_CLNro,
	C_CLIENTE.CLOBS as CLIENTE_CLOBS,
	C_CLIENTE.CLPAGEWEB as CLIENTE_CLPAGEWEB,
	C_CLIENTE.CLPAIS as CLIENTE_CLPAIS,
	C_CLIENTE.CLPISO as CLIENTE_ClPiso,
	C_CLIENTE.CLPRV as CLIENTE_CLPRV,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_CLIENTE.CLTLF as CLIENTE_CLTLF,
	C_CLIENTE.CLTIPODOC as CLIENTE_CLTIPODOC,
	C_CLIENTE.CLMOVIL as CLIENTE_CLMovil,
	C_CLIENTE.CLTOPECCTE as CLIENTE_CLTOPECCTE,
	C_CLIENTE.CLLISPREC as CLIENTE_CLLisPrec,
	C_CLIENTE.CLCLAS as CLIENTE_CLCLAS,
	C_CLIENTE.CLTIPCONV as CLIENTE_CLTIPCONV,
	C_CLIENTE.CLNROIIBB as CLIENTE_CLNROIIBB,
	C_CLIENTE.CLCO_DTO as CLIENTE_CLCO_DTO,
	C_CLIENTE.CLTRANS as CLIENTE_CLTRANS,
	C_CLIENTE.ESTADO as CLIENTE_Estado,
	C_CLIENTE.HIJOS as CLIENTE_Hijos,
	C_CLIENTE.SEXO as CLIENTE_Sexo,
	C_CLIENTE.GLOBALID as CLIENTE_globalid,
	C_CLIENTE.RUT as CLIENTE_RUT,
	C_CLIENTE.CLCODFANT as CLIENTE_CLCODFANT,
	C_CLIENTE.CLTIPOCLI as CLIENTE_CLTipoCli,
	C_CLIENTE.CLCATEGCLI as CLIENTE_CLCategCli,
	C_CLIENTE.CLCONDPAG as CLIENTE_CLCONDPAG,
	C_CLIENTE.CLSUJVINC as CLIENTE_CLSujVinc,
	C_CLIENTE.CLPERTIVA as CLIENTE_CLPERTIVA,
	C_CLIENTE.CLSITGAN as CLIENTE_CLSITGAN,
	C_CLIENTE.EXPERIVA as CLIENTE_EXPERIVA,
	C_CLIENTE.CLPERGAN as CLIENTE_CLPERGAN,
	C_CLIENTE.EXPERGAN as CLIENTE_EXPERGAN,
	C_CLIENTE.CODRECOM as CLIENTE_CODRECOM,
	C_CLIENTE.NOMRECOM as CLIENTE_NOMRECOM,
	C_CLIENTE.CLPRINOM as CLIENTE_CLPRINOM,
	C_CLIENTE.CLSEGNOM as CLIENTE_CLSEGNOM,
	C_CLIENTE.CLAPELL as CLIENTE_CLAPELL,
	case when c_cliente.vhastaiva = '01/01/1900 00:00:00' then null else c_cliente.vhastaiva end as CLIENTE_VHastaIva,
	case when c_cliente.vhastagan = '01/01/1900 00:00:00' then null else c_cliente.vhastagan end as CLIENTE_VHastaGan,
	C_CLIENTE.CLSIPRIB as CLIENTE_CLSIPRIB,
	C_CLIENTE.PORCENTC as CLIENTE_PorcenTC,
	C_CLIENTE.APLICATC as CLIENTE_AplicaTC,
	C_CLIENTE.INACTIVOFW as CLIENTE_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_PICKING.BDALTAFW as PICKING_BDALTAFW,
	c_PICKING.BDMODIFW as PICKING_BDMODIFW,
	c_PICKING.ESTTRANS as PICKING_ESTTRANS,
	case when c_picking.faltafw = '01/01/1900 00:00:00' then null else c_picking.faltafw end as PICKING_FALTAFW,
	case when c_picking.fecexpo = '01/01/1900 00:00:00' then null else c_picking.fecexpo end as PICKING_FECEXPO,
	case when c_picking.fecimpo = '01/01/1900 00:00:00' then null else c_picking.fecimpo end as PICKING_FECIMPO,
	case when c_picking.fmodifw = '01/01/1900 00:00:00' then null else c_picking.fmodifw end as PICKING_FMODIFW,
	case when c_picking.fectrans = '01/01/1900 00:00:00' then null else c_picking.fectrans end as PICKING_FECTRANS,
	c_PICKING.HALTAFW as PICKING_HALTAFW,
	c_PICKING.HORAEXPO as PICKING_HORAEXPO,
	c_PICKING.HORAIMPO as PICKING_HORAIMPO,
	c_PICKING.HMODIFW as PICKING_HMODIFW,
	c_PICKING.SALTAFW as PICKING_SALTAFW,
	c_PICKING.SMODIFW as PICKING_SMODIFW,
	c_PICKING.UALTAFW as PICKING_UALTAFW,
	c_PICKING.UMODIFW as PICKING_UMODIFW,
	c_PICKING.VALTAFW as PICKING_VALTAFW,
	c_PICKING.VMODIFW as PICKING_VMODIFW,
	c_PICKING.ZADSFW as PICKING_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as PICKING__SUCURSAL,
	cast( c_picking.cantidadtotal - c_picking.nopickeados as numeric( 15, 2 ) ) as PICKING_CantidadCoincidenciaTotal,
	cast( c_picking.nopickeados as numeric( 15, 2 ) ) as PICKING_CantidadNoPickeadosTotal,
	cast( c_picking.cantidadtotal as numeric( 15, 2 ) ) as PICKING_CantidadTotal,
	cast( @parametro1 as varchar( 8 ) ) as PICKING_TipoDiferenciaVirtual,
	cast( c_picking.agregados as numeric( 15, 2 ) ) as PICKING_CantidadAgregadosTotal,
	C_VENDEDOR22.CLNOM as VENDEDOR22_CLNOM,
	C_CLIENTE.CLNOM as CLIENTE_CLNOM,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_VENDEDOR24.CLNOM as VENDEDOR24_CLNOM,
	C_PAISES.PDES as PAISES_pdes,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_CLIENTE.CLIVA as CLIENTE_CLIVA,
	C_LISTADEPRECIOS.LPR_NOMBRE as LISTADEPRECIOS_LPR_NOMBRE,
	C_CLASIFICACIONCLIENTE.CLADES as CLASIFICACIONCLIENTE_CLADES,
	C_DESCUENTO.DES as DESCUENTO_Des,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_NOMBREDEFANTASIA.NFCOD as NOMBREDEFANTASIA_NFCOD,
	C_TIPOCLIENTE.TCDES as TIPOCLIENTE_TCDES,
	C_CATEGORIACLIENTE.CGDES as CATEGORIACLIENTE_CGDes,
	C_CONDICIONDEPAGO.CLNOM as CONDICIONDEPAGO_CLNOM,
	C_IMPUESTO63.DESCRIP as IMPUESTO63_descrip,
	C_IMPUESTO66.DESCRIP as IMPUESTO66_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_CATEGORIACLIENTE.CGCOD as CATEGORIACLIENTE_CGCod,
	C_CLASIFICACIONCLIENTE.CLACOD as CLASIFICACIONCLIENTE_CLACOD,
	C_CLIENTE.CLCOD as CLIENTE_CLCOD,
	C_CONDICIONDEPAGO.CLCOD as CONDICIONDEPAGO_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DESCUENTO.CODIGO as DESCUENTO_codigo,
	C_IMPUESTO63.CODIGO as IMPUESTO63_codigo,
	C_IMPUESTO66.CODIGO as IMPUESTO66_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS.LPR_NUMERO as LISTADEPRECIOS_LPR_NUMERO,
	C_PAISES.PCOD as PAISES_pcod,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOCLIENTE.TCCOD as TIPOCLIENTE_TCCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_VENDEDOR22.CLCOD as VENDEDOR22_CLCOD,
	C_VENDEDOR24.CLCOD as VENDEDOR24_CLCOD
 from ( select cast( Funciones.ObtenerCantidadAgregadosDeUnPicking( NUMERO ) as numeric( 15, 2 ) ) as Agregados, cast( Funciones.ObtenerCantidadDiferenciaDeUnPicking( NUMERO ) as numeric( 15, 2 ) ) as NoPickeados, cast( Funciones.ObtenerCantidadTotalDeUnPicking( NUMERO ) as numeric( 15, 2 ) ) as CantidadTotal, * from ZooLogic.PICKING) as c_PICKING
 left join ZooLogic.CLI as C_CLIENTE on C_CLIENTE.CLCOD = C_PICKING.FPERSON and 0 = Funciones.empty( C_PICKING.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO on C_CONDICIONDEPAGO.CLCOD = C_CLIENTE.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_CLIENTE.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO on C_DESCUENTO.CODIGO = C_CLIENTE.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO63 on C_IMPUESTO63.CODIGO = C_CLIENTE.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO66 on C_IMPUESTO66.CODIGO = C_CLIENTE.CLPERGAN and 0 = Funciones.empty( C_CLIENTE.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS on C_LISTADEPRECIOS.LPR_NUMERO = C_CLIENTE.CLLISPREC and 0 = Funciones.empty( C_CLIENTE.CLLISPREC )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_CLIENTE.CLPAIS and 0 = Funciones.empty( C_CLIENTE.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_CLIENTE.CLPRV and 0 = Funciones.empty( C_CLIENTE.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_CLIENTE.CLIVA and 0 = Funciones.empty( C_CLIENTE.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE on C_TIPOCLIENTE.TCCOD = C_CLIENTE.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_CLIENTE.CLTRANS and 0 = Funciones.empty( C_CLIENTE.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR22 on C_VENDEDOR22.CLCOD = C_PICKING.VENDEDOR and 0 = Funciones.empty( C_PICKING.VENDEDOR )
 left join ZooLogic.VEN as C_VENDEDOR24 on C_VENDEDOR24.CLCOD = C_CLIENTE.CLVEND and 0 = Funciones.empty( C_CLIENTE.CLVEND )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA on C_NOMBREDEFANTASIA.NFCOD = C_CLIENTE.CLCODFANT and 0 = Funciones.empty( C_CLIENTE.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE on C_CATEGORIACLIENTE.CGCOD = C_CLIENTE.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE on C_CLASIFICACIONCLIENTE.CLACOD = C_CLIENTE.CLCLAS and 0 = Funciones.empty( C_CLIENTE.CLCLAS )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( not 1 = funciones.empty( c_picking.codigo ) ) and
	( case  when @Parametro1 = '0' then sign(c_picking.cantidadtotal - c_picking.nopickeados)
			when @Parametro1 = '1' then sign(c_PICKING.NoPickeados) 
			when @Parametro1 = '2' then sign(c_PICKING.Agregados) else 1 end = 1 ) and 
	( ( @PICKING_TIPOCOMPROBANTEORIGEN is null ) OR ( c_PICKING.CompOrigen = @PICKING_TIPOCOMPROBANTEORIGEN ) ) and 
	( ( @PICKING_VENDEDOR_DESDE is null ) OR ( c_PICKING.Vendedor >= @PICKING_VENDEDOR_DESDE ) ) and 
	( ( @PICKING_VENDEDOR_HASTA is null ) OR ( c_PICKING.Vendedor <= @PICKING_VENDEDOR_HASTA ) ) and 
	( ( @PICKING_CLIENTE_DESDE is null ) OR ( c_PICKING.FPerson >= @PICKING_CLIENTE_DESDE ) ) and 
	( ( @PICKING_CLIENTE_HASTA is null ) OR ( c_PICKING.FPerson <= @PICKING_CLIENTE_HASTA ) ) and 
	( ( @PICKING_CLIENTEDESCRIPCION_DESDE is null ) OR ( c_PICKING.FCLIENTE >= @PICKING_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @PICKING_CLIENTEDESCRIPCION_HASTA is null ) OR ( c_PICKING.FCLIENTE <= @PICKING_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @PICKING_NUMERO_DESDE is null ) OR ( c_PICKING.Numero >= @PICKING_NUMERO_DESDE ) ) and 
	( ( @PICKING_NUMERO_HASTA is null ) OR ( c_PICKING.Numero <= @PICKING_NUMERO_HASTA ) ) and 
	( ( @PICKING_FECHA_DESDE is null ) OR ( c_PICKING.Fecha >= @PICKING_FECHA_DESDE ) ) and 
	( ( @PICKING_FECHA_HASTA is null ) OR ( c_PICKING.Fecha <= @PICKING_FECHA_HASTA ) ) and 
	( ( @VENDEDOR_22_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR22.CLNOM >= @VENDEDOR_22_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_22_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR22.CLNOM <= @VENDEDOR_22_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @CLIENTE_23_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE.CLNOM >= @CLIENTE_23_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_23_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE.CLNOM <= @CLIENTE_23_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_9150_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9150_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9150_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9150_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9149_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9149_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9149_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9149_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9148_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9148_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9148_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9148_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_24_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR24.CLNOM >= @VENDEDOR_24_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_24_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR24.CLNOM <= @VENDEDOR_24_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_39_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_39_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_39_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_39_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_41_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_41_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_41_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_41_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_47_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE >= @LISTADEPRECIOS_47_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_47_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE <= @LISTADEPRECIOS_47_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_48_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES >= @CLASIFICACIONCLIENTE_48_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_48_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES <= @CLASIFICACIONCLIENTE_48_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_51_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO.Des >= @DESCUENTO_51_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_51_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO.Des <= @DESCUENTO_51_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_52_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_52_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_52_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_52_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_58_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA.NFCOD >= @NOMBREDEFANTASIA_58_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_58_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA.NFCOD <= @NOMBREDEFANTASIA_58_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_59_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE.TCDES >= @TIPOCLIENTE_59_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_59_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE.TCDES <= @TIPOCLIENTE_59_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_60_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE.CGDes >= @CATEGORIACLIENTE_60_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_60_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE.CGDes <= @CATEGORIACLIENTE_60_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO.CLNOM >= @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO.CLNOM <= @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_63_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO63.descrip >= @IMPUESTO_63_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_63_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO63.descrip <= @IMPUESTO_63_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_66_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO66.descrip >= @IMPUESTO_66_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_66_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO66.descrip <= @IMPUESTO_66_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_75_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_75_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_75_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_75_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9145_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9145_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9145_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9145_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9145_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9145_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9145_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9145_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9145_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9145_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9145_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9145_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9145_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9145_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9145_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9145_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_23_VENDEDOR_DESDE is null ) OR ( C_CLIENTE.CLVend >= @CLIENTE_23_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_23_VENDEDOR_HASTA is null ) OR ( C_CLIENTE.CLVend <= @CLIENTE_23_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_23_CALLE_DESDE is null ) OR ( C_CLIENTE.CLCalle >= @CLIENTE_23_CALLE_DESDE ) ) and 
	( ( @CLIENTE_23_CALLE_HASTA is null ) OR ( C_CLIENTE.CLCalle <= @CLIENTE_23_CALLE_HASTA ) ) and 
	( ( @CLIENTE_23_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE.CLCP >= @CLIENTE_23_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_23_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE.CLCP <= @CLIENTE_23_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_23_CUIT_DESDE is null ) OR ( C_CLIENTE.CLCUIT >= @CLIENTE_23_CUIT_DESDE ) ) and 
	( ( @CLIENTE_23_CUIT_HASTA is null ) OR ( C_CLIENTE.CLCUIT <= @CLIENTE_23_CUIT_HASTA ) ) and 
	( ( @CLIENTE_23_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE.CLDEPTO >= @CLIENTE_23_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_23_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE.CLDEPTO <= @CLIENTE_23_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_23_EMAIL_DESDE is null ) OR ( C_CLIENTE.CLEMAIL >= @CLIENTE_23_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_23_EMAIL_HASTA is null ) OR ( C_CLIENTE.CLEMAIL <= @CLIENTE_23_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_23_FAX_DESDE is null ) OR ( C_CLIENTE.CLFAX >= @CLIENTE_23_FAX_DESDE ) ) and 
	( ( @CLIENTE_23_FAX_HASTA is null ) OR ( C_CLIENTE.CLFAX <= @CLIENTE_23_FAX_HASTA ) ) and 
	( ( @CLIENTE_23_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE.CLFECHA >= @CLIENTE_23_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_23_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE.CLFECHA <= @CLIENTE_23_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_23_IMAGEN_DESDE is null ) OR ( C_CLIENTE.CIMAGEN >= @CLIENTE_23_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_23_IMAGEN_HASTA is null ) OR ( C_CLIENTE.CIMAGEN <= @CLIENTE_23_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_23_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE.CLLOC >= @CLIENTE_23_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_23_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE.CLLOC <= @CLIENTE_23_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_23_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLNRODOC >= @CLIENTE_23_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_23_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLNRODOC <= @CLIENTE_23_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_23_NUMERO_DESDE is null ) OR ( C_CLIENTE.CLNro >= @CLIENTE_23_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_23_NUMERO_HASTA is null ) OR ( C_CLIENTE.CLNro <= @CLIENTE_23_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_23_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE.CLPAGEWEB >= @CLIENTE_23_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_23_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE.CLPAGEWEB <= @CLIENTE_23_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_23_PAIS_DESDE is null ) OR ( C_CLIENTE.CLPAIS >= @CLIENTE_23_PAIS_DESDE ) ) and 
	( ( @CLIENTE_23_PAIS_HASTA is null ) OR ( C_CLIENTE.CLPAIS <= @CLIENTE_23_PAIS_HASTA ) ) and 
	( ( @CLIENTE_23_PISO_DESDE is null ) OR ( C_CLIENTE.ClPiso >= @CLIENTE_23_PISO_DESDE ) ) and 
	( ( @CLIENTE_23_PISO_HASTA is null ) OR ( C_CLIENTE.ClPiso <= @CLIENTE_23_PISO_HASTA ) ) and 
	( ( @CLIENTE_23_PROVINCIA_DESDE is null ) OR ( C_CLIENTE.CLPRV >= @CLIENTE_23_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_23_PROVINCIA_HASTA is null ) OR ( C_CLIENTE.CLPRV <= @CLIENTE_23_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_42_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_42_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_23_TELEFONO_DESDE is null ) OR ( C_CLIENTE.CLTLF >= @CLIENTE_23_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_23_TELEFONO_HASTA is null ) OR ( C_CLIENTE.CLTLF <= @CLIENTE_23_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_23_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLTIPODOC >= @CLIENTE_23_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_23_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLTIPODOC <= @CLIENTE_23_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_23_MOVIL_DESDE is null ) OR ( C_CLIENTE.CLMovil >= @CLIENTE_23_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_23_MOVIL_HASTA is null ) OR ( C_CLIENTE.CLMovil <= @CLIENTE_23_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_23_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE.CLTOPECCTE >= @CLIENTE_23_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_23_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE.CLTOPECCTE <= @CLIENTE_23_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_23_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE.CLLisPrec >= @CLIENTE_23_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_23_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE.CLLisPrec <= @CLIENTE_23_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_23_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE.CLCLAS >= @CLIENTE_23_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_23_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE.CLCLAS <= @CLIENTE_23_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_23_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE.CLTIPCONV >= @CLIENTE_23_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_23_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE.CLTIPCONV <= @CLIENTE_23_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_23_NROIIBB_DESDE is null ) OR ( C_CLIENTE.CLNROIIBB >= @CLIENTE_23_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_23_NROIIBB_HASTA is null ) OR ( C_CLIENTE.CLNROIIBB <= @CLIENTE_23_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_23_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE.CLCO_DTO >= @CLIENTE_23_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_23_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE.CLCO_DTO <= @CLIENTE_23_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_23_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE.CLTRANS >= @CLIENTE_23_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_23_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE.CLTRANS <= @CLIENTE_23_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_23_ESTADOCIVIL is null ) OR ( C_CLIENTE.Estado = @CLIENTE_23_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_23_HIJOS_DESDE is null ) OR ( C_CLIENTE.Hijos >= @CLIENTE_23_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_23_HIJOS_HASTA is null ) OR ( C_CLIENTE.Hijos <= @CLIENTE_23_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_23_SEXO is null ) OR ( C_CLIENTE.Sexo = @CLIENTE_23_SEXO ) ) and 
	( ( @CLIENTE_23_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE.globalid >= @CLIENTE_23_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_23_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE.globalid <= @CLIENTE_23_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_23_RUT_DESDE is null ) OR ( C_CLIENTE.RUT >= @CLIENTE_23_RUT_DESDE ) ) and 
	( ( @CLIENTE_23_RUT_HASTA is null ) OR ( C_CLIENTE.RUT <= @CLIENTE_23_RUT_HASTA ) ) and 
	( ( @CLIENTE_23_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE.CLCODFANT >= @CLIENTE_23_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_23_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE.CLCODFANT <= @CLIENTE_23_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_23_TIPOCLI_DESDE is null ) OR ( C_CLIENTE.CLTipoCli >= @CLIENTE_23_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_23_TIPOCLI_HASTA is null ) OR ( C_CLIENTE.CLTipoCli <= @CLIENTE_23_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_23_CATEGCLI_DESDE is null ) OR ( C_CLIENTE.CLCategCli >= @CLIENTE_23_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_23_CATEGCLI_HASTA is null ) OR ( C_CLIENTE.CLCategCli <= @CLIENTE_23_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_23_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE.CLCONDPAG >= @CLIENTE_23_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_23_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE.CLCONDPAG <= @CLIENTE_23_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_23_SUJETOVINCULADO is null ) OR ( C_CLIENTE.CLSujVinc = @CLIENTE_23_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_23_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE.CLPERTIVA >= @CLIENTE_23_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_23_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE.CLPERTIVA <= @CLIENTE_23_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_23_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE.CLSITGAN = @CLIENTE_23_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_23_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE.EXPERIVA = @CLIENTE_23_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_23_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE.CLPERGAN >= @CLIENTE_23_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_23_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE.CLPERGAN <= @CLIENTE_23_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_23_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE.EXPERGAN = @CLIENTE_23_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_23_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.CODRECOM >= @CLIENTE_23_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_23_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.CODRECOM <= @CLIENTE_23_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_23_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.NOMRECOM >= @CLIENTE_23_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_23_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.NOMRECOM <= @CLIENTE_23_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_23_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE.CLPRINOM >= @CLIENTE_23_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_23_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE.CLPRINOM <= @CLIENTE_23_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_23_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE.CLSEGNOM >= @CLIENTE_23_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_23_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE.CLSEGNOM <= @CLIENTE_23_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_23_APELLIDO_DESDE is null ) OR ( C_CLIENTE.CLAPELL >= @CLIENTE_23_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_23_APELLIDO_HASTA is null ) OR ( C_CLIENTE.CLAPELL <= @CLIENTE_23_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_23_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE.VHastaIva >= @CLIENTE_23_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_23_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE.VHastaIva <= @CLIENTE_23_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_23_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE.VHastaGan >= @CLIENTE_23_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_23_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE.VHastaGan <= @CLIENTE_23_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_23_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE.CLSIPRIB >= @CLIENTE_23_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_23_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE.CLSIPRIB <= @CLIENTE_23_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_23_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE.PorcenTC >= @CLIENTE_23_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_23_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE.PorcenTC <= @CLIENTE_23_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_23_TASACEROAPLICA is null ) OR ( C_CLIENTE.AplicaTC = @CLIENTE_23_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_23_INACTIVOFW is null ) OR ( C_CLIENTE.InactivoFW = @CLIENTE_23_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9145_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9145_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9145_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9145_CODIGO_HASTA ) ) and 
	( ( @PICKING_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_PICKING.BDALTAFW >= @PICKING_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @PICKING_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_PICKING.BDALTAFW <= @PICKING_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @PICKING_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_PICKING.BDMODIFW >= @PICKING_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @PICKING_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_PICKING.BDMODIFW <= @PICKING_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @PICKING_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_PICKING.ESTTRANS >= @PICKING_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @PICKING_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_PICKING.ESTTRANS <= @PICKING_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @PICKING_FECHAALTAFW_DESDE is null ) OR ( c_PICKING.FALTAFW >= @PICKING_FECHAALTAFW_DESDE ) ) and 
	( ( @PICKING_FECHAALTAFW_HASTA is null ) OR ( c_PICKING.FALTAFW <= @PICKING_FECHAALTAFW_HASTA ) ) and 
	( ( @PICKING_FECHAEXPO_DESDE is null ) OR ( c_PICKING.FECEXPO >= @PICKING_FECHAEXPO_DESDE ) ) and 
	( ( @PICKING_FECHAEXPO_HASTA is null ) OR ( c_PICKING.FECEXPO <= @PICKING_FECHAEXPO_HASTA ) ) and 
	( ( @PICKING_FECHAIMPO_DESDE is null ) OR ( c_PICKING.FECIMPO >= @PICKING_FECHAIMPO_DESDE ) ) and 
	( ( @PICKING_FECHAIMPO_HASTA is null ) OR ( c_PICKING.FECIMPO <= @PICKING_FECHAIMPO_HASTA ) ) and 
	( ( @PICKING_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_PICKING.FMODIFW >= @PICKING_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @PICKING_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_PICKING.FMODIFW <= @PICKING_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @PICKING_FECHATRANSFERENCIA_DESDE is null ) OR ( c_PICKING.FECTRANS >= @PICKING_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @PICKING_FECHATRANSFERENCIA_HASTA is null ) OR ( c_PICKING.FECTRANS <= @PICKING_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @PICKING_HORAALTAFW_DESDE is null ) OR ( c_PICKING.HALTAFW >= @PICKING_HORAALTAFW_DESDE ) ) and 
	( ( @PICKING_HORAALTAFW_HASTA is null ) OR ( c_PICKING.HALTAFW <= @PICKING_HORAALTAFW_HASTA ) ) and 
	( ( @PICKING_HORAEXPO_DESDE is null ) OR ( c_PICKING.HORAEXPO >= @PICKING_HORAEXPO_DESDE ) ) and 
	( ( @PICKING_HORAEXPO_HASTA is null ) OR ( c_PICKING.HORAEXPO <= @PICKING_HORAEXPO_HASTA ) ) and 
	( ( @PICKING_HORAIMPO_DESDE is null ) OR ( c_PICKING.HORAIMPO >= @PICKING_HORAIMPO_DESDE ) ) and 
	( ( @PICKING_HORAIMPO_HASTA is null ) OR ( c_PICKING.HORAIMPO <= @PICKING_HORAIMPO_HASTA ) ) and 
	( ( @PICKING_HORAMODIFICACIONFW_DESDE is null ) OR ( c_PICKING.HMODIFW >= @PICKING_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @PICKING_HORAMODIFICACIONFW_HASTA is null ) OR ( c_PICKING.HMODIFW <= @PICKING_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @PICKING_SERIEALTAFW_DESDE is null ) OR ( c_PICKING.SALTAFW >= @PICKING_SERIEALTAFW_DESDE ) ) and 
	( ( @PICKING_SERIEALTAFW_HASTA is null ) OR ( c_PICKING.SALTAFW <= @PICKING_SERIEALTAFW_HASTA ) ) and 
	( ( @PICKING_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_PICKING.SMODIFW >= @PICKING_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @PICKING_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_PICKING.SMODIFW <= @PICKING_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @PICKING_USUARIOALTAFW_DESDE is null ) OR ( c_PICKING.UALTAFW >= @PICKING_USUARIOALTAFW_DESDE ) ) and 
	( ( @PICKING_USUARIOALTAFW_HASTA is null ) OR ( c_PICKING.UALTAFW <= @PICKING_USUARIOALTAFW_HASTA ) ) and 
	( ( @PICKING_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_PICKING.UMODIFW >= @PICKING_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @PICKING_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_PICKING.UMODIFW <= @PICKING_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @PICKING_VERSIONALTAFW_DESDE is null ) OR ( c_PICKING.VALTAFW >= @PICKING_VERSIONALTAFW_DESDE ) ) and 
	( ( @PICKING_VERSIONALTAFW_HASTA is null ) OR ( c_PICKING.VALTAFW <= @PICKING_VERSIONALTAFW_HASTA ) ) and 
	( ( @PICKING_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_PICKING.VMODIFW >= @PICKING_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @PICKING_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_PICKING.VMODIFW <= @PICKING_VERSIONMODIFICACIONFW_HASTA ) )

)