IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_PRESUPUESTODECOMPRA_ITEMARTICULOSPRECOMPRA_ITEMARTICULOSPRECOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_PRESUPUESTODECOMPRA_ITEMARTICULOSPRECOMPRA_ITEMARTICULOSPRECOMPRA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_PRESUPUESTODECOMPRA_ITEMARTICULOSPRECOMPRA_ITEMARTICULOSPRECOMPRA]
( @BaseDeDatos varchar(8),
	@PRESUPUESTODECOMPRA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@PRESUPUESTODECOMPRA_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@ITEMARTICULOSPRECOMPRA_ARTICULO_DESDE varchar(15),
	@ITEMARTICULOSPRECOMPRA_ARTICULO_HASTA varchar(15),
	@ITEMARTICULOSPRECOMPRA_ARTICULODETALLE_DESDE varchar(100),
	@ITEMARTICULOSPRECOMPRA_ARTICULODETALLE_HASTA varchar(100),
	@ITEMARTICULOSPRECOMPRA_COLOR_DESDE varchar(6),
	@ITEMARTICULOSPRECOMPRA_COLOR_HASTA varchar(6),
	@ITEMARTICULOSPRECOMPRA_COLORDETALLE_DESDE varchar(50),
	@ITEMARTICULOSPRECOMPRA_COLORDETALLE_HASTA varchar(50),
	@ITEMARTICULOSPRECOMPRA_TALLE_DESDE varchar(5),
	@ITEMARTICULOSPRECOMPRA_TALLE_HASTA varchar(5),
	@ITEMARTICULOSPRECOMPRA_CANTIDAD_DESDE numeric(8, 2),
	@ITEMARTICULOSPRECOMPRA_CANTIDAD_HASTA numeric(8, 2),
	@ITEMARTICULOSPRECOMPRA_PRECIO_DESDE numeric(14, 4),
	@ITEMARTICULOSPRECOMPRA_PRECIO_HASTA numeric(14, 4),
	@ITEMARTICULOSPRECOMPRA_DESCUENTO_DESDE numeric(7, 2),
	@ITEMARTICULOSPRECOMPRA_DESCUENTO_HASTA numeric(7, 2),
	@ITEMARTICULOSPRECOMPRA_MONTODESCUENTO_DESDE numeric(12, 2),
	@ITEMARTICULOSPRECOMPRA_MONTODESCUENTO_HASTA numeric(12, 2),
	@ITEMARTICULOSPRECOMPRA_MONTO_DESDE numeric(15, 2),
	@ITEMARTICULOSPRECOMPRA_MONTO_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_CODIGO_DESDE varchar(38),
	@PRESUPUESTODECOMPRA_1_CODIGO_HASTA varchar(38),
	@PRESUPUESTODECOMPRA_1_LETRA_DESDE varchar(1),
	@PRESUPUESTODECOMPRA_1_LETRA_HASTA varchar(1),
	@PRESUPUESTODECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE numeric(5, 0),
	@PRESUPUESTODECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA numeric(5, 0),
	@PRESUPUESTODECOMPRA_1_NUMERO_DESDE numeric(8, 0),
	@PRESUPUESTODECOMPRA_1_NUMERO_HASTA numeric(8, 0),
	@PRESUPUESTODECOMPRA_1_PUNTODEVENTA_DESDE numeric(4, 0),
	@PRESUPUESTODECOMPRA_1_PUNTODEVENTA_HASTA numeric(4, 0),
	@PRESUPUESTODECOMPRA_1_PROVEEDOR_DESDE varchar(10),
	@PRESUPUESTODECOMPRA_1_PROVEEDOR_HASTA varchar(10),
	@PRESUPUESTODECOMPRA_1_LISTADEPRECIOS_DESDE varchar(6),
	@PRESUPUESTODECOMPRA_1_LISTADEPRECIOS_HASTA varchar(6),
	@PRESUPUESTODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE varchar(5),
	@PRESUPUESTODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA varchar(5),
	@PRESUPUESTODECOMPRA_1_MOTIVO_DESDE varchar(3),
	@PRESUPUESTODECOMPRA_1_MOTIVO_HASTA varchar(3),
	@PRESUPUESTODECOMPRA_1_TRANSPORTISTA_DESDE varchar(15),
	@PRESUPUESTODECOMPRA_1_TRANSPORTISTA_HASTA varchar(15),
	@PRESUPUESTODECOMPRA_1_NUMINT_DESDE numeric(10, 0),
	@PRESUPUESTODECOMPRA_1_NUMINT_HASTA numeric(10, 0),
	@PRESUPUESTODECOMPRA_1_FECHA_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHA_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_COTIZACION_DESDE numeric(15, 5),
	@PRESUPUESTODECOMPRA_1_COTIZACION_HASTA numeric(15, 5),
	@PRESUPUESTODECOMPRA_1_FECHAVENCIMIENTO_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHAVENCIMIENTO_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@PRESUPUESTODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@PRESUPUESTODECOMPRA_1_DESCUENTO_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_DESCUENTO_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@PRESUPUESTODECOMPRA_1_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@PRESUPUESTODECOMPRA_1_RECARGOMONTO_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_RECARGOMONTO_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_RECARGOMONTO2_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_RECARGOMONTO2_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_IMPUESTOS_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_IMPUESTOS_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_TOTALIMPUESTOS_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_TOTALIMPUESTOS_HASTA numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_TOTAL_DESDE numeric(15, 2),
	@PRESUPUESTODECOMPRA_1_TOTAL_HASTA numeric(15, 2),
	@PROVEEDOR_80_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_80_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@LISTADEPRECIOS_124_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_124_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CONDICIONDEPAGO_125_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_125_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA varchar(100),
	@MOTIVO_126_MOTIVO_DESCRIPCION_DESDE varchar(40),
	@MOTIVO_126_MOTIVO_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_127_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_127_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_8148_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_8148_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_8147_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_8147_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_12_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_12_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_13_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_13_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE varchar(40),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA varchar(40),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE varchar(150),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA varchar(150),
	@MARCA_42_MARCA_DESCRIPCION_DESDE varchar(100),
	@MARCA_42_MARCA_DESCRIPCION_HASTA varchar(100),
	@PROVINCIA_83_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_83_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_99_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_99_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_101_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_101_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_103_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_103_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_106_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_106_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_108_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_108_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_109_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_109_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_110_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_110_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_119_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_119_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_8144_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_8144_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_8144_LINEA_DESDE varchar(10),
	@SUCURSAL_8144_LINEA_HASTA varchar(10),
	@SUCURSAL_8144_TIPO_DESDE varchar(10),
	@SUCURSAL_8144_TIPO_HASTA varchar(10),
	@SUCURSAL_8144_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_8144_DESCRIPCION_HASTA varchar(50),
	@ARTICULO_2_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_2_PROVEEDOR_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVAVENTAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA numeric(5, 2),
	@ARTICULO_2_IMAGEN_DESDE varchar(180),
	@ARTICULO_2_IMAGEN_HASTA varchar(180),
	@ARTICULO_2_TEMPORADA_DESDE varchar(5),
	@ARTICULO_2_TEMPORADA_HASTA varchar(5),
	@ARTICULO_2_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_2_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_2_FAMILIA_DESDE varchar(10),
	@ARTICULO_2_FAMILIA_HASTA varchar(10),
	@ARTICULO_2_MATERIAL_DESDE varchar(10),
	@ARTICULO_2_MATERIAL_HASTA varchar(10),
	@ARTICULO_2_LINEA_DESDE varchar(10),
	@ARTICULO_2_LINEA_HASTA varchar(10),
	@ARTICULO_2_GRUPO_DESDE varchar(10),
	@ARTICULO_2_GRUPO_HASTA varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_2_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_2_ANO_DESDE numeric(4, 0),
	@ARTICULO_2_ANO_HASTA numeric(4, 0),
	@ARTICULO_2_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_2_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVACOMPRAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA numeric(5, 2),
	@ARTICULO_2_COMPORTAMIENTO numeric(1, 0),
	@ARTICULO_2_PALETADECOLORES_DESDE varchar(10),
	@ARTICULO_2_PALETADECOLORES_HASTA varchar(10),
	@ARTICULO_2_CURVADETALLES_DESDE varchar(10),
	@ARTICULO_2_CURVADETALLES_HASTA varchar(10),
	@ARTICULO_2_NOCOMERCIALIZABLE_DESDE datetime,
	@ARTICULO_2_NOCOMERCIALIZABLE_HASTA datetime,
	@ARTICULO_2_NOMENCLADOR_DESDE varchar(6),
	@ARTICULO_2_NOMENCLADOR_HASTA varchar(6),
	@ARTICULO_2_NOPERMITEDEVOLUCIONES bit,
	@ARTICULO_2_IMPRIMEDESPACHO bit,
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA numeric(5, 2),
	@ARTICULO_2_RESTRINGIRDESCUENTOS bit,
	@ARTICULO_2_PESO_DESDE numeric(11, 3),
	@ARTICULO_2_PESO_HASTA numeric(11, 3),
	@ARTICULO_2_LARGO_DESDE numeric(11, 2),
	@ARTICULO_2_LARGO_HASTA numeric(11, 2),
	@ARTICULO_2_ANCHO_DESDE numeric(11, 2),
	@ARTICULO_2_ANCHO_HASTA numeric(11, 2),
	@ARTICULO_2_ALTO_DESDE numeric(11, 2),
	@ARTICULO_2_ALTO_HASTA numeric(11, 2),
	@ARTICULO_2_REQUIERECCOSTO_DESDE numeric(1, 0),
	@ARTICULO_2_REQUIERECCOSTO_HASTA numeric(1, 0),
	@ARTICULO_2_NOPUBLICARENECOMMERCE bit,
	@ARTICULO_2_IMPORTADO bit,
	@ARTICULO_2_DESCRIPCIONADICIONAL_DESDE varchar(254),
	@ARTICULO_2_DESCRIPCIONADICIONAL_HASTA varchar(254),
	@ARTICULO_2_SOLOPROMOYKIT bit,
	@ARTICULO_2_RESTRINGIRARTICULO_DESDE datetime,
	@ARTICULO_2_RESTRINGIRARTICULO_HASTA datetime,
	@ARTICULO_2_MARCA_DESDE varchar(30),
	@ARTICULO_2_MARCA_HASTA varchar(30),
	@ARTICULO_2_PERCEPCIONIVARG5329 numeric(1, 0),
	@PROVEEDOR_80_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_80_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_80_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_80_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_80_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_80_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_80_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_80_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_80_FAX_DESDE varchar(60),
	@PROVEEDOR_80_FAX_HASTA varchar(60),
	@PROVEEDOR_80_EMAIL_DESDE varchar(250),
	@PROVEEDOR_80_EMAIL_HASTA varchar(250),
	@PROVEEDOR_80_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_80_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_88_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_80_CUIT_DESDE varchar(15),
	@PROVEEDOR_80_CUIT_HASTA varchar(15),
	@PROVEEDOR_80_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_80_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_80_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_80_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_80_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_80_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_80_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_80_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_80_CALLE_DESDE varchar(70),
	@PROVEEDOR_80_CALLE_HASTA varchar(70),
	@PROVEEDOR_80_PISO_DESDE varchar(3),
	@PROVEEDOR_80_PISO_HASTA varchar(3),
	@PROVEEDOR_80_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_80_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_80_PAIS_DESDE varchar(3),
	@PROVEEDOR_80_PAIS_HASTA varchar(3),
	@PROVEEDOR_80_MOVIL_DESDE varchar(30),
	@PROVEEDOR_80_MOVIL_HASTA varchar(30),
	@PROVEEDOR_80_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_80_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_80_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_80_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_80_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_80_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_80_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_80_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_80_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_80_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_80_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_80_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_80_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_80_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_80_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_80_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_80_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_80_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_80_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_80_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_80_EMPLEADOR bit,
	@PROVEEDOR_80_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_80_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_80_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_80_SUJETOVINCULADO bit,
	@PROVEEDOR_80_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_80_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_80_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_80_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_80_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_80_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_80_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_80_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_80_TASACEROAPLICA bit,
	@PROVEEDOR_80_RUT_DESDE varchar(12),
	@PROVEEDOR_80_RUT_HASTA varchar(12),
	@PROVEEDOR_80_INACTIVOFW bit,
	@SUCURSAL_8144_CODIGO_DESDE varchar(10),
	@SUCURSAL_8144_CODIGO_HASTA varchar(10),
	@ITEMARTICULOSPRECOMPRA_NROITEM_DESDE numeric(5, 0),
	@ITEMARTICULOSPRECOMPRA_NROITEM_HASTA numeric(5, 0),
	@PRESUPUESTODECOMPRA_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@PRESUPUESTODECOMPRA_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@PRESUPUESTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@PRESUPUESTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@PRESUPUESTODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@PRESUPUESTODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@PRESUPUESTODECOMPRA_1_FECHAALTAFW_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHAALTAFW_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_FECHAEXPO_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHAEXPO_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_FECHAIMPO_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHAIMPO_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_FECHAMODIFICACIONFW_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHAMODIFICACIONFW_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_FECHATRANSFERENCIA_DESDE datetime,
	@PRESUPUESTODECOMPRA_1_FECHATRANSFERENCIA_HASTA datetime,
	@PRESUPUESTODECOMPRA_1_HORAALTAFW_DESDE varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAALTAFW_HASTA varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAEXPO_DESDE varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAEXPO_HASTA varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAIMPO_DESDE varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAIMPO_HASTA varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@PRESUPUESTODECOMPRA_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@PRESUPUESTODECOMPRA_1_SERIEALTAFW_DESDE varchar(7),
	@PRESUPUESTODECOMPRA_1_SERIEALTAFW_HASTA varchar(7),
	@PRESUPUESTODECOMPRA_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@PRESUPUESTODECOMPRA_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@PRESUPUESTODECOMPRA_1_USUARIOALTAFW_DESDE varchar(100),
	@PRESUPUESTODECOMPRA_1_USUARIOALTAFW_HASTA varchar(100),
	@PRESUPUESTODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@PRESUPUESTODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@PRESUPUESTODECOMPRA_1_VERSIONALTAFW_DESDE varchar(13),
	@PRESUPUESTODECOMPRA_1_VERSIONALTAFW_HASTA varchar(13),
	@PRESUPUESTODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@PRESUPUESTODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
with ConjuntoBase as
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticulosprecompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSPRECOMPRA__Grupo,
	@basededatos as ITEMARTICULOSPRECOMPRA__BD,
	/* Campos requeridos para las consultas derivadas */
	c_ITEMARTICULOSPRECOMPRA.CODIGO,
	c_ITEMARTICULOSPRECOMPRA.IDITEM,
	c_ITEMARTICULOSPRECOMPRA.AFE_COD,
	c_ITEMARTICULOSPRECOMPRA.AFESALDO,
	c_ITEMARTICULOSPRECOMPRA.FCANT,
	C_PRESUPUESTODECOMPRA.FACTTIPO,
	/*------------------------------------------------*/
	c_ITEMARTICULOSPRECOMPRA.CODIGO as ITEMARTICULOSPRECOMPRA_CODIGO,
	c_ITEMARTICULOSPRECOMPRA.FART as ITEMARTICULOSPRECOMPRA_FART,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	c_ITEMARTICULOSPRECOMPRA.FTXT as ITEMARTICULOSPRECOMPRA_FTXT,
	c_ITEMARTICULOSPRECOMPRA.FCOLO as ITEMARTICULOSPRECOMPRA_FCOLO,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticulosprecompra.fart, c_itemarticulosprecompra.fcolo, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSPRECOMPRA_OrdenPaletaColores,
	c_ITEMARTICULOSPRECOMPRA.FCOTXT as ITEMARTICULOSPRECOMPRA_FCOTXT,
	c_ITEMARTICULOSPRECOMPRA.FTALL as ITEMARTICULOSPRECOMPRA_FTALL,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticulosprecompra.fart, c_itemarticulosprecompra.ftall, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSPRECOMPRA_OrdenCurvaTalles,
	c_ITEMARTICULOSPRECOMPRA.FCANT as ITEMARTICULOSPRECOMPRA_FCANT,
	c_ITEMARTICULOSPRECOMPRA.FPRECIO as ITEMARTICULOSPRECOMPRA_FPRECIO,
	c_ITEMARTICULOSPRECOMPRA.FCFI as ITEMARTICULOSPRECOMPRA_FCFI,
	c_ITEMARTICULOSPRECOMPRA.MNTDES as ITEMARTICULOSPRECOMPRA_MNTDES,
	c_ITEMARTICULOSPRECOMPRA.FMONTO as ITEMARTICULOSPRECOMPRA_FMONTO,
	C_PRESUPUESTODECOMPRA.CODIGO as PRESUPUESTODECOMPRA_CODIGO,
	C_PRESUPUESTODECOMPRA.FLETRA as PRESUPUESTODECOMPRA_FLETRA,
	C_PRESUPUESTODECOMPRA.FPTOVENEXT as PRESUPUESTODECOMPRA_FPTOVENEXT,
	C_PRESUPUESTODECOMPRA.FNUMCOMP as PRESUPUESTODECOMPRA_FNUMCOMP,
	C_PRESUPUESTODECOMPRA.FPTOVEN as PRESUPUESTODECOMPRA_FPTOVEN,
	C_PRESUPUESTODECOMPRA.FPERSON as PRESUPUESTODECOMPRA_FPerson,
	C_PROVEEDOR80.CIMAGEN as PROVEEDOR80_CIMAGEN,
	C_PRESUPUESTODECOMPRA.CODLISTA as PRESUPUESTODECOMPRA_CodLista,
	C_PRESUPUESTODECOMPRA.CONDPAGO as PRESUPUESTODECOMPRA_CONDPAGO,
	C_PRESUPUESTODECOMPRA.MOTIVO as PRESUPUESTODECOMPRA_MOTIVO,
	C_PRESUPUESTODECOMPRA.FTRANSP as PRESUPUESTODECOMPRA_FTransp,
	C_PRESUPUESTODECOMPRA.NUMINT as PRESUPUESTODECOMPRA_NumInt,
	case when c_presupuestodecompra.ffch = '01/01/1900 00:00:00' then null else c_presupuestodecompra.ffch end as PRESUPUESTODECOMPRA_FFCH,
	C_PRESUPUESTODECOMPRA.COTIZ as PRESUPUESTODECOMPRA_Cotiz,
	case when c_presupuestodecompra.ffchvenc = '01/01/1900 00:00:00' then null else c_presupuestodecompra.ffchvenc end as PRESUPUESTODECOMPRA_FFCHVENC,
	C_PRESUPUESTODECOMPRA.FPODES as PRESUPUESTODECOMPRA_FPODES,
	C_PRESUPUESTODECOMPRA.FDESCU as PRESUPUESTODECOMPRA_fDescu,
	C_PRESUPUESTODECOMPRA.FOBS as PRESUPUESTODECOMPRA_FObs,
	C_PRESUPUESTODECOMPRA.FMTDES3 as PRESUPUESTODECOMPRA_FMTDES3,
	C_PRESUPUESTODECOMPRA.RECPOR as PRESUPUESTODECOMPRA_RecPor,
	C_PRESUPUESTODECOMPRA.MR as PRESUPUESTODECOMPRA_MR,
	C_PRESUPUESTODECOMPRA.RECMONTO2 as PRESUPUESTODECOMPRA_RecMonto2,
	C_PRESUPUESTODECOMPRA.FIMPUESTO as PRESUPUESTODECOMPRA_fImpuesto,
	C_PRESUPUESTODECOMPRA.TOTIMPUE as PRESUPUESTODECOMPRA_totimpue,
	C_PRESUPUESTODECOMPRA.FTOTAL as PRESUPUESTODECOMPRA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_ARTICULO.ARTCONIVA as ARTICULO_ARTCONIVA,
	C_ARTICULO.ARTPORIVA as ARTICULO_ARTPORIVA,
	C_ARTICULO.AOBS as ARTICULO_AObs,
	C_ARTICULO.ATEMPORADA as ARTICULO_ATEMPORADA,
	C_ARTICULO.UNIMED as ARTICULO_UniMed,
	C_ARTICULO.FAMILIA as ARTICULO_Familia,
	C_ARTICULO.MAT as ARTICULO_Mat,
	C_ARTICULO.LINEA as ARTICULO_Linea,
	C_ARTICULO.GRUPO as ARTICULO_Grupo,
	C_ARTICULO.CATEARTI as ARTICULO_CateArti,
	C_ARTICULO.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	C_ARTICULO.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ARTIVA as ARTICULO_ARTIVA,
	C_ARTICULO.ANX2 as ARTICULO_ANX2,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	C_ARTICULO.PALCOL as ARTICULO_PalCol,
	C_ARTICULO.CURTALL as ARTICULO_Curtall,
	case when c_articulo.nocom = '01/01/1900 00:00:00' then null else c_articulo.nocom end as ARTICULO_NOCOM,
	C_ARTICULO.ARTNARBA as ARTICULO_ARTNARBA,
	C_ARTICULO.ARTNODEVO as ARTICULO_ARTNODEVO,
	C_ARTICULO.ESIMPDES as ARTICULO_EsImpDes,
	C_ARTICULO.IMPINTERNO as ARTICULO_impinterno,
	C_ARTICULO.ARTSINDES as ARTICULO_ArtSinDes,
	C_ARTICULO.ARTPESO as ARTICULO_ARTPESO,
	C_ARTICULO.ARTLARGO as ARTICULO_ARTLARGO,
	C_ARTICULO.ARTANCHO as ARTICULO_ARTANCHO,
	C_ARTICULO.ARTALTO as ARTICULO_ARTALTO,
	C_ARTICULO.REQCCOSTO as ARTICULO_ReqCCosto,
	C_ARTICULO.PUBECOM as ARTICULO_PubEcom,
	C_ARTICULO.IMPORTADO as ARTICULO_Importado,
	C_ARTICULO.ARTDESADIC as ARTICULO_ARTDESADIC,
	C_ARTICULO.PROMOYKIT as ARTICULO_PromoYKit,
	C_ARTICULO.DESECOHTML as ARTICULO_DesEcoHTML,
	C_ARTICULO.DESECO as ARTICULO_DesEco,
	case when c_articulo.artrest = '01/01/1900 00:00:00' then null else c_articulo.artrest end as ARTICULO_ArtRest,
	C_ARTICULO.MARCA as ARTICULO_Marca,
	C_ARTICULO.ARTPERCEP as ARTICULO_ArtPercep,
	C_PROVEEDOR80.CLLOC as PROVEEDOR80_CLLOC,
	C_PROVEEDOR80.CLCP as PROVEEDOR80_CLCP,
	C_PROVEEDOR80.CLPRV as PROVEEDOR80_CLPRV,
	C_PROVEEDOR80.CLTLF as PROVEEDOR80_CLTLF,
	C_PROVEEDOR80.CLFAX as PROVEEDOR80_CLFAX,
	C_PROVEEDOR80.CLEMAIL as PROVEEDOR80_CLEMAIL,
	C_PROVEEDOR80.CLPAGEWEB as PROVEEDOR80_CLPAGEWEB,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_PROVEEDOR80.CLCUIT as PROVEEDOR80_CLCUIT,
	C_PROVEEDOR80.CLOBS as PROVEEDOR80_CLOBS,
	C_PROVEEDOR80.CLTIPODOC as PROVEEDOR80_CLTIPODOC,
	C_PROVEEDOR80.CLNRODOC as PROVEEDOR80_CLNRODOC,
	C_PROVEEDOR80.PNUMERO as PROVEEDOR80_PNUMERO,
	C_PROVEEDOR80.PCALLE as PROVEEDOR80_PCALLE,
	C_PROVEEDOR80.PPISO as PROVEEDOR80_PPISO,
	C_PROVEEDOR80.PDEPTO as PROVEEDOR80_PDEPTO,
	C_PROVEEDOR80.PPAIS as PROVEEDOR80_PPAIS,
	C_PROVEEDOR80.TLFM as PROVEEDOR80_TLFM,
	C_PROVEEDOR80.CLAS as PROVEEDOR80_CLAS,
	case when c_proveedor80.clfecha = '01/01/1900 00:00:00' then null else c_proveedor80.clfecha end as PROVEEDOR80_CLFECHA,
	C_PROVEEDOR80.CLCONDPAG as PROVEEDOR80_CLCONDPAG,
	C_PROVEEDOR80.CLTIPCONV as PROVEEDOR80_CLTIPCONV,
	C_PROVEEDOR80.CLNROIIBB as PROVEEDOR80_CLNROIIBB,
	C_PROVEEDOR80.CLLISTPRE as PROVEEDOR80_CLLISTPRE,
	C_PROVEEDOR80.CLSITGAN as PROVEEDOR80_CLSITGAN,
	C_PROVEEDOR80.CLRETGAN as PROVEEDOR80_CLRETGAN,
	C_PROVEEDOR80.CLRETSUSS as PROVEEDOR80_CLRETSUSS,
	C_PROVEEDOR80.CLRETIVA as PROVEEDOR80_CLRETIVA,
	C_PROVEEDOR80.CLOBJIVA as PROVEEDOR80_CLOBJIVA,
	C_PROVEEDOR80.CLEMPLEAD as PROVEEDOR80_CLEMPLEAD,
	C_PROVEEDOR80.EXRETGAN as PROVEEDOR80_EXRETGAN,
	C_PROVEEDOR80.EXRETIVA as PROVEEDOR80_EXRETIVA,
	C_PROVEEDOR80.EXRETSUSS as PROVEEDOR80_EXRETSUSS,
	C_PROVEEDOR80.CLSUJVINC as PROVEEDOR80_CLSujVinc,
	case when c_proveedor80.pvhastaiva = '01/01/1900 00:00:00' then null else c_proveedor80.pvhastaiva end as PROVEEDOR80_PVHastaIva,
	case when c_proveedor80.pvhastagan = '01/01/1900 00:00:00' then null else c_proveedor80.pvhastagan end as PROVEEDOR80_PVHastaGan,
	C_PROVEEDOR80.CLSIPRIB as PROVEEDOR80_CLSIPRIB,
	C_PROVEEDOR80.PORCENTC as PROVEEDOR80_PorcenTC,
	C_PROVEEDOR80.APLICATC as PROVEEDOR80_AplicaTC,
	C_PROVEEDOR80.RUT as PROVEEDOR80_RUT,
	C_PROVEEDOR80.INACTIVOFW as PROVEEDOR80_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMARTICULOSPRECOMPRA.NROITEM as ITEMARTICULOSPRECOMPRA_NroItem,
	C_PRESUPUESTODECOMPRA.BDALTAFW as PRESUPUESTODECOMPRA_BDALTAFW,
	C_PRESUPUESTODECOMPRA.BDMODIFW as PRESUPUESTODECOMPRA_BDMODIFW,
	C_PRESUPUESTODECOMPRA.ESTTRANS as PRESUPUESTODECOMPRA_ESTTRANS,
	case when c_presupuestodecompra.faltafw = '01/01/1900 00:00:00' then null else c_presupuestodecompra.faltafw end as PRESUPUESTODECOMPRA_FALTAFW,
	case when c_presupuestodecompra.fecexpo = '01/01/1900 00:00:00' then null else c_presupuestodecompra.fecexpo end as PRESUPUESTODECOMPRA_FECEXPO,
	case when c_presupuestodecompra.fecimpo = '01/01/1900 00:00:00' then null else c_presupuestodecompra.fecimpo end as PRESUPUESTODECOMPRA_FECIMPO,
	case when c_presupuestodecompra.fmodifw = '01/01/1900 00:00:00' then null else c_presupuestodecompra.fmodifw end as PRESUPUESTODECOMPRA_FMODIFW,
	case when c_presupuestodecompra.fectrans = '01/01/1900 00:00:00' then null else c_presupuestodecompra.fectrans end as PRESUPUESTODECOMPRA_FECTRANS,
	C_PRESUPUESTODECOMPRA.HALTAFW as PRESUPUESTODECOMPRA_HALTAFW,
	C_PRESUPUESTODECOMPRA.HORAEXPO as PRESUPUESTODECOMPRA_HORAEXPO,
	C_PRESUPUESTODECOMPRA.HORAIMPO as PRESUPUESTODECOMPRA_HORAIMPO,
	C_PRESUPUESTODECOMPRA.HMODIFW as PRESUPUESTODECOMPRA_HMODIFW,
	C_PRESUPUESTODECOMPRA.SALTAFW as PRESUPUESTODECOMPRA_SALTAFW,
	C_PRESUPUESTODECOMPRA.SMODIFW as PRESUPUESTODECOMPRA_SMODIFW,
	C_PRESUPUESTODECOMPRA.UALTAFW as PRESUPUESTODECOMPRA_UALTAFW,
	C_PRESUPUESTODECOMPRA.UMODIFW as PRESUPUESTODECOMPRA_UMODIFW,
	C_PRESUPUESTODECOMPRA.VALTAFW as PRESUPUESTODECOMPRA_VALTAFW,
	C_PRESUPUESTODECOMPRA.VMODIFW as PRESUPUESTODECOMPRA_VMODIFW,
	C_PRESUPUESTODECOMPRA.ZADSFW as PRESUPUESTODECOMPRA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMARTICULOSPRECOMPRA__SUCURSAL,
	cast( funciones.identificadordecomprobantecomprasparalistado(c_presupuestodecompra.facttipo, c_presupuestodecompra.fletra, c_presupuestodecompra.fptoven, c_presupuestodecompra.fptovenext, c_presupuestodecompra.fnumcomp) as varchar( 20 ) ) as PRESUPUESTODECOMPRA_1_ComprobanteVirtual,
	C_PRESUPUESTODECOMPRA.MONEDA as PRESUPUESTODECOMPRA_Moneda,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_PROVEEDOR80.CLNOM as PROVEEDOR80_CLNOM,
	C_LISTADEPRECIOS124.LPR_NOMBRE as LISTADEPRECIOS124_LPR_NOMBRE,
	C_CONDICIONDEPAGO125.CLNOM as CONDICIONDEPAGO125_CLNOM,
	C_MOTIVO.MOTDES as MOTIVO_MOTDES,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVEEDOR3.CLNOM as PROVEEDOR3_CLNOM,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_PALETADECOLORES.DESCRIP as PALETADECOLORES_Descrip,
	C_CURVADETALLES.DESCRIP as CURVADETALLES_Descrip,
	C_NOMENCLADORARBA.NMCDES as NOMENCLADORARBA_NMCDES,
	C_MARCA.DESCRIP as MARCA_Descrip,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_PROVEEDOR80.CLIVA as PROVEEDOR80_CLIVA,
	C_PAISES.PDES as PAISES_pdes,
	C_CLASIFICACIONPROVEEDOR.CLADES as CLASIFICACIONPROVEEDOR_CLADES,
	C_CONDICIONDEPAGO103.CLNOM as CONDICIONDEPAGO103_CLNOM,
	C_LISTADEPRECIOS106.LPR_NOMBRE as LISTADEPRECIOS106_LPR_NOMBRE,
	C_IMPUESTO108.DESCRIP as IMPUESTO108_descrip,
	C_IMPUESTO109.DESCRIP as IMPUESTO109_descrip,
	C_IMPUESTO110.DESCRIP as IMPUESTO110_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_CLASIFICACIONPROVEEDOR.CLACOD as CLASIFICACIONPROVEEDOR_CLACOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_CONDICIONDEPAGO103.CLCOD as CONDICIONDEPAGO103_CLCOD,
	C_CONDICIONDEPAGO125.CLCOD as CONDICIONDEPAGO125_CLCOD,
	C_CURVADETALLES.CODIGO as CURVADETALLES_Codigo,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_IMPUESTO108.CODIGO as IMPUESTO108_codigo,
	C_IMPUESTO109.CODIGO as IMPUESTO109_codigo,
	C_IMPUESTO110.CODIGO as IMPUESTO110_codigo,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS106.LPR_NUMERO as LISTADEPRECIOS106_LPR_NUMERO,
	C_LISTADEPRECIOS124.LPR_NUMERO as LISTADEPRECIOS124_LPR_NUMERO,
	C_MARCA.CODIGO as MARCA_Codigo,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_MOTIVO.MOTCOD as MOTIVO_MOTCOD,
	C_NOMENCLADORARBA.NMCCOD as NOMENCLADORARBA_NMCCOD,
	C_PAISES.PCOD as PAISES_pcod,
	C_PALETADECOLORES.CODIGO as PALETADECOLORES_Codigo,
	C_PROVEEDOR3.CLCOD as PROVEEDOR3_CLCOD,
	C_PROVEEDOR80.CLCOD as PROVEEDOR80_CLCOD,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from ZooLogic.PRECOMPRADET as c_ITEMARTICULOSPRECOMPRA
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSPRECOMPRA.FART and 0 = Funciones.empty( C_ITEMARTICULOSPRECOMPRA.FART )
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = C_ARTICULO.CATEARTI and 0 = Funciones.empty( C_ARTICULO.CATEARTI )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = C_ARTICULO.CLASIFART and 0 = Funciones.empty( C_ARTICULO.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSPRECOMPRA.FCOLO and 0 = Funciones.empty( C_ITEMARTICULOSPRECOMPRA.FCOLO )
 left join ZooLogic.CTALLE as C_CURVADETALLES on C_CURVADETALLES.CODIGO = C_ARTICULO.CURTALL and 0 = Funciones.empty( C_ARTICULO.CURTALL )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.MARCAS as C_MARCA on C_MARCA.CODIGO = C_ARTICULO.MARCA and 0 = Funciones.empty( C_ARTICULO.MARCA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.NMCARBA as C_NOMENCLADORARBA on C_NOMENCLADORARBA.NMCCOD = C_ARTICULO.ARTNARBA and 0 = Funciones.empty( C_ARTICULO.ARTNARBA )
 left join ZooLogic.PCOLOR as C_PALETADECOLORES on C_PALETADECOLORES.CODIGO = C_ARTICULO.PALCOL and 0 = Funciones.empty( C_ARTICULO.PALCOL )
 left join ZooLogic.PRECOMPRA as C_PRESUPUESTODECOMPRA on C_PRESUPUESTODECOMPRA.CODIGO = C_ITEMARTICULOSPRECOMPRA.CODIGO and 0 = Funciones.empty( C_ITEMARTICULOSPRECOMPRA.CODIGO )
 left join ZooLogic.PROV as C_PROVEEDOR3 on C_PROVEEDOR3.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ZooLogic.PROV as C_PROVEEDOR80 on C_PROVEEDOR80.CLCOD = C_PRESUPUESTODECOMPRA.FPERSON and 0 = Funciones.empty( C_PRESUPUESTODECOMPRA.FPERSON )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_PROVEEDOR80.CLPRV and 0 = Funciones.empty( C_PROVEEDOR80.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_PROVEEDOR80.CLIVA and 0 = Funciones.empty( C_PROVEEDOR80.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSPRECOMPRA.FTALL and 0 = Funciones.empty( C_ITEMARTICULOSPRECOMPRA.FTALL )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_PRESUPUESTODECOMPRA.FTRANSP and 0 = Funciones.empty( C_PRESUPUESTODECOMPRA.FTRANSP )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = C_ARTICULO.UNIMED and 0 = Funciones.empty( C_ARTICULO.UNIMED )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR on C_CLASIFICACIONPROVEEDOR.CLACOD = C_PROVEEDOR80.CLAS and 0 = Funciones.empty( C_PROVEEDOR80.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO103 on C_CONDICIONDEPAGO103.CLCOD = C_PROVEEDOR80.CLCONDPAG and 0 = Funciones.empty( C_PROVEEDOR80.CLCONDPAG )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO125 on C_CONDICIONDEPAGO125.CLCOD = C_PRESUPUESTODECOMPRA.CONDPAGO and 0 = Funciones.empty( C_PRESUPUESTODECOMPRA.CONDPAGO )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_PROVEEDOR80.CLSIPRIB and 0 = Funciones.empty( C_PROVEEDOR80.CLSIPRIB )
 left join ZooLogic.IMPUESTO as C_IMPUESTO108 on C_IMPUESTO108.CODIGO = C_PROVEEDOR80.CLRETGAN and 0 = Funciones.empty( C_PROVEEDOR80.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO109 on C_IMPUESTO109.CODIGO = C_PROVEEDOR80.CLRETSUSS and 0 = Funciones.empty( C_PROVEEDOR80.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO110 on C_IMPUESTO110.CODIGO = C_PROVEEDOR80.CLRETIVA and 0 = Funciones.empty( C_PROVEEDOR80.CLRETIVA )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS106 on C_LISTADEPRECIOS106.LPR_NUMERO = C_PROVEEDOR80.CLLISTPRE and 0 = Funciones.empty( C_PROVEEDOR80.CLLISTPRE )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS124 on C_LISTADEPRECIOS124.LPR_NUMERO = C_PRESUPUESTODECOMPRA.CODLISTA and 0 = Funciones.empty( C_PRESUPUESTODECOMPRA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_PRESUPUESTODECOMPRA.MONEDA and 0 = Funciones.empty( C_PRESUPUESTODECOMPRA.MONEDA )
 left join ZooLogic.MOTIVO as C_MOTIVO on C_MOTIVO.MOTCOD = C_PRESUPUESTODECOMPRA.MOTIVO and 0 = Funciones.empty( C_PRESUPUESTODECOMPRA.MOTIVO )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_PROVEEDOR80.PPAIS and 0 = Funciones.empty( C_PROVEEDOR80.PPAIS )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( 1=1 ) and
( not 1 = funciones.empty( c_itemarticulosprecompra.codigo ) and ( not 1 = funciones.empty( c_presupuestodecompra.codigo ) and c_presupuestodecompra.facttipo = 30 ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.Moneda >= @PRESUPUESTODECOMPRA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.Moneda <= @PRESUPUESTODECOMPRA_1_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_ARTICULO_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FART >= @ITEMARTICULOSPRECOMPRA_ARTICULO_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_ARTICULO_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FART <= @ITEMARTICULOSPRECOMPRA_ARTICULO_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_ARTICULODETALLE_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FTXT >= @ITEMARTICULOSPRECOMPRA_ARTICULODETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_ARTICULODETALLE_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FTXT <= @ITEMARTICULOSPRECOMPRA_ARTICULODETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_COLOR_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCOLO >= @ITEMARTICULOSPRECOMPRA_COLOR_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_COLOR_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCOLO <= @ITEMARTICULOSPRECOMPRA_COLOR_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_COLORDETALLE_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCOTXT >= @ITEMARTICULOSPRECOMPRA_COLORDETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_COLORDETALLE_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCOTXT <= @ITEMARTICULOSPRECOMPRA_COLORDETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_TALLE_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FTALL >= @ITEMARTICULOSPRECOMPRA_TALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_TALLE_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FTALL <= @ITEMARTICULOSPRECOMPRA_TALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_CANTIDAD_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCANT >= @ITEMARTICULOSPRECOMPRA_CANTIDAD_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_CANTIDAD_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCANT <= @ITEMARTICULOSPRECOMPRA_CANTIDAD_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_PRECIO_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FPRECIO >= @ITEMARTICULOSPRECOMPRA_PRECIO_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_PRECIO_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FPRECIO <= @ITEMARTICULOSPRECOMPRA_PRECIO_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_DESCUENTO_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCFI >= @ITEMARTICULOSPRECOMPRA_DESCUENTO_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_DESCUENTO_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FCFI <= @ITEMARTICULOSPRECOMPRA_DESCUENTO_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_MONTODESCUENTO_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.MNTDES >= @ITEMARTICULOSPRECOMPRA_MONTODESCUENTO_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_MONTODESCUENTO_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.MNTDES <= @ITEMARTICULOSPRECOMPRA_MONTODESCUENTO_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_MONTO_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FMONTO >= @ITEMARTICULOSPRECOMPRA_MONTO_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_MONTO_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.FMONTO <= @ITEMARTICULOSPRECOMPRA_MONTO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_CODIGO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.CODIGO >= @PRESUPUESTODECOMPRA_1_CODIGO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_CODIGO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.CODIGO <= @PRESUPUESTODECOMPRA_1_CODIGO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_LETRA_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FLETRA >= @PRESUPUESTODECOMPRA_1_LETRA_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_LETRA_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FLETRA <= @PRESUPUESTODECOMPRA_1_LETRA_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FPTOVENEXT >= @PRESUPUESTODECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FPTOVENEXT <= @PRESUPUESTODECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_NUMERO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FNUMCOMP >= @PRESUPUESTODECOMPRA_1_NUMERO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_NUMERO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FNUMCOMP <= @PRESUPUESTODECOMPRA_1_NUMERO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PUNTODEVENTA_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FPTOVEN >= @PRESUPUESTODECOMPRA_1_PUNTODEVENTA_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PUNTODEVENTA_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FPTOVEN <= @PRESUPUESTODECOMPRA_1_PUNTODEVENTA_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PROVEEDOR_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FPerson >= @PRESUPUESTODECOMPRA_1_PROVEEDOR_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PROVEEDOR_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FPerson <= @PRESUPUESTODECOMPRA_1_PROVEEDOR_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_LISTADEPRECIOS_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.CodLista >= @PRESUPUESTODECOMPRA_1_LISTADEPRECIOS_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_LISTADEPRECIOS_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.CodLista <= @PRESUPUESTODECOMPRA_1_LISTADEPRECIOS_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.CONDPAGO >= @PRESUPUESTODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.CONDPAGO <= @PRESUPUESTODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_MOTIVO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.MOTIVO >= @PRESUPUESTODECOMPRA_1_MOTIVO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_MOTIVO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.MOTIVO <= @PRESUPUESTODECOMPRA_1_MOTIVO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_TRANSPORTISTA_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FTransp >= @PRESUPUESTODECOMPRA_1_TRANSPORTISTA_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_TRANSPORTISTA_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FTransp <= @PRESUPUESTODECOMPRA_1_TRANSPORTISTA_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_NUMINT_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.NumInt >= @PRESUPUESTODECOMPRA_1_NUMINT_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_NUMINT_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.NumInt <= @PRESUPUESTODECOMPRA_1_NUMINT_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHA_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FFCH >= @PRESUPUESTODECOMPRA_1_FECHA_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHA_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FFCH <= @PRESUPUESTODECOMPRA_1_FECHA_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_COTIZACION_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.Cotiz >= @PRESUPUESTODECOMPRA_1_COTIZACION_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_COTIZACION_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.Cotiz <= @PRESUPUESTODECOMPRA_1_COTIZACION_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAVENCIMIENTO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FFCHVENC >= @PRESUPUESTODECOMPRA_1_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAVENCIMIENTO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FFCHVENC <= @PRESUPUESTODECOMPRA_1_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FPODES >= @PRESUPUESTODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FPODES <= @PRESUPUESTODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_DESCUENTO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.fDescu >= @PRESUPUESTODECOMPRA_1_DESCUENTO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_DESCUENTO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.fDescu <= @PRESUPUESTODECOMPRA_1_DESCUENTO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FMTDES3 >= @PRESUPUESTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FMTDES3 <= @PRESUPUESTODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_RECARGOPORCENTAJE_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.RecPor >= @PRESUPUESTODECOMPRA_1_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_RECARGOPORCENTAJE_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.RecPor <= @PRESUPUESTODECOMPRA_1_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_RECARGOMONTO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.MR >= @PRESUPUESTODECOMPRA_1_RECARGOMONTO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_RECARGOMONTO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.MR <= @PRESUPUESTODECOMPRA_1_RECARGOMONTO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_RECARGOMONTO2_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.RecMonto2 >= @PRESUPUESTODECOMPRA_1_RECARGOMONTO2_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_RECARGOMONTO2_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.RecMonto2 <= @PRESUPUESTODECOMPRA_1_RECARGOMONTO2_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_IMPUESTOS_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.fImpuesto >= @PRESUPUESTODECOMPRA_1_IMPUESTOS_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_IMPUESTOS_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.fImpuesto <= @PRESUPUESTODECOMPRA_1_IMPUESTOS_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_TOTALIMPUESTOS_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.totimpue >= @PRESUPUESTODECOMPRA_1_TOTALIMPUESTOS_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_TOTALIMPUESTOS_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.totimpue <= @PRESUPUESTODECOMPRA_1_TOTALIMPUESTOS_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_TOTAL_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FTotal >= @PRESUPUESTODECOMPRA_1_TOTAL_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_TOTAL_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FTotal <= @PRESUPUESTODECOMPRA_1_TOTAL_HASTA ) ) and 
	( ( @PROVEEDOR_80_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR80.CLNOM >= @PROVEEDOR_80_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_80_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR80.CLNOM <= @PROVEEDOR_80_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @LISTADEPRECIOS_124_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS124.LPR_NOMBRE >= @LISTADEPRECIOS_124_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_124_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS124.LPR_NOMBRE <= @LISTADEPRECIOS_124_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_125_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO125.CLNOM >= @CONDICIONDEPAGO_125_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_125_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO125.CLNOM <= @CONDICIONDEPAGO_125_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @MOTIVO_126_MOTIVO_DESCRIPCION_DESDE is null ) OR ( C_MOTIVO.MOTDES >= @MOTIVO_126_MOTIVO_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVO_126_MOTIVO_DESCRIPCION_HASTA is null ) OR ( C_MOTIVO.MOTDES <= @MOTIVO_126_MOTIVO_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_127_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_127_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_127_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_127_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_8149_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_8148_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_8148_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_8148_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_8148_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_8147_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR3.CLNOM >= @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR3.CLNOM <= @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_13_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_13_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_14_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_14_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE is null ) OR ( C_PALETADECOLORES.Descrip >= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA is null ) OR ( C_PALETADECOLORES.Descrip <= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE is null ) OR ( C_CURVADETALLES.Descrip >= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA is null ) OR ( C_CURVADETALLES.Descrip <= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE is null ) OR ( C_NOMENCLADORARBA.NMCDES >= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA is null ) OR ( C_NOMENCLADORARBA.NMCDES <= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_DESDE is null ) OR ( C_MARCA.Descrip >= @MARCA_42_MARCA_DESCRIPCION_DESDE ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_HASTA is null ) OR ( C_MARCA.Descrip <= @MARCA_42_MARCA_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_83_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_83_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_83_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_83_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_99_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_99_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_99_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_99_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_101_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES >= @CLASIFICACIONPROVEEDOR_101_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_101_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES <= @CLASIFICACIONPROVEEDOR_101_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_103_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO103.CLNOM >= @CONDICIONDEPAGO_103_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_103_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO103.CLNOM <= @CONDICIONDEPAGO_103_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_106_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS106.LPR_NOMBRE >= @LISTADEPRECIOS_106_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_106_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS106.LPR_NOMBRE <= @LISTADEPRECIOS_106_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_108_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO108.descrip >= @IMPUESTO_108_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_108_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO108.descrip <= @IMPUESTO_108_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_109_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO109.descrip >= @IMPUESTO_109_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_109_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO109.descrip <= @IMPUESTO_109_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_110_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO110.descrip >= @IMPUESTO_110_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_110_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO110.descrip <= @IMPUESTO_110_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_119_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_119_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_119_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_119_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_8010_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_8144_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_8144_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_8144_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_8144_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_8144_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_8144_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_8144_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_8144_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_8144_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_8144_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_8144_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_8144_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_8144_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_8144_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_8144_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_8144_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_2_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_2_PROVEEDOR_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVAVENTAS is null ) OR ( C_ARTICULO.ARTCONIVA = @ARTICULO_2_CONDICIONIVAVENTAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE is null ) OR ( C_ARTICULO.ARTPORIVA >= @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA is null ) OR ( C_ARTICULO.ARTPORIVA <= @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA ) ) and 
	( ( @ARTICULO_2_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_2_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_2_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_2_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_2_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_2_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_2_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_2_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_2_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_2_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_2_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_2_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_2_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_2_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_2_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_2_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_2_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_2_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_2_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_2_LINEA_DESDE ) ) and 
	( ( @ARTICULO_2_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_2_LINEA_HASTA ) ) and 
	( ( @ARTICULO_2_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_2_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_2_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_2_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_2_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_2_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_2_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_2_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_2_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_2_ANO_DESDE ) ) and 
	( ( @ARTICULO_2_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_2_ANO_HASTA ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_2_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_2_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVACOMPRAS is null ) OR ( C_ARTICULO.ARTIVA = @ARTICULO_2_CONDICIONIVACOMPRAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE is null ) OR ( C_ARTICULO.ANX2 >= @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA is null ) OR ( C_ARTICULO.ANX2 <= @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA ) ) and 
	( ( @ARTICULO_2_COMPORTAMIENTO is null ) OR ( C_ARTICULO.ASTOCK = @ARTICULO_2_COMPORTAMIENTO ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_DESDE is null ) OR ( C_ARTICULO.PalCol >= @ARTICULO_2_PALETADECOLORES_DESDE ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_HASTA is null ) OR ( C_ARTICULO.PalCol <= @ARTICULO_2_PALETADECOLORES_HASTA ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_DESDE is null ) OR ( C_ARTICULO.Curtall >= @ARTICULO_2_CURVADETALLES_DESDE ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_HASTA is null ) OR ( C_ARTICULO.Curtall <= @ARTICULO_2_CURVADETALLES_HASTA ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_DESDE is null ) OR ( C_ARTICULO.NOCOM >= @ARTICULO_2_NOCOMERCIALIZABLE_DESDE ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_HASTA is null ) OR ( C_ARTICULO.NOCOM <= @ARTICULO_2_NOCOMERCIALIZABLE_HASTA ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_DESDE is null ) OR ( C_ARTICULO.ARTNARBA >= @ARTICULO_2_NOMENCLADOR_DESDE ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_HASTA is null ) OR ( C_ARTICULO.ARTNARBA <= @ARTICULO_2_NOMENCLADOR_HASTA ) ) and 
	( ( @ARTICULO_2_NOPERMITEDEVOLUCIONES is null ) OR ( C_ARTICULO.ARTNODEVO = @ARTICULO_2_NOPERMITEDEVOLUCIONES ) ) and 
	( ( @ARTICULO_2_IMPRIMEDESPACHO is null ) OR ( C_ARTICULO.EsImpDes = @ARTICULO_2_IMPRIMEDESPACHO ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE is null ) OR ( C_ARTICULO.impinterno >= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA is null ) OR ( C_ARTICULO.impinterno <= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA ) ) and 
	( ( @ARTICULO_2_RESTRINGIRDESCUENTOS is null ) OR ( C_ARTICULO.ArtSinDes = @ARTICULO_2_RESTRINGIRDESCUENTOS ) ) and 
	( ( @ARTICULO_2_PESO_DESDE is null ) OR ( C_ARTICULO.ARTPESO >= @ARTICULO_2_PESO_DESDE ) ) and 
	( ( @ARTICULO_2_PESO_HASTA is null ) OR ( C_ARTICULO.ARTPESO <= @ARTICULO_2_PESO_HASTA ) ) and 
	( ( @ARTICULO_2_LARGO_DESDE is null ) OR ( C_ARTICULO.ARTLARGO >= @ARTICULO_2_LARGO_DESDE ) ) and 
	( ( @ARTICULO_2_LARGO_HASTA is null ) OR ( C_ARTICULO.ARTLARGO <= @ARTICULO_2_LARGO_HASTA ) ) and 
	( ( @ARTICULO_2_ANCHO_DESDE is null ) OR ( C_ARTICULO.ARTANCHO >= @ARTICULO_2_ANCHO_DESDE ) ) and 
	( ( @ARTICULO_2_ANCHO_HASTA is null ) OR ( C_ARTICULO.ARTANCHO <= @ARTICULO_2_ANCHO_HASTA ) ) and 
	( ( @ARTICULO_2_ALTO_DESDE is null ) OR ( C_ARTICULO.ARTALTO >= @ARTICULO_2_ALTO_DESDE ) ) and 
	( ( @ARTICULO_2_ALTO_HASTA is null ) OR ( C_ARTICULO.ARTALTO <= @ARTICULO_2_ALTO_HASTA ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_DESDE is null ) OR ( C_ARTICULO.ReqCCosto >= @ARTICULO_2_REQUIERECCOSTO_DESDE ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_HASTA is null ) OR ( C_ARTICULO.ReqCCosto <= @ARTICULO_2_REQUIERECCOSTO_HASTA ) ) and 
	( ( @ARTICULO_2_NOPUBLICARENECOMMERCE is null ) OR ( C_ARTICULO.PubEcom = @ARTICULO_2_NOPUBLICARENECOMMERCE ) ) and 
	( ( @ARTICULO_2_IMPORTADO is null ) OR ( C_ARTICULO.Importado = @ARTICULO_2_IMPORTADO ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE is null ) OR ( C_ARTICULO.ARTDESADIC >= @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA is null ) OR ( C_ARTICULO.ARTDESADIC <= @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA ) ) and 
	( ( @ARTICULO_2_SOLOPROMOYKIT is null ) OR ( C_ARTICULO.PromoYKit = @ARTICULO_2_SOLOPROMOYKIT ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_DESDE is null ) OR ( C_ARTICULO.ArtRest >= @ARTICULO_2_RESTRINGIRARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_HASTA is null ) OR ( C_ARTICULO.ArtRest <= @ARTICULO_2_RESTRINGIRARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_MARCA_DESDE is null ) OR ( C_ARTICULO.Marca >= @ARTICULO_2_MARCA_DESDE ) ) and 
	( ( @ARTICULO_2_MARCA_HASTA is null ) OR ( C_ARTICULO.Marca <= @ARTICULO_2_MARCA_HASTA ) ) and 
	( ( @ARTICULO_2_PERCEPCIONIVARG5329 is null ) OR ( C_ARTICULO.ArtPercep = @ARTICULO_2_PERCEPCIONIVARG5329 ) ) and 
	( ( @PROVEEDOR_80_LOCALIDAD_DESDE is null ) OR ( C_PROVEEDOR80.CLLOC >= @PROVEEDOR_80_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_80_LOCALIDAD_HASTA is null ) OR ( C_PROVEEDOR80.CLLOC <= @PROVEEDOR_80_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_80_CODIGOPOSTAL_DESDE is null ) OR ( C_PROVEEDOR80.CLCP >= @PROVEEDOR_80_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_80_CODIGOPOSTAL_HASTA is null ) OR ( C_PROVEEDOR80.CLCP <= @PROVEEDOR_80_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_80_PROVINCIA_DESDE is null ) OR ( C_PROVEEDOR80.CLPRV >= @PROVEEDOR_80_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_80_PROVINCIA_HASTA is null ) OR ( C_PROVEEDOR80.CLPRV <= @PROVEEDOR_80_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_80_TELEFONO_DESDE is null ) OR ( C_PROVEEDOR80.CLTLF >= @PROVEEDOR_80_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_80_TELEFONO_HASTA is null ) OR ( C_PROVEEDOR80.CLTLF <= @PROVEEDOR_80_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_80_FAX_DESDE is null ) OR ( C_PROVEEDOR80.CLFAX >= @PROVEEDOR_80_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_80_FAX_HASTA is null ) OR ( C_PROVEEDOR80.CLFAX <= @PROVEEDOR_80_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_80_EMAIL_DESDE is null ) OR ( C_PROVEEDOR80.CLEMAIL >= @PROVEEDOR_80_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_80_EMAIL_HASTA is null ) OR ( C_PROVEEDOR80.CLEMAIL <= @PROVEEDOR_80_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_80_PAGINAWEB_DESDE is null ) OR ( C_PROVEEDOR80.CLPAGEWEB >= @PROVEEDOR_80_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_80_PAGINAWEB_HASTA is null ) OR ( C_PROVEEDOR80.CLPAGEWEB <= @PROVEEDOR_80_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_88_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_88_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_80_CUIT_DESDE is null ) OR ( C_PROVEEDOR80.CLCUIT >= @PROVEEDOR_80_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_80_CUIT_HASTA is null ) OR ( C_PROVEEDOR80.CLCUIT <= @PROVEEDOR_80_CUIT_HASTA ) ) and 
	( ( @PROVEEDOR_80_TIPODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR80.CLTIPODOC >= @PROVEEDOR_80_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_80_TIPODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR80.CLTIPODOC <= @PROVEEDOR_80_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_80_NRODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR80.CLNRODOC >= @PROVEEDOR_80_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_80_NRODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR80.CLNRODOC <= @PROVEEDOR_80_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_80_IMAGEN_DESDE is null ) OR ( C_PROVEEDOR80.CIMAGEN >= @PROVEEDOR_80_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_80_IMAGEN_HASTA is null ) OR ( C_PROVEEDOR80.CIMAGEN <= @PROVEEDOR_80_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_80_NUMERO_DESDE is null ) OR ( C_PROVEEDOR80.PNUMERO >= @PROVEEDOR_80_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_80_NUMERO_HASTA is null ) OR ( C_PROVEEDOR80.PNUMERO <= @PROVEEDOR_80_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_80_CALLE_DESDE is null ) OR ( C_PROVEEDOR80.PCALLE >= @PROVEEDOR_80_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_80_CALLE_HASTA is null ) OR ( C_PROVEEDOR80.PCALLE <= @PROVEEDOR_80_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_80_PISO_DESDE is null ) OR ( C_PROVEEDOR80.PPISO >= @PROVEEDOR_80_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_80_PISO_HASTA is null ) OR ( C_PROVEEDOR80.PPISO <= @PROVEEDOR_80_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_80_DEPARTAMENTO_DESDE is null ) OR ( C_PROVEEDOR80.PDEPTO >= @PROVEEDOR_80_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_80_DEPARTAMENTO_HASTA is null ) OR ( C_PROVEEDOR80.PDEPTO <= @PROVEEDOR_80_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_80_PAIS_DESDE is null ) OR ( C_PROVEEDOR80.PPAIS >= @PROVEEDOR_80_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_80_PAIS_HASTA is null ) OR ( C_PROVEEDOR80.PPAIS <= @PROVEEDOR_80_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_80_MOVIL_DESDE is null ) OR ( C_PROVEEDOR80.TLFM >= @PROVEEDOR_80_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_80_MOVIL_HASTA is null ) OR ( C_PROVEEDOR80.TLFM <= @PROVEEDOR_80_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_80_CLASIFICACION_DESDE is null ) OR ( C_PROVEEDOR80.CLAS >= @PROVEEDOR_80_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_80_CLASIFICACION_HASTA is null ) OR ( C_PROVEEDOR80.CLAS <= @PROVEEDOR_80_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_80_FECHANACIMIENTO_DESDE is null ) OR ( C_PROVEEDOR80.CLFECHA >= @PROVEEDOR_80_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_80_FECHANACIMIENTO_HASTA is null ) OR ( C_PROVEEDOR80.CLFECHA <= @PROVEEDOR_80_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_80_CONDICIONDEPAGO_DESDE is null ) OR ( C_PROVEEDOR80.CLCONDPAG >= @PROVEEDOR_80_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_80_CONDICIONDEPAGO_HASTA is null ) OR ( C_PROVEEDOR80.CLCONDPAG <= @PROVEEDOR_80_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_80_TIPOCONVENIO_DESDE is null ) OR ( C_PROVEEDOR80.CLTIPCONV >= @PROVEEDOR_80_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_80_TIPOCONVENIO_HASTA is null ) OR ( C_PROVEEDOR80.CLTIPCONV <= @PROVEEDOR_80_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_80_NROIIBB_DESDE is null ) OR ( C_PROVEEDOR80.CLNROIIBB >= @PROVEEDOR_80_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_80_NROIIBB_HASTA is null ) OR ( C_PROVEEDOR80.CLNROIIBB <= @PROVEEDOR_80_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_80_LISTADEPRECIO_DESDE is null ) OR ( C_PROVEEDOR80.CLLISTPRE >= @PROVEEDOR_80_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_80_LISTADEPRECIO_HASTA is null ) OR ( C_PROVEEDOR80.CLLISTPRE <= @PROVEEDOR_80_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_80_SITUACIONGANANCIAS is null ) OR ( C_PROVEEDOR80.CLSITGAN = @PROVEEDOR_80_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_80_RETENCIONGANANCIAS_DESDE is null ) OR ( C_PROVEEDOR80.CLRETGAN >= @PROVEEDOR_80_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_80_RETENCIONGANANCIAS_HASTA is null ) OR ( C_PROVEEDOR80.CLRETGAN <= @PROVEEDOR_80_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_80_RETENCIONSUSS_DESDE is null ) OR ( C_PROVEEDOR80.CLRETSUSS >= @PROVEEDOR_80_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_80_RETENCIONSUSS_HASTA is null ) OR ( C_PROVEEDOR80.CLRETSUSS <= @PROVEEDOR_80_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_80_RETENCIONIVA_DESDE is null ) OR ( C_PROVEEDOR80.CLRETIVA >= @PROVEEDOR_80_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_80_RETENCIONIVA_HASTA is null ) OR ( C_PROVEEDOR80.CLRETIVA <= @PROVEEDOR_80_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_80_OBJETOIVA is null ) OR ( C_PROVEEDOR80.CLOBJIVA = @PROVEEDOR_80_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_80_EMPLEADOR is null ) OR ( C_PROVEEDOR80.CLEMPLEAD = @PROVEEDOR_80_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_80_EXCLUIDORETENCIONGANANCIAS is null ) OR ( C_PROVEEDOR80.EXRETGAN = @PROVEEDOR_80_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_80_EXCLUIDORETENCIONIVA is null ) OR ( C_PROVEEDOR80.EXRETIVA = @PROVEEDOR_80_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_80_EXCLUIDORETENCIONSUSS is null ) OR ( C_PROVEEDOR80.EXRETSUSS = @PROVEEDOR_80_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_80_SUJETOVINCULADO is null ) OR ( C_PROVEEDOR80.CLSujVinc = @PROVEEDOR_80_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_80_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_PROVEEDOR80.PVHastaIva >= @PROVEEDOR_80_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_80_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_PROVEEDOR80.PVHastaIva <= @PROVEEDOR_80_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_80_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_PROVEEDOR80.PVHastaGan >= @PROVEEDOR_80_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_80_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_PROVEEDOR80.PVHastaGan <= @PROVEEDOR_80_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_80_CODIGOSIPRIB_DESDE is null ) OR ( C_PROVEEDOR80.CLSIPRIB >= @PROVEEDOR_80_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_80_CODIGOSIPRIB_HASTA is null ) OR ( C_PROVEEDOR80.CLSIPRIB <= @PROVEEDOR_80_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_80_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR80.PorcenTC >= @PROVEEDOR_80_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_80_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR80.PorcenTC <= @PROVEEDOR_80_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_80_TASACEROAPLICA is null ) OR ( C_PROVEEDOR80.AplicaTC = @PROVEEDOR_80_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_80_RUT_DESDE is null ) OR ( C_PROVEEDOR80.RUT >= @PROVEEDOR_80_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_80_RUT_HASTA is null ) OR ( C_PROVEEDOR80.RUT <= @PROVEEDOR_80_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_80_INACTIVOFW is null ) OR ( C_PROVEEDOR80.InactivoFW = @PROVEEDOR_80_INACTIVOFW ) ) and 
	( ( @SUCURSAL_8144_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_8144_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_8144_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_8144_CODIGO_HASTA ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_NROITEM_DESDE is null ) OR ( c_ITEMARTICULOSPRECOMPRA.NroItem >= @ITEMARTICULOSPRECOMPRA_NROITEM_DESDE ) ) and 
	( ( @ITEMARTICULOSPRECOMPRA_NROITEM_HASTA is null ) OR ( c_ITEMARTICULOSPRECOMPRA.NroItem <= @ITEMARTICULOSPRECOMPRA_NROITEM_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.BDALTAFW >= @PRESUPUESTODECOMPRA_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.BDALTAFW <= @PRESUPUESTODECOMPRA_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.BDMODIFW >= @PRESUPUESTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.BDMODIFW <= @PRESUPUESTODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.ESTTRANS >= @PRESUPUESTODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.ESTTRANS <= @PRESUPUESTODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAALTAFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FALTAFW >= @PRESUPUESTODECOMPRA_1_FECHAALTAFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAALTAFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FALTAFW <= @PRESUPUESTODECOMPRA_1_FECHAALTAFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAEXPO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FECEXPO >= @PRESUPUESTODECOMPRA_1_FECHAEXPO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAEXPO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FECEXPO <= @PRESUPUESTODECOMPRA_1_FECHAEXPO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAIMPO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FECIMPO >= @PRESUPUESTODECOMPRA_1_FECHAIMPO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAIMPO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FECIMPO <= @PRESUPUESTODECOMPRA_1_FECHAIMPO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FMODIFW >= @PRESUPUESTODECOMPRA_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FMODIFW <= @PRESUPUESTODECOMPRA_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.FECTRANS >= @PRESUPUESTODECOMPRA_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.FECTRANS <= @PRESUPUESTODECOMPRA_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAALTAFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.HALTAFW >= @PRESUPUESTODECOMPRA_1_HORAALTAFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAALTAFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.HALTAFW <= @PRESUPUESTODECOMPRA_1_HORAALTAFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAEXPO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.HORAEXPO >= @PRESUPUESTODECOMPRA_1_HORAEXPO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAEXPO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.HORAEXPO <= @PRESUPUESTODECOMPRA_1_HORAEXPO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAIMPO_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.HORAIMPO >= @PRESUPUESTODECOMPRA_1_HORAIMPO_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAIMPO_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.HORAIMPO <= @PRESUPUESTODECOMPRA_1_HORAIMPO_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.HMODIFW >= @PRESUPUESTODECOMPRA_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.HMODIFW <= @PRESUPUESTODECOMPRA_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_SERIEALTAFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.SALTAFW >= @PRESUPUESTODECOMPRA_1_SERIEALTAFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_SERIEALTAFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.SALTAFW <= @PRESUPUESTODECOMPRA_1_SERIEALTAFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.SMODIFW >= @PRESUPUESTODECOMPRA_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.SMODIFW <= @PRESUPUESTODECOMPRA_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_USUARIOALTAFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.UALTAFW >= @PRESUPUESTODECOMPRA_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_USUARIOALTAFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.UALTAFW <= @PRESUPUESTODECOMPRA_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.UMODIFW >= @PRESUPUESTODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.UMODIFW <= @PRESUPUESTODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_VERSIONALTAFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.VALTAFW >= @PRESUPUESTODECOMPRA_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_VERSIONALTAFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.VALTAFW <= @PRESUPUESTODECOMPRA_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_PRESUPUESTODECOMPRA.VMODIFW >= @PRESUPUESTODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @PRESUPUESTODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_PRESUPUESTODECOMPRA.VMODIFW <= @PRESUPUESTODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA ) )
)
, ComprobantesAfectantes as
	(
	select 
		  dc.IDITEM
		, dc.FCANT
		, Afecta.AFETIPOCOM
		, Afecta.AFECTA
		, Afecta.CODIGO
	from ( select CODIGO, AFECTA, CODINTER, AFETIPOCOM from ZooLogic.COMPAFE where AFETIPO = 'Afectante' ) Afecta
		inner join ( select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.PRECOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.FACCOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.NCCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.REMCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.PEDCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.CANCOMPRADET
					) dc on Afecta.CODIGO = dc.AFE_COD and Afecta.AFECTA = dc.CODIGO
	where 1=1
	)
, ComprobantesRelacionadosAux( IDITEM, CODIGO, Cantidad, Tipo, TipoAfectado, Secuencia, SecuenciaAfectada, Afectado, Nivel ) as
	(
		select Principal.IDITEM,
			Principal.CODIGO,
			Principal.FCANT,
			Principal.FACTTIPO,
			cast( 0 as numeric(2,0)),
			cast( case 
				when Principal.FACTTIPO = 30 then 1 -- Presupuesto
				when Principal.FACTTIPO = 38 then 2	-- Pedido
				when Principal.FACTTIPO = 40 then 3	-- Remito
				when Principal.FACTTIPO =  8 then 4	-- Facturas
				else 5
			end as numeric(2, 0)),
			cast( 0 as numeric(2,0)),
			Principal.CODIGO,
			0 as nivel
		from ( select CODIGO, IDITEM, FACTTIPO, FCANT from ConjuntoBase ) as Principal

		union all

		select Anterior.IDITEM,
			Anterior.CODIGO,
			Afecta.FCANT,
			Afecta.AFETIPOCOM,
			Anterior.Tipo,
			cast(case 
				when Afecta.AFETIPOCOM = 30 then 1 -- Presupuesto
				when Afecta.AFETIPOCOM = 38 then 2	-- Pedido
				when Afecta.AFETIPOCOM = 40 then 3	-- Remito
				when Afecta.AFETIPOCOM =  8 then 4	-- Facturas
				when Afecta.AFETIPOCOM in (41, 10) and Anterior.TipoAfectado != 41 then -case 
																					when Anterior.Tipo = 30 then 1
																					when Anterior.Tipo = 38 then 2
																					when Anterior.Tipo = 40 then 3
																					when Anterior.Tipo =  8 then 4
																				else 5
																			end
			else 5
			end as numeric(2, 0)),
			cast(case 
				when Anterior.Tipo = 30 then 1
				when Anterior.Tipo = 38 then 2
				when Anterior.Tipo = 40 then 3
				when Anterior.Tipo =  8 then 4
			else 5
			end as numeric(2, 0)),
			Afecta.AFECTA,
			Anterior.nivel + 1
		from ComprobantesRelacionadosAux as Anterior
			inner join ComprobantesAfectantes Afecta on Anterior.Afectado = Afecta.CODIGO and Anterior.IDITEM = Afecta.IDITEM
	where 1=1
			and Anterior.nivel < 5
	)
, CantidadesDistribuidas as
	(
		select cantidades.CODIGO, cantidades.IDITEM
			, case cantidades.Secuencia          when  1								then cantidades.cantidad else 0 end as ConfirmadoS1
			, case cantidades.Secuencia          when -1								then cantidades.cantidad else 0 end as CanceladoS1
			, case when cantidades.SecuenciaAfectada = 1 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS1
			, case cantidades.Secuencia          when  2								then cantidades.cantidad else 0 end as ConfirmadoS2
			, case cantidades.Secuencia          when -2								then cantidades.cantidad else 0 end as CanceladoS2
			, case when cantidades.SecuenciaAfectada = 2 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS2
			, case cantidades.Secuencia          when  3								then cantidades.cantidad else 0 end as ConfirmadoS3
			, case cantidades.Secuencia          when -3								then cantidades.cantidad else 0 end as CanceladoS3
			, case when cantidades.SecuenciaAfectada = 3 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS3
			, case cantidades.Secuencia          when  4								then cantidades.cantidad else 0 end as ConfirmadoS4
			, case cantidades.Secuencia          when -4								then cantidades.cantidad else 0 end as CanceladoS4
			, case when cantidades.SecuenciaAfectada = 4 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS4
			, case cantidades.Secuencia          when  5								then cantidades.cantidad else 0 end as ConfirmadoS5
			, case cantidades.Secuencia          when -5								then cantidades.cantidad else 0 end as CanceladoS5
			, case when cantidades.SecuenciaAfectada = 5 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS5
		from ComprobantesRelacionadosAux cantidades
	)
, ResumenDeCantidades as
	(
	select CODIGO, IDITEM
		, cast( sum( ConfirmadoS1 ) as numeric( 9, 3 ) )							as confirmadopresupuesto
		, cast( sum( CanceladoS1 ) as numeric( 9, 3 ) )								as canceladopresupuesto
		, cast( sum( AfectadoS1 ) as numeric( 9, 3 ) )								as afectadopresupuesto
		, cast( sum( ConfirmadoS1 - CanceladoS1 - AfectadoS1 ) as numeric( 9, 3 ) ) as pendientepedido
		, cast( sum( ConfirmadoS2 ) as numeric( 9, 3 ) )							as confirmadopedido
		, cast( sum( CanceladoS2 ) as numeric( 9, 3 ) )								as canceladopedido
		, cast( sum( AfectadoS2 ) as numeric( 9, 3 ) )								as afectadopedido
		, cast( sum( ConfirmadoS2 - CanceladoS2 - AfectadoS2 ) as numeric( 9, 3 ) ) as pendienteremito
		, cast( sum( ConfirmadoS3 ) as numeric( 9, 3 ) )							as confirmadoremito
		, cast( sum( CanceladoS3 ) as numeric( 9, 3 ) )								as canceladoremito
		, cast( sum( AfectadoS3 ) as numeric( 9, 3 ) )								as afectadoremito
		, cast( sum( ConfirmadoS3 - CanceladoS3 - AfectadoS3 ) as numeric( 9, 3 ) ) as pendientefactura
		, cast( sum( ConfirmadoS4 ) as numeric( 9, 3 ) )							as confirmadofactura
		, cast( sum( CanceladoS4 ) as numeric( 9, 3 ) )								as canceladofactura
		, cast( sum( AfectadoS4 ) as numeric( 9, 3 ) )								as afectadofactura
		, cast( sum( ConfirmadoS5 ) as numeric( 9, 3 ) )							as confirmadonotas
		, cast( sum( CanceladoS5 ) as numeric( 9, 3 ) )								as canceladonotas
		, cast( sum( AfectadoS5 ) as numeric( 9, 3 ) )								as afectadonotas
	from CantidadesDistribuidas
	group by CODIGO, IDITEM
	)
Select cb.*, 
	cast( rc.confirmadopresupuesto	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CantidadTramo0Virtual,
	cast( rc.canceladopresupuesto	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CancelaTramo0Virtual,
	cast( rc.pendientepedido	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_PendienteTramo1Virtual,
	cast( rc.confirmadopedido	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CantidadTramo1Virtual,
	cast( rc.canceladopedido	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CancelaTramo1Virtual,
	cast( rc.pendienteremito	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_PendienteTramo2Virtual,
	cast( rc.confirmadoremito	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CantidadTramo2Virtual,
	cast( rc.canceladoremito	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CancelaTramo2Virtual,
	cast( rc.pendientefactura	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_PendienteTramo3Virtual,
	cast( rc.confirmadofactura	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CantidadTramo3Virtual,
	cast( rc.canceladofactura	as numeric( 9, 3 ) ) as ITEMARTICULOSPRECOMPRA_CancelaTramo3Virtual
from ConjuntoBase cb
	left join ResumenDeCantidades rc on cb.CODIGO = rc.CODIGO and cb.IDITEM = rc.IDITEM