IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_ASIENTO_ITEMASIENTO]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_ASIENTO_ITEMASIENTO];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_ASIENTO_ITEMASIENTO]
( @BaseDeDatos varchar(8),
	@ASIENTO_CODIGO_DESDE varchar(20),
	@ASIENTO_CODIGO_HASTA varchar(20),
	@ASIENTO_FUENTE_DESDE varchar(10),
	@ASIENTO_FUENTE_HASTA varchar(10),
	@ASIENTO_EJERCICIO_DESDE numeric(8, 0),
	@ASIENTO_EJERCICIO_HASTA numeric(8, 0),
	@ASIENTO_RAZONSOCIAL_DESDE varchar(10),
	@ASIENTO_RAZONSOCIAL_HASTA varchar(10),
	@ASIENTO_TIPO numeric(1, 0),
	@ASIENTO_CLASE numeric(1, 0),
	@ASIENTO_REFERENCIA_DESDE varchar(150),
	@ASIENTO_REFERENCIA_HASTA varchar(150),
	@ASIENTO_NUMERO_DESDE numeric(8, 0),
	@ASIENTO_NUMERO_HASTA numeric(8, 0),
	@ASIENTO_FECHA_DESDE datetime,
	@ASIENTO_FECHA_HASTA datetime,
	@EJERCICIO_22_EJERCICIO_DESCRIPCION_DESDE varchar(50),
	@EJERCICIO_22_EJERCICIO_DESCRIPCION_HASTA varchar(50),
	@RAZONSOCIAL_23_RAZONSOCIAL_DESCRIPCION_DESDE varchar(50),
	@RAZONSOCIAL_23_RAZONSOCIAL_DESCRIPCION_HASTA varchar(50),
	@SEGMENTACION_9209_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9209_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9208_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9208_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9207_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9207_TIPO_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9204_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9204_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9204_LINEA_DESDE varchar(10),
	@SUCURSAL_9204_LINEA_HASTA varchar(10),
	@SUCURSAL_9204_TIPO_DESDE varchar(10),
	@SUCURSAL_9204_TIPO_HASTA varchar(10),
	@SUCURSAL_9204_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9204_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_9204_CODIGO_DESDE varchar(10),
	@SUCURSAL_9204_CODIGO_HASTA varchar(10),
	@ASIENTO_BASEDEDATOSALTAFW_DESDE varchar(8),
	@ASIENTO_BASEDEDATOSALTAFW_HASTA varchar(8),
	@ASIENTO_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@ASIENTO_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@ASIENTO_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@ASIENTO_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@ASIENTO_FECHAALTAFW_DESDE datetime,
	@ASIENTO_FECHAALTAFW_HASTA datetime,
	@ASIENTO_FECHAEXPO_DESDE datetime,
	@ASIENTO_FECHAEXPO_HASTA datetime,
	@ASIENTO_FECHAIMPO_DESDE datetime,
	@ASIENTO_FECHAIMPO_HASTA datetime,
	@ASIENTO_FECHAMODIFICACIONFW_DESDE datetime,
	@ASIENTO_FECHAMODIFICACIONFW_HASTA datetime,
	@ASIENTO_FECHATRANSFERENCIA_DESDE datetime,
	@ASIENTO_FECHATRANSFERENCIA_HASTA datetime,
	@ASIENTO_HORAALTAFW_DESDE varchar(8),
	@ASIENTO_HORAALTAFW_HASTA varchar(8),
	@ASIENTO_HORAEXPO_DESDE varchar(8),
	@ASIENTO_HORAEXPO_HASTA varchar(8),
	@ASIENTO_HORAIMPO_DESDE varchar(8),
	@ASIENTO_HORAIMPO_HASTA varchar(8),
	@ASIENTO_HORAMODIFICACIONFW_DESDE varchar(8),
	@ASIENTO_HORAMODIFICACIONFW_HASTA varchar(8),
	@ASIENTO_SERIEALTAFW_DESDE varchar(7),
	@ASIENTO_SERIEALTAFW_HASTA varchar(7),
	@ASIENTO_SERIEMODIFICACIONFW_DESDE varchar(7),
	@ASIENTO_SERIEMODIFICACIONFW_HASTA varchar(7),
	@ASIENTO_USUARIOALTAFW_DESDE varchar(100),
	@ASIENTO_USUARIOALTAFW_HASTA varchar(100),
	@ASIENTO_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@ASIENTO_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@ASIENTO_VERSIONALTAFW_DESDE varchar(13),
	@ASIENTO_VERSIONALTAFW_HASTA varchar(13),
	@ASIENTO_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@ASIENTO_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select  top(100) percent cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemasiento.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMASIENTO__Grupo,
	@basededatos as ITEMASIENTO__BD,
	c_ITEMASIENTO.CODIGO as ITEMASIENTO_CODIGO,
	null as ITEMASIENTO_CODCCOS,
	cast( null as varchar( 30 ) ) as ITEMASIENTO_CuentaIndentadaSegunAplicacionVirtual,
	cast( null as varchar( 120 ) ) as ITEMASIENTO_DescripcionIndentadaSegunAplicacionVirtu,
	cast( null as varchar( 30 ) ) as ITEMASIENTO_PCUENTA,
	cast( null as varchar( 100 ) ) as ITEMASIENTO_PCUENTAD,
	cast( null as varchar( 150 ) ) as ITEMASIENTO_Leyenda,
	c_ITEMASIENTO.DEBE as ITEMASIENTO_DEBE,
	c_ITEMASIENTO.HABER as ITEMASIENTO_HABER,
	cast( null as numeric( 5, 0 ) ) as ITEMASIENTO_NROITEM,
	cast( c_ITEMASIENTO.CtaDebe as varchar( 30 ) ) as ITEMASIENTO_CuentaDebeVirtual,
	cast( c_ITEMASIENTO.DetDebe as varchar( 100 ) ) as ITEMASIENTO_DetalleDebeVirtual,
	cast( c_ITEMASIENTO.LydDebe as varchar( 150 ) ) as ITEMASIENTO_LeyendaDebeVirtual,
	cast( c_ITEMASIENTO.NIDebe as numeric( 5, 0 ) ) as ITEMASIENTO_NroItemDebeVirtual,
	cast( c_ITEMASIENTO.CtaHaber as varchar( 30 ) ) as ITEMASIENTO_CuentaHaberVirtual,
	cast( c_ITEMASIENTO.DetHaber as varchar( 100 ) ) as ITEMASIENTO_DetalleHaberVirtual,
	cast( c_ITEMASIENTO.LydHaber as varchar( 150 ) ) as ITEMASIENTO_LeyendaHaberVirtual,
	cast( c_ITEMASIENTO.NIHaber as numeric( 5, 0 ) ) as ITEMASIENTO_NroItemHaberVirtual,
	null as CENTRODECOSTO_COSDES,
	null as PLANDECUENTAS_descrip,
	null as CENTRODECOSTO_COSCOD,
	null as PLANDECUENTAS_ctacodigo
	from Listados.Vista_ASIENTODET as c_ITEMASIENTO
	left join ZooLogic.PLANCUENTA as C_PLANDECUENTAS on C_PLANDECUENTAS.CTACODIGO is null
	inner join ZooLogic.ASIENTO as C_ASIENTO_CABECERA on C_ASIENTO_CABECERA.ACOD = C_ITEMASIENTO.CODIGO
	left join ZooLogic.EJERCICIO as C_EJERCICIO_CABECERA on C_EJERCICIO_CABECERA.NUMERO = C_ASIENTO_CABECERA.EJERCICIO and 0 = Funciones.empty( C_ASIENTO_CABECERA.EJERCICIO )
	left join ZooLogic.RAZONS as C_RAZONSOCIAL_CABECERA on C_RAZONSOCIAL_CABECERA.RZCOD = C_ASIENTO_CABECERA.RSOCIAL and 0 = Funciones.empty( C_ASIENTO_CABECERA.RSOCIAL )
	left join ORGANIZACION.SUC as C_SUCURSAL_CABECERA on C_SUCURSAL_CABECERA.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
	left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL_CABECERA on C_TIPOSUCURSAL_CABECERA.TCOD = C_SUCURSAL_CABECERA.TIPO and 0 = Funciones.empty( C_SUCURSAL_CABECERA.TIPO )
	left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL_CABECERA on C_LINEASUCURSAL_CABECERA.LSCOD = C_SUCURSAL_CABECERA.LINEA and 0 = Funciones.empty( C_SUCURSAL_CABECERA.LINEA )
	left join ORGANIZACION.SECOD as C_SEGMENTACION_CABECERA on C_SEGMENTACION_CABECERA.SCOD = C_SUCURSAL_CABECERA.SEG and 0 = Funciones.empty( C_SUCURSAL_CABECERA.SEG )
	where ( not 1 = funciones.empty( c_asiento_cabecera.acod ) ) and 
	( ( @ASIENTO_CODIGO_DESDE is null ) OR ( C_ASIENTO_CABECERA.ACOD >= @ASIENTO_CODIGO_DESDE ) ) and 
	( ( @ASIENTO_CODIGO_HASTA is null ) OR ( C_ASIENTO_CABECERA.ACOD <= @ASIENTO_CODIGO_HASTA ) ) and 
	( ( @ASIENTO_FUENTE_DESDE is null ) OR ( C_ASIENTO_CABECERA.Fuente >= @ASIENTO_FUENTE_DESDE ) ) and 
	( ( @ASIENTO_FUENTE_HASTA is null ) OR ( C_ASIENTO_CABECERA.Fuente <= @ASIENTO_FUENTE_HASTA ) ) and 
	( ( @ASIENTO_EJERCICIO_DESDE is null ) OR ( C_ASIENTO_CABECERA.Ejercicio >= @ASIENTO_EJERCICIO_DESDE ) ) and 
	( ( @ASIENTO_EJERCICIO_HASTA is null ) OR ( C_ASIENTO_CABECERA.Ejercicio <= @ASIENTO_EJERCICIO_HASTA ) ) and 
	( ( @ASIENTO_RAZONSOCIAL_DESDE is null ) OR ( C_ASIENTO_CABECERA.RSOCIAL >= @ASIENTO_RAZONSOCIAL_DESDE ) ) and 
	( ( @ASIENTO_RAZONSOCIAL_HASTA is null ) OR ( C_ASIENTO_CABECERA.RSOCIAL <= @ASIENTO_RAZONSOCIAL_HASTA ) ) and 
	( ( @ASIENTO_TIPO is null ) OR ( C_ASIENTO_CABECERA.TipoAsient = @ASIENTO_TIPO ) ) and 
	( ( @ASIENTO_CLASE is null ) OR ( C_ASIENTO_CABECERA.Clase = @ASIENTO_CLASE ) ) and 
	( ( @ASIENTO_REFERENCIA_DESDE is null ) OR ( C_ASIENTO_CABECERA.REFEREN >= @ASIENTO_REFERENCIA_DESDE ) ) and 
	( ( @ASIENTO_REFERENCIA_HASTA is null ) OR ( C_ASIENTO_CABECERA.REFEREN <= @ASIENTO_REFERENCIA_HASTA ) ) and 
	( ( @ASIENTO_NUMERO_DESDE is null ) OR ( C_ASIENTO_CABECERA.NUMERO >= @ASIENTO_NUMERO_DESDE ) ) and 
	( ( @ASIENTO_NUMERO_HASTA is null ) OR ( C_ASIENTO_CABECERA.NUMERO <= @ASIENTO_NUMERO_HASTA ) ) and 
	( ( @ASIENTO_FECHA_DESDE is null ) OR ( C_ASIENTO_CABECERA.Fecha >= @ASIENTO_FECHA_DESDE ) ) and 
	( ( @ASIENTO_FECHA_HASTA is null ) OR ( C_ASIENTO_CABECERA.Fecha <= @ASIENTO_FECHA_HASTA ) ) and 
	( ( @EJERCICIO_22_EJERCICIO_DESCRIPCION_DESDE is null ) OR ( C_EJERCICIO_CABECERA.DESCRIP >= @EJERCICIO_22_EJERCICIO_DESCRIPCION_DESDE ) ) and 
	( ( @EJERCICIO_22_EJERCICIO_DESCRIPCION_HASTA is null ) OR ( C_EJERCICIO_CABECERA.DESCRIP <= @EJERCICIO_22_EJERCICIO_DESCRIPCION_HASTA ) ) and 
	( ( @RAZONSOCIAL_23_RAZONSOCIAL_DESCRIPCION_DESDE is null ) OR ( C_RAZONSOCIAL_CABECERA.RZDES >= @RAZONSOCIAL_23_RAZONSOCIAL_DESCRIPCION_DESDE ) ) and 
	( ( @RAZONSOCIAL_23_RAZONSOCIAL_DESCRIPCION_HASTA is null ) OR ( C_RAZONSOCIAL_CABECERA.RZDES <= @RAZONSOCIAL_23_RAZONSOCIAL_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9209_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION_CABECERA.SDES >= @SEGMENTACION_9209_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9209_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION_CABECERA.SDES <= @SEGMENTACION_9209_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9208_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES >= @LINEASUCURSAL_9208_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9208_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL_CABECERA.LSDES <= @LINEASUCURSAL_9208_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9207_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES >= @TIPOSUCURSAL_9207_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9207_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL_CABECERA.TDES <= @TIPOSUCURSAL_9207_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9204_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.seg >= @SUCURSAL_9204_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9204_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.seg <= @SUCURSAL_9204_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9204_LINEA_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Linea >= @SUCURSAL_9204_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9204_LINEA_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Linea <= @SUCURSAL_9204_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9204_TIPO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.Tipo >= @SUCURSAL_9204_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9204_TIPO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.Tipo <= @SUCURSAL_9204_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9204_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL_CABECERA.descrip >= @SUCURSAL_9204_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9204_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL_CABECERA.descrip <= @SUCURSAL_9204_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9204_CODIGO_DESDE is null ) OR ( C_SUCURSAL_CABECERA.codigo >= @SUCURSAL_9204_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9204_CODIGO_HASTA is null ) OR ( C_SUCURSAL_CABECERA.codigo <= @SUCURSAL_9204_CODIGO_HASTA ) ) and 
	( ( @ASIENTO_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.BDALTAFW >= @ASIENTO_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @ASIENTO_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.BDALTAFW <= @ASIENTO_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @ASIENTO_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.BDMODIFW >= @ASIENTO_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @ASIENTO_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.BDMODIFW <= @ASIENTO_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @ASIENTO_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_ASIENTO_CABECERA.ESTTRANS >= @ASIENTO_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @ASIENTO_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_ASIENTO_CABECERA.ESTTRANS <= @ASIENTO_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @ASIENTO_FECHAALTAFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.FALTAFW >= @ASIENTO_FECHAALTAFW_DESDE ) ) and 
	( ( @ASIENTO_FECHAALTAFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.FALTAFW <= @ASIENTO_FECHAALTAFW_HASTA ) ) and 
	( ( @ASIENTO_FECHAEXPO_DESDE is null ) OR ( C_ASIENTO_CABECERA.FECEXPO >= @ASIENTO_FECHAEXPO_DESDE ) ) and 
	( ( @ASIENTO_FECHAEXPO_HASTA is null ) OR ( C_ASIENTO_CABECERA.FECEXPO <= @ASIENTO_FECHAEXPO_HASTA ) ) and 
	( ( @ASIENTO_FECHAIMPO_DESDE is null ) OR ( C_ASIENTO_CABECERA.FECIMPO >= @ASIENTO_FECHAIMPO_DESDE ) ) and 
	( ( @ASIENTO_FECHAIMPO_HASTA is null ) OR ( C_ASIENTO_CABECERA.FECIMPO <= @ASIENTO_FECHAIMPO_HASTA ) ) and 
	( ( @ASIENTO_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.FMODIFW >= @ASIENTO_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @ASIENTO_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.FMODIFW <= @ASIENTO_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @ASIENTO_FECHATRANSFERENCIA_DESDE is null ) OR ( C_ASIENTO_CABECERA.FECTRANS >= @ASIENTO_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @ASIENTO_FECHATRANSFERENCIA_HASTA is null ) OR ( C_ASIENTO_CABECERA.FECTRANS <= @ASIENTO_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @ASIENTO_HORAALTAFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.HALTAFW >= @ASIENTO_HORAALTAFW_DESDE ) ) and 
	( ( @ASIENTO_HORAALTAFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.HALTAFW <= @ASIENTO_HORAALTAFW_HASTA ) ) and 
	( ( @ASIENTO_HORAEXPO_DESDE is null ) OR ( C_ASIENTO_CABECERA.HORAEXPO >= @ASIENTO_HORAEXPO_DESDE ) ) and 
	( ( @ASIENTO_HORAEXPO_HASTA is null ) OR ( C_ASIENTO_CABECERA.HORAEXPO <= @ASIENTO_HORAEXPO_HASTA ) ) and 
	( ( @ASIENTO_HORAIMPO_DESDE is null ) OR ( C_ASIENTO_CABECERA.HORAIMPO >= @ASIENTO_HORAIMPO_DESDE ) ) and 
	( ( @ASIENTO_HORAIMPO_HASTA is null ) OR ( C_ASIENTO_CABECERA.HORAIMPO <= @ASIENTO_HORAIMPO_HASTA ) ) and 
	( ( @ASIENTO_HORAMODIFICACIONFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.HMODIFW >= @ASIENTO_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @ASIENTO_HORAMODIFICACIONFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.HMODIFW <= @ASIENTO_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @ASIENTO_SERIEALTAFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.SALTAFW >= @ASIENTO_SERIEALTAFW_DESDE ) ) and 
	( ( @ASIENTO_SERIEALTAFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.SALTAFW <= @ASIENTO_SERIEALTAFW_HASTA ) ) and 
	( ( @ASIENTO_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.SMODIFW >= @ASIENTO_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @ASIENTO_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.SMODIFW <= @ASIENTO_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @ASIENTO_USUARIOALTAFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.UALTAFW >= @ASIENTO_USUARIOALTAFW_DESDE ) ) and 
	( ( @ASIENTO_USUARIOALTAFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.UALTAFW <= @ASIENTO_USUARIOALTAFW_HASTA ) ) and 
	( ( @ASIENTO_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.UMODIFW >= @ASIENTO_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @ASIENTO_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.UMODIFW <= @ASIENTO_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @ASIENTO_VERSIONALTAFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.VALTAFW >= @ASIENTO_VERSIONALTAFW_DESDE ) ) and 
	( ( @ASIENTO_VERSIONALTAFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.VALTAFW <= @ASIENTO_VERSIONALTAFW_HASTA ) ) and 
	( ( @ASIENTO_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_ASIENTO_CABECERA.VMODIFW >= @ASIENTO_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @ASIENTO_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_ASIENTO_CABECERA.VMODIFW <= @ASIENTO_VERSIONMODIFICACIONFW_HASTA ) )
	ORDER BY (CASE WHEN c_ITEMASIENTO.CtaDebe IS NULL THEN 1 ELSE 0 END), c_ITEMASIENTO.CtaDebe, (CASE WHEN c_ITEMASIENTO.CtaHaber IS NULL THEN 1 ELSE 0 END), c_ITEMASIENTO.CtaHaber 
)