IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[VAL_ITEMVALORESAREC]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[VAL_ITEMVALORESAREC];
GO;

CREATE FUNCTION [Listados].[VAL_ITEMVALORESAREC]
(
	@ITEMVALORES_FECHA_DESDE datetime,
	@ITEMVALORES_FECHA_HASTA datetime
)
RETURNS TABLE
AS
RETURN
(
select
	c_CANJEDECUPONESAREC.FALTAFW + convert( datetime, c_CANJEDECUPONESAREC.HALTAFW) as MARCATEMPORAL,
	4 as ORDEN,
	c_ITEMVALORESAREC.COTIZA,
	c_ITEMVALORESAREC.CUPON,
	c_ITEMVALORESAREC.FECHCOTI,
	c_ITEMVALORESAREC.GUIDCUPON,
	c_ITEMVALORESAREC.IDCAJA,
	c_ITEMVALORESAREC.JJCO,
	c_ITEMVALORESAREC.JJCOTIZ,
	c_ITEMVALORESAREC.JJDE,
	c_CANJEDECUPONESAREC.FECHA as JJFE,
	c_CANJEDECUPONESAREC.FECHA as JJFECHA,
	c_ITEMVALORESAREC.JJM,
	c_ITEMVALORESAREC.JJNUM,
	c_CANJEDECUPONESAREC.FACTTIPO as JJT,
	c_ITEMVALORESAREC.JJTOTFAC,
	c_ITEMVALORESAREC.JJTOTFAC as JJrecib,
	cast(0 as numeric(1, 0)) as JJTURNO,
	c_CANJEDECUPONESAREC.VENDEDOR as JJVEN,
	c_CANJEDECUPONESAREC.FLETRA as LETRA,
	c_ITEMVALORESAREC.NROCHEQUE,
	c_ITEMVALORESAREC.NROCHPROP,
	cast('' as varchar(10)) as NRODOC,
	c_ITEMVALORESAREC.NROINTERNO,
	c_ITEMVALORESAREC.NROITEM,
	c_CANJEDECUPONESAREC.NUMERO as NUMCOMPR,
	c_ITEMVALORESAREC.PERMVUELTO,
	c_ITEMVALORESAREC.PERSCOMP,
	c_ITEMVALORESAREC.PESOS,
	c_ITEMVALORESAREC.MONTOSISTE,
	c_ITEMVALORESAREC.PESOS as RECPESOS,
	c_CANJEDECUPONESAREC.FPTOVEN as PTOVENTA,
	cast(0 as numeric(12, 2)) as RECMONTO,
	cast(0 as numeric(6, 2)) as RECPORC,
	cast(0 as numeric(12, 2)) as RECSINIMP,
	cast(0 as numeric(12, 2)) as RECSINPER,
	cast('' as varchar(10)) as REDONDEO,
	c_ITEMVALORESAREC.SIGNO,
	c_ITEMVALORESAREC.TIPCOMP,
	c_ITEMVALORESAREC.TIPODOC,
	cast('' as char(38)) as VALECAMBIO,
	c_ITEMVALORESAREC.AUTORIZADO,
	cast('' as varchar(38)) as IDITEM,
	cast(0 as numeric(12, 2)) as DESCMONTO,
	cast(0 as numeric(6, 2)) as DESCPORC,
	cast(0 as numeric(15, 2)) as DESCSINIMP,
	cast(0 as numeric(12, 2)) as MONDESPES,
	cast(0 as numeric(12, 2)) as MONDESREC,
	cast(0 as numeric(12, 2)) as MONRECPES,
	cast(0 as numeric(6, 2 )) as PORCDESREC,
	cast(0 as bit) as EsVuelto,
	c_CANJEDECUPONESAREC.faltafw,
	c_CANJEDECUPONESAREC.HALTAFW,
	c_CANJEDECUPONESAREC.BDALTAFW,
	c_CANJEDECUPONESAREC.BDMODIFW,
	c_CANJEDECUPONESAREC.ESTTRANS,
	c_CANJEDECUPONESAREC.fecexpo,
	c_CANJEDECUPONESAREC.fecimpo, 
	c_CANJEDECUPONESAREC.fmodifw,
	c_CANJEDECUPONESAREC.fectrans,
	c_CANJEDECUPONESAREC.HORAEXPO,
	c_CANJEDECUPONESAREC.HORAIMPO,
	c_CANJEDECUPONESAREC.HMODIFW,
	c_CANJEDECUPONESAREC.SALTAFW, 
	c_CANJEDECUPONESAREC.SMODIFW, 
	c_CANJEDECUPONESAREC.UALTAFW, 
	c_CANJEDECUPONESAREC.UMODIFW, 
	c_CANJEDECUPONESAREC.VALTAFW, 
	c_CANJEDECUPONESAREC.VMODIFW, 
	c_CANJEDECUPONESAREC.ZADSFW 
from ZooLogic.CANJECUPONESDET as c_ITEMVALORESAREC
	left join ZooLogic.CANJECUPONES as c_CANJEDECUPONESAREC on c_CANJEDECUPONESAREC.CODIGO = c_ITEMVALORESAREC.JJNUM
where ( c_CANJEDECUPONESAREC.ANULADO = 0 ) and 
	( ( @ITEMVALORES_FECHA_DESDE is null ) OR ( c_CANJEDECUPONESAREC.FECHA >= @ITEMVALORES_FECHA_DESDE ) ) and 
	( ( @ITEMVALORES_FECHA_HASTA is null ) OR ( c_CANJEDECUPONESAREC.FECHA <= @ITEMVALORES_FECHA_HASTA ) )
)
