IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_FACTURADECOMPRA_ITEMARTICULOSCOMPRA_CIS_ITEMARTICULOSCOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_FACTURADECOMPRA_ITEMARTICULOSCOMPRA_CIS_ITEMARTICULOSCOMPRA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_FACTURADECOMPRA_ITEMARTICULOSCOMPRA_CIS_ITEMARTICULOSCOMPRA]
( @BaseDeDatos varchar(8),
	@ITEMARTICULOSCOMPRA_ARTICULO_DESDE varchar(15),
	@ITEMARTICULOSCOMPRA_ARTICULO_HASTA varchar(15),
	@ITEMARTICULOSCOMPRA_ARTICULODETALLE_DESDE varchar(100),
	@ITEMARTICULOSCOMPRA_ARTICULODETALLE_HASTA varchar(100),
	@ITEMARTICULOSCOMPRA_COLOR_DESDE varchar(6),
	@ITEMARTICULOSCOMPRA_COLOR_HASTA varchar(6),
	@ITEMARTICULOSCOMPRA_COLORDETALLE_DESDE varchar(50),
	@ITEMARTICULOSCOMPRA_COLORDETALLE_HASTA varchar(50),
	@ITEMARTICULOSCOMPRA_TALLE_DESDE varchar(5),
	@ITEMARTICULOSCOMPRA_TALLE_HASTA varchar(5),
	@ITEMARTICULOSCOMPRA_CENTRODECOSTO_DESDE varchar(20),
	@ITEMARTICULOSCOMPRA_CENTRODECOSTO_HASTA varchar(20),
	@ITEMARTICULOSCOMPRA_PRECIO_DESDE numeric(14, 4),
	@ITEMARTICULOSCOMPRA_PRECIO_HASTA numeric(14, 4),
	@FACTURADECOMPRA_1_CODIGO_DESDE varchar(38),
	@FACTURADECOMPRA_1_CODIGO_HASTA varchar(38),
	@FACTURADECOMPRA_1_TIPOCOMPROBANTERG1361 numeric(2, 0),
	@FACTURADECOMPRA_1_LETRA_DESDE varchar(2),
	@FACTURADECOMPRA_1_LETRA_HASTA varchar(2),
	@FACTURADECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE numeric(5, 0),
	@FACTURADECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA numeric(5, 0),
	@FACTURADECOMPRA_1_NUMERO_DESDE numeric(8, 0),
	@FACTURADECOMPRA_1_NUMERO_HASTA numeric(8, 0),
	@FACTURADECOMPRA_1_PUNTODEVENTA_DESDE numeric(4, 0),
	@FACTURADECOMPRA_1_PUNTODEVENTA_HASTA numeric(4, 0),
	@FACTURADECOMPRA_1_PROVEEDOR_DESDE varchar(10),
	@FACTURADECOMPRA_1_PROVEEDOR_HASTA varchar(10),
	@FACTURADECOMPRA_1_NUMINT_DESDE numeric(10, 0),
	@FACTURADECOMPRA_1_NUMINT_HASTA numeric(10, 0),
	@FACTURADECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE varchar(5),
	@FACTURADECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA varchar(5),
	@FACTURADECOMPRA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURADECOMPRA_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@FACTURADECOMPRA_1_LISTADEPRECIOS_DESDE varchar(6),
	@FACTURADECOMPRA_1_LISTADEPRECIOS_HASTA varchar(6),
	@FACTURADECOMPRA_1_REMITO_DESDE varchar(16),
	@FACTURADECOMPRA_1_REMITO_HASTA varchar(16),
	@FACTURADECOMPRA_1_FECHA_DESDE datetime,
	@FACTURADECOMPRA_1_FECHA_HASTA datetime,
	@FACTURADECOMPRA_1_FECHAFACTURA_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAFACTURA_HASTA datetime,
	@FACTURADECOMPRA_1_COTIZACION_DESDE numeric(15, 5),
	@FACTURADECOMPRA_1_COTIZACION_HASTA numeric(15, 5),
	@FACTURADECOMPRA_1_FECHAVENCIMIENTO_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAVENCIMIENTO_HASTA datetime,
	@FACTURADECOMPRA_1_CAI_DESDE numeric(14, 0),
	@FACTURADECOMPRA_1_CAI_HASTA numeric(14, 0),
	@FACTURADECOMPRA_1_FECHAVTOCAI_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAVTOCAI_HASTA datetime,
	@FACTURADECOMPRA_1_CENTRODECOSTO_DESDE varchar(20),
	@FACTURADECOMPRA_1_CENTRODECOSTO_HASTA varchar(20),
	@FACTURADECOMPRA_1_DISTRIBUCIONPORCENTRODECOSTO_DESDE varchar(20),
	@FACTURADECOMPRA_1_DISTRIBUCIONPORCENTRODECOSTO_HASTA varchar(20),
	@FACTURADECOMPRA_1_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@FACTURADECOMPRA_1_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@FACTURADECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE numeric(15, 2),
	@FACTURADECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA numeric(15, 2),
	@FACTURADECOMPRA_1_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@FACTURADECOMPRA_1_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@PROVEEDOR_98_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_98_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@CONDICIONDEPAGO_143_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_143_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA varchar(100),
	@MONEDA_144_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_144_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@LISTADEPRECIOS_145_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_145_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CENTRODECOSTO_153_CENTRODECOSTO_DESCRIPCION_DESDE varchar(150),
	@CENTRODECOSTO_153_CENTRODECOSTO_DESCRIPCION_HASTA varchar(150),
	@DISTRIBUCIONCENTRODECOSTO_154_DISTRIBUCIONPORCENTRODECOSTO_DESCRIP_DESDE varchar(150),
	@DISTRIBUCIONCENTRODECOSTO_154_DISTRIBUCIONPORCENTRODECOSTO_DESCRIP_HASTA varchar(150),
	@SEGMENTACION_305_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_305_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_304_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_304_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_303_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_303_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_12_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_12_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_13_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_13_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE varchar(40),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA varchar(40),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE varchar(150),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA varchar(150),
	@MARCA_42_MARCA_DESCRIPCION_DESDE varchar(100),
	@MARCA_42_MARCA_DESCRIPCION_HASTA varchar(100),
	@PROVINCIA_101_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_101_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_117_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_117_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_119_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_119_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_121_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_121_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_124_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_124_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_126_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_126_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_127_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_127_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_128_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_128_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_137_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_137_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_300_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_300_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_300_LINEA_DESDE varchar(10),
	@SUCURSAL_300_LINEA_HASTA varchar(10),
	@SUCURSAL_300_TIPO_DESDE varchar(10),
	@SUCURSAL_300_TIPO_HASTA varchar(10),
	@SUCURSAL_300_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_300_DESCRIPCION_HASTA varchar(50),
	@ARTICULO_2_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_2_PROVEEDOR_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVAVENTAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA numeric(5, 2),
	@ARTICULO_2_IMAGEN_DESDE varchar(180),
	@ARTICULO_2_IMAGEN_HASTA varchar(180),
	@ARTICULO_2_TEMPORADA_DESDE varchar(5),
	@ARTICULO_2_TEMPORADA_HASTA varchar(5),
	@ARTICULO_2_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_2_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_2_FAMILIA_DESDE varchar(10),
	@ARTICULO_2_FAMILIA_HASTA varchar(10),
	@ARTICULO_2_MATERIAL_DESDE varchar(10),
	@ARTICULO_2_MATERIAL_HASTA varchar(10),
	@ARTICULO_2_LINEA_DESDE varchar(10),
	@ARTICULO_2_LINEA_HASTA varchar(10),
	@ARTICULO_2_GRUPO_DESDE varchar(10),
	@ARTICULO_2_GRUPO_HASTA varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_2_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_2_ANO_DESDE numeric(4, 0),
	@ARTICULO_2_ANO_HASTA numeric(4, 0),
	@ARTICULO_2_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_2_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVACOMPRAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA numeric(5, 2),
	@ARTICULO_2_COMPORTAMIENTO numeric(1, 0),
	@ARTICULO_2_PALETADECOLORES_DESDE varchar(10),
	@ARTICULO_2_PALETADECOLORES_HASTA varchar(10),
	@ARTICULO_2_CURVADETALLES_DESDE varchar(10),
	@ARTICULO_2_CURVADETALLES_HASTA varchar(10),
	@ARTICULO_2_NOCOMERCIALIZABLE_DESDE datetime,
	@ARTICULO_2_NOCOMERCIALIZABLE_HASTA datetime,
	@ARTICULO_2_NOMENCLADOR_DESDE varchar(6),
	@ARTICULO_2_NOMENCLADOR_HASTA varchar(6),
	@ARTICULO_2_NOPERMITEDEVOLUCIONES bit,
	@ARTICULO_2_IMPRIMEDESPACHO bit,
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA numeric(5, 2),
	@ARTICULO_2_RESTRINGIRDESCUENTOS bit,
	@ARTICULO_2_PESO_DESDE numeric(11, 3),
	@ARTICULO_2_PESO_HASTA numeric(11, 3),
	@ARTICULO_2_LARGO_DESDE numeric(11, 2),
	@ARTICULO_2_LARGO_HASTA numeric(11, 2),
	@ARTICULO_2_ANCHO_DESDE numeric(11, 2),
	@ARTICULO_2_ANCHO_HASTA numeric(11, 2),
	@ARTICULO_2_ALTO_DESDE numeric(11, 2),
	@ARTICULO_2_ALTO_HASTA numeric(11, 2),
	@ARTICULO_2_REQUIERECCOSTO_DESDE numeric(1, 0),
	@ARTICULO_2_REQUIERECCOSTO_HASTA numeric(1, 0),
	@ARTICULO_2_NOPUBLICARENECOMMERCE bit,
	@ARTICULO_2_IMPORTADO bit,
	@ARTICULO_2_DESCRIPCIONADICIONAL_DESDE varchar(254),
	@ARTICULO_2_DESCRIPCIONADICIONAL_HASTA varchar(254),
	@ARTICULO_2_SOLOPROMOYKIT bit,
	@ARTICULO_2_RESTRINGIRARTICULO_DESDE datetime,
	@ARTICULO_2_RESTRINGIRARTICULO_HASTA datetime,
	@ARTICULO_2_MARCA_DESDE varchar(30),
	@ARTICULO_2_MARCA_HASTA varchar(30),
	@ARTICULO_2_PERCEPCIONIVARG5329 numeric(1, 0),
	@PROVEEDOR_98_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_98_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_98_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_98_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_98_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_98_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_98_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_98_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_98_FAX_DESDE varchar(60),
	@PROVEEDOR_98_FAX_HASTA varchar(60),
	@PROVEEDOR_98_EMAIL_DESDE varchar(250),
	@PROVEEDOR_98_EMAIL_HASTA varchar(250),
	@PROVEEDOR_98_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_98_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_106_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_98_CUIT_DESDE varchar(15),
	@PROVEEDOR_98_CUIT_HASTA varchar(15),
	@PROVEEDOR_98_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_98_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_98_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_98_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_98_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_98_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_98_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_98_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_98_CALLE_DESDE varchar(70),
	@PROVEEDOR_98_CALLE_HASTA varchar(70),
	@PROVEEDOR_98_PISO_DESDE varchar(3),
	@PROVEEDOR_98_PISO_HASTA varchar(3),
	@PROVEEDOR_98_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_98_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_98_PAIS_DESDE varchar(3),
	@PROVEEDOR_98_PAIS_HASTA varchar(3),
	@PROVEEDOR_98_MOVIL_DESDE varchar(30),
	@PROVEEDOR_98_MOVIL_HASTA varchar(30),
	@PROVEEDOR_98_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_98_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_98_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_98_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_98_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_98_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_98_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_98_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_98_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_98_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_98_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_98_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_98_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_98_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_98_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_98_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_98_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_98_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_98_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_98_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_98_EMPLEADOR bit,
	@PROVEEDOR_98_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_98_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_98_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_98_SUJETOVINCULADO bit,
	@PROVEEDOR_98_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_98_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_98_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_98_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_98_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_98_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_98_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_98_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_98_TASACEROAPLICA bit,
	@PROVEEDOR_98_RUT_DESDE varchar(12),
	@PROVEEDOR_98_RUT_HASTA varchar(12),
	@PROVEEDOR_98_INACTIVOFW bit,
	@SUCURSAL_300_CODIGO_DESDE varchar(10),
	@SUCURSAL_300_CODIGO_HASTA varchar(10),
	@ITEMARTICULOSCOMPRA_NROITEM_DESDE numeric(5, 0),
	@ITEMARTICULOSCOMPRA_NROITEM_HASTA numeric(5, 0),
	@FACTURADECOMPRA_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@FACTURADECOMPRA_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURADECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@FACTURADECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@FACTURADECOMPRA_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@FACTURADECOMPRA_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@FACTURADECOMPRA_1_FECHAALTAFW_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAALTAFW_HASTA datetime,
	@FACTURADECOMPRA_1_FECHAEXPO_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAEXPO_HASTA datetime,
	@FACTURADECOMPRA_1_FECHAIMPO_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAIMPO_HASTA datetime,
	@FACTURADECOMPRA_1_FECHAMODIFICACIONFW_DESDE datetime,
	@FACTURADECOMPRA_1_FECHAMODIFICACIONFW_HASTA datetime,
	@FACTURADECOMPRA_1_FECHATRANSFERENCIA_DESDE datetime,
	@FACTURADECOMPRA_1_FECHATRANSFERENCIA_HASTA datetime,
	@FACTURADECOMPRA_1_HORAALTAFW_DESDE varchar(8),
	@FACTURADECOMPRA_1_HORAALTAFW_HASTA varchar(8),
	@FACTURADECOMPRA_1_HORAEXPO_DESDE varchar(8),
	@FACTURADECOMPRA_1_HORAEXPO_HASTA varchar(8),
	@FACTURADECOMPRA_1_HORAIMPO_DESDE varchar(8),
	@FACTURADECOMPRA_1_HORAIMPO_HASTA varchar(8),
	@FACTURADECOMPRA_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@FACTURADECOMPRA_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@FACTURADECOMPRA_1_SERIEALTAFW_DESDE varchar(7),
	@FACTURADECOMPRA_1_SERIEALTAFW_HASTA varchar(7),
	@FACTURADECOMPRA_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@FACTURADECOMPRA_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@FACTURADECOMPRA_1_USUARIOALTAFW_DESDE varchar(100),
	@FACTURADECOMPRA_1_USUARIOALTAFW_HASTA varchar(100),
	@FACTURADECOMPRA_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@FACTURADECOMPRA_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@FACTURADECOMPRA_1_VERSIONALTAFW_DESDE varchar(13),
	@FACTURADECOMPRA_1_VERSIONALTAFW_HASTA varchar(13),
	@FACTURADECOMPRA_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@FACTURADECOMPRA_1_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@FACTURADECOMPRA_TIPOCOMPROBANTE numeric(2, 0),
	@Parametro1 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticuloscompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSCOMPRA__BD,
	c_ITEMARTICULOSCOMPRA.CODIGO as ITEMARTICULOSCOMPRA_CODIGO,
	c_ITEMARTICULOSCOMPRA.FART as ITEMARTICULOSCOMPRA_FART,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.fcfitot as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_FCFITot,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.fneto as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_FNETO,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.mntprecci as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPRECCI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.mntptot as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPTOT,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.mntpper as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPPER,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.mntpdesci as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPDESCI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.mntprecsi as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPRECSI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.mntpdessi as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPDESSI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.mnpdsi as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_MNPDSI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.mndesci as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_MNDESCI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.mndessi as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_MNDESSI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.fbruto as numeric( 15, 4 ) ) as ITEMARTICULOSCOMPRA_FBruto,
	c_ITEMARTICULOSCOMPRA.FTXT as ITEMARTICULOSCOMPRA_FTXT,
	c_ITEMARTICULOSCOMPRA.FCOLO as ITEMARTICULOSCOMPRA_FCOLO,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticuloscompra.fart, c_itemarticuloscompra.fcolo, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSCOMPRA_OrdenPaletaColores,
	c_ITEMARTICULOSCOMPRA.FCOTXT as ITEMARTICULOSCOMPRA_FCOTXT,
	cast( c_facturadecompra.cotiz*c_itemarticuloscompra.mntpiva as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_MNTPIVA, -- out signomov y (-1) porque se muestran juntos crédito y restitución => va con mismo signo que NetoGravadoVirtual
	c_ITEMARTICULOSCOMPRA.FTALL as ITEMARTICULOSCOMPRA_FTALL,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticuloscompra.fart, c_itemarticuloscompra.ftall, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSCOMPRA_OrdenCurvaTalles,
	c_ITEMARTICULOSCOMPRA.CCOSTO as ITEMARTICULOSCOMPRA_CCOSTO,
	cast( c_facturadecompra.signomov*-1*c_itemarticuloscompra.fcant as numeric( 8, 2 ) ) as ITEMARTICULOSCOMPRA_FCANT,
	c_ITEMARTICULOSCOMPRA.FPRECIO as ITEMARTICULOSCOMPRA_FPRECIO,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.fcfi as numeric( 7, 2 ) ) as ITEMARTICULOSCOMPRA_FCFI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_itemarticuloscompra.mntdes as numeric( 12, 2 ) ) as ITEMARTICULOSCOMPRA_MNTDES,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_itemarticuloscompra.fmonto as numeric( 15, 2 ) ) as ITEMARTICULOSCOMPRA_FMONTO,
	C_FACTURADECOMPRA.CODIGO as FACTURADECOMPRA_CODIGO,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fsubtot as numeric( 15, 2 ) ) as FACTURADECOMPRA_FSubTOT,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fsubton as numeric( 15, 2 ) ) as FACTURADECOMPRA_fSubToN,
	cast( c_facturadecompra.signomov*-1*c_facturadecompra.totalcant as numeric( 15, 2 ) ) as FACTURADECOMPRA_TotalCant,
	C_FACTURADECOMPRA.TCRG1361 as FACTURADECOMPRA_tcrg1361,
	C_FACTURADECOMPRA.FLETRA as FACTURADECOMPRA_FLETRA,
	C_FACTURADECOMPRA.FPTOVENEXT as FACTURADECOMPRA_FPTOVENEXT,
	C_FACTURADECOMPRA.FNUMCOMP as FACTURADECOMPRA_FNUMCOMP,
	C_FACTURADECOMPRA.FPTOVEN as FACTURADECOMPRA_FPTOVEN,
	C_FACTURADECOMPRA.FPERSON as FACTURADECOMPRA_FPerson,
	C_PROVEEDOR98.CIMAGEN as PROVEEDOR98_CIMAGEN,
	C_FACTURADECOMPRA.NUMINT as FACTURADECOMPRA_NumInt,
	C_FACTURADECOMPRA.CONDPAGO as FACTURADECOMPRA_CONDPAGO,
	C_FACTURADECOMPRA.MONEDA as FACTURADECOMPRA_Moneda,
	C_FACTURADECOMPRA.CODLISTA as FACTURADECOMPRA_CodLista,
	C_FACTURADECOMPRA.NROREMITO as FACTURADECOMPRA_NROREMITO,
	case when c_facturadecompra.ffch = '01/01/1900 00:00:00' then null else c_facturadecompra.ffch end as FACTURADECOMPRA_FFCH,
	case when c_facturadecompra.ffchfac = '01/01/1900 00:00:00' then null else c_facturadecompra.ffchfac end as FACTURADECOMPRA_FFCHFAC,
	C_FACTURADECOMPRA.COTIZ as FACTURADECOMPRA_Cotiz,
	case when c_facturadecompra.ffchvenc = '01/01/1900 00:00:00' then null else c_facturadecompra.ffchvenc end as FACTURADECOMPRA_FFCHVENC,
	C_FACTURADECOMPRA.NCAI as FACTURADECOMPRA_NCAI,
	case when c_facturadecompra.fvtocai = '01/01/1900 00:00:00' then null else c_facturadecompra.fvtocai end as FACTURADECOMPRA_FVTOCAI,
	C_FACTURADECOMPRA.CCOSTO as FACTURADECOMPRA_CCosto,
	C_FACTURADECOMPRA.DISCCOS as FACTURADECOMPRA_DisCCos,
	C_FACTURADECOMPRA.FPODES as FACTURADECOMPRA_FPODES,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.fdescu as numeric( 15, 2 ) ) as FACTURADECOMPRA_fDescu,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fvuelto as numeric( 15, 2 ) ) as FACTURADECOMPRA_FVuelto,
	C_FACTURADECOMPRA.FMTDES3 as FACTURADECOMPRA_FMTDES3,
	C_FACTURADECOMPRA.RECPOR as FACTURADECOMPRA_RecPor,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.mr as numeric( 15, 2 ) ) as FACTURADECOMPRA_MR,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.recmonto2 as numeric( 15, 2 ) ) as FACTURADECOMPRA_RecMonto2,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fimpuesto as numeric( 15, 2 ) ) as FACTURADECOMPRA_fImpuesto,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.totdescsi as numeric( 15, 2 ) ) as FACTURADECOMPRA_totdescSI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.totrecarsi as numeric( 15, 2 ) ) as FACTURADECOMPRA_totrecarSI,
	C_FACTURADECOMPRA.FOBS as FACTURADECOMPRA_FObs,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.ftotal as numeric( 15, 2 ) ) as FACTURADECOMPRA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_ARTICULO.ARTCONIVA as ARTICULO_ARTCONIVA,
	C_ARTICULO.ARTPORIVA as ARTICULO_ARTPORIVA,
	C_ARTICULO.AOBS as ARTICULO_AObs,
	C_ARTICULO.ATEMPORADA as ARTICULO_ATEMPORADA,
	C_ARTICULO.UNIMED as ARTICULO_UniMed,
	C_ARTICULO.FAMILIA as ARTICULO_Familia,
	C_ARTICULO.MAT as ARTICULO_Mat,
	C_ARTICULO.LINEA as ARTICULO_Linea,
	C_ARTICULO.GRUPO as ARTICULO_Grupo,
	C_ARTICULO.CATEARTI as ARTICULO_CateArti,
	C_ARTICULO.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	C_ARTICULO.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ARTIVA as ARTICULO_ARTIVA,
	C_ARTICULO.ANX2 as ARTICULO_ANX2,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	C_ARTICULO.PALCOL as ARTICULO_PalCol,
	C_ARTICULO.CURTALL as ARTICULO_Curtall,
	case when c_articulo.nocom = '01/01/1900 00:00:00' then null else c_articulo.nocom end as ARTICULO_NOCOM,
	C_ARTICULO.ARTNARBA as ARTICULO_ARTNARBA,
	C_ARTICULO.ARTNODEVO as ARTICULO_ARTNODEVO,
	C_ARTICULO.ESIMPDES as ARTICULO_EsImpDes,
	C_ARTICULO.IMPINTERNO as ARTICULO_impinterno,
	C_ARTICULO.ARTSINDES as ARTICULO_ArtSinDes,
	C_ARTICULO.ARTPESO as ARTICULO_ARTPESO,
	C_ARTICULO.ARTLARGO as ARTICULO_ARTLARGO,
	C_ARTICULO.ARTANCHO as ARTICULO_ARTANCHO,
	C_ARTICULO.ARTALTO as ARTICULO_ARTALTO,
	C_ARTICULO.REQCCOSTO as ARTICULO_ReqCCosto,
	C_ARTICULO.PUBECOM as ARTICULO_PubEcom,
	C_ARTICULO.IMPORTADO as ARTICULO_Importado,
	C_ARTICULO.ARTDESADIC as ARTICULO_ARTDESADIC,
	C_ARTICULO.PROMOYKIT as ARTICULO_PromoYKit,
	C_ARTICULO.DESECOHTML as ARTICULO_DesEcoHTML,
	C_ARTICULO.DESECO as ARTICULO_DesEco,
	case when c_articulo.artrest = '01/01/1900 00:00:00' then null else c_articulo.artrest end as ARTICULO_ArtRest,
	C_ARTICULO.MARCA as ARTICULO_Marca,
	C_ARTICULO.ARTPERCEP as ARTICULO_ArtPercep,
	C_PROVEEDOR98.CLLOC as PROVEEDOR98_CLLOC,
	C_PROVEEDOR98.CLCP as PROVEEDOR98_CLCP,
	C_PROVEEDOR98.CLPRV as PROVEEDOR98_CLPRV,
	C_PROVEEDOR98.CLTLF as PROVEEDOR98_CLTLF,
	C_PROVEEDOR98.CLFAX as PROVEEDOR98_CLFAX,
	C_PROVEEDOR98.CLEMAIL as PROVEEDOR98_CLEMAIL,
	C_PROVEEDOR98.CLPAGEWEB as PROVEEDOR98_CLPAGEWEB,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_PROVEEDOR98.CLCUIT as PROVEEDOR98_CLCUIT,
	C_PROVEEDOR98.CLOBS as PROVEEDOR98_CLOBS,
	C_PROVEEDOR98.CLTIPODOC as PROVEEDOR98_CLTIPODOC,
	C_PROVEEDOR98.CLNRODOC as PROVEEDOR98_CLNRODOC,
	C_PROVEEDOR98.PNUMERO as PROVEEDOR98_PNUMERO,
	C_PROVEEDOR98.PCALLE as PROVEEDOR98_PCALLE,
	C_PROVEEDOR98.PPISO as PROVEEDOR98_PPISO,
	C_PROVEEDOR98.PDEPTO as PROVEEDOR98_PDEPTO,
	C_PROVEEDOR98.PPAIS as PROVEEDOR98_PPAIS,
	C_PROVEEDOR98.TLFM as PROVEEDOR98_TLFM,
	C_PROVEEDOR98.CLAS as PROVEEDOR98_CLAS,
	case when c_proveedor98.clfecha = '01/01/1900 00:00:00' then null else c_proveedor98.clfecha end as PROVEEDOR98_CLFECHA,
	C_PROVEEDOR98.CLCONDPAG as PROVEEDOR98_CLCONDPAG,
	C_PROVEEDOR98.CLTIPCONV as PROVEEDOR98_CLTIPCONV,
	C_PROVEEDOR98.CLNROIIBB as PROVEEDOR98_CLNROIIBB,
	C_PROVEEDOR98.CLLISTPRE as PROVEEDOR98_CLLISTPRE,
	C_PROVEEDOR98.CLSITGAN as PROVEEDOR98_CLSITGAN,
	C_PROVEEDOR98.CLRETGAN as PROVEEDOR98_CLRETGAN,
	C_PROVEEDOR98.CLRETSUSS as PROVEEDOR98_CLRETSUSS,
	C_PROVEEDOR98.CLRETIVA as PROVEEDOR98_CLRETIVA,
	C_PROVEEDOR98.CLOBJIVA as PROVEEDOR98_CLOBJIVA,
	C_PROVEEDOR98.CLEMPLEAD as PROVEEDOR98_CLEMPLEAD,
	C_PROVEEDOR98.EXRETGAN as PROVEEDOR98_EXRETGAN,
	C_PROVEEDOR98.EXRETIVA as PROVEEDOR98_EXRETIVA,
	C_PROVEEDOR98.EXRETSUSS as PROVEEDOR98_EXRETSUSS,
	C_PROVEEDOR98.CLSUJVINC as PROVEEDOR98_CLSujVinc,
	case when c_proveedor98.pvhastaiva = '01/01/1900 00:00:00' then null else c_proveedor98.pvhastaiva end as PROVEEDOR98_PVHastaIva,
	case when c_proveedor98.pvhastagan = '01/01/1900 00:00:00' then null else c_proveedor98.pvhastagan end as PROVEEDOR98_PVHastaGan,
	C_PROVEEDOR98.CLSIPRIB as PROVEEDOR98_CLSIPRIB,
	C_PROVEEDOR98.PORCENTC as PROVEEDOR98_PorcenTC,
	C_PROVEEDOR98.APLICATC as PROVEEDOR98_AplicaTC,
	C_PROVEEDOR98.RUT as PROVEEDOR98_RUT,
	C_PROVEEDOR98.INACTIVOFW as PROVEEDOR98_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMARTICULOSCOMPRA.NROITEM as ITEMARTICULOSCOMPRA_NroItem,
	C_FACTURADECOMPRA.BDALTAFW as FACTURADECOMPRA_BDALTAFW,
	C_FACTURADECOMPRA.BDMODIFW as FACTURADECOMPRA_BDMODIFW,
	C_FACTURADECOMPRA.ESTTRANS as FACTURADECOMPRA_ESTTRANS,
	case when c_facturadecompra.faltafw = '01/01/1900 00:00:00' then null else c_facturadecompra.faltafw end as FACTURADECOMPRA_FALTAFW,
	case when c_facturadecompra.fecexpo = '01/01/1900 00:00:00' then null else c_facturadecompra.fecexpo end as FACTURADECOMPRA_FECEXPO,
	case when c_facturadecompra.fecimpo = '01/01/1900 00:00:00' then null else c_facturadecompra.fecimpo end as FACTURADECOMPRA_FECIMPO,
	case when c_facturadecompra.fmodifw = '01/01/1900 00:00:00' then null else c_facturadecompra.fmodifw end as FACTURADECOMPRA_FMODIFW,
	case when c_facturadecompra.fectrans = '01/01/1900 00:00:00' then null else c_facturadecompra.fectrans end as FACTURADECOMPRA_FECTRANS,
	C_FACTURADECOMPRA.HALTAFW as FACTURADECOMPRA_HALTAFW,
	C_FACTURADECOMPRA.HORAEXPO as FACTURADECOMPRA_HORAEXPO,
	C_FACTURADECOMPRA.HORAIMPO as FACTURADECOMPRA_HORAIMPO,
	C_FACTURADECOMPRA.HMODIFW as FACTURADECOMPRA_HMODIFW,
	C_FACTURADECOMPRA.SALTAFW as FACTURADECOMPRA_SALTAFW,
	C_FACTURADECOMPRA.SMODIFW as FACTURADECOMPRA_SMODIFW,
	C_FACTURADECOMPRA.UALTAFW as FACTURADECOMPRA_UALTAFW,
	C_FACTURADECOMPRA.UMODIFW as FACTURADECOMPRA_UMODIFW,
	C_FACTURADECOMPRA.VALTAFW as FACTURADECOMPRA_VALTAFW,
	C_FACTURADECOMPRA.VMODIFW as FACTURADECOMPRA_VMODIFW,
	C_FACTURADECOMPRA.ZADSFW as FACTURADECOMPRA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMARTICULOSCOMPRA__SUCURSAL,
	C_FACTURADECOMPRA.FACTTIPO as FACTURADECOMPRA_FACTTIPO,
	------------------------------------------------------
	cast( @parametro1 as varchar( 250 ) ) as FACTURADECOMPRA_BDIvaSimpleVirtual,
	cast( '' as varchar( 1 ) ) as FACTURADECOMPRA_TipoOperVirtual,

	case 
		when C_ARTICULO.ANX2 = 2.5 then '9'	
		when C_ARTICULO.ANX2 = 5.0 then '8'
		when C_ARTICULO.ANX2 = 10.5 then '4'
		when C_ARTICULO.ANX2 = 21.0 OR (C_ARTICULO.ANX2 = 0.00 and C_ARTICULO.ARTIVA in (0, 1)) then '5' -- 21%   
		when C_ARTICULO.ANX2 = 27.0 then '6'								
		when C_ARTICULO.ANX2 = 0.00 and ( C_ARTICULO.ARTIVA IN (2,5,4 ) ) then '3' -- NO GRAVADO
	END as FACTURADECOMPRA_AlicuotaVirtual,					

	cast( (c_ITEMARTICULOSCOMPRA.Fneto - c_ITEMARTICULOSCOMPRA.mntpdessi ) as numeric( 15, 2 ) )  as FACTURADECOMPRA_NetoGravadoVirtual,

	cast( '' as varchar( 20 ) ) as FACTURADECOMPRA_CriterioVirtual,
	case 
		when C_FACTURADECOMPRA.FACTTIPO in (8,9 ) then 'CRÉDITO' -- factura y nota de débito
		When C_FACTURADECOMPRA.FACTTIPO in (10 ) then 'RESTITUCIÓN' -- nota de crédito
	end as FACTURADECOMPRA_TipoCreditoVirtual,

	cast( '' as varchar( 85 ) ) as FACTURADECOMPRA_DescTipoOperVirtual,

	case 
		when C_FACTURADECOMPRA.FACTTIPO in (8,9 ) then cast( c_facturadecompra.cotiz*c_itemarticuloscompra.mntpiva as numeric( 15, 2 ) )
		When C_FACTURADECOMPRA.FACTTIPO in (10 ) then cast( 0 as numeric( 15, 2 ) )  -- si es restitución no se informa
    end as FACTURADECOMPRA_CreditoComputableVirtual,

	cast( '' as varchar( 6 ) ) as FACTURADECOMPRA_ActividadVirtual,
	cast( funciones.identificadordecomprobantecomprasparalistado(c_facturadecompra.facttipo, c_facturadecompra.fletra, c_facturadecompra.fptoven, c_facturadecompra.fptovenext, c_facturadecompra.fnumcomp) as varchar( 21 ) ) as FACTURADECOMPRA_ComprobanteVirtual,
	--------------------------------------------------------
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_CENTRODECOSTO64.COSDES as CENTRODECOSTO64_COSDES,
	C_PROVEEDOR98.CLNOM as PROVEEDOR98_CLNOM,
	C_CONDICIONDEPAGO143.CLNOM as CONDICIONDEPAGO143_CLNOM,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_LISTADEPRECIOS145.LPR_NOMBRE as LISTADEPRECIOS145_LPR_NOMBRE,
	C_CENTRODECOSTO153.COSDES as CENTRODECOSTO153_COSDES,
	C_DISTRIBUCIONCENTRODECOSTO.DESCRIP as DISTRIBUCIONCENTRODECOSTO_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVEEDOR3.CLNOM as PROVEEDOR3_CLNOM,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_PALETADECOLORES.DESCRIP as PALETADECOLORES_Descrip,
	C_CURVADETALLES.DESCRIP as CURVADETALLES_Descrip,
	C_NOMENCLADORARBA.NMCDES as NOMENCLADORARBA_NMCDES,
	C_MARCA.DESCRIP as MARCA_Descrip,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_PROVEEDOR98.CLIVA as PROVEEDOR98_CLIVA,
	C_PAISES.PDES as PAISES_pdes,
	C_CLASIFICACIONPROVEEDOR.CLADES as CLASIFICACIONPROVEEDOR_CLADES,
	C_CONDICIONDEPAGO121.CLNOM as CONDICIONDEPAGO121_CLNOM,
	C_LISTADEPRECIOS124.LPR_NOMBRE as LISTADEPRECIOS124_LPR_NOMBRE,
	C_IMPUESTO126.DESCRIP as IMPUESTO126_descrip,
	C_IMPUESTO127.DESCRIP as IMPUESTO127_descrip,
	C_IMPUESTO128.DESCRIP as IMPUESTO128_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CENTRODECOSTO64.COSCOD as CENTRODECOSTO64_COSCOD,
	C_CENTRODECOSTO153.COSCOD as CENTRODECOSTO153_COSCOD,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_CLASIFICACIONPROVEEDOR.CLACOD as CLASIFICACIONPROVEEDOR_CLACOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_CONDICIONDEPAGO121.CLCOD as CONDICIONDEPAGO121_CLCOD,
	C_CONDICIONDEPAGO143.CLCOD as CONDICIONDEPAGO143_CLCOD,
	C_CURVADETALLES.CODIGO as CURVADETALLES_Codigo,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DISTRIBUCIONCENTRODECOSTO.CODIGO as DISTRIBUCIONCENTRODECOSTO_Codigo,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_IMPUESTO126.CODIGO as IMPUESTO126_codigo,
	C_IMPUESTO127.CODIGO as IMPUESTO127_codigo,
	C_IMPUESTO128.CODIGO as IMPUESTO128_codigo,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS124.LPR_NUMERO as LISTADEPRECIOS124_LPR_NUMERO,
	C_LISTADEPRECIOS145.LPR_NUMERO as LISTADEPRECIOS145_LPR_NUMERO,
	C_MARCA.CODIGO as MARCA_Codigo,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_NOMENCLADORARBA.NMCCOD as NOMENCLADORARBA_NMCCOD,
	C_PAISES.PCOD as PAISES_pcod,
	C_PALETADECOLORES.CODIGO as PALETADECOLORES_Codigo,
	C_PROVEEDOR3.CLCOD as PROVEEDOR3_CLCOD,
	C_PROVEEDOR98.CLCOD as PROVEEDOR98_CLCOD,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from (Select fart,ftxt,fcant,codigo,fcolo,fcotxt,fcfi,fcfitot,fkit,famate,fmonto,fmtocfi,fmtodto1,fmtoiva,fneto,nroitem,fx2,fporcfi,fpordto1,fporiva,prunconimp,fprecio,prunsinimp,fprun,ftall,fn11,funid,ciditem,iditemorig,afenroitem,afetipocom,afeletra,afeptoven,afenumcom,afecant,afesaldo,acondivac,aporcivac,procstock,afets,equiv,mntdes,mntprecci,mntptot,mntpper,mntpdesci,mntprecsi,mntpdessi,mntpiva,seniacance,mnpdsi,mndesci,mndessi,afe_cod,usarplista,fbruto,ajucimp,ajusimp,dccosto,ccosto,iditem,comp,artpercep from ZooLogic.FACCOMPRADET union all Select fart,ftxt,fcant,codigo,fcolo,fcotxt,fcfi,fcfitot,fkit,famate,fmonto,fmtocfi,fmtodto1,fmtoiva,fneto,nroitem,fx2,fporcfi,fpordto1,fporiva,prunconimp,fprecio,prunsinimp,fprun,ftall,fn11,funid,ciditem,iditemorig,afenroitem,afetipocom,afeletra,afeptoven,afenumcom,afecant,afesaldo,acondivac,aporcivac,procstock,afets,equiv,mntdes,mntprecci,mntptot,mntpper,mntpdesci,mntprecsi,mntpdessi,mntpiva,seniacance,mnpdsi,mndesci,mndessi,afe_cod,usarplista,fbruto,ajucimp,ajusimp,dccosto,ccosto,iditem,comp,artpercep from ZooLogic.NCCOMPRADET union all Select fart,ftxt,fcant,codigo,fcolo,fcotxt,fcfi,fcfitot,fkit,famate,fmonto,fmtocfi,fmtodto1,fmtoiva,fneto,nroitem,fx2,fporcfi,fpordto1,fporiva,prunconimp,fprecio,prunsinimp,fprun,ftall,fn11,funid,ciditem,iditemorig,afenroitem,afetipocom,afeletra,afeptoven,afenumcom,afecant,afesaldo,acondivac,aporcivac,procstock,afets,equiv,mntdes,mntprecci,mntptot,mntpper,mntpdesci,mntprecsi,mntpdessi,mntpiva,seniacance,mnpdsi,mndesci,mndessi,afe_cod,usarplista,fbruto,ajucimp,ajusimp,dccosto,ccosto,iditem,comp,artpercep from ZooLogic.NDCOMPRADET)  as c_ITEMARTICULOSCOMPRA
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSCOMPRA.FART and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.FART )
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = C_ARTICULO.CATEARTI and 0 = Funciones.empty( C_ARTICULO.CATEARTI )
 left join ZooLogic.CCOSTO as C_CENTRODECOSTO64 on C_CENTRODECOSTO64.COSCOD = C_ITEMARTICULOSCOMPRA.CCOSTO and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.CCOSTO )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = C_ARTICULO.CLASIFART and 0 = Funciones.empty( C_ARTICULO.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSCOMPRA.FCOLO and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.FCOLO )
 left join ZooLogic.CTALLE as C_CURVADETALLES on C_CURVADETALLES.CODIGO = C_ARTICULO.CURTALL and 0 = Funciones.empty( C_ARTICULO.CURTALL )
 left join (Select fperson,numint,fcompfis,ffch,fd2,fhora,fimpuesto,fletra,codlista,moneda,fdescu,fnumcomp,fobs,fpodes,fptoven,simbmon,sitfiscpro,fsubtot,fsubton,facttipo,ftotal,fturno,fvuelto,signomov,anulado,condivalp,fcuit,idvuelto,desauto,subtotcisi,subtotsisi,fmtdes1,fpodes1,fmtdes2,fpodes2,fmtdes3,recpor,recmnto,recmnto1,recmnto2,recmntosi,recmntosi1,recmntosi2,desmntosi,desmntosi1,desmntosi2,desmntosi3,totimpue,totrecar,totdesc,totrecarsi,totdescsi,idcaja,codigo,ffchfac,ffchvenc,nroremito,condpago,fvtocai,ncai,tcrg1361,cotiz,monsis,recmonto1,recmonto2,mr,totalcant,impman,disccos,ccosto,fptovenext,entregapos,bdaltafw,bdmodifw,esttrans,faltafw,fecexpo,fecimpo,fmodifw,fectrans,haltafw,horaexpo,horaimpo,hmodifw,saltafw,smodifw,ualtafw,umodifw,valtafw,vmodifw,zadsfw from ZooLogic.FACCOMPRA union all Select fperson,numint,fcompfis,ffch,fd2,fhora,fimpuesto,fletra,codlista,moneda,fdescu,fnumcomp,fobs,fpodes,fptoven,simbmon,sitfiscpro,fsubtot,fsubton,facttipo,ftotal,fturno,fvuelto,signomov,anulado,condivalp,fcuit,idvuelto,desauto,subtotcisi,subtotsisi,fmtdes1,fpodes1,fmtdes2,fpodes2,fmtdes3,recpor,recmnto,recmnto1,recmnto2,recmntosi,recmntosi1,recmntosi2,desmntosi,desmntosi1,desmntosi2,desmntosi3,totimpue,totrecar,totdesc,totrecarsi,totdescsi,idcaja,codigo,ffchfac,ffchvenc,nroremito,condpago,fvtocai,ncai,tcrg1361,cotiz,monsis,recmonto1,recmonto2,mr,totalcant,impman,disccos,ccosto,fptovenext,entregapos,bdaltafw,bdmodifw,esttrans,faltafw,fecexpo,fecimpo,fmodifw,fectrans,haltafw,horaexpo,horaimpo,hmodifw,saltafw,smodifw,ualtafw,umodifw,valtafw,vmodifw,zadsfw from ZooLogic.NCCOMPRA union all Select fperson,numint,fcompfis,ffch,fd2,fhora,fimpuesto,fletra,codlista,moneda,fdescu,fnumcomp,fobs,fpodes,fptoven,simbmon,sitfiscpro,fsubtot,fsubton,facttipo,ftotal,fturno,fvuelto,signomov,anulado,condivalp,fcuit,idvuelto,desauto,subtotcisi,subtotsisi,fmtdes1,fpodes1,fmtdes2,fpodes2,fmtdes3,recpor,recmnto,recmnto1,recmnto2,recmntosi,recmntosi1,recmntosi2,desmntosi,desmntosi1,desmntosi2,desmntosi3,totimpue,totrecar,totdesc,totrecarsi,totdescsi,idcaja,codigo,ffchfac,ffchvenc,nroremito,condpago,fvtocai,ncai,tcrg1361,cotiz,monsis,recmonto1,recmonto2,mr,totalcant,impman,disccos,ccosto,fptovenext,entregapos,bdaltafw,bdmodifw,esttrans,faltafw,fecexpo,fecimpo,fmodifw,fectrans,haltafw,horaexpo,horaimpo,hmodifw,saltafw,smodifw,ualtafw,umodifw,valtafw,vmodifw,zadsfw from ZooLogic.NDCOMPRA)  as C_FACTURADECOMPRA on C_FACTURADECOMPRA.CODIGO = C_ITEMARTICULOSCOMPRA.CODIGO and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.CODIGO )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS145 on C_LISTADEPRECIOS145.LPR_NUMERO = C_FACTURADECOMPRA.CODLISTA and 0 = Funciones.empty( C_FACTURADECOMPRA.CODLISTA )
 left join ZooLogic.MARCAS as C_MARCA on C_MARCA.CODIGO = C_ARTICULO.MARCA and 0 = Funciones.empty( C_ARTICULO.MARCA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_FACTURADECOMPRA.MONEDA and 0 = Funciones.empty( C_FACTURADECOMPRA.MONEDA )
 left join ZooLogic.NMCARBA as C_NOMENCLADORARBA on C_NOMENCLADORARBA.NMCCOD = C_ARTICULO.ARTNARBA and 0 = Funciones.empty( C_ARTICULO.ARTNARBA )
 left join ZooLogic.PCOLOR as C_PALETADECOLORES on C_PALETADECOLORES.CODIGO = C_ARTICULO.PALCOL and 0 = Funciones.empty( C_ARTICULO.PALCOL )
 left join ZooLogic.PROV as C_PROVEEDOR3 on C_PROVEEDOR3.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ZooLogic.PROV as C_PROVEEDOR98 on C_PROVEEDOR98.CLCOD = C_FACTURADECOMPRA.FPERSON and 0 = Funciones.empty( C_FACTURADECOMPRA.FPERSON )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_PROVEEDOR98.CLPRV and 0 = Funciones.empty( C_PROVEEDOR98.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_PROVEEDOR98.CLIVA and 0 = Funciones.empty( C_PROVEEDOR98.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSCOMPRA.FTALL and 0 = Funciones.empty( C_ITEMARTICULOSCOMPRA.FTALL )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = C_ARTICULO.UNIMED and 0 = Funciones.empty( C_ARTICULO.UNIMED )
 left join ZooLogic.CCOSTO as C_CENTRODECOSTO153 on C_CENTRODECOSTO153.COSCOD = C_FACTURADECOMPRA.CCOSTO and 0 = Funciones.empty( C_FACTURADECOMPRA.CCOSTO )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR on C_CLASIFICACIONPROVEEDOR.CLACOD = C_PROVEEDOR98.CLAS and 0 = Funciones.empty( C_PROVEEDOR98.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO121 on C_CONDICIONDEPAGO121.CLCOD = C_PROVEEDOR98.CLCONDPAG and 0 = Funciones.empty( C_PROVEEDOR98.CLCONDPAG )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO143 on C_CONDICIONDEPAGO143.CLCOD = C_FACTURADECOMPRA.CONDPAGO and 0 = Funciones.empty( C_FACTURADECOMPRA.CONDPAGO )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_PROVEEDOR98.CLSIPRIB and 0 = Funciones.empty( C_PROVEEDOR98.CLSIPRIB )
 left join ZooLogic.DCCOSTO as C_DISTRIBUCIONCENTRODECOSTO on C_DISTRIBUCIONCENTRODECOSTO.CODIGO = C_FACTURADECOMPRA.DISCCOS and 0 = Funciones.empty( C_FACTURADECOMPRA.DISCCOS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO126 on C_IMPUESTO126.CODIGO = C_PROVEEDOR98.CLRETGAN and 0 = Funciones.empty( C_PROVEEDOR98.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO127 on C_IMPUESTO127.CODIGO = C_PROVEEDOR98.CLRETSUSS and 0 = Funciones.empty( C_PROVEEDOR98.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO128 on C_IMPUESTO128.CODIGO = C_PROVEEDOR98.CLRETIVA and 0 = Funciones.empty( C_PROVEEDOR98.CLRETIVA )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS124 on C_LISTADEPRECIOS124.LPR_NUMERO = C_PROVEEDOR98.CLLISTPRE and 0 = Funciones.empty( C_PROVEEDOR98.CLLISTPRE )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_PROVEEDOR98.PPAIS and 0 = Funciones.empty( C_PROVEEDOR98.PPAIS )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( 1=1 ) and 

	( C_FACTURADECOMPRA.TCRG1361 between 1 and 10 ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTE is null ) OR 
	( ( 1 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 3) ) OR  -- @CompFiscal
	( ( 2 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 1) ) OR  -- @CompManual
	( ( 3 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 2) ) OR  -- @CompElectr
	--( ( 4 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 4) ) OR -- @CompDespacho
	--( ( 5 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 5) ) OR -- @CompLiqA
	--( ( 6 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 6) ) OR -- @CompLiqB
	--( ( 7 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 7) ) OR -- @CompServPubA
	--( ( 8 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 8) ) OR -- @CompServPubB
	--( ( 9 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 9) ) OR -- @CompReciboA 
	--( ( 10 = @FACTURADECOMPRA_TIPOCOMPROBANTE ) AND ( C_FACTURADECOMPRA.TCRG1361 = 10) ) OR -- @CompReciboC 
	( @FACTURADECOMPRA_TIPOCOMPROBANTE = C_FACTURADECOMPRA.TCRG1361 ) ) and

	(C_FACTURADECOMPRA.Anulado = 0 ) and
 	( ( @ITEMARTICULOSCOMPRA_ARTICULO_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.FART >= @ITEMARTICULOSCOMPRA_ARTICULO_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_ARTICULO_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.FART <= @ITEMARTICULOSCOMPRA_ARTICULO_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_ARTICULODETALLE_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.FTXT >= @ITEMARTICULOSCOMPRA_ARTICULODETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_ARTICULODETALLE_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.FTXT <= @ITEMARTICULOSCOMPRA_ARTICULODETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_COLOR_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.FCOLO >= @ITEMARTICULOSCOMPRA_COLOR_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_COLOR_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.FCOLO <= @ITEMARTICULOSCOMPRA_COLOR_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_COLORDETALLE_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.FCOTXT >= @ITEMARTICULOSCOMPRA_COLORDETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_COLORDETALLE_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.FCOTXT <= @ITEMARTICULOSCOMPRA_COLORDETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_TALLE_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.FTALL >= @ITEMARTICULOSCOMPRA_TALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_TALLE_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.FTALL <= @ITEMARTICULOSCOMPRA_TALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_CENTRODECOSTO_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.CCOSTO >= @ITEMARTICULOSCOMPRA_CENTRODECOSTO_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_CENTRODECOSTO_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.CCOSTO <= @ITEMARTICULOSCOMPRA_CENTRODECOSTO_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_PRECIO_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.FPRECIO >= @ITEMARTICULOSCOMPRA_PRECIO_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_PRECIO_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.FPRECIO <= @ITEMARTICULOSCOMPRA_PRECIO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_CODIGO_DESDE is null ) OR ( C_FACTURADECOMPRA.CODIGO >= @FACTURADECOMPRA_1_CODIGO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_CODIGO_HASTA is null ) OR ( C_FACTURADECOMPRA.CODIGO <= @FACTURADECOMPRA_1_CODIGO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_TIPOCOMPROBANTERG1361 is null ) OR ( C_FACTURADECOMPRA.tcrg1361 = @FACTURADECOMPRA_1_TIPOCOMPROBANTERG1361 ) ) and 
	( ( @FACTURADECOMPRA_1_LETRA_DESDE is null ) OR ( C_FACTURADECOMPRA.FLETRA >= @FACTURADECOMPRA_1_LETRA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_LETRA_HASTA is null ) OR ( C_FACTURADECOMPRA.FLETRA <= @FACTURADECOMPRA_1_LETRA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE is null ) OR ( C_FACTURADECOMPRA.FPTOVENEXT >= @FACTURADECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA is null ) OR ( C_FACTURADECOMPRA.FPTOVENEXT <= @FACTURADECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_NUMERO_DESDE is null ) OR ( C_FACTURADECOMPRA.FNUMCOMP >= @FACTURADECOMPRA_1_NUMERO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_NUMERO_HASTA is null ) OR ( C_FACTURADECOMPRA.FNUMCOMP <= @FACTURADECOMPRA_1_NUMERO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_PUNTODEVENTA_DESDE is null ) OR ( C_FACTURADECOMPRA.FPTOVEN >= @FACTURADECOMPRA_1_PUNTODEVENTA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_PUNTODEVENTA_HASTA is null ) OR ( C_FACTURADECOMPRA.FPTOVEN <= @FACTURADECOMPRA_1_PUNTODEVENTA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_PROVEEDOR_DESDE is null ) OR ( C_FACTURADECOMPRA.FPerson >= @FACTURADECOMPRA_1_PROVEEDOR_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_PROVEEDOR_HASTA is null ) OR ( C_FACTURADECOMPRA.FPerson <= @FACTURADECOMPRA_1_PROVEEDOR_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_NUMINT_DESDE is null ) OR ( C_FACTURADECOMPRA.NumInt >= @FACTURADECOMPRA_1_NUMINT_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_NUMINT_HASTA is null ) OR ( C_FACTURADECOMPRA.NumInt <= @FACTURADECOMPRA_1_NUMINT_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE is null ) OR ( C_FACTURADECOMPRA.CONDPAGO >= @FACTURADECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA is null ) OR ( C_FACTURADECOMPRA.CONDPAGO <= @FACTURADECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_FACTURADECOMPRA.Moneda >= @FACTURADECOMPRA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_FACTURADECOMPRA.Moneda <= @FACTURADECOMPRA_1_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_LISTADEPRECIOS_DESDE is null ) OR ( C_FACTURADECOMPRA.CodLista >= @FACTURADECOMPRA_1_LISTADEPRECIOS_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_LISTADEPRECIOS_HASTA is null ) OR ( C_FACTURADECOMPRA.CodLista <= @FACTURADECOMPRA_1_LISTADEPRECIOS_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_REMITO_DESDE is null ) OR ( C_FACTURADECOMPRA.NROREMITO >= @FACTURADECOMPRA_1_REMITO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_REMITO_HASTA is null ) OR ( C_FACTURADECOMPRA.NROREMITO <= @FACTURADECOMPRA_1_REMITO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHA_DESDE is null ) OR ( C_FACTURADECOMPRA.FFCH >= @FACTURADECOMPRA_1_FECHA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHA_HASTA is null ) OR ( C_FACTURADECOMPRA.FFCH <= @FACTURADECOMPRA_1_FECHA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAFACTURA_DESDE is null ) OR ( C_FACTURADECOMPRA.FFCHFAC >= @FACTURADECOMPRA_1_FECHAFACTURA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAFACTURA_HASTA is null ) OR ( C_FACTURADECOMPRA.FFCHFAC <= @FACTURADECOMPRA_1_FECHAFACTURA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_COTIZACION_DESDE is null ) OR ( C_FACTURADECOMPRA.Cotiz >= @FACTURADECOMPRA_1_COTIZACION_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_COTIZACION_HASTA is null ) OR ( C_FACTURADECOMPRA.Cotiz <= @FACTURADECOMPRA_1_COTIZACION_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAVENCIMIENTO_DESDE is null ) OR ( C_FACTURADECOMPRA.FFCHVENC >= @FACTURADECOMPRA_1_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAVENCIMIENTO_HASTA is null ) OR ( C_FACTURADECOMPRA.FFCHVENC <= @FACTURADECOMPRA_1_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_CAI_DESDE is null ) OR ( C_FACTURADECOMPRA.NCAI >= @FACTURADECOMPRA_1_CAI_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_CAI_HASTA is null ) OR ( C_FACTURADECOMPRA.NCAI <= @FACTURADECOMPRA_1_CAI_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAVTOCAI_DESDE is null ) OR ( C_FACTURADECOMPRA.FVTOCAI >= @FACTURADECOMPRA_1_FECHAVTOCAI_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAVTOCAI_HASTA is null ) OR ( C_FACTURADECOMPRA.FVTOCAI <= @FACTURADECOMPRA_1_FECHAVTOCAI_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_CENTRODECOSTO_DESDE is null ) OR ( C_FACTURADECOMPRA.CCosto >= @FACTURADECOMPRA_1_CENTRODECOSTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_CENTRODECOSTO_HASTA is null ) OR ( C_FACTURADECOMPRA.CCosto <= @FACTURADECOMPRA_1_CENTRODECOSTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_DISTRIBUCIONPORCENTRODECOSTO_DESDE is null ) OR ( C_FACTURADECOMPRA.DisCCos >= @FACTURADECOMPRA_1_DISTRIBUCIONPORCENTRODECOSTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_DISTRIBUCIONPORCENTRODECOSTO_HASTA is null ) OR ( C_FACTURADECOMPRA.DisCCos <= @FACTURADECOMPRA_1_DISTRIBUCIONPORCENTRODECOSTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_FACTURADECOMPRA.FPODES >= @FACTURADECOMPRA_1_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_FACTURADECOMPRA.FPODES <= @FACTURADECOMPRA_1_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE is null ) OR ( C_FACTURADECOMPRA.FMTDES3 >= @FACTURADECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA is null ) OR ( C_FACTURADECOMPRA.FMTDES3 <= @FACTURADECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_RECARGOPORCENTAJE_DESDE is null ) OR ( C_FACTURADECOMPRA.RecPor >= @FACTURADECOMPRA_1_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_RECARGOPORCENTAJE_HASTA is null ) OR ( C_FACTURADECOMPRA.RecPor <= @FACTURADECOMPRA_1_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @PROVEEDOR_98_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR98.CLNOM >= @PROVEEDOR_98_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_98_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR98.CLNOM <= @PROVEEDOR_98_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_143_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO143.CLNOM >= @CONDICIONDEPAGO_143_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_143_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO143.CLNOM <= @CONDICIONDEPAGO_143_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_144_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_144_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_144_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_144_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_145_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS145.LPR_NOMBRE >= @LISTADEPRECIOS_145_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_145_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS145.LPR_NOMBRE <= @LISTADEPRECIOS_145_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CENTRODECOSTO_153_CENTRODECOSTO_DESCRIPCION_DESDE is null ) OR ( C_CENTRODECOSTO153.COSDES >= @CENTRODECOSTO_153_CENTRODECOSTO_DESCRIPCION_DESDE ) ) and 
	( ( @CENTRODECOSTO_153_CENTRODECOSTO_DESCRIPCION_HASTA is null ) OR ( C_CENTRODECOSTO153.COSDES <= @CENTRODECOSTO_153_CENTRODECOSTO_DESCRIPCION_HASTA ) ) and 
	( ( @DISTRIBUCIONCENTRODECOSTO_154_DISTRIBUCIONPORCENTRODECOSTO_DESCRIP_DESDE is null ) OR ( C_DISTRIBUCIONCENTRODECOSTO.Descrip >= @DISTRIBUCIONCENTRODECOSTO_154_DISTRIBUCIONPORCENTRODECOSTO_DESCRIP_DESDE ) ) and 
	( ( @DISTRIBUCIONCENTRODECOSTO_154_DISTRIBUCIONPORCENTRODECOSTO_DESCRIP_HASTA is null ) OR ( C_DISTRIBUCIONCENTRODECOSTO.Descrip <= @DISTRIBUCIONCENTRODECOSTO_154_DISTRIBUCIONPORCENTRODECOSTO_DESCRIP_HASTA ) ) and 
	( ( @SEGMENTACION_305_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_305_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_305_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_305_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_304_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_304_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_304_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_304_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_303_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_303_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_303_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_303_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR3.CLNOM >= @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR3.CLNOM <= @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_13_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_13_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_14_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_14_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE is null ) OR ( C_PALETADECOLORES.Descrip >= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA is null ) OR ( C_PALETADECOLORES.Descrip <= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE is null ) OR ( C_CURVADETALLES.Descrip >= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA is null ) OR ( C_CURVADETALLES.Descrip <= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE is null ) OR ( C_NOMENCLADORARBA.NMCDES >= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA is null ) OR ( C_NOMENCLADORARBA.NMCDES <= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_DESDE is null ) OR ( C_MARCA.Descrip >= @MARCA_42_MARCA_DESCRIPCION_DESDE ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_HASTA is null ) OR ( C_MARCA.Descrip <= @MARCA_42_MARCA_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_101_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_101_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_101_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_101_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_117_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_117_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_117_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_117_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_119_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES >= @CLASIFICACIONPROVEEDOR_119_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_119_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES <= @CLASIFICACIONPROVEEDOR_119_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_121_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO121.CLNOM >= @CONDICIONDEPAGO_121_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_121_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO121.CLNOM <= @CONDICIONDEPAGO_121_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_124_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS124.LPR_NOMBRE >= @LISTADEPRECIOS_124_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_124_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS124.LPR_NOMBRE <= @LISTADEPRECIOS_124_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_126_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO126.descrip >= @IMPUESTO_126_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_126_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO126.descrip <= @IMPUESTO_126_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_127_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO127.descrip >= @IMPUESTO_127_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_127_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO127.descrip <= @IMPUESTO_127_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_128_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO128.descrip >= @IMPUESTO_128_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_128_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO128.descrip <= @IMPUESTO_128_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_137_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_137_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_137_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_137_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_300_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_300_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_300_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_300_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_300_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_300_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_300_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_300_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_300_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_300_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_300_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_300_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_300_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_300_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_300_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_300_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_2_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_2_PROVEEDOR_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVAVENTAS is null ) OR ( C_ARTICULO.ARTCONIVA = @ARTICULO_2_CONDICIONIVAVENTAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE is null ) OR ( C_ARTICULO.ARTPORIVA >= @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA is null ) OR ( C_ARTICULO.ARTPORIVA <= @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA ) ) and 
	( ( @ARTICULO_2_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_2_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_2_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_2_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_2_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_2_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_2_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_2_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_2_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_2_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_2_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_2_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_2_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_2_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_2_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_2_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_2_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_2_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_2_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_2_LINEA_DESDE ) ) and 
	( ( @ARTICULO_2_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_2_LINEA_HASTA ) ) and 
	( ( @ARTICULO_2_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_2_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_2_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_2_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_2_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_2_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_2_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_2_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_2_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_2_ANO_DESDE ) ) and 
	( ( @ARTICULO_2_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_2_ANO_HASTA ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_2_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_2_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVACOMPRAS is null ) OR ( C_ARTICULO.ARTIVA = @ARTICULO_2_CONDICIONIVACOMPRAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE is null ) OR ( C_ARTICULO.ANX2 >= @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA is null ) OR ( C_ARTICULO.ANX2 <= @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA ) ) and 
	( ( @ARTICULO_2_COMPORTAMIENTO is null ) OR ( C_ARTICULO.ASTOCK = @ARTICULO_2_COMPORTAMIENTO ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_DESDE is null ) OR ( C_ARTICULO.PalCol >= @ARTICULO_2_PALETADECOLORES_DESDE ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_HASTA is null ) OR ( C_ARTICULO.PalCol <= @ARTICULO_2_PALETADECOLORES_HASTA ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_DESDE is null ) OR ( C_ARTICULO.Curtall >= @ARTICULO_2_CURVADETALLES_DESDE ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_HASTA is null ) OR ( C_ARTICULO.Curtall <= @ARTICULO_2_CURVADETALLES_HASTA ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_DESDE is null ) OR ( C_ARTICULO.NOCOM >= @ARTICULO_2_NOCOMERCIALIZABLE_DESDE ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_HASTA is null ) OR ( C_ARTICULO.NOCOM <= @ARTICULO_2_NOCOMERCIALIZABLE_HASTA ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_DESDE is null ) OR ( C_ARTICULO.ARTNARBA >= @ARTICULO_2_NOMENCLADOR_DESDE ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_HASTA is null ) OR ( C_ARTICULO.ARTNARBA <= @ARTICULO_2_NOMENCLADOR_HASTA ) ) and 
	( ( @ARTICULO_2_NOPERMITEDEVOLUCIONES is null ) OR ( C_ARTICULO.ARTNODEVO = @ARTICULO_2_NOPERMITEDEVOLUCIONES ) ) and 
	( ( @ARTICULO_2_IMPRIMEDESPACHO is null ) OR ( C_ARTICULO.EsImpDes = @ARTICULO_2_IMPRIMEDESPACHO ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE is null ) OR ( C_ARTICULO.impinterno >= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA is null ) OR ( C_ARTICULO.impinterno <= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA ) ) and 
	( ( @ARTICULO_2_RESTRINGIRDESCUENTOS is null ) OR ( C_ARTICULO.ArtSinDes = @ARTICULO_2_RESTRINGIRDESCUENTOS ) ) and 
	( ( @ARTICULO_2_PESO_DESDE is null ) OR ( C_ARTICULO.ARTPESO >= @ARTICULO_2_PESO_DESDE ) ) and 
	( ( @ARTICULO_2_PESO_HASTA is null ) OR ( C_ARTICULO.ARTPESO <= @ARTICULO_2_PESO_HASTA ) ) and 
	( ( @ARTICULO_2_LARGO_DESDE is null ) OR ( C_ARTICULO.ARTLARGO >= @ARTICULO_2_LARGO_DESDE ) ) and 
	( ( @ARTICULO_2_LARGO_HASTA is null ) OR ( C_ARTICULO.ARTLARGO <= @ARTICULO_2_LARGO_HASTA ) ) and 
	( ( @ARTICULO_2_ANCHO_DESDE is null ) OR ( C_ARTICULO.ARTANCHO >= @ARTICULO_2_ANCHO_DESDE ) ) and 
	( ( @ARTICULO_2_ANCHO_HASTA is null ) OR ( C_ARTICULO.ARTANCHO <= @ARTICULO_2_ANCHO_HASTA ) ) and 
	( ( @ARTICULO_2_ALTO_DESDE is null ) OR ( C_ARTICULO.ARTALTO >= @ARTICULO_2_ALTO_DESDE ) ) and 
	( ( @ARTICULO_2_ALTO_HASTA is null ) OR ( C_ARTICULO.ARTALTO <= @ARTICULO_2_ALTO_HASTA ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_DESDE is null ) OR ( C_ARTICULO.ReqCCosto >= @ARTICULO_2_REQUIERECCOSTO_DESDE ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_HASTA is null ) OR ( C_ARTICULO.ReqCCosto <= @ARTICULO_2_REQUIERECCOSTO_HASTA ) ) and 
	( ( @ARTICULO_2_NOPUBLICARENECOMMERCE is null ) OR ( C_ARTICULO.PubEcom = @ARTICULO_2_NOPUBLICARENECOMMERCE ) ) and 
	( ( @ARTICULO_2_IMPORTADO is null ) OR ( C_ARTICULO.Importado = @ARTICULO_2_IMPORTADO ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE is null ) OR ( C_ARTICULO.ARTDESADIC >= @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA is null ) OR ( C_ARTICULO.ARTDESADIC <= @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA ) ) and 
	( ( @ARTICULO_2_SOLOPROMOYKIT is null ) OR ( C_ARTICULO.PromoYKit = @ARTICULO_2_SOLOPROMOYKIT ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_DESDE is null ) OR ( C_ARTICULO.ArtRest >= @ARTICULO_2_RESTRINGIRARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_HASTA is null ) OR ( C_ARTICULO.ArtRest <= @ARTICULO_2_RESTRINGIRARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_MARCA_DESDE is null ) OR ( C_ARTICULO.Marca >= @ARTICULO_2_MARCA_DESDE ) ) and 
	( ( @ARTICULO_2_MARCA_HASTA is null ) OR ( C_ARTICULO.Marca <= @ARTICULO_2_MARCA_HASTA ) ) and 
	( ( @ARTICULO_2_PERCEPCIONIVARG5329 is null ) OR ( C_ARTICULO.ArtPercep = @ARTICULO_2_PERCEPCIONIVARG5329 ) ) and 
	( ( @PROVEEDOR_98_LOCALIDAD_DESDE is null ) OR ( C_PROVEEDOR98.CLLOC >= @PROVEEDOR_98_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_98_LOCALIDAD_HASTA is null ) OR ( C_PROVEEDOR98.CLLOC <= @PROVEEDOR_98_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_98_CODIGOPOSTAL_DESDE is null ) OR ( C_PROVEEDOR98.CLCP >= @PROVEEDOR_98_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_98_CODIGOPOSTAL_HASTA is null ) OR ( C_PROVEEDOR98.CLCP <= @PROVEEDOR_98_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_98_PROVINCIA_DESDE is null ) OR ( C_PROVEEDOR98.CLPRV >= @PROVEEDOR_98_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_98_PROVINCIA_HASTA is null ) OR ( C_PROVEEDOR98.CLPRV <= @PROVEEDOR_98_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_98_TELEFONO_DESDE is null ) OR ( C_PROVEEDOR98.CLTLF >= @PROVEEDOR_98_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_98_TELEFONO_HASTA is null ) OR ( C_PROVEEDOR98.CLTLF <= @PROVEEDOR_98_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_98_FAX_DESDE is null ) OR ( C_PROVEEDOR98.CLFAX >= @PROVEEDOR_98_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_98_FAX_HASTA is null ) OR ( C_PROVEEDOR98.CLFAX <= @PROVEEDOR_98_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_98_EMAIL_DESDE is null ) OR ( C_PROVEEDOR98.CLEMAIL >= @PROVEEDOR_98_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_98_EMAIL_HASTA is null ) OR ( C_PROVEEDOR98.CLEMAIL <= @PROVEEDOR_98_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_98_PAGINAWEB_DESDE is null ) OR ( C_PROVEEDOR98.CLPAGEWEB >= @PROVEEDOR_98_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_98_PAGINAWEB_HASTA is null ) OR ( C_PROVEEDOR98.CLPAGEWEB <= @PROVEEDOR_98_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_106_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_106_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_98_CUIT_DESDE is null ) OR ( C_PROVEEDOR98.CLCUIT >= @PROVEEDOR_98_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_98_CUIT_HASTA is null ) OR ( C_PROVEEDOR98.CLCUIT <= @PROVEEDOR_98_CUIT_HASTA ) ) and 
	( ( @PROVEEDOR_98_TIPODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR98.CLTIPODOC >= @PROVEEDOR_98_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_98_TIPODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR98.CLTIPODOC <= @PROVEEDOR_98_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_98_NRODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR98.CLNRODOC >= @PROVEEDOR_98_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_98_NRODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR98.CLNRODOC <= @PROVEEDOR_98_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_98_IMAGEN_DESDE is null ) OR ( C_PROVEEDOR98.CIMAGEN >= @PROVEEDOR_98_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_98_IMAGEN_HASTA is null ) OR ( C_PROVEEDOR98.CIMAGEN <= @PROVEEDOR_98_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_98_NUMERO_DESDE is null ) OR ( C_PROVEEDOR98.PNUMERO >= @PROVEEDOR_98_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_98_NUMERO_HASTA is null ) OR ( C_PROVEEDOR98.PNUMERO <= @PROVEEDOR_98_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_98_CALLE_DESDE is null ) OR ( C_PROVEEDOR98.PCALLE >= @PROVEEDOR_98_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_98_CALLE_HASTA is null ) OR ( C_PROVEEDOR98.PCALLE <= @PROVEEDOR_98_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_98_PISO_DESDE is null ) OR ( C_PROVEEDOR98.PPISO >= @PROVEEDOR_98_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_98_PISO_HASTA is null ) OR ( C_PROVEEDOR98.PPISO <= @PROVEEDOR_98_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_98_DEPARTAMENTO_DESDE is null ) OR ( C_PROVEEDOR98.PDEPTO >= @PROVEEDOR_98_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_98_DEPARTAMENTO_HASTA is null ) OR ( C_PROVEEDOR98.PDEPTO <= @PROVEEDOR_98_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_98_PAIS_DESDE is null ) OR ( C_PROVEEDOR98.PPAIS >= @PROVEEDOR_98_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_98_PAIS_HASTA is null ) OR ( C_PROVEEDOR98.PPAIS <= @PROVEEDOR_98_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_98_MOVIL_DESDE is null ) OR ( C_PROVEEDOR98.TLFM >= @PROVEEDOR_98_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_98_MOVIL_HASTA is null ) OR ( C_PROVEEDOR98.TLFM <= @PROVEEDOR_98_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_98_CLASIFICACION_DESDE is null ) OR ( C_PROVEEDOR98.CLAS >= @PROVEEDOR_98_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_98_CLASIFICACION_HASTA is null ) OR ( C_PROVEEDOR98.CLAS <= @PROVEEDOR_98_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_98_FECHANACIMIENTO_DESDE is null ) OR ( C_PROVEEDOR98.CLFECHA >= @PROVEEDOR_98_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_98_FECHANACIMIENTO_HASTA is null ) OR ( C_PROVEEDOR98.CLFECHA <= @PROVEEDOR_98_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_98_CONDICIONDEPAGO_DESDE is null ) OR ( C_PROVEEDOR98.CLCONDPAG >= @PROVEEDOR_98_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_98_CONDICIONDEPAGO_HASTA is null ) OR ( C_PROVEEDOR98.CLCONDPAG <= @PROVEEDOR_98_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_98_TIPOCONVENIO_DESDE is null ) OR ( C_PROVEEDOR98.CLTIPCONV >= @PROVEEDOR_98_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_98_TIPOCONVENIO_HASTA is null ) OR ( C_PROVEEDOR98.CLTIPCONV <= @PROVEEDOR_98_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_98_NROIIBB_DESDE is null ) OR ( C_PROVEEDOR98.CLNROIIBB >= @PROVEEDOR_98_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_98_NROIIBB_HASTA is null ) OR ( C_PROVEEDOR98.CLNROIIBB <= @PROVEEDOR_98_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_98_LISTADEPRECIO_DESDE is null ) OR ( C_PROVEEDOR98.CLLISTPRE >= @PROVEEDOR_98_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_98_LISTADEPRECIO_HASTA is null ) OR ( C_PROVEEDOR98.CLLISTPRE <= @PROVEEDOR_98_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_98_SITUACIONGANANCIAS is null ) OR ( C_PROVEEDOR98.CLSITGAN = @PROVEEDOR_98_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_98_RETENCIONGANANCIAS_DESDE is null ) OR ( C_PROVEEDOR98.CLRETGAN >= @PROVEEDOR_98_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_98_RETENCIONGANANCIAS_HASTA is null ) OR ( C_PROVEEDOR98.CLRETGAN <= @PROVEEDOR_98_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_98_RETENCIONSUSS_DESDE is null ) OR ( C_PROVEEDOR98.CLRETSUSS >= @PROVEEDOR_98_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_98_RETENCIONSUSS_HASTA is null ) OR ( C_PROVEEDOR98.CLRETSUSS <= @PROVEEDOR_98_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_98_RETENCIONIVA_DESDE is null ) OR ( C_PROVEEDOR98.CLRETIVA >= @PROVEEDOR_98_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_98_RETENCIONIVA_HASTA is null ) OR ( C_PROVEEDOR98.CLRETIVA <= @PROVEEDOR_98_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_98_OBJETOIVA is null ) OR ( C_PROVEEDOR98.CLOBJIVA = @PROVEEDOR_98_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_98_EMPLEADOR is null ) OR ( C_PROVEEDOR98.CLEMPLEAD = @PROVEEDOR_98_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_98_EXCLUIDORETENCIONGANANCIAS is null ) OR ( C_PROVEEDOR98.EXRETGAN = @PROVEEDOR_98_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_98_EXCLUIDORETENCIONIVA is null ) OR ( C_PROVEEDOR98.EXRETIVA = @PROVEEDOR_98_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_98_EXCLUIDORETENCIONSUSS is null ) OR ( C_PROVEEDOR98.EXRETSUSS = @PROVEEDOR_98_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_98_SUJETOVINCULADO is null ) OR ( C_PROVEEDOR98.CLSujVinc = @PROVEEDOR_98_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_98_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_PROVEEDOR98.PVHastaIva >= @PROVEEDOR_98_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_98_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_PROVEEDOR98.PVHastaIva <= @PROVEEDOR_98_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_98_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_PROVEEDOR98.PVHastaGan >= @PROVEEDOR_98_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_98_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_PROVEEDOR98.PVHastaGan <= @PROVEEDOR_98_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_98_CODIGOSIPRIB_DESDE is null ) OR ( C_PROVEEDOR98.CLSIPRIB >= @PROVEEDOR_98_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_98_CODIGOSIPRIB_HASTA is null ) OR ( C_PROVEEDOR98.CLSIPRIB <= @PROVEEDOR_98_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_98_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR98.PorcenTC >= @PROVEEDOR_98_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_98_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR98.PorcenTC <= @PROVEEDOR_98_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_98_TASACEROAPLICA is null ) OR ( C_PROVEEDOR98.AplicaTC = @PROVEEDOR_98_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_98_RUT_DESDE is null ) OR ( C_PROVEEDOR98.RUT >= @PROVEEDOR_98_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_98_RUT_HASTA is null ) OR ( C_PROVEEDOR98.RUT <= @PROVEEDOR_98_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_98_INACTIVOFW is null ) OR ( C_PROVEEDOR98.InactivoFW = @PROVEEDOR_98_INACTIVOFW ) ) and 
	( ( @SUCURSAL_300_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_300_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_300_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_300_CODIGO_HASTA ) ) and 
	( ( @ITEMARTICULOSCOMPRA_NROITEM_DESDE is null ) OR ( c_ITEMARTICULOSCOMPRA.NroItem >= @ITEMARTICULOSCOMPRA_NROITEM_DESDE ) ) and 
	( ( @ITEMARTICULOSCOMPRA_NROITEM_HASTA is null ) OR ( c_ITEMARTICULOSCOMPRA.NroItem <= @ITEMARTICULOSCOMPRA_NROITEM_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA.BDALTAFW >= @FACTURADECOMPRA_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA.BDALTAFW <= @FACTURADECOMPRA_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA.BDMODIFW >= @FACTURADECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA.BDMODIFW <= @FACTURADECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_FACTURADECOMPRA.ESTTRANS >= @FACTURADECOMPRA_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_FACTURADECOMPRA.ESTTRANS <= @FACTURADECOMPRA_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA.FALTAFW >= @FACTURADECOMPRA_1_FECHAALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA.FALTAFW <= @FACTURADECOMPRA_1_FECHAALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAEXPO_DESDE is null ) OR ( C_FACTURADECOMPRA.FECEXPO >= @FACTURADECOMPRA_1_FECHAEXPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAEXPO_HASTA is null ) OR ( C_FACTURADECOMPRA.FECEXPO <= @FACTURADECOMPRA_1_FECHAEXPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAIMPO_DESDE is null ) OR ( C_FACTURADECOMPRA.FECIMPO >= @FACTURADECOMPRA_1_FECHAIMPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAIMPO_HASTA is null ) OR ( C_FACTURADECOMPRA.FECIMPO <= @FACTURADECOMPRA_1_FECHAIMPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA.FMODIFW >= @FACTURADECOMPRA_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA.FMODIFW <= @FACTURADECOMPRA_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_FACTURADECOMPRA.FECTRANS >= @FACTURADECOMPRA_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_FACTURADECOMPRA.FECTRANS <= @FACTURADECOMPRA_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_HORAALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA.HALTAFW >= @FACTURADECOMPRA_1_HORAALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_HORAALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA.HALTAFW <= @FACTURADECOMPRA_1_HORAALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_HORAEXPO_DESDE is null ) OR ( C_FACTURADECOMPRA.HORAEXPO >= @FACTURADECOMPRA_1_HORAEXPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_HORAEXPO_HASTA is null ) OR ( C_FACTURADECOMPRA.HORAEXPO <= @FACTURADECOMPRA_1_HORAEXPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_HORAIMPO_DESDE is null ) OR ( C_FACTURADECOMPRA.HORAIMPO >= @FACTURADECOMPRA_1_HORAIMPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_HORAIMPO_HASTA is null ) OR ( C_FACTURADECOMPRA.HORAIMPO <= @FACTURADECOMPRA_1_HORAIMPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA.HMODIFW >= @FACTURADECOMPRA_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA.HMODIFW <= @FACTURADECOMPRA_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_SERIEALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA.SALTAFW >= @FACTURADECOMPRA_1_SERIEALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_SERIEALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA.SALTAFW <= @FACTURADECOMPRA_1_SERIEALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA.SMODIFW >= @FACTURADECOMPRA_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA.SMODIFW <= @FACTURADECOMPRA_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_USUARIOALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA.UALTAFW >= @FACTURADECOMPRA_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_USUARIOALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA.UALTAFW <= @FACTURADECOMPRA_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA.UMODIFW >= @FACTURADECOMPRA_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA.UMODIFW <= @FACTURADECOMPRA_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_VERSIONALTAFW_DESDE is null ) OR ( C_FACTURADECOMPRA.VALTAFW >= @FACTURADECOMPRA_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_VERSIONALTAFW_HASTA is null ) OR ( C_FACTURADECOMPRA.VALTAFW <= @FACTURADECOMPRA_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_FACTURADECOMPRA.VMODIFW >= @FACTURADECOMPRA_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_FACTURADECOMPRA.VMODIFW <= @FACTURADECOMPRA_1_VERSIONMODIFICACIONFW_HASTA ) ) --and 
--	( ( @FACTURADECOMPRA_TIPOCOMPROBANTE is null ) OR ( C_FACTURADECOMPRA.FACTTIPO = @FACTURADECOMPRA_TIPOCOMPROBANTE ) )

)