IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_FACTURADECOMPRA_TRAZADECOMPRAS_FACTURADECOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_FACTURADECOMPRA_TRAZADECOMPRAS_FACTURADECOMPRA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_FACTURADECOMPRA_TRAZADECOMPRAS_FACTURADECOMPRA]
( @BaseDeDatos varchar(8),
	@FACTURADECOMPRA_FECHA_DESDE datetime,
	@FACTURADECOMPRA_FECHA_HASTA datetime,
	@FACTURADECOMPRA_TIPOCOMPROBANTERG1361 numeric(2, 0),
	@FACTURADECOMPRA_LETRA_DESDE varchar(2),
	@FACTURADECOMPRA_LETRA_HASTA varchar(2),
	@FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_DESDE numeric(5, 0),
	@FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_HASTA numeric(5, 0),
	@FACTURADECOMPRA_NUMERO_DESDE numeric(8, 0),
	@FACTURADECOMPRA_NUMERO_HASTA numeric(8, 0),
	@FACTURADECOMPRA_PUNTODEVENTA_DESDE numeric(4, 0),
	@FACTURADECOMPRA_PUNTODEVENTA_HASTA numeric(4, 0),
	@FACTURADECOMPRA_PROVEEDOR_DESDE varchar(10),
	@FACTURADECOMPRA_PROVEEDOR_HASTA varchar(10),
	@FACTURADECOMPRA_NUMINT_DESDE numeric(10, 0),
	@FACTURADECOMPRA_NUMINT_HASTA numeric(10, 0),
	@FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_DESDE varchar(5),
	@FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_HASTA varchar(5),
	@FACTURADECOMPRA_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURADECOMPRA_MONEDACOMPROBANTE_HASTA varchar(10),
	@FACTURADECOMPRA_LISTADEPRECIOS_DESDE varchar(6),
	@FACTURADECOMPRA_LISTADEPRECIOS_HASTA varchar(6),
	@FACTURADECOMPRA_REMITO_DESDE varchar(16),
	@FACTURADECOMPRA_REMITO_HASTA varchar(16),
	@FACTURADECOMPRA_FECHAFACTURA_DESDE datetime,
	@FACTURADECOMPRA_FECHAFACTURA_HASTA datetime,
	@FACTURADECOMPRA_COTIZACION_DESDE numeric(15, 5),
	@FACTURADECOMPRA_COTIZACION_HASTA numeric(15, 5),
	@FACTURADECOMPRA_FECHAVENCIMIENTO_DESDE datetime,
	@FACTURADECOMPRA_FECHAVENCIMIENTO_HASTA datetime,
	@FACTURADECOMPRA_CAI_DESDE numeric(14, 0),
	@FACTURADECOMPRA_CAI_HASTA numeric(14, 0),
	@FACTURADECOMPRA_FECHAVTOCAI_DESDE datetime,
	@FACTURADECOMPRA_FECHAVTOCAI_HASTA datetime,
	@FACTURADECOMPRA_CENTRODECOSTO_DESDE varchar(20),
	@FACTURADECOMPRA_CENTRODECOSTO_HASTA varchar(20),
	@FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_DESDE varchar(20),
	@FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_HASTA varchar(20),
	@FACTURADECOMPRA_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@FACTURADECOMPRA_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_DESDE numeric(15, 2),
	@FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_HASTA numeric(15, 2),
	@FACTURADECOMPRA_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@FACTURADECOMPRA_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@PROVEEDOR_29_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_29_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA varchar(100),
	@MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_DESDE varchar(150),
	@CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_HASTA varchar(150),
	@DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_DESDE varchar(150),
	@DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_HASTA varchar(150),
	@SEGMENTACION_284_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_284_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_283_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_283_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_282_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_282_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVINCIA_32_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_32_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_48_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_48_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_59_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_59_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_279_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_279_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_279_LINEA_DESDE varchar(10),
	@SUCURSAL_279_LINEA_HASTA varchar(10),
	@SUCURSAL_279_TIPO_DESDE varchar(10),
	@SUCURSAL_279_TIPO_HASTA varchar(10),
	@SUCURSAL_279_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_279_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_29_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_29_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_29_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_29_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_29_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_29_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_29_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_29_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_29_FAX_DESDE varchar(60),
	@PROVEEDOR_29_FAX_HASTA varchar(60),
	@PROVEEDOR_29_EMAIL_DESDE varchar(250),
	@PROVEEDOR_29_EMAIL_HASTA varchar(250),
	@PROVEEDOR_29_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_29_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_37_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_29_CUIT_DESDE varchar(15),
	@PROVEEDOR_29_CUIT_HASTA varchar(15),
	@PROVEEDOR_29_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_29_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_29_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_29_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_29_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_29_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_29_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_29_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_29_CALLE_DESDE varchar(70),
	@PROVEEDOR_29_CALLE_HASTA varchar(70),
	@PROVEEDOR_29_PISO_DESDE varchar(3),
	@PROVEEDOR_29_PISO_HASTA varchar(3),
	@PROVEEDOR_29_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_29_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_29_PAIS_DESDE varchar(3),
	@PROVEEDOR_29_PAIS_HASTA varchar(3),
	@PROVEEDOR_29_MOVIL_DESDE varchar(30),
	@PROVEEDOR_29_MOVIL_HASTA varchar(30),
	@PROVEEDOR_29_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_29_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_29_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_29_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_29_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_29_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_29_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_29_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_29_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_29_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_29_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_29_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_29_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_29_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_29_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_29_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_29_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_29_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_29_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_29_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_29_EMPLEADOR bit,
	@PROVEEDOR_29_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_29_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_29_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_29_SUJETOVINCULADO bit,
	@PROVEEDOR_29_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_29_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_29_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_29_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_29_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_29_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_29_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_29_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_29_TASACEROAPLICA bit,
	@PROVEEDOR_29_RUT_DESDE varchar(12),
	@PROVEEDOR_29_RUT_HASTA varchar(12),
	@PROVEEDOR_29_INACTIVOFW bit,
	@SUCURSAL_279_CODIGO_DESDE varchar(10),
	@SUCURSAL_279_CODIGO_HASTA varchar(10),
	@FACTURADECOMPRA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@FACTURADECOMPRA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@FACTURADECOMPRA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@FACTURADECOMPRA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@FACTURADECOMPRA_FECHAALTAFW_DESDE datetime,
	@FACTURADECOMPRA_FECHAALTAFW_HASTA datetime,
	@FACTURADECOMPRA_FECHAEXPO_DESDE datetime,
	@FACTURADECOMPRA_FECHAEXPO_HASTA datetime,
	@FACTURADECOMPRA_FECHAIMPO_DESDE datetime,
	@FACTURADECOMPRA_FECHAIMPO_HASTA datetime,
	@FACTURADECOMPRA_FECHAMODIFICACIONFW_DESDE datetime,
	@FACTURADECOMPRA_FECHAMODIFICACIONFW_HASTA datetime,
	@FACTURADECOMPRA_FECHATRANSFERENCIA_DESDE datetime,
	@FACTURADECOMPRA_FECHATRANSFERENCIA_HASTA datetime,
	@FACTURADECOMPRA_HORAALTAFW_DESDE varchar(8),
	@FACTURADECOMPRA_HORAALTAFW_HASTA varchar(8),
	@FACTURADECOMPRA_HORAEXPO_DESDE varchar(8),
	@FACTURADECOMPRA_HORAEXPO_HASTA varchar(8),
	@FACTURADECOMPRA_HORAIMPO_DESDE varchar(8),
	@FACTURADECOMPRA_HORAIMPO_HASTA varchar(8),
	@FACTURADECOMPRA_HORAMODIFICACIONFW_DESDE varchar(8),
	@FACTURADECOMPRA_HORAMODIFICACIONFW_HASTA varchar(8),
	@FACTURADECOMPRA_SERIEALTAFW_DESDE varchar(7),
	@FACTURADECOMPRA_SERIEALTAFW_HASTA varchar(7),
	@FACTURADECOMPRA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@FACTURADECOMPRA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@FACTURADECOMPRA_USUARIOALTAFW_DESDE varchar(100),
	@FACTURADECOMPRA_USUARIOALTAFW_HASTA varchar(100),
	@FACTURADECOMPRA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@FACTURADECOMPRA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@FACTURADECOMPRA_VERSIONALTAFW_DESDE varchar(13),
	@FACTURADECOMPRA_VERSIONALTAFW_HASTA varchar(13),
	@FACTURADECOMPRA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@FACTURADECOMPRA_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max),
	@Parametro2 varchar(max),
	@Parametro3 varchar(max) )
RETURNS TABLE
AS
RETURN
(
-- Los parámetros adicionales son del tipo varchar(max) pero para filtrar los niveles se requiere valores
-- numéricos, cualquier otro valor se reemplaza por null
-- Aqui se utilizan solo para obtener el valor SoloMostrarPedidosYRemitosVirtual 
with Parametros as
(
	select 
		cast( case when isnumeric( @Parametro1 ) = 1 then @Parametro1 else null end as int ) * -1 as TopeSuperior, 
		cast( case when isnumeric( @Parametro2 ) = 1 then @Parametro2 else null end as int ) as TopeInferior,
		cast( case when isnumeric( @Parametro3 ) = 1 then @Parametro2 else null end as bit ) as EstaFiltrandoPedidosYRemitos
)

select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_facturadecompra.codigo, 38, ' ' ) as varchar( 46 ) ) as FACTURADECOMPRA__Grupo,
	@basededatos as FACTURADECOMPRA__BD,
	c_FACTURADECOMPRA.CODIGO as FACTURADECOMPRA_CODIGO,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fsubtot as numeric( 15, 2 ) ) as FACTURADECOMPRA_FSubTOT,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fsubton as numeric( 15, 2 ) ) as FACTURADECOMPRA_fSubToN,
	cast( c_facturadecompra.signomov*-1*c_facturadecompra.totalcant as numeric( 16, 3 ) ) as FACTURADECOMPRA_TotalCant,
	c_FACTURADECOMPRA.TCRG1361 as FACTURADECOMPRA_tcrg1361,
	c_FACTURADECOMPRA.FLETRA as FACTURADECOMPRA_FLETRA,
	c_FACTURADECOMPRA.FPTOVENEXT as FACTURADECOMPRA_FPTOVENEXT,
	c_FACTURADECOMPRA.FNUMCOMP as FACTURADECOMPRA_FNUMCOMP,
	c_FACTURADECOMPRA.FPTOVEN as FACTURADECOMPRA_FPTOVEN,
	c_FACTURADECOMPRA.FPERSON as FACTURADECOMPRA_FPerson,
	C_PROVEEDOR.CIMAGEN as PROVEEDOR_CIMAGEN,
	c_FACTURADECOMPRA.NUMINT as FACTURADECOMPRA_NumInt,
	c_FACTURADECOMPRA.CONDPAGO as FACTURADECOMPRA_CONDPAGO,
	c_FACTURADECOMPRA.MONEDA as FACTURADECOMPRA_Moneda,
	c_FACTURADECOMPRA.CODLISTA as FACTURADECOMPRA_CodLista,
	c_FACTURADECOMPRA.NROREMITO as FACTURADECOMPRA_NROREMITO,
	case when c_facturadecompra.ffchfac = '01/01/1900 00:00:00' then null else c_facturadecompra.ffchfac end as FACTURADECOMPRA_FFCHFAC,
	c_FACTURADECOMPRA.COTIZ as FACTURADECOMPRA_Cotiz,
	case when c_facturadecompra.ffchvenc = '01/01/1900 00:00:00' then null else c_facturadecompra.ffchvenc end as FACTURADECOMPRA_FFCHVENC,
	c_FACTURADECOMPRA.NCAI as FACTURADECOMPRA_NCAI,
	case when c_facturadecompra.fvtocai = '01/01/1900 00:00:00' then null else c_facturadecompra.fvtocai end as FACTURADECOMPRA_FVTOCAI,
	c_FACTURADECOMPRA.CCOSTO as FACTURADECOMPRA_CCosto,
	c_FACTURADECOMPRA.DISCCOS as FACTURADECOMPRA_DisCCos,
	c_FACTURADECOMPRA.FPODES as FACTURADECOMPRA_FPODES,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.fdescu as numeric( 15, 2 ) ) as FACTURADECOMPRA_fDescu,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fvuelto as numeric( 15, 2 ) ) as FACTURADECOMPRA_FVuelto,
	c_FACTURADECOMPRA.FMTDES3 as FACTURADECOMPRA_FMTDES3,
	c_FACTURADECOMPRA.RECPOR as FACTURADECOMPRA_RecPor,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.mr as numeric( 15, 2 ) ) as FACTURADECOMPRA_MR,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.recmonto2 as numeric( 15, 2 ) ) as FACTURADECOMPRA_RecMonto2,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.fimpuesto as numeric( 15, 2 ) ) as FACTURADECOMPRA_fImpuesto,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*c_facturadecompra.totdescsi as numeric( 15, 2 ) ) as FACTURADECOMPRA_totdescSI,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.totrecarsi as numeric( 15, 2 ) ) as FACTURADECOMPRA_totrecarSI,
	c_FACTURADECOMPRA.FOBS as FACTURADECOMPRA_FObs,
	cast( c_facturadecompra.signomov*c_facturadecompra.cotiz*-1*c_facturadecompra.ftotal as numeric( 15, 2 ) ) as FACTURADECOMPRA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_PROVEEDOR.CLLOC as PROVEEDOR_CLLOC,
	C_PROVEEDOR.CLCP as PROVEEDOR_CLCP,
	C_PROVEEDOR.CLPRV as PROVEEDOR_CLPRV,
	C_PROVEEDOR.CLTLF as PROVEEDOR_CLTLF,
	C_PROVEEDOR.CLFAX as PROVEEDOR_CLFAX,
	C_PROVEEDOR.CLEMAIL as PROVEEDOR_CLEMAIL,
	C_PROVEEDOR.CLPAGEWEB as PROVEEDOR_CLPAGEWEB,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_PROVEEDOR.CLCUIT as PROVEEDOR_CLCUIT,
	C_PROVEEDOR.CLOBS as PROVEEDOR_CLOBS,
	C_PROVEEDOR.CLTIPODOC as PROVEEDOR_CLTIPODOC,
	C_PROVEEDOR.CLNRODOC as PROVEEDOR_CLNRODOC,
	C_PROVEEDOR.PNUMERO as PROVEEDOR_PNUMERO,
	C_PROVEEDOR.PCALLE as PROVEEDOR_PCALLE,
	C_PROVEEDOR.PPISO as PROVEEDOR_PPISO,
	C_PROVEEDOR.PDEPTO as PROVEEDOR_PDEPTO,
	C_PROVEEDOR.PPAIS as PROVEEDOR_PPAIS,
	C_PROVEEDOR.TLFM as PROVEEDOR_TLFM,
	C_PROVEEDOR.CLAS as PROVEEDOR_CLAS,
	case when c_proveedor.clfecha = '01/01/1900 00:00:00' then null else c_proveedor.clfecha end as PROVEEDOR_CLFECHA,
	C_PROVEEDOR.CLCONDPAG as PROVEEDOR_CLCONDPAG,
	C_PROVEEDOR.CLTIPCONV as PROVEEDOR_CLTIPCONV,
	C_PROVEEDOR.CLNROIIBB as PROVEEDOR_CLNROIIBB,
	C_PROVEEDOR.CLLISTPRE as PROVEEDOR_CLLISTPRE,
	C_PROVEEDOR.CLSITGAN as PROVEEDOR_CLSITGAN,
	C_PROVEEDOR.CLRETGAN as PROVEEDOR_CLRETGAN,
	C_PROVEEDOR.CLRETSUSS as PROVEEDOR_CLRETSUSS,
	C_PROVEEDOR.CLRETIVA as PROVEEDOR_CLRETIVA,
	C_PROVEEDOR.CLOBJIVA as PROVEEDOR_CLOBJIVA,
	C_PROVEEDOR.CLEMPLEAD as PROVEEDOR_CLEMPLEAD,
	C_PROVEEDOR.EXRETGAN as PROVEEDOR_EXRETGAN,
	C_PROVEEDOR.EXRETIVA as PROVEEDOR_EXRETIVA,
	C_PROVEEDOR.EXRETSUSS as PROVEEDOR_EXRETSUSS,
	C_PROVEEDOR.CLSUJVINC as PROVEEDOR_CLSujVinc,
	case when c_proveedor.pvhastaiva = '01/01/1900 00:00:00' then null else c_proveedor.pvhastaiva end as PROVEEDOR_PVHastaIva,
	case when c_proveedor.pvhastagan = '01/01/1900 00:00:00' then null else c_proveedor.pvhastagan end as PROVEEDOR_PVHastaGan,
	C_PROVEEDOR.CLSIPRIB as PROVEEDOR_CLSIPRIB,
	C_PROVEEDOR.PORCENTC as PROVEEDOR_PorcenTC,
	C_PROVEEDOR.APLICATC as PROVEEDOR_AplicaTC,
	C_PROVEEDOR.RUT as PROVEEDOR_RUT,
	C_PROVEEDOR.INACTIVOFW as PROVEEDOR_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_FACTURADECOMPRA.BDALTAFW as FACTURADECOMPRA_BDALTAFW,
	c_FACTURADECOMPRA.BDMODIFW as FACTURADECOMPRA_BDMODIFW,
	c_FACTURADECOMPRA.ESTTRANS as FACTURADECOMPRA_ESTTRANS,
	case when c_facturadecompra.faltafw = '01/01/1900 00:00:00' then null else c_facturadecompra.faltafw end as FACTURADECOMPRA_FALTAFW,
	case when c_facturadecompra.fecexpo = '01/01/1900 00:00:00' then null else c_facturadecompra.fecexpo end as FACTURADECOMPRA_FECEXPO,
	case when c_facturadecompra.fecimpo = '01/01/1900 00:00:00' then null else c_facturadecompra.fecimpo end as FACTURADECOMPRA_FECIMPO,
	case when c_facturadecompra.fmodifw = '01/01/1900 00:00:00' then null else c_facturadecompra.fmodifw end as FACTURADECOMPRA_FMODIFW,
	case when c_facturadecompra.fectrans = '01/01/1900 00:00:00' then null else c_facturadecompra.fectrans end as FACTURADECOMPRA_FECTRANS,
	c_FACTURADECOMPRA.HALTAFW as FACTURADECOMPRA_HALTAFW,
	c_FACTURADECOMPRA.HORAEXPO as FACTURADECOMPRA_HORAEXPO,
	c_FACTURADECOMPRA.HORAIMPO as FACTURADECOMPRA_HORAIMPO,
	c_FACTURADECOMPRA.HMODIFW as FACTURADECOMPRA_HMODIFW,
	c_FACTURADECOMPRA.SALTAFW as FACTURADECOMPRA_SALTAFW,
	c_FACTURADECOMPRA.SMODIFW as FACTURADECOMPRA_SMODIFW,
	c_FACTURADECOMPRA.UALTAFW as FACTURADECOMPRA_UALTAFW,
	c_FACTURADECOMPRA.UMODIFW as FACTURADECOMPRA_UMODIFW,
	c_FACTURADECOMPRA.VALTAFW as FACTURADECOMPRA_VALTAFW,
	c_FACTURADECOMPRA.VMODIFW as FACTURADECOMPRA_VMODIFW,
	c_FACTURADECOMPRA.ZADSFW as FACTURADECOMPRA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as FACTURADECOMPRA__SUCURSAL,
	cast( c_FACTURADECOMPRA.COMPROBANTE as varchar( 20 ) ) as FACTURADECOMPRA_ComprobanteVirtual,
	cast( c_FACTURADECOMPRA.TIPO as varchar( 20 ) ) as FACTURADECOMPRA_TipoDeComprobanteVirtual,
	case when c_facturadecompra.ffch = '01/01/1900 00:00:00' then null else c_facturadecompra.ffch end as FACTURADECOMPRA_FFCH,
	c_FACTURADECOMPRA.FFCHENTR as FACTURADECOMPRA_FechaDeEntregaVirtual,
	cast( @parametro1 as varchar( 6 ) ) as FACTURADECOMPRA_CantidadDeNivelesPorEncimaVirtual,
	cast( @parametro2 as varchar( 6 ) ) as FACTURADECOMPRA_CantidadDeNivelesPorDebajoVirtual,
	cast( case when c_FACTURADECOMPRA.FACTTIPO = 38 then 1 else case when coalesce( Parametros.TopeInferior, 0 ) > 0 AND c_FACTURADECOMPRA.FACTTIPO = 40 then power( 0, c_FACTURADECOMPRA.COMPROBANTES_QUE_AFECTE ) else 0 end end as bit ) as FACTURADECOMPRA_SoloMostrarPedidosYRemitosCBVirtual,
	cast( c_FACTURADECOMPRA.COMPROBANTES_QUE_AFECTE as numeric( 5, 0 ) ) as FACTURADECOMPRA_ComprobantesQueAfecteVirtual,
	cast( c_FACTURADECOMPRA.COMPROBANTES_QUE_ME_AFECTARON as numeric( 5, 0 ) ) as FACTURADECOMPRA_ComprobantesQueMeAfectaronVirtual,
	C_PROVEEDOR.CLNOM as PROVEEDOR_CLNOM,
	C_CONDICIONDEPAGO74.CLNOM as CONDICIONDEPAGO74_CLNOM,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_LISTADEPRECIOS76.LPR_NOMBRE as LISTADEPRECIOS76_LPR_NOMBRE,
	C_CENTRODECOSTO.COSDES as CENTRODECOSTO_COSDES,
	C_DISTRIBUCIONCENTRODECOSTO.DESCRIP as DISTRIBUCIONCENTRODECOSTO_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_PROVEEDOR.CLIVA as PROVEEDOR_CLIVA,
	C_PAISES.PDES as PAISES_pdes,
	C_CLASIFICACIONPROVEEDOR.CLADES as CLASIFICACIONPROVEEDOR_CLADES,
	C_CONDICIONDEPAGO52.CLNOM as CONDICIONDEPAGO52_CLNOM,
	C_LISTADEPRECIOS55.LPR_NOMBRE as LISTADEPRECIOS55_LPR_NOMBRE,
	C_IMPUESTO57.DESCRIP as IMPUESTO57_descrip,
	C_IMPUESTO58.DESCRIP as IMPUESTO58_descrip,
	C_IMPUESTO59.DESCRIP as IMPUESTO59_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_CENTRODECOSTO.COSCOD as CENTRODECOSTO_COSCOD,
	C_CLASIFICACIONPROVEEDOR.CLACOD as CLASIFICACIONPROVEEDOR_CLACOD,
	C_CONDICIONDEPAGO52.CLCOD as CONDICIONDEPAGO52_CLCOD,
	C_CONDICIONDEPAGO74.CLCOD as CONDICIONDEPAGO74_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DISTRIBUCIONCENTRODECOSTO.CODIGO as DISTRIBUCIONCENTRODECOSTO_Codigo,
	C_IMPUESTO57.CODIGO as IMPUESTO57_codigo,
	C_IMPUESTO58.CODIGO as IMPUESTO58_codigo,
	C_IMPUESTO59.CODIGO as IMPUESTO59_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS55.LPR_NUMERO as LISTADEPRECIOS55_LPR_NUMERO,
	C_LISTADEPRECIOS76.LPR_NUMERO as LISTADEPRECIOS76_LPR_NUMERO,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_PAISES.PCOD as PAISES_pcod,
	C_PROVEEDOR.CLCOD as PROVEEDOR_CLCOD,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD
 from [Listados].[Vista_ComprobanteC] as c_FACTURADECOMPRA cross join Parametros
 left join ZooLogic.CCOSTO as C_CENTRODECOSTO on C_CENTRODECOSTO.COSCOD = C_FACTURADECOMPRA.CCOSTO and 0 = Funciones.empty( C_FACTURADECOMPRA.CCOSTO )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO74 on C_CONDICIONDEPAGO74.CLCOD = C_FACTURADECOMPRA.CONDPAGO and 0 = Funciones.empty( C_FACTURADECOMPRA.CONDPAGO )
 left join ZooLogic.DCCOSTO as C_DISTRIBUCIONCENTRODECOSTO on C_DISTRIBUCIONCENTRODECOSTO.CODIGO = C_FACTURADECOMPRA.DISCCOS and 0 = Funciones.empty( C_FACTURADECOMPRA.DISCCOS )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS76 on C_LISTADEPRECIOS76.LPR_NUMERO = C_FACTURADECOMPRA.CODLISTA and 0 = Funciones.empty( C_FACTURADECOMPRA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_FACTURADECOMPRA.MONEDA and 0 = Funciones.empty( C_FACTURADECOMPRA.MONEDA )
 left join ZooLogic.PROV as C_PROVEEDOR on C_PROVEEDOR.CLCOD = C_FACTURADECOMPRA.FPERSON and 0 = Funciones.empty( C_FACTURADECOMPRA.FPERSON )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_PROVEEDOR.CLPRV and 0 = Funciones.empty( C_PROVEEDOR.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_PROVEEDOR.CLIVA and 0 = Funciones.empty( C_PROVEEDOR.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR on C_CLASIFICACIONPROVEEDOR.CLACOD = C_PROVEEDOR.CLAS and 0 = Funciones.empty( C_PROVEEDOR.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO52 on C_CONDICIONDEPAGO52.CLCOD = C_PROVEEDOR.CLCONDPAG and 0 = Funciones.empty( C_PROVEEDOR.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_PROVEEDOR.CLSIPRIB and 0 = Funciones.empty( C_PROVEEDOR.CLSIPRIB )
 left join ZooLogic.IMPUESTO as C_IMPUESTO57 on C_IMPUESTO57.CODIGO = C_PROVEEDOR.CLRETGAN and 0 = Funciones.empty( C_PROVEEDOR.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO58 on C_IMPUESTO58.CODIGO = C_PROVEEDOR.CLRETSUSS and 0 = Funciones.empty( C_PROVEEDOR.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO59 on C_IMPUESTO59.CODIGO = C_PROVEEDOR.CLRETIVA and 0 = Funciones.empty( C_PROVEEDOR.CLRETIVA )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS55 on C_LISTADEPRECIOS55.LPR_NUMERO = C_PROVEEDOR.CLLISTPRE and 0 = Funciones.empty( C_PROVEEDOR.CLLISTPRE )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_PROVEEDOR.PPAIS and 0 = Funciones.empty( C_PROVEEDOR.PPAIS )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( 1=1 ) and 
	( ( @FACTURADECOMPRA_FECHA_DESDE is null ) OR ( c_FACTURADECOMPRA.FFCH >= @FACTURADECOMPRA_FECHA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHA_HASTA is null ) OR ( c_FACTURADECOMPRA.FFCH <= @FACTURADECOMPRA_FECHA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTERG1361 is null ) OR ( c_FACTURADECOMPRA.tcrg1361 = @FACTURADECOMPRA_TIPOCOMPROBANTERG1361 ) ) and 
	( ( @FACTURADECOMPRA_LETRA_DESDE is null ) OR ( c_FACTURADECOMPRA.FLETRA >= @FACTURADECOMPRA_LETRA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_LETRA_HASTA is null ) OR ( c_FACTURADECOMPRA.FLETRA <= @FACTURADECOMPRA_LETRA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_DESDE is null ) OR ( c_FACTURADECOMPRA.FPTOVENEXT >= @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_HASTA is null ) OR ( c_FACTURADECOMPRA.FPTOVENEXT <= @FACTURADECOMPRA_PUNTODEVENTAEXTENDIDO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_NUMERO_DESDE is null ) OR ( c_FACTURADECOMPRA.FNUMCOMP >= @FACTURADECOMPRA_NUMERO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_NUMERO_HASTA is null ) OR ( c_FACTURADECOMPRA.FNUMCOMP <= @FACTURADECOMPRA_NUMERO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTA_DESDE is null ) OR ( c_FACTURADECOMPRA.FPTOVEN >= @FACTURADECOMPRA_PUNTODEVENTA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PUNTODEVENTA_HASTA is null ) OR ( c_FACTURADECOMPRA.FPTOVEN <= @FACTURADECOMPRA_PUNTODEVENTA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PROVEEDOR_DESDE is null ) OR ( c_FACTURADECOMPRA.FPerson >= @FACTURADECOMPRA_PROVEEDOR_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PROVEEDOR_HASTA is null ) OR ( c_FACTURADECOMPRA.FPerson <= @FACTURADECOMPRA_PROVEEDOR_HASTA ) ) and 
	( ( @FACTURADECOMPRA_NUMINT_DESDE is null ) OR ( c_FACTURADECOMPRA.NumInt >= @FACTURADECOMPRA_NUMINT_DESDE ) ) and 
	( ( @FACTURADECOMPRA_NUMINT_HASTA is null ) OR ( c_FACTURADECOMPRA.NumInt <= @FACTURADECOMPRA_NUMINT_HASTA ) ) and 
	( ( @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_DESDE is null ) OR ( c_FACTURADECOMPRA.CONDPAGO >= @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_HASTA is null ) OR ( c_FACTURADECOMPRA.CONDPAGO <= @FACTURADECOMPRA_CONDICIONPAGOPREFERENTE_HASTA ) ) and 
	( ( @FACTURADECOMPRA_MONEDACOMPROBANTE_DESDE is null ) OR ( c_FACTURADECOMPRA.Moneda >= @FACTURADECOMPRA_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_MONEDACOMPROBANTE_HASTA is null ) OR ( c_FACTURADECOMPRA.Moneda <= @FACTURADECOMPRA_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @FACTURADECOMPRA_LISTADEPRECIOS_DESDE is null ) OR ( c_FACTURADECOMPRA.CodLista >= @FACTURADECOMPRA_LISTADEPRECIOS_DESDE ) ) and 
	( ( @FACTURADECOMPRA_LISTADEPRECIOS_HASTA is null ) OR ( c_FACTURADECOMPRA.CodLista <= @FACTURADECOMPRA_LISTADEPRECIOS_HASTA ) ) and 
	( ( @FACTURADECOMPRA_REMITO_DESDE is null ) OR ( c_FACTURADECOMPRA.NROREMITO >= @FACTURADECOMPRA_REMITO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_REMITO_HASTA is null ) OR ( c_FACTURADECOMPRA.NROREMITO <= @FACTURADECOMPRA_REMITO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAFACTURA_DESDE is null ) OR ( c_FACTURADECOMPRA.FFCHFAC >= @FACTURADECOMPRA_FECHAFACTURA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAFACTURA_HASTA is null ) OR ( c_FACTURADECOMPRA.FFCHFAC <= @FACTURADECOMPRA_FECHAFACTURA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_COTIZACION_DESDE is null ) OR ( c_FACTURADECOMPRA.Cotiz >= @FACTURADECOMPRA_COTIZACION_DESDE ) ) and 
	( ( @FACTURADECOMPRA_COTIZACION_HASTA is null ) OR ( c_FACTURADECOMPRA.Cotiz <= @FACTURADECOMPRA_COTIZACION_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAVENCIMIENTO_DESDE is null ) OR ( c_FACTURADECOMPRA.FFCHVENC >= @FACTURADECOMPRA_FECHAVENCIMIENTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAVENCIMIENTO_HASTA is null ) OR ( c_FACTURADECOMPRA.FFCHVENC <= @FACTURADECOMPRA_FECHAVENCIMIENTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_CAI_DESDE is null ) OR ( c_FACTURADECOMPRA.NCAI >= @FACTURADECOMPRA_CAI_DESDE ) ) and 
	( ( @FACTURADECOMPRA_CAI_HASTA is null ) OR ( c_FACTURADECOMPRA.NCAI <= @FACTURADECOMPRA_CAI_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAVTOCAI_DESDE is null ) OR ( c_FACTURADECOMPRA.FVTOCAI >= @FACTURADECOMPRA_FECHAVTOCAI_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAVTOCAI_HASTA is null ) OR ( c_FACTURADECOMPRA.FVTOCAI <= @FACTURADECOMPRA_FECHAVTOCAI_HASTA ) ) and 
	( ( @FACTURADECOMPRA_CENTRODECOSTO_DESDE is null ) OR ( c_FACTURADECOMPRA.CCosto >= @FACTURADECOMPRA_CENTRODECOSTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_CENTRODECOSTO_HASTA is null ) OR ( c_FACTURADECOMPRA.CCosto <= @FACTURADECOMPRA_CENTRODECOSTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_DESDE is null ) OR ( c_FACTURADECOMPRA.DisCCos >= @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_HASTA is null ) OR ( c_FACTURADECOMPRA.DisCCos <= @FACTURADECOMPRA_DISTRIBUCIONPORCENTRODECOSTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_PORCENTAJEDESCUENTO_DESDE is null ) OR ( c_FACTURADECOMPRA.FPODES >= @FACTURADECOMPRA_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_PORCENTAJEDESCUENTO_HASTA is null ) OR ( c_FACTURADECOMPRA.FPODES <= @FACTURADECOMPRA_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_DESDE is null ) OR ( c_FACTURADECOMPRA.FMTDES3 >= @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_DESDE ) ) and 
	( ( @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_HASTA is null ) OR ( c_FACTURADECOMPRA.FMTDES3 <= @FACTURADECOMPRA_MONTODESCUENTOCONIMPUESTOS3_HASTA ) ) and 
	( ( @FACTURADECOMPRA_RECARGOPORCENTAJE_DESDE is null ) OR ( c_FACTURADECOMPRA.RecPor >= @FACTURADECOMPRA_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @FACTURADECOMPRA_RECARGOPORCENTAJE_HASTA is null ) OR ( c_FACTURADECOMPRA.RecPor <= @FACTURADECOMPRA_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @PROVEEDOR_29_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR.CLNOM >= @PROVEEDOR_29_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_29_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR.CLNOM <= @PROVEEDOR_29_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO74.CLNOM >= @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO74.CLNOM <= @CONDICIONDEPAGO_74_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_75_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS76.LPR_NOMBRE >= @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS76.LPR_NOMBRE <= @LISTADEPRECIOS_76_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_DESDE is null ) OR ( C_CENTRODECOSTO.COSDES >= @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_DESDE ) ) and 
	( ( @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_HASTA is null ) OR ( C_CENTRODECOSTO.COSDES <= @CENTRODECOSTO_84_CENTRODECOSTO_DESCRIPCION_HASTA ) ) and 
	( ( @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_DESDE is null ) OR ( C_DISTRIBUCIONCENTRODECOSTO.Descrip >= @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_DESDE ) ) and 
	( ( @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_HASTA is null ) OR ( C_DISTRIBUCIONCENTRODECOSTO.Descrip <= @DISTRIBUCIONCENTRODECOSTO_85_DISTRIBUCIONPORCENTRODECOSTO_DESCRIPC_HASTA ) ) and 
	( ( @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_284_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_283_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_283_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_283_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_283_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_282_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_282_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_282_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_282_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_32_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_32_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_32_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_32_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_48_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_48_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_48_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_48_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES >= @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES <= @CLASIFICACIONPROVEEDOR_50_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO52.CLNOM >= @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO52.CLNOM <= @CONDICIONDEPAGO_52_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS55.LPR_NOMBRE >= @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS55.LPR_NOMBRE <= @LISTADEPRECIOS_55_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO57.descrip >= @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO57.descrip <= @IMPUESTO_57_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO58.descrip >= @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO58.descrip <= @IMPUESTO_58_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO59.descrip >= @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO59.descrip <= @IMPUESTO_59_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_68_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_279_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_279_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_279_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_279_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_279_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_279_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_279_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_279_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_279_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_279_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_279_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_279_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_279_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_279_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_279_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_279_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_29_LOCALIDAD_DESDE is null ) OR ( C_PROVEEDOR.CLLOC >= @PROVEEDOR_29_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_29_LOCALIDAD_HASTA is null ) OR ( C_PROVEEDOR.CLLOC <= @PROVEEDOR_29_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_29_CODIGOPOSTAL_DESDE is null ) OR ( C_PROVEEDOR.CLCP >= @PROVEEDOR_29_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_29_CODIGOPOSTAL_HASTA is null ) OR ( C_PROVEEDOR.CLCP <= @PROVEEDOR_29_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_29_PROVINCIA_DESDE is null ) OR ( C_PROVEEDOR.CLPRV >= @PROVEEDOR_29_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_29_PROVINCIA_HASTA is null ) OR ( C_PROVEEDOR.CLPRV <= @PROVEEDOR_29_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_29_TELEFONO_DESDE is null ) OR ( C_PROVEEDOR.CLTLF >= @PROVEEDOR_29_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_29_TELEFONO_HASTA is null ) OR ( C_PROVEEDOR.CLTLF <= @PROVEEDOR_29_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_29_FAX_DESDE is null ) OR ( C_PROVEEDOR.CLFAX >= @PROVEEDOR_29_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_29_FAX_HASTA is null ) OR ( C_PROVEEDOR.CLFAX <= @PROVEEDOR_29_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_29_EMAIL_DESDE is null ) OR ( C_PROVEEDOR.CLEMAIL >= @PROVEEDOR_29_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_29_EMAIL_HASTA is null ) OR ( C_PROVEEDOR.CLEMAIL <= @PROVEEDOR_29_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_29_PAGINAWEB_DESDE is null ) OR ( C_PROVEEDOR.CLPAGEWEB >= @PROVEEDOR_29_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_29_PAGINAWEB_HASTA is null ) OR ( C_PROVEEDOR.CLPAGEWEB <= @PROVEEDOR_29_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_37_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_37_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_29_CUIT_DESDE is null ) OR ( C_PROVEEDOR.CLCUIT >= @PROVEEDOR_29_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_29_CUIT_HASTA is null ) OR ( C_PROVEEDOR.CLCUIT <= @PROVEEDOR_29_CUIT_HASTA ) ) and 
	( ( @PROVEEDOR_29_TIPODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR.CLTIPODOC >= @PROVEEDOR_29_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_TIPODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR.CLTIPODOC <= @PROVEEDOR_29_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_NRODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR.CLNRODOC >= @PROVEEDOR_29_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_NRODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR.CLNRODOC <= @PROVEEDOR_29_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_IMAGEN_DESDE is null ) OR ( C_PROVEEDOR.CIMAGEN >= @PROVEEDOR_29_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_29_IMAGEN_HASTA is null ) OR ( C_PROVEEDOR.CIMAGEN <= @PROVEEDOR_29_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_29_NUMERO_DESDE is null ) OR ( C_PROVEEDOR.PNUMERO >= @PROVEEDOR_29_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_29_NUMERO_HASTA is null ) OR ( C_PROVEEDOR.PNUMERO <= @PROVEEDOR_29_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_29_CALLE_DESDE is null ) OR ( C_PROVEEDOR.PCALLE >= @PROVEEDOR_29_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_29_CALLE_HASTA is null ) OR ( C_PROVEEDOR.PCALLE <= @PROVEEDOR_29_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_29_PISO_DESDE is null ) OR ( C_PROVEEDOR.PPISO >= @PROVEEDOR_29_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_29_PISO_HASTA is null ) OR ( C_PROVEEDOR.PPISO <= @PROVEEDOR_29_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_29_DEPARTAMENTO_DESDE is null ) OR ( C_PROVEEDOR.PDEPTO >= @PROVEEDOR_29_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_DEPARTAMENTO_HASTA is null ) OR ( C_PROVEEDOR.PDEPTO <= @PROVEEDOR_29_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_PAIS_DESDE is null ) OR ( C_PROVEEDOR.PPAIS >= @PROVEEDOR_29_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_29_PAIS_HASTA is null ) OR ( C_PROVEEDOR.PPAIS <= @PROVEEDOR_29_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_29_MOVIL_DESDE is null ) OR ( C_PROVEEDOR.TLFM >= @PROVEEDOR_29_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_29_MOVIL_HASTA is null ) OR ( C_PROVEEDOR.TLFM <= @PROVEEDOR_29_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_29_CLASIFICACION_DESDE is null ) OR ( C_PROVEEDOR.CLAS >= @PROVEEDOR_29_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_29_CLASIFICACION_HASTA is null ) OR ( C_PROVEEDOR.CLAS <= @PROVEEDOR_29_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_29_FECHANACIMIENTO_DESDE is null ) OR ( C_PROVEEDOR.CLFECHA >= @PROVEEDOR_29_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_29_FECHANACIMIENTO_HASTA is null ) OR ( C_PROVEEDOR.CLFECHA <= @PROVEEDOR_29_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_29_CONDICIONDEPAGO_DESDE is null ) OR ( C_PROVEEDOR.CLCONDPAG >= @PROVEEDOR_29_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_29_CONDICIONDEPAGO_HASTA is null ) OR ( C_PROVEEDOR.CLCONDPAG <= @PROVEEDOR_29_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_29_TIPOCONVENIO_DESDE is null ) OR ( C_PROVEEDOR.CLTIPCONV >= @PROVEEDOR_29_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_29_TIPOCONVENIO_HASTA is null ) OR ( C_PROVEEDOR.CLTIPCONV <= @PROVEEDOR_29_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_29_NROIIBB_DESDE is null ) OR ( C_PROVEEDOR.CLNROIIBB >= @PROVEEDOR_29_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_29_NROIIBB_HASTA is null ) OR ( C_PROVEEDOR.CLNROIIBB <= @PROVEEDOR_29_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_29_LISTADEPRECIO_DESDE is null ) OR ( C_PROVEEDOR.CLLISTPRE >= @PROVEEDOR_29_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_29_LISTADEPRECIO_HASTA is null ) OR ( C_PROVEEDOR.CLLISTPRE <= @PROVEEDOR_29_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_29_SITUACIONGANANCIAS is null ) OR ( C_PROVEEDOR.CLSITGAN = @PROVEEDOR_29_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_29_RETENCIONGANANCIAS_DESDE is null ) OR ( C_PROVEEDOR.CLRETGAN >= @PROVEEDOR_29_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_29_RETENCIONGANANCIAS_HASTA is null ) OR ( C_PROVEEDOR.CLRETGAN <= @PROVEEDOR_29_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_29_RETENCIONSUSS_DESDE is null ) OR ( C_PROVEEDOR.CLRETSUSS >= @PROVEEDOR_29_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_29_RETENCIONSUSS_HASTA is null ) OR ( C_PROVEEDOR.CLRETSUSS <= @PROVEEDOR_29_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_29_RETENCIONIVA_DESDE is null ) OR ( C_PROVEEDOR.CLRETIVA >= @PROVEEDOR_29_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_29_RETENCIONIVA_HASTA is null ) OR ( C_PROVEEDOR.CLRETIVA <= @PROVEEDOR_29_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_29_OBJETOIVA is null ) OR ( C_PROVEEDOR.CLOBJIVA = @PROVEEDOR_29_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_29_EMPLEADOR is null ) OR ( C_PROVEEDOR.CLEMPLEAD = @PROVEEDOR_29_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_29_EXCLUIDORETENCIONGANANCIAS is null ) OR ( C_PROVEEDOR.EXRETGAN = @PROVEEDOR_29_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_29_EXCLUIDORETENCIONIVA is null ) OR ( C_PROVEEDOR.EXRETIVA = @PROVEEDOR_29_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_29_EXCLUIDORETENCIONSUSS is null ) OR ( C_PROVEEDOR.EXRETSUSS = @PROVEEDOR_29_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_29_SUJETOVINCULADO is null ) OR ( C_PROVEEDOR.CLSujVinc = @PROVEEDOR_29_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_PROVEEDOR.PVHastaIva >= @PROVEEDOR_29_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_PROVEEDOR.PVHastaIva <= @PROVEEDOR_29_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_PROVEEDOR.PVHastaGan >= @PROVEEDOR_29_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_29_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_PROVEEDOR.PVHastaGan <= @PROVEEDOR_29_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_29_CODIGOSIPRIB_DESDE is null ) OR ( C_PROVEEDOR.CLSIPRIB >= @PROVEEDOR_29_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_29_CODIGOSIPRIB_HASTA is null ) OR ( C_PROVEEDOR.CLSIPRIB <= @PROVEEDOR_29_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_29_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR.PorcenTC >= @PROVEEDOR_29_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_29_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR.PorcenTC <= @PROVEEDOR_29_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_29_TASACEROAPLICA is null ) OR ( C_PROVEEDOR.AplicaTC = @PROVEEDOR_29_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_29_RUT_DESDE is null ) OR ( C_PROVEEDOR.RUT >= @PROVEEDOR_29_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_29_RUT_HASTA is null ) OR ( C_PROVEEDOR.RUT <= @PROVEEDOR_29_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_29_INACTIVOFW is null ) OR ( C_PROVEEDOR.InactivoFW = @PROVEEDOR_29_INACTIVOFW ) ) and 
	( ( @SUCURSAL_279_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_279_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_279_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_279_CODIGO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_FACTURADECOMPRA.BDALTAFW >= @FACTURADECOMPRA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_FACTURADECOMPRA.BDALTAFW <= @FACTURADECOMPRA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_FACTURADECOMPRA.BDMODIFW >= @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_FACTURADECOMPRA.BDMODIFW <= @FACTURADECOMPRA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_FACTURADECOMPRA.ESTTRANS >= @FACTURADECOMPRA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_FACTURADECOMPRA.ESTTRANS <= @FACTURADECOMPRA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAALTAFW_DESDE is null ) OR ( c_FACTURADECOMPRA.FALTAFW >= @FACTURADECOMPRA_FECHAALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAALTAFW_HASTA is null ) OR ( c_FACTURADECOMPRA.FALTAFW <= @FACTURADECOMPRA_FECHAALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAEXPO_DESDE is null ) OR ( c_FACTURADECOMPRA.FECEXPO >= @FACTURADECOMPRA_FECHAEXPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAEXPO_HASTA is null ) OR ( c_FACTURADECOMPRA.FECEXPO <= @FACTURADECOMPRA_FECHAEXPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAIMPO_DESDE is null ) OR ( c_FACTURADECOMPRA.FECIMPO >= @FACTURADECOMPRA_FECHAIMPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAIMPO_HASTA is null ) OR ( c_FACTURADECOMPRA.FECIMPO <= @FACTURADECOMPRA_FECHAIMPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_FACTURADECOMPRA.FMODIFW >= @FACTURADECOMPRA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_FACTURADECOMPRA.FMODIFW <= @FACTURADECOMPRA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_FECHATRANSFERENCIA_DESDE is null ) OR ( c_FACTURADECOMPRA.FECTRANS >= @FACTURADECOMPRA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHATRANSFERENCIA_HASTA is null ) OR ( c_FACTURADECOMPRA.FECTRANS <= @FACTURADECOMPRA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAALTAFW_DESDE is null ) OR ( c_FACTURADECOMPRA.HALTAFW >= @FACTURADECOMPRA_HORAALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAALTAFW_HASTA is null ) OR ( c_FACTURADECOMPRA.HALTAFW <= @FACTURADECOMPRA_HORAALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAEXPO_DESDE is null ) OR ( c_FACTURADECOMPRA.HORAEXPO >= @FACTURADECOMPRA_HORAEXPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAEXPO_HASTA is null ) OR ( c_FACTURADECOMPRA.HORAEXPO <= @FACTURADECOMPRA_HORAEXPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAIMPO_DESDE is null ) OR ( c_FACTURADECOMPRA.HORAIMPO >= @FACTURADECOMPRA_HORAIMPO_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAIMPO_HASTA is null ) OR ( c_FACTURADECOMPRA.HORAIMPO <= @FACTURADECOMPRA_HORAIMPO_HASTA ) ) and 
	( ( @FACTURADECOMPRA_HORAMODIFICACIONFW_DESDE is null ) OR ( c_FACTURADECOMPRA.HMODIFW >= @FACTURADECOMPRA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_HORAMODIFICACIONFW_HASTA is null ) OR ( c_FACTURADECOMPRA.HMODIFW <= @FACTURADECOMPRA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_SERIEALTAFW_DESDE is null ) OR ( c_FACTURADECOMPRA.SALTAFW >= @FACTURADECOMPRA_SERIEALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_SERIEALTAFW_HASTA is null ) OR ( c_FACTURADECOMPRA.SALTAFW <= @FACTURADECOMPRA_SERIEALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_FACTURADECOMPRA.SMODIFW >= @FACTURADECOMPRA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_FACTURADECOMPRA.SMODIFW <= @FACTURADECOMPRA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_USUARIOALTAFW_DESDE is null ) OR ( c_FACTURADECOMPRA.UALTAFW >= @FACTURADECOMPRA_USUARIOALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_USUARIOALTAFW_HASTA is null ) OR ( c_FACTURADECOMPRA.UALTAFW <= @FACTURADECOMPRA_USUARIOALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_FACTURADECOMPRA.UMODIFW >= @FACTURADECOMPRA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_FACTURADECOMPRA.UMODIFW <= @FACTURADECOMPRA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_VERSIONALTAFW_DESDE is null ) OR ( c_FACTURADECOMPRA.VALTAFW >= @FACTURADECOMPRA_VERSIONALTAFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_VERSIONALTAFW_HASTA is null ) OR ( c_FACTURADECOMPRA.VALTAFW <= @FACTURADECOMPRA_VERSIONALTAFW_HASTA ) ) and 
	( ( @FACTURADECOMPRA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_FACTURADECOMPRA.VMODIFW >= @FACTURADECOMPRA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURADECOMPRA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_FACTURADECOMPRA.VMODIFW <= @FACTURADECOMPRA_VERSIONMODIFICACIONFW_HASTA ) )

)