IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[VistaIntegraComprobantes]') AND type = N'V')
	DROP VIEW [Listados].[VistaIntegraComprobantes];
GO;

CREATE VIEW [Listados].[VistaIntegraComprobantes] AS
(
select
	Comprobantes.Origen,
	Comprobantes.GrupoInfo,
	Comprobantes.Codigo,
	Comprobantes.FPerson,
	Comprobantes.RolDePersonaVirtual,
	Comprobantes.FFCH,
	Comprobantes.HALTAFW,
	Comprobantes.FACTTIPO,
	Comprobantes.FLETRA,
	Comprobantes.FPTOVEN,
	Comprobantes.FNUMCOMP,
	Comprobantes.Primero,
	Comprobantes.Ultimo,
	Comprobantes.FactSec,
	Comprobantes.ComprobanteVirtual,
	Comprobantes.signomov * Comprobantes.fImpuesto as fImpuesto,
	Comprobantes.CodLista,
	Comprobantes.Moneda,
	Comprobantes.signomov * Comprobantes.FTotal as FTotal,
	Comprobantes.signomov,
	Comprobantes.Anulado,
	Comprobantes.CondivaLp,
	Comprobantes.fCuit,
	Comprobantes.signomov * Comprobantes.totimpue as totimpue,
	Comprobantes.signomov * Comprobantes.totrecarCI as totrecarCI,
	Comprobantes.signomov * Comprobantes.totdesc as totdesc,
	Comprobantes.signomov * Comprobantes.totrecarSI as totrecarSI,
	Comprobantes.signomov * Comprobantes.totdescSI as totdescSI,
	Comprobantes.IdCaja,
	Comprobantes.Cotiz,
	Comprobantes.MonSis,
	abs( Comprobantes.signomov * Comprobantes.TotalCant ) as TotalCant,
	Comprobantes.signomov * Comprobantes.fSubToN as fSubToN,
	Comprobantes.fven 
from
	(
		select
			'VENTAS'																as Origen,	--Indica el origen del registro
			'Ventas'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Cliente' as varchar( 26 ) )										as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			FLETRA 																	as FLETRA,
			FPTOVEN 																as FPTOVEN,
			FNUMCOMP 																as FNUMCOMP,
			FNUMCOMP 																as Primero,
			FNUMCOMP 																as Ultimo,
			FACTSEC																	as FactSec,
			cast( funciones.identificadordecomprobanteparalistado(facttipo, fletra, fptoven, fnumcomp) as varchar( 26 ) ) as ComprobanteVirtual,
			FIMPUESTO 																as fImpuesto,
			CODLISTA 																as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			SIGNOMOV 																as signomov,
			ANULADO 																as Anulado,
			CONDIVALP 																as CondivaLp,
			FCUIT 																	as fCuit,
			TOTIMPUE 																as totimpue,
			TOTRECARCI 																as totrecarCI,
			TOTDESC 																as totdesc,
			TOTRECARSI 																as totrecarSI,
			TOTDESCSI 																as totdescSI,
			IDCAJA 																	as IdCaja,
			COTIZ 																	as Cotiz,
			MONSIS 																	as MonSis,
			TOTALCANT 																as TotalCant,
			FSUBTON																	as fSubToN,
			FVEN																	as fven
		from ZooLogic.COMPROBANTEV
		union all
		select
			'VENTAS'																as Origen,	--Indica el origen del registro
			'Fondos'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Cliente' as varchar( 26 ) )										as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			FLETRA 																	as FLETRA,
			FPTOVEN 																as FPTOVEN,
			FNUMCOMP 																as FNUMCOMP,
			FNUMCOMP																as Primero,
			FNUMCOMP 																as Ultimo,
			null																	as FactSec,
			cast( funciones.identificadordecomprobanteparalistado(facttipo, fletra, fptoven, fnumcomp) as varchar( 26 ) ) as ComprobanteVirtual,
			null 																	as fImpuesto,
			null 																	as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			SIGNOMOV 																as signomov,
			ANULADO 																as Anulado,
			null 																	as CondivaLp,
			null 																	as fCuit,
			null 																	as totimpue,
			null 																	as totrecarCI,
			null 																	as totdesc,
			null 																	as totrecarSI,
			null	 																as totdescSI,
			IDCAJA 																	as IdCaja,
			COTIZ 																	as Cotiz,
			MONSIS 																	as MonSis,
			null	 																as TotalCant,
			null																	as fSubToN, 
			FVEN																	as fven
		from ZooLogic.RECIBO
		union all
		select
			'COMPRAS_FC'															as Origen,
			'Compras'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Proveedor' as varchar( 26 ) )									as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			cast( FLETRA as char(1) )														as FLETRA,
			null	 																as FPTOVEN,
			FNUMCOMP 																as FNUMCOMP,
			NUMINT 																	as Primero,
			NUMINT	 																as Ultimo,
			cast( null as char(2) )													as FACTSEC,
			cast( funciones.identificadordecomprobanteparalistado(facttipo, fletra, fptoven, fnumcomp) as varchar( 26 ) ) as ComprobanteVirtual,
			FIMPUESTO 																as fImpuesto,
			CODLISTA 																as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			SIGNOMOV 																as signomov,
			ANULADO 																as Anulado,
			CONDIVALP 																as CondivaLp,
			FCUIT 																	as fCuit,
			TOTIMPUE 																as totimpue,
			TOTRECAR 																as totrecarCI,
			TOTDESC 																as totdesc,
			TOTRECARSI 																as totrecarSI,
			TOTDESCSI 																as totdescSI,
			IDCAJA 																	as IdCaja,
			COTIZ 																	as Cotiz,
			MONSIS 																	as MonSis,
			(select sum( fcd.FCANT ) from ZooLogic.FACCOMPRADET fcd where fcd.CODIGO = fc.CODIGO) as TotalCant,
			FSUBTON																	as fSubToN,
			cast( null as char(10) )												as fven
		from ZooLogic.FACCOMPRA fc
		union all
		select
			'COMPRAS_NC'															as Origen,
			'Compras'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Proveedor' as varchar( 26 ) )									as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			cast( FLETRA as char(1) )														as FLETRA,
			null	 																as FPTOVEN,
			FNUMCOMP 																as FNUMCOMP,
			NUMINT 																	as Primero,
			NUMINT	 																as Ultimo,
			cast( null as char(2) )													as FACTSEC,
			cast( funciones.identificadordecomprobanteparalistado(facttipo, fletra, fptoven, fnumcomp) as varchar( 26 ) ) as ComprobanteVirtual,
			FIMPUESTO 																as fImpuesto,
			CODLISTA 																as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			SIGNOMOV 																as signomov,
			ANULADO 																as Anulado,
			CONDIVALP 																as CondivaLp,
			FCUIT 																	as fCuit,
			TOTIMPUE 																as totimpue,
			TOTRECAR 																as totrecarCI,
			TOTDESC 																as totdesc,
			TOTRECARSI 																as totrecarSI,
			TOTDESCSI 																as totdescSI,
			IDCAJA 																	as IdCaja,
			COTIZ 																	as Cotiz,
			MONSIS 																	as MonSis,
			(select sum( ncd.FCANT ) from ZooLogic.NCCOMPRADET ncd where ncd.CODIGO = nc.CODIGO) as TotalCant,
			FSUBTON																	as fSubToN,
			cast( null as char(10) )												as fven
		from ZooLogic.NCCOMPRA nc 
		union all
		select
			'COMPRAS_ND'															as Origen,
			'Compras'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Proveedor' as varchar( 26 ) )									as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			cast( FLETRA as char(1) ) 														as FLETRA,
			null	 																as FPTOVEN,
			FNUMCOMP 																as FNUMCOMP,
			NUMINT 																	as Primero,
			NUMINT	 																as Ultimo,
			cast( null as char(2) )													as FACTSEC,
			cast( funciones.identificadordecomprobanteparalistado(facttipo, fletra, fptoven, fnumcomp) as varchar( 26 ) ) as ComprobanteVirtual,
			FIMPUESTO 																as fImpuesto,
			CODLISTA 																as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			SIGNOMOV 																as signomov,
			ANULADO 																as Anulado,
			CONDIVALP 																as CondivaLp,
			FCUIT 																	as fCuit,
			TOTIMPUE 																as totimpue,
			TOTRECAR 																as totrecarCI,
			TOTDESC 																as totdesc,
			TOTRECARSI 																as totrecarSI,
			TOTDESCSI 																as totdescSI,
			IDCAJA 																	as IdCaja,
			COTIZ 																	as Cotiz,
			MONSIS 																	as MonSis,
			(select sum( ndd.FCANT ) from ZooLogic.FACCOMPRADET ndd where ndd.CODIGO = nd.CODIGO) as TotalCant,
			FSUBTON																	as fSubToN,
			cast( null as char(10) )												as fven
		from ZooLogic.NDCOMPRA nd
		union all
		select
			'PAGOS'																	as Origen,
			'Fondos'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Proveedor' as varchar( 26 ) )									as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			FLETRA 																	as FLETRA,
			FPTOVEN 																as FPTOVEN,
			FNUMCOMP 																as FNUMCOMP,
			FNUMCOMP																as Primero,
			FNUMCOMP 																as Ultimo,
			cast( null as char(2) )													as FACTSEC,
			cast( funciones.identificadordecomprobanteparalistado(facttipo, fletra, fptoven, fnumcomp) as varchar( 26 ) ) as ComprobanteVirtual,
			null	 																as fImpuesto,
			null	 																as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			-1		 																as signomov,
			ANULADO 																as Anulado,
			null	 																as CondivaLp,
			null 																	as fCuit,
			null	 																as totimpue,
			null 																	as totrecarCI,
			null	 																as totdesc,
			null																	as totrecarSI,
			null 																	as totdescSI,
			(select top 1 pdv.IDCAJA from ZooLogic.PAGOVAL pdv where pdv.JJNUM = pg.CODIGO ) as IdCaja,
			null 																	as Cotiz,
			null 																	as MonSis,
			null	 																as TotalCant,
			null																	as fSubToN,
			cast( null as char(10) )												as fven
		from ZooLogic.PAGO pg
		union all
		select
			'CAJA'																	as Origen,
			'Fondos'																as GrupoInfo,
			CODIGO																	as Codigo,
			null																	as FPerson,
			null																	as RolDePersonaVirtual,
			case when fecha = '01/01/1900 00:00:00' then null else fecha end		as FFCH,
			haltafw																	as HALTAFW,
			98		 																as FACTTIPO,
			null 																	as FLETRA,
			null	 																as FPTOVEN,
			NUMERO																	as FNUMCOMP,
			NUMERO 																	as Primero,
			NUMERO	 																as Ultimo,
			cast( null as char(2) )													as FACTSEC,
			cast( funciones.identificadordecomprobanteparalistado( 98, null, null, NUMERO) as varchar( 26 ) ) as ComprobanteVirtual,
			null	 																as fImpuesto,
			null	 																as CodLista,
			MONEDA 																	as Moneda,
			null 																	as FTotal,
			SIGNOMOV 																as signomov,
			0		 																as Anulado,
			null	 																as CondivaLp,
			null 																	as fCuit,
			null	 																as totimpue,
			null 																	as totrecarCI,
			null	 																as totdesc,
			null																	as totrecarSI,
			null 																	as totdescSI,
			( SELECT TOP 1 ccd.IDCAJA FROM ZooLogic.COMPCAJADET ccd where ccd.CODDETVAL = cc.CODIGO ) as IdCaja,
			null 																	as Cotiz,
			null 																	as MonSis,
			null	 																as TotalCant,
			null																	as fSubToN,
			VENDEDOR																as fven		
		from ZooLogic.COMCAJ cc
		union all
		select
			'CANJEVALORES'															as Origen,
			'Fondos'																as GrupoInfo,
			CODIGO																	as Codigo,
			null																	as FPerson,
			null																	as RolDePersonaVirtual,
			case when fecha = '01/01/1900 00:00:00' then null else fecha end		as FFCH,
			haltafw																	as HALTAFW,
			32		 																as FACTTIPO,
			null 																	as FLETRA,
			null	 																as FPTOVEN,
			NUMERO																	as FNUMCOMP,
			NUMERO 																	as Primero,
			NUMERO	 																as Ultimo,
			cast( null as char(2) )													as FACTSEC,
			cast( funciones.identificadordecomprobanteparalistado( 32, null, null, NUMERO) as varchar( 26 ) ) as ComprobanteVirtual,
			null	 																as fImpuesto,
			null	 																as CodLista,
			MONEDA 																	as Moneda,
			ftotal 																	as FTotal,
			SIGNO	 																as signomov,
			0		 																as Anulado,
			null	 																as CondivaLp,
			null 																	as fCuit,
			null	 																as totimpue,
			null 																	as totrecarCI,
			null	 																as totdesc,
			null																	as totrecarSI,
			null 																	as totdescSI,
			( SELECT TOP 1 ccd.IDCAJA FROM ZooLogic.CANJECUPONESDET ccd where ccd.jjnum = canj.CODIGO ) as IdCaja,
			( SELECT TOP 1 ccd.COTIZA FROM ZooLogic.CANJECUPONESDET ccd where ccd.jjnum = canj.CODIGO ) as Cotiz,
			null 																	as MonSis,
			null	 																as TotalCant,
			null																	as fSubToN ,
			VENDEDOR																as fven
		from ZooLogic.CANJECUPONES canj

		union all

		select
			'OTROSPAGOS'															as Origen,	--Indica el origen del registro
			'Fondos'																as GrupoInfo,
			CODIGO																	as Codigo,
			FPERSON																	as FPerson,
			cast( 'Proveedor' as varchar( 26 ) )									as RolDePersonaVirtual,
			case when ffch = '01/01/1900 00:00:00' then null else ffch end 			as FFCH,
			haltafw																	as HALTAFW,
			FACTTIPO 																as FACTTIPO,
			FLETRA 																	as FLETRA,
			FPTOVEN 																as FPTOVEN,
			NUMERO 																as FNUMCOMP,
			NUMERO 																as Primero,
			NUMERO 																as Ultimo,
			cast( null as char(2) )													as FactSec,
			cast( funciones.identificadordecomprobanteparalistado( 888, 'X', null, NUMERO) as varchar( 26 ) ) as ComprobanteVirtual,
			null 																	as fImpuesto,
			null 																	as CodLista,
			MONEDA 																	as Moneda,
			FTOTAL 																	as FTotal,
			-1	 																	as signomov,
			ANULADO 																as Anulado,
			NULL 																	as CondivaLp,
			NULL 																	as fCuit,
			NULL 																	as totimpue,
			NULL 																	as totrecarCI,
			NULL 																	as totdesc,
			NULL 																	as totrecarSI,
			NULL 																	as totdescSI,
			(select top 1 vcp.IDCAJA from ZooLogic.VALCOMPPAGO vcp where vcp.JJNUM = cp.CODIGO ) as IdCaja,
			COTIZ 																	as Cotiz,
			MONSIS 																	as MonSis,
			NULL 																	as TotalCant,
			NULL																	as fSubToN,
			cast( null as char(10) )												as fven
		from ZooLogic.COMPPAGO CP

	) as Comprobantes
);







