IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_FACTURA_VENTAS_FACTURA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_FACTURA_VENTAS_FACTURA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_FACTURA_VENTAS_FACTURA]
( @BaseDeDatos varchar(8),
	@FACTURA_DESPACHOS_DESDE varchar(254),
	@FACTURA_DESPACHOS_HASTA varchar(254),
	@DATOSADICIONALESCOMPROBANTESA_1_SUSCRIBE numeric(2, 0),
	@DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_DESDE varchar(2),
	@DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_HASTA varchar(2),
	@DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_DESDE varchar(10),
	@DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_HASTA varchar(10),
	@MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_DESDE varchar(70),
	@MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_HASTA varchar(70),
	@FACTURA_VENDEDOR_DESDE varchar(10),
	@FACTURA_VENDEDOR_HASTA varchar(10),
	@FACTURA_CLIENTE_DESDE varchar(10),
	@FACTURA_CLIENTE_HASTA varchar(10),
	@FACTURA_TIPOCOMPROBANTE numeric(2, 0),
	@FACTURA_ANULADO bit,
	@FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE varchar(10),
	@FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA varchar(10),
	@FACTURA_NROOPECOMMERCE_DESDE varchar(254),
	@FACTURA_NROOPECOMMERCE_HASTA varchar(254),
	@FACTURA_CLIENTEDESCRIPCION_DESDE varchar(185),
	@FACTURA_CLIENTEDESCRIPCION_HASTA varchar(185),
	@FACTURA_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURA_MONEDACOMPROBANTE_HASTA varchar(10),
	@FACTURA_LISTADEPRECIOS_DESDE varchar(6),
	@FACTURA_LISTADEPRECIOS_HASTA varchar(6),
	@FACTURA_EMAIL_DESDE varchar(250),
	@FACTURA_EMAIL_HASTA varchar(250),
	@FACTURA_LETRA_DESDE varchar(1),
	@FACTURA_LETRA_HASTA varchar(1),
	@FACTURA_PUNTODEVENTA_DESDE numeric(4, 0),
	@FACTURA_PUNTODEVENTA_HASTA numeric(4, 0),
	@FACTURA_NUMERO_DESDE numeric(8, 0),
	@FACTURA_NUMERO_HASTA numeric(8, 0),
	@FACTURA_FECHA_DESDE datetime,
	@FACTURA_FECHA_HASTA datetime,
	@FACTURA_COTIZACION_DESDE numeric(15, 5),
	@FACTURA_COTIZACION_HASTA numeric(15, 5),
	@FACTURA_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@FACTURA_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@FACTURA_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@FACTURA_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@CLIENTE_2_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_2_CLIENTE_NOMBRE_HASTA varchar(185),
	@MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE varchar(50),
	@MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA varchar(50),
	@MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9249_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9249_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9248_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9248_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_3_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_3_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_18_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_18_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@PROVINCIA_96_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_96_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_102_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_102_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@VENDEDOR_9111_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_9111_VENDEDOR_NOMBRE_HASTA varchar(60),
	@SUCURSAL_9245_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9245_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9245_LINEA_DESDE varchar(10),
	@SUCURSAL_9245_LINEA_HASTA varchar(10),
	@SUCURSAL_9245_TIPO_DESDE varchar(10),
	@SUCURSAL_9245_TIPO_HASTA varchar(10),
	@SUCURSAL_9245_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9245_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_2_VENDEDOR_DESDE varchar(10),
	@CLIENTE_2_VENDEDOR_HASTA varchar(10),
	@CLIENTE_2_CALLE_DESDE varchar(250),
	@CLIENTE_2_CALLE_HASTA varchar(250),
	@CLIENTE_2_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_2_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_2_CUIT_DESDE varchar(15),
	@CLIENTE_2_CUIT_HASTA varchar(15),
	@CLIENTE_2_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_2_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_2_EMAIL_DESDE varchar(250),
	@CLIENTE_2_EMAIL_HASTA varchar(250),
	@CLIENTE_2_FAX_DESDE varchar(20),
	@CLIENTE_2_FAX_HASTA varchar(20),
	@CLIENTE_2_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_2_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_2_IMAGEN_DESDE varchar(180),
	@CLIENTE_2_IMAGEN_HASTA varchar(180),
	@CLIENTE_2_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_2_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_2_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_2_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_2_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_2_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_2_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_2_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_2_PAIS_DESDE varchar(3),
	@CLIENTE_2_PAIS_HASTA varchar(3),
	@CLIENTE_2_PISO_DESDE varchar(3),
	@CLIENTE_2_PISO_HASTA varchar(3),
	@CLIENTE_2_PROVINCIA_DESDE varchar(2),
	@CLIENTE_2_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_2_TELEFONO_DESDE varchar(30),
	@CLIENTE_2_TELEFONO_HASTA varchar(30),
	@CLIENTE_2_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_2_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_2_MOVIL_DESDE varchar(30),
	@CLIENTE_2_MOVIL_HASTA varchar(30),
	@CLIENTE_2_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_2_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_2_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_2_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_2_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_2_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_2_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_2_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_2_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_2_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_2_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_2_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_2_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_2_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_2_ESTADOCIVIL varchar(13),
	@CLIENTE_2_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_2_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_2_SEXO varchar(10),
	@CLIENTE_2_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_2_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_2_RUT_DESDE varchar(12),
	@CLIENTE_2_RUT_HASTA varchar(12),
	@CLIENTE_2_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_2_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_2_TIPOCLI_DESDE varchar(10),
	@CLIENTE_2_TIPOCLI_HASTA varchar(10),
	@CLIENTE_2_CATEGCLI_DESDE varchar(10),
	@CLIENTE_2_CATEGCLI_HASTA varchar(10),
	@CLIENTE_2_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_2_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_2_SUJETOVINCULADO bit,
	@CLIENTE_2_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_2_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_2_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_2_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_2_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_2_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_2_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_2_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_2_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_2_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_2_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_2_APELLIDO_DESDE varchar(60),
	@CLIENTE_2_APELLIDO_HASTA varchar(60),
	@CLIENTE_2_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_2_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_2_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_2_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_2_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_2_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_2_TASACEROAPLICA bit,
	@CLIENTE_2_INACTIVOFW bit,
	@MOTIVODESCUENTOYDEVOLUCION_64_TIPO numeric(1, 0),
	@VENDEDOR_9111_CODIGOPOSTAL_DESDE varchar(8),
	@VENDEDOR_9111_CODIGOPOSTAL_HASTA varchar(8),
	@VENDEDOR_9111_CALLE_DESDE varchar(70),
	@VENDEDOR_9111_CALLE_HASTA varchar(70),
	@VENDEDOR_9111_NRODOCUMENTO_DESDE varchar(10),
	@VENDEDOR_9111_NRODOCUMENTO_HASTA varchar(10),
	@VENDEDOR_9111_EMAIL_DESDE varchar(250),
	@VENDEDOR_9111_EMAIL_HASTA varchar(250),
	@VENDEDOR_9111_FECHAINGRESO_DESDE datetime,
	@VENDEDOR_9111_FECHAINGRESO_HASTA datetime,
	@VENDEDOR_9111_FECHANACIMIENTO_DESDE datetime,
	@VENDEDOR_9111_FECHANACIMIENTO_HASTA datetime,
	@VENDEDOR_9111_IMAGEN_DESDE varchar(180),
	@VENDEDOR_9111_IMAGEN_HASTA varchar(180),
	@VENDEDOR_9111_LOCALIDAD_DESDE varchar(70),
	@VENDEDOR_9111_LOCALIDAD_HASTA varchar(70),
	@VENDEDOR_9111_PROVINCIA_DESDE varchar(2),
	@VENDEDOR_9111_PROVINCIA_HASTA varchar(2),
	@VENDEDOR_9111_TELEFONO_DESDE varchar(30),
	@VENDEDOR_9111_TELEFONO_HASTA varchar(30),
	@VENDEDOR_9111_TIPODOCUMENTO_DESDE varchar(2),
	@VENDEDOR_9111_TIPODOCUMENTO_HASTA varchar(2),
	@VENDEDOR_9111_NUMERO_DESDE numeric(5, 0),
	@VENDEDOR_9111_NUMERO_HASTA numeric(5, 0),
	@VENDEDOR_9111_PISO_DESDE varchar(3),
	@VENDEDOR_9111_PISO_HASTA varchar(3),
	@VENDEDOR_9111_DEPARTAMENTO_DESDE varchar(3),
	@VENDEDOR_9111_DEPARTAMENTO_HASTA varchar(3),
	@VENDEDOR_9111_PAIS_DESDE varchar(3),
	@VENDEDOR_9111_PAIS_HASTA varchar(3),
	@VENDEDOR_9111_FECHAEGRESO_DESDE datetime,
	@VENDEDOR_9111_FECHAEGRESO_HASTA datetime,
	@VENDEDOR_9111_MOVIL_DESDE varchar(30),
	@VENDEDOR_9111_MOVIL_HASTA varchar(30),
	@VENDEDOR_9111_CLASIFICACION_DESDE varchar(10),
	@VENDEDOR_9111_CLASIFICACION_HASTA varchar(10),
	@VENDEDOR_9111_DESCUENTOPREFERENTE_DESDE varchar(10),
	@VENDEDOR_9111_DESCUENTOPREFERENTE_HASTA varchar(10),
	@VENDEDOR_9111_INACTIVOFW bit,
	@SUCURSAL_9245_CODIGO_DESDE varchar(10),
	@SUCURSAL_9245_CODIGO_HASTA varchar(10),
	@FACTURA_FECHAALTAFW_DESDE datetime,
	@FACTURA_FECHAALTAFW_HASTA datetime,
	@FACTURA_HORAALTAFW_DESDE varchar(8),
	@FACTURA_HORAALTAFW_HASTA varchar(8),
	@FACTURA_BASEDEDATOSALTAFW_DESDE varchar(8),
	@FACTURA_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURA_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@FACTURA_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@FACTURA_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@FACTURA_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@FACTURA_FECHAEXPO_DESDE datetime,
	@FACTURA_FECHAEXPO_HASTA datetime,
	@FACTURA_FECHAIMPO_DESDE datetime,
	@FACTURA_FECHAIMPO_HASTA datetime,
	@FACTURA_FECHAMODIFICACIONFW_DESDE datetime,
	@FACTURA_FECHAMODIFICACIONFW_HASTA datetime,
	@FACTURA_FECHATRANSFERENCIA_DESDE datetime,
	@FACTURA_FECHATRANSFERENCIA_HASTA datetime,
	@FACTURA_HORAEXPO_DESDE varchar(8),
	@FACTURA_HORAEXPO_HASTA varchar(8),
	@FACTURA_HORAIMPO_DESDE varchar(8),
	@FACTURA_HORAIMPO_HASTA varchar(8),
	@FACTURA_HORAMODIFICACIONFW_DESDE varchar(8),
	@FACTURA_HORAMODIFICACIONFW_HASTA varchar(8),
	@FACTURA_SERIEALTAFW_DESDE varchar(7),
	@FACTURA_SERIEALTAFW_HASTA varchar(7),
	@FACTURA_SERIEMODIFICACIONFW_DESDE varchar(7),
	@FACTURA_SERIEMODIFICACIONFW_HASTA varchar(7),
	@FACTURA_USUARIOALTAFW_DESDE varchar(100),
	@FACTURA_USUARIOALTAFW_HASTA varchar(100),
	@FACTURA_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@FACTURA_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@FACTURA_VERSIONALTAFW_DESDE varchar(13),
	@FACTURA_VERSIONALTAFW_HASTA varchar(13),
	@FACTURA_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@FACTURA_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max),
	@Parametro2 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_factura.codigo, 38, ' ' ) as varchar( 46 ) ) as FACTURA__Grupo,
	@basededatos as FACTURA__BD,
	c_FACTURA.CODIGO as FACTURA_CODIGO,
	c_FACTURA.FPERSON as FACTURA_FPerson,
	C_CLIENTE.CIMAGEN as CLIENTE_CIMAGEN,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fsubtot as numeric( 15, 4 ) ) as FACTURA_FSubTOT,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fsubton as numeric( 15, 4 ) ) as FACTURA_fSubToN,
	c_FACTURA.ANULADO as FACTURA_Anulado,
	cast( c_factura.signomov*c_factura.totalcant as numeric( 16, 3 ) ) as FACTURA_TotalCant,
	c_FACTURA.MOTDESCDEV as FACTURA_MotDescDev,
	c_FACTURA.OPECOMM as FACTURA_OPEcomm,
	c_FACTURA.FCLIENTE as FACTURA_FCLIENTE,
	C_VENDEDOR9111.CIMAGEN as VENDEDOR9111_CIMAGEN,
	c_FACTURA.MONEDA as FACTURA_Moneda,
	c_FACTURA.CODLISTA as FACTURA_CodLista,
	c_FACTURA.EMAIL as FACTURA_Email,
	c_FACTURA.FLETRA as FACTURA_FLETRA,
	c_FACTURA.FPTOVEN as FACTURA_FPTOVEN,
	c_FACTURA.FNUMCOMP as FACTURA_FNUMCOMP,
	case when c_factura.ffch = '01/01/1900 00:00:00' then null else c_factura.ffch end as FACTURA_FFCH,
	c_FACTURA.COTIZ as FACTURA_Cotiz,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fajxre as numeric( 15, 2 ) ) as FACTURA_FAjXRe,
	c_FACTURA.FPODES as FACTURA_FPODES,
	cast( c_factura.signomov*c_factura.cotiz*-1*c_factura.fdescu as numeric( 15, 2 ) ) as FACTURA_fDescu,
	cast( c_factura.signomov*c_factura.cotiz*-1*c_factura.md3 as numeric( 15, 2 ) ) as FACTURA_MD3,
	c_FACTURA.RECPOR as FACTURA_RecPor,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.mr as numeric( 15, 2 ) ) as FACTURA_MR,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.mr2 as numeric( 15, 2 ) ) as FACTURA_MR2,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.mr1 as numeric( 17, 4 ) ) as FACTURA_MR1,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.percepcion as numeric( 15, 2 ) ) as FACTURA_percepcion,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fimpuesto as numeric( 15, 2 ) ) as FACTURA_fImpuesto,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.gravamen as numeric( 15, 2 ) ) as FACTURA_gravamen,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.totrecarsi as numeric( 15, 4 ) ) as FACTURA_totrecarSI,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.trci as numeric( 15, 4 ) ) as FACTURA_TRCI,
	cast( c_factura.signomov*c_factura.cotiz*-1*c_factura.totdescsi as numeric( 15, 4 ) ) as FACTURA_totdescSI,
	cast( c_factura.signomov*c_factura.cotiz*-1*c_factura.tdci as numeric( 15, 4 ) ) as FACTURA_TDCI,
	c_FACTURA.FOBS as FACTURA_FObs,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.ftotal as numeric( 15, 2 ) ) as FACTURA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CLIENTE.CLVEND as CLIENTE_CLVend,
	C_CLIENTE.CLCALLE as CLIENTE_CLCalle,
	C_CLIENTE.CLCP as CLIENTE_CLCP,
	C_CLIENTE.CLCUIT as CLIENTE_CLCUIT,
	C_CLIENTE.CLDEPTO as CLIENTE_CLDEPTO,
	C_CLIENTE.CLEMAIL as CLIENTE_CLEMAIL,
	C_CLIENTE.CLFAX as CLIENTE_CLFAX,
	case when c_cliente.clfecha = '01/01/1900 00:00:00' then null else c_cliente.clfecha end as CLIENTE_CLFECHA,
	C_CLIENTE.CLLOC as CLIENTE_CLLOC,
	C_CLIENTE.CLNRODOC as CLIENTE_CLNRODOC,
	C_CLIENTE.CLNRO as CLIENTE_CLNro,
	C_CLIENTE.CLOBS as CLIENTE_CLOBS,
	C_CLIENTE.CLPAGEWEB as CLIENTE_CLPAGEWEB,
	C_CLIENTE.CLPAIS as CLIENTE_CLPAIS,
	C_CLIENTE.CLPISO as CLIENTE_ClPiso,
	C_CLIENTE.CLPRV as CLIENTE_CLPRV,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_CLIENTE.CLTLF as CLIENTE_CLTLF,
	C_CLIENTE.CLTIPODOC as CLIENTE_CLTIPODOC,
	C_CLIENTE.CLMOVIL as CLIENTE_CLMovil,
	C_CLIENTE.CLTOPECCTE as CLIENTE_CLTOPECCTE,
	C_CLIENTE.CLLISPREC as CLIENTE_CLLisPrec,
	C_CLIENTE.CLCLAS as CLIENTE_CLCLAS,
	C_CLIENTE.CLTIPCONV as CLIENTE_CLTIPCONV,
	C_CLIENTE.CLNROIIBB as CLIENTE_CLNROIIBB,
	C_CLIENTE.CLCO_DTO as CLIENTE_CLCO_DTO,
	C_CLIENTE.CLTRANS as CLIENTE_CLTRANS,
	C_CLIENTE.ESTADO as CLIENTE_Estado,
	C_CLIENTE.HIJOS as CLIENTE_Hijos,
	C_CLIENTE.SEXO as CLIENTE_Sexo,
	C_CLIENTE.GLOBALID as CLIENTE_globalid,
	C_CLIENTE.RUT as CLIENTE_RUT,
	C_CLIENTE.CLCODFANT as CLIENTE_CLCODFANT,
	C_CLIENTE.CLTIPOCLI as CLIENTE_CLTipoCli,
	C_CLIENTE.CLCATEGCLI as CLIENTE_CLCategCli,
	C_CLIENTE.CLCONDPAG as CLIENTE_CLCONDPAG,
	C_CLIENTE.CLSUJVINC as CLIENTE_CLSujVinc,
	C_CLIENTE.CLPERTIVA as CLIENTE_CLPERTIVA,
	C_CLIENTE.CLSITGAN as CLIENTE_CLSITGAN,
	C_CLIENTE.EXPERIVA as CLIENTE_EXPERIVA,
	C_CLIENTE.CLPERGAN as CLIENTE_CLPERGAN,
	C_CLIENTE.EXPERGAN as CLIENTE_EXPERGAN,
	C_CLIENTE.CODRECOM as CLIENTE_CODRECOM,
	C_CLIENTE.NOMRECOM as CLIENTE_NOMRECOM,
	C_CLIENTE.CLPRINOM as CLIENTE_CLPRINOM,
	C_CLIENTE.CLSEGNOM as CLIENTE_CLSEGNOM,
	C_CLIENTE.CLAPELL as CLIENTE_CLAPELL,
	case when c_cliente.vhastaiva = '01/01/1900 00:00:00' then null else c_cliente.vhastaiva end as CLIENTE_VHastaIva,
	case when c_cliente.vhastagan = '01/01/1900 00:00:00' then null else c_cliente.vhastagan end as CLIENTE_VHastaGan,
	C_CLIENTE.CLSIPRIB as CLIENTE_CLSIPRIB,
	C_CLIENTE.PORCENTC as CLIENTE_PorcenTC,
	C_CLIENTE.APLICATC as CLIENTE_AplicaTC,
	C_CLIENTE.INACTIVOFW as CLIENTE_InactivoFW,
	C_MOTIVODESCUENTOYDEVOLUCION64.TIPO as MOTIVODESCUENTOYDEVOLUCION64_Tipo,
	C_MOTIVODESCUENTOYDEVOLUCION64.OBS as MOTIVODESCUENTOYDEVOLUCION64_Obs,
	C_VENDEDOR9111.CLCP as VENDEDOR9111_CLCP,
	C_VENDEDOR9111.CLDIR as VENDEDOR9111_CLDIR,
	C_VENDEDOR9111.CLNRODOC as VENDEDOR9111_CLNRODOC,
	C_VENDEDOR9111.CLEMAIL as VENDEDOR9111_CLEMAIL,
	case when c_vendedor9111.clfing = '01/01/1900 00:00:00' then null else c_vendedor9111.clfing end as VENDEDOR9111_CLFING,
	case when c_vendedor9111.clfecha = '01/01/1900 00:00:00' then null else c_vendedor9111.clfecha end as VENDEDOR9111_CLFECHA,
	C_VENDEDOR9111.CLLOC as VENDEDOR9111_CLLOC,
	C_VENDEDOR9111.CLOBS as VENDEDOR9111_CLOBS,
	C_VENDEDOR9111.CLPRV as VENDEDOR9111_CLPRV,
	C_VENDEDOR9111.CLTLF as VENDEDOR9111_CLTLF,
	C_VENDEDOR9111.CLTIPODOC as VENDEDOR9111_CLTIPODOC,
	C_VENDEDOR9111.CLNUM as VENDEDOR9111_CLNUM,
	C_VENDEDOR9111.CLPISO as VENDEDOR9111_CLPISO,
	C_VENDEDOR9111.CLDEPTO as VENDEDOR9111_CLDEPTO,
	C_VENDEDOR9111.PPAIS as VENDEDOR9111_PPAIS,
	case when c_vendedor9111.clfegr = '01/01/1900 00:00:00' then null else c_vendedor9111.clfegr end as VENDEDOR9111_CLFEGR,
	C_VENDEDOR9111.CLTLFM as VENDEDOR9111_CLTLFM,
	C_VENDEDOR9111.CLAS as VENDEDOR9111_CLAS,
	C_VENDEDOR9111.CLDESC as VENDEDOR9111_CLDESC,
	C_VENDEDOR9111.INACTIVOFW as VENDEDOR9111_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	case when c_factura.faltafw = '01/01/1900 00:00:00' then null else c_factura.faltafw end as FACTURA_FAltaFW,
	c_FACTURA.HALTAFW as FACTURA_HAltaFW,
	c_FACTURA.BDALTAFW as FACTURA_BDALTAFW,
	c_FACTURA.BDMODIFW as FACTURA_BDMODIFW,
	c_FACTURA.ESTTRANS as FACTURA_ESTTRANS,
	case when c_factura.fecexpo = '01/01/1900 00:00:00' then null else c_factura.fecexpo end as FACTURA_FECEXPO,
	case when c_factura.fecimpo = '01/01/1900 00:00:00' then null else c_factura.fecimpo end as FACTURA_FECIMPO,
	case when c_factura.fmodifw = '01/01/1900 00:00:00' then null else c_factura.fmodifw end as FACTURA_FMODIFW,
	case when c_factura.fectrans = '01/01/1900 00:00:00' then null else c_factura.fectrans end as FACTURA_FECTRANS,
	c_FACTURA.HORAEXPO as FACTURA_HORAEXPO,
	c_FACTURA.HORAIMPO as FACTURA_HORAIMPO,
	c_FACTURA.HMODIFW as FACTURA_HMODIFW,
	c_FACTURA.SALTAFW as FACTURA_SALTAFW,
	c_FACTURA.SMODIFW as FACTURA_SMODIFW,
	c_FACTURA.UALTAFW as FACTURA_UALTAFW,
	c_FACTURA.UMODIFW as FACTURA_UMODIFW,
	c_FACTURA.VALTAFW as FACTURA_VALTAFW,
	c_FACTURA.VMODIFW as FACTURA_VMODIFW,
	c_FACTURA.ZADSFW as FACTURA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as FACTURA__SUCURSAL,
	c_FACTURA.DIRENTR as FACTURA_DirEntr,
	cast( @parametro1 as varchar( 16 ) ) as FACTURA_AplicaPromocionVirtual,
	cast( (select sum(ap.beneficio) from zoologic.promdet as ap where ap.codigo = c_factura.codigo) as numeric( 15, 2 ) ) as FACTURA_BeneficioPromoVirtual,
	cast( funciones.obtenernumerodecaedelcomprobante(c_factura.codigo) as varchar( 20 ) ) as FACTURA_CaeVirtual,
	cast( funciones.obtenerultimocomprobanteafectadooafectante(c_factura.codigo, 0) as varchar( 25 ) ) as FACTURA_UltimoAfectanteVirtual,
	cast( funciones.obtenerultimocomprobanteafectadooafectante(c_factura.codigo, 1) as varchar( 25 ) ) as FACTURA_UltimoAfectadoVirtual,

	--cast( @parametro2 as varchar( 16 ) ) as FACTURA_TipoDeEntregaVirtual,
	 case when c_factura.entregapos = 0 then 'Inmediata' else case when c_factura.entregapos = 1 then 'Posterior' else 
	 case when c_factura.entregapos = 2 then 'Inmediata' else 'Venta continua'end end end as FACTURA_TipoDeEntregaVirtual,

	c_FACTURA.DESPACHOS as FACTURA_Despachos,
	c_FACTURA.FACTTIPO as FACTURA_FACTTIPO,
	cast( 1 as numeric( 15, 2 ) ) as FACTURA_CantidadComprobVirtual,
	cast( c_factura.ftotal*c_factura.signomov as numeric( 15, 2 ) ) as FACTURA_MontoCantidadComprobVirtual,
	cast( c_factura.totalcant*c_factura.signomov as numeric( 16, 3 ) ) as FACTURA_UnidadesCantidadComprobVirtual,
	C_DATOSADICIONALESCOMPROBANTESA.CODCOMP as DATOSADICIONALESCOMPROBANTESA_CodComp,
	C_DATOSADICIONALESCOMPROBANTESA.SUSCRIBE as DATOSADICIONALESCOMPROBANTESA_Suscribe,
	C_DATOSADICIONALESCOMPROBANTESA.TIPODOC as DATOSADICIONALESCOMPROBANTESA_Tipodoc,
	C_DATOSADICIONALESCOMPROBANTESA.NRODOC as DATOSADICIONALESCOMPROBANTESA_NroDoc,
	C_DATOSADICIONALESCOMPROBANTESA.MOTIVO as DATOSADICIONALESCOMPROBANTESA_Motivo,
	C_MOTIVODATOSADICIONALESCOMPROBANTESA.DESCRIP as MOTIVODATOSADICIONALESCOMPROBANTESA_Descrip,
	cast( funciones.obtenerdescripciondocumentoafip(c_datosadicionalescomprobantesa.tipodoc) as varchar( 40 ) ) as DATOSADICIONALESCOMPROBANTESA_1_TipoDocumentoVirtual,
	cast( funciones.identificadordecomprobanteparalistado(c_factura.facttipo, c_factura.fletra, c_factura.fptoven, c_factura.fnumcomp) as varchar( 20 ) ) as FACTURA_ComprobanteVirtual,
	cast( funciones.identificadordecomprobanteparalistado(c_factura.tipocrela, c_factura.letrarela, c_factura.puntorela, c_factura.numerorela) as varchar( 25 ) ) as FACTURA_ComprobanteAsociado,
	cast( c_factura.signomov*c_factura.cotiz*(c_factura.fimpuesto+c_factura.percepcion+c_factura.gravamen) as numeric( 15, 2 ) ) as FACTURA_totimpue,
	cast( c_factura.signomov*c_factura.cotiz*(c_factura.fsubtot+c_factura.trci-c_factura.tdci) as numeric( 15, 2 ) ) as FACTURA_SubtotalDRConImpuestos,
	cast( c_factura.signomov*c_factura.cotiz*(c_factura.fsubton+c_factura.totrecarsi-c_factura.totdescsi) as numeric( 15, 2 ) ) as FACTURA_SubtotalDRSinImpuestos,
	c_FACTURA.FVEN as FACTURA_FVEN,
	C_CLIENTE.CLNOM as CLIENTE_CLNOM,
	C_MOTIVODESCUENTOYDEVOLUCION64.DESCRIP as MOTIVODESCUENTOYDEVOLUCION64_Descrip,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_LISTADEPRECIOS109.LPR_NOMBRE as LISTADEPRECIOS109_LPR_NOMBRE,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_VENDEDOR3.CLNOM as VENDEDOR3_CLNOM,
	C_PAISES18.PDES as PAISES18_pdes,
	C_PROVINCIA20.PRV_DES as PROVINCIA20_PRV_DES,
	C_CLIENTE.CLIVA as CLIENTE_CLIVA,
	C_LISTADEPRECIOS26.LPR_NOMBRE as LISTADEPRECIOS26_LPR_NOMBRE,
	C_CLASIFICACIONCLIENTE.CLADES as CLASIFICACIONCLIENTE_CLADES,
	C_DESCUENTO30.DES as DESCUENTO30_Des,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_NOMBREDEFANTASIA.NFCOD as NOMBREDEFANTASIA_NFCOD,
	C_TIPOCLIENTE.TCDES as TIPOCLIENTE_TCDES,
	C_CATEGORIACLIENTE.CGDES as CATEGORIACLIENTE_CGDes,
	C_CONDICIONDEPAGO.CLNOM as CONDICIONDEPAGO_CLNOM,
	C_IMPUESTO42.DESCRIP as IMPUESTO42_descrip,
	C_IMPUESTO45.DESCRIP as IMPUESTO45_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_PROVINCIA96.PRV_DES as PROVINCIA96_PRV_DES,
	C_PAISES102.PDES as PAISES102_pdes,
	C_CLASIFICACIONVENDEDOR.CLADES as CLASIFICACIONVENDEDOR_CLADES,
	C_DESCUENTO106.DES as DESCUENTO106_Des,
	C_VENDEDOR9111.CLNOM as VENDEDOR9111_CLNOM,
	C_CATEGORIACLIENTE.CGCOD as CATEGORIACLIENTE_CGCod,
	C_CLASIFICACIONCLIENTE.CLACOD as CLASIFICACIONCLIENTE_CLACOD,
	C_CLASIFICACIONVENDEDOR.CLACOD as CLASIFICACIONVENDEDOR_CLACOD,
	C_CLIENTE.CLCOD as CLIENTE_CLCOD,
	C_CONDICIONDEPAGO.CLCOD as CONDICIONDEPAGO_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DESCUENTO30.CODIGO as DESCUENTO30_codigo,
	C_DESCUENTO106.CODIGO as DESCUENTO106_codigo,
	C_IMPUESTO42.CODIGO as IMPUESTO42_codigo,
	C_IMPUESTO45.CODIGO as IMPUESTO45_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS26.LPR_NUMERO as LISTADEPRECIOS26_LPR_NUMERO,
	C_LISTADEPRECIOS109.LPR_NUMERO as LISTADEPRECIOS109_LPR_NUMERO,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_MOTIVODATOSADICIONALESCOMPROBANTESA.CODIGO as MOTIVODATOSADICIONALESCOMPROBANTESA_Codigo,
	C_MOTIVODESCUENTOYDEVOLUCION64.CODIGO as MOTIVODESCUENTOYDEVOLUCION64_Codigo,
	C_PAISES18.PCOD as PAISES18_pcod,
	C_PAISES102.PCOD as PAISES102_pcod,
	C_PROVINCIA20.PRV_COD as PROVINCIA20_PRV_COD,
	C_PROVINCIA96.PRV_COD as PROVINCIA96_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOCLIENTE.TCCOD as TIPOCLIENTE_TCCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_VENDEDOR3.CLCOD as VENDEDOR3_CLCOD,
	C_VENDEDOR9111.CLCOD as VENDEDOR9111_CLCOD
 from ZooLogic.COMPROBANTEV as c_FACTURA
 left join ZooLogic.AFIP3668 as C_DATOSADICIONALESCOMPROBANTESA on C_DATOSADICIONALESCOMPROBANTESA.CODCOMP = C_FACTURA.CODIGO and 0 = Funciones.empty( C_FACTURA.CODIGO )
 left join ZooLogic.CLI as C_CLIENTE on C_CLIENTE.CLCOD = C_FACTURA.FPERSON and 0 = Funciones.empty( C_FACTURA.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO on C_CONDICIONDEPAGO.CLCOD = C_CLIENTE.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_CLIENTE.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO30 on C_DESCUENTO30.CODIGO = C_CLIENTE.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO42 on C_IMPUESTO42.CODIGO = C_CLIENTE.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO45 on C_IMPUESTO45.CODIGO = C_CLIENTE.CLPERGAN and 0 = Funciones.empty( C_CLIENTE.CLPERGAN )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS26 on C_LISTADEPRECIOS26.LPR_NUMERO = C_CLIENTE.CLLISPREC and 0 = Funciones.empty( C_CLIENTE.CLLISPREC )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS109 on C_LISTADEPRECIOS109.LPR_NUMERO = C_FACTURA.CODLISTA and 0 = Funciones.empty( C_FACTURA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_FACTURA.MONEDA and 0 = Funciones.empty( C_FACTURA.MONEDA )
 left join ORGANIZACION.MOTADICA as C_MOTIVODATOSADICIONALESCOMPROBANTESA on C_MOTIVODATOSADICIONALESCOMPROBANTESA.CODIGO = C_DATOSADICIONALESCOMPROBANTESA.MOTIVO and 0 = Funciones.empty( C_DATOSADICIONALESCOMPROBANTESA.MOTIVO )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION64 on C_MOTIVODESCUENTOYDEVOLUCION64.CODIGO = C_FACTURA.MOTDESCDEV and 0 = Funciones.empty( C_FACTURA.MOTDESCDEV )
 left join ZooLogic.PAISES as C_PAISES18 on C_PAISES18.PCOD = C_CLIENTE.CLPAIS and 0 = Funciones.empty( C_CLIENTE.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA20 on C_PROVINCIA20.PRV_COD = C_CLIENTE.CLPRV and 0 = Funciones.empty( C_CLIENTE.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_CLIENTE.CLIVA and 0 = Funciones.empty( C_CLIENTE.CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE on C_TIPOCLIENTE.TCCOD = C_CLIENTE.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE.CLTIPOCLI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_CLIENTE.CLTRANS and 0 = Funciones.empty( C_CLIENTE.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR3 on C_VENDEDOR3.CLCOD = C_CLIENTE.CLVEND and 0 = Funciones.empty( C_CLIENTE.CLVEND )
 left join ZooLogic.VEN as C_VENDEDOR9111 on C_VENDEDOR9111.CLCOD = C_FACTURA.FVEN and 0 = Funciones.empty( C_FACTURA.FVEN )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA on C_NOMBREDEFANTASIA.NFCOD = C_CLIENTE.CLCODFANT and 0 = Funciones.empty( C_CLIENTE.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE on C_CATEGORIACLIENTE.CGCOD = C_CLIENTE.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE on C_CLASIFICACIONCLIENTE.CLACOD = C_CLIENTE.CLCLAS and 0 = Funciones.empty( C_CLIENTE.CLCLAS )
 left join ZooLogic.CLASVEND as C_CLASIFICACIONVENDEDOR on C_CLASIFICACIONVENDEDOR.CLACOD = C_VENDEDOR9111.CLAS and 0 = Funciones.empty( C_VENDEDOR9111.CLAS )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO106 on C_DESCUENTO106.CODIGO = C_VENDEDOR9111.CLDESC and 0 = Funciones.empty( C_VENDEDOR9111.CLDESC )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.PAISES as C_PAISES102 on C_PAISES102.PCOD = C_VENDEDOR9111.PPAIS and 0 = Funciones.empty( C_VENDEDOR9111.PPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA96 on C_PROVINCIA96.PRV_COD = C_VENDEDOR9111.CLPRV and 0 = Funciones.empty( C_VENDEDOR9111.CLPRV )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( ( case when @parametro1 = '' or @parametro1 = 'todos' then 1 else 0 end = 1 ) or (case when @parametro1 = 'sinpromo' then 0 else 1 end = coalesce( ( select top 1 1 from zoologic.promdet as ap where ap.codigo = c_factura.codigo ), 0) ) ) and 
	( ( case when @parametro2 = '' or @parametro2 = 'todos' then 0 else -1 end = 0 )
	 or ( case when @parametro2 = 'posterior' then 1 else -1 end = c_factura.entregapos ) 
	 or ( case when @parametro2 = 'inmediata' then c_factura.entregapos else -1 end in (0,2) )
	 or ( case when @Parametro2 = 'venta continua' then 3 else -1 end = c_factura.entregapos ) ) and
	--( ( @FACTURA_DESPACHOS_DESDE is null ) OR ( C_FACTURA.Despachos >= @FACTURA_DESPACHOS_DESDE ) ) and 
	--( ( @FACTURA_DESPACHOS_HASTA is null ) OR ( C_FACTURA.Despachos <= @FACTURA_DESPACHOS_HASTA ) ) and 
	( ( @FACTURA_DESPACHOS_DESDE is null ) OR (Funciones.Alltrim(c_factura.Despachos) LIKE '%' + Funciones.Alltrim(@FACTURA_DESPACHOS_DESDE) + '%') ) and
	( ( @DATOSADICIONALESCOMPROBANTESA_1_SUSCRIBE is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA.Suscribe = @DATOSADICIONALESCOMPROBANTESA_1_SUSCRIBE ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_DESDE is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA.Tipodoc >= @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_DESDE ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_HASTA is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA.Tipodoc <= @DATOSADICIONALESCOMPROBANTESA_1_TIPODOCUMENTO_HASTA ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_DESDE is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA.NroDoc >= @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_DESDE ) ) and 
	( ( @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_HASTA is null ) OR ( C_DATOSADICIONALESCOMPROBANTESA.NroDoc <= @DATOSADICIONALESCOMPROBANTESA_1_NRODOCUMENTO_HASTA ) ) and 
	( ( @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_DESDE is null ) OR ( C_MOTIVODATOSADICIONALESCOMPROBANTESA.Descrip >= @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_HASTA is null ) OR ( C_MOTIVODATOSADICIONALESCOMPROBANTESA.Descrip <= @MOTIVODATOSADICIONALESCOMPROBANTESA_9104_DESCRIPCION_HASTA ) ) and 
	( ( @FACTURA_VENDEDOR_DESDE is null ) OR ( c_FACTURA.FVEN >= @FACTURA_VENDEDOR_DESDE ) ) and 
	( ( @FACTURA_VENDEDOR_HASTA is null ) OR ( c_FACTURA.FVEN <= @FACTURA_VENDEDOR_HASTA ) ) and 
	( ( @FACTURA_CLIENTE_DESDE is null ) OR ( c_FACTURA.FPerson >= @FACTURA_CLIENTE_DESDE ) ) and 
	( ( @FACTURA_CLIENTE_HASTA is null ) OR ( c_FACTURA.FPerson <= @FACTURA_CLIENTE_HASTA ) ) and 
	( c_FACTURA.FACTTIPO in ( 1, 2, 3, 4, 5, 6, 27, 28, 29, 33, 35, 36, 47, 48, 49, 51, 52, 53, 54, 55, 56 ) ) and 
	( ( @FACTURA_TIPOCOMPROBANTE is null ) OR ( ( -2 = @FACTURA_TIPOCOMPROBANTE ) AND ( c_FACTURA.FACTTIPO in ( 2, 5, 6, 51, 52, 53 ) ) ) OR ( ( -3 = @FACTURA_TIPOCOMPROBANTE ) AND ( c_FACTURA.FACTTIPO in ( 1, 3, 4 ) ) ) OR ( ( -4 = @FACTURA_TIPOCOMPROBANTE ) AND ( c_FACTURA.FACTTIPO in ( 27, 28, 29, 33, 35, 36, 54, 55, 56 ) ) ) OR ( ( -5 = @FACTURA_TIPOCOMPROBANTE ) AND ( c_FACTURA.FACTTIPO in ( 47, 48, 49 ) ) ) OR ( c_FACTURA.FACTTIPO = @FACTURA_TIPOCOMPROBANTE ) ) and 
	( ( @FACTURA_ANULADO is null ) OR ( c_FACTURA.Anulado = @FACTURA_ANULADO ) ) and 
	( ( @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE is null ) OR ( c_FACTURA.MotDescDev >= @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE ) ) and 
	( ( @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA is null ) OR ( c_FACTURA.MotDescDev <= @FACTURA_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA ) ) and 
	( ( @FACTURA_NROOPECOMMERCE_DESDE is null ) OR ( c_FACTURA.OPEcomm >= @FACTURA_NROOPECOMMERCE_DESDE ) ) and 
	( ( @FACTURA_NROOPECOMMERCE_HASTA is null ) OR ( c_FACTURA.OPEcomm <= @FACTURA_NROOPECOMMERCE_HASTA ) ) and 
	( ( @FACTURA_CLIENTEDESCRIPCION_DESDE is null ) OR ( c_FACTURA.FCLIENTE >= @FACTURA_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @FACTURA_CLIENTEDESCRIPCION_HASTA is null ) OR ( c_FACTURA.FCLIENTE <= @FACTURA_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @FACTURA_MONEDACOMPROBANTE_DESDE is null ) OR ( c_FACTURA.Moneda >= @FACTURA_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURA_MONEDACOMPROBANTE_HASTA is null ) OR ( c_FACTURA.Moneda <= @FACTURA_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @FACTURA_LISTADEPRECIOS_DESDE is null ) OR ( c_FACTURA.CodLista >= @FACTURA_LISTADEPRECIOS_DESDE ) ) and 
	( ( @FACTURA_LISTADEPRECIOS_HASTA is null ) OR ( c_FACTURA.CodLista <= @FACTURA_LISTADEPRECIOS_HASTA ) ) and 
	( ( @FACTURA_EMAIL_DESDE is null ) OR ( c_FACTURA.Email >= @FACTURA_EMAIL_DESDE ) ) and 
	( ( @FACTURA_EMAIL_HASTA is null ) OR ( c_FACTURA.Email <= @FACTURA_EMAIL_HASTA ) ) and 
	( ( @FACTURA_LETRA_DESDE is null ) OR ( c_FACTURA.FLETRA >= @FACTURA_LETRA_DESDE ) ) and 
	( ( @FACTURA_LETRA_HASTA is null ) OR ( c_FACTURA.FLETRA <= @FACTURA_LETRA_HASTA ) ) and 
	( ( @FACTURA_PUNTODEVENTA_DESDE is null ) OR ( c_FACTURA.FPTOVEN >= @FACTURA_PUNTODEVENTA_DESDE ) ) and 
	( ( @FACTURA_PUNTODEVENTA_HASTA is null ) OR ( c_FACTURA.FPTOVEN <= @FACTURA_PUNTODEVENTA_HASTA ) ) and 
	( ( @FACTURA_NUMERO_DESDE is null ) OR ( c_FACTURA.FNUMCOMP >= @FACTURA_NUMERO_DESDE ) ) and 
	( ( @FACTURA_NUMERO_HASTA is null ) OR ( c_FACTURA.FNUMCOMP <= @FACTURA_NUMERO_HASTA ) ) and 
	( ( @FACTURA_FECHA_DESDE is null ) OR ( c_FACTURA.FFCH >= @FACTURA_FECHA_DESDE ) ) and 
	( ( @FACTURA_FECHA_HASTA is null ) OR ( c_FACTURA.FFCH <= @FACTURA_FECHA_HASTA ) ) and 
	( ( @FACTURA_COTIZACION_DESDE is null ) OR ( c_FACTURA.Cotiz >= @FACTURA_COTIZACION_DESDE ) ) and 
	( ( @FACTURA_COTIZACION_HASTA is null ) OR ( c_FACTURA.Cotiz <= @FACTURA_COTIZACION_HASTA ) ) and 
	( ( @FACTURA_PORCENTAJEDESCUENTO_DESDE is null ) OR ( c_FACTURA.FPODES >= @FACTURA_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @FACTURA_PORCENTAJEDESCUENTO_HASTA is null ) OR ( c_FACTURA.FPODES <= @FACTURA_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @FACTURA_RECARGOPORCENTAJE_DESDE is null ) OR ( c_FACTURA.RecPor >= @FACTURA_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @FACTURA_RECARGOPORCENTAJE_HASTA is null ) OR ( c_FACTURA.RecPor <= @FACTURA_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE.CLNOM >= @CLIENTE_2_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE.CLNOM <= @CLIENTE_2_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION64.Descrip >= @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION64.Descrip <= @MOTIVODESCUENTOYDEVOLUCION_64_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA ) ) and 
	( ( @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_108_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS109.LPR_NOMBRE >= @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS109.LPR_NOMBRE <= @LISTADEPRECIOS_109_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9250_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9249_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9249_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9249_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9249_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9248_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR3.CLNOM >= @VENDEDOR_3_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR3.CLNOM <= @VENDEDOR_3_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES18.pdes >= @PAISES_18_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_18_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES18.pdes <= @PAISES_18_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA20.PRV_DES >= @PROVINCIA_20_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA20.PRV_DES <= @PROVINCIA_20_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS26.LPR_NOMBRE >= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS26.LPR_NOMBRE <= @LISTADEPRECIOS_26_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES >= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES <= @CLASIFICACIONCLIENTE_27_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO30.Des >= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO30.Des <= @DESCUENTO_30_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_31_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA.NFCOD >= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA.NFCOD <= @NOMBREDEFANTASIA_37_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE.TCDES >= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE.TCDES <= @TIPOCLIENTE_38_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE.CGDes >= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE.CGDes <= @CATEGORIACLIENTE_39_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO.CLNOM >= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO.CLNOM <= @CONDICIONDEPAGO_40_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO42.descrip >= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO42.descrip <= @IMPUESTO_42_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO45.descrip >= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO45.descrip <= @IMPUESTO_45_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_54_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_96_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA96.PRV_DES >= @PROVINCIA_96_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_96_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA96.PRV_DES <= @PROVINCIA_96_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_102_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES102.pdes >= @PAISES_102_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_102_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES102.pdes <= @PAISES_102_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONVENDEDOR.CLADES >= @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONVENDEDOR.CLADES <= @CLASIFICACIONVENDEDOR_105_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO106.Des >= @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO106.Des <= @DESCUENTO_106_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_9111_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR9111.CLNOM >= @VENDEDOR_9111_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_9111_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR9111.CLNOM <= @VENDEDOR_9111_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @SUCURSAL_9245_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9245_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9245_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9245_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9245_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9245_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9245_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9245_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9245_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9245_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9245_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9245_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9245_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9245_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9245_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9245_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_2_VENDEDOR_DESDE is null ) OR ( C_CLIENTE.CLVend >= @CLIENTE_2_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_2_VENDEDOR_HASTA is null ) OR ( C_CLIENTE.CLVend <= @CLIENTE_2_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_2_CALLE_DESDE is null ) OR ( C_CLIENTE.CLCalle >= @CLIENTE_2_CALLE_DESDE ) ) and 
	( ( @CLIENTE_2_CALLE_HASTA is null ) OR ( C_CLIENTE.CLCalle <= @CLIENTE_2_CALLE_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE.CLCP >= @CLIENTE_2_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE.CLCP <= @CLIENTE_2_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_2_CUIT_DESDE is null ) OR ( C_CLIENTE.CLCUIT >= @CLIENTE_2_CUIT_DESDE ) ) and 
	( ( @CLIENTE_2_CUIT_HASTA is null ) OR ( C_CLIENTE.CLCUIT <= @CLIENTE_2_CUIT_HASTA ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE.CLDEPTO >= @CLIENTE_2_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE.CLDEPTO <= @CLIENTE_2_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_EMAIL_DESDE is null ) OR ( C_CLIENTE.CLEMAIL >= @CLIENTE_2_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_2_EMAIL_HASTA is null ) OR ( C_CLIENTE.CLEMAIL <= @CLIENTE_2_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_2_FAX_DESDE is null ) OR ( C_CLIENTE.CLFAX >= @CLIENTE_2_FAX_DESDE ) ) and 
	( ( @CLIENTE_2_FAX_HASTA is null ) OR ( C_CLIENTE.CLFAX <= @CLIENTE_2_FAX_HASTA ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE.CLFECHA >= @CLIENTE_2_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_2_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE.CLFECHA <= @CLIENTE_2_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_2_IMAGEN_DESDE is null ) OR ( C_CLIENTE.CIMAGEN >= @CLIENTE_2_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_2_IMAGEN_HASTA is null ) OR ( C_CLIENTE.CIMAGEN <= @CLIENTE_2_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE.CLLOC >= @CLIENTE_2_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_2_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE.CLLOC <= @CLIENTE_2_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLNRODOC >= @CLIENTE_2_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLNRODOC <= @CLIENTE_2_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_NUMERO_DESDE is null ) OR ( C_CLIENTE.CLNro >= @CLIENTE_2_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_2_NUMERO_HASTA is null ) OR ( C_CLIENTE.CLNro <= @CLIENTE_2_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE.CLPAGEWEB >= @CLIENTE_2_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_2_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE.CLPAGEWEB <= @CLIENTE_2_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_2_PAIS_DESDE is null ) OR ( C_CLIENTE.CLPAIS >= @CLIENTE_2_PAIS_DESDE ) ) and 
	( ( @CLIENTE_2_PAIS_HASTA is null ) OR ( C_CLIENTE.CLPAIS <= @CLIENTE_2_PAIS_HASTA ) ) and 
	( ( @CLIENTE_2_PISO_DESDE is null ) OR ( C_CLIENTE.ClPiso >= @CLIENTE_2_PISO_DESDE ) ) and 
	( ( @CLIENTE_2_PISO_HASTA is null ) OR ( C_CLIENTE.ClPiso <= @CLIENTE_2_PISO_HASTA ) ) and 
	( ( @CLIENTE_2_PROVINCIA_DESDE is null ) OR ( C_CLIENTE.CLPRV >= @CLIENTE_2_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_2_PROVINCIA_HASTA is null ) OR ( C_CLIENTE.CLPRV <= @CLIENTE_2_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_21_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_2_TELEFONO_DESDE is null ) OR ( C_CLIENTE.CLTLF >= @CLIENTE_2_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_2_TELEFONO_HASTA is null ) OR ( C_CLIENTE.CLTLF <= @CLIENTE_2_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLTIPODOC >= @CLIENTE_2_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLTIPODOC <= @CLIENTE_2_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_2_MOVIL_DESDE is null ) OR ( C_CLIENTE.CLMovil >= @CLIENTE_2_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_2_MOVIL_HASTA is null ) OR ( C_CLIENTE.CLMovil <= @CLIENTE_2_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE.CLTOPECCTE >= @CLIENTE_2_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_2_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE.CLTOPECCTE <= @CLIENTE_2_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE.CLLisPrec >= @CLIENTE_2_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_2_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE.CLLisPrec <= @CLIENTE_2_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE.CLCLAS >= @CLIENTE_2_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_2_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE.CLCLAS <= @CLIENTE_2_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE.CLTIPCONV >= @CLIENTE_2_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE.CLTIPCONV <= @CLIENTE_2_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_2_NROIIBB_DESDE is null ) OR ( C_CLIENTE.CLNROIIBB >= @CLIENTE_2_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_2_NROIIBB_HASTA is null ) OR ( C_CLIENTE.CLNROIIBB <= @CLIENTE_2_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE.CLCO_DTO >= @CLIENTE_2_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_2_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE.CLCO_DTO <= @CLIENTE_2_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE.CLTRANS >= @CLIENTE_2_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_2_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE.CLTRANS <= @CLIENTE_2_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_2_ESTADOCIVIL is null ) OR ( C_CLIENTE.Estado = @CLIENTE_2_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_2_HIJOS_DESDE is null ) OR ( C_CLIENTE.Hijos >= @CLIENTE_2_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_2_HIJOS_HASTA is null ) OR ( C_CLIENTE.Hijos <= @CLIENTE_2_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_2_SEXO is null ) OR ( C_CLIENTE.Sexo = @CLIENTE_2_SEXO ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE.globalid >= @CLIENTE_2_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_2_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE.globalid <= @CLIENTE_2_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_2_RUT_DESDE is null ) OR ( C_CLIENTE.RUT >= @CLIENTE_2_RUT_DESDE ) ) and 
	( ( @CLIENTE_2_RUT_HASTA is null ) OR ( C_CLIENTE.RUT <= @CLIENTE_2_RUT_HASTA ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE.CLCODFANT >= @CLIENTE_2_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_2_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE.CLCODFANT <= @CLIENTE_2_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_2_TIPOCLI_DESDE is null ) OR ( C_CLIENTE.CLTipoCli >= @CLIENTE_2_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_2_TIPOCLI_HASTA is null ) OR ( C_CLIENTE.CLTipoCli <= @CLIENTE_2_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CATEGCLI_DESDE is null ) OR ( C_CLIENTE.CLCategCli >= @CLIENTE_2_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_2_CATEGCLI_HASTA is null ) OR ( C_CLIENTE.CLCategCli <= @CLIENTE_2_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE.CLCONDPAG >= @CLIENTE_2_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_2_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE.CLCONDPAG <= @CLIENTE_2_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_2_SUJETOVINCULADO is null ) OR ( C_CLIENTE.CLSujVinc = @CLIENTE_2_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE.CLPERTIVA >= @CLIENTE_2_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE.CLPERTIVA <= @CLIENTE_2_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_2_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE.CLSITGAN = @CLIENTE_2_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE.EXPERIVA = @CLIENTE_2_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE.CLPERGAN >= @CLIENTE_2_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE.CLPERGAN <= @CLIENTE_2_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE.EXPERGAN = @CLIENTE_2_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.CODRECOM >= @CLIENTE_2_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.CODRECOM <= @CLIENTE_2_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.NOMRECOM >= @CLIENTE_2_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_2_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.NOMRECOM <= @CLIENTE_2_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE.CLPRINOM >= @CLIENTE_2_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE.CLPRINOM <= @CLIENTE_2_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE.CLSEGNOM >= @CLIENTE_2_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_2_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE.CLSEGNOM <= @CLIENTE_2_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_2_APELLIDO_DESDE is null ) OR ( C_CLIENTE.CLAPELL >= @CLIENTE_2_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_2_APELLIDO_HASTA is null ) OR ( C_CLIENTE.CLAPELL <= @CLIENTE_2_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE.VHastaIva >= @CLIENTE_2_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE.VHastaIva <= @CLIENTE_2_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE.VHastaGan >= @CLIENTE_2_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_2_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE.VHastaGan <= @CLIENTE_2_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE.CLSIPRIB >= @CLIENTE_2_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_2_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE.CLSIPRIB <= @CLIENTE_2_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE.PorcenTC >= @CLIENTE_2_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_2_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE.PorcenTC <= @CLIENTE_2_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_2_TASACEROAPLICA is null ) OR ( C_CLIENTE.AplicaTC = @CLIENTE_2_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_2_INACTIVOFW is null ) OR ( C_CLIENTE.InactivoFW = @CLIENTE_2_INACTIVOFW ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_64_TIPO is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION64.Tipo = @MOTIVODESCUENTOYDEVOLUCION_64_TIPO ) ) and 
	( ( @VENDEDOR_9111_CODIGOPOSTAL_DESDE is null ) OR ( C_VENDEDOR9111.CLCP >= @VENDEDOR_9111_CODIGOPOSTAL_DESDE ) ) and 
	( ( @VENDEDOR_9111_CODIGOPOSTAL_HASTA is null ) OR ( C_VENDEDOR9111.CLCP <= @VENDEDOR_9111_CODIGOPOSTAL_HASTA ) ) and 
	( ( @VENDEDOR_9111_CALLE_DESDE is null ) OR ( C_VENDEDOR9111.CLDIR >= @VENDEDOR_9111_CALLE_DESDE ) ) and 
	( ( @VENDEDOR_9111_CALLE_HASTA is null ) OR ( C_VENDEDOR9111.CLDIR <= @VENDEDOR_9111_CALLE_HASTA ) ) and 
	( ( @VENDEDOR_9111_NRODOCUMENTO_DESDE is null ) OR ( C_VENDEDOR9111.CLNRODOC >= @VENDEDOR_9111_NRODOCUMENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_NRODOCUMENTO_HASTA is null ) OR ( C_VENDEDOR9111.CLNRODOC <= @VENDEDOR_9111_NRODOCUMENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_EMAIL_DESDE is null ) OR ( C_VENDEDOR9111.CLEMAIL >= @VENDEDOR_9111_EMAIL_DESDE ) ) and 
	( ( @VENDEDOR_9111_EMAIL_HASTA is null ) OR ( C_VENDEDOR9111.CLEMAIL <= @VENDEDOR_9111_EMAIL_HASTA ) ) and 
	( ( @VENDEDOR_9111_FECHAINGRESO_DESDE is null ) OR ( C_VENDEDOR9111.CLFING >= @VENDEDOR_9111_FECHAINGRESO_DESDE ) ) and 
	( ( @VENDEDOR_9111_FECHAINGRESO_HASTA is null ) OR ( C_VENDEDOR9111.CLFING <= @VENDEDOR_9111_FECHAINGRESO_HASTA ) ) and 
	( ( @VENDEDOR_9111_FECHANACIMIENTO_DESDE is null ) OR ( C_VENDEDOR9111.CLFECHA >= @VENDEDOR_9111_FECHANACIMIENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_FECHANACIMIENTO_HASTA is null ) OR ( C_VENDEDOR9111.CLFECHA <= @VENDEDOR_9111_FECHANACIMIENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_IMAGEN_DESDE is null ) OR ( C_VENDEDOR9111.CIMAGEN >= @VENDEDOR_9111_IMAGEN_DESDE ) ) and 
	( ( @VENDEDOR_9111_IMAGEN_HASTA is null ) OR ( C_VENDEDOR9111.CIMAGEN <= @VENDEDOR_9111_IMAGEN_HASTA ) ) and 
	( ( @VENDEDOR_9111_LOCALIDAD_DESDE is null ) OR ( C_VENDEDOR9111.CLLOC >= @VENDEDOR_9111_LOCALIDAD_DESDE ) ) and 
	( ( @VENDEDOR_9111_LOCALIDAD_HASTA is null ) OR ( C_VENDEDOR9111.CLLOC <= @VENDEDOR_9111_LOCALIDAD_HASTA ) ) and 
	( ( @VENDEDOR_9111_PROVINCIA_DESDE is null ) OR ( C_VENDEDOR9111.CLPRV >= @VENDEDOR_9111_PROVINCIA_DESDE ) ) and 
	( ( @VENDEDOR_9111_PROVINCIA_HASTA is null ) OR ( C_VENDEDOR9111.CLPRV <= @VENDEDOR_9111_PROVINCIA_HASTA ) ) and 
	( ( @VENDEDOR_9111_TELEFONO_DESDE is null ) OR ( C_VENDEDOR9111.CLTLF >= @VENDEDOR_9111_TELEFONO_DESDE ) ) and 
	( ( @VENDEDOR_9111_TELEFONO_HASTA is null ) OR ( C_VENDEDOR9111.CLTLF <= @VENDEDOR_9111_TELEFONO_HASTA ) ) and 
	( ( @VENDEDOR_9111_TIPODOCUMENTO_DESDE is null ) OR ( C_VENDEDOR9111.CLTIPODOC >= @VENDEDOR_9111_TIPODOCUMENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_TIPODOCUMENTO_HASTA is null ) OR ( C_VENDEDOR9111.CLTIPODOC <= @VENDEDOR_9111_TIPODOCUMENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_NUMERO_DESDE is null ) OR ( C_VENDEDOR9111.CLNUM >= @VENDEDOR_9111_NUMERO_DESDE ) ) and 
	( ( @VENDEDOR_9111_NUMERO_HASTA is null ) OR ( C_VENDEDOR9111.CLNUM <= @VENDEDOR_9111_NUMERO_HASTA ) ) and 
	( ( @VENDEDOR_9111_PISO_DESDE is null ) OR ( C_VENDEDOR9111.CLPISO >= @VENDEDOR_9111_PISO_DESDE ) ) and 
	( ( @VENDEDOR_9111_PISO_HASTA is null ) OR ( C_VENDEDOR9111.CLPISO <= @VENDEDOR_9111_PISO_HASTA ) ) and 
	( ( @VENDEDOR_9111_DEPARTAMENTO_DESDE is null ) OR ( C_VENDEDOR9111.CLDEPTO >= @VENDEDOR_9111_DEPARTAMENTO_DESDE ) ) and 
	( ( @VENDEDOR_9111_DEPARTAMENTO_HASTA is null ) OR ( C_VENDEDOR9111.CLDEPTO <= @VENDEDOR_9111_DEPARTAMENTO_HASTA ) ) and 
	( ( @VENDEDOR_9111_PAIS_DESDE is null ) OR ( C_VENDEDOR9111.PPAIS >= @VENDEDOR_9111_PAIS_DESDE ) ) and 
	( ( @VENDEDOR_9111_PAIS_HASTA is null ) OR ( C_VENDEDOR9111.PPAIS <= @VENDEDOR_9111_PAIS_HASTA ) ) and 
	( ( @VENDEDOR_9111_FECHAEGRESO_DESDE is null ) OR ( C_VENDEDOR9111.CLFEGR >= @VENDEDOR_9111_FECHAEGRESO_DESDE ) ) and 
	( ( @VENDEDOR_9111_FECHAEGRESO_HASTA is null ) OR ( C_VENDEDOR9111.CLFEGR <= @VENDEDOR_9111_FECHAEGRESO_HASTA ) ) and 
	( ( @VENDEDOR_9111_MOVIL_DESDE is null ) OR ( C_VENDEDOR9111.CLTLFM >= @VENDEDOR_9111_MOVIL_DESDE ) ) and 
	( ( @VENDEDOR_9111_MOVIL_HASTA is null ) OR ( C_VENDEDOR9111.CLTLFM <= @VENDEDOR_9111_MOVIL_HASTA ) ) and 
	( ( @VENDEDOR_9111_CLASIFICACION_DESDE is null ) OR ( C_VENDEDOR9111.CLAS >= @VENDEDOR_9111_CLASIFICACION_DESDE ) ) and 
	( ( @VENDEDOR_9111_CLASIFICACION_HASTA is null ) OR ( C_VENDEDOR9111.CLAS <= @VENDEDOR_9111_CLASIFICACION_HASTA ) ) and 
	( ( @VENDEDOR_9111_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_VENDEDOR9111.CLDESC >= @VENDEDOR_9111_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @VENDEDOR_9111_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_VENDEDOR9111.CLDESC <= @VENDEDOR_9111_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @VENDEDOR_9111_INACTIVOFW is null ) OR ( C_VENDEDOR9111.InactivoFW = @VENDEDOR_9111_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9245_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9245_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9245_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9245_CODIGO_HASTA ) ) and 
	( ( @FACTURA_FECHAALTAFW_DESDE is null ) OR ( c_FACTURA.FAltaFW >= @FACTURA_FECHAALTAFW_DESDE ) ) and 
	( ( @FACTURA_FECHAALTAFW_HASTA is null ) OR ( c_FACTURA.FAltaFW <= @FACTURA_FECHAALTAFW_HASTA ) ) and 
	( ( @FACTURA_HORAALTAFW_DESDE is null ) OR ( c_FACTURA.HAltaFW >= @FACTURA_HORAALTAFW_DESDE ) ) and 
	( ( @FACTURA_HORAALTAFW_HASTA is null ) OR ( c_FACTURA.HAltaFW <= @FACTURA_HORAALTAFW_HASTA ) ) and 
	( ( @FACTURA_BASEDEDATOSALTAFW_DESDE is null ) OR ( c_FACTURA.BDALTAFW >= @FACTURA_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @FACTURA_BASEDEDATOSALTAFW_HASTA is null ) OR ( c_FACTURA.BDALTAFW <= @FACTURA_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURA_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( c_FACTURA.BDMODIFW >= @FACTURA_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( c_FACTURA.BDMODIFW <= @FACTURA_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_ESTADOTRANSFERENCIA_DESDE is null ) OR ( c_FACTURA.ESTTRANS >= @FACTURA_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURA_ESTADOTRANSFERENCIA_HASTA is null ) OR ( c_FACTURA.ESTTRANS <= @FACTURA_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURA_FECHAEXPO_DESDE is null ) OR ( c_FACTURA.FECEXPO >= @FACTURA_FECHAEXPO_DESDE ) ) and 
	( ( @FACTURA_FECHAEXPO_HASTA is null ) OR ( c_FACTURA.FECEXPO <= @FACTURA_FECHAEXPO_HASTA ) ) and 
	( ( @FACTURA_FECHAIMPO_DESDE is null ) OR ( c_FACTURA.FECIMPO >= @FACTURA_FECHAIMPO_DESDE ) ) and 
	( ( @FACTURA_FECHAIMPO_HASTA is null ) OR ( c_FACTURA.FECIMPO <= @FACTURA_FECHAIMPO_HASTA ) ) and 
	( ( @FACTURA_FECHAMODIFICACIONFW_DESDE is null ) OR ( c_FACTURA.FMODIFW >= @FACTURA_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_FECHAMODIFICACIONFW_HASTA is null ) OR ( c_FACTURA.FMODIFW <= @FACTURA_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_FECHATRANSFERENCIA_DESDE is null ) OR ( c_FACTURA.FECTRANS >= @FACTURA_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURA_FECHATRANSFERENCIA_HASTA is null ) OR ( c_FACTURA.FECTRANS <= @FACTURA_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURA_HORAEXPO_DESDE is null ) OR ( c_FACTURA.HORAEXPO >= @FACTURA_HORAEXPO_DESDE ) ) and 
	( ( @FACTURA_HORAEXPO_HASTA is null ) OR ( c_FACTURA.HORAEXPO <= @FACTURA_HORAEXPO_HASTA ) ) and 
	( ( @FACTURA_HORAIMPO_DESDE is null ) OR ( c_FACTURA.HORAIMPO >= @FACTURA_HORAIMPO_DESDE ) ) and 
	( ( @FACTURA_HORAIMPO_HASTA is null ) OR ( c_FACTURA.HORAIMPO <= @FACTURA_HORAIMPO_HASTA ) ) and 
	( ( @FACTURA_HORAMODIFICACIONFW_DESDE is null ) OR ( c_FACTURA.HMODIFW >= @FACTURA_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_HORAMODIFICACIONFW_HASTA is null ) OR ( c_FACTURA.HMODIFW <= @FACTURA_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_SERIEALTAFW_DESDE is null ) OR ( c_FACTURA.SALTAFW >= @FACTURA_SERIEALTAFW_DESDE ) ) and 
	( ( @FACTURA_SERIEALTAFW_HASTA is null ) OR ( c_FACTURA.SALTAFW <= @FACTURA_SERIEALTAFW_HASTA ) ) and 
	( ( @FACTURA_SERIEMODIFICACIONFW_DESDE is null ) OR ( c_FACTURA.SMODIFW >= @FACTURA_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_SERIEMODIFICACIONFW_HASTA is null ) OR ( c_FACTURA.SMODIFW <= @FACTURA_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_USUARIOALTAFW_DESDE is null ) OR ( c_FACTURA.UALTAFW >= @FACTURA_USUARIOALTAFW_DESDE ) ) and 
	( ( @FACTURA_USUARIOALTAFW_HASTA is null ) OR ( c_FACTURA.UALTAFW <= @FACTURA_USUARIOALTAFW_HASTA ) ) and 
	( ( @FACTURA_USUARIOMODIFICACIONFW_DESDE is null ) OR ( c_FACTURA.UMODIFW >= @FACTURA_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_USUARIOMODIFICACIONFW_HASTA is null ) OR ( c_FACTURA.UMODIFW <= @FACTURA_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_VERSIONALTAFW_DESDE is null ) OR ( c_FACTURA.VALTAFW >= @FACTURA_VERSIONALTAFW_DESDE ) ) and 
	( ( @FACTURA_VERSIONALTAFW_HASTA is null ) OR ( c_FACTURA.VALTAFW <= @FACTURA_VERSIONALTAFW_HASTA ) ) and 
	( ( @FACTURA_VERSIONMODIFICACIONFW_DESDE is null ) OR ( c_FACTURA.VMODIFW >= @FACTURA_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_VERSIONMODIFICACIONFW_HASTA is null ) OR ( c_FACTURA.VMODIFW <= @FACTURA_VERSIONMODIFICACIONFW_HASTA ) )

)