IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_COMPROBANTEDERETENCIONES_ITEMCDRIMPUESTOSEIVA_ITEMCDRIMPUESTOS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_COMPROBANTEDERETENCIONES_ITEMCDRIMPUESTOSEIVA_ITEMCDRIMPUESTOS];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_COMPROBANTEDERETENCIONES_ITEMCDRIMPUESTOSEIVA_ITEMCDRIMPUESTOS]
( @BaseDeDatos varchar(8),
	@ITEMCDRIMPUESTOS_CODIMP_DESDE varchar(10),
	@ITEMCDRIMPUESTOS_CODIMP_HASTA varchar(10),
	@IMPUESTO_8000_TIPO_DESDE varchar(10),
	@IMPUESTO_8000_TIPO_HASTA varchar(10),
	@IMPUESTO_8000_APLICACION varchar(10),
	@COMPROBANTEDERETENCIONES_1_PROVEEDOR_DESDE varchar(10),
	@COMPROBANTEDERETENCIONES_1_PROVEEDOR_HASTA varchar(10),
	@PROVEEDOR_9000_CUIT_DESDE varchar(15),
	@PROVEEDOR_9000_CUIT_HASTA varchar(15),
	@ITEMCDRIMPUESTOS_MONTO_DESDE numeric(15, 2),
	@ITEMCDRIMPUESTOS_MONTO_HASTA numeric(15, 2),
	@ITEMCDRIMPUESTOS_CONVENIOMULTILATERAL_DESDE varchar(10),
	@ITEMCDRIMPUESTOS_CONVENIOMULTILATERAL_HASTA varchar(10),
	@ITEMCDRIMPUESTOS_PORCENTAJEDECONVENIO_DESDE numeric(6, 2),
	@ITEMCDRIMPUESTOS_PORCENTAJEDECONVENIO_HASTA numeric(6, 2),
	@ITEMCDRIMPUESTOS_PORCENTAJEDEBASE_DESDE numeric(6, 2),
	@ITEMCDRIMPUESTOS_PORCENTAJEDEBASE_HASTA numeric(6, 2),
	@ITEMCDRIMPUESTOS_MONTOBASE_DESDE numeric(15, 2),
	@ITEMCDRIMPUESTOS_MONTOBASE_HASTA numeric(15, 2),
	@ITEMCDRIMPUESTOS_BASEDECALCULO_DESDE varchar(10),
	@ITEMCDRIMPUESTOS_BASEDECALCULO_HASTA varchar(10),
	@ITEMCDRIMPUESTOS_REGIMENIMPOSITIVO_DESDE varchar(5),
	@ITEMCDRIMPUESTOS_REGIMENIMPOSITIVO_HASTA varchar(5),
	@ITEMCDRIMPUESTOS_MINIMO_DESDE numeric(12, 2),
	@ITEMCDRIMPUESTOS_MINIMO_HASTA numeric(12, 2),
	@ITEMCDRIMPUESTOS_MINIMONOIMP_DESDE numeric(15, 2),
	@ITEMCDRIMPUESTOS_MINIMONOIMP_HASTA numeric(15, 2),
	@ITEMCDRIMPUESTOS_MONTOCOMPROBANTEORIGEN_DESDE numeric(15, 2),
	@ITEMCDRIMPUESTOS_MONTOCOMPROBANTEORIGEN_HASTA numeric(15, 2),
	@ITEMCDRIMPUESTOS_REGIMENIMPOSITIVODESCRIPCION_DESDE varchar(100),
	@ITEMCDRIMPUESTOS_REGIMENIMPOSITIVODESCRIPCION_HASTA varchar(100),
	@ITEMCDRIMPUESTOS_CERTIFICADOSIRE_DESDE varchar(25),
	@ITEMCDRIMPUESTOS_CERTIFICADOSIRE_HASTA varchar(25),
	@ITEMCDRIMPUESTOS_CODSEGURIDADSIRE_DESDE varchar(4),
	@ITEMCDRIMPUESTOS_CODSEGURIDADSIRE_HASTA varchar(4),
	@ITEMCDRIMPUESTOS_JURISDICCIONDESCRIPCION_DESDE varchar(50),
	@ITEMCDRIMPUESTOS_JURISDICCIONDESCRIPCION_HASTA varchar(50),
	@ITEMCDRIMPUESTOS_RESOLUCION_DESDE varchar(60),
	@ITEMCDRIMPUESTOS_RESOLUCION_HASTA varchar(60),
	@ITEMCDRIMPUESTOS_MINIMONOIMPONIBLE_DESDE numeric(15, 2),
	@ITEMCDRIMPUESTOS_MINIMONOIMPONIBLE_HASTA numeric(15, 2),
	@ITEMCDRIMPUESTOS_PORCENTAJE_DESDE numeric(6, 2),
	@ITEMCDRIMPUESTOS_PORCENTAJE_HASTA numeric(6, 2),
	@COMPROBANTEDERETENCIONES_1_CODIGO_DESDE varchar(38),
	@COMPROBANTEDERETENCIONES_1_CODIGO_HASTA varchar(38),
	@COMPROBANTEDERETENCIONES_1_PROVEEDORDESCRIPCION_DESDE varchar(60),
	@COMPROBANTEDERETENCIONES_1_PROVEEDORDESCRIPCION_HASTA varchar(60),
	@COMPROBANTEDERETENCIONES_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@COMPROBANTEDERETENCIONES_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@COMPROBANTEDERETENCIONES_1_PUNTODEVENTA_DESDE numeric(4, 0),
	@COMPROBANTEDERETENCIONES_1_PUNTODEVENTA_HASTA numeric(4, 0),
	@COMPROBANTEDERETENCIONES_1_NUMERO_DESDE numeric(10, 0),
	@COMPROBANTEDERETENCIONES_1_NUMERO_HASTA numeric(10, 0),
	@COMPROBANTEDERETENCIONES_1_FECHA_DESDE datetime,
	@COMPROBANTEDERETENCIONES_1_FECHA_HASTA datetime,
	@COMPROBANTEDERETENCIONES_1_LETRAORDENDEPAGO_DESDE varchar(1),
	@COMPROBANTEDERETENCIONES_1_LETRAORDENDEPAGO_HASTA varchar(1),
	@COMPROBANTEDERETENCIONES_1_PUNTODEVENTAORDENDEPAGO_DESDE numeric(4, 0),
	@COMPROBANTEDERETENCIONES_1_PUNTODEVENTAORDENDEPAGO_HASTA numeric(4, 0),
	@COMPROBANTEDERETENCIONES_1_NUMEROORDENDEPAGO_DESDE numeric(10, 0),
	@COMPROBANTEDERETENCIONES_1_NUMEROORDENDEPAGO_HASTA numeric(10, 0),
	@COMPROBANTEDERETENCIONES_1_TOTAL_DESDE numeric(15, 2),
	@COMPROBANTEDERETENCIONES_1_TOTAL_HASTA numeric(15, 2),
	@MONEDA_83_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_83_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_9189_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9189_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9188_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9188_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9187_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9187_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVINCIA_42_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_42_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_57_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_57_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_59_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_59_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_64_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_64_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_66_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_66_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_67_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_67_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_68_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_68_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_77_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_77_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@TIPOIMPUESTO_8010_TIPO_DESCRIPCION_DESDE varchar(40),
	@TIPOIMPUESTO_8010_TIPO_DESCRIPCION_HASTA varchar(40),
	@PROVEEDOR_9000_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_9000_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@SUCURSAL_9184_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9184_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9184_LINEA_DESDE varchar(10),
	@SUCURSAL_9184_LINEA_HASTA varchar(10),
	@SUCURSAL_9184_TIPO_DESDE varchar(10),
	@SUCURSAL_9184_TIPO_HASTA varchar(10),
	@SUCURSAL_9184_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9184_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_9000_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_9000_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_9000_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_9000_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_9000_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_9000_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_9000_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_9000_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_9000_FAX_DESDE varchar(60),
	@PROVEEDOR_9000_FAX_HASTA varchar(60),
	@PROVEEDOR_9000_EMAIL_DESDE varchar(250),
	@PROVEEDOR_9000_EMAIL_HASTA varchar(250),
	@PROVEEDOR_9000_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_9000_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_47_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_9000_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_9000_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_9000_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_9000_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_9000_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_9000_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_9000_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_9000_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_9000_CALLE_DESDE varchar(70),
	@PROVEEDOR_9000_CALLE_HASTA varchar(70),
	@PROVEEDOR_9000_PISO_DESDE varchar(3),
	@PROVEEDOR_9000_PISO_HASTA varchar(3),
	@PROVEEDOR_9000_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_9000_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_9000_PAIS_DESDE varchar(3),
	@PROVEEDOR_9000_PAIS_HASTA varchar(3),
	@PROVEEDOR_9000_MOVIL_DESDE varchar(30),
	@PROVEEDOR_9000_MOVIL_HASTA varchar(30),
	@PROVEEDOR_9000_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_9000_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_9000_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_9000_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_9000_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_9000_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_9000_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_9000_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_9000_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_9000_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_9000_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_9000_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_9000_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_9000_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_9000_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_9000_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_9000_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_9000_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_9000_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_9000_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_9000_EMPLEADOR bit,
	@PROVEEDOR_9000_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_9000_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_9000_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_9000_SUJETOVINCULADO bit,
	@PROVEEDOR_9000_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_9000_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_9000_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_9000_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_9000_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_9000_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_9000_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_9000_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_9000_TASACEROAPLICA bit,
	@PROVEEDOR_9000_RUT_DESDE varchar(12),
	@PROVEEDOR_9000_RUT_HASTA varchar(12),
	@PROVEEDOR_9000_INACTIVOFW bit,
	@SUCURSAL_9184_CODIGO_DESDE varchar(10),
	@SUCURSAL_9184_CODIGO_HASTA varchar(10),
	@ITEMCDRIMPUESTOS_NROITEM_DESDE numeric(5, 0),
	@ITEMCDRIMPUESTOS_NROITEM_HASTA numeric(5, 0),
	@COMPROBANTEDERETENCIONES_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@COMPROBANTEDERETENCIONES_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@COMPROBANTEDERETENCIONES_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@COMPROBANTEDERETENCIONES_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@COMPROBANTEDERETENCIONES_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@COMPROBANTEDERETENCIONES_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@COMPROBANTEDERETENCIONES_1_FECHAALTAFW_DESDE datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAALTAFW_HASTA datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAEXPO_DESDE datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAEXPO_HASTA datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAIMPO_DESDE datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAIMPO_HASTA datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAMODIFICACIONFW_DESDE datetime,
	@COMPROBANTEDERETENCIONES_1_FECHAMODIFICACIONFW_HASTA datetime,
	@COMPROBANTEDERETENCIONES_1_FECHATRANSFERENCIA_DESDE datetime,
	@COMPROBANTEDERETENCIONES_1_FECHATRANSFERENCIA_HASTA datetime,
	@COMPROBANTEDERETENCIONES_1_HORAALTAFW_DESDE varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAALTAFW_HASTA varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAEXPO_DESDE varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAEXPO_HASTA varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAIMPO_DESDE varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAIMPO_HASTA varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@COMPROBANTEDERETENCIONES_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@COMPROBANTEDERETENCIONES_1_SERIEALTAFW_DESDE varchar(7),
	@COMPROBANTEDERETENCIONES_1_SERIEALTAFW_HASTA varchar(7),
	@COMPROBANTEDERETENCIONES_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@COMPROBANTEDERETENCIONES_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@COMPROBANTEDERETENCIONES_1_USUARIOALTAFW_DESDE varchar(100),
	@COMPROBANTEDERETENCIONES_1_USUARIOALTAFW_HASTA varchar(100),
	@COMPROBANTEDERETENCIONES_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@COMPROBANTEDERETENCIONES_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@COMPROBANTEDERETENCIONES_1_VERSIONALTAFW_DESDE varchar(13),
	@COMPROBANTEDERETENCIONES_1_VERSIONALTAFW_HASTA varchar(13),
	@COMPROBANTEDERETENCIONES_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@COMPROBANTEDERETENCIONES_1_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_ITEMCDRIMPUESTOS.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMCDRIMPUESTOS__Grupo,
	@basededatos as ITEMCDRIMPUESTOS__BD,
	c_ITEMCDRIMPUESTOS.CODIGO as ITEMCDRIMPUESTOS_Codigo,
	c_ITEMCDRIMPUESTOS.CONVMULTI as ITEMCDRIMPUESTOS_ConvMulti,
	c_ITEMCDRIMPUESTOS.PORCONVMUL as ITEMCDRIMPUESTOS_PorConvMul,
	c_ITEMCDRIMPUESTOS.PORCBASE as ITEMCDRIMPUESTOS_PorcBase,
	c_ITEMCDRIMPUESTOS.MONTOBASE as ITEMCDRIMPUESTOS_MontoBase,
	c_ITEMCDRIMPUESTOS.BASECALC as ITEMCDRIMPUESTOS_BaseCalc,
	c_ITEMCDRIMPUESTOS.REGIMENIMP as ITEMCDRIMPUESTOS_RegimenImp,
	c_ITEMCDRIMPUESTOS.MINIMO as ITEMCDRIMPUESTOS_Minimo,
	c_ITEMCDRIMPUESTOS.MINNOIMP as ITEMCDRIMPUESTOS_MinNoImp,
	c_ITEMCDRIMPUESTOS.MONTOORIGE as ITEMCDRIMPUESTOS_MontoOrige,
	c_ITEMCDRIMPUESTOS.REGIMDESCR as ITEMCDRIMPUESTOS_RegimDescr,
	c_ITEMCDRIMPUESTOS.SIRECERT as ITEMCDRIMPUESTOS_SIRECERT,
	c_ITEMCDRIMPUESTOS.SIRECS as ITEMCDRIMPUESTOS_SIRECS,
	c_ITEMCDRIMPUESTOS.JURISDETA as ITEMCDRIMPUESTOS_JurisDeta,
	c_ITEMCDRIMPUESTOS.RESOLDETA as ITEMCDRIMPUESTOS_ResolDeta,
	c_ITEMCDRIMPUESTOS.MINNOIMPO as ITEMCDRIMPUESTOS_MinNoImpo,
	c_ITEMCDRIMPUESTOS.PORCENTAJE as ITEMCDRIMPUESTOS_Porcentaje,
	c_ITEMCDRIMPUESTOS.CR_CODIGO as COMPROBANTEDERETENCIONES_CODIGO,
	c_proveedor.CIMAGEN as PROVEEDOR_CIMAGEN,
	c_ITEMCDRIMPUESTOS.CR_DESPROV as COMPROBANTEDERETENCIONES_DesProv,
	c_ITEMCDRIMPUESTOS.CR_MONEDA as COMPROBANTEDERETENCIONES_Moneda,
	c_ITEMCDRIMPUESTOS.CR_PTOVENTA as COMPROBANTEDERETENCIONES_PtoVenta,
	c_ITEMCDRIMPUESTOS.CR_NUMERO as COMPROBANTEDERETENCIONES_Numero,
	case when c_ITEMCDRIMPUESTOS.CR_fecha = '01/01/1900 00:00:00' then null else c_ITEMCDRIMPUESTOS.CR_fecha end as COMPROBANTEDERETENCIONES_Fecha,
	c_ITEMCDRIMPUESTOS.CR_LETRAOP as COMPROBANTEDERETENCIONES_LetraOP,
	c_ITEMCDRIMPUESTOS.CR_PTOVENOP as COMPROBANTEDERETENCIONES_PtoVenOP,
	c_ITEMCDRIMPUESTOS.CR_NUMOP as COMPROBANTEDERETENCIONES_NumOP,
	c_ITEMCDRIMPUESTOS.CR_CRTOTAL as COMPROBANTEDERETENCIONES_CRTotal,
	c_ITEMCDRIMPUESTOS.CR_OBS as COMPROBANTEDERETENCIONES_Obs,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_PROVEEDOR.CLLOC as PROVEEDOR_CLLOC,
	C_PROVEEDOR.CLCP as PROVEEDOR_CLCP,
	C_PROVEEDOR.CLPRV as PROVEEDOR_CLPRV,
	C_PROVEEDOR.CLTLF as PROVEEDOR_CLTLF,
	C_PROVEEDOR.CLFAX as PROVEEDOR_CLFAX,
	c_proveedor.CLEMAIL as PROVEEDOR_CLEMAIL,
	C_PROVEEDOR.CLPAGEWEB as PROVEEDOR_CLPAGEWEB,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	c_proveedor.CLOBS as PROVEEDOR_CLOBS,
	c_proveedor.CLTIPODOC as PROVEEDOR_CLTIPODOC,
	c_proveedor.CLNRODOC as PROVEEDOR_CLNRODOC,
	c_proveedor.PNUMERO as PROVEEDOR_PNUMERO,
	c_proveedor.PCALLE as PROVEEDOR_PCALLE,
	c_proveedor.PPISO as PROVEEDOR_PPISO,
	c_proveedor.PDEPTO as PROVEEDOR_PDEPTO,
	c_proveedor.PPAIS as PROVEEDOR_PPAIS,
	c_proveedor.TLFM as PROVEEDOR_TLFM,
	c_proveedor.CLAS as PROVEEDOR_CLAS,
	case when c_proveedor.clfecha = '01/01/1900 00:00:00' then null else c_proveedor.clfecha end as PROVEEDOR_CLFECHA,
	c_proveedor.CLCONDPAG as PROVEEDOR_CLCONDPAG,
	c_proveedor.CLTIPCONV as PROVEEDOR_CLTIPCONV,
	c_proveedor.CLNROIIBB as PROVEEDOR_CLNROIIBB,
	c_proveedor.CLLISTPRE as PROVEEDOR_CLLISTPRE,
	c_proveedor.CLSITGAN as PROVEEDOR_CLSITGAN,
	c_proveedor.CLRETGAN as PROVEEDOR_CLRETGAN,
	c_proveedor.CLRETSUSS as PROVEEDOR_CLRETSUSS,
	c_proveedor.CLRETIVA as PROVEEDOR_CLRETIVA,
	c_proveedor.CLOBJIVA as PROVEEDOR_CLOBJIVA,
	c_proveedor.CLEMPLEAD as PROVEEDOR_CLEMPLEAD,
	c_proveedor.EXRETGAN as PROVEEDOR_EXRETGAN,
	c_proveedor.EXRETIVA as PROVEEDOR_EXRETIVA,
	c_proveedor.EXRETSUSS as PROVEEDOR_EXRETSUSS,
	c_proveedor.CLSUJVINC as PROVEEDOR_CLSujVinc,
	case when c_proveedor.pvhastaiva = '01/01/1900 00:00:00' then null else c_proveedor.pvhastaiva end as PROVEEDOR_PVHastaIva,
	case when c_proveedor.pvhastagan = '01/01/1900 00:00:00' then null else c_proveedor.pvhastagan end as PROVEEDOR_PVHastaGan,
	c_proveedor.CLSIPRIB as PROVEEDOR_CLSIPRIB,
	c_proveedor.INACTIVOFW as PROVEEDOR_InactivoFW,
	C_PROVEEDOR.PORCENTC as PROVEEDOR_PorcenTC,
	C_PROVEEDOR.APLICATC as PROVEEDOR_AplicaTC,
	C_PROVEEDOR.RUT as PROVEEDOR_RUT,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMCDRIMPUESTOS.NROITEM as ITEMCDRIMPUESTOS_NROITEM,
	c_ITEMCDRIMPUESTOS.CR_BDALTAFW as COMPROBANTEDERETENCIONES_BDALTAFW,
	c_ITEMCDRIMPUESTOS.CR_BDMODIFW as COMPROBANTEDERETENCIONES_BDMODIFW,
	c_ITEMCDRIMPUESTOS.CR_ESTTRANS as COMPROBANTEDERETENCIONES_ESTTRANS,
	case when C_ITEMCDRIMPUESTOS.CR_faltafw = '01/01/1900 00:00:00' then null else C_ITEMCDRIMPUESTOS.CR_faltafw end as COMPROBANTEDERETENCIONES_FALTAFW,
	case when C_ITEMCDRIMPUESTOS.CR_fecexpo = '01/01/1900 00:00:00' then null else C_ITEMCDRIMPUESTOS.CR_fecexpo end as COMPROBANTEDERETENCIONES_FECEXPO,
	case when C_ITEMCDRIMPUESTOS.CR_fecimpo = '01/01/1900 00:00:00' then null else C_ITEMCDRIMPUESTOS.CR_fecimpo end as COMPROBANTEDERETENCIONES_FECIMPO,
	case when C_ITEMCDRIMPUESTOS.CR_fmodifw = '01/01/1900 00:00:00' then null else C_ITEMCDRIMPUESTOS.CR_fmodifw end as COMPROBANTEDERETENCIONES_FMODIFW,
	case when C_ITEMCDRIMPUESTOS.CR_fectrans = '01/01/1900 00:00:00' then null else C_ITEMCDRIMPUESTOS.CR_fectrans end as COMPROBANTEDERETENCIONES_FECTRANS,
	c_ITEMCDRIMPUESTOS.CR_HALTAFW as COMPROBANTEDERETENCIONES_HALTAFW,
	C_ITEMCDRIMPUESTOS.CR_HORAEXPO as COMPROBANTEDERETENCIONES_HORAEXPO,
	C_ITEMCDRIMPUESTOS.CR_HORAIMPO as COMPROBANTEDERETENCIONES_HORAIMPO,
	C_ITEMCDRIMPUESTOS.CR_HMODIFW as COMPROBANTEDERETENCIONES_HMODIFW,
	C_ITEMCDRIMPUESTOS.CR_SALTAFW as COMPROBANTEDERETENCIONES_SALTAFW,
	C_ITEMCDRIMPUESTOS.CR_SMODIFW as COMPROBANTEDERETENCIONES_SMODIFW,
	C_ITEMCDRIMPUESTOS.CR_UALTAFW as COMPROBANTEDERETENCIONES_UALTAFW,
	C_ITEMCDRIMPUESTOS.CR_UMODIFW as COMPROBANTEDERETENCIONES_UMODIFW,
	C_ITEMCDRIMPUESTOS.CR_VALTAFW as COMPROBANTEDERETENCIONES_VALTAFW,
	C_ITEMCDRIMPUESTOS.CR_VMODIFW as COMPROBANTEDERETENCIONES_VMODIFW,
	C_ITEMCDRIMPUESTOS.CR_ZADSFW as COMPROBANTEDERETENCIONES_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMCDRIMPUESTOS__SUCURSAL,
	c_ITEMCDRIMPUESTOS.CODIMP as ITEMCDRIMPUESTOS_CodImp,
	C_IMPUESTO8000.TIPO as IMPUESTO8000_tipo,
	C_IMPUESTO8000.APLICACION as IMPUESTO8000_aplicacion,
	c_ITEMCDRIMPUESTOS.IMPUESTO8000_8000_SignoVirtual as IMPUESTO8000_8000_SignoVirtual,
	c_ITEMCDRIMPUESTOS.CR_1_TipoComprobanteVirtual as COMPROBANTEDERETENCIONES_1_TipoComprobanteVirtual,
	c_ITEMCDRIMPUESTOS.CR_PROV as COMPROBANTEDERETENCIONES_Prov,
	case when c_ITEMCDRIMPUESTOS.CR_1_TipoComprobanteVirtual = 999 
		then 'LIQ ' + c_ITEMCDRIMPUESTOS.CR_1_OCVirtual 
		else Funciones.IdentificadorDeComprobanteParaListado( c_ITEMCDRIMPUESTOS.CR_1_TipoComprobanteVirtual, c_ITEMCDRIMPUESTOS.CR_letraop, c_ITEMCDRIMPUESTOS.CR_Ptovenop, c_ITEMCDRIMPUESTOS.CR_numop ) 
		end as COMPROBANTEDERETENCIONES_1_Comprobantevirtual,
	c_proveedor.CLCUIT as PROVEEDOR_CLCUIT,
	c_ITEMCDRIMPUESTOS.CR_1_OCVirtual as COMPROBANTEDERETENCIONES_1_OCVirtual,
	cast( case when not 1 = funciones.empty(C_COMPROBANTEDERETENCIONES.impman) then  'manual' else  'automatica' end as varchar( 10 ) ) as COMPROBANTEDERETENCIONES_ImpMan,
	c_ITEMCDRIMPUESTOS.MONTO as ITEMCDRIMPUESTOS_Monto,
	c_ITEMCDRIMPUESTOS.CR_FechaEmisionVirtual as COMPROBANTEDERETENCIONES_FechaEmisionVirtual,
	c_moneda.Descrip as MONEDA_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	c_ITEMCDRIMPUESTOS.PROVEEDOR_CLIVA as PROVEEDOR_CLIVA,
	C_PAISES.PDES as PAISES_pdes,
	C_CLASIFICACIONPROVEEDOR.CLADES as CLASIFICACIONPROVEEDOR_CLADES,
	C_CONDICIONDEPAGO.CLNOM as CONDICIONDEPAGO_CLNOM,
	C_LISTADEPRECIOS.LPR_NOMBRE as LISTADEPRECIOS_LPR_NOMBRE,
	C_IMPUESTO66.DESCRIP as IMPUESTO66_descrip,
	C_IMPUESTO67.DESCRIP as IMPUESTO67_descrip,
	C_IMPUESTO68.DESCRIP as IMPUESTO68_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	c_ITEMCDRIMPUESTOS.IMPUESTO8000_DESCRIP as IMPUESTO8000_descrip,
	c_ITEMCDRIMPUESTOS.tipoimpuesto_decrip as TIPOIMPUESTO_Decrip, -- C_TIPOIMPUESTO.DECRIP as TIPOIMPUESTO_Decrip,
	c_proveedor.CLNOM as PROVEEDOR_CLNOM,
	C_CLASIFICACIONPROVEEDOR.CLACOD as CLASIFICACIONPROVEEDOR_CLACOD,
	C_CONDICIONDEPAGO.CLCOD as CONDICIONDEPAGO_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_IMPUESTO66.CODIGO as IMPUESTO66_codigo,
	C_IMPUESTO67.CODIGO as IMPUESTO67_codigo,
	C_IMPUESTO68.CODIGO as IMPUESTO68_codigo,
	c_ITEMCDRIMPUESTOS.IMPUESTO8000_codigo as IMPUESTO8000_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS.LPR_NUMERO as LISTADEPRECIOS_LPR_NUMERO,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_PAISES.PCOD as PAISES_pcod,
	c_ITEMCDRIMPUESTOS.PROVEEDOR_CLCOD as PROVEEDOR_CLCOD,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	c_ITEMCDRIMPUESTOS.tipoimpuesto_codigo as TIPOIMPUESTO_Codigo,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD
 from Funciones.ObtenerRetPerIVA(@BaseDeDatos) as c_ITEMCDRIMPUESTOS
 left join ZooLogic.COMPRET as C_COMPROBANTEDERETENCIONES on C_COMPROBANTEDERETENCIONES.CODIGO = c_ITEMCDRIMPUESTOS.CODIGO and 0 = Funciones.empty( c_ITEMCDRIMPUESTOS.CODIGO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO8000 on C_IMPUESTO8000.CODIGO = c_ITEMCDRIMPUESTOS.CODIMP and 0 = Funciones.empty( c_ITEMCDRIMPUESTOS.CODIMP )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = c_ITEMCDRIMPUESTOS.CR_Moneda and 0 = Funciones.empty( c_ITEMCDRIMPUESTOS.CR_Moneda )
 left join ZooLogic.PROV as C_PROVEEDOR on C_PROVEEDOR.CLCOD = c_ITEMCDRIMPUESTOS.PROVEEDOR_CLCOD and 0 = Funciones.empty( c_ITEMCDRIMPUESTOS.PROVEEDOR_CLCOD )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = c_proveedor.CLPRV and 0 = Funciones.empty( c_proveedor.CLPRV )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = c_ITEMCDRIMPUESTOS.PROVEEDOR_CLIVA and 0 = Funciones.empty( c_ITEMCDRIMPUESTOS.PROVEEDOR_CLIVA )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TIPOIMP as C_TIPOIMPUESTO on C_TIPOIMPUESTO.CODIGO = c_ITEMCDRIMPUESTOS.IMPUESTO8000_TIPO and 0 = Funciones.empty( c_ITEMCDRIMPUESTOS.IMPUESTO8000_TIPO )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR on C_CLASIFICACIONPROVEEDOR.CLACOD = c_proveedor.CLAS and 0 = Funciones.empty( c_proveedor.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO on C_CONDICIONDEPAGO.CLCOD = c_proveedor.CLCONDPAG and 0 = Funciones.empty( c_proveedor.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = c_proveedor.CLSIPRIB and 0 = Funciones.empty( c_proveedor.CLSIPRIB )
 left join ZooLogic.IMPUESTO as C_IMPUESTO66 on C_IMPUESTO66.CODIGO = c_proveedor.CLRETGAN and 0 = Funciones.empty( c_proveedor.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO67 on C_IMPUESTO67.CODIGO = c_proveedor.CLRETSUSS and 0 = Funciones.empty( c_proveedor.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO68 on C_IMPUESTO68.CODIGO = c_proveedor.CLRETIVA and 0 = Funciones.empty( c_proveedor.CLRETIVA )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS on C_LISTADEPRECIOS.LPR_NUMERO = c_proveedor.CLLISTPRE and 0 = Funciones.empty( c_proveedor.CLLISTPRE )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = c_proveedor.PPAIS and 0 = Funciones.empty( c_proveedor.PPAIS )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( 1=1 ) and 
	( ( @ITEMCDRIMPUESTOS_CODIMP_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CodImp >= @ITEMCDRIMPUESTOS_CODIMP_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_CODIMP_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.CodImp <= @ITEMCDRIMPUESTOS_CODIMP_HASTA ) ) and 
	( ( @IMPUESTO_8000_TIPO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.IMPUESTO8000_tipo >= @IMPUESTO_8000_TIPO_DESDE ) ) and 
	( ( @IMPUESTO_8000_TIPO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.IMPUESTO8000_tipo <= @IMPUESTO_8000_TIPO_HASTA ) ) and 
	( ( @IMPUESTO_8000_APLICACION is null ) OR ( c_ITEMCDRIMPUESTOS.IMPUESTO8000_aplicacion = @IMPUESTO_8000_APLICACION ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PROVEEDOR_DESDE is null ) OR ( C_COMPROBANTEDERETENCIONES.Prov >= @COMPROBANTEDERETENCIONES_1_PROVEEDOR_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PROVEEDOR_HASTA is null ) OR ( C_COMPROBANTEDERETENCIONES.Prov <= @COMPROBANTEDERETENCIONES_1_PROVEEDOR_HASTA ) ) and 
	( ( @PROVEEDOR_9000_CUIT_DESDE is null ) OR ( c_proveedor.CLCUIT >= @PROVEEDOR_9000_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_9000_CUIT_HASTA is null ) OR ( c_proveedor.CLCUIT <= @PROVEEDOR_9000_CUIT_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_MONTO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.Monto >= @ITEMCDRIMPUESTOS_MONTO_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_MONTO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.Monto <= @ITEMCDRIMPUESTOS_MONTO_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_CONVENIOMULTILATERAL_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.ConvMulti >= @ITEMCDRIMPUESTOS_CONVENIOMULTILATERAL_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_CONVENIOMULTILATERAL_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.ConvMulti <= @ITEMCDRIMPUESTOS_CONVENIOMULTILATERAL_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_PORCENTAJEDECONVENIO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.PorConvMul >= @ITEMCDRIMPUESTOS_PORCENTAJEDECONVENIO_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_PORCENTAJEDECONVENIO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.PorConvMul <= @ITEMCDRIMPUESTOS_PORCENTAJEDECONVENIO_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_PORCENTAJEDEBASE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.PorcBase >= @ITEMCDRIMPUESTOS_PORCENTAJEDEBASE_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_PORCENTAJEDEBASE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.PorcBase <= @ITEMCDRIMPUESTOS_PORCENTAJEDEBASE_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_MONTOBASE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.MontoBase >= @ITEMCDRIMPUESTOS_MONTOBASE_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_MONTOBASE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.MontoBase <= @ITEMCDRIMPUESTOS_MONTOBASE_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_BASEDECALCULO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.BaseCalc >= @ITEMCDRIMPUESTOS_BASEDECALCULO_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_BASEDECALCULO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.BaseCalc <= @ITEMCDRIMPUESTOS_BASEDECALCULO_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.RegimenImp >= @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVO_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.RegimenImp <= @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVO_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_MINIMO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.Minimo >= @ITEMCDRIMPUESTOS_MINIMO_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_MINIMO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.Minimo <= @ITEMCDRIMPUESTOS_MINIMO_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_MINIMONOIMP_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.MinNoImp >= @ITEMCDRIMPUESTOS_MINIMONOIMP_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_MINIMONOIMP_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.MinNoImp <= @ITEMCDRIMPUESTOS_MINIMONOIMP_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_MONTOCOMPROBANTEORIGEN_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.MontoOrige >= @ITEMCDRIMPUESTOS_MONTOCOMPROBANTEORIGEN_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_MONTOCOMPROBANTEORIGEN_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.MontoOrige <= @ITEMCDRIMPUESTOS_MONTOCOMPROBANTEORIGEN_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVODESCRIPCION_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.RegimDescr >= @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVODESCRIPCION_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVODESCRIPCION_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.RegimDescr <= @ITEMCDRIMPUESTOS_REGIMENIMPOSITIVODESCRIPCION_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_CERTIFICADOSIRE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.SIRECERT >= @ITEMCDRIMPUESTOS_CERTIFICADOSIRE_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_CERTIFICADOSIRE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.SIRECERT <= @ITEMCDRIMPUESTOS_CERTIFICADOSIRE_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_CODSEGURIDADSIRE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.SIRECS >= @ITEMCDRIMPUESTOS_CODSEGURIDADSIRE_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_CODSEGURIDADSIRE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.SIRECS <= @ITEMCDRIMPUESTOS_CODSEGURIDADSIRE_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_JURISDICCIONDESCRIPCION_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.JurisDeta >= @ITEMCDRIMPUESTOS_JURISDICCIONDESCRIPCION_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_JURISDICCIONDESCRIPCION_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.JurisDeta <= @ITEMCDRIMPUESTOS_JURISDICCIONDESCRIPCION_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_RESOLUCION_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.ResolDeta >= @ITEMCDRIMPUESTOS_RESOLUCION_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_RESOLUCION_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.ResolDeta <= @ITEMCDRIMPUESTOS_RESOLUCION_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_MINIMONOIMPONIBLE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.MinNoImpo >= @ITEMCDRIMPUESTOS_MINIMONOIMPONIBLE_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_MINIMONOIMPONIBLE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.MinNoImpo <= @ITEMCDRIMPUESTOS_MINIMONOIMPONIBLE_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_PORCENTAJE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.Porcentaje >= @ITEMCDRIMPUESTOS_PORCENTAJE_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_PORCENTAJE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.Porcentaje <= @ITEMCDRIMPUESTOS_PORCENTAJE_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_CODIGO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CR_CODIGO >= @COMPROBANTEDERETENCIONES_1_CODIGO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_CODIGO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.CR_CODIGO <= @COMPROBANTEDERETENCIONES_1_CODIGO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PROVEEDORDESCRIPCION_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CR_DesProv >= @COMPROBANTEDERETENCIONES_1_PROVEEDORDESCRIPCION_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PROVEEDORDESCRIPCION_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.CR_DesProv <= @COMPROBANTEDERETENCIONES_1_PROVEEDORDESCRIPCION_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_MONEDACOMPROBANTE_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CR_Moneda >= @COMPROBANTEDERETENCIONES_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_MONEDACOMPROBANTE_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.CR_Moneda <= @COMPROBANTEDERETENCIONES_1_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PUNTODEVENTA_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CR_PtoVenta >= @COMPROBANTEDERETENCIONES_1_PUNTODEVENTA_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PUNTODEVENTA_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.CR_PtoVenta <= @COMPROBANTEDERETENCIONES_1_PUNTODEVENTA_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_NUMERO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CR_Numero >= @COMPROBANTEDERETENCIONES_1_NUMERO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_NUMERO_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.CR_Numero <= @COMPROBANTEDERETENCIONES_1_NUMERO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHA_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_Fecha >= @COMPROBANTEDERETENCIONES_1_FECHA_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHA_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_Fecha <= @COMPROBANTEDERETENCIONES_1_FECHA_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_LETRAORDENDEPAGO_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.CR_LetraOP >= @COMPROBANTEDERETENCIONES_1_LETRAORDENDEPAGO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_LETRAORDENDEPAGO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_LetraOP <= @COMPROBANTEDERETENCIONES_1_LETRAORDENDEPAGO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PUNTODEVENTAORDENDEPAGO_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_PtoVenOP >= @COMPROBANTEDERETENCIONES_1_PUNTODEVENTAORDENDEPAGO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_PUNTODEVENTAORDENDEPAGO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_PtoVenOP <= @COMPROBANTEDERETENCIONES_1_PUNTODEVENTAORDENDEPAGO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_NUMEROORDENDEPAGO_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_NumOP >= @COMPROBANTEDERETENCIONES_1_NUMEROORDENDEPAGO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_NUMEROORDENDEPAGO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_NumOP <= @COMPROBANTEDERETENCIONES_1_NUMEROORDENDEPAGO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_TOTAL_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_CRTotal >= @COMPROBANTEDERETENCIONES_1_TOTAL_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_TOTAL_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_CRTotal <= @COMPROBANTEDERETENCIONES_1_TOTAL_HASTA ) ) and 
	( ( @MONEDA_83_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_83_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_83_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_83_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_9189_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9189_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9189_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9189_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9188_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9188_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9188_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9188_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9187_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9187_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9187_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9187_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_42_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_42_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_42_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_42_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_57_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_57_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_57_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_57_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_59_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES >= @CLASIFICACIONPROVEEDOR_59_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_59_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES <= @CLASIFICACIONPROVEEDOR_59_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO.CLNOM >= @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO.CLNOM <= @CONDICIONDEPAGO_61_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_64_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE >= @LISTADEPRECIOS_64_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_64_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS.LPR_NOMBRE <= @LISTADEPRECIOS_64_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_66_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO66.descrip >= @IMPUESTO_66_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_66_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO66.descrip <= @IMPUESTO_66_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_67_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO67.descrip >= @IMPUESTO_67_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_67_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO67.descrip <= @IMPUESTO_67_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_68_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO68.descrip >= @IMPUESTO_68_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_68_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO68.descrip <= @IMPUESTO_68_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_77_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_77_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_77_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_77_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOIMPUESTO_8010_TIPO_DESCRIPCION_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.TIPOIMPUESTO_Decrip >= @TIPOIMPUESTO_8010_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOIMPUESTO_8010_TIPO_DESCRIPCION_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.TIPOIMPUESTO_Decrip <= @TIPOIMPUESTO_8010_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_9000_PROVEEDOR_NOMBRE_DESDE is null ) OR ( c_proveedor.CLNOM >= @PROVEEDOR_9000_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_9000_PROVEEDOR_NOMBRE_HASTA is null ) OR ( c_proveedor.CLNOM <= @PROVEEDOR_9000_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @SUCURSAL_9184_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9184_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9184_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9184_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9184_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9184_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9184_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9184_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9184_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9184_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9184_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9184_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9184_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9184_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9184_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9184_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_9000_LOCALIDAD_DESDE is null ) OR ( c_proveedor.CLLOC >= @PROVEEDOR_9000_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_9000_LOCALIDAD_HASTA is null ) OR ( c_proveedor.CLLOC <= @PROVEEDOR_9000_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_9000_CODIGOPOSTAL_DESDE is null ) OR ( c_proveedor.CLCP >= @PROVEEDOR_9000_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_9000_CODIGOPOSTAL_HASTA is null ) OR ( c_proveedor.CLCP <= @PROVEEDOR_9000_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_9000_PROVINCIA_DESDE is null ) OR ( c_proveedor.CLPRV >= @PROVEEDOR_9000_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_9000_PROVINCIA_HASTA is null ) OR ( c_proveedor.CLPRV <= @PROVEEDOR_9000_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_9000_TELEFONO_DESDE is null ) OR ( c_proveedor.CLTLF >= @PROVEEDOR_9000_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_TELEFONO_HASTA is null ) OR ( c_proveedor.CLTLF <= @PROVEEDOR_9000_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_FAX_DESDE is null ) OR ( c_proveedor.CLFAX >= @PROVEEDOR_9000_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_9000_FAX_HASTA is null ) OR ( c_proveedor.CLFAX <= @PROVEEDOR_9000_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_9000_EMAIL_DESDE is null ) OR ( c_proveedor.CLEMAIL >= @PROVEEDOR_9000_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_9000_EMAIL_HASTA is null ) OR ( c_proveedor.CLEMAIL <= @PROVEEDOR_9000_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_9000_PAGINAWEB_DESDE is null ) OR ( c_proveedor.CLPAGEWEB >= @PROVEEDOR_9000_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_9000_PAGINAWEB_HASTA is null ) OR ( c_proveedor.CLPAGEWEB <= @PROVEEDOR_9000_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_47_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_47_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_9000_TIPODOCUMENTO_DESDE is null ) OR ( c_proveedor.CLTIPODOC >= @PROVEEDOR_9000_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_TIPODOCUMENTO_HASTA is null ) OR ( c_proveedor.CLTIPODOC <= @PROVEEDOR_9000_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_NRODOCUMENTO_DESDE is null ) OR ( c_proveedor.CLNRODOC >= @PROVEEDOR_9000_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_NRODOCUMENTO_HASTA is null ) OR ( c_proveedor.CLNRODOC <= @PROVEEDOR_9000_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_IMAGEN_DESDE is null ) OR ( c_proveedor.CIMAGEN >= @PROVEEDOR_9000_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_9000_IMAGEN_HASTA is null ) OR ( c_proveedor.CIMAGEN <= @PROVEEDOR_9000_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_9000_NUMERO_DESDE is null ) OR ( c_proveedor.PNUMERO >= @PROVEEDOR_9000_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_NUMERO_HASTA is null ) OR ( c_proveedor.PNUMERO <= @PROVEEDOR_9000_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_CALLE_DESDE is null ) OR ( c_proveedor.PCALLE >= @PROVEEDOR_9000_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_9000_CALLE_HASTA is null ) OR ( c_proveedor.PCALLE <= @PROVEEDOR_9000_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_9000_PISO_DESDE is null ) OR ( c_proveedor.PPISO >= @PROVEEDOR_9000_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_PISO_HASTA is null ) OR ( c_proveedor.PPISO <= @PROVEEDOR_9000_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_DEPARTAMENTO_DESDE is null ) OR ( c_proveedor.PDEPTO >= @PROVEEDOR_9000_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_DEPARTAMENTO_HASTA is null ) OR ( c_proveedor.PDEPTO <= @PROVEEDOR_9000_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_PAIS_DESDE is null ) OR ( c_proveedor.PPAIS >= @PROVEEDOR_9000_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_9000_PAIS_HASTA is null ) OR ( c_proveedor.PPAIS <= @PROVEEDOR_9000_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_9000_MOVIL_DESDE is null ) OR ( c_proveedor.TLFM >= @PROVEEDOR_9000_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_9000_MOVIL_HASTA is null ) OR ( c_proveedor.TLFM <= @PROVEEDOR_9000_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_9000_CLASIFICACION_DESDE is null ) OR ( c_proveedor.CLAS >= @PROVEEDOR_9000_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_9000_CLASIFICACION_HASTA is null ) OR ( c_proveedor.CLAS <= @PROVEEDOR_9000_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_9000_FECHANACIMIENTO_DESDE is null ) OR ( c_proveedor.CLFECHA >= @PROVEEDOR_9000_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_FECHANACIMIENTO_HASTA is null ) OR ( c_proveedor.CLFECHA <= @PROVEEDOR_9000_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_CONDICIONDEPAGO_DESDE is null ) OR ( c_proveedor.CLCONDPAG >= @PROVEEDOR_9000_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_CONDICIONDEPAGO_HASTA is null ) OR ( c_proveedor.CLCONDPAG <= @PROVEEDOR_9000_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_TIPOCONVENIO_DESDE is null ) OR ( c_proveedor.CLTIPCONV >= @PROVEEDOR_9000_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_TIPOCONVENIO_HASTA is null ) OR ( c_proveedor.CLTIPCONV <= @PROVEEDOR_9000_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_NROIIBB_DESDE is null ) OR ( c_proveedor.CLNROIIBB >= @PROVEEDOR_9000_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_9000_NROIIBB_HASTA is null ) OR ( c_proveedor.CLNROIIBB <= @PROVEEDOR_9000_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_9000_LISTADEPRECIO_DESDE is null ) OR ( c_proveedor.CLLISTPRE >= @PROVEEDOR_9000_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_9000_LISTADEPRECIO_HASTA is null ) OR ( c_proveedor.CLLISTPRE <= @PROVEEDOR_9000_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_9000_SITUACIONGANANCIAS is null ) OR ( c_proveedor.CLSITGAN = @PROVEEDOR_9000_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_9000_RETENCIONGANANCIAS_DESDE is null ) OR ( c_proveedor.CLRETGAN >= @PROVEEDOR_9000_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_9000_RETENCIONGANANCIAS_HASTA is null ) OR ( c_proveedor.CLRETGAN <= @PROVEEDOR_9000_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_9000_RETENCIONSUSS_DESDE is null ) OR ( c_proveedor.CLRETSUSS >= @PROVEEDOR_9000_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_9000_RETENCIONSUSS_HASTA is null ) OR ( c_proveedor.CLRETSUSS <= @PROVEEDOR_9000_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_9000_RETENCIONIVA_DESDE is null ) OR ( c_proveedor.CLRETIVA >= @PROVEEDOR_9000_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_9000_RETENCIONIVA_HASTA is null ) OR ( c_proveedor.CLRETIVA <= @PROVEEDOR_9000_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_9000_OBJETOIVA is null ) OR ( c_proveedor.CLOBJIVA = @PROVEEDOR_9000_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_9000_EMPLEADOR is null ) OR ( c_proveedor.CLEMPLEAD = @PROVEEDOR_9000_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_9000_EXCLUIDORETENCIONGANANCIAS is null ) OR ( c_proveedor.EXRETGAN = @PROVEEDOR_9000_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_9000_EXCLUIDORETENCIONIVA is null ) OR ( c_proveedor.EXRETIVA = @PROVEEDOR_9000_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_9000_EXCLUIDORETENCIONSUSS is null ) OR ( c_proveedor.EXRETSUSS = @PROVEEDOR_9000_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_9000_SUJETOVINCULADO is null ) OR ( c_proveedor.CLSujVinc = @PROVEEDOR_9000_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_9000_VIGENCIAHASTAIVA_DESDE is null ) OR ( c_proveedor.PVHastaIva >= @PROVEEDOR_9000_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_9000_VIGENCIAHASTAIVA_HASTA is null ) OR ( c_proveedor.PVHastaIva <= @PROVEEDOR_9000_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_9000_VIGENCIAHASTAGAN_DESDE is null ) OR ( c_proveedor.PVHastaGan >= @PROVEEDOR_9000_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_9000_VIGENCIAHASTAGAN_HASTA is null ) OR ( c_proveedor.PVHastaGan <= @PROVEEDOR_9000_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_9000_CODIGOSIPRIB_DESDE is null ) OR ( c_proveedor.CLSIPRIB >= @PROVEEDOR_9000_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_9000_CODIGOSIPRIB_HASTA is null ) OR ( c_proveedor.CLSIPRIB <= @PROVEEDOR_9000_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_9000_INACTIVOFW is null ) OR ( c_proveedor.InactivoFW = @PROVEEDOR_9000_INACTIVOFW ) ) and
	( ( @PROVEEDOR_9000_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR.PorcenTC >= @PROVEEDOR_9000_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_9000_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR.PorcenTC <= @PROVEEDOR_9000_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_9000_TASACEROAPLICA is null ) OR ( C_PROVEEDOR.AplicaTC = @PROVEEDOR_9000_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_9000_RUT_DESDE is null ) OR ( C_PROVEEDOR.RUT >= @PROVEEDOR_9000_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_9000_RUT_HASTA is null ) OR ( C_PROVEEDOR.RUT <= @PROVEEDOR_9000_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_9000_INACTIVOFW is null ) OR ( C_PROVEEDOR.InactivoFW = @PROVEEDOR_9000_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9184_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9184_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9184_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9184_CODIGO_HASTA ) ) and 
	( ( @ITEMCDRIMPUESTOS_NROITEM_DESDE is null ) OR ( c_ITEMCDRIMPUESTOS.NROITEM >= @ITEMCDRIMPUESTOS_NROITEM_DESDE ) ) and 
	( ( @ITEMCDRIMPUESTOS_NROITEM_HASTA is null ) OR ( c_ITEMCDRIMPUESTOS.NROITEM <= @ITEMCDRIMPUESTOS_NROITEM_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_BDALTAFW >= @COMPROBANTEDERETENCIONES_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_BDALTAFW <= @COMPROBANTEDERETENCIONES_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_BDMODIFW >= @COMPROBANTEDERETENCIONES_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_BDMODIFW <= @COMPROBANTEDERETENCIONES_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_ESTTRANS >= @COMPROBANTEDERETENCIONES_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_ESTTRANS <= @COMPROBANTEDERETENCIONES_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAALTAFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FALTAFW >= @COMPROBANTEDERETENCIONES_1_FECHAALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAALTAFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FALTAFW <= @COMPROBANTEDERETENCIONES_1_FECHAALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAEXPO_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FECEXPO >= @COMPROBANTEDERETENCIONES_1_FECHAEXPO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAEXPO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FECEXPO <= @COMPROBANTEDERETENCIONES_1_FECHAEXPO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAIMPO_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FECIMPO >= @COMPROBANTEDERETENCIONES_1_FECHAIMPO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAIMPO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FECIMPO <= @COMPROBANTEDERETENCIONES_1_FECHAIMPO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FMODIFW >= @COMPROBANTEDERETENCIONES_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FMODIFW <= @COMPROBANTEDERETENCIONES_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FECTRANS >= @COMPROBANTEDERETENCIONES_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_FECTRANS <= @COMPROBANTEDERETENCIONES_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAALTAFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HALTAFW >= @COMPROBANTEDERETENCIONES_1_HORAALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAALTAFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HALTAFW <= @COMPROBANTEDERETENCIONES_1_HORAALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAEXPO_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HORAEXPO >= @COMPROBANTEDERETENCIONES_1_HORAEXPO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAEXPO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HORAEXPO <= @COMPROBANTEDERETENCIONES_1_HORAEXPO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAIMPO_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HORAIMPO >= @COMPROBANTEDERETENCIONES_1_HORAIMPO_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAIMPO_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HORAIMPO <= @COMPROBANTEDERETENCIONES_1_HORAIMPO_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HMODIFW >= @COMPROBANTEDERETENCIONES_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_HMODIFW <= @COMPROBANTEDERETENCIONES_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_SERIEALTAFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_SALTAFW >= @COMPROBANTEDERETENCIONES_1_SERIEALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_SERIEALTAFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_SALTAFW <= @COMPROBANTEDERETENCIONES_1_SERIEALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_SMODIFW >= @COMPROBANTEDERETENCIONES_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_SMODIFW <= @COMPROBANTEDERETENCIONES_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_USUARIOALTAFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_UALTAFW >= @COMPROBANTEDERETENCIONES_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_USUARIOALTAFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_UALTAFW <= @COMPROBANTEDERETENCIONES_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_UMODIFW >= @COMPROBANTEDERETENCIONES_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_UMODIFW <= @COMPROBANTEDERETENCIONES_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_VERSIONALTAFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_VALTAFW >= @COMPROBANTEDERETENCIONES_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_VERSIONALTAFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_VALTAFW <= @COMPROBANTEDERETENCIONES_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_ITEMCDRIMPUESTOS.CR_VMODIFW >= @COMPROBANTEDERETENCIONES_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDERETENCIONES_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_ITEMCDRIMPUESTOS.CR_VMODIFW <= @COMPROBANTEDERETENCIONES_1_VERSIONMODIFICACIONFW_HASTA ) )

)