IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_FACTURA_ITEMPROMOCIONES_ITEMPROMOCIONES]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_FACTURA_ITEMPROMOCIONES_ITEMPROMOCIONES];
GO;

CREATE FUNCTION [Listados].[GENERICO_FACTURA_ITEMPROMOCIONES_ITEMPROMOCIONES]
( @BaseDeDatos varchar(8),
	@FACTURA_DESPACHOS_DESDE varchar(254),
	@FACTURA_DESPACHOS_HASTA varchar(254),
	@ITEMPROMOCIONES_PROMOCION_DESDE varchar(15),
	@ITEMPROMOCIONES_PROMOCION_HASTA varchar(15),
	@ITEMPROMOCIONES_PROMOCIONDETALLE_DESDE varchar(200),
	@ITEMPROMOCIONES_PROMOCIONDETALLE_HASTA varchar(200),
	@ITEMPROMOCIONES_CANTIDAD_DESDE numeric(8, 0),
	@ITEMPROMOCIONES_CANTIDAD_HASTA numeric(8, 0),
	@FACTURA_1_CODIGO_DESDE varchar(38),
	@FACTURA_1_CODIGO_HASTA varchar(38),
	@FACTURA_1_CLIENTE_DESDE varchar(10),
	@FACTURA_1_CLIENTE_HASTA varchar(10),
	@FACTURA_1_ANULADO bit,
	@FACTURA_1_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE varchar(10),
	@FACTURA_1_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA varchar(10),
	@FACTURA_1_NROOPECOMMERCE_DESDE varchar(254),
	@FACTURA_1_NROOPECOMMERCE_HASTA varchar(254),
	@FACTURA_1_CLIENTEDESCRIPCION_DESDE varchar(185),
	@FACTURA_1_CLIENTEDESCRIPCION_HASTA varchar(185),
	@FACTURA_1_VENDEDOR_DESDE varchar(10),
	@FACTURA_1_VENDEDOR_HASTA varchar(10),
	@FACTURA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURA_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@FACTURA_1_LISTADEPRECIOS_DESDE varchar(6),
	@FACTURA_1_LISTADEPRECIOS_HASTA varchar(6),
	@FACTURA_1_EMAIL_DESDE varchar(250),
	@FACTURA_1_EMAIL_HASTA varchar(250),
	@FACTURA_1_LETRA_DESDE varchar(1),
	@FACTURA_1_LETRA_HASTA varchar(1),
	@FACTURA_1_PUNTODEVENTA_DESDE numeric(4, 0),
	@FACTURA_1_PUNTODEVENTA_HASTA numeric(4, 0),
	@FACTURA_1_NUMERO_DESDE numeric(8, 0),
	@FACTURA_1_NUMERO_HASTA numeric(8, 0),
	@FACTURA_1_FECHA_DESDE datetime,
	@FACTURA_1_FECHA_HASTA datetime,
	@FACTURA_1_COTIZACION_DESDE numeric(15, 5),
	@FACTURA_1_COTIZACION_HASTA numeric(15, 5),
	@FACTURA_1_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@FACTURA_1_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@FACTURA_1_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@FACTURA_1_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@CLIENTE_7_CLIENTE_NOMBRE_DESDE varchar(185),
	@CLIENTE_7_CLIENTE_NOMBRE_HASTA varchar(185),
	@MOTIVODESCUENTOYDEVOLUCION_69_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE varchar(50),
	@MOTIVODESCUENTOYDEVOLUCION_69_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA varchar(50),
	@VENDEDOR_91_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_91_VENDEDOR_NOMBRE_HASTA varchar(60),
	@MONEDA_92_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_92_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@LISTADEPRECIOS_93_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_93_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9338_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9338_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9337_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9337_TIPO_DESCRIPCION_HASTA varchar(50),
	@VENDEDOR_8_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_8_VENDEDOR_NOMBRE_HASTA varchar(60),
	@PAISES_23_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_23_PAIS_DESCRIPCION_HASTA varchar(30),
	@PROVINCIA_25_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_25_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@LISTADEPRECIOS_31_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_31_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@CLASIFICACIONCLIENTE_32_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCLIENTE_32_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@DESCUENTO_35_DESCUENTOPREFERENTE_DESCRIPCION_DESDE varchar(40),
	@DESCUENTO_35_DESCUENTOPREFERENTE_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_36_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_36_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@NOMBREDEFANTASIA_42_CODNOMBREFANTASIA_CODIGO_DESDE varchar(50),
	@NOMBREDEFANTASIA_42_CODNOMBREFANTASIA_CODIGO_HASTA varchar(50),
	@TIPOCLIENTE_43_TIPOCLI_DESCRIPCION_DESDE varchar(50),
	@TIPOCLIENTE_43_TIPOCLI_DESCRIPCION_HASTA varchar(50),
	@CATEGORIACLIENTE_44_CATEGCLI_DESCRIPCION_DESDE varchar(50),
	@CATEGORIACLIENTE_44_CATEGCLI_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_45_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_45_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@IMPUESTO_47_PERCEPCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_47_PERCEPCIONIVA_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_50_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_50_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_59_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_59_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@SUCURSAL_9334_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9334_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9334_LINEA_DESDE varchar(10),
	@SUCURSAL_9334_LINEA_HASTA varchar(10),
	@SUCURSAL_9334_TIPO_DESDE varchar(10),
	@SUCURSAL_9334_TIPO_HASTA varchar(10),
	@SUCURSAL_9334_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9334_DESCRIPCION_HASTA varchar(50),
	@CLIENTE_7_VENDEDOR_DESDE varchar(10),
	@CLIENTE_7_VENDEDOR_HASTA varchar(10),
	@CLIENTE_7_CALLE_DESDE varchar(250),
	@CLIENTE_7_CALLE_HASTA varchar(250),
	@CLIENTE_7_CODIGOPOSTAL_DESDE varchar(8),
	@CLIENTE_7_CODIGOPOSTAL_HASTA varchar(8),
	@CLIENTE_7_CUIT_DESDE varchar(15),
	@CLIENTE_7_CUIT_HASTA varchar(15),
	@CLIENTE_7_DEPARTAMENTO_DESDE varchar(3),
	@CLIENTE_7_DEPARTAMENTO_HASTA varchar(3),
	@CLIENTE_7_EMAIL_DESDE varchar(250),
	@CLIENTE_7_EMAIL_HASTA varchar(250),
	@CLIENTE_7_FAX_DESDE varchar(20),
	@CLIENTE_7_FAX_HASTA varchar(20),
	@CLIENTE_7_FECHANACIMIENTO_DESDE datetime,
	@CLIENTE_7_FECHANACIMIENTO_HASTA datetime,
	@CLIENTE_7_IMAGEN_DESDE varchar(180),
	@CLIENTE_7_IMAGEN_HASTA varchar(180),
	@CLIENTE_7_LOCALIDAD_DESDE varchar(70),
	@CLIENTE_7_LOCALIDAD_HASTA varchar(70),
	@CLIENTE_7_NRODOCUMENTO_DESDE varchar(10),
	@CLIENTE_7_NRODOCUMENTO_HASTA varchar(10),
	@CLIENTE_7_NUMERO_DESDE numeric(5, 0),
	@CLIENTE_7_NUMERO_HASTA numeric(5, 0),
	@CLIENTE_7_PAGINAWEB_DESDE varchar(60),
	@CLIENTE_7_PAGINAWEB_HASTA varchar(60),
	@CLIENTE_7_PAIS_DESDE varchar(3),
	@CLIENTE_7_PAIS_HASTA varchar(3),
	@CLIENTE_7_PISO_DESDE varchar(3),
	@CLIENTE_7_PISO_HASTA varchar(3),
	@CLIENTE_7_PROVINCIA_DESDE varchar(2),
	@CLIENTE_7_PROVINCIA_HASTA varchar(2),
	@SITUACIONFISCAL_26_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@CLIENTE_7_TELEFONO_DESDE varchar(30),
	@CLIENTE_7_TELEFONO_HASTA varchar(30),
	@CLIENTE_7_TIPODOCUMENTO_DESDE varchar(2),
	@CLIENTE_7_TIPODOCUMENTO_HASTA varchar(2),
	@CLIENTE_7_MOVIL_DESDE varchar(30),
	@CLIENTE_7_MOVIL_HASTA varchar(30),
	@CLIENTE_7_TOPECTACTE_DESDE numeric(15, 2),
	@CLIENTE_7_TOPECTACTE_HASTA numeric(15, 2),
	@CLIENTE_7_LISTADEPRECIO_DESDE varchar(6),
	@CLIENTE_7_LISTADEPRECIO_HASTA varchar(6),
	@CLIENTE_7_CLASIFICACION_DESDE varchar(10),
	@CLIENTE_7_CLASIFICACION_HASTA varchar(10),
	@CLIENTE_7_TIPOCONVENIO_DESDE numeric(1, 0),
	@CLIENTE_7_TIPOCONVENIO_HASTA numeric(1, 0),
	@CLIENTE_7_NROIIBB_DESDE numeric(11, 0),
	@CLIENTE_7_NROIIBB_HASTA numeric(11, 0),
	@CLIENTE_7_DESCUENTOPREFERENTE_DESDE varchar(10),
	@CLIENTE_7_DESCUENTOPREFERENTE_HASTA varchar(10),
	@CLIENTE_7_TRANSPORTISTA_DESDE varchar(15),
	@CLIENTE_7_TRANSPORTISTA_HASTA varchar(15),
	@CLIENTE_7_ESTADOCIVIL varchar(13),
	@CLIENTE_7_HIJOS_DESDE numeric(2, 0),
	@CLIENTE_7_HIJOS_HASTA numeric(2, 0),
	@CLIENTE_7_SEXO varchar(10),
	@CLIENTE_7_IDGLOBAL_DESDE varchar(38),
	@CLIENTE_7_IDGLOBAL_HASTA varchar(38),
	@CLIENTE_7_RUT_DESDE varchar(12),
	@CLIENTE_7_RUT_HASTA varchar(12),
	@CLIENTE_7_CODNOMBREFANTASIA_DESDE varchar(50),
	@CLIENTE_7_CODNOMBREFANTASIA_HASTA varchar(50),
	@CLIENTE_7_TIPOCLI_DESDE varchar(10),
	@CLIENTE_7_TIPOCLI_HASTA varchar(10),
	@CLIENTE_7_CATEGCLI_DESDE varchar(10),
	@CLIENTE_7_CATEGCLI_HASTA varchar(10),
	@CLIENTE_7_CONDICIONDEPAGO_DESDE varchar(5),
	@CLIENTE_7_CONDICIONDEPAGO_HASTA varchar(5),
	@CLIENTE_7_SUJETOVINCULADO bit,
	@CLIENTE_7_PERCEPCIONIVA_DESDE varchar(10),
	@CLIENTE_7_PERCEPCIONIVA_HASTA varchar(10),
	@CLIENTE_7_SITUACIONGANANCIAS numeric(1, 0),
	@CLIENTE_7_EXCLUIDOPERCEPCIONIVA bit,
	@CLIENTE_7_PERCEPCIONGANANCIAS_DESDE varchar(10),
	@CLIENTE_7_PERCEPCIONGANANCIAS_HASTA varchar(10),
	@CLIENTE_7_EXCLUIDOPERCEPCIONGANANCIAS bit,
	@CLIENTE_7_CODRECOMENDANTE_DESDE varchar(10),
	@CLIENTE_7_CODRECOMENDANTE_HASTA varchar(10),
	@CLIENTE_7_NOMBRERECOMENDANTE_DESDE varchar(60),
	@CLIENTE_7_NOMBRERECOMENDANTE_HASTA varchar(60),
	@CLIENTE_7_PRIMERNOMBRE_DESDE varchar(60),
	@CLIENTE_7_PRIMERNOMBRE_HASTA varchar(60),
	@CLIENTE_7_SEGUNDONOMBRE_DESDE varchar(60),
	@CLIENTE_7_SEGUNDONOMBRE_HASTA varchar(60),
	@CLIENTE_7_APELLIDO_DESDE varchar(60),
	@CLIENTE_7_APELLIDO_HASTA varchar(60),
	@CLIENTE_7_VIGENCIAHASTAIVA_DESDE datetime,
	@CLIENTE_7_VIGENCIAHASTAIVA_HASTA datetime,
	@CLIENTE_7_VIGENCIAHASTAGAN_DESDE datetime,
	@CLIENTE_7_VIGENCIAHASTAGAN_HASTA datetime,
	@CLIENTE_7_CODIGOSIPRIB_DESDE varchar(20),
	@CLIENTE_7_CODIGOSIPRIB_HASTA varchar(20),
	@CLIENTE_7_TASACEROPORCEN_DESDE numeric(6, 2),
	@CLIENTE_7_TASACEROPORCEN_HASTA numeric(6, 2),
	@CLIENTE_7_TASACEROAPLICA bit,
	@CLIENTE_7_INACTIVOFW bit,
	@MOTIVODESCUENTOYDEVOLUCION_69_TIPO numeric(1, 0),
	@SUCURSAL_9334_CODIGO_DESDE varchar(10),
	@SUCURSAL_9334_CODIGO_HASTA varchar(10),
	@ITEMPROMOCIONES_NROITEM_DESDE numeric(5, 0),
	@ITEMPROMOCIONES_NROITEM_HASTA numeric(5, 0),
	@FACTURA_1_FECHAALTAFW_DESDE datetime,
	@FACTURA_1_FECHAALTAFW_HASTA datetime,
	@FACTURA_1_HORAALTAFW_DESDE varchar(8),
	@FACTURA_1_HORAALTAFW_HASTA varchar(8),
	@FACTURA_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@FACTURA_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@FACTURA_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@FACTURA_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@FACTURA_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@FACTURA_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@FACTURA_1_FECHAEXPO_DESDE datetime,
	@FACTURA_1_FECHAEXPO_HASTA datetime,
	@FACTURA_1_FECHAIMPO_DESDE datetime,
	@FACTURA_1_FECHAIMPO_HASTA datetime,
	@FACTURA_1_FECHAMODIFICACIONFW_DESDE datetime,
	@FACTURA_1_FECHAMODIFICACIONFW_HASTA datetime,
	@FACTURA_1_FECHATRANSFERENCIA_DESDE datetime,
	@FACTURA_1_FECHATRANSFERENCIA_HASTA datetime,
	@FACTURA_1_HORAEXPO_DESDE varchar(8),
	@FACTURA_1_HORAEXPO_HASTA varchar(8),
	@FACTURA_1_HORAIMPO_DESDE varchar(8),
	@FACTURA_1_HORAIMPO_HASTA varchar(8),
	@FACTURA_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@FACTURA_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@FACTURA_1_SERIEALTAFW_DESDE varchar(7),
	@FACTURA_1_SERIEALTAFW_HASTA varchar(7),
	@FACTURA_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@FACTURA_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@FACTURA_1_USUARIOALTAFW_DESDE varchar(100),
	@FACTURA_1_USUARIOALTAFW_HASTA varchar(100),
	@FACTURA_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@FACTURA_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@FACTURA_1_VERSIONALTAFW_DESDE varchar(13),
	@FACTURA_1_VERSIONALTAFW_HASTA varchar(13),
	@FACTURA_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@FACTURA_1_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itempromociones.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMPROMOCIONES__Grupo,
	@basededatos as ITEMPROMOCIONES__BD,
	c_ITEMPROMOCIONES.CODIGO as ITEMPROMOCIONES_Codigo,
	c_ITEMPROMOCIONES.PROMO as ITEMPROMOCIONES_Promo,
	c_ITEMPROMOCIONES.DESCRIP as ITEMPROMOCIONES_descrip,
	c_ITEMPROMOCIONES.CANTIDAD as ITEMPROMOCIONES_Cantidad,
	C_FACTURA.CODIGO as FACTURA_CODIGO,
	C_FACTURA.FPERSON as FACTURA_FPerson,
	C_CLIENTE.CIMAGEN as CLIENTE_CIMAGEN,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fsubtot as numeric( 15, 4 ) ) as FACTURA_FSubTOT,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fsubton as numeric( 15, 4 ) ) as FACTURA_fSubToN,
	C_FACTURA.ANULADO as FACTURA_Anulado,
	cast( c_factura.signomov*c_factura.totalcant as numeric( 16, 3 ) ) as FACTURA_TotalCant,
	C_FACTURA.MOTDESCDEV as FACTURA_MotDescDev,
	C_FACTURA.OPECOMM as FACTURA_OPEcomm,
	C_FACTURA.FCLIENTE as FACTURA_FCLIENTE,
	C_FACTURA.FVEN as FACTURA_FVEN,
	C_FACTURA.MONEDA as FACTURA_Moneda,
	C_FACTURA.CODLISTA as FACTURA_CodLista,
	C_FACTURA.EMAIL as FACTURA_Email,
	C_FACTURA.FLETRA as FACTURA_FLETRA,
	C_FACTURA.FPTOVEN as FACTURA_FPTOVEN,
	C_FACTURA.FNUMCOMP as FACTURA_FNUMCOMP,
	case when c_factura.ffch = '01/01/1900 00:00:00' then null else c_factura.ffch end as FACTURA_FFCH,
	C_FACTURA.COTIZ as FACTURA_Cotiz,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.fajxre as numeric( 15, 2 ) ) as FACTURA_FAjXRe,
	C_FACTURA.FPODES as FACTURA_FPODES,
	C_FACTURA.RECPOR as FACTURA_RecPor,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.mr as numeric( 15, 2 ) ) as FACTURA_MR,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.mr2 as numeric( 15, 2 ) ) as FACTURA_MR2,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.percepcion as numeric( 15, 2 ) ) as FACTURA_percepcion,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.gravamen as numeric( 15, 2 ) ) as FACTURA_gravamen,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.totrecarsi as numeric( 15, 4 ) ) as FACTURA_totrecarSI,
	cast( c_factura.signomov*c_factura.cotiz*c_factura.trci as numeric( 15, 4 ) ) as FACTURA_TRCI,
	cast( c_factura.signomov*c_factura.cotiz*-1*c_factura.totdescsi as numeric( 15, 4 ) ) as FACTURA_totdescSI,
	cast( c_factura.signomov*c_factura.cotiz*-1*c_factura.tdci as numeric( 15, 4 ) ) as FACTURA_TDCI,
	C_FACTURA.FOBS as FACTURA_FObs,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CLIENTE.CLVEND as CLIENTE_CLVend,
	C_CLIENTE.CLCALLE as CLIENTE_CLCalle,
	C_CLIENTE.CLCP as CLIENTE_CLCP,
	C_CLIENTE.CLCUIT as CLIENTE_CLCUIT,
	C_CLIENTE.CLDEPTO as CLIENTE_CLDEPTO,
	C_CLIENTE.CLEMAIL as CLIENTE_CLEMAIL,
	C_CLIENTE.CLFAX as CLIENTE_CLFAX,
	case when c_cliente.clfecha = '01/01/1900 00:00:00' then null else c_cliente.clfecha end as CLIENTE_CLFECHA,
	C_CLIENTE.CLLOC as CLIENTE_CLLOC,
	C_CLIENTE.CLNRODOC as CLIENTE_CLNRODOC,
	C_CLIENTE.CLNRO as CLIENTE_CLNro,
	C_CLIENTE.CLOBS as CLIENTE_CLOBS,
	C_CLIENTE.CLPAGEWEB as CLIENTE_CLPAGEWEB,
	C_CLIENTE.CLPAIS as CLIENTE_CLPAIS,
	C_CLIENTE.CLPISO as CLIENTE_ClPiso,
	C_CLIENTE.CLPRV as CLIENTE_CLPRV,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_CLIENTE.CLTLF as CLIENTE_CLTLF,
	C_CLIENTE.CLTIPODOC as CLIENTE_CLTIPODOC,
	C_CLIENTE.CLMOVIL as CLIENTE_CLMovil,
	C_CLIENTE.CLTOPECCTE as CLIENTE_CLTOPECCTE,
	C_CLIENTE.CLLISPREC as CLIENTE_CLLisPrec,
	C_CLIENTE.CLCLAS as CLIENTE_CLCLAS,
	C_CLIENTE.CLTIPCONV as CLIENTE_CLTIPCONV,
	C_CLIENTE.CLNROIIBB as CLIENTE_CLNROIIBB,
	C_CLIENTE.CLCO_DTO as CLIENTE_CLCO_DTO,
	C_CLIENTE.CLTRANS as CLIENTE_CLTRANS,
	C_CLIENTE.ESTADO as CLIENTE_Estado,
	C_CLIENTE.HIJOS as CLIENTE_Hijos,
	C_CLIENTE.SEXO as CLIENTE_Sexo,
	C_CLIENTE.GLOBALID as CLIENTE_globalid,
	C_CLIENTE.RUT as CLIENTE_RUT,
	C_CLIENTE.CLCODFANT as CLIENTE_CLCODFANT,
	C_CLIENTE.CLTIPOCLI as CLIENTE_CLTipoCli,
	C_CLIENTE.CLCATEGCLI as CLIENTE_CLCategCli,
	C_CLIENTE.CLCONDPAG as CLIENTE_CLCONDPAG,
	C_CLIENTE.CLSUJVINC as CLIENTE_CLSujVinc,
	C_CLIENTE.CLPERTIVA as CLIENTE_CLPERTIVA,
	C_CLIENTE.CLSITGAN as CLIENTE_CLSITGAN,
	C_CLIENTE.EXPERIVA as CLIENTE_EXPERIVA,
	C_CLIENTE.CLPERGAN as CLIENTE_CLPERGAN,
	C_CLIENTE.EXPERGAN as CLIENTE_EXPERGAN,
	C_CLIENTE.CODRECOM as CLIENTE_CODRECOM,
	C_CLIENTE.NOMRECOM as CLIENTE_NOMRECOM,
	C_CLIENTE.CLPRINOM as CLIENTE_CLPRINOM,
	C_CLIENTE.CLSEGNOM as CLIENTE_CLSEGNOM,
	C_CLIENTE.CLAPELL as CLIENTE_CLAPELL,
	case when c_cliente.vhastaiva = '01/01/1900 00:00:00' then null else c_cliente.vhastaiva end as CLIENTE_VHastaIva,
	case when c_cliente.vhastagan = '01/01/1900 00:00:00' then null else c_cliente.vhastagan end as CLIENTE_VHastaGan,
	C_CLIENTE.CLSIPRIB as CLIENTE_CLSIPRIB,
	C_CLIENTE.PORCENTC as CLIENTE_PorcenTC,
	C_CLIENTE.APLICATC as CLIENTE_AplicaTC,
	C_CLIENTE.INACTIVOFW as CLIENTE_InactivoFW,
	C_MOTIVODESCUENTOYDEVOLUCION.TIPO as MOTIVODESCUENTOYDEVOLUCION_Tipo,
	C_MOTIVODESCUENTOYDEVOLUCION.OBS as MOTIVODESCUENTOYDEVOLUCION_Obs,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMPROMOCIONES.NROITEM as ITEMPROMOCIONES_NROITEM,
	case when c_factura.faltafw = '01/01/1900 00:00:00' then null else c_factura.faltafw end as FACTURA_FAltaFW,
	C_FACTURA.HALTAFW as FACTURA_HAltaFW,
	C_FACTURA.BDALTAFW as FACTURA_BDALTAFW,
	C_FACTURA.BDMODIFW as FACTURA_BDMODIFW,
	C_FACTURA.ESTTRANS as FACTURA_ESTTRANS,
	case when c_factura.fecexpo = '01/01/1900 00:00:00' then null else c_factura.fecexpo end as FACTURA_FECEXPO,
	case when c_factura.fecimpo = '01/01/1900 00:00:00' then null else c_factura.fecimpo end as FACTURA_FECIMPO,
	case when c_factura.fmodifw = '01/01/1900 00:00:00' then null else c_factura.fmodifw end as FACTURA_FMODIFW,
	case when c_factura.fectrans = '01/01/1900 00:00:00' then null else c_factura.fectrans end as FACTURA_FECTRANS,
	C_FACTURA.HORAEXPO as FACTURA_HORAEXPO,
	C_FACTURA.HORAIMPO as FACTURA_HORAIMPO,
	C_FACTURA.HMODIFW as FACTURA_HMODIFW,
	C_FACTURA.SALTAFW as FACTURA_SALTAFW,
	C_FACTURA.SMODIFW as FACTURA_SMODIFW,
	C_FACTURA.UALTAFW as FACTURA_UALTAFW,
	C_FACTURA.UMODIFW as FACTURA_UMODIFW,
	C_FACTURA.VALTAFW as FACTURA_VALTAFW,
	C_FACTURA.VMODIFW as FACTURA_VMODIFW,
	C_FACTURA.ZADSFW as FACTURA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMPROMOCIONES__SUCURSAL,
	cast( funciones.identificadordecomprobanteparalistado(c_factura.facttipo, c_factura.fletra, c_factura.fptoven, c_factura.fnumcomp) as varchar( 20 ) ) as FACTURA_1_ComprobanteVirtual,
	cast( funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 2) as numeric( 15, 2 ) ) as ITEMPROMOCIONES_MontoAfectadoVirtual,
	cast( case when row_number() over(partition by c_itempromociones.codigo order by c_itempromociones.codigo, c_itempromociones.tipo) = 1 then funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 1) else null end as numeric( 15, 2 ) ) as ITEMPROMOCIONES_MontoSinPromoVirtual,
	cast( case when row_number() over(partition by c_itempromociones.codigo order by c_itempromociones.codigo, c_itempromociones.tipo) = 1 then funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 3) else null end as numeric( 15, 2 ) ) as ITEMPROMOCIONES_OtrosDescuentosVirtual,
	cast( case when row_number() over(partition by c_itempromociones.codigo order by c_itempromociones.codigo, c_itempromociones.tipo) = 1 then funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 4) else null end as numeric( 15, 2 ) ) as ITEMPROMOCIONES_RecargodVirtual,
	cast( funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 5) as numeric( 15, 2 ) ) as ITEMPROMOCIONES_NCPromoBancariaVirtual,
	cast( funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 6) as numeric( 15, 2 ) ) as ITEMPROMOCIONES_NCPendientesVirtual,
	cast( case when row_number() over(partition by c_itempromociones.codigo order by c_itempromociones.codigo, c_itempromociones.tipo) = 1 then funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 0) else null end as numeric( 15, 2 ) ) as ITEMPROMOCIONES_MontoBrutoVirtual,
	cast( case when row_number() over(partition by c_itempromociones.codigo order by c_itempromociones.codigo, c_itempromociones.tipo) = 1 then funciones.obtenermontosegunafectaciondeunapromocion(c_itempromociones.codigo, c_itempromociones.iditem, 7) else null end as numeric( 15, 2 ) ) as ITEMPROMOCIONES_MontoTotalVirtual,
	cast( c_itempromociones.beneficio*c_factura.signomov as numeric( 15, 2 ) ) as ITEMPROMOCIONES_Beneficio,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.fimpuesto*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_fImpuesto,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.ftotal*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_FTotal,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.fvuelto*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_FVuelto,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.totimpue*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_totimpue,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.md2*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_MD2,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.md3*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_MD3,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.mr1*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_MR1,
	cast( case when row_number() over(partition by c_factura.codigo order by c_factura.codigo) = 1 then c_factura.fdescu*c_factura.signomov else null end as numeric( 15, 2 ) ) as FACTURA_fDescu,
	cast( funciones.obtenernumerodecaedelcomprobante(c_factura.codigo) as varchar( 20 ) ) as FACTURA_1_CaeVirtual,
	C_FACTURA.DESPACHOS as FACTURA_Despachos,
	C_PROMOCION.DESCRIP as PROMOCION_Descrip,
	C_CLIENTE.CLNOM as CLIENTE_CLNOM,
	C_MOTIVODESCUENTOYDEVOLUCION.DESCRIP as MOTIVODESCUENTOYDEVOLUCION_Descrip,
	C_VENDEDOR91.CLNOM as VENDEDOR91_CLNOM,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_LISTADEPRECIOS93.LPR_NOMBRE as LISTADEPRECIOS93_LPR_NOMBRE,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_VENDEDOR8.CLNOM as VENDEDOR8_CLNOM,
	C_PAISES.PDES as PAISES_pdes,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_CLIENTE.CLIVA as CLIENTE_CLIVA,
	C_LISTADEPRECIOS31.LPR_NOMBRE as LISTADEPRECIOS31_LPR_NOMBRE,
	C_CLASIFICACIONCLIENTE.CLADES as CLASIFICACIONCLIENTE_CLADES,
	C_DESCUENTO.DES as DESCUENTO_Des,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_NOMBREDEFANTASIA.NFCOD as NOMBREDEFANTASIA_NFCOD,
	C_TIPOCLIENTE.TCDES as TIPOCLIENTE_TCDES,
	C_CATEGORIACLIENTE.CGDES as CATEGORIACLIENTE_CGDes,
	C_CONDICIONDEPAGO.CLNOM as CONDICIONDEPAGO_CLNOM,
	C_IMPUESTO47.DESCRIP as IMPUESTO47_descrip,
	C_IMPUESTO50.DESCRIP as IMPUESTO50_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_CATEGORIACLIENTE.CGCOD as CATEGORIACLIENTE_CGCod,
	C_CLASIFICACIONCLIENTE.CLACOD as CLASIFICACIONCLIENTE_CLACOD,
	C_CLIENTE.CLCOD as CLIENTE_CLCOD,
	C_CONDICIONDEPAGO.CLCOD as CONDICIONDEPAGO_CLCOD,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_DESCUENTO.CODIGO as DESCUENTO_codigo,
	C_IMPUESTO47.CODIGO as IMPUESTO47_codigo,
	C_IMPUESTO50.CODIGO as IMPUESTO50_codigo,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS31.LPR_NUMERO as LISTADEPRECIOS31_LPR_NUMERO,
	C_LISTADEPRECIOS93.LPR_NUMERO as LISTADEPRECIOS93_LPR_NUMERO,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_MOTIVODESCUENTOYDEVOLUCION.CODIGO as MOTIVODESCUENTOYDEVOLUCION_Codigo,
	C_PAISES.PCOD as PAISES_pcod,
	C_PROMOCION.CODIGO as PROMOCION_Codigo,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TIPOCLIENTE.TCCOD as TIPOCLIENTE_TCCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_VENDEDOR8.CLCOD as VENDEDOR8_CLCOD,
	C_VENDEDOR91.CLCOD as VENDEDOR91_CLCOD
 from ZooLogic.PROMDET as c_ITEMPROMOCIONES
 left join ZooLogic.COMPROBANTEV as C_FACTURA on C_FACTURA.CODIGO = C_ITEMPROMOCIONES.CODIGO and 0 = Funciones.empty( C_ITEMPROMOCIONES.CODIGO )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS93 on C_LISTADEPRECIOS93.LPR_NUMERO = C_FACTURA.CODLISTA and 0 = Funciones.empty( C_FACTURA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_FACTURA.MONEDA and 0 = Funciones.empty( C_FACTURA.MONEDA )
 left join ZooLogic.MOTIVODESCDEV as C_MOTIVODESCUENTOYDEVOLUCION on C_MOTIVODESCUENTOYDEVOLUCION.CODIGO = C_FACTURA.MOTDESCDEV and 0 = Funciones.empty( C_FACTURA.MOTDESCDEV )
 left join ZooLogic.PROMOS as C_PROMOCION on C_PROMOCION.CODIGO = C_ITEMPROMOCIONES.PROMO and 0 = Funciones.empty( C_ITEMPROMOCIONES.PROMO )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.VEN as C_VENDEDOR91 on C_VENDEDOR91.CLCOD = C_FACTURA.FVEN and 0 = Funciones.empty( C_FACTURA.FVEN )
 left join ZooLogic.CLI as C_CLIENTE on C_CLIENTE.CLCOD = C_FACTURA.FPERSON and 0 = Funciones.empty( C_FACTURA.FPERSON )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO on C_CONDICIONDEPAGO.CLCOD = C_CLIENTE.CLCONDPAG and 0 = Funciones.empty( C_CLIENTE.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_CLIENTE.CLSIPRIB and 0 = Funciones.empty( C_CLIENTE.CLSIPRIB )
 left join ZooLogic.DESCUENTOS as C_DESCUENTO on C_DESCUENTO.CODIGO = C_CLIENTE.CLCO_DTO and 0 = Funciones.empty( C_CLIENTE.CLCO_DTO )
 left join ZooLogic.IMPUESTO as C_IMPUESTO47 on C_IMPUESTO47.CODIGO = C_CLIENTE.CLPERTIVA and 0 = Funciones.empty( C_CLIENTE.CLPERTIVA )
 left join ZooLogic.IMPUESTO as C_IMPUESTO50 on C_IMPUESTO50.CODIGO = C_CLIENTE.CLPERGAN and 0 = Funciones.empty( C_CLIENTE.CLPERGAN )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS31 on C_LISTADEPRECIOS31.LPR_NUMERO = C_CLIENTE.CLLISPREC and 0 = Funciones.empty( C_CLIENTE.CLLISPREC )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_CLIENTE.CLPAIS and 0 = Funciones.empty( C_CLIENTE.CLPAIS )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_CLIENTE.CLPRV and 0 = Funciones.empty( C_CLIENTE.CLPRV )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_CLIENTE.CLIVA and 0 = Funciones.empty( C_CLIENTE.CLIVA )
 left join ZooLogic.TIPOCLI as C_TIPOCLIENTE on C_TIPOCLIENTE.TCCOD = C_CLIENTE.CLTIPOCLI and 0 = Funciones.empty( C_CLIENTE.CLTIPOCLI )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_CLIENTE.CLTRANS and 0 = Funciones.empty( C_CLIENTE.CLTRANS )
 left join ZooLogic.VEN as C_VENDEDOR8 on C_VENDEDOR8.CLCOD = C_CLIENTE.CLVEND and 0 = Funciones.empty( C_CLIENTE.CLVEND )
 left join ZooLogic.NOMFANT as C_NOMBREDEFANTASIA on C_NOMBREDEFANTASIA.NFCOD = C_CLIENTE.CLCODFANT and 0 = Funciones.empty( C_CLIENTE.CLCODFANT )
 left join ZooLogic.CATCLI as C_CATEGORIACLIENTE on C_CATEGORIACLIENTE.CGCOD = C_CLIENTE.CLCATEGCLI and 0 = Funciones.empty( C_CLIENTE.CLCATEGCLI )
 left join ZooLogic.CLASIF as C_CLASIFICACIONCLIENTE on C_CLASIFICACIONCLIENTE.CLACOD = C_CLIENTE.CLCLAS and 0 = Funciones.empty( C_CLIENTE.CLCLAS )
 where ( 1=1 ) and 
	( C_FACTURA.FACTTIPO not in ( 11, 12, 23, 25 ) ) and
	--( ( @FACTURA_DESPACHOS_DESDE is null ) OR ( C_FACTURA.Despachos >= @FACTURA_DESPACHOS_DESDE ) ) and 
	--( ( @FACTURA_DESPACHOS_HASTA is null ) OR ( C_FACTURA.Despachos <= @FACTURA_DESPACHOS_HASTA ) ) and 
	( ( @FACTURA_DESPACHOS_DESDE is null ) OR (Funciones.Alltrim(c_factura.Despachos) LIKE '%' + Funciones.Alltrim(@FACTURA_DESPACHOS_DESDE) + '%') ) and
 	( ( @ITEMPROMOCIONES_PROMOCION_DESDE is null ) OR ( c_ITEMPROMOCIONES.Promo >= @ITEMPROMOCIONES_PROMOCION_DESDE ) ) and 
	( ( @ITEMPROMOCIONES_PROMOCION_HASTA is null ) OR ( c_ITEMPROMOCIONES.Promo <= @ITEMPROMOCIONES_PROMOCION_HASTA ) ) and 
	( ( @ITEMPROMOCIONES_PROMOCIONDETALLE_DESDE is null ) OR ( c_ITEMPROMOCIONES.descrip >= @ITEMPROMOCIONES_PROMOCIONDETALLE_DESDE ) ) and 
	( ( @ITEMPROMOCIONES_PROMOCIONDETALLE_HASTA is null ) OR ( c_ITEMPROMOCIONES.descrip <= @ITEMPROMOCIONES_PROMOCIONDETALLE_HASTA ) ) and 
	( ( @ITEMPROMOCIONES_CANTIDAD_DESDE is null ) OR ( c_ITEMPROMOCIONES.Cantidad >= @ITEMPROMOCIONES_CANTIDAD_DESDE ) ) and 
	( ( @ITEMPROMOCIONES_CANTIDAD_HASTA is null ) OR ( c_ITEMPROMOCIONES.Cantidad <= @ITEMPROMOCIONES_CANTIDAD_HASTA ) ) and 
	( ( @FACTURA_1_CODIGO_DESDE is null ) OR ( C_FACTURA.CODIGO >= @FACTURA_1_CODIGO_DESDE ) ) and 
	( ( @FACTURA_1_CODIGO_HASTA is null ) OR ( C_FACTURA.CODIGO <= @FACTURA_1_CODIGO_HASTA ) ) and 
	( ( @FACTURA_1_CLIENTE_DESDE is null ) OR ( C_FACTURA.FPerson >= @FACTURA_1_CLIENTE_DESDE ) ) and 
	( ( @FACTURA_1_CLIENTE_HASTA is null ) OR ( C_FACTURA.FPerson <= @FACTURA_1_CLIENTE_HASTA ) ) and 
	( ( @FACTURA_1_ANULADO is null ) OR ( C_FACTURA.Anulado = @FACTURA_1_ANULADO ) ) and 
	( ( @FACTURA_1_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE is null ) OR ( C_FACTURA.MotDescDev >= @FACTURA_1_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESDE ) ) and 
	( ( @FACTURA_1_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA is null ) OR ( C_FACTURA.MotDescDev <= @FACTURA_1_CODIGOMOTIVODESCUENTOENSUBTOTAL_HASTA ) ) and 
	( ( @FACTURA_1_NROOPECOMMERCE_DESDE is null ) OR ( C_FACTURA.OPEcomm >= @FACTURA_1_NROOPECOMMERCE_DESDE ) ) and 
	( ( @FACTURA_1_NROOPECOMMERCE_HASTA is null ) OR ( C_FACTURA.OPEcomm <= @FACTURA_1_NROOPECOMMERCE_HASTA ) ) and 
	( ( @FACTURA_1_CLIENTEDESCRIPCION_DESDE is null ) OR ( C_FACTURA.FCLIENTE >= @FACTURA_1_CLIENTEDESCRIPCION_DESDE ) ) and 
	( ( @FACTURA_1_CLIENTEDESCRIPCION_HASTA is null ) OR ( C_FACTURA.FCLIENTE <= @FACTURA_1_CLIENTEDESCRIPCION_HASTA ) ) and 
	( ( @FACTURA_1_VENDEDOR_DESDE is null ) OR ( C_FACTURA.FVEN >= @FACTURA_1_VENDEDOR_DESDE ) ) and 
	( ( @FACTURA_1_VENDEDOR_HASTA is null ) OR ( C_FACTURA.FVEN <= @FACTURA_1_VENDEDOR_HASTA ) ) and 
	( ( @FACTURA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_FACTURA.Moneda >= @FACTURA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @FACTURA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_FACTURA.Moneda <= @FACTURA_1_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @FACTURA_1_LISTADEPRECIOS_DESDE is null ) OR ( C_FACTURA.CodLista >= @FACTURA_1_LISTADEPRECIOS_DESDE ) ) and 
	( ( @FACTURA_1_LISTADEPRECIOS_HASTA is null ) OR ( C_FACTURA.CodLista <= @FACTURA_1_LISTADEPRECIOS_HASTA ) ) and 
	( ( @FACTURA_1_EMAIL_DESDE is null ) OR ( C_FACTURA.Email >= @FACTURA_1_EMAIL_DESDE ) ) and 
	( ( @FACTURA_1_EMAIL_HASTA is null ) OR ( C_FACTURA.Email <= @FACTURA_1_EMAIL_HASTA ) ) and 
	( ( @FACTURA_1_LETRA_DESDE is null ) OR ( C_FACTURA.FLETRA >= @FACTURA_1_LETRA_DESDE ) ) and 
	( ( @FACTURA_1_LETRA_HASTA is null ) OR ( C_FACTURA.FLETRA <= @FACTURA_1_LETRA_HASTA ) ) and 
	( ( @FACTURA_1_PUNTODEVENTA_DESDE is null ) OR ( C_FACTURA.FPTOVEN >= @FACTURA_1_PUNTODEVENTA_DESDE ) ) and 
	( ( @FACTURA_1_PUNTODEVENTA_HASTA is null ) OR ( C_FACTURA.FPTOVEN <= @FACTURA_1_PUNTODEVENTA_HASTA ) ) and 
	( ( @FACTURA_1_NUMERO_DESDE is null ) OR ( C_FACTURA.FNUMCOMP >= @FACTURA_1_NUMERO_DESDE ) ) and 
	( ( @FACTURA_1_NUMERO_HASTA is null ) OR ( C_FACTURA.FNUMCOMP <= @FACTURA_1_NUMERO_HASTA ) ) and 
	( ( @FACTURA_1_FECHA_DESDE is null ) OR ( C_FACTURA.FFCH >= @FACTURA_1_FECHA_DESDE ) ) and 
	( ( @FACTURA_1_FECHA_HASTA is null ) OR ( C_FACTURA.FFCH <= @FACTURA_1_FECHA_HASTA ) ) and 
	( ( @FACTURA_1_COTIZACION_DESDE is null ) OR ( C_FACTURA.Cotiz >= @FACTURA_1_COTIZACION_DESDE ) ) and 
	( ( @FACTURA_1_COTIZACION_HASTA is null ) OR ( C_FACTURA.Cotiz <= @FACTURA_1_COTIZACION_HASTA ) ) and 
	( ( @FACTURA_1_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_FACTURA.FPODES >= @FACTURA_1_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @FACTURA_1_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_FACTURA.FPODES <= @FACTURA_1_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @FACTURA_1_RECARGOPORCENTAJE_DESDE is null ) OR ( C_FACTURA.RecPor >= @FACTURA_1_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @FACTURA_1_RECARGOPORCENTAJE_HASTA is null ) OR ( C_FACTURA.RecPor <= @FACTURA_1_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @CLIENTE_7_CLIENTE_NOMBRE_DESDE is null ) OR ( C_CLIENTE.CLNOM >= @CLIENTE_7_CLIENTE_NOMBRE_DESDE ) ) and 
	( ( @CLIENTE_7_CLIENTE_NOMBRE_HASTA is null ) OR ( C_CLIENTE.CLNOM <= @CLIENTE_7_CLIENTE_NOMBRE_HASTA ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_69_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION.Descrip >= @MOTIVODESCUENTOYDEVOLUCION_69_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_DESDE ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_69_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION.Descrip <= @MOTIVODESCUENTOYDEVOLUCION_69_CODIGOMOTIVODESCUENTOENSUBTOTAL_DESCR_HASTA ) ) and 
	( ( @VENDEDOR_91_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR91.CLNOM >= @VENDEDOR_91_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_91_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR91.CLNOM <= @VENDEDOR_91_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @MONEDA_92_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_92_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_92_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_92_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_93_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS93.LPR_NOMBRE >= @LISTADEPRECIOS_93_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_93_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS93.LPR_NOMBRE <= @LISTADEPRECIOS_93_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9339_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9338_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9338_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9338_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9338_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9337_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_8_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR8.CLNOM >= @VENDEDOR_8_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_8_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR8.CLNOM <= @VENDEDOR_8_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @PAISES_23_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_23_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_23_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_23_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_25_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_25_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_25_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_25_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_31_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS31.LPR_NOMBRE >= @LISTADEPRECIOS_31_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_31_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS31.LPR_NOMBRE <= @LISTADEPRECIOS_31_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @CLASIFICACIONCLIENTE_32_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES >= @CLASIFICACIONCLIENTE_32_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCLIENTE_32_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCLIENTE.CLADES <= @CLASIFICACIONCLIENTE_32_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @DESCUENTO_35_DESCUENTOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_DESCUENTO.Des >= @DESCUENTO_35_DESCUENTOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @DESCUENTO_35_DESCUENTOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_DESCUENTO.Des <= @DESCUENTO_35_DESCUENTOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_36_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_36_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_36_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_36_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @NOMBREDEFANTASIA_42_CODNOMBREFANTASIA_CODIGO_DESDE is null ) OR ( C_NOMBREDEFANTASIA.NFCOD >= @NOMBREDEFANTASIA_42_CODNOMBREFANTASIA_CODIGO_DESDE ) ) and 
	( ( @NOMBREDEFANTASIA_42_CODNOMBREFANTASIA_CODIGO_HASTA is null ) OR ( C_NOMBREDEFANTASIA.NFCOD <= @NOMBREDEFANTASIA_42_CODNOMBREFANTASIA_CODIGO_HASTA ) ) and 
	( ( @TIPOCLIENTE_43_TIPOCLI_DESCRIPCION_DESDE is null ) OR ( C_TIPOCLIENTE.TCDES >= @TIPOCLIENTE_43_TIPOCLI_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOCLIENTE_43_TIPOCLI_DESCRIPCION_HASTA is null ) OR ( C_TIPOCLIENTE.TCDES <= @TIPOCLIENTE_43_TIPOCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIACLIENTE_44_CATEGCLI_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIACLIENTE.CGDes >= @CATEGORIACLIENTE_44_CATEGCLI_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIACLIENTE_44_CATEGCLI_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIACLIENTE.CGDes <= @CATEGORIACLIENTE_44_CATEGCLI_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_45_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO.CLNOM >= @CONDICIONDEPAGO_45_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_45_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO.CLNOM <= @CONDICIONDEPAGO_45_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_47_PERCEPCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO47.descrip >= @IMPUESTO_47_PERCEPCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_47_PERCEPCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO47.descrip <= @IMPUESTO_47_PERCEPCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_50_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO50.descrip >= @IMPUESTO_50_PERCEPCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_50_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO50.descrip <= @IMPUESTO_50_PERCEPCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_59_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_59_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_59_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_59_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9334_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9334_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9334_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9334_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9334_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9334_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9334_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9334_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9334_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9334_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9334_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9334_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9334_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9334_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9334_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9334_DESCRIPCION_HASTA ) ) and 
	( ( @CLIENTE_7_VENDEDOR_DESDE is null ) OR ( C_CLIENTE.CLVend >= @CLIENTE_7_VENDEDOR_DESDE ) ) and 
	( ( @CLIENTE_7_VENDEDOR_HASTA is null ) OR ( C_CLIENTE.CLVend <= @CLIENTE_7_VENDEDOR_HASTA ) ) and 
	( ( @CLIENTE_7_CALLE_DESDE is null ) OR ( C_CLIENTE.CLCalle >= @CLIENTE_7_CALLE_DESDE ) ) and 
	( ( @CLIENTE_7_CALLE_HASTA is null ) OR ( C_CLIENTE.CLCalle <= @CLIENTE_7_CALLE_HASTA ) ) and 
	( ( @CLIENTE_7_CODIGOPOSTAL_DESDE is null ) OR ( C_CLIENTE.CLCP >= @CLIENTE_7_CODIGOPOSTAL_DESDE ) ) and 
	( ( @CLIENTE_7_CODIGOPOSTAL_HASTA is null ) OR ( C_CLIENTE.CLCP <= @CLIENTE_7_CODIGOPOSTAL_HASTA ) ) and 
	( ( @CLIENTE_7_CUIT_DESDE is null ) OR ( C_CLIENTE.CLCUIT >= @CLIENTE_7_CUIT_DESDE ) ) and 
	( ( @CLIENTE_7_CUIT_HASTA is null ) OR ( C_CLIENTE.CLCUIT <= @CLIENTE_7_CUIT_HASTA ) ) and 
	( ( @CLIENTE_7_DEPARTAMENTO_DESDE is null ) OR ( C_CLIENTE.CLDEPTO >= @CLIENTE_7_DEPARTAMENTO_DESDE ) ) and 
	( ( @CLIENTE_7_DEPARTAMENTO_HASTA is null ) OR ( C_CLIENTE.CLDEPTO <= @CLIENTE_7_DEPARTAMENTO_HASTA ) ) and 
	( ( @CLIENTE_7_EMAIL_DESDE is null ) OR ( C_CLIENTE.CLEMAIL >= @CLIENTE_7_EMAIL_DESDE ) ) and 
	( ( @CLIENTE_7_EMAIL_HASTA is null ) OR ( C_CLIENTE.CLEMAIL <= @CLIENTE_7_EMAIL_HASTA ) ) and 
	( ( @CLIENTE_7_FAX_DESDE is null ) OR ( C_CLIENTE.CLFAX >= @CLIENTE_7_FAX_DESDE ) ) and 
	( ( @CLIENTE_7_FAX_HASTA is null ) OR ( C_CLIENTE.CLFAX <= @CLIENTE_7_FAX_HASTA ) ) and 
	( ( @CLIENTE_7_FECHANACIMIENTO_DESDE is null ) OR ( C_CLIENTE.CLFECHA >= @CLIENTE_7_FECHANACIMIENTO_DESDE ) ) and 
	( ( @CLIENTE_7_FECHANACIMIENTO_HASTA is null ) OR ( C_CLIENTE.CLFECHA <= @CLIENTE_7_FECHANACIMIENTO_HASTA ) ) and 
	( ( @CLIENTE_7_IMAGEN_DESDE is null ) OR ( C_CLIENTE.CIMAGEN >= @CLIENTE_7_IMAGEN_DESDE ) ) and 
	( ( @CLIENTE_7_IMAGEN_HASTA is null ) OR ( C_CLIENTE.CIMAGEN <= @CLIENTE_7_IMAGEN_HASTA ) ) and 
	( ( @CLIENTE_7_LOCALIDAD_DESDE is null ) OR ( C_CLIENTE.CLLOC >= @CLIENTE_7_LOCALIDAD_DESDE ) ) and 
	( ( @CLIENTE_7_LOCALIDAD_HASTA is null ) OR ( C_CLIENTE.CLLOC <= @CLIENTE_7_LOCALIDAD_HASTA ) ) and 
	( ( @CLIENTE_7_NRODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLNRODOC >= @CLIENTE_7_NRODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_7_NRODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLNRODOC <= @CLIENTE_7_NRODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_7_NUMERO_DESDE is null ) OR ( C_CLIENTE.CLNro >= @CLIENTE_7_NUMERO_DESDE ) ) and 
	( ( @CLIENTE_7_NUMERO_HASTA is null ) OR ( C_CLIENTE.CLNro <= @CLIENTE_7_NUMERO_HASTA ) ) and 
	( ( @CLIENTE_7_PAGINAWEB_DESDE is null ) OR ( C_CLIENTE.CLPAGEWEB >= @CLIENTE_7_PAGINAWEB_DESDE ) ) and 
	( ( @CLIENTE_7_PAGINAWEB_HASTA is null ) OR ( C_CLIENTE.CLPAGEWEB <= @CLIENTE_7_PAGINAWEB_HASTA ) ) and 
	( ( @CLIENTE_7_PAIS_DESDE is null ) OR ( C_CLIENTE.CLPAIS >= @CLIENTE_7_PAIS_DESDE ) ) and 
	( ( @CLIENTE_7_PAIS_HASTA is null ) OR ( C_CLIENTE.CLPAIS <= @CLIENTE_7_PAIS_HASTA ) ) and 
	( ( @CLIENTE_7_PISO_DESDE is null ) OR ( C_CLIENTE.ClPiso >= @CLIENTE_7_PISO_DESDE ) ) and 
	( ( @CLIENTE_7_PISO_HASTA is null ) OR ( C_CLIENTE.ClPiso <= @CLIENTE_7_PISO_HASTA ) ) and 
	( ( @CLIENTE_7_PROVINCIA_DESDE is null ) OR ( C_CLIENTE.CLPRV >= @CLIENTE_7_PROVINCIA_DESDE ) ) and 
	( ( @CLIENTE_7_PROVINCIA_HASTA is null ) OR ( C_CLIENTE.CLPRV <= @CLIENTE_7_PROVINCIA_HASTA ) ) and 
	( ( @SITUACIONFISCAL_26_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_26_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @CLIENTE_7_TELEFONO_DESDE is null ) OR ( C_CLIENTE.CLTLF >= @CLIENTE_7_TELEFONO_DESDE ) ) and 
	( ( @CLIENTE_7_TELEFONO_HASTA is null ) OR ( C_CLIENTE.CLTLF <= @CLIENTE_7_TELEFONO_HASTA ) ) and 
	( ( @CLIENTE_7_TIPODOCUMENTO_DESDE is null ) OR ( C_CLIENTE.CLTIPODOC >= @CLIENTE_7_TIPODOCUMENTO_DESDE ) ) and 
	( ( @CLIENTE_7_TIPODOCUMENTO_HASTA is null ) OR ( C_CLIENTE.CLTIPODOC <= @CLIENTE_7_TIPODOCUMENTO_HASTA ) ) and 
	( ( @CLIENTE_7_MOVIL_DESDE is null ) OR ( C_CLIENTE.CLMovil >= @CLIENTE_7_MOVIL_DESDE ) ) and 
	( ( @CLIENTE_7_MOVIL_HASTA is null ) OR ( C_CLIENTE.CLMovil <= @CLIENTE_7_MOVIL_HASTA ) ) and 
	( ( @CLIENTE_7_TOPECTACTE_DESDE is null ) OR ( C_CLIENTE.CLTOPECCTE >= @CLIENTE_7_TOPECTACTE_DESDE ) ) and 
	( ( @CLIENTE_7_TOPECTACTE_HASTA is null ) OR ( C_CLIENTE.CLTOPECCTE <= @CLIENTE_7_TOPECTACTE_HASTA ) ) and 
	( ( @CLIENTE_7_LISTADEPRECIO_DESDE is null ) OR ( C_CLIENTE.CLLisPrec >= @CLIENTE_7_LISTADEPRECIO_DESDE ) ) and 
	( ( @CLIENTE_7_LISTADEPRECIO_HASTA is null ) OR ( C_CLIENTE.CLLisPrec <= @CLIENTE_7_LISTADEPRECIO_HASTA ) ) and 
	( ( @CLIENTE_7_CLASIFICACION_DESDE is null ) OR ( C_CLIENTE.CLCLAS >= @CLIENTE_7_CLASIFICACION_DESDE ) ) and 
	( ( @CLIENTE_7_CLASIFICACION_HASTA is null ) OR ( C_CLIENTE.CLCLAS <= @CLIENTE_7_CLASIFICACION_HASTA ) ) and 
	( ( @CLIENTE_7_TIPOCONVENIO_DESDE is null ) OR ( C_CLIENTE.CLTIPCONV >= @CLIENTE_7_TIPOCONVENIO_DESDE ) ) and 
	( ( @CLIENTE_7_TIPOCONVENIO_HASTA is null ) OR ( C_CLIENTE.CLTIPCONV <= @CLIENTE_7_TIPOCONVENIO_HASTA ) ) and 
	( ( @CLIENTE_7_NROIIBB_DESDE is null ) OR ( C_CLIENTE.CLNROIIBB >= @CLIENTE_7_NROIIBB_DESDE ) ) and 
	( ( @CLIENTE_7_NROIIBB_HASTA is null ) OR ( C_CLIENTE.CLNROIIBB <= @CLIENTE_7_NROIIBB_HASTA ) ) and 
	( ( @CLIENTE_7_DESCUENTOPREFERENTE_DESDE is null ) OR ( C_CLIENTE.CLCO_DTO >= @CLIENTE_7_DESCUENTOPREFERENTE_DESDE ) ) and 
	( ( @CLIENTE_7_DESCUENTOPREFERENTE_HASTA is null ) OR ( C_CLIENTE.CLCO_DTO <= @CLIENTE_7_DESCUENTOPREFERENTE_HASTA ) ) and 
	( ( @CLIENTE_7_TRANSPORTISTA_DESDE is null ) OR ( C_CLIENTE.CLTRANS >= @CLIENTE_7_TRANSPORTISTA_DESDE ) ) and 
	( ( @CLIENTE_7_TRANSPORTISTA_HASTA is null ) OR ( C_CLIENTE.CLTRANS <= @CLIENTE_7_TRANSPORTISTA_HASTA ) ) and 
	( ( @CLIENTE_7_ESTADOCIVIL is null ) OR ( C_CLIENTE.Estado = @CLIENTE_7_ESTADOCIVIL ) ) and 
	( ( @CLIENTE_7_HIJOS_DESDE is null ) OR ( C_CLIENTE.Hijos >= @CLIENTE_7_HIJOS_DESDE ) ) and 
	( ( @CLIENTE_7_HIJOS_HASTA is null ) OR ( C_CLIENTE.Hijos <= @CLIENTE_7_HIJOS_HASTA ) ) and 
	( ( @CLIENTE_7_SEXO is null ) OR ( C_CLIENTE.Sexo = @CLIENTE_7_SEXO ) ) and 
	( ( @CLIENTE_7_IDGLOBAL_DESDE is null ) OR ( C_CLIENTE.globalid >= @CLIENTE_7_IDGLOBAL_DESDE ) ) and 
	( ( @CLIENTE_7_IDGLOBAL_HASTA is null ) OR ( C_CLIENTE.globalid <= @CLIENTE_7_IDGLOBAL_HASTA ) ) and 
	( ( @CLIENTE_7_RUT_DESDE is null ) OR ( C_CLIENTE.RUT >= @CLIENTE_7_RUT_DESDE ) ) and 
	( ( @CLIENTE_7_RUT_HASTA is null ) OR ( C_CLIENTE.RUT <= @CLIENTE_7_RUT_HASTA ) ) and 
	( ( @CLIENTE_7_CODNOMBREFANTASIA_DESDE is null ) OR ( C_CLIENTE.CLCODFANT >= @CLIENTE_7_CODNOMBREFANTASIA_DESDE ) ) and 
	( ( @CLIENTE_7_CODNOMBREFANTASIA_HASTA is null ) OR ( C_CLIENTE.CLCODFANT <= @CLIENTE_7_CODNOMBREFANTASIA_HASTA ) ) and 
	( ( @CLIENTE_7_TIPOCLI_DESDE is null ) OR ( C_CLIENTE.CLTipoCli >= @CLIENTE_7_TIPOCLI_DESDE ) ) and 
	( ( @CLIENTE_7_TIPOCLI_HASTA is null ) OR ( C_CLIENTE.CLTipoCli <= @CLIENTE_7_TIPOCLI_HASTA ) ) and 
	( ( @CLIENTE_7_CATEGCLI_DESDE is null ) OR ( C_CLIENTE.CLCategCli >= @CLIENTE_7_CATEGCLI_DESDE ) ) and 
	( ( @CLIENTE_7_CATEGCLI_HASTA is null ) OR ( C_CLIENTE.CLCategCli <= @CLIENTE_7_CATEGCLI_HASTA ) ) and 
	( ( @CLIENTE_7_CONDICIONDEPAGO_DESDE is null ) OR ( C_CLIENTE.CLCONDPAG >= @CLIENTE_7_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @CLIENTE_7_CONDICIONDEPAGO_HASTA is null ) OR ( C_CLIENTE.CLCONDPAG <= @CLIENTE_7_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @CLIENTE_7_SUJETOVINCULADO is null ) OR ( C_CLIENTE.CLSujVinc = @CLIENTE_7_SUJETOVINCULADO ) ) and 
	( ( @CLIENTE_7_PERCEPCIONIVA_DESDE is null ) OR ( C_CLIENTE.CLPERTIVA >= @CLIENTE_7_PERCEPCIONIVA_DESDE ) ) and 
	( ( @CLIENTE_7_PERCEPCIONIVA_HASTA is null ) OR ( C_CLIENTE.CLPERTIVA <= @CLIENTE_7_PERCEPCIONIVA_HASTA ) ) and 
	( ( @CLIENTE_7_SITUACIONGANANCIAS is null ) OR ( C_CLIENTE.CLSITGAN = @CLIENTE_7_SITUACIONGANANCIAS ) ) and 
	( ( @CLIENTE_7_EXCLUIDOPERCEPCIONIVA is null ) OR ( C_CLIENTE.EXPERIVA = @CLIENTE_7_EXCLUIDOPERCEPCIONIVA ) ) and 
	( ( @CLIENTE_7_PERCEPCIONGANANCIAS_DESDE is null ) OR ( C_CLIENTE.CLPERGAN >= @CLIENTE_7_PERCEPCIONGANANCIAS_DESDE ) ) and 
	( ( @CLIENTE_7_PERCEPCIONGANANCIAS_HASTA is null ) OR ( C_CLIENTE.CLPERGAN <= @CLIENTE_7_PERCEPCIONGANANCIAS_HASTA ) ) and 
	( ( @CLIENTE_7_EXCLUIDOPERCEPCIONGANANCIAS is null ) OR ( C_CLIENTE.EXPERGAN = @CLIENTE_7_EXCLUIDOPERCEPCIONGANANCIAS ) ) and 
	( ( @CLIENTE_7_CODRECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.CODRECOM >= @CLIENTE_7_CODRECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_7_CODRECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.CODRECOM <= @CLIENTE_7_CODRECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_7_NOMBRERECOMENDANTE_DESDE is null ) OR ( C_CLIENTE.NOMRECOM >= @CLIENTE_7_NOMBRERECOMENDANTE_DESDE ) ) and 
	( ( @CLIENTE_7_NOMBRERECOMENDANTE_HASTA is null ) OR ( C_CLIENTE.NOMRECOM <= @CLIENTE_7_NOMBRERECOMENDANTE_HASTA ) ) and 
	( ( @CLIENTE_7_PRIMERNOMBRE_DESDE is null ) OR ( C_CLIENTE.CLPRINOM >= @CLIENTE_7_PRIMERNOMBRE_DESDE ) ) and 
	( ( @CLIENTE_7_PRIMERNOMBRE_HASTA is null ) OR ( C_CLIENTE.CLPRINOM <= @CLIENTE_7_PRIMERNOMBRE_HASTA ) ) and 
	( ( @CLIENTE_7_SEGUNDONOMBRE_DESDE is null ) OR ( C_CLIENTE.CLSEGNOM >= @CLIENTE_7_SEGUNDONOMBRE_DESDE ) ) and 
	( ( @CLIENTE_7_SEGUNDONOMBRE_HASTA is null ) OR ( C_CLIENTE.CLSEGNOM <= @CLIENTE_7_SEGUNDONOMBRE_HASTA ) ) and 
	( ( @CLIENTE_7_APELLIDO_DESDE is null ) OR ( C_CLIENTE.CLAPELL >= @CLIENTE_7_APELLIDO_DESDE ) ) and 
	( ( @CLIENTE_7_APELLIDO_HASTA is null ) OR ( C_CLIENTE.CLAPELL <= @CLIENTE_7_APELLIDO_HASTA ) ) and 
	( ( @CLIENTE_7_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_CLIENTE.VHastaIva >= @CLIENTE_7_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @CLIENTE_7_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_CLIENTE.VHastaIva <= @CLIENTE_7_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @CLIENTE_7_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_CLIENTE.VHastaGan >= @CLIENTE_7_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @CLIENTE_7_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_CLIENTE.VHastaGan <= @CLIENTE_7_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @CLIENTE_7_CODIGOSIPRIB_DESDE is null ) OR ( C_CLIENTE.CLSIPRIB >= @CLIENTE_7_CODIGOSIPRIB_DESDE ) ) and 
	( ( @CLIENTE_7_CODIGOSIPRIB_HASTA is null ) OR ( C_CLIENTE.CLSIPRIB <= @CLIENTE_7_CODIGOSIPRIB_HASTA ) ) and 
	( ( @CLIENTE_7_TASACEROPORCEN_DESDE is null ) OR ( C_CLIENTE.PorcenTC >= @CLIENTE_7_TASACEROPORCEN_DESDE ) ) and 
	( ( @CLIENTE_7_TASACEROPORCEN_HASTA is null ) OR ( C_CLIENTE.PorcenTC <= @CLIENTE_7_TASACEROPORCEN_HASTA ) ) and 
	( ( @CLIENTE_7_TASACEROAPLICA is null ) OR ( C_CLIENTE.AplicaTC = @CLIENTE_7_TASACEROAPLICA ) ) and 
	( ( @CLIENTE_7_INACTIVOFW is null ) OR ( C_CLIENTE.InactivoFW = @CLIENTE_7_INACTIVOFW ) ) and 
	( ( @MOTIVODESCUENTOYDEVOLUCION_69_TIPO is null ) OR ( C_MOTIVODESCUENTOYDEVOLUCION.Tipo = @MOTIVODESCUENTOYDEVOLUCION_69_TIPO ) ) and 
	( ( @SUCURSAL_9334_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9334_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9334_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9334_CODIGO_HASTA ) ) and 
	( ( @ITEMPROMOCIONES_NROITEM_DESDE is null ) OR ( c_ITEMPROMOCIONES.NROITEM >= @ITEMPROMOCIONES_NROITEM_DESDE ) ) and 
	( ( @ITEMPROMOCIONES_NROITEM_HASTA is null ) OR ( c_ITEMPROMOCIONES.NROITEM <= @ITEMPROMOCIONES_NROITEM_HASTA ) ) and 
	( ( @FACTURA_1_FECHAALTAFW_DESDE is null ) OR ( C_FACTURA.FAltaFW >= @FACTURA_1_FECHAALTAFW_DESDE ) ) and 
	( ( @FACTURA_1_FECHAALTAFW_HASTA is null ) OR ( C_FACTURA.FAltaFW <= @FACTURA_1_FECHAALTAFW_HASTA ) ) and 
	( ( @FACTURA_1_HORAALTAFW_DESDE is null ) OR ( C_FACTURA.HAltaFW >= @FACTURA_1_HORAALTAFW_DESDE ) ) and 
	( ( @FACTURA_1_HORAALTAFW_HASTA is null ) OR ( C_FACTURA.HAltaFW <= @FACTURA_1_HORAALTAFW_HASTA ) ) and 
	( ( @FACTURA_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_FACTURA.BDALTAFW >= @FACTURA_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @FACTURA_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_FACTURA.BDALTAFW <= @FACTURA_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @FACTURA_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA.BDMODIFW >= @FACTURA_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA.BDMODIFW <= @FACTURA_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_FACTURA.ESTTRANS >= @FACTURA_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURA_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_FACTURA.ESTTRANS <= @FACTURA_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURA_1_FECHAEXPO_DESDE is null ) OR ( C_FACTURA.FECEXPO >= @FACTURA_1_FECHAEXPO_DESDE ) ) and 
	( ( @FACTURA_1_FECHAEXPO_HASTA is null ) OR ( C_FACTURA.FECEXPO <= @FACTURA_1_FECHAEXPO_HASTA ) ) and 
	( ( @FACTURA_1_FECHAIMPO_DESDE is null ) OR ( C_FACTURA.FECIMPO >= @FACTURA_1_FECHAIMPO_DESDE ) ) and 
	( ( @FACTURA_1_FECHAIMPO_HASTA is null ) OR ( C_FACTURA.FECIMPO <= @FACTURA_1_FECHAIMPO_HASTA ) ) and 
	( ( @FACTURA_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA.FMODIFW >= @FACTURA_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA.FMODIFW <= @FACTURA_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_FACTURA.FECTRANS >= @FACTURA_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @FACTURA_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_FACTURA.FECTRANS <= @FACTURA_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @FACTURA_1_HORAEXPO_DESDE is null ) OR ( C_FACTURA.HORAEXPO >= @FACTURA_1_HORAEXPO_DESDE ) ) and 
	( ( @FACTURA_1_HORAEXPO_HASTA is null ) OR ( C_FACTURA.HORAEXPO <= @FACTURA_1_HORAEXPO_HASTA ) ) and 
	( ( @FACTURA_1_HORAIMPO_DESDE is null ) OR ( C_FACTURA.HORAIMPO >= @FACTURA_1_HORAIMPO_DESDE ) ) and 
	( ( @FACTURA_1_HORAIMPO_HASTA is null ) OR ( C_FACTURA.HORAIMPO <= @FACTURA_1_HORAIMPO_HASTA ) ) and 
	( ( @FACTURA_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA.HMODIFW >= @FACTURA_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA.HMODIFW <= @FACTURA_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_1_SERIEALTAFW_DESDE is null ) OR ( C_FACTURA.SALTAFW >= @FACTURA_1_SERIEALTAFW_DESDE ) ) and 
	( ( @FACTURA_1_SERIEALTAFW_HASTA is null ) OR ( C_FACTURA.SALTAFW <= @FACTURA_1_SERIEALTAFW_HASTA ) ) and 
	( ( @FACTURA_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA.SMODIFW >= @FACTURA_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA.SMODIFW <= @FACTURA_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_1_USUARIOALTAFW_DESDE is null ) OR ( C_FACTURA.UALTAFW >= @FACTURA_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @FACTURA_1_USUARIOALTAFW_HASTA is null ) OR ( C_FACTURA.UALTAFW <= @FACTURA_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @FACTURA_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA.UMODIFW >= @FACTURA_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA.UMODIFW <= @FACTURA_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @FACTURA_1_VERSIONALTAFW_DESDE is null ) OR ( C_FACTURA.VALTAFW >= @FACTURA_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @FACTURA_1_VERSIONALTAFW_HASTA is null ) OR ( C_FACTURA.VALTAFW <= @FACTURA_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @FACTURA_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_FACTURA.VMODIFW >= @FACTURA_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @FACTURA_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_FACTURA.VMODIFW <= @FACTURA_1_VERSIONMODIFICACIONFW_HASTA ) )

)