IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[160_ITEMARTICULOSCOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[160_ITEMARTICULOSCOMPRA];
GO;

CREATE FUNCTION [Listados].[160_ITEMARTICULOSCOMPRA]
( @BaseDeDatos varchar(8),
	@FACTURADECOMPRA_FECHA_DESDE datetime,
	@FACTURADECOMPRA_FECHA_HASTA datetime,
	@FACTURADECOMPRA_TIPOCOMPROBANTE varchar(3) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticuloscompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSCOMPRA__BD,
	c_ITEMARTICULOSCOMPRA.CODIGO as ITEMARTICULOSCOMPRA_CODIGO,
	c_ITEMARTICULOSCOMPRA.FNETO as ITEMARTICULOSCOMPRA_FNETO,
	c_ITEMARTICULOSCOMPRA.FPORIVA as ITEMARTICULOSCOMPRA_FPORIVA,
	c_ITEMARTICULOSCOMPRA.FMTOIVA as ITEMARTICULOSCOMPRA_FMTOIVA,
	case when c_facturadecompra.ffch = '01/01/1900 00:00:00' then null else c_facturadecompra.ffch end as FACTURADECOMPRA_FFCH,
	C_FACTURADECOMPRA.FACTTIPO as FACTURADECOMPRA_FACTTIPO,
	C_FACTURADECOMPRA.CODIGO as FACTURADECOMPRA_CODIGO
 from ZooLogic.FACCOMPRADET as c_ITEMARTICULOSCOMPRA
 left join ZooLogic.FACCOMPRA as C_FACTURADECOMPRA on C_FACTURADECOMPRA.CODIGO = c_ITEMARTICULOSCOMPRA.CODIGO and 0 = Funciones.empty( c_ITEMARTICULOSCOMPRA.CODIGO )
 where ( not 1 = funciones.empty( c_itemarticuloscompra.codigo ) ) and 
	( ( @FACTURADECOMPRA_FECHA_DESDE is null ) OR ( C_FACTURADECOMPRA.FFCH >= @FACTURADECOMPRA_FECHA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHA_HASTA is null ) OR ( C_FACTURADECOMPRA.FFCH <= @FACTURADECOMPRA_FECHA_HASTA ) ) and 
	( C_FACTURADECOMPRA.FACTTIPO in ( 8, 9, 10 ) ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTE is null ) OR ( C_FACTURADECOMPRA.FACTTIPO = @FACTURADECOMPRA_TIPOCOMPROBANTE ) ) and
	( c_ITEMARTICULOSCOMPRA.FMTOIVA <> 0 )

union all

select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticuloscompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSCOMPRA__BD,
	c_ITEMARTICULOSCOMPRA.CODIGO as ITEMARTICULOSCOMPRA_CODIGO,
	c_ITEMARTICULOSCOMPRA.FNETO *-1 as ITEMARTICULOSCOMPRA_FNETO,
	c_ITEMARTICULOSCOMPRA.FPORIVA as ITEMARTICULOSCOMPRA_FPORIVA,
	c_ITEMARTICULOSCOMPRA.FMTOIVA *-1 as ITEMARTICULOSCOMPRA_FMTOIVA,
	case when c_facturadecompra.ffch = '01/01/1900 00:00:00' then null else c_facturadecompra.ffch end as FACTURADECOMPRA_FFCH,
	C_FACTURADECOMPRA.FACTTIPO as FACTURADECOMPRA_FACTTIPO,
	C_FACTURADECOMPRA.CODIGO as FACTURADECOMPRA_CODIGO
 from ZooLogic.NCCOMPRADET as c_ITEMARTICULOSCOMPRA
 left join ZooLogic.NCCOMPRA as C_FACTURADECOMPRA on C_FACTURADECOMPRA.CODIGO = c_ITEMARTICULOSCOMPRA.CODIGO and 0 = Funciones.empty( c_ITEMARTICULOSCOMPRA.CODIGO )
 where ( not 1 = funciones.empty( c_itemarticuloscompra.codigo ) ) and 
	( ( @FACTURADECOMPRA_FECHA_DESDE is null ) OR ( C_FACTURADECOMPRA.FFCH >= @FACTURADECOMPRA_FECHA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHA_HASTA is null ) OR ( C_FACTURADECOMPRA.FFCH <= @FACTURADECOMPRA_FECHA_HASTA ) ) and 
	( C_FACTURADECOMPRA.FACTTIPO in ( 8, 9, 10 ) ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTE is null ) OR ( C_FACTURADECOMPRA.FACTTIPO = @FACTURADECOMPRA_TIPOCOMPROBANTE ) ) and
	( c_ITEMARTICULOSCOMPRA.FMTOIVA <> 0 )

union all

select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticuloscompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSCOMPRA__BD,
	c_ITEMARTICULOSCOMPRA.CODIGO as ITEMARTICULOSCOMPRA_CODIGO,
	c_ITEMARTICULOSCOMPRA.FNETO as ITEMARTICULOSCOMPRA_FNETO,
	c_ITEMARTICULOSCOMPRA.FPORIVA as ITEMARTICULOSCOMPRA_FPORIVA,
	c_ITEMARTICULOSCOMPRA.FMTOIVA as ITEMARTICULOSCOMPRA_FMTOIVA,
	case when c_facturadecompra.ffch = '01/01/1900 00:00:00' then null else c_facturadecompra.ffch end as FACTURADECOMPRA_FFCH,
	C_FACTURADECOMPRA.FACTTIPO as FACTURADECOMPRA_FACTTIPO,
	C_FACTURADECOMPRA.CODIGO as FACTURADECOMPRA_CODIGO
 from ZooLogic.NDCOMPRADET as c_ITEMARTICULOSCOMPRA
 left join ZooLogic.NDCOMPRA as C_FACTURADECOMPRA on C_FACTURADECOMPRA.CODIGO = c_ITEMARTICULOSCOMPRA.CODIGO and 0 = Funciones.empty( c_ITEMARTICULOSCOMPRA.CODIGO )
 where ( not 1 = funciones.empty( c_itemarticuloscompra.codigo ) ) and 
	( ( @FACTURADECOMPRA_FECHA_DESDE is null ) OR ( C_FACTURADECOMPRA.FFCH >= @FACTURADECOMPRA_FECHA_DESDE ) ) and 
	( ( @FACTURADECOMPRA_FECHA_HASTA is null ) OR ( C_FACTURADECOMPRA.FFCH <= @FACTURADECOMPRA_FECHA_HASTA ) ) and 
	( C_FACTURADECOMPRA.FACTTIPO in ( 8, 9, 10 ) ) and 
	( ( @FACTURADECOMPRA_TIPOCOMPROBANTE is null ) OR ( C_FACTURADECOMPRA.FACTTIPO = @FACTURADECOMPRA_TIPOCOMPROBANTE ) ) and
	( c_ITEMARTICULOSCOMPRA.FMTOIVA <> 0 )

)