IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_COMPROBANTEDECAJA_ITEMVALORESCAJA_ITEMVALORESCAJA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_COMPROBANTEDECAJA_ITEMVALORESCAJA_ITEMVALORESCAJA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_COMPROBANTEDECAJA_ITEMVALORESCAJA_ITEMVALORESCAJA]
( @BaseDeDatos varchar(8),
	@FACTURA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@FACTURA_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@ITEMVALORESCAJA_NUMERO_DESDE varchar(20),
	@ITEMVALORESCAJA_NUMERO_HASTA varchar(20),
	@ITEMVALORESCAJA_VALOR_DESDE varchar(5),
	@ITEMVALORESCAJA_VALOR_HASTA varchar(5),
	@ITEMVALORESCAJA_VALORDETALLE_DESDE varchar(40),
	@ITEMVALORESCAJA_VALORDETALLE_HASTA varchar(40),
	@ITEMVALORESCAJA_FECHA_DESDE datetime,
	@ITEMVALORESCAJA_FECHA_HASTA datetime,
	@ITEMVALORESCAJA_NUMEROINTERNO_DESDE varchar(15),
	@ITEMVALORESCAJA_NUMEROINTERNO_HASTA varchar(15),
	@ITEMVALORESCAJA_MONTOAMONEDASISTEMA_DESDE numeric(15, 2),
	@ITEMVALORESCAJA_MONTOAMONEDASISTEMA_HASTA numeric(15, 2),
	@COMPROBANTEDECAJA_1_IDENTIFICADOR_DESDE varchar(20),
	@COMPROBANTEDECAJA_1_IDENTIFICADOR_HASTA varchar(20),
	@COMPROBANTEDECAJA_1_CAJAORIGEN_DESDE numeric(2, 0),
	@COMPROBANTEDECAJA_1_CAJAORIGEN_HASTA numeric(2, 0),
	@COMPROBANTEDECAJA_1_ORIGENDESTINO_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_ORIGENDESTINO_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_CONCEPTO_DESDE varchar(10),
	@COMPROBANTEDECAJA_1_CONCEPTO_HASTA varchar(10),
	@COMPROBANTEDECAJA_1_TIPO numeric(1, 0),
	@COMPROBANTEDECAJA_1_CAJADESTINO_DESDE numeric(2, 0),
	@COMPROBANTEDECAJA_1_CAJADESTINO_HASTA numeric(2, 0),
	@COMPROBANTEDECAJA_1_VENDEDOR_DESDE varchar(10),
	@COMPROBANTEDECAJA_1_VENDEDOR_HASTA varchar(10),
	@COMPROBANTEDECAJA_1_NUMERO_DESDE numeric(10, 0),
	@COMPROBANTEDECAJA_1_NUMERO_HASTA numeric(10, 0),
	@COMPROBANTEDECAJA_1_FECHA_DESDE datetime,
	@COMPROBANTEDECAJA_1_FECHA_HASTA datetime,
	@CAJAESTADO_28_CAJAORIGEN_DESCRIPCION_DESDE varchar(40),
	@CAJAESTADO_28_CAJAORIGEN_DESCRIPCION_HASTA varchar(40),
	@ORIGENDEDATOS_29_ORIGENDESTINO_DESCRIPCION_DESDE varchar(40),
	@ORIGENDEDATOS_29_ORIGENDESTINO_DESCRIPCION_HASTA varchar(40),
	@CONCEPTOCAJA_30_CONCEPTO_DESCRIPCION_DESDE varchar(100),
	@CONCEPTOCAJA_30_CONCEPTO_DESCRIPCION_HASTA varchar(100),
	@CAJAESTADO_38_CAJADESTINO_DESCRIPCION_DESDE varchar(40),
	@CAJAESTADO_38_CAJADESTINO_DESCRIPCION_HASTA varchar(40),
	@VENDEDOR_39_VENDEDOR_NOMBRE_DESDE varchar(60),
	@VENDEDOR_39_VENDEDOR_NOMBRE_HASTA varchar(60),
	@SEGMENTACION_10153_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_10153_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_10152_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_10152_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_10151_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_10151_TIPO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONCONCEPTOCAJA_33_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONCONCEPTOCAJA_33_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CAJAESTADO_34_CAJADESTINO_DESCRIPCION_DESDE varchar(40),
	@CAJAESTADO_34_CAJADESTINO_DESCRIPCION_HASTA varchar(40),
	@CUENTABANCARIA_36_CUENTABANCARIA_DESCRIPCION_DESDE varchar(40),
	@CUENTABANCARIA_36_CUENTABANCARIA_DESCRIPCION_HASTA varchar(40),
	@MONEDA_9130_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_9130_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_10148_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_10148_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_10148_LINEA_DESDE varchar(10),
	@SUCURSAL_10148_LINEA_HASTA varchar(10),
	@SUCURSAL_10148_TIPO_DESDE varchar(10),
	@SUCURSAL_10148_TIPO_HASTA varchar(10),
	@SUCURSAL_10148_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_10148_DESCRIPCION_HASTA varchar(50),
	@CONCEPTOCAJA_30_TIPO_DESDE numeric(1, 0),
	@CONCEPTOCAJA_30_TIPO_HASTA numeric(1, 0),
	@CONCEPTOCAJA_30_CLASIFICACION_DESDE varchar(10),
	@CONCEPTOCAJA_30_CLASIFICACION_HASTA varchar(10),
	@CONCEPTOCAJA_30_CAJADESTINO_DESDE numeric(2, 0),
	@CONCEPTOCAJA_30_CAJADESTINO_HASTA numeric(2, 0),
	@CONCEPTOCAJA_30_ESTADOCHEQUE varchar(5),
	@CONCEPTOCAJA_30_CUENTABANCARIA_DESDE varchar(5),
	@CONCEPTOCAJA_30_CUENTABANCARIA_HASTA varchar(5),
	@SUCURSAL_10148_CODIGO_DESDE varchar(10),
	@SUCURSAL_10148_CODIGO_HASTA varchar(10),
	@ITEMVALORESCAJA_NROITEM_DESDE numeric(5, 0),
	@ITEMVALORESCAJA_NROITEM_HASTA numeric(5, 0),
	@COMPROBANTEDECAJA_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@COMPROBANTEDECAJA_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@COMPROBANTEDECAJA_1_FECHAALTAFW_DESDE datetime,
	@COMPROBANTEDECAJA_1_FECHAALTAFW_HASTA datetime,
	@COMPROBANTEDECAJA_1_FECHAEXPO_DESDE datetime,
	@COMPROBANTEDECAJA_1_FECHAEXPO_HASTA datetime,
	@COMPROBANTEDECAJA_1_FECHAIMPO_DESDE datetime,
	@COMPROBANTEDECAJA_1_FECHAIMPO_HASTA datetime,
	@COMPROBANTEDECAJA_1_FECHAMODIFICACIONFW_DESDE datetime,
	@COMPROBANTEDECAJA_1_FECHAMODIFICACIONFW_HASTA datetime,
	@COMPROBANTEDECAJA_1_FECHATRANSFERENCIA_DESDE datetime,
	@COMPROBANTEDECAJA_1_FECHATRANSFERENCIA_HASTA datetime,
	@COMPROBANTEDECAJA_1_HORAALTAFW_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_HORAALTAFW_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_HORAEXPO_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_HORAEXPO_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_HORAIMPO_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_HORAIMPO_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@COMPROBANTEDECAJA_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@COMPROBANTEDECAJA_1_SERIEALTAFW_DESDE varchar(7),
	@COMPROBANTEDECAJA_1_SERIEALTAFW_HASTA varchar(7),
	@COMPROBANTEDECAJA_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@COMPROBANTEDECAJA_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@COMPROBANTEDECAJA_1_USUARIOALTAFW_DESDE varchar(100),
	@COMPROBANTEDECAJA_1_USUARIOALTAFW_HASTA varchar(100),
	@COMPROBANTEDECAJA_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@COMPROBANTEDECAJA_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@COMPROBANTEDECAJA_1_VERSIONALTAFW_DESDE varchar(13),
	@COMPROBANTEDECAJA_1_VERSIONALTAFW_HASTA varchar(13),
	@COMPROBANTEDECAJA_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@COMPROBANTEDECAJA_1_VERSIONMODIFICACIONFW_HASTA varchar(13),
	@Parametro1 varchar(max) )
RETURNS TABLE
AS
RETURN
(
select * from (

select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemvalorescaja.coddetval, 38, ' ' ) as varchar( 46 ) ) as ITEMVALORESCAJA__Grupo,
	@basededatos as ITEMVALORESCAJA__BD,
	c_ITEMVALORESCAJA.CODDETVAL as ITEMVALORESCAJA_CodDetVal,
	c_ITEMVALORESCAJA.CODVAL as ITEMVALORESCAJA_CodVal,
	c_ITEMVALORESCAJA.DESCRIP as ITEMVALORESCAJA_Descrip,
	case when c_itemvalorescaja.fecha = '01/01/1900 00:00:00' then null else c_itemvalorescaja.fecha end as ITEMVALORESCAJA_Fecha,
	c_ITEMVALORESCAJA.NROINTERNO as ITEMVALORESCAJA_NroInterno,
	c_ITEMVALORESCAJA.MONTOSISTE as ITEMVALORESCAJA_Montosiste,
	C_COMPROBANTEDECAJA.CODIGO as COMPROBANTEDECAJA_Codigo,
	C_COMPROBANTEDECAJA.CAJAORIG as COMPROBANTEDECAJA_CajaOrig,
	C_COMPROBANTEDECAJA.ORIGDEST as COMPROBANTEDECAJA_ORIGDEST,
	C_COMPROBANTEDECAJA.CONCEPTO as COMPROBANTEDECAJA_Concepto,
	C_COMPROBANTEDECAJA.TIPO as COMPROBANTEDECAJA_Tipo,
	C_COMPROBANTEDECAJA.CAJADEST as COMPROBANTEDECAJA_CajaDest,
	C_COMPROBANTEDECAJA.VENDEDOR as COMPROBANTEDECAJA_vendedor,
	C_COMPROBANTEDECAJA.NUMERO as COMPROBANTEDECAJA_Numero,
	case when c_comprobantedecaja.fecha = '01/01/1900 00:00:00' then null else c_comprobantedecaja.fecha end as COMPROBANTEDECAJA_Fecha,
	C_COMPROBANTEDECAJA.COBS as COMPROBANTEDECAJA_CObs,
	cast( c_itemvalorescaja.monto*(case when c_itemvalorescaja.cotiza = 0 then 1 else c_itemvalorescaja.cotiza end)*c_comprobantedecaja.signomov as numeric( 15, 2 ) ) as ITEMVALORESCAJA_MontoVirtual,
	cast( case when c_itemvalorescaja.cotiza = 0 then 1 else c_itemvalorescaja.cotiza end as numeric( 15, 5 ) ) as ITEMVALORESCAJA_Cotiza,
	cast( c_itemvalorescaja.monto*c_comprobantedecaja.signomov as numeric( 15, 2 ) ) as ITEMVALORESCAJA_monto,
	c_ITEMVALORESCAJA.IDCAJA as ITEMVALORESCAJA_IdCaja,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_CONCEPTOCAJA.COBS as CONCEPTOCAJA_CObs,
	C_CONCEPTOCAJA.TIPO as CONCEPTOCAJA_Tipo,
	C_CONCEPTOCAJA.CLASIF as CONCEPTOCAJA_Clasif,
	C_CONCEPTOCAJA.CAJADEST as CONCEPTOCAJA_CajaDest,
	C_CONCEPTOCAJA.ESTCHEQUE as CONCEPTOCAJA_estcheque,
	C_CONCEPTOCAJA.CTABANC as CONCEPTOCAJA_CtaBanc,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMVALORESCAJA.NROITEM as ITEMVALORESCAJA_NROITEM,
	C_COMPROBANTEDECAJA.BDALTAFW as COMPROBANTEDECAJA_BDALTAFW,
	C_COMPROBANTEDECAJA.BDMODIFW as COMPROBANTEDECAJA_BDMODIFW,
	C_COMPROBANTEDECAJA.ESTTRANS as COMPROBANTEDECAJA_ESTTRANS,
	case when c_comprobantedecaja.faltafw = '01/01/1900 00:00:00' then null else c_comprobantedecaja.faltafw end as COMPROBANTEDECAJA_FALTAFW,
	case when c_comprobantedecaja.fecexpo = '01/01/1900 00:00:00' then null else c_comprobantedecaja.fecexpo end as COMPROBANTEDECAJA_FECEXPO,
	case when c_comprobantedecaja.fecimpo = '01/01/1900 00:00:00' then null else c_comprobantedecaja.fecimpo end as COMPROBANTEDECAJA_FECIMPO,
	case when c_comprobantedecaja.fmodifw = '01/01/1900 00:00:00' then null else c_comprobantedecaja.fmodifw end as COMPROBANTEDECAJA_FMODIFW,
	case when c_comprobantedecaja.fectrans = '01/01/1900 00:00:00' then null else c_comprobantedecaja.fectrans end as COMPROBANTEDECAJA_FECTRANS,
	C_COMPROBANTEDECAJA.HALTAFW as COMPROBANTEDECAJA_HALTAFW,
	C_COMPROBANTEDECAJA.HORAEXPO as COMPROBANTEDECAJA_HORAEXPO,
	C_COMPROBANTEDECAJA.HORAIMPO as COMPROBANTEDECAJA_HORAIMPO,
	C_COMPROBANTEDECAJA.HMODIFW as COMPROBANTEDECAJA_HMODIFW,
	C_COMPROBANTEDECAJA.SALTAFW as COMPROBANTEDECAJA_SALTAFW,
	C_COMPROBANTEDECAJA.SMODIFW as COMPROBANTEDECAJA_SMODIFW,
	C_COMPROBANTEDECAJA.UALTAFW as COMPROBANTEDECAJA_UALTAFW,
	C_COMPROBANTEDECAJA.UMODIFW as COMPROBANTEDECAJA_UMODIFW,
	C_COMPROBANTEDECAJA.VALTAFW as COMPROBANTEDECAJA_VALTAFW,
	C_COMPROBANTEDECAJA.VMODIFW as COMPROBANTEDECAJA_VMODIFW,
	C_COMPROBANTEDECAJA.ZADSFW as COMPROBANTEDECAJA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMVALORESCAJA__SUCURSAL,
	C_FACTURA.MONEDA as FACTURA_Moneda,
	cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_MostrarCajaEnNuevaPaginaVirtual,
	cast( Funciones.ObtenerCotizacion( @COMPROBANTEDECAJA_1_FECHA_HASTA , C_VALOR.clsmonet ) as numeric( 10, 4 ) ) as COMPROBANTEDECAJA_CotizacionHastaVirtual,
	cast( c_itemvalorescaja.monto* (case when c_itemvalorescaja.cotiza = 0 then 1 else Funciones.ObtenerCotizacion( @COMPROBANTEDECAJA_1_FECHA_HASTA , C_VALOR.clsmonet ) end) * c_comprobantedecaja.signomov as numeric( 15, 2 ) ) as COMPROBANTEDECAJA_MontoVirtualCotizHasta,
	cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_IncluyeCCVirtual,
	cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_IncluyeCanjeValorVirtual,
	cast( @parametro1 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_IncluyeCierreCajaVirtual,
	C_VALOR.CLNOM as VALOR_CLNOM,
	C_CAJAESTADO28.DESCRIP as CAJAESTADO28_Descrip,
	C_ORIGENDEDATOS.DESCRIP as ORIGENDEDATOS_DESCRIP,
	C_CONCEPTOCAJA.DESCRIP as CONCEPTOCAJA_Descrip,
	C_CAJAESTADO38.DESCRIP as CAJAESTADO38_Descrip,
	C_VENDEDOR.CLNOM as VENDEDOR_CLNOM,
	C_CAJAESTADO10014.DESCRIP as CAJAESTADO10014_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_CLASIFICACIONCONCEPTOCAJA.DESCRIP as CLASIFICACIONCONCEPTOCAJA_DESCRIP,
	C_CAJAESTADO34.DESCRIP as CAJAESTADO34_Descrip,
	C_CUENTABANCARIA.CBDES as CUENTABANCARIA_CBDes,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_CAJAESTADO28.NUMCAJA as CAJAESTADO28_NumCaja,
	C_CAJAESTADO34.NUMCAJA as CAJAESTADO34_NumCaja,
	C_CAJAESTADO38.NUMCAJA as CAJAESTADO38_NumCaja,
	C_CAJAESTADO10014.NUMCAJA as CAJAESTADO10014_NumCaja,
	C_CLASIFICACIONCONCEPTOCAJA.CODIGO as CLASIFICACIONCONCEPTOCAJA_CODIGO,
	C_CONCEPTOCAJA.CODIGO as CONCEPTOCAJA_Codigo,
	C_CUENTABANCARIA.CBCOD as CUENTABANCARIA_CBCod,
	C_FACTURA.CODIGO as FACTURA_CODIGO,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_ORIGENDEDATOS.CODIGO as ORIGENDEDATOS_CODIGO,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_VALOR.CLCOD as VALOR_CLCOD,
	C_VENDEDOR.CLCOD as VENDEDOR_CLCOD
 from ZooLogic.COMPCAJADET as c_ITEMVALORESCAJA
 left join ZooLogic.CAJAESTA as C_CAJAESTADO10014 on C_CAJAESTADO10014.NUMCAJA = C_ITEMVALORESCAJA.IDCAJA and 0 = Funciones.empty( C_ITEMVALORESCAJA.IDCAJA )
 left join ZooLogic.COMCAJ as C_COMPROBANTEDECAJA on C_COMPROBANTEDECAJA.CODIGO = C_ITEMVALORESCAJA.CODDETVAL and 0 = Funciones.empty( C_ITEMVALORESCAJA.CODDETVAL )
 left join ZooLogic.CONCECAJA as C_CONCEPTOCAJA on C_CONCEPTOCAJA.CODIGO = C_COMPROBANTEDECAJA.CONCEPTO and 0 = Funciones.empty( C_COMPROBANTEDECAJA.CONCEPTO )
 left join ZooLogic.CTABAN as C_CUENTABANCARIA on C_CUENTABANCARIA.CBCOD = C_CONCEPTOCAJA.CTABANC and 0 = Funciones.empty( C_CONCEPTOCAJA.CTABANC )
 left join ZooLogic.COMPROBANTEV as C_FACTURA on C_FACTURA.CODIGO = C_ITEMVALORESCAJA.CODDETVAL and 0 = Funciones.empty( C_ITEMVALORESCAJA.CODDETVAL )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_FACTURA.MONEDA and 0 = Funciones.empty( C_FACTURA.MONEDA )
 left join ZooLogic.ORDAT as C_ORIGENDEDATOS on C_ORIGENDEDATOS.CODIGO = C_COMPROBANTEDECAJA.ORIGDEST and 0 = Funciones.empty( C_COMPROBANTEDECAJA.ORIGDEST )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.XVAL as C_VALOR on C_VALOR.CLCOD = C_ITEMVALORESCAJA.CODVAL and 0 = Funciones.empty( C_ITEMVALORESCAJA.CODVAL )
 left join ZooLogic.VEN as C_VENDEDOR on C_VENDEDOR.CLCOD = C_COMPROBANTEDECAJA.VENDEDOR and 0 = Funciones.empty( C_COMPROBANTEDECAJA.VENDEDOR )
 left join ZooLogic.CAJAESTA as C_CAJAESTADO28 on C_CAJAESTADO28.NUMCAJA = C_COMPROBANTEDECAJA.CAJAORIG and 0 = Funciones.empty( C_COMPROBANTEDECAJA.CAJAORIG )
 left join ZooLogic.CAJAESTA as C_CAJAESTADO34 on C_CAJAESTADO34.NUMCAJA = C_CONCEPTOCAJA.CAJADEST and 0 = Funciones.empty( C_CONCEPTOCAJA.CAJADEST )
 left join ZooLogic.CAJAESTA as C_CAJAESTADO38 on C_CAJAESTADO38.NUMCAJA = C_COMPROBANTEDECAJA.CAJADEST and 0 = Funciones.empty( C_COMPROBANTEDECAJA.CAJADEST )
 left join ZooLogic.CLASIFCCAJA as C_CLASIFICACIONCONCEPTOCAJA on C_CLASIFICACIONCONCEPTOCAJA.CODIGO = C_CONCEPTOCAJA.CLASIF and 0 = Funciones.empty( C_CONCEPTOCAJA.CLASIF )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( 1=1 ) and 
	--	( ( @FACTURA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_FACTURA.Moneda >= @FACTURA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	--	( ( @FACTURA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_FACTURA.Moneda <= @FACTURA_1_MONEDACOMPROBANTE_HASTA ) ) and 
	case when @Parametro1 <> 1 and (C_COMPROBANTEDECAJA.CONCEPTO <> Funciones.ObtenerConceptoCierreCaja() and C_COMPROBANTEDECAJA.CONCEPTO <> 'CIERRE' ) then 0 else 1 end = @Parametro1 and
	( ( @COMPROBANTEDECAJA_1_FECHA_DESDE is null ) OR ( C_COMPROBANTEDECAJA.FALTAFW + C_COMPROBANTEDECAJA.HALTAFW >= 
		case when @COMPROBANTEDECAJA_1_HORAALTAFW_DESDE is null 
					then @COMPROBANTEDECAJA_1_FECHA_DESDE + '00:00:00'
					else @COMPROBANTEDECAJA_1_FECHA_DESDE + @COMPROBANTEDECAJA_1_HORAALTAFW_DESDE end )) and

	( ( @COMPROBANTEDECAJA_1_FECHA_HASTA is null ) OR ( C_COMPROBANTEDECAJA.FALTAFW + C_COMPROBANTEDECAJA.HALTAFW <=
		case when @COMPROBANTEDECAJA_1_HORAALTAFW_hasta is null 
					then  @COMPROBANTEDECAJA_1_FECHA_HASTA + '23:59:59'
					else  @COMPROBANTEDECAJA_1_FECHA_HASTA  + @COMPROBANTEDECAJA_1_HORAALTAFW_HASTA end ) ) and 

	( ( @ITEMVALORESCAJA_NUMERO_DESDE is null ) OR ( c_ITEMVALORESCAJA.CodDetVal >= @ITEMVALORESCAJA_NUMERO_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_NUMERO_HASTA is null ) OR ( c_ITEMVALORESCAJA.CodDetVal <= @ITEMVALORESCAJA_NUMERO_HASTA ) ) and 
	( ( @ITEMVALORESCAJA_VALOR_DESDE is null ) OR ( c_ITEMVALORESCAJA.CodVal >= @ITEMVALORESCAJA_VALOR_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_VALOR_HASTA is null ) OR ( c_ITEMVALORESCAJA.CodVal <= @ITEMVALORESCAJA_VALOR_HASTA ) ) and 
	( ( @ITEMVALORESCAJA_VALORDETALLE_DESDE is null ) OR ( c_ITEMVALORESCAJA.Descrip >= @ITEMVALORESCAJA_VALORDETALLE_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_VALORDETALLE_HASTA is null ) OR ( c_ITEMVALORESCAJA.Descrip <= @ITEMVALORESCAJA_VALORDETALLE_HASTA ) ) and 
	( ( @ITEMVALORESCAJA_FECHA_DESDE is null ) OR ( c_ITEMVALORESCAJA.Fecha >= @ITEMVALORESCAJA_FECHA_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_FECHA_HASTA is null ) OR ( c_ITEMVALORESCAJA.Fecha <= @ITEMVALORESCAJA_FECHA_HASTA ) ) and 
	( ( @ITEMVALORESCAJA_NUMEROINTERNO_DESDE is null ) OR ( c_ITEMVALORESCAJA.NroInterno >= @ITEMVALORESCAJA_NUMEROINTERNO_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_NUMEROINTERNO_HASTA is null ) OR ( c_ITEMVALORESCAJA.NroInterno <= @ITEMVALORESCAJA_NUMEROINTERNO_HASTA ) ) and 
	( ( @ITEMVALORESCAJA_MONTOAMONEDASISTEMA_DESDE is null ) OR ( c_ITEMVALORESCAJA.Montosiste >= @ITEMVALORESCAJA_MONTOAMONEDASISTEMA_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_MONTOAMONEDASISTEMA_HASTA is null ) OR ( c_ITEMVALORESCAJA.Montosiste <= @ITEMVALORESCAJA_MONTOAMONEDASISTEMA_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_IDENTIFICADOR_DESDE is null ) OR ( C_COMPROBANTEDECAJA.Codigo >= @COMPROBANTEDECAJA_1_IDENTIFICADOR_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_IDENTIFICADOR_HASTA is null ) OR ( C_COMPROBANTEDECAJA.Codigo <= @COMPROBANTEDECAJA_1_IDENTIFICADOR_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_CAJAORIGEN_DESDE is null ) OR ( C_COMPROBANTEDECAJA.CajaOrig >= @COMPROBANTEDECAJA_1_CAJAORIGEN_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_CAJAORIGEN_HASTA is null ) OR ( C_COMPROBANTEDECAJA.CajaOrig <= @COMPROBANTEDECAJA_1_CAJAORIGEN_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_ORIGENDESTINO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.ORIGDEST >= @COMPROBANTEDECAJA_1_ORIGENDESTINO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_ORIGENDESTINO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.ORIGDEST <= @COMPROBANTEDECAJA_1_ORIGENDESTINO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_CONCEPTO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.Concepto >= @COMPROBANTEDECAJA_1_CONCEPTO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_CONCEPTO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.Concepto <= @COMPROBANTEDECAJA_1_CONCEPTO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_TIPO is null ) OR ( C_COMPROBANTEDECAJA.Tipo = @COMPROBANTEDECAJA_1_TIPO ) ) and 
	( ( @COMPROBANTEDECAJA_1_CAJADESTINO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.CajaDest >= @COMPROBANTEDECAJA_1_CAJADESTINO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_CAJADESTINO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.CajaDest <= @COMPROBANTEDECAJA_1_CAJADESTINO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_VENDEDOR_DESDE is null ) OR ( C_COMPROBANTEDECAJA.vendedor >= @COMPROBANTEDECAJA_1_VENDEDOR_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_VENDEDOR_HASTA is null ) OR ( C_COMPROBANTEDECAJA.vendedor <= @COMPROBANTEDECAJA_1_VENDEDOR_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_NUMERO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.Numero >= @COMPROBANTEDECAJA_1_NUMERO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_NUMERO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.Numero <= @COMPROBANTEDECAJA_1_NUMERO_HASTA ) ) and 
	--( ( @COMPROBANTEDECAJA_1_FECHA_DESDE is null ) OR ( C_COMPROBANTEDECAJA.Fecha >= @COMPROBANTEDECAJA_1_FECHA_DESDE ) ) and 
	--( ( @COMPROBANTEDECAJA_1_FECHA_HASTA is null ) OR ( C_COMPROBANTEDECAJA.Fecha <= @COMPROBANTEDECAJA_1_FECHA_HASTA ) ) and 
	( ( @CAJAESTADO_28_CAJAORIGEN_DESCRIPCION_DESDE is null ) OR ( C_CAJAESTADO28.Descrip >= @CAJAESTADO_28_CAJAORIGEN_DESCRIPCION_DESDE ) ) and 
	( ( @CAJAESTADO_28_CAJAORIGEN_DESCRIPCION_HASTA is null ) OR ( C_CAJAESTADO28.Descrip <= @CAJAESTADO_28_CAJAORIGEN_DESCRIPCION_HASTA ) ) and 
	( ( @ORIGENDEDATOS_29_ORIGENDESTINO_DESCRIPCION_DESDE is null ) OR ( C_ORIGENDEDATOS.DESCRIP >= @ORIGENDEDATOS_29_ORIGENDESTINO_DESCRIPCION_DESDE ) ) and 
	( ( @ORIGENDEDATOS_29_ORIGENDESTINO_DESCRIPCION_HASTA is null ) OR ( C_ORIGENDEDATOS.DESCRIP <= @ORIGENDEDATOS_29_ORIGENDESTINO_DESCRIPCION_HASTA ) ) and 
	( ( @CONCEPTOCAJA_30_CONCEPTO_DESCRIPCION_DESDE is null ) OR ( C_CONCEPTOCAJA.Descrip >= @CONCEPTOCAJA_30_CONCEPTO_DESCRIPCION_DESDE ) ) and 
	( ( @CONCEPTOCAJA_30_CONCEPTO_DESCRIPCION_HASTA is null ) OR ( C_CONCEPTOCAJA.Descrip <= @CONCEPTOCAJA_30_CONCEPTO_DESCRIPCION_HASTA ) ) and 
	( ( @CAJAESTADO_38_CAJADESTINO_DESCRIPCION_DESDE is null ) OR ( C_CAJAESTADO38.Descrip >= @CAJAESTADO_38_CAJADESTINO_DESCRIPCION_DESDE ) ) and 
	( ( @CAJAESTADO_38_CAJADESTINO_DESCRIPCION_HASTA is null ) OR ( C_CAJAESTADO38.Descrip <= @CAJAESTADO_38_CAJADESTINO_DESCRIPCION_HASTA ) ) and 
	( ( @VENDEDOR_39_VENDEDOR_NOMBRE_DESDE is null ) OR ( C_VENDEDOR.CLNOM >= @VENDEDOR_39_VENDEDOR_NOMBRE_DESDE ) ) and 
	( ( @VENDEDOR_39_VENDEDOR_NOMBRE_HASTA is null ) OR ( C_VENDEDOR.CLNOM <= @VENDEDOR_39_VENDEDOR_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_10153_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_10153_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_10153_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_10153_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_10152_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_10152_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_10152_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_10152_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_10151_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_10151_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_10151_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_10151_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONCONCEPTOCAJA_33_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONCONCEPTOCAJA.DESCRIP >= @CLASIFICACIONCONCEPTOCAJA_33_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONCONCEPTOCAJA_33_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONCONCEPTOCAJA.DESCRIP <= @CLASIFICACIONCONCEPTOCAJA_33_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CAJAESTADO_34_CAJADESTINO_DESCRIPCION_DESDE is null ) OR ( C_CAJAESTADO34.Descrip >= @CAJAESTADO_34_CAJADESTINO_DESCRIPCION_DESDE ) ) and 
	( ( @CAJAESTADO_34_CAJADESTINO_DESCRIPCION_HASTA is null ) OR ( C_CAJAESTADO34.Descrip <= @CAJAESTADO_34_CAJADESTINO_DESCRIPCION_HASTA ) ) and 
	( ( @CUENTABANCARIA_36_CUENTABANCARIA_DESCRIPCION_DESDE is null ) OR ( C_CUENTABANCARIA.CBDes >= @CUENTABANCARIA_36_CUENTABANCARIA_DESCRIPCION_DESDE ) ) and 
	( ( @CUENTABANCARIA_36_CUENTABANCARIA_DESCRIPCION_HASTA is null ) OR ( C_CUENTABANCARIA.CBDes <= @CUENTABANCARIA_36_CUENTABANCARIA_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_9130_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_9130_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_9130_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_9130_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_10148_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_10148_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_10148_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_10148_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_10148_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_10148_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_10148_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_10148_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_10148_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_10148_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_10148_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_10148_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_10148_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_10148_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_10148_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_10148_DESCRIPCION_HASTA ) ) and 
	( ( @CONCEPTOCAJA_30_TIPO_DESDE is null ) OR ( C_CONCEPTOCAJA.Tipo >= @CONCEPTOCAJA_30_TIPO_DESDE ) ) and 
	( ( @CONCEPTOCAJA_30_TIPO_HASTA is null ) OR ( C_CONCEPTOCAJA.Tipo <= @CONCEPTOCAJA_30_TIPO_HASTA ) ) and 
	( ( @CONCEPTOCAJA_30_CLASIFICACION_DESDE is null ) OR ( C_CONCEPTOCAJA.Clasif >= @CONCEPTOCAJA_30_CLASIFICACION_DESDE ) ) and 
	( ( @CONCEPTOCAJA_30_CLASIFICACION_HASTA is null ) OR ( C_CONCEPTOCAJA.Clasif <= @CONCEPTOCAJA_30_CLASIFICACION_HASTA ) ) and 
	( ( @CONCEPTOCAJA_30_CAJADESTINO_DESDE is null ) OR ( C_CONCEPTOCAJA.CajaDest >= @CONCEPTOCAJA_30_CAJADESTINO_DESDE ) ) and 
	( ( @CONCEPTOCAJA_30_CAJADESTINO_HASTA is null ) OR ( C_CONCEPTOCAJA.CajaDest <= @CONCEPTOCAJA_30_CAJADESTINO_HASTA ) ) and 
	( ( @CONCEPTOCAJA_30_ESTADOCHEQUE is null ) OR ( C_CONCEPTOCAJA.estcheque = @CONCEPTOCAJA_30_ESTADOCHEQUE ) ) and 
	( ( @CONCEPTOCAJA_30_CUENTABANCARIA_DESDE is null ) OR ( C_CONCEPTOCAJA.CtaBanc >= @CONCEPTOCAJA_30_CUENTABANCARIA_DESDE ) ) and 
	( ( @CONCEPTOCAJA_30_CUENTABANCARIA_HASTA is null ) OR ( C_CONCEPTOCAJA.CtaBanc <= @CONCEPTOCAJA_30_CUENTABANCARIA_HASTA ) ) and 
	( ( @SUCURSAL_10148_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_10148_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_10148_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_10148_CODIGO_HASTA ) ) and 
	( ( @ITEMVALORESCAJA_NROITEM_DESDE is null ) OR ( c_ITEMVALORESCAJA.NROITEM >= @ITEMVALORESCAJA_NROITEM_DESDE ) ) and 
	( ( @ITEMVALORESCAJA_NROITEM_HASTA is null ) OR ( c_ITEMVALORESCAJA.NROITEM <= @ITEMVALORESCAJA_NROITEM_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.BDALTAFW >= @COMPROBANTEDECAJA_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.BDALTAFW <= @COMPROBANTEDECAJA_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.BDMODIFW >= @COMPROBANTEDECAJA_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.BDMODIFW <= @COMPROBANTEDECAJA_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_COMPROBANTEDECAJA.ESTTRANS >= @COMPROBANTEDECAJA_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_COMPROBANTEDECAJA.ESTTRANS <= @COMPROBANTEDECAJA_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
--	( ( @COMPROBANTEDECAJA_1_FECHAALTAFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.FALTAFW >= @COMPROBANTEDECAJA_1_FECHAALTAFW_DESDE ) ) and 
--	( ( @COMPROBANTEDECAJA_1_FECHAALTAFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.FALTAFW <= @COMPROBANTEDECAJA_1_FECHAALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHAEXPO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.FECEXPO >= @COMPROBANTEDECAJA_1_FECHAEXPO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHAEXPO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.FECEXPO <= @COMPROBANTEDECAJA_1_FECHAEXPO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHAIMPO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.FECIMPO >= @COMPROBANTEDECAJA_1_FECHAIMPO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHAIMPO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.FECIMPO <= @COMPROBANTEDECAJA_1_FECHAIMPO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.FMODIFW >= @COMPROBANTEDECAJA_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.FMODIFW <= @COMPROBANTEDECAJA_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_COMPROBANTEDECAJA.FECTRANS >= @COMPROBANTEDECAJA_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_COMPROBANTEDECAJA.FECTRANS <= @COMPROBANTEDECAJA_1_FECHATRANSFERENCIA_HASTA ) ) and 
	--( ( @COMPROBANTEDECAJA_1_HORAALTAFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.HALTAFW >= @COMPROBANTEDECAJA_1_HORAALTAFW_DESDE ) ) and 
	--( ( @COMPROBANTEDECAJA_1_HORAALTAFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.HALTAFW <= @COMPROBANTEDECAJA_1_HORAALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_HORAEXPO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.HORAEXPO >= @COMPROBANTEDECAJA_1_HORAEXPO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_HORAEXPO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.HORAEXPO <= @COMPROBANTEDECAJA_1_HORAEXPO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_HORAIMPO_DESDE is null ) OR ( C_COMPROBANTEDECAJA.HORAIMPO >= @COMPROBANTEDECAJA_1_HORAIMPO_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_HORAIMPO_HASTA is null ) OR ( C_COMPROBANTEDECAJA.HORAIMPO <= @COMPROBANTEDECAJA_1_HORAIMPO_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.HMODIFW >= @COMPROBANTEDECAJA_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.HMODIFW <= @COMPROBANTEDECAJA_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_SERIEALTAFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.SALTAFW >= @COMPROBANTEDECAJA_1_SERIEALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_SERIEALTAFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.SALTAFW <= @COMPROBANTEDECAJA_1_SERIEALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.SMODIFW >= @COMPROBANTEDECAJA_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.SMODIFW <= @COMPROBANTEDECAJA_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_USUARIOALTAFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.UALTAFW >= @COMPROBANTEDECAJA_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_USUARIOALTAFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.UALTAFW <= @COMPROBANTEDECAJA_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.UMODIFW >= @COMPROBANTEDECAJA_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.UMODIFW <= @COMPROBANTEDECAJA_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_VERSIONALTAFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.VALTAFW >= @COMPROBANTEDECAJA_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_VERSIONALTAFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.VALTAFW <= @COMPROBANTEDECAJA_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @COMPROBANTEDECAJA_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_COMPROBANTEDECAJA.VMODIFW >= @COMPROBANTEDECAJA_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_COMPROBANTEDECAJA.VMODIFW <= @COMPROBANTEDECAJA_1_VERSIONMODIFICACIONFW_HASTA ) )

 union all

 select cast( '' as varchar( 46 ) ) as ITEMVALORESCAJA__Grupo,
	@basededatos as ITEMVALORESCAJA__BD,
	null as ITEMVALORESCAJA_CodDetVal,
	c_ITEMVALORESCAJA.valor as ITEMVALORESCAJA_CodVal,
	c_valor.CLNOM as ITEMVALORESCAJA_Descrip,
	case when c_cajaaudi.fecha = '01/01/1900 00:00:00' then null else c_cajaaudi.fecha end as ITEMVALORESCAJA_Fecha,
	null as ITEMVALORESCAJA_NroInterno, 
	c_itemvalorescaja.monto  as ITEMVALORESCAJA_Montosiste,
	null as COMPROBANTEDECAJA_Codigo,
	c_cajaaudi.NUMCAJA as COMPROBANTEDECAJA_CajaOrig,
	null as COMPROBANTEDECAJA_ORIGDEST,
	c_cajaaudi.tarea as COMPROBANTEDECAJA_Concepto,
	null as COMPROBANTEDECAJA_Tipo,
	null as COMPROBANTEDECAJA_CajaDest,
	null as COMPROBANTEDECAJA_vendedor,
	null as COMPROBANTEDECAJA_Numero,
	case when c_cajaaudi.fecha = '01/01/1900 00:00:00' then null else c_cajaaudi.fecha end as COMPROBANTEDECAJA_Fecha,
	'' as COMPROBANTEDECAJA_CObs,
	cast( c_itemvalorescaja.monto*(case when Funciones.ObtenerCotizacion (c_cajaaudi.fecha, c_valor.CLSMONET ) = 0 then 1 else Funciones.ObtenerCotizacion (c_cajaaudi.fecha, c_valor.CLSMONET ) end) as numeric( 15, 2 ) ) as ITEMVALORESCAJA_MontoVirtual,
	cast( case when Funciones.ObtenerCotizacion (c_cajaaudi.fecha, c_valor.CLSMONET ) = 0 then 1 else Funciones.ObtenerCotizacion (c_cajaaudi.fecha, c_valor.CLSMONET ) end as numeric( 15, 5 ) ) as ITEMVALORESCAJA_Cotiza,
	cast( c_itemvalorescaja.monto as numeric( 15, 2 ) ) as ITEMVALORESCAJA_monto,
	c_cajaaudi.NUMCAJA as ITEMVALORESCAJA_IdCaja,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	null as CONCEPTOCAJA_CObs,
	null as CONCEPTOCAJA_Tipo,
	null as CONCEPTOCAJA_Clasif,
	null as CONCEPTOCAJA_CajaDest,
	null as CONCEPTOCAJA_estcheque,
	null as CONCEPTOCAJA_CtaBanc,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMVALORESCAJA.NROITEM as ITEMVALORESCAJA_NROITEM,
	c_cajaaudi.BDALTAFW as COMPROBANTEDECAJA_BDALTAFW,
	c_cajaaudi.BDMODIFW as COMPROBANTEDECAJA_BDMODIFW,
	c_cajaaudi.ESTTRANS as COMPROBANTEDECAJA_ESTTRANS,
	case when c_cajaaudi.faltafw = '01/01/1900 00:00:00' then null else c_cajaaudi.faltafw end as COMPROBANTEDECAJA_FALTAFW,
	case when c_cajaaudi.fecexpo = '01/01/1900 00:00:00' then null else c_cajaaudi.fecexpo end as COMPROBANTEDECAJA_FECEXPO,
	case when c_cajaaudi.fecimpo = '01/01/1900 00:00:00' then null else c_cajaaudi.fecimpo end as COMPROBANTEDECAJA_FECIMPO,
	case when c_cajaaudi.fmodifw = '01/01/1900 00:00:00' then null else c_cajaaudi.fmodifw end as COMPROBANTEDECAJA_FMODIFW,
	case when c_cajaaudi.fectrans = '01/01/1900 00:00:00' then null else c_cajaaudi.fectrans end as COMPROBANTEDECAJA_FECTRANS,
	c_cajaaudi.HALTAFW as COMPROBANTEDECAJA_HALTAFW,
	c_cajaaudi.HORAEXPO as COMPROBANTEDECAJA_HORAEXPO,
	c_cajaaudi.HORAIMPO as COMPROBANTEDECAJA_HORAIMPO,
	c_cajaaudi.HMODIFW as COMPROBANTEDECAJA_HMODIFW,
	c_cajaaudi.SALTAFW as COMPROBANTEDECAJA_SALTAFW,
	c_cajaaudi.SMODIFW as COMPROBANTEDECAJA_SMODIFW,
	c_cajaaudi.UALTAFW as COMPROBANTEDECAJA_UALTAFW,
	c_cajaaudi.UMODIFW as COMPROBANTEDECAJA_UMODIFW,
	c_cajaaudi.VALTAFW as COMPROBANTEDECAJA_VALTAFW,
	c_cajaaudi.VMODIFW as COMPROBANTEDECAJA_VMODIFW,
	c_cajaaudi.ZADSFW as COMPROBANTEDECAJA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMVALORESCAJA__SUCURSAL,
	c_valor.CLSMONET as FACTURA_Moneda,
	cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_MostrarCajaEnNuevaPaginaVirtual,
	cast( Funciones.ObtenerCotizacion( @COMPROBANTEDECAJA_1_FECHA_HASTA , C_VALOR.clsmonet ) as numeric( 10, 4 ) ) as COMPROBANTEDECAJA_CotizacionHastaVirtual,
	cast( c_itemvalorescaja.monto* (case when Funciones.ObtenerCotizacion (@COMPROBANTEDECAJA_1_FECHA_HASTA, c_valor.CLSMONET ) = 0 then 1 else Funciones.ObtenerCotizacion( @COMPROBANTEDECAJA_1_FECHA_HASTA , C_VALOR.clsmonet ) end)  as numeric( 15, 2 ) ) as COMPROBANTEDECAJA_MontoVirtualCotizHasta,

	cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_IncluyeCCVirtual,
    cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_IncluyeCanjeVirtual,
	cast( 0 as numeric( 1, 0 ) ) as COMPROBANTEDECAJA_IncluyeCierreCajaVirtual,	
	C_VALOR.CLNOM as VALOR_CLNOM,
	'Caja ' + Funciones.Alltrim( c_cajaaudi.NUMCAJA ) as CAJAESTADO28_Descrip,
	'' as ORIGENDEDATOS_DESCRIP,
	'Apertura de caja' as CONCEPTOCAJA_Descrip,
	null as CAJAESTADO38_Descrip,
	'' as VENDEDOR_CLNOM,
	'Caja ' + Funciones.Alltrim( c_cajaaudi.NUMCAJA ) as CAJAESTADO10014_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	'' as CLASIFICACIONCONCEPTOCAJA_DESCRIP,
	null as CAJAESTADO34_Descrip,
	null as CUENTABANCARIA_CBDes,
	'' as MONEDA_Descrip,
	c_cajaaudi.NUMCAJA as CAJAESTADO28_NumCaja,
	c_cajaaudi.NUMCAJA as CAJAESTADO34_NumCaja,
	c_cajaaudi.NUMCAJA as CAJAESTADO38_NumCaja,
	c_cajaaudi.NUMCAJA as CAJAESTADO10014_NumCaja,
	'' as CLASIFICACIONCONCEPTOCAJA_CODIGO,
	c_cajaaudi.tarea as CONCEPTOCAJA_Codigo,
	null as CUENTABANCARIA_CBCod,
	null as FACTURA_CODIGO,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	null as MONEDA_Codigo,
	null as ORIGENDEDATOS_CODIGO,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_VALOR.CLCOD as VALOR_CLCOD,
	null as VENDEDOR_CLCOD

  from Zoologic.detaudi c_ITEMVALORESCAJA 
 LEFT JOIN [ZooLogic].CAJAAUDI c_cajaaudi ON c_ITEMVALORESCAJA.CODIGO = c_cajaaudi.CODIGO
 left join ZooLogic.XVAL as C_VALOR on C_VALOR.CLCOD = C_ITEMVALORESCAJA.valor and 0 = Funciones.empty( C_ITEMVALORESCAJA.valor )
  left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
  left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )

  where c_cajaaudi.tarea = 'APERTURA' AND
  	( ( @COMPROBANTEDECAJA_1_CAJAORIGEN_DESDE is null ) OR ( c_cajaaudi.NUMCAJA >= @COMPROBANTEDECAJA_1_CAJAORIGEN_DESDE ) ) and 
	( ( @COMPROBANTEDECAJA_1_CAJAORIGEN_HASTA is null ) OR ( c_cajaaudi.NUMCAJA <= @COMPROBANTEDECAJA_1_CAJAORIGEN_HASTA ) ) and 

   	( ( @COMPROBANTEDECAJA_1_FECHA_DESDE is null ) OR ( c_cajaaudi.FECHA + c_cajaaudi.HORA >= 
			case when @COMPROBANTEDECAJA_1_HORAALTAFW_DESDE is null 
					then @COMPROBANTEDECAJA_1_FECHA_DESDE + '00:00:00'
					else @COMPROBANTEDECAJA_1_FECHA_DESDE + @COMPROBANTEDECAJA_1_HORAALTAFW_DESDE end ) ) and
	( ( @COMPROBANTEDECAJA_1_FECHA_HASTA is null ) OR ( c_cajaaudi.FECHA + c_cajaaudi.HORA <= 
			case when @COMPROBANTEDECAJA_1_HORAALTAFW_HASTA is null	
					then @COMPROBANTEDECAJA_1_FECHA_HASTA + '23:59:59'
					else @COMPROBANTEDECAJA_1_FECHA_HASTA  + @COMPROBANTEDECAJA_1_HORAALTAFW_HASTA end ) ) 

) as c_ITEMVALORESCAJA

) 