IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[GENERICO_CONCILIACIONES_ITEMMOVBANCARIOS_ITEMMOVBANCARIOS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[GENERICO_CONCILIACIONES_ITEMMOVBANCARIOS_ITEMMOVBANCARIOS];
GO;

CREATE FUNCTION [Listados].[GENERICO_CONCILIACIONES_ITEMMOVBANCARIOS_ITEMMOVBANCARIOS]
( @BaseDeDatos varchar(8),
	@MOVIMIENTOBANCARIO_3_FECHA_DESDE datetime,
	@MOVIMIENTOBANCARIO_3_FECHA_HASTA datetime,
	@MOVIMIENTOBANCARIO_3_CONCEPTO_DESDE varchar(10),
	@MOVIMIENTOBANCARIO_3_CONCEPTO_HASTA varchar(10),
	@MOVIMIENTOBANCARIO_3_NUMERO_DESDE numeric(10, 0),
	@MOVIMIENTOBANCARIO_3_NUMERO_HASTA numeric(10, 0),
	@MOVIMIENTOBANCARIO_3_IMPORTE_DESDE numeric(15, 2),
	@MOVIMIENTOBANCARIO_3_IMPORTE_HASTA numeric(15, 2),
	@ITEMMOVBANCARIOS_MOVIMIENTO_DESDE varchar(20),
	@ITEMMOVBANCARIOS_MOVIMIENTO_HASTA varchar(20),
	@CONCILIACIONES_1_CODIGO_DESDE varchar(38),
	@CONCILIACIONES_1_CODIGO_HASTA varchar(38),
	@CONCILIACIONES_1_NUMERO_DESDE numeric(8, 0),
	@CONCILIACIONES_1_NUMERO_HASTA numeric(8, 0),
	@CONCILIACIONES_1_CUENTABANCARIA_DESDE varchar(5),
	@CONCILIACIONES_1_CUENTABANCARIA_HASTA varchar(5),
	@CUENTABANCARIA_25_CUENTABANCARIA_DESCRIPCION_DESDE varchar(40),
	@CUENTABANCARIA_25_CUENTABANCARIA_DESCRIPCION_HASTA varchar(40),
	@SEGMENTACION_13163_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_13163_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_13162_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_13162_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_13161_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_13161_TIPO_DESCRIPCION_HASTA varchar(50),
	@CONCEPTOENTIDADFINANCIERA_13021_CONCEPTO_CONCEPTO_DESDE varchar(100),
	@CONCEPTOENTIDADFINANCIERA_13021_CONCEPTO_CONCEPTO_HASTA varchar(100),
	@SUCURSAL_13158_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_13158_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_13158_LINEA_DESDE varchar(10),
	@SUCURSAL_13158_LINEA_HASTA varchar(10),
	@SUCURSAL_13158_TIPO_DESDE varchar(10),
	@SUCURSAL_13158_TIPO_HASTA varchar(10),
	@SUCURSAL_13158_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_13158_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_13158_CODIGO_DESDE varchar(10),
	@SUCURSAL_13158_CODIGO_HASTA varchar(10),
	@ITEMMOVBANCARIOS_NROITEM_DESDE numeric(5, 0),
	@ITEMMOVBANCARIOS_NROITEM_HASTA numeric(5, 0),
	@CONCILIACIONES_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@CONCILIACIONES_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@CONCILIACIONES_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@CONCILIACIONES_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@CONCILIACIONES_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@CONCILIACIONES_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@CONCILIACIONES_1_FECHAALTAFW_DESDE datetime,
	@CONCILIACIONES_1_FECHAALTAFW_HASTA datetime,
	@CONCILIACIONES_1_FECHAEXPO_DESDE datetime,
	@CONCILIACIONES_1_FECHAEXPO_HASTA datetime,
	@CONCILIACIONES_1_FECHAIMPO_DESDE datetime,
	@CONCILIACIONES_1_FECHAIMPO_HASTA datetime,
	@CONCILIACIONES_1_FECHAMODIFICACIONFW_DESDE datetime,
	@CONCILIACIONES_1_FECHAMODIFICACIONFW_HASTA datetime,
	@CONCILIACIONES_1_FECHATRANSFERENCIA_DESDE datetime,
	@CONCILIACIONES_1_FECHATRANSFERENCIA_HASTA datetime,
	@CONCILIACIONES_1_HORAALTAFW_DESDE varchar(8),
	@CONCILIACIONES_1_HORAALTAFW_HASTA varchar(8),
	@CONCILIACIONES_1_HORAEXPO_DESDE varchar(8),
	@CONCILIACIONES_1_HORAEXPO_HASTA varchar(8),
	@CONCILIACIONES_1_HORAIMPO_DESDE varchar(8),
	@CONCILIACIONES_1_HORAIMPO_HASTA varchar(8),
	@CONCILIACIONES_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@CONCILIACIONES_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@CONCILIACIONES_1_SERIEALTAFW_DESDE varchar(7),
	@CONCILIACIONES_1_SERIEALTAFW_HASTA varchar(7),
	@CONCILIACIONES_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@CONCILIACIONES_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@CONCILIACIONES_1_USUARIOALTAFW_DESDE varchar(100),
	@CONCILIACIONES_1_USUARIOALTAFW_HASTA varchar(100),
	@CONCILIACIONES_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@CONCILIACIONES_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@CONCILIACIONES_1_VERSIONALTAFW_DESDE varchar(13),
	@CONCILIACIONES_1_VERSIONALTAFW_HASTA varchar(13),
	@CONCILIACIONES_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@CONCILIACIONES_1_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemmovbancarios.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMMOVBANCARIOS__Grupo,
	@basededatos as ITEMMOVBANCARIOS__BD,
	c_ITEMMOVBANCARIOS.CODIGO as ITEMMOVBANCARIOS_Codigo,
	c_ITEMMOVBANCARIOS.MOV as ITEMMOVBANCARIOS_Mov,
	C_CONCILIACIONES.CODIGO as CONCILIACIONES_Codigo,
	C_CONCILIACIONES.NUMERO as CONCILIACIONES_Numero,
	C_CONCILIACIONES.CTABANC as CONCILIACIONES_CtaBanc,
	C_CONCILIACIONES.OBS as CONCILIACIONES_Obs,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMMOVBANCARIOS.NROITEM as ITEMMOVBANCARIOS_NROITEM,
	C_CONCILIACIONES.BDALTAFW as CONCILIACIONES_BDALTAFW,
	C_CONCILIACIONES.BDMODIFW as CONCILIACIONES_BDMODIFW,
	C_CONCILIACIONES.ESTTRANS as CONCILIACIONES_ESTTRANS,
	case when c_conciliaciones.faltafw = '01/01/1900 00:00:00' then null else c_conciliaciones.faltafw end as CONCILIACIONES_FALTAFW,
	case when c_conciliaciones.fecexpo = '01/01/1900 00:00:00' then null else c_conciliaciones.fecexpo end as CONCILIACIONES_FECEXPO,
	case when c_conciliaciones.fecimpo = '01/01/1900 00:00:00' then null else c_conciliaciones.fecimpo end as CONCILIACIONES_FECIMPO,
	case when c_conciliaciones.fmodifw = '01/01/1900 00:00:00' then null else c_conciliaciones.fmodifw end as CONCILIACIONES_FMODIFW,
	case when c_conciliaciones.fectrans = '01/01/1900 00:00:00' then null else c_conciliaciones.fectrans end as CONCILIACIONES_FECTRANS,
	C_CONCILIACIONES.HALTAFW as CONCILIACIONES_HALTAFW,
	C_CONCILIACIONES.HORAEXPO as CONCILIACIONES_HORAEXPO,
	C_CONCILIACIONES.HORAIMPO as CONCILIACIONES_HORAIMPO,
	C_CONCILIACIONES.HMODIFW as CONCILIACIONES_HMODIFW,
	C_CONCILIACIONES.SALTAFW as CONCILIACIONES_SALTAFW,
	C_CONCILIACIONES.SMODIFW as CONCILIACIONES_SMODIFW,
	C_CONCILIACIONES.UALTAFW as CONCILIACIONES_UALTAFW,
	C_CONCILIACIONES.UMODIFW as CONCILIACIONES_UMODIFW,
	C_CONCILIACIONES.VALTAFW as CONCILIACIONES_VALTAFW,
	C_CONCILIACIONES.VMODIFW as CONCILIACIONES_VMODIFW,
	C_CONCILIACIONES.ZADSFW as CONCILIACIONES_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMMOVBANCARIOS__SUCURSAL,
	case when c_movimientobancario.fecha = '01/01/1900 00:00:00' then null else c_movimientobancario.fecha end as MOVIMIENTOBANCARIO_Fecha,
	C_MOVIMIENTOBANCARIO.CONCEPTO as MOVIMIENTOBANCARIO_Concepto,
	C_MOVIMIENTOBANCARIO.NUMERO as MOVIMIENTOBANCARIO_Numero,
	C_MOVIMIENTOBANCARIO.IMPORTE as MOVIMIENTOBANCARIO_Importe,
	cast( '' as varchar( 100 ) ) as MOVIMIENTOBANCARIO_3_Descripcion,
	C_CUENTABANCARIA.CBDES as CUENTABANCARIA_CBDes,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	CASE WHEN 0=Funciones.Empty(C_CONCEPTOENTIDADFINANCIERA.DESCRI) THEN C_CONCEPTOENTIDADFINANCIERA.DESCRI ELSE C_CONCEPTOENTIDADFINANCIERA.CONCEPTO END AS CONCEPTOENTIDADFINANCIERA_Concepto,
	C_CONCEPTOENTIDADFINANCIERA.CODIGO as CONCEPTOENTIDADFINANCIERA_Codigo,
	C_CUENTABANCARIA.CBCOD as CUENTABANCARIA_CBCod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MOVIMIENTOBANCARIO.CODIGO as MOVIMIENTOBANCARIO_Codigo,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD
 from ZooLogic.DETMOVBANC as c_ITEMMOVBANCARIOS
 left join ZooLogic.CONCILIACION as C_CONCILIACIONES on C_CONCILIACIONES.CODIGO = C_ITEMMOVBANCARIOS.CODIGO and 0 = Funciones.empty( C_ITEMMOVBANCARIOS.CODIGO )
 left join ZooLogic.CTABAN as C_CUENTABANCARIA on C_CUENTABANCARIA.CBCOD = C_CONCILIACIONES.CTABANC and 0 = Funciones.empty( C_CONCILIACIONES.CTABANC )
 left join ZooLogic.MOVBANC as C_MOVIMIENTOBANCARIO on C_MOVIMIENTOBANCARIO.CODIGO = C_ITEMMOVBANCARIOS.MOV and 0 = Funciones.empty( C_ITEMMOVBANCARIOS.MOV )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.CONENTFIN as C_CONCEPTOENTIDADFINANCIERA on C_CONCEPTOENTIDADFINANCIERA.CODIGO = C_MOVIMIENTOBANCARIO.CONCEPTO and 0 = Funciones.empty( C_MOVIMIENTOBANCARIO.CONCEPTO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 where ( not 1 = funciones.empty( c_itemmovbancarios.codigo ) and ( not 1 = funciones.empty( c_conciliaciones.codigo ) ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_FECHA_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Fecha >= @MOVIMIENTOBANCARIO_3_FECHA_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_FECHA_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Fecha <= @MOVIMIENTOBANCARIO_3_FECHA_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_CONCEPTO_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Concepto >= @MOVIMIENTOBANCARIO_3_CONCEPTO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_CONCEPTO_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Concepto <= @MOVIMIENTOBANCARIO_3_CONCEPTO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_NUMERO_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Numero >= @MOVIMIENTOBANCARIO_3_NUMERO_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_NUMERO_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Numero <= @MOVIMIENTOBANCARIO_3_NUMERO_HASTA ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_IMPORTE_DESDE is null ) OR ( C_MOVIMIENTOBANCARIO.Importe >= @MOVIMIENTOBANCARIO_3_IMPORTE_DESDE ) ) and 
	( ( @MOVIMIENTOBANCARIO_3_IMPORTE_HASTA is null ) OR ( C_MOVIMIENTOBANCARIO.Importe <= @MOVIMIENTOBANCARIO_3_IMPORTE_HASTA ) ) and 
	( ( @ITEMMOVBANCARIOS_MOVIMIENTO_DESDE is null ) OR ( c_ITEMMOVBANCARIOS.Mov >= @ITEMMOVBANCARIOS_MOVIMIENTO_DESDE ) ) and 
	( ( @ITEMMOVBANCARIOS_MOVIMIENTO_HASTA is null ) OR ( c_ITEMMOVBANCARIOS.Mov <= @ITEMMOVBANCARIOS_MOVIMIENTO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_CODIGO_DESDE is null ) OR ( C_CONCILIACIONES.Codigo >= @CONCILIACIONES_1_CODIGO_DESDE ) ) and 
	( ( @CONCILIACIONES_1_CODIGO_HASTA is null ) OR ( C_CONCILIACIONES.Codigo <= @CONCILIACIONES_1_CODIGO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_NUMERO_DESDE is null ) OR ( C_CONCILIACIONES.Numero >= @CONCILIACIONES_1_NUMERO_DESDE ) ) and 
	( ( @CONCILIACIONES_1_NUMERO_HASTA is null ) OR ( C_CONCILIACIONES.Numero <= @CONCILIACIONES_1_NUMERO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_CUENTABANCARIA_DESDE is null ) OR ( C_CONCILIACIONES.CtaBanc >= @CONCILIACIONES_1_CUENTABANCARIA_DESDE ) ) and 
	( ( @CONCILIACIONES_1_CUENTABANCARIA_HASTA is null ) OR ( C_CONCILIACIONES.CtaBanc <= @CONCILIACIONES_1_CUENTABANCARIA_HASTA ) ) and 
	( ( @CUENTABANCARIA_25_CUENTABANCARIA_DESCRIPCION_DESDE is null ) OR ( C_CUENTABANCARIA.CBDes >= @CUENTABANCARIA_25_CUENTABANCARIA_DESCRIPCION_DESDE ) ) and 
	( ( @CUENTABANCARIA_25_CUENTABANCARIA_DESCRIPCION_HASTA is null ) OR ( C_CUENTABANCARIA.CBDes <= @CUENTABANCARIA_25_CUENTABANCARIA_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_13163_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_13163_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_13163_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_13163_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_13162_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_13162_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_13162_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_13162_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_13161_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_13161_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_13161_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_13161_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @CONCEPTOENTIDADFINANCIERA_13021_CONCEPTO_CONCEPTO_DESDE is null ) OR ( C_CONCEPTOENTIDADFINANCIERA.Concepto >= @CONCEPTOENTIDADFINANCIERA_13021_CONCEPTO_CONCEPTO_DESDE ) ) and 
	( ( @CONCEPTOENTIDADFINANCIERA_13021_CONCEPTO_CONCEPTO_HASTA is null ) OR ( C_CONCEPTOENTIDADFINANCIERA.Concepto <= @CONCEPTOENTIDADFINANCIERA_13021_CONCEPTO_CONCEPTO_HASTA ) ) and 
	( ( @SUCURSAL_13158_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_13158_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_13158_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_13158_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_13158_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_13158_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_13158_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_13158_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_13158_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_13158_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_13158_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_13158_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_13158_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_13158_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_13158_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_13158_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_13158_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_13158_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_13158_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_13158_CODIGO_HASTA ) ) and 
	( ( @ITEMMOVBANCARIOS_NROITEM_DESDE is null ) OR ( c_ITEMMOVBANCARIOS.NROITEM >= @ITEMMOVBANCARIOS_NROITEM_DESDE ) ) and 
	( ( @ITEMMOVBANCARIOS_NROITEM_HASTA is null ) OR ( c_ITEMMOVBANCARIOS.NROITEM <= @ITEMMOVBANCARIOS_NROITEM_HASTA ) ) and 
	( ( @CONCILIACIONES_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_CONCILIACIONES.BDALTAFW >= @CONCILIACIONES_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_CONCILIACIONES.BDALTAFW <= @CONCILIACIONES_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES.BDMODIFW >= @CONCILIACIONES_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES.BDMODIFW <= @CONCILIACIONES_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_CONCILIACIONES.ESTTRANS >= @CONCILIACIONES_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @CONCILIACIONES_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_CONCILIACIONES.ESTTRANS <= @CONCILIACIONES_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @CONCILIACIONES_1_FECHAALTAFW_DESDE is null ) OR ( C_CONCILIACIONES.FALTAFW >= @CONCILIACIONES_1_FECHAALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_FECHAALTAFW_HASTA is null ) OR ( C_CONCILIACIONES.FALTAFW <= @CONCILIACIONES_1_FECHAALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_FECHAEXPO_DESDE is null ) OR ( C_CONCILIACIONES.FECEXPO >= @CONCILIACIONES_1_FECHAEXPO_DESDE ) ) and 
	( ( @CONCILIACIONES_1_FECHAEXPO_HASTA is null ) OR ( C_CONCILIACIONES.FECEXPO <= @CONCILIACIONES_1_FECHAEXPO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_FECHAIMPO_DESDE is null ) OR ( C_CONCILIACIONES.FECIMPO >= @CONCILIACIONES_1_FECHAIMPO_DESDE ) ) and 
	( ( @CONCILIACIONES_1_FECHAIMPO_HASTA is null ) OR ( C_CONCILIACIONES.FECIMPO <= @CONCILIACIONES_1_FECHAIMPO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES.FMODIFW >= @CONCILIACIONES_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES.FMODIFW <= @CONCILIACIONES_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_CONCILIACIONES.FECTRANS >= @CONCILIACIONES_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @CONCILIACIONES_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_CONCILIACIONES.FECTRANS <= @CONCILIACIONES_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @CONCILIACIONES_1_HORAALTAFW_DESDE is null ) OR ( C_CONCILIACIONES.HALTAFW >= @CONCILIACIONES_1_HORAALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_HORAALTAFW_HASTA is null ) OR ( C_CONCILIACIONES.HALTAFW <= @CONCILIACIONES_1_HORAALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_HORAEXPO_DESDE is null ) OR ( C_CONCILIACIONES.HORAEXPO >= @CONCILIACIONES_1_HORAEXPO_DESDE ) ) and 
	( ( @CONCILIACIONES_1_HORAEXPO_HASTA is null ) OR ( C_CONCILIACIONES.HORAEXPO <= @CONCILIACIONES_1_HORAEXPO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_HORAIMPO_DESDE is null ) OR ( C_CONCILIACIONES.HORAIMPO >= @CONCILIACIONES_1_HORAIMPO_DESDE ) ) and 
	( ( @CONCILIACIONES_1_HORAIMPO_HASTA is null ) OR ( C_CONCILIACIONES.HORAIMPO <= @CONCILIACIONES_1_HORAIMPO_HASTA ) ) and 
	( ( @CONCILIACIONES_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES.HMODIFW >= @CONCILIACIONES_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES.HMODIFW <= @CONCILIACIONES_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_SERIEALTAFW_DESDE is null ) OR ( C_CONCILIACIONES.SALTAFW >= @CONCILIACIONES_1_SERIEALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_SERIEALTAFW_HASTA is null ) OR ( C_CONCILIACIONES.SALTAFW <= @CONCILIACIONES_1_SERIEALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES.SMODIFW >= @CONCILIACIONES_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES.SMODIFW <= @CONCILIACIONES_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_USUARIOALTAFW_DESDE is null ) OR ( C_CONCILIACIONES.UALTAFW >= @CONCILIACIONES_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_USUARIOALTAFW_HASTA is null ) OR ( C_CONCILIACIONES.UALTAFW <= @CONCILIACIONES_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES.UMODIFW >= @CONCILIACIONES_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES.UMODIFW <= @CONCILIACIONES_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_VERSIONALTAFW_DESDE is null ) OR ( C_CONCILIACIONES.VALTAFW >= @CONCILIACIONES_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_VERSIONALTAFW_HASTA is null ) OR ( C_CONCILIACIONES.VALTAFW <= @CONCILIACIONES_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @CONCILIACIONES_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_CONCILIACIONES.VMODIFW >= @CONCILIACIONES_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @CONCILIACIONES_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_CONCILIACIONES.VMODIFW <= @CONCILIACIONES_1_VERSIONMODIFICACIONFW_HASTA ) )

)