IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_GENERICO_REMITODECOMPRA_ITEMARTICULOSREMCOMPRA_ITEMARTICULOSREMCOMPRA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_GENERICO_REMITODECOMPRA_ITEMARTICULOSREMCOMPRA_ITEMARTICULOSREMCOMPRA];
GO;

CREATE FUNCTION [Listados].[HER_GENERICO_REMITODECOMPRA_ITEMARTICULOSREMCOMPRA_ITEMARTICULOSREMCOMPRA]
( @BaseDeDatos varchar(8),
	@REMITODECOMPRA_1_MONEDACOMPROBANTE_DESDE varchar(10),
	@REMITODECOMPRA_1_MONEDACOMPROBANTE_HASTA varchar(10),
	@ITEMARTICULOSREMCOMPRA_ARTICULO_DESDE varchar(15),
	@ITEMARTICULOSREMCOMPRA_ARTICULO_HASTA varchar(15),
	@ITEMARTICULOSREMCOMPRA_MONTOIVA_DESDE numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_MONTOIVA_HASTA numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_PRECIOCONIMPUESTOS_DESDE numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_PRECIOCONIMPUESTOS_HASTA numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_MONTODESCUENTOCONIMPUESTOS_DESDE numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_MONTODESCUENTOCONIMPUESTOS_HASTA numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_BRUTO_DESDE numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_BRUTO_HASTA numeric(15, 4),
	@ITEMARTICULOSREMCOMPRA_ARTICULODETALLE_DESDE varchar(100),
	@ITEMARTICULOSREMCOMPRA_ARTICULODETALLE_HASTA varchar(100),
	@ITEMARTICULOSREMCOMPRA_COLOR_DESDE varchar(6),
	@ITEMARTICULOSREMCOMPRA_COLOR_HASTA varchar(6),
	@ITEMARTICULOSREMCOMPRA_COLORDETALLE_DESDE varchar(50),
	@ITEMARTICULOSREMCOMPRA_COLORDETALLE_HASTA varchar(50),
	@ITEMARTICULOSREMCOMPRA_TALLE_DESDE varchar(5),
	@ITEMARTICULOSREMCOMPRA_TALLE_HASTA varchar(5),
	@ITEMARTICULOSREMCOMPRA_CANTIDAD_DESDE numeric(8, 2),
	@ITEMARTICULOSREMCOMPRA_CANTIDAD_HASTA numeric(8, 2),
	@ITEMARTICULOSREMCOMPRA_PRECIO_DESDE numeric(14, 4),
	@ITEMARTICULOSREMCOMPRA_PRECIO_HASTA numeric(14, 4),
	@ITEMARTICULOSREMCOMPRA_DESCUENTO_DESDE numeric(7, 2),
	@ITEMARTICULOSREMCOMPRA_DESCUENTO_HASTA numeric(7, 2),
	@ITEMARTICULOSREMCOMPRA_MONTODESCUENTO_DESDE numeric(12, 2),
	@ITEMARTICULOSREMCOMPRA_MONTODESCUENTO_HASTA numeric(12, 2),
	@ITEMARTICULOSREMCOMPRA_MONTO_DESDE numeric(15, 2),
	@ITEMARTICULOSREMCOMPRA_MONTO_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_CODIGO_DESDE varchar(38),
	@REMITODECOMPRA_1_CODIGO_HASTA varchar(38),
	@REMITODECOMPRA_1_LETRA_DESDE varchar(1),
	@REMITODECOMPRA_1_LETRA_HASTA varchar(1),
	@REMITODECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE numeric(5, 0),
	@REMITODECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA numeric(5, 0),
	@REMITODECOMPRA_1_NUMERO_DESDE numeric(8, 0),
	@REMITODECOMPRA_1_NUMERO_HASTA numeric(8, 0),
	@REMITODECOMPRA_1_PUNTODEVENTA_DESDE numeric(4, 0),
	@REMITODECOMPRA_1_PUNTODEVENTA_HASTA numeric(4, 0),
	@REMITODECOMPRA_1_PROVEEDOR_DESDE varchar(10),
	@REMITODECOMPRA_1_PROVEEDOR_HASTA varchar(10),
	@REMITODECOMPRA_1_LISTADEPRECIOS_DESDE varchar(6),
	@REMITODECOMPRA_1_LISTADEPRECIOS_HASTA varchar(6),
	@REMITODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE varchar(5),
	@REMITODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA varchar(5),
	@REMITODECOMPRA_1_MOTIVO_DESDE varchar(3),
	@REMITODECOMPRA_1_MOTIVO_HASTA varchar(3),
	@REMITODECOMPRA_1_TRANSPORTISTA_DESDE varchar(15),
	@REMITODECOMPRA_1_TRANSPORTISTA_HASTA varchar(15),
	@REMITODECOMPRA_1_NUMINT_DESDE numeric(10, 0),
	@REMITODECOMPRA_1_NUMINT_HASTA numeric(10, 0),
	@REMITODECOMPRA_1_FECHA_DESDE datetime,
	@REMITODECOMPRA_1_FECHA_HASTA datetime,
	@REMITODECOMPRA_1_COTIZACION_DESDE numeric(15, 5),
	@REMITODECOMPRA_1_COTIZACION_HASTA numeric(15, 5),
	@REMITODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE numeric(6, 2),
	@REMITODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA numeric(6, 2),
	@REMITODECOMPRA_1_DESCUENTO_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_DESCUENTO_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_RECARGOPORCENTAJE_DESDE numeric(6, 2),
	@REMITODECOMPRA_1_RECARGOPORCENTAJE_HASTA numeric(6, 2),
	@REMITODECOMPRA_1_RECARGOMONTO_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_RECARGOMONTO_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_RECARGOMONTO2_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_RECARGOMONTO2_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_IMPUESTOS_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_IMPUESTOS_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_TOTALIMPUESTOS_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_TOTALIMPUESTOS_HASTA numeric(15, 2),
	@REMITODECOMPRA_1_TOTAL_DESDE numeric(15, 2),
	@REMITODECOMPRA_1_TOTAL_HASTA numeric(15, 2),
	@PROVEEDOR_84_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_84_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@LISTADEPRECIOS_128_LISTADEPRECIOS_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_128_LISTADEPRECIOS_NOMBRE_HASTA varchar(30),
	@CONDICIONDEPAGO_129_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_129_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA varchar(100),
	@MOTIVO_130_MOTIVO_DESCRIPCION_DESDE varchar(40),
	@MOTIVO_130_MOTIVO_DESCRIPCION_HASTA varchar(40),
	@TRANSPORTISTA_131_TRANSPORTISTA_NOMBRE_DESDE varchar(30),
	@TRANSPORTISTA_131_TRANSPORTISTA_NOMBRE_HASTA varchar(30),
	@SEGMENTACION_9142_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_9142_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_9141_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_9141_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_9140_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_9140_TIPO_DESCRIPCION_HASTA varchar(50),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA varchar(60),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_11_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_12_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_12_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_13_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_13_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_14_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE varchar(40),
	@PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE varchar(40),
	@CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA varchar(40),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE varchar(150),
	@NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA varchar(150),
	@MARCA_42_MARCA_DESCRIPCION_DESDE varchar(100),
	@MARCA_42_MARCA_DESCRIPCION_HASTA varchar(100),
	@PROVINCIA_87_PROVINCIA_DESCRIPCION_DESDE varchar(50),
	@PROVINCIA_87_PROVINCIA_DESCRIPCION_HASTA varchar(50),
	@PAISES_103_PAIS_DESCRIPCION_DESDE varchar(30),
	@PAISES_103_PAIS_DESCRIPCION_HASTA varchar(30),
	@CLASIFICACIONPROVEEDOR_105_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONPROVEEDOR_105_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@CONDICIONDEPAGO_107_CONDICIONDEPAGO_DESCRIPCION_DESDE varchar(100),
	@CONDICIONDEPAGO_107_CONDICIONDEPAGO_DESCRIPCION_HASTA varchar(100),
	@LISTADEPRECIOS_110_LISTADEPRECIO_NOMBRE_DESDE varchar(30),
	@LISTADEPRECIOS_110_LISTADEPRECIO_NOMBRE_HASTA varchar(30),
	@IMPUESTO_112_RETENCIONGANANCIAS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_112_RETENCIONGANANCIAS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_113_RETENCIONSUSS_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_113_RETENCIONSUSS_DESCRIPCION_HASTA varchar(50),
	@IMPUESTO_114_RETENCIONIVA_DESCRIPCION_DESDE varchar(50),
	@IMPUESTO_114_RETENCIONIVA_DESCRIPCION_HASTA varchar(50),
	@DATOSADICIONALESSIPRIB_123_CODIGOSIPRIB_DESCRIPCION_DESDE varchar(15),
	@DATOSADICIONALESSIPRIB_123_CODIGOSIPRIB_DESCRIPCION_HASTA varchar(15),
	@MONEDA_9003_MONEDACOMPROBANTE_DESCRIPCION_DESDE varchar(40),
	@MONEDA_9003_MONEDACOMPROBANTE_DESCRIPCION_HASTA varchar(40),
	@SUCURSAL_9137_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_9137_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_9137_LINEA_DESDE varchar(10),
	@SUCURSAL_9137_LINEA_HASTA varchar(10),
	@SUCURSAL_9137_TIPO_DESDE varchar(10),
	@SUCURSAL_9137_TIPO_HASTA varchar(10),
	@SUCURSAL_9137_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_9137_DESCRIPCION_HASTA varchar(50),
	@ARTICULO_2_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_2_PROVEEDOR_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVAVENTAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA numeric(5, 2),
	@ARTICULO_2_IMAGEN_DESDE varchar(180),
	@ARTICULO_2_IMAGEN_HASTA varchar(180),
	@ARTICULO_2_TEMPORADA_DESDE varchar(5),
	@ARTICULO_2_TEMPORADA_HASTA varchar(5),
	@ARTICULO_2_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_2_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_2_FAMILIA_DESDE varchar(10),
	@ARTICULO_2_FAMILIA_HASTA varchar(10),
	@ARTICULO_2_MATERIAL_DESDE varchar(10),
	@ARTICULO_2_MATERIAL_HASTA varchar(10),
	@ARTICULO_2_LINEA_DESDE varchar(10),
	@ARTICULO_2_LINEA_HASTA varchar(10),
	@ARTICULO_2_GRUPO_DESDE varchar(10),
	@ARTICULO_2_GRUPO_HASTA varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_2_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_2_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_2_ANO_DESDE numeric(4, 0),
	@ARTICULO_2_ANO_HASTA numeric(4, 0),
	@ARTICULO_2_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_2_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_2_CONDICIONIVACOMPRAS numeric(1, 0),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA numeric(5, 2),
	@ARTICULO_2_COMPORTAMIENTO numeric(1, 0),
	@ARTICULO_2_PALETADECOLORES_DESDE varchar(10),
	@ARTICULO_2_PALETADECOLORES_HASTA varchar(10),
	@ARTICULO_2_CURVADETALLES_DESDE varchar(10),
	@ARTICULO_2_CURVADETALLES_HASTA varchar(10),
	@ARTICULO_2_NOCOMERCIALIZABLE_DESDE datetime,
	@ARTICULO_2_NOCOMERCIALIZABLE_HASTA datetime,
	@ARTICULO_2_NOMENCLADOR_DESDE varchar(6),
	@ARTICULO_2_NOMENCLADOR_HASTA varchar(6),
	@ARTICULO_2_NOPERMITEDEVOLUCIONES bit,
	@ARTICULO_2_IMPRIMEDESPACHO bit,
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE numeric(5, 2),
	@ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA numeric(5, 2),
	@ARTICULO_2_RESTRINGIRDESCUENTOS bit,
	@ARTICULO_2_PESO_DESDE numeric(11, 3),
	@ARTICULO_2_PESO_HASTA numeric(11, 3),
	@ARTICULO_2_LARGO_DESDE numeric(11, 2),
	@ARTICULO_2_LARGO_HASTA numeric(11, 2),
	@ARTICULO_2_ANCHO_DESDE numeric(11, 2),
	@ARTICULO_2_ANCHO_HASTA numeric(11, 2),
	@ARTICULO_2_ALTO_DESDE numeric(11, 2),
	@ARTICULO_2_ALTO_HASTA numeric(11, 2),
	@ARTICULO_2_REQUIERECCOSTO_DESDE numeric(1, 0),
	@ARTICULO_2_REQUIERECCOSTO_HASTA numeric(1, 0),
	@ARTICULO_2_NOPUBLICARENECOMMERCE bit,
	@ARTICULO_2_IMPORTADO bit,
	@ARTICULO_2_DESCRIPCIONADICIONAL_DESDE varchar(254),
	@ARTICULO_2_DESCRIPCIONADICIONAL_HASTA varchar(254),
	@ARTICULO_2_SOLOPROMOYKIT bit,
	@ARTICULO_2_RESTRINGIRARTICULO_DESDE datetime,
	@ARTICULO_2_RESTRINGIRARTICULO_HASTA datetime,
	@ARTICULO_2_MARCA_DESDE varchar(30),
	@ARTICULO_2_MARCA_HASTA varchar(30),
	@ARTICULO_2_PERCEPCIONIVARG5329 numeric(1, 0),
	@PROVEEDOR_84_LOCALIDAD_DESDE varchar(70),
	@PROVEEDOR_84_LOCALIDAD_HASTA varchar(70),
	@PROVEEDOR_84_CODIGOPOSTAL_DESDE varchar(8),
	@PROVEEDOR_84_CODIGOPOSTAL_HASTA varchar(8),
	@PROVEEDOR_84_PROVINCIA_DESDE varchar(2),
	@PROVEEDOR_84_PROVINCIA_HASTA varchar(2),
	@PROVEEDOR_84_TELEFONO_DESDE varchar(30),
	@PROVEEDOR_84_TELEFONO_HASTA varchar(30),
	@PROVEEDOR_84_FAX_DESDE varchar(60),
	@PROVEEDOR_84_FAX_HASTA varchar(60),
	@PROVEEDOR_84_EMAIL_DESDE varchar(250),
	@PROVEEDOR_84_EMAIL_HASTA varchar(250),
	@PROVEEDOR_84_PAGINAWEB_DESDE varchar(60),
	@PROVEEDOR_84_PAGINAWEB_HASTA varchar(60),
	@SITUACIONFISCAL_92_SITUACIONFISCAL_DESCRIPCION varchar(40),
	@PROVEEDOR_84_CUIT_DESDE varchar(15),
	@PROVEEDOR_84_CUIT_HASTA varchar(15),
	@PROVEEDOR_84_TIPODOCUMENTO_DESDE varchar(2),
	@PROVEEDOR_84_TIPODOCUMENTO_HASTA varchar(2),
	@PROVEEDOR_84_NRODOCUMENTO_DESDE varchar(10),
	@PROVEEDOR_84_NRODOCUMENTO_HASTA varchar(10),
	@PROVEEDOR_84_IMAGEN_DESDE varchar(180),
	@PROVEEDOR_84_IMAGEN_HASTA varchar(180),
	@PROVEEDOR_84_NUMERO_DESDE numeric(5, 0),
	@PROVEEDOR_84_NUMERO_HASTA numeric(5, 0),
	@PROVEEDOR_84_CALLE_DESDE varchar(70),
	@PROVEEDOR_84_CALLE_HASTA varchar(70),
	@PROVEEDOR_84_PISO_DESDE varchar(3),
	@PROVEEDOR_84_PISO_HASTA varchar(3),
	@PROVEEDOR_84_DEPARTAMENTO_DESDE varchar(3),
	@PROVEEDOR_84_DEPARTAMENTO_HASTA varchar(3),
	@PROVEEDOR_84_PAIS_DESDE varchar(3),
	@PROVEEDOR_84_PAIS_HASTA varchar(3),
	@PROVEEDOR_84_MOVIL_DESDE varchar(30),
	@PROVEEDOR_84_MOVIL_HASTA varchar(30),
	@PROVEEDOR_84_CLASIFICACION_DESDE varchar(10),
	@PROVEEDOR_84_CLASIFICACION_HASTA varchar(10),
	@PROVEEDOR_84_FECHANACIMIENTO_DESDE datetime,
	@PROVEEDOR_84_FECHANACIMIENTO_HASTA datetime,
	@PROVEEDOR_84_CONDICIONDEPAGO_DESDE varchar(5),
	@PROVEEDOR_84_CONDICIONDEPAGO_HASTA varchar(5),
	@PROVEEDOR_84_TIPOCONVENIO_DESDE numeric(1, 0),
	@PROVEEDOR_84_TIPOCONVENIO_HASTA numeric(1, 0),
	@PROVEEDOR_84_NROIIBB_DESDE numeric(11, 0),
	@PROVEEDOR_84_NROIIBB_HASTA numeric(11, 0),
	@PROVEEDOR_84_LISTADEPRECIO_DESDE varchar(6),
	@PROVEEDOR_84_LISTADEPRECIO_HASTA varchar(6),
	@PROVEEDOR_84_SITUACIONGANANCIAS numeric(1, 0),
	@PROVEEDOR_84_RETENCIONGANANCIAS_DESDE varchar(10),
	@PROVEEDOR_84_RETENCIONGANANCIAS_HASTA varchar(10),
	@PROVEEDOR_84_RETENCIONSUSS_DESDE varchar(10),
	@PROVEEDOR_84_RETENCIONSUSS_HASTA varchar(10),
	@PROVEEDOR_84_RETENCIONIVA_DESDE varchar(10),
	@PROVEEDOR_84_RETENCIONIVA_HASTA varchar(10),
	@PROVEEDOR_84_OBJETOIVA numeric(1, 0),
	@PROVEEDOR_84_EMPLEADOR bit,
	@PROVEEDOR_84_EXCLUIDORETENCIONGANANCIAS bit,
	@PROVEEDOR_84_EXCLUIDORETENCIONIVA bit,
	@PROVEEDOR_84_EXCLUIDORETENCIONSUSS bit,
	@PROVEEDOR_84_SUJETOVINCULADO bit,
	@PROVEEDOR_84_VIGENCIAHASTAIVA_DESDE datetime,
	@PROVEEDOR_84_VIGENCIAHASTAIVA_HASTA datetime,
	@PROVEEDOR_84_VIGENCIAHASTAGAN_DESDE datetime,
	@PROVEEDOR_84_VIGENCIAHASTAGAN_HASTA datetime,
	@PROVEEDOR_84_CODIGOSIPRIB_DESDE varchar(20),
	@PROVEEDOR_84_CODIGOSIPRIB_HASTA varchar(20),
	@PROVEEDOR_84_TASACEROPORCEN_DESDE numeric(6, 2),
	@PROVEEDOR_84_TASACEROPORCEN_HASTA numeric(6, 2),
	@PROVEEDOR_84_TASACEROAPLICA bit,
	@PROVEEDOR_84_RUT_DESDE varchar(12),
	@PROVEEDOR_84_RUT_HASTA varchar(12),
	@PROVEEDOR_84_INACTIVOFW bit,
	@SUCURSAL_9137_CODIGO_DESDE varchar(10),
	@SUCURSAL_9137_CODIGO_HASTA varchar(10),
	@ITEMARTICULOSREMCOMPRA_NROITEM_DESDE numeric(5, 0),
	@ITEMARTICULOSREMCOMPRA_NROITEM_HASTA numeric(5, 0),
	@REMITODECOMPRA_1_BASEDEDATOSALTAFW_DESDE varchar(8),
	@REMITODECOMPRA_1_BASEDEDATOSALTAFW_HASTA varchar(8),
	@REMITODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE varchar(8),
	@REMITODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA varchar(8),
	@REMITODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE varchar(20),
	@REMITODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA varchar(20),
	@REMITODECOMPRA_1_FECHAALTAFW_DESDE datetime,
	@REMITODECOMPRA_1_FECHAALTAFW_HASTA datetime,
	@REMITODECOMPRA_1_FECHAEXPO_DESDE datetime,
	@REMITODECOMPRA_1_FECHAEXPO_HASTA datetime,
	@REMITODECOMPRA_1_FECHAIMPO_DESDE datetime,
	@REMITODECOMPRA_1_FECHAIMPO_HASTA datetime,
	@REMITODECOMPRA_1_FECHAMODIFICACIONFW_DESDE datetime,
	@REMITODECOMPRA_1_FECHAMODIFICACIONFW_HASTA datetime,
	@REMITODECOMPRA_1_FECHATRANSFERENCIA_DESDE datetime,
	@REMITODECOMPRA_1_FECHATRANSFERENCIA_HASTA datetime,
	@REMITODECOMPRA_1_HORAALTAFW_DESDE varchar(8),
	@REMITODECOMPRA_1_HORAALTAFW_HASTA varchar(8),
	@REMITODECOMPRA_1_HORAEXPO_DESDE varchar(8),
	@REMITODECOMPRA_1_HORAEXPO_HASTA varchar(8),
	@REMITODECOMPRA_1_HORAIMPO_DESDE varchar(8),
	@REMITODECOMPRA_1_HORAIMPO_HASTA varchar(8),
	@REMITODECOMPRA_1_HORAMODIFICACIONFW_DESDE varchar(8),
	@REMITODECOMPRA_1_HORAMODIFICACIONFW_HASTA varchar(8),
	@REMITODECOMPRA_1_SERIEALTAFW_DESDE varchar(7),
	@REMITODECOMPRA_1_SERIEALTAFW_HASTA varchar(7),
	@REMITODECOMPRA_1_SERIEMODIFICACIONFW_DESDE varchar(7),
	@REMITODECOMPRA_1_SERIEMODIFICACIONFW_HASTA varchar(7),
	@REMITODECOMPRA_1_USUARIOALTAFW_DESDE varchar(100),
	@REMITODECOMPRA_1_USUARIOALTAFW_HASTA varchar(100),
	@REMITODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE varchar(100),
	@REMITODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA varchar(100),
	@REMITODECOMPRA_1_VERSIONALTAFW_DESDE varchar(13),
	@REMITODECOMPRA_1_VERSIONALTAFW_HASTA varchar(13),
	@REMITODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE varchar(13),
	@REMITODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA varchar(13) )
RETURNS TABLE
AS
RETURN
with ConjuntoBase as
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_itemarticulosremcompra.codigo, 38, ' ' ) as varchar( 46 ) ) as ITEMARTICULOSREMCOMPRA__Grupo,
	@basededatos as ITEMARTICULOSREMCOMPRA__BD,
	/* Campos requeridos para las consultas derivadas */
	c_ITEMARTICULOSREMCOMPRA.CODIGO,
	c_ITEMARTICULOSREMCOMPRA.IDITEM,
	c_ITEMARTICULOSREMCOMPRA.AFE_COD,
	c_ITEMARTICULOSREMCOMPRA.AFESALDO,
	c_ITEMARTICULOSREMCOMPRA.FCANT,
	C_REMITODECOMPRA.FACTTIPO,
	/*------------------------------------------------*/
	c_ITEMARTICULOSREMCOMPRA.CODIGO as ITEMARTICULOSREMCOMPRA_CODIGO,
	c_ITEMARTICULOSREMCOMPRA.FART as ITEMARTICULOSREMCOMPRA_FART,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	c_ITEMARTICULOSREMCOMPRA.FMTOIVA as ITEMARTICULOSREMCOMPRA_FmtoIVA,
	c_ITEMARTICULOSREMCOMPRA.PRUNCONIMP as ITEMARTICULOSREMCOMPRA_prunconimp,
	c_ITEMARTICULOSREMCOMPRA.MNDESCI as ITEMARTICULOSREMCOMPRA_MNDESCI,
	c_ITEMARTICULOSREMCOMPRA.FBRUTO as ITEMARTICULOSREMCOMPRA_FBruto,
	c_ITEMARTICULOSREMCOMPRA.FTXT as ITEMARTICULOSREMCOMPRA_FTXT,
	c_ITEMARTICULOSREMCOMPRA.FCOLO as ITEMARTICULOSREMCOMPRA_FCOLO,
	cast( funciones.obtenerordenenlapaletadecolores(c_itemarticulosremcompra.fart, c_itemarticulosremcompra.fcolo, c_articulo.palcol, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSREMCOMPRA_OrdenPaletaColores,
	c_ITEMARTICULOSREMCOMPRA.FCOTXT as ITEMARTICULOSREMCOMPRA_FCOTXT,
	c_ITEMARTICULOSREMCOMPRA.FTALL as ITEMARTICULOSREMCOMPRA_FTALL,
	cast( funciones.obtenerordenenlacurvadetalle(c_itemarticulosremcompra.fart, c_itemarticulosremcompra.ftall, c_articulo.curtall, c_articulo.grupo) as numeric( 3, 0 ) ) as ITEMARTICULOSREMCOMPRA_OrdenCurvaTalles,
	c_ITEMARTICULOSREMCOMPRA.FCANT as ITEMARTICULOSREMCOMPRA_FCANT,
	c_ITEMARTICULOSREMCOMPRA.FPRECIO as ITEMARTICULOSREMCOMPRA_FPRECIO,
	c_ITEMARTICULOSREMCOMPRA.FCFI as ITEMARTICULOSREMCOMPRA_FCFI,
	c_ITEMARTICULOSREMCOMPRA.MNTDES as ITEMARTICULOSREMCOMPRA_MNTDES,
	c_ITEMARTICULOSREMCOMPRA.FMONTO as ITEMARTICULOSREMCOMPRA_FMONTO,
	C_REMITODECOMPRA.CODIGO as REMITODECOMPRA_CODIGO,
	C_REMITODECOMPRA.FLETRA as REMITODECOMPRA_FLETRA,
	C_REMITODECOMPRA.FPTOVENEXT as REMITODECOMPRA_FPTOVENEXT,
	C_REMITODECOMPRA.FNUMCOMP as REMITODECOMPRA_FNUMCOMP,
	C_REMITODECOMPRA.FPTOVEN as REMITODECOMPRA_FPTOVEN,
	C_REMITODECOMPRA.FPERSON as REMITODECOMPRA_FPerson,
	C_PROVEEDOR84.CIMAGEN as PROVEEDOR84_CIMAGEN,
	C_REMITODECOMPRA.CODLISTA as REMITODECOMPRA_CodLista,
	C_REMITODECOMPRA.CONDPAGO as REMITODECOMPRA_CONDPAGO,
	C_REMITODECOMPRA.MOTIVO as REMITODECOMPRA_MOTIVO,
	C_REMITODECOMPRA.FTRANSP as REMITODECOMPRA_FTransp,
	C_REMITODECOMPRA.NUMINT as REMITODECOMPRA_NumInt,
	case when c_remitodecompra.ffch = '01/01/1900 00:00:00' then null else c_remitodecompra.ffch end as REMITODECOMPRA_FFCH,
	C_REMITODECOMPRA.COTIZ as REMITODECOMPRA_Cotiz,
	C_REMITODECOMPRA.FPODES as REMITODECOMPRA_FPODES,
	C_REMITODECOMPRA.FDESCU as REMITODECOMPRA_fDescu,
	C_REMITODECOMPRA.FOBS as REMITODECOMPRA_FObs,
	C_REMITODECOMPRA.FMTDES3 as REMITODECOMPRA_FMTDES3,
	C_REMITODECOMPRA.RECPOR as REMITODECOMPRA_RecPor,
	C_REMITODECOMPRA.MR as REMITODECOMPRA_MR,
	C_REMITODECOMPRA.RECMONTO2 as REMITODECOMPRA_RecMonto2,
	C_REMITODECOMPRA.FIMPUESTO as REMITODECOMPRA_fImpuesto,
	C_REMITODECOMPRA.TOTIMPUE as REMITODECOMPRA_totimpue,
	C_REMITODECOMPRA.FTOTAL as REMITODECOMPRA_FTotal,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_ARTICULO.ARTCONIVA as ARTICULO_ARTCONIVA,
	C_ARTICULO.ARTPORIVA as ARTICULO_ARTPORIVA,
	C_ARTICULO.AOBS as ARTICULO_AObs,
	C_ARTICULO.ATEMPORADA as ARTICULO_ATEMPORADA,
	C_ARTICULO.UNIMED as ARTICULO_UniMed,
	C_ARTICULO.FAMILIA as ARTICULO_Familia,
	C_ARTICULO.MAT as ARTICULO_Mat,
	C_ARTICULO.LINEA as ARTICULO_Linea,
	C_ARTICULO.GRUPO as ARTICULO_Grupo,
	C_ARTICULO.CATEARTI as ARTICULO_CateArti,
	C_ARTICULO.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	C_ARTICULO.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ARTIVA as ARTICULO_ARTIVA,
	C_ARTICULO.ANX2 as ARTICULO_ANX2,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	C_ARTICULO.PALCOL as ARTICULO_PalCol,
	C_ARTICULO.CURTALL as ARTICULO_Curtall,
	case when c_articulo.nocom = '01/01/1900 00:00:00' then null else c_articulo.nocom end as ARTICULO_NOCOM,
	C_ARTICULO.ARTNARBA as ARTICULO_ARTNARBA,
	C_ARTICULO.ARTNODEVO as ARTICULO_ARTNODEVO,
	C_ARTICULO.ESIMPDES as ARTICULO_EsImpDes,
	C_ARTICULO.IMPINTERNO as ARTICULO_impinterno,
	C_ARTICULO.ARTSINDES as ARTICULO_ArtSinDes,
	C_ARTICULO.ARTPESO as ARTICULO_ARTPESO,
	C_ARTICULO.ARTLARGO as ARTICULO_ARTLARGO,
	C_ARTICULO.ARTANCHO as ARTICULO_ARTANCHO,
	C_ARTICULO.ARTALTO as ARTICULO_ARTALTO,
	C_ARTICULO.REQCCOSTO as ARTICULO_ReqCCosto,
	C_ARTICULO.PUBECOM as ARTICULO_PubEcom,
	C_ARTICULO.IMPORTADO as ARTICULO_Importado,
	C_ARTICULO.ARTDESADIC as ARTICULO_ARTDESADIC,
	C_ARTICULO.PROMOYKIT as ARTICULO_PromoYKit,
	C_ARTICULO.DESECOHTML as ARTICULO_DesEcoHTML,
	C_ARTICULO.DESECO as ARTICULO_DesEco,
	case when c_articulo.artrest = '01/01/1900 00:00:00' then null else c_articulo.artrest end as ARTICULO_ArtRest,
	C_ARTICULO.MARCA as ARTICULO_Marca,
	C_ARTICULO.ARTPERCEP as ARTICULO_ArtPercep,
	C_PROVEEDOR84.CLLOC as PROVEEDOR84_CLLOC,
	C_PROVEEDOR84.CLCP as PROVEEDOR84_CLCP,
	C_PROVEEDOR84.CLPRV as PROVEEDOR84_CLPRV,
	C_PROVEEDOR84.CLTLF as PROVEEDOR84_CLTLF,
	C_PROVEEDOR84.CLFAX as PROVEEDOR84_CLFAX,
	C_PROVEEDOR84.CLEMAIL as PROVEEDOR84_CLEMAIL,
	C_PROVEEDOR84.CLPAGEWEB as PROVEEDOR84_CLPAGEWEB,
	C_SITUACIONFISCAL.DESCRIP as SITUACIONFISCAL_Descrip,
	C_PROVEEDOR84.CLCUIT as PROVEEDOR84_CLCUIT,
	C_PROVEEDOR84.CLOBS as PROVEEDOR84_CLOBS,
	C_PROVEEDOR84.CLTIPODOC as PROVEEDOR84_CLTIPODOC,
	C_PROVEEDOR84.CLNRODOC as PROVEEDOR84_CLNRODOC,
	C_PROVEEDOR84.PNUMERO as PROVEEDOR84_PNUMERO,
	C_PROVEEDOR84.PCALLE as PROVEEDOR84_PCALLE,
	C_PROVEEDOR84.PPISO as PROVEEDOR84_PPISO,
	C_PROVEEDOR84.PDEPTO as PROVEEDOR84_PDEPTO,
	C_PROVEEDOR84.PPAIS as PROVEEDOR84_PPAIS,
	C_PROVEEDOR84.TLFM as PROVEEDOR84_TLFM,
	C_PROVEEDOR84.CLAS as PROVEEDOR84_CLAS,
	case when c_proveedor84.clfecha = '01/01/1900 00:00:00' then null else c_proveedor84.clfecha end as PROVEEDOR84_CLFECHA,
	C_PROVEEDOR84.CLCONDPAG as PROVEEDOR84_CLCONDPAG,
	C_PROVEEDOR84.CLTIPCONV as PROVEEDOR84_CLTIPCONV,
	C_PROVEEDOR84.CLNROIIBB as PROVEEDOR84_CLNROIIBB,
	C_PROVEEDOR84.CLLISTPRE as PROVEEDOR84_CLLISTPRE,
	C_PROVEEDOR84.CLSITGAN as PROVEEDOR84_CLSITGAN,
	C_PROVEEDOR84.CLRETGAN as PROVEEDOR84_CLRETGAN,
	C_PROVEEDOR84.CLRETSUSS as PROVEEDOR84_CLRETSUSS,
	C_PROVEEDOR84.CLRETIVA as PROVEEDOR84_CLRETIVA,
	C_PROVEEDOR84.CLOBJIVA as PROVEEDOR84_CLOBJIVA,
	C_PROVEEDOR84.CLEMPLEAD as PROVEEDOR84_CLEMPLEAD,
	C_PROVEEDOR84.EXRETGAN as PROVEEDOR84_EXRETGAN,
	C_PROVEEDOR84.EXRETIVA as PROVEEDOR84_EXRETIVA,
	C_PROVEEDOR84.EXRETSUSS as PROVEEDOR84_EXRETSUSS,
	C_PROVEEDOR84.CLSUJVINC as PROVEEDOR84_CLSujVinc,
	case when c_proveedor84.pvhastaiva = '01/01/1900 00:00:00' then null else c_proveedor84.pvhastaiva end as PROVEEDOR84_PVHastaIva,
	case when c_proveedor84.pvhastagan = '01/01/1900 00:00:00' then null else c_proveedor84.pvhastagan end as PROVEEDOR84_PVHastaGan,
	C_PROVEEDOR84.CLSIPRIB as PROVEEDOR84_CLSIPRIB,
	C_PROVEEDOR84.PORCENTC as PROVEEDOR84_PorcenTC,
	C_PROVEEDOR84.APLICATC as PROVEEDOR84_AplicaTC,
	C_PROVEEDOR84.RUT as PROVEEDOR84_RUT,
	C_PROVEEDOR84.INACTIVOFW as PROVEEDOR84_InactivoFW,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	c_ITEMARTICULOSREMCOMPRA.NROITEM as ITEMARTICULOSREMCOMPRA_NroItem,
	C_REMITODECOMPRA.BDALTAFW as REMITODECOMPRA_BDALTAFW,
	C_REMITODECOMPRA.BDMODIFW as REMITODECOMPRA_BDMODIFW,
	C_REMITODECOMPRA.ESTTRANS as REMITODECOMPRA_ESTTRANS,
	case when c_remitodecompra.faltafw = '01/01/1900 00:00:00' then null else c_remitodecompra.faltafw end as REMITODECOMPRA_FALTAFW,
	case when c_remitodecompra.fecexpo = '01/01/1900 00:00:00' then null else c_remitodecompra.fecexpo end as REMITODECOMPRA_FECEXPO,
	case when c_remitodecompra.fecimpo = '01/01/1900 00:00:00' then null else c_remitodecompra.fecimpo end as REMITODECOMPRA_FECIMPO,
	case when c_remitodecompra.fmodifw = '01/01/1900 00:00:00' then null else c_remitodecompra.fmodifw end as REMITODECOMPRA_FMODIFW,
	case when c_remitodecompra.fectrans = '01/01/1900 00:00:00' then null else c_remitodecompra.fectrans end as REMITODECOMPRA_FECTRANS,
	C_REMITODECOMPRA.HALTAFW as REMITODECOMPRA_HALTAFW,
	C_REMITODECOMPRA.HORAEXPO as REMITODECOMPRA_HORAEXPO,
	C_REMITODECOMPRA.HORAIMPO as REMITODECOMPRA_HORAIMPO,
	C_REMITODECOMPRA.HMODIFW as REMITODECOMPRA_HMODIFW,
	C_REMITODECOMPRA.SALTAFW as REMITODECOMPRA_SALTAFW,
	C_REMITODECOMPRA.SMODIFW as REMITODECOMPRA_SMODIFW,
	C_REMITODECOMPRA.UALTAFW as REMITODECOMPRA_UALTAFW,
	C_REMITODECOMPRA.UMODIFW as REMITODECOMPRA_UMODIFW,
	C_REMITODECOMPRA.VALTAFW as REMITODECOMPRA_VALTAFW,
	C_REMITODECOMPRA.VMODIFW as REMITODECOMPRA_VMODIFW,
	C_REMITODECOMPRA.ZADSFW as REMITODECOMPRA_ZADSFW,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ITEMARTICULOSREMCOMPRA__SUCURSAL,
	cast( funciones.identificadordecomprobantecomprasparalistado(c_remitodecompra.facttipo, c_remitodecompra.fletra, c_remitodecompra.fptoven, c_remitodecompra.fptovenext, c_remitodecompra.fnumcomp) as varchar( 20 ) ) as REMITODECOMPRA_1_ComprobanteVirtual,
	C_REMITODECOMPRA.MONEDA as REMITODECOMPRA_Moneda,
	--cast( 0 as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CantidadTramo0Virtual,
	--cast( 0 as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CancelaTramo0Virtual,
	--cast( 0 as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CantidadTramo1Virtual,
	--cast( 0 as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CancelaTramo1Virtual,
	--cast( 0 as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_PendienteTramo1Virtual,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_PROVEEDOR84.CLNOM as PROVEEDOR84_CLNOM,
	C_LISTADEPRECIOS128.LPR_NOMBRE as LISTADEPRECIOS128_LPR_NOMBRE,
	C_CONDICIONDEPAGO129.CLNOM as CONDICIONDEPAGO129_CLNOM,
	C_MOTIVO.MOTDES as MOTIVO_MOTDES,
	C_TRANSPORTISTA.TRNOM as TRANSPORTISTA_TRNOM,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_PROVEEDOR3.CLNOM as PROVEEDOR3_CLNOM,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_PALETADECOLORES.DESCRIP as PALETADECOLORES_Descrip,
	C_CURVADETALLES.DESCRIP as CURVADETALLES_Descrip,
	C_NOMENCLADORARBA.NMCDES as NOMENCLADORARBA_NMCDES,
	C_MARCA.DESCRIP as MARCA_Descrip,
	C_PROVINCIA.PRV_DES as PROVINCIA_PRV_DES,
	C_PROVEEDOR84.CLIVA as PROVEEDOR84_CLIVA,
	C_PAISES.PDES as PAISES_pdes,
	C_CLASIFICACIONPROVEEDOR.CLADES as CLASIFICACIONPROVEEDOR_CLADES,
	C_CONDICIONDEPAGO107.CLNOM as CONDICIONDEPAGO107_CLNOM,
	C_LISTADEPRECIOS110.LPR_NOMBRE as LISTADEPRECIOS110_LPR_NOMBRE,
	C_IMPUESTO112.DESCRIP as IMPUESTO112_descrip,
	C_IMPUESTO113.DESCRIP as IMPUESTO113_descrip,
	C_IMPUESTO114.DESCRIP as IMPUESTO114_descrip,
	C_DATOSADICIONALESSIPRIB.DESCRIP as DATOSADICIONALESSIPRIB_Descrip,
	C_MONEDA.DESCRIP as MONEDA_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_CLASIFICACIONPROVEEDOR.CLACOD as CLASIFICACIONPROVEEDOR_CLACOD,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_CONDICIONDEPAGO107.CLCOD as CONDICIONDEPAGO107_CLCOD,
	C_CONDICIONDEPAGO129.CLCOD as CONDICIONDEPAGO129_CLCOD,
	C_CURVADETALLES.CODIGO as CURVADETALLES_Codigo,
	C_DATOSADICIONALESSIPRIB.CODIGO as DATOSADICIONALESSIPRIB_Codigo,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_IMPUESTO112.CODIGO as IMPUESTO112_codigo,
	C_IMPUESTO113.CODIGO as IMPUESTO113_codigo,
	C_IMPUESTO114.CODIGO as IMPUESTO114_codigo,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_LISTADEPRECIOS110.LPR_NUMERO as LISTADEPRECIOS110_LPR_NUMERO,
	C_LISTADEPRECIOS128.LPR_NUMERO as LISTADEPRECIOS128_LPR_NUMERO,
	C_MARCA.CODIGO as MARCA_Codigo,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_MONEDA.CODIGO as MONEDA_Codigo,
	C_MOTIVO.MOTCOD as MOTIVO_MOTCOD,
	C_NOMENCLADORARBA.NMCCOD as NOMENCLADORARBA_NMCCOD,
	C_PAISES.PCOD as PAISES_pcod,
	C_PALETADECOLORES.CODIGO as PALETADECOLORES_Codigo,
	C_PROVEEDOR3.CLCOD as PROVEEDOR3_CLCOD,
	C_PROVEEDOR84.CLCOD as PROVEEDOR84_CLCOD,
	C_PROVINCIA.PRV_COD as PROVINCIA_PRV_COD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_SITUACIONFISCAL.CODIGO as SITUACIONFISCAL_Codigo,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_TRANSPORTISTA.TRCOD as TRANSPORTISTA_TRCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from ZooLogic.REMCOMPRADET as c_ITEMARTICULOSREMCOMPRA
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ITEMARTICULOSREMCOMPRA.FART and 0 = Funciones.empty( C_ITEMARTICULOSREMCOMPRA.FART )
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = C_ARTICULO.CATEARTI and 0 = Funciones.empty( C_ARTICULO.CATEARTI )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = C_ARTICULO.CLASIFART and 0 = Funciones.empty( C_ARTICULO.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ITEMARTICULOSREMCOMPRA.FCOLO and 0 = Funciones.empty( C_ITEMARTICULOSREMCOMPRA.FCOLO )
 left join ZooLogic.CTALLE as C_CURVADETALLES on C_CURVADETALLES.CODIGO = C_ARTICULO.CURTALL and 0 = Funciones.empty( C_ARTICULO.CURTALL )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.MARCAS as C_MARCA on C_MARCA.CODIGO = C_ARTICULO.MARCA and 0 = Funciones.empty( C_ARTICULO.MARCA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.NMCARBA as C_NOMENCLADORARBA on C_NOMENCLADORARBA.NMCCOD = C_ARTICULO.ARTNARBA and 0 = Funciones.empty( C_ARTICULO.ARTNARBA )
 left join ZooLogic.PCOLOR as C_PALETADECOLORES on C_PALETADECOLORES.CODIGO = C_ARTICULO.PALCOL and 0 = Funciones.empty( C_ARTICULO.PALCOL )
 left join ZooLogic.PROV as C_PROVEEDOR3 on C_PROVEEDOR3.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ZooLogic.REMCOMPRA as C_REMITODECOMPRA on C_REMITODECOMPRA.CODIGO = C_ITEMARTICULOSREMCOMPRA.CODIGO and 0 = Funciones.empty( C_ITEMARTICULOSREMCOMPRA.CODIGO )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ITEMARTICULOSREMCOMPRA.FTALL and 0 = Funciones.empty( C_ITEMARTICULOSREMCOMPRA.FTALL )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.TRA as C_TRANSPORTISTA on C_TRANSPORTISTA.TRCOD = C_REMITODECOMPRA.FTRANSP and 0 = Funciones.empty( C_REMITODECOMPRA.FTRANSP )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = C_ARTICULO.UNIMED and 0 = Funciones.empty( C_ARTICULO.UNIMED )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO129 on C_CONDICIONDEPAGO129.CLCOD = C_REMITODECOMPRA.CONDPAGO and 0 = Funciones.empty( C_REMITODECOMPRA.CONDPAGO )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS128 on C_LISTADEPRECIOS128.LPR_NUMERO = C_REMITODECOMPRA.CODLISTA and 0 = Funciones.empty( C_REMITODECOMPRA.CODLISTA )
 left join ZooLogic.MONEDA as C_MONEDA on C_MONEDA.CODIGO = C_REMITODECOMPRA.MONEDA and 0 = Funciones.empty( C_REMITODECOMPRA.MONEDA )
 left join ZooLogic.MOTIVO as C_MOTIVO on C_MOTIVO.MOTCOD = C_REMITODECOMPRA.MOTIVO and 0 = Funciones.empty( C_REMITODECOMPRA.MOTIVO )
 left join ZooLogic.PROV as C_PROVEEDOR84 on C_PROVEEDOR84.CLCOD = C_REMITODECOMPRA.FPERSON and 0 = Funciones.empty( C_REMITODECOMPRA.FPERSON )
 left join ZooLogic.PROVINCI as C_PROVINCIA on C_PROVINCIA.PRV_COD = C_PROVEEDOR84.CLPRV and 0 = Funciones.empty( C_PROVEEDOR84.CLPRV )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 left join ORGANIZACION.SITFISCAL as C_SITUACIONFISCAL on C_SITUACIONFISCAL.CODIGO = C_PROVEEDOR84.CLIVA and 0 = Funciones.empty( C_PROVEEDOR84.CLIVA )
 left join ZooLogic.CLASPROV as C_CLASIFICACIONPROVEEDOR on C_CLASIFICACIONPROVEEDOR.CLACOD = C_PROVEEDOR84.CLAS and 0 = Funciones.empty( C_PROVEEDOR84.CLAS )
 left join ZooLogic.CONDPAGO as C_CONDICIONDEPAGO107 on C_CONDICIONDEPAGO107.CLCOD = C_PROVEEDOR84.CLCONDPAG and 0 = Funciones.empty( C_PROVEEDOR84.CLCONDPAG )
 left join ZooLogic.SIPRIBDATADIC as C_DATOSADICIONALESSIPRIB on C_DATOSADICIONALESSIPRIB.CODIGO = C_PROVEEDOR84.CLSIPRIB and 0 = Funciones.empty( C_PROVEEDOR84.CLSIPRIB )
 left join ZooLogic.IMPUESTO as C_IMPUESTO112 on C_IMPUESTO112.CODIGO = C_PROVEEDOR84.CLRETGAN and 0 = Funciones.empty( C_PROVEEDOR84.CLRETGAN )
 left join ZooLogic.IMPUESTO as C_IMPUESTO113 on C_IMPUESTO113.CODIGO = C_PROVEEDOR84.CLRETSUSS and 0 = Funciones.empty( C_PROVEEDOR84.CLRETSUSS )
 left join ZooLogic.IMPUESTO as C_IMPUESTO114 on C_IMPUESTO114.CODIGO = C_PROVEEDOR84.CLRETIVA and 0 = Funciones.empty( C_PROVEEDOR84.CLRETIVA )
 left join ZooLogic.LPRECIO as C_LISTADEPRECIOS110 on C_LISTADEPRECIOS110.LPR_NUMERO = C_PROVEEDOR84.CLLISTPRE and 0 = Funciones.empty( C_PROVEEDOR84.CLLISTPRE )
 left join ZooLogic.PAISES as C_PAISES on C_PAISES.PCOD = C_PROVEEDOR84.PPAIS and 0 = Funciones.empty( C_PROVEEDOR84.PPAIS )
 where ( not 1 = funciones.empty( c_itemarticulosremcompra.codigo ) and ( not 1 = funciones.empty( c_remitodecompra.codigo ) and c_remitodecompra.facttipo = 40 ) ) and 
	( ( @REMITODECOMPRA_1_MONEDACOMPROBANTE_DESDE is null ) OR ( C_REMITODECOMPRA.Moneda >= @REMITODECOMPRA_1_MONEDACOMPROBANTE_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_MONEDACOMPROBANTE_HASTA is null ) OR ( C_REMITODECOMPRA.Moneda <= @REMITODECOMPRA_1_MONEDACOMPROBANTE_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_ARTICULO_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FART >= @ITEMARTICULOSREMCOMPRA_ARTICULO_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_ARTICULO_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FART <= @ITEMARTICULOSREMCOMPRA_ARTICULO_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTOIVA_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FmtoIVA >= @ITEMARTICULOSREMCOMPRA_MONTOIVA_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTOIVA_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FmtoIVA <= @ITEMARTICULOSREMCOMPRA_MONTOIVA_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_PRECIOCONIMPUESTOS_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.prunconimp >= @ITEMARTICULOSREMCOMPRA_PRECIOCONIMPUESTOS_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_PRECIOCONIMPUESTOS_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.prunconimp <= @ITEMARTICULOSREMCOMPRA_PRECIOCONIMPUESTOS_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTODESCUENTOCONIMPUESTOS_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.MNDESCI >= @ITEMARTICULOSREMCOMPRA_MONTODESCUENTOCONIMPUESTOS_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTODESCUENTOCONIMPUESTOS_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.MNDESCI <= @ITEMARTICULOSREMCOMPRA_MONTODESCUENTOCONIMPUESTOS_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_BRUTO_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FBruto >= @ITEMARTICULOSREMCOMPRA_BRUTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_BRUTO_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FBruto <= @ITEMARTICULOSREMCOMPRA_BRUTO_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_ARTICULODETALLE_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FTXT >= @ITEMARTICULOSREMCOMPRA_ARTICULODETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_ARTICULODETALLE_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FTXT <= @ITEMARTICULOSREMCOMPRA_ARTICULODETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_COLOR_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCOLO >= @ITEMARTICULOSREMCOMPRA_COLOR_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_COLOR_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCOLO <= @ITEMARTICULOSREMCOMPRA_COLOR_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_COLORDETALLE_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCOTXT >= @ITEMARTICULOSREMCOMPRA_COLORDETALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_COLORDETALLE_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCOTXT <= @ITEMARTICULOSREMCOMPRA_COLORDETALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_TALLE_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FTALL >= @ITEMARTICULOSREMCOMPRA_TALLE_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_TALLE_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FTALL <= @ITEMARTICULOSREMCOMPRA_TALLE_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_CANTIDAD_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCANT >= @ITEMARTICULOSREMCOMPRA_CANTIDAD_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_CANTIDAD_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCANT <= @ITEMARTICULOSREMCOMPRA_CANTIDAD_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_PRECIO_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FPRECIO >= @ITEMARTICULOSREMCOMPRA_PRECIO_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_PRECIO_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FPRECIO <= @ITEMARTICULOSREMCOMPRA_PRECIO_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_DESCUENTO_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCFI >= @ITEMARTICULOSREMCOMPRA_DESCUENTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_DESCUENTO_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FCFI <= @ITEMARTICULOSREMCOMPRA_DESCUENTO_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTODESCUENTO_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.MNTDES >= @ITEMARTICULOSREMCOMPRA_MONTODESCUENTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTODESCUENTO_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.MNTDES <= @ITEMARTICULOSREMCOMPRA_MONTODESCUENTO_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTO_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FMONTO >= @ITEMARTICULOSREMCOMPRA_MONTO_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_MONTO_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.FMONTO <= @ITEMARTICULOSREMCOMPRA_MONTO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_CODIGO_DESDE is null ) OR ( C_REMITODECOMPRA.CODIGO >= @REMITODECOMPRA_1_CODIGO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_CODIGO_HASTA is null ) OR ( C_REMITODECOMPRA.CODIGO <= @REMITODECOMPRA_1_CODIGO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_LETRA_DESDE is null ) OR ( C_REMITODECOMPRA.FLETRA >= @REMITODECOMPRA_1_LETRA_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_LETRA_HASTA is null ) OR ( C_REMITODECOMPRA.FLETRA <= @REMITODECOMPRA_1_LETRA_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE is null ) OR ( C_REMITODECOMPRA.FPTOVENEXT >= @REMITODECOMPRA_1_PUNTODEVENTAEXTENDIDO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA is null ) OR ( C_REMITODECOMPRA.FPTOVENEXT <= @REMITODECOMPRA_1_PUNTODEVENTAEXTENDIDO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_NUMERO_DESDE is null ) OR ( C_REMITODECOMPRA.FNUMCOMP >= @REMITODECOMPRA_1_NUMERO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_NUMERO_HASTA is null ) OR ( C_REMITODECOMPRA.FNUMCOMP <= @REMITODECOMPRA_1_NUMERO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_PUNTODEVENTA_DESDE is null ) OR ( C_REMITODECOMPRA.FPTOVEN >= @REMITODECOMPRA_1_PUNTODEVENTA_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_PUNTODEVENTA_HASTA is null ) OR ( C_REMITODECOMPRA.FPTOVEN <= @REMITODECOMPRA_1_PUNTODEVENTA_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_PROVEEDOR_DESDE is null ) OR ( C_REMITODECOMPRA.FPerson >= @REMITODECOMPRA_1_PROVEEDOR_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_PROVEEDOR_HASTA is null ) OR ( C_REMITODECOMPRA.FPerson <= @REMITODECOMPRA_1_PROVEEDOR_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_LISTADEPRECIOS_DESDE is null ) OR ( C_REMITODECOMPRA.CodLista >= @REMITODECOMPRA_1_LISTADEPRECIOS_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_LISTADEPRECIOS_HASTA is null ) OR ( C_REMITODECOMPRA.CodLista <= @REMITODECOMPRA_1_LISTADEPRECIOS_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE is null ) OR ( C_REMITODECOMPRA.CONDPAGO >= @REMITODECOMPRA_1_CONDICIONPAGOPREFERENTE_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA is null ) OR ( C_REMITODECOMPRA.CONDPAGO <= @REMITODECOMPRA_1_CONDICIONPAGOPREFERENTE_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_MOTIVO_DESDE is null ) OR ( C_REMITODECOMPRA.MOTIVO >= @REMITODECOMPRA_1_MOTIVO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_MOTIVO_HASTA is null ) OR ( C_REMITODECOMPRA.MOTIVO <= @REMITODECOMPRA_1_MOTIVO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_TRANSPORTISTA_DESDE is null ) OR ( C_REMITODECOMPRA.FTransp >= @REMITODECOMPRA_1_TRANSPORTISTA_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_TRANSPORTISTA_HASTA is null ) OR ( C_REMITODECOMPRA.FTransp <= @REMITODECOMPRA_1_TRANSPORTISTA_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_NUMINT_DESDE is null ) OR ( C_REMITODECOMPRA.NumInt >= @REMITODECOMPRA_1_NUMINT_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_NUMINT_HASTA is null ) OR ( C_REMITODECOMPRA.NumInt <= @REMITODECOMPRA_1_NUMINT_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_FECHA_DESDE is null ) OR ( C_REMITODECOMPRA.FFCH >= @REMITODECOMPRA_1_FECHA_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_FECHA_HASTA is null ) OR ( C_REMITODECOMPRA.FFCH <= @REMITODECOMPRA_1_FECHA_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_COTIZACION_DESDE is null ) OR ( C_REMITODECOMPRA.Cotiz >= @REMITODECOMPRA_1_COTIZACION_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_COTIZACION_HASTA is null ) OR ( C_REMITODECOMPRA.Cotiz <= @REMITODECOMPRA_1_COTIZACION_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE is null ) OR ( C_REMITODECOMPRA.FPODES >= @REMITODECOMPRA_1_PORCENTAJEDESCUENTO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA is null ) OR ( C_REMITODECOMPRA.FPODES <= @REMITODECOMPRA_1_PORCENTAJEDESCUENTO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_DESCUENTO_DESDE is null ) OR ( C_REMITODECOMPRA.fDescu >= @REMITODECOMPRA_1_DESCUENTO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_DESCUENTO_HASTA is null ) OR ( C_REMITODECOMPRA.fDescu <= @REMITODECOMPRA_1_DESCUENTO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE is null ) OR ( C_REMITODECOMPRA.FMTDES3 >= @REMITODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA is null ) OR ( C_REMITODECOMPRA.FMTDES3 <= @REMITODECOMPRA_1_MONTODESCUENTOCONIMPUESTOS3_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_RECARGOPORCENTAJE_DESDE is null ) OR ( C_REMITODECOMPRA.RecPor >= @REMITODECOMPRA_1_RECARGOPORCENTAJE_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_RECARGOPORCENTAJE_HASTA is null ) OR ( C_REMITODECOMPRA.RecPor <= @REMITODECOMPRA_1_RECARGOPORCENTAJE_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_RECARGOMONTO_DESDE is null ) OR ( C_REMITODECOMPRA.MR >= @REMITODECOMPRA_1_RECARGOMONTO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_RECARGOMONTO_HASTA is null ) OR ( C_REMITODECOMPRA.MR <= @REMITODECOMPRA_1_RECARGOMONTO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_RECARGOMONTO2_DESDE is null ) OR ( C_REMITODECOMPRA.RecMonto2 >= @REMITODECOMPRA_1_RECARGOMONTO2_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_RECARGOMONTO2_HASTA is null ) OR ( C_REMITODECOMPRA.RecMonto2 <= @REMITODECOMPRA_1_RECARGOMONTO2_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_IMPUESTOS_DESDE is null ) OR ( C_REMITODECOMPRA.fImpuesto >= @REMITODECOMPRA_1_IMPUESTOS_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_IMPUESTOS_HASTA is null ) OR ( C_REMITODECOMPRA.fImpuesto <= @REMITODECOMPRA_1_IMPUESTOS_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_TOTALIMPUESTOS_DESDE is null ) OR ( C_REMITODECOMPRA.totimpue >= @REMITODECOMPRA_1_TOTALIMPUESTOS_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_TOTALIMPUESTOS_HASTA is null ) OR ( C_REMITODECOMPRA.totimpue <= @REMITODECOMPRA_1_TOTALIMPUESTOS_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_TOTAL_DESDE is null ) OR ( C_REMITODECOMPRA.FTotal >= @REMITODECOMPRA_1_TOTAL_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_TOTAL_HASTA is null ) OR ( C_REMITODECOMPRA.FTotal <= @REMITODECOMPRA_1_TOTAL_HASTA ) ) and 
	( ( @PROVEEDOR_84_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR84.CLNOM >= @PROVEEDOR_84_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_84_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR84.CLNOM <= @PROVEEDOR_84_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @LISTADEPRECIOS_128_LISTADEPRECIOS_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS128.LPR_NOMBRE >= @LISTADEPRECIOS_128_LISTADEPRECIOS_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_128_LISTADEPRECIOS_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS128.LPR_NOMBRE <= @LISTADEPRECIOS_128_LISTADEPRECIOS_NOMBRE_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_129_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO129.CLNOM >= @CONDICIONDEPAGO_129_CONDICIONPAGOPREFERENTE_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_129_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO129.CLNOM <= @CONDICIONDEPAGO_129_CONDICIONPAGOPREFERENTE_DESCRIPCION_HASTA ) ) and 
	( ( @MOTIVO_130_MOTIVO_DESCRIPCION_DESDE is null ) OR ( C_MOTIVO.MOTDES >= @MOTIVO_130_MOTIVO_DESCRIPCION_DESDE ) ) and 
	( ( @MOTIVO_130_MOTIVO_DESCRIPCION_HASTA is null ) OR ( C_MOTIVO.MOTDES <= @MOTIVO_130_MOTIVO_DESCRIPCION_HASTA ) ) and 
	( ( @TRANSPORTISTA_131_TRANSPORTISTA_NOMBRE_DESDE is null ) OR ( C_TRANSPORTISTA.TRNOM >= @TRANSPORTISTA_131_TRANSPORTISTA_NOMBRE_DESDE ) ) and 
	( ( @TRANSPORTISTA_131_TRANSPORTISTA_NOMBRE_HASTA is null ) OR ( C_TRANSPORTISTA.TRNOM <= @TRANSPORTISTA_131_TRANSPORTISTA_NOMBRE_HASTA ) ) and 
	( ( @SEGMENTACION_9142_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_9142_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_9142_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_9142_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_9141_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_9141_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_9141_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_9141_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_9140_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_9140_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_9140_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_9140_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR3.CLNOM >= @PROVEEDOR_3_PROVEEDOR_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR3.CLNOM <= @PROVEEDOR_3_PROVEEDOR_NOMBRE_HASTA ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_9_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_9_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_10_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_11_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_11_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_12_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_12_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_13_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_13_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_13_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_14_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_14_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_14_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_15_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_16_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_18_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE is null ) OR ( C_PALETADECOLORES.Descrip >= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_DESDE ) ) and 
	( ( @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA is null ) OR ( C_PALETADECOLORES.Descrip <= @PALETADECOLORES_22_PALETADECOLORES_DESCRIPCION_HASTA ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE is null ) OR ( C_CURVADETALLES.Descrip >= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_DESDE ) ) and 
	( ( @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA is null ) OR ( C_CURVADETALLES.Descrip <= @CURVADETALLES_23_CURVADETALLES_DESCRIPCION_HASTA ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE is null ) OR ( C_NOMENCLADORARBA.NMCDES >= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_DESDE ) ) and 
	( ( @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA is null ) OR ( C_NOMENCLADORARBA.NMCDES <= @NOMENCLADORARBA_25_NOMENCLADOR_DESCRIPCION_HASTA ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_DESDE is null ) OR ( C_MARCA.Descrip >= @MARCA_42_MARCA_DESCRIPCION_DESDE ) ) and 
	( ( @MARCA_42_MARCA_DESCRIPCION_HASTA is null ) OR ( C_MARCA.Descrip <= @MARCA_42_MARCA_DESCRIPCION_HASTA ) ) and 
	( ( @PROVINCIA_87_PROVINCIA_DESCRIPCION_DESDE is null ) OR ( C_PROVINCIA.PRV_DES >= @PROVINCIA_87_PROVINCIA_DESCRIPCION_DESDE ) ) and 
	( ( @PROVINCIA_87_PROVINCIA_DESCRIPCION_HASTA is null ) OR ( C_PROVINCIA.PRV_DES <= @PROVINCIA_87_PROVINCIA_DESCRIPCION_HASTA ) ) and 
	( ( @PAISES_103_PAIS_DESCRIPCION_DESDE is null ) OR ( C_PAISES.pdes >= @PAISES_103_PAIS_DESCRIPCION_DESDE ) ) and 
	( ( @PAISES_103_PAIS_DESCRIPCION_HASTA is null ) OR ( C_PAISES.pdes <= @PAISES_103_PAIS_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_105_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES >= @CLASIFICACIONPROVEEDOR_105_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONPROVEEDOR_105_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONPROVEEDOR.CLADES <= @CLASIFICACIONPROVEEDOR_105_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @CONDICIONDEPAGO_107_CONDICIONDEPAGO_DESCRIPCION_DESDE is null ) OR ( C_CONDICIONDEPAGO107.CLNOM >= @CONDICIONDEPAGO_107_CONDICIONDEPAGO_DESCRIPCION_DESDE ) ) and 
	( ( @CONDICIONDEPAGO_107_CONDICIONDEPAGO_DESCRIPCION_HASTA is null ) OR ( C_CONDICIONDEPAGO107.CLNOM <= @CONDICIONDEPAGO_107_CONDICIONDEPAGO_DESCRIPCION_HASTA ) ) and 
	( ( @LISTADEPRECIOS_110_LISTADEPRECIO_NOMBRE_DESDE is null ) OR ( C_LISTADEPRECIOS110.LPR_NOMBRE >= @LISTADEPRECIOS_110_LISTADEPRECIO_NOMBRE_DESDE ) ) and 
	( ( @LISTADEPRECIOS_110_LISTADEPRECIO_NOMBRE_HASTA is null ) OR ( C_LISTADEPRECIOS110.LPR_NOMBRE <= @LISTADEPRECIOS_110_LISTADEPRECIO_NOMBRE_HASTA ) ) and 
	( ( @IMPUESTO_112_RETENCIONGANANCIAS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO112.descrip >= @IMPUESTO_112_RETENCIONGANANCIAS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_112_RETENCIONGANANCIAS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO112.descrip <= @IMPUESTO_112_RETENCIONGANANCIAS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_113_RETENCIONSUSS_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO113.descrip >= @IMPUESTO_113_RETENCIONSUSS_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_113_RETENCIONSUSS_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO113.descrip <= @IMPUESTO_113_RETENCIONSUSS_DESCRIPCION_HASTA ) ) and 
	( ( @IMPUESTO_114_RETENCIONIVA_DESCRIPCION_DESDE is null ) OR ( C_IMPUESTO114.descrip >= @IMPUESTO_114_RETENCIONIVA_DESCRIPCION_DESDE ) ) and 
	( ( @IMPUESTO_114_RETENCIONIVA_DESCRIPCION_HASTA is null ) OR ( C_IMPUESTO114.descrip <= @IMPUESTO_114_RETENCIONIVA_DESCRIPCION_HASTA ) ) and 
	( ( @DATOSADICIONALESSIPRIB_123_CODIGOSIPRIB_DESCRIPCION_DESDE is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip >= @DATOSADICIONALESSIPRIB_123_CODIGOSIPRIB_DESCRIPCION_DESDE ) ) and 
	( ( @DATOSADICIONALESSIPRIB_123_CODIGOSIPRIB_DESCRIPCION_HASTA is null ) OR ( C_DATOSADICIONALESSIPRIB.Descrip <= @DATOSADICIONALESSIPRIB_123_CODIGOSIPRIB_DESCRIPCION_HASTA ) ) and 
	( ( @MONEDA_9003_MONEDACOMPROBANTE_DESCRIPCION_DESDE is null ) OR ( C_MONEDA.Descrip >= @MONEDA_9003_MONEDACOMPROBANTE_DESCRIPCION_DESDE ) ) and 
	( ( @MONEDA_9003_MONEDACOMPROBANTE_DESCRIPCION_HASTA is null ) OR ( C_MONEDA.Descrip <= @MONEDA_9003_MONEDACOMPROBANTE_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_9137_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_9137_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_9137_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_9137_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_9137_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_9137_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_9137_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_9137_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_9137_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_9137_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_9137_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_9137_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_9137_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_9137_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_9137_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_9137_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_2_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_2_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_2_PROVEEDOR_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVAVENTAS is null ) OR ( C_ARTICULO.ARTCONIVA = @ARTICULO_2_CONDICIONIVAVENTAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE is null ) OR ( C_ARTICULO.ARTPORIVA >= @ARTICULO_2_PORCENTAJEIVAVENTAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA is null ) OR ( C_ARTICULO.ARTPORIVA <= @ARTICULO_2_PORCENTAJEIVAVENTAS_HASTA ) ) and 
	( ( @ARTICULO_2_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_2_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_2_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_2_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_2_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_2_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_2_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_2_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_2_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_2_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_2_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_2_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_2_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_2_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_2_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_2_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_2_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_2_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_2_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_2_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_2_LINEA_DESDE ) ) and 
	( ( @ARTICULO_2_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_2_LINEA_HASTA ) ) and 
	( ( @ARTICULO_2_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_2_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_2_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_2_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_2_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_2_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_2_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_2_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_2_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_2_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_2_ANO_DESDE ) ) and 
	( ( @ARTICULO_2_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_2_ANO_HASTA ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_2_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_2_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_CONDICIONIVACOMPRAS is null ) OR ( C_ARTICULO.ARTIVA = @ARTICULO_2_CONDICIONIVACOMPRAS ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE is null ) OR ( C_ARTICULO.ANX2 >= @ARTICULO_2_PORCENTAJEIVACOMPRAS_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA is null ) OR ( C_ARTICULO.ANX2 <= @ARTICULO_2_PORCENTAJEIVACOMPRAS_HASTA ) ) and 
	( ( @ARTICULO_2_COMPORTAMIENTO is null ) OR ( C_ARTICULO.ASTOCK = @ARTICULO_2_COMPORTAMIENTO ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_DESDE is null ) OR ( C_ARTICULO.PalCol >= @ARTICULO_2_PALETADECOLORES_DESDE ) ) and 
	( ( @ARTICULO_2_PALETADECOLORES_HASTA is null ) OR ( C_ARTICULO.PalCol <= @ARTICULO_2_PALETADECOLORES_HASTA ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_DESDE is null ) OR ( C_ARTICULO.Curtall >= @ARTICULO_2_CURVADETALLES_DESDE ) ) and 
	( ( @ARTICULO_2_CURVADETALLES_HASTA is null ) OR ( C_ARTICULO.Curtall <= @ARTICULO_2_CURVADETALLES_HASTA ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_DESDE is null ) OR ( C_ARTICULO.NOCOM >= @ARTICULO_2_NOCOMERCIALIZABLE_DESDE ) ) and 
	( ( @ARTICULO_2_NOCOMERCIALIZABLE_HASTA is null ) OR ( C_ARTICULO.NOCOM <= @ARTICULO_2_NOCOMERCIALIZABLE_HASTA ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_DESDE is null ) OR ( C_ARTICULO.ARTNARBA >= @ARTICULO_2_NOMENCLADOR_DESDE ) ) and 
	( ( @ARTICULO_2_NOMENCLADOR_HASTA is null ) OR ( C_ARTICULO.ARTNARBA <= @ARTICULO_2_NOMENCLADOR_HASTA ) ) and 
	( ( @ARTICULO_2_NOPERMITEDEVOLUCIONES is null ) OR ( C_ARTICULO.ARTNODEVO = @ARTICULO_2_NOPERMITEDEVOLUCIONES ) ) and 
	( ( @ARTICULO_2_IMPRIMEDESPACHO is null ) OR ( C_ARTICULO.EsImpDes = @ARTICULO_2_IMPRIMEDESPACHO ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE is null ) OR ( C_ARTICULO.impinterno >= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_DESDE ) ) and 
	( ( @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA is null ) OR ( C_ARTICULO.impinterno <= @ARTICULO_2_PORCENTAJEIMPUESTOINTERNO_HASTA ) ) and 
	( ( @ARTICULO_2_RESTRINGIRDESCUENTOS is null ) OR ( C_ARTICULO.ArtSinDes = @ARTICULO_2_RESTRINGIRDESCUENTOS ) ) and 
	( ( @ARTICULO_2_PESO_DESDE is null ) OR ( C_ARTICULO.ARTPESO >= @ARTICULO_2_PESO_DESDE ) ) and 
	( ( @ARTICULO_2_PESO_HASTA is null ) OR ( C_ARTICULO.ARTPESO <= @ARTICULO_2_PESO_HASTA ) ) and 
	( ( @ARTICULO_2_LARGO_DESDE is null ) OR ( C_ARTICULO.ARTLARGO >= @ARTICULO_2_LARGO_DESDE ) ) and 
	( ( @ARTICULO_2_LARGO_HASTA is null ) OR ( C_ARTICULO.ARTLARGO <= @ARTICULO_2_LARGO_HASTA ) ) and 
	( ( @ARTICULO_2_ANCHO_DESDE is null ) OR ( C_ARTICULO.ARTANCHO >= @ARTICULO_2_ANCHO_DESDE ) ) and 
	( ( @ARTICULO_2_ANCHO_HASTA is null ) OR ( C_ARTICULO.ARTANCHO <= @ARTICULO_2_ANCHO_HASTA ) ) and 
	( ( @ARTICULO_2_ALTO_DESDE is null ) OR ( C_ARTICULO.ARTALTO >= @ARTICULO_2_ALTO_DESDE ) ) and 
	( ( @ARTICULO_2_ALTO_HASTA is null ) OR ( C_ARTICULO.ARTALTO <= @ARTICULO_2_ALTO_HASTA ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_DESDE is null ) OR ( C_ARTICULO.ReqCCosto >= @ARTICULO_2_REQUIERECCOSTO_DESDE ) ) and 
	( ( @ARTICULO_2_REQUIERECCOSTO_HASTA is null ) OR ( C_ARTICULO.ReqCCosto <= @ARTICULO_2_REQUIERECCOSTO_HASTA ) ) and 
	( ( @ARTICULO_2_NOPUBLICARENECOMMERCE is null ) OR ( C_ARTICULO.PubEcom = @ARTICULO_2_NOPUBLICARENECOMMERCE ) ) and 
	( ( @ARTICULO_2_IMPORTADO is null ) OR ( C_ARTICULO.Importado = @ARTICULO_2_IMPORTADO ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE is null ) OR ( C_ARTICULO.ARTDESADIC >= @ARTICULO_2_DESCRIPCIONADICIONAL_DESDE ) ) and 
	( ( @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA is null ) OR ( C_ARTICULO.ARTDESADIC <= @ARTICULO_2_DESCRIPCIONADICIONAL_HASTA ) ) and 
	( ( @ARTICULO_2_SOLOPROMOYKIT is null ) OR ( C_ARTICULO.PromoYKit = @ARTICULO_2_SOLOPROMOYKIT ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_DESDE is null ) OR ( C_ARTICULO.ArtRest >= @ARTICULO_2_RESTRINGIRARTICULO_DESDE ) ) and 
	( ( @ARTICULO_2_RESTRINGIRARTICULO_HASTA is null ) OR ( C_ARTICULO.ArtRest <= @ARTICULO_2_RESTRINGIRARTICULO_HASTA ) ) and 
	( ( @ARTICULO_2_MARCA_DESDE is null ) OR ( C_ARTICULO.Marca >= @ARTICULO_2_MARCA_DESDE ) ) and 
	( ( @ARTICULO_2_MARCA_HASTA is null ) OR ( C_ARTICULO.Marca <= @ARTICULO_2_MARCA_HASTA ) ) and 
	( ( @ARTICULO_2_PERCEPCIONIVARG5329 is null ) OR ( C_ARTICULO.ArtPercep = @ARTICULO_2_PERCEPCIONIVARG5329 ) ) and 
	( ( @PROVEEDOR_84_LOCALIDAD_DESDE is null ) OR ( C_PROVEEDOR84.CLLOC >= @PROVEEDOR_84_LOCALIDAD_DESDE ) ) and 
	( ( @PROVEEDOR_84_LOCALIDAD_HASTA is null ) OR ( C_PROVEEDOR84.CLLOC <= @PROVEEDOR_84_LOCALIDAD_HASTA ) ) and 
	( ( @PROVEEDOR_84_CODIGOPOSTAL_DESDE is null ) OR ( C_PROVEEDOR84.CLCP >= @PROVEEDOR_84_CODIGOPOSTAL_DESDE ) ) and 
	( ( @PROVEEDOR_84_CODIGOPOSTAL_HASTA is null ) OR ( C_PROVEEDOR84.CLCP <= @PROVEEDOR_84_CODIGOPOSTAL_HASTA ) ) and 
	( ( @PROVEEDOR_84_PROVINCIA_DESDE is null ) OR ( C_PROVEEDOR84.CLPRV >= @PROVEEDOR_84_PROVINCIA_DESDE ) ) and 
	( ( @PROVEEDOR_84_PROVINCIA_HASTA is null ) OR ( C_PROVEEDOR84.CLPRV <= @PROVEEDOR_84_PROVINCIA_HASTA ) ) and 
	( ( @PROVEEDOR_84_TELEFONO_DESDE is null ) OR ( C_PROVEEDOR84.CLTLF >= @PROVEEDOR_84_TELEFONO_DESDE ) ) and 
	( ( @PROVEEDOR_84_TELEFONO_HASTA is null ) OR ( C_PROVEEDOR84.CLTLF <= @PROVEEDOR_84_TELEFONO_HASTA ) ) and 
	( ( @PROVEEDOR_84_FAX_DESDE is null ) OR ( C_PROVEEDOR84.CLFAX >= @PROVEEDOR_84_FAX_DESDE ) ) and 
	( ( @PROVEEDOR_84_FAX_HASTA is null ) OR ( C_PROVEEDOR84.CLFAX <= @PROVEEDOR_84_FAX_HASTA ) ) and 
	( ( @PROVEEDOR_84_EMAIL_DESDE is null ) OR ( C_PROVEEDOR84.CLEMAIL >= @PROVEEDOR_84_EMAIL_DESDE ) ) and 
	( ( @PROVEEDOR_84_EMAIL_HASTA is null ) OR ( C_PROVEEDOR84.CLEMAIL <= @PROVEEDOR_84_EMAIL_HASTA ) ) and 
	( ( @PROVEEDOR_84_PAGINAWEB_DESDE is null ) OR ( C_PROVEEDOR84.CLPAGEWEB >= @PROVEEDOR_84_PAGINAWEB_DESDE ) ) and 
	( ( @PROVEEDOR_84_PAGINAWEB_HASTA is null ) OR ( C_PROVEEDOR84.CLPAGEWEB <= @PROVEEDOR_84_PAGINAWEB_HASTA ) ) and 
	( ( @SITUACIONFISCAL_92_SITUACIONFISCAL_DESCRIPCION is null ) OR ( C_SITUACIONFISCAL.Descrip = @SITUACIONFISCAL_92_SITUACIONFISCAL_DESCRIPCION ) ) and 
	( ( @PROVEEDOR_84_CUIT_DESDE is null ) OR ( C_PROVEEDOR84.CLCUIT >= @PROVEEDOR_84_CUIT_DESDE ) ) and 
	( ( @PROVEEDOR_84_CUIT_HASTA is null ) OR ( C_PROVEEDOR84.CLCUIT <= @PROVEEDOR_84_CUIT_HASTA ) ) and 
	( ( @PROVEEDOR_84_TIPODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR84.CLTIPODOC >= @PROVEEDOR_84_TIPODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_84_TIPODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR84.CLTIPODOC <= @PROVEEDOR_84_TIPODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_84_NRODOCUMENTO_DESDE is null ) OR ( C_PROVEEDOR84.CLNRODOC >= @PROVEEDOR_84_NRODOCUMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_84_NRODOCUMENTO_HASTA is null ) OR ( C_PROVEEDOR84.CLNRODOC <= @PROVEEDOR_84_NRODOCUMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_84_IMAGEN_DESDE is null ) OR ( C_PROVEEDOR84.CIMAGEN >= @PROVEEDOR_84_IMAGEN_DESDE ) ) and 
	( ( @PROVEEDOR_84_IMAGEN_HASTA is null ) OR ( C_PROVEEDOR84.CIMAGEN <= @PROVEEDOR_84_IMAGEN_HASTA ) ) and 
	( ( @PROVEEDOR_84_NUMERO_DESDE is null ) OR ( C_PROVEEDOR84.PNUMERO >= @PROVEEDOR_84_NUMERO_DESDE ) ) and 
	( ( @PROVEEDOR_84_NUMERO_HASTA is null ) OR ( C_PROVEEDOR84.PNUMERO <= @PROVEEDOR_84_NUMERO_HASTA ) ) and 
	( ( @PROVEEDOR_84_CALLE_DESDE is null ) OR ( C_PROVEEDOR84.PCALLE >= @PROVEEDOR_84_CALLE_DESDE ) ) and 
	( ( @PROVEEDOR_84_CALLE_HASTA is null ) OR ( C_PROVEEDOR84.PCALLE <= @PROVEEDOR_84_CALLE_HASTA ) ) and 
	( ( @PROVEEDOR_84_PISO_DESDE is null ) OR ( C_PROVEEDOR84.PPISO >= @PROVEEDOR_84_PISO_DESDE ) ) and 
	( ( @PROVEEDOR_84_PISO_HASTA is null ) OR ( C_PROVEEDOR84.PPISO <= @PROVEEDOR_84_PISO_HASTA ) ) and 
	( ( @PROVEEDOR_84_DEPARTAMENTO_DESDE is null ) OR ( C_PROVEEDOR84.PDEPTO >= @PROVEEDOR_84_DEPARTAMENTO_DESDE ) ) and 
	( ( @PROVEEDOR_84_DEPARTAMENTO_HASTA is null ) OR ( C_PROVEEDOR84.PDEPTO <= @PROVEEDOR_84_DEPARTAMENTO_HASTA ) ) and 
	( ( @PROVEEDOR_84_PAIS_DESDE is null ) OR ( C_PROVEEDOR84.PPAIS >= @PROVEEDOR_84_PAIS_DESDE ) ) and 
	( ( @PROVEEDOR_84_PAIS_HASTA is null ) OR ( C_PROVEEDOR84.PPAIS <= @PROVEEDOR_84_PAIS_HASTA ) ) and 
	( ( @PROVEEDOR_84_MOVIL_DESDE is null ) OR ( C_PROVEEDOR84.TLFM >= @PROVEEDOR_84_MOVIL_DESDE ) ) and 
	( ( @PROVEEDOR_84_MOVIL_HASTA is null ) OR ( C_PROVEEDOR84.TLFM <= @PROVEEDOR_84_MOVIL_HASTA ) ) and 
	( ( @PROVEEDOR_84_CLASIFICACION_DESDE is null ) OR ( C_PROVEEDOR84.CLAS >= @PROVEEDOR_84_CLASIFICACION_DESDE ) ) and 
	( ( @PROVEEDOR_84_CLASIFICACION_HASTA is null ) OR ( C_PROVEEDOR84.CLAS <= @PROVEEDOR_84_CLASIFICACION_HASTA ) ) and 
	( ( @PROVEEDOR_84_FECHANACIMIENTO_DESDE is null ) OR ( C_PROVEEDOR84.CLFECHA >= @PROVEEDOR_84_FECHANACIMIENTO_DESDE ) ) and 
	( ( @PROVEEDOR_84_FECHANACIMIENTO_HASTA is null ) OR ( C_PROVEEDOR84.CLFECHA <= @PROVEEDOR_84_FECHANACIMIENTO_HASTA ) ) and 
	( ( @PROVEEDOR_84_CONDICIONDEPAGO_DESDE is null ) OR ( C_PROVEEDOR84.CLCONDPAG >= @PROVEEDOR_84_CONDICIONDEPAGO_DESDE ) ) and 
	( ( @PROVEEDOR_84_CONDICIONDEPAGO_HASTA is null ) OR ( C_PROVEEDOR84.CLCONDPAG <= @PROVEEDOR_84_CONDICIONDEPAGO_HASTA ) ) and 
	( ( @PROVEEDOR_84_TIPOCONVENIO_DESDE is null ) OR ( C_PROVEEDOR84.CLTIPCONV >= @PROVEEDOR_84_TIPOCONVENIO_DESDE ) ) and 
	( ( @PROVEEDOR_84_TIPOCONVENIO_HASTA is null ) OR ( C_PROVEEDOR84.CLTIPCONV <= @PROVEEDOR_84_TIPOCONVENIO_HASTA ) ) and 
	( ( @PROVEEDOR_84_NROIIBB_DESDE is null ) OR ( C_PROVEEDOR84.CLNROIIBB >= @PROVEEDOR_84_NROIIBB_DESDE ) ) and 
	( ( @PROVEEDOR_84_NROIIBB_HASTA is null ) OR ( C_PROVEEDOR84.CLNROIIBB <= @PROVEEDOR_84_NROIIBB_HASTA ) ) and 
	( ( @PROVEEDOR_84_LISTADEPRECIO_DESDE is null ) OR ( C_PROVEEDOR84.CLLISTPRE >= @PROVEEDOR_84_LISTADEPRECIO_DESDE ) ) and 
	( ( @PROVEEDOR_84_LISTADEPRECIO_HASTA is null ) OR ( C_PROVEEDOR84.CLLISTPRE <= @PROVEEDOR_84_LISTADEPRECIO_HASTA ) ) and 
	( ( @PROVEEDOR_84_SITUACIONGANANCIAS is null ) OR ( C_PROVEEDOR84.CLSITGAN = @PROVEEDOR_84_SITUACIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_84_RETENCIONGANANCIAS_DESDE is null ) OR ( C_PROVEEDOR84.CLRETGAN >= @PROVEEDOR_84_RETENCIONGANANCIAS_DESDE ) ) and 
	( ( @PROVEEDOR_84_RETENCIONGANANCIAS_HASTA is null ) OR ( C_PROVEEDOR84.CLRETGAN <= @PROVEEDOR_84_RETENCIONGANANCIAS_HASTA ) ) and 
	( ( @PROVEEDOR_84_RETENCIONSUSS_DESDE is null ) OR ( C_PROVEEDOR84.CLRETSUSS >= @PROVEEDOR_84_RETENCIONSUSS_DESDE ) ) and 
	( ( @PROVEEDOR_84_RETENCIONSUSS_HASTA is null ) OR ( C_PROVEEDOR84.CLRETSUSS <= @PROVEEDOR_84_RETENCIONSUSS_HASTA ) ) and 
	( ( @PROVEEDOR_84_RETENCIONIVA_DESDE is null ) OR ( C_PROVEEDOR84.CLRETIVA >= @PROVEEDOR_84_RETENCIONIVA_DESDE ) ) and 
	( ( @PROVEEDOR_84_RETENCIONIVA_HASTA is null ) OR ( C_PROVEEDOR84.CLRETIVA <= @PROVEEDOR_84_RETENCIONIVA_HASTA ) ) and 
	( ( @PROVEEDOR_84_OBJETOIVA is null ) OR ( C_PROVEEDOR84.CLOBJIVA = @PROVEEDOR_84_OBJETOIVA ) ) and 
	( ( @PROVEEDOR_84_EMPLEADOR is null ) OR ( C_PROVEEDOR84.CLEMPLEAD = @PROVEEDOR_84_EMPLEADOR ) ) and 
	( ( @PROVEEDOR_84_EXCLUIDORETENCIONGANANCIAS is null ) OR ( C_PROVEEDOR84.EXRETGAN = @PROVEEDOR_84_EXCLUIDORETENCIONGANANCIAS ) ) and 
	( ( @PROVEEDOR_84_EXCLUIDORETENCIONIVA is null ) OR ( C_PROVEEDOR84.EXRETIVA = @PROVEEDOR_84_EXCLUIDORETENCIONIVA ) ) and 
	( ( @PROVEEDOR_84_EXCLUIDORETENCIONSUSS is null ) OR ( C_PROVEEDOR84.EXRETSUSS = @PROVEEDOR_84_EXCLUIDORETENCIONSUSS ) ) and 
	( ( @PROVEEDOR_84_SUJETOVINCULADO is null ) OR ( C_PROVEEDOR84.CLSujVinc = @PROVEEDOR_84_SUJETOVINCULADO ) ) and 
	( ( @PROVEEDOR_84_VIGENCIAHASTAIVA_DESDE is null ) OR ( C_PROVEEDOR84.PVHastaIva >= @PROVEEDOR_84_VIGENCIAHASTAIVA_DESDE ) ) and 
	( ( @PROVEEDOR_84_VIGENCIAHASTAIVA_HASTA is null ) OR ( C_PROVEEDOR84.PVHastaIva <= @PROVEEDOR_84_VIGENCIAHASTAIVA_HASTA ) ) and 
	( ( @PROVEEDOR_84_VIGENCIAHASTAGAN_DESDE is null ) OR ( C_PROVEEDOR84.PVHastaGan >= @PROVEEDOR_84_VIGENCIAHASTAGAN_DESDE ) ) and 
	( ( @PROVEEDOR_84_VIGENCIAHASTAGAN_HASTA is null ) OR ( C_PROVEEDOR84.PVHastaGan <= @PROVEEDOR_84_VIGENCIAHASTAGAN_HASTA ) ) and 
	( ( @PROVEEDOR_84_CODIGOSIPRIB_DESDE is null ) OR ( C_PROVEEDOR84.CLSIPRIB >= @PROVEEDOR_84_CODIGOSIPRIB_DESDE ) ) and 
	( ( @PROVEEDOR_84_CODIGOSIPRIB_HASTA is null ) OR ( C_PROVEEDOR84.CLSIPRIB <= @PROVEEDOR_84_CODIGOSIPRIB_HASTA ) ) and 
	( ( @PROVEEDOR_84_TASACEROPORCEN_DESDE is null ) OR ( C_PROVEEDOR84.PorcenTC >= @PROVEEDOR_84_TASACEROPORCEN_DESDE ) ) and 
	( ( @PROVEEDOR_84_TASACEROPORCEN_HASTA is null ) OR ( C_PROVEEDOR84.PorcenTC <= @PROVEEDOR_84_TASACEROPORCEN_HASTA ) ) and 
	( ( @PROVEEDOR_84_TASACEROAPLICA is null ) OR ( C_PROVEEDOR84.AplicaTC = @PROVEEDOR_84_TASACEROAPLICA ) ) and 
	( ( @PROVEEDOR_84_RUT_DESDE is null ) OR ( C_PROVEEDOR84.RUT >= @PROVEEDOR_84_RUT_DESDE ) ) and 
	( ( @PROVEEDOR_84_RUT_HASTA is null ) OR ( C_PROVEEDOR84.RUT <= @PROVEEDOR_84_RUT_HASTA ) ) and 
	( ( @PROVEEDOR_84_INACTIVOFW is null ) OR ( C_PROVEEDOR84.InactivoFW = @PROVEEDOR_84_INACTIVOFW ) ) and 
	( ( @SUCURSAL_9137_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_9137_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_9137_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_9137_CODIGO_HASTA ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_NROITEM_DESDE is null ) OR ( c_ITEMARTICULOSREMCOMPRA.NroItem >= @ITEMARTICULOSREMCOMPRA_NROITEM_DESDE ) ) and 
	( ( @ITEMARTICULOSREMCOMPRA_NROITEM_HASTA is null ) OR ( c_ITEMARTICULOSREMCOMPRA.NroItem <= @ITEMARTICULOSREMCOMPRA_NROITEM_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_BASEDEDATOSALTAFW_DESDE is null ) OR ( C_REMITODECOMPRA.BDALTAFW >= @REMITODECOMPRA_1_BASEDEDATOSALTAFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_BASEDEDATOSALTAFW_HASTA is null ) OR ( C_REMITODECOMPRA.BDALTAFW <= @REMITODECOMPRA_1_BASEDEDATOSALTAFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE is null ) OR ( C_REMITODECOMPRA.BDMODIFW >= @REMITODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA is null ) OR ( C_REMITODECOMPRA.BDMODIFW <= @REMITODECOMPRA_1_BASEDEDATOSMODIFICACIONFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE is null ) OR ( C_REMITODECOMPRA.ESTTRANS >= @REMITODECOMPRA_1_ESTADOTRANSFERENCIA_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA is null ) OR ( C_REMITODECOMPRA.ESTTRANS <= @REMITODECOMPRA_1_ESTADOTRANSFERENCIA_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_FECHAALTAFW_DESDE is null ) OR ( C_REMITODECOMPRA.FALTAFW >= @REMITODECOMPRA_1_FECHAALTAFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_FECHAALTAFW_HASTA is null ) OR ( C_REMITODECOMPRA.FALTAFW <= @REMITODECOMPRA_1_FECHAALTAFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_FECHAEXPO_DESDE is null ) OR ( C_REMITODECOMPRA.FECEXPO >= @REMITODECOMPRA_1_FECHAEXPO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_FECHAEXPO_HASTA is null ) OR ( C_REMITODECOMPRA.FECEXPO <= @REMITODECOMPRA_1_FECHAEXPO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_FECHAIMPO_DESDE is null ) OR ( C_REMITODECOMPRA.FECIMPO >= @REMITODECOMPRA_1_FECHAIMPO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_FECHAIMPO_HASTA is null ) OR ( C_REMITODECOMPRA.FECIMPO <= @REMITODECOMPRA_1_FECHAIMPO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_FECHAMODIFICACIONFW_DESDE is null ) OR ( C_REMITODECOMPRA.FMODIFW >= @REMITODECOMPRA_1_FECHAMODIFICACIONFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_FECHAMODIFICACIONFW_HASTA is null ) OR ( C_REMITODECOMPRA.FMODIFW <= @REMITODECOMPRA_1_FECHAMODIFICACIONFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_FECHATRANSFERENCIA_DESDE is null ) OR ( C_REMITODECOMPRA.FECTRANS >= @REMITODECOMPRA_1_FECHATRANSFERENCIA_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_FECHATRANSFERENCIA_HASTA is null ) OR ( C_REMITODECOMPRA.FECTRANS <= @REMITODECOMPRA_1_FECHATRANSFERENCIA_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_HORAALTAFW_DESDE is null ) OR ( C_REMITODECOMPRA.HALTAFW >= @REMITODECOMPRA_1_HORAALTAFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_HORAALTAFW_HASTA is null ) OR ( C_REMITODECOMPRA.HALTAFW <= @REMITODECOMPRA_1_HORAALTAFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_HORAEXPO_DESDE is null ) OR ( C_REMITODECOMPRA.HORAEXPO >= @REMITODECOMPRA_1_HORAEXPO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_HORAEXPO_HASTA is null ) OR ( C_REMITODECOMPRA.HORAEXPO <= @REMITODECOMPRA_1_HORAEXPO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_HORAIMPO_DESDE is null ) OR ( C_REMITODECOMPRA.HORAIMPO >= @REMITODECOMPRA_1_HORAIMPO_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_HORAIMPO_HASTA is null ) OR ( C_REMITODECOMPRA.HORAIMPO <= @REMITODECOMPRA_1_HORAIMPO_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_HORAMODIFICACIONFW_DESDE is null ) OR ( C_REMITODECOMPRA.HMODIFW >= @REMITODECOMPRA_1_HORAMODIFICACIONFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_HORAMODIFICACIONFW_HASTA is null ) OR ( C_REMITODECOMPRA.HMODIFW <= @REMITODECOMPRA_1_HORAMODIFICACIONFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_SERIEALTAFW_DESDE is null ) OR ( C_REMITODECOMPRA.SALTAFW >= @REMITODECOMPRA_1_SERIEALTAFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_SERIEALTAFW_HASTA is null ) OR ( C_REMITODECOMPRA.SALTAFW <= @REMITODECOMPRA_1_SERIEALTAFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_SERIEMODIFICACIONFW_DESDE is null ) OR ( C_REMITODECOMPRA.SMODIFW >= @REMITODECOMPRA_1_SERIEMODIFICACIONFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_SERIEMODIFICACIONFW_HASTA is null ) OR ( C_REMITODECOMPRA.SMODIFW <= @REMITODECOMPRA_1_SERIEMODIFICACIONFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_USUARIOALTAFW_DESDE is null ) OR ( C_REMITODECOMPRA.UALTAFW >= @REMITODECOMPRA_1_USUARIOALTAFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_USUARIOALTAFW_HASTA is null ) OR ( C_REMITODECOMPRA.UALTAFW <= @REMITODECOMPRA_1_USUARIOALTAFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE is null ) OR ( C_REMITODECOMPRA.UMODIFW >= @REMITODECOMPRA_1_USUARIOMODIFICACIONFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA is null ) OR ( C_REMITODECOMPRA.UMODIFW <= @REMITODECOMPRA_1_USUARIOMODIFICACIONFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_VERSIONALTAFW_DESDE is null ) OR ( C_REMITODECOMPRA.VALTAFW >= @REMITODECOMPRA_1_VERSIONALTAFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_VERSIONALTAFW_HASTA is null ) OR ( C_REMITODECOMPRA.VALTAFW <= @REMITODECOMPRA_1_VERSIONALTAFW_HASTA ) ) and 
	( ( @REMITODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE is null ) OR ( C_REMITODECOMPRA.VMODIFW >= @REMITODECOMPRA_1_VERSIONMODIFICACIONFW_DESDE ) ) and 
	( ( @REMITODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA is null ) OR ( C_REMITODECOMPRA.VMODIFW <= @REMITODECOMPRA_1_VERSIONMODIFICACIONFW_HASTA ) )
)
, ComprobantesAfectantes as
	(
	select 
		  dc.IDITEM
		, dc.FCANT
		, Afecta.AFETIPOCOM
		, Afecta.AFECTA
		, Afecta.CODIGO
	from ( select CODIGO, AFECTA, CODINTER, AFETIPOCOM from ZooLogic.COMPAFE where AFETIPO = 'Afectante' ) Afecta
		inner join ( select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.FACCOMPRADET 
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.NCCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.REMCOMPRADET
					 union
					 select CODIGO, IDITEM, AFE_COD, FCANT, FART, FCOLO, FTALL from ZooLogic.CANCOMPRADET
					) dc on Afecta.CODIGO = dc.AFE_COD and Afecta.AFECTA = dc.CODIGO
	where 1=1
	)
, ComprobantesRelacionadosAux( IDITEM, CODIGO, Cantidad, Tipo, TipoAfectado, Secuencia, SecuenciaAfectada, Afectado, Nivel ) as
	(
		select Principal.IDITEM,
			Principal.CODIGO,
			Principal.FCANT,
			Principal.FACTTIPO,
			cast( 0 as numeric(2,0)),
			cast( case 
				when Principal.FACTTIPO = 40 then 1	-- Remito
				when Principal.FACTTIPO =  8 then 2	-- Facturas
				else 3
			end as numeric(2, 0)),
			cast( 0 as numeric(2,0)),
			Principal.CODIGO,
			0 as nivel
		from ( select CODIGO, IDITEM, FACTTIPO, FCANT from ConjuntoBase ) as Principal

		union all

		select Anterior.IDITEM,
			Anterior.CODIGO,
			Afecta.FCANT,
			Afecta.AFETIPOCOM,
			Anterior.Tipo,
			cast(case 
				when Afecta.AFETIPOCOM = 40 then 1	-- Remito
				when Afecta.AFETIPOCOM =  8 then 2	-- Facturas
				when Afecta.AFETIPOCOM in (41, 10) and Anterior.TipoAfectado != 41 then -case 
																					when Anterior.Tipo = 40 then 1
																					when Anterior.Tipo =  8 then 2
																				else 3
																			end
			else 3
			end as numeric(2, 0)),
			cast(case 
				when Anterior.Tipo = 40 then 1
				when Anterior.Tipo =  8 then 2
			else 3
			end as numeric(2, 0)),
			Afecta.AFECTA,
			Anterior.nivel + 1
		from ComprobantesRelacionadosAux as Anterior
			inner join ComprobantesAfectantes Afecta on Anterior.Afectado = Afecta.CODIGO and Anterior.IDITEM = Afecta.IDITEM
	where 1=1
			and Anterior.nivel < 3
	)
, CantidadesDistribuidas as
	(
		select cantidades.CODIGO, cantidades.IDITEM
			, case cantidades.Secuencia          when  1								then cantidades.cantidad else 0 end as ConfirmadoS1
			, case cantidades.Secuencia          when -1								then cantidades.cantidad else 0 end as CanceladoS1
			, case when cantidades.SecuenciaAfectada = 1 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS1
			, case cantidades.Secuencia          when  2								then cantidades.cantidad else 0 end as ConfirmadoS2
			, case cantidades.Secuencia          when -2								then cantidades.cantidad else 0 end as CanceladoS2
			, case when cantidades.SecuenciaAfectada = 2 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS2
			, case cantidades.Secuencia          when  3								then cantidades.cantidad else 0 end as ConfirmadoS3
			, case cantidades.Secuencia          when -3								then cantidades.cantidad else 0 end as CanceladoS3
			, case when cantidades.SecuenciaAfectada = 3 and cantidades.Secuencia > 0	then cantidades.cantidad else 0 end as AfectadoS3
		from ComprobantesRelacionadosAux cantidades
	)
, ResumenDeCantidades as
	(
	select CODIGO, IDITEM
		, cast( sum( ConfirmadoS1 ) as numeric( 9, 3 ) )							as confirmadoremito
		, cast( sum( CanceladoS1 ) as numeric( 9, 3 ) )								as canceladoremito
		, cast( sum( AfectadoS1 ) as numeric( 9, 3 ) )								as afectadoremito
		, cast( sum( ConfirmadoS1 - CanceladoS1 - AfectadoS1 ) as numeric( 9, 3 ) ) as pendientefactura
		, cast( sum( ConfirmadoS2 ) as numeric( 9, 3 ) )							as confirmadofactura
		, cast( sum( CanceladoS2 ) as numeric( 9, 3 ) )								as canceladofactura
		, cast( sum( AfectadoS2 ) as numeric( 9, 3 ) )								as afectadofactura
		, cast( sum( ConfirmadoS3 ) as numeric( 9, 3 ) )							as confirmadonotas
		, cast( sum( CanceladoS3 ) as numeric( 9, 3 ) )								as canceladonotas
		, cast( sum( AfectadoS3 ) as numeric( 9, 3 ) )								as afectadonotas
	from CantidadesDistribuidas
	group by CODIGO, IDITEM
	)
Select cb.*, 
	cast( rc.confirmadoremito	as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CantidadTramo0Virtual,
	cast( rc.canceladoremito	as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CancelaTramo0Virtual,
	cast( rc.pendientefactura	as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_PendienteTramo1Virtual,
	cast( rc.confirmadofactura	as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CantidadTramo1Virtual,
	cast( rc.canceladofactura	as numeric( 9, 3 ) ) as ITEMARTICULOSREMCOMPRA_CancelaTramo1Virtual
from ConjuntoBase cb
	left join ResumenDeCantidades rc on cb.CODIGO = rc.CODIGO and cb.IDITEM = rc.IDITEM