IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[VAL_CON_CANJEDEVALORES]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[VAL_CON_CANJEDEVALORES];
GO;

CREATE FUNCTION [Listados].[VAL_CON_CANJEDEVALORES]
(
	@ITEMVALORES_FECHA_DESDE datetime,
	@ITEMVALORES_FECHA_HASTA datetime
)
RETURNS TABLE
AS
RETURN
(
select
	row_number() over ( order by c_VALEXTENDIDA.JJFECHA, c_VALEXTENDIDA.MARCATEMPORAL, c_VALEXTENDIDA.ORDEN, c_VALEXTENDIDA.IDCAJA, c_VALEXTENDIDA.JJT ) as SECUENCIA,
	c_VALEXTENDIDA.COTIZA, 
	c_VALEXTENDIDA.CUPON, 
	c_VALEXTENDIDA.FECHCOTI, 
	c_VALEXTENDIDA.GUIDCUPON, 
	c_VALEXTENDIDA.IDCAJA, 
	c_VALEXTENDIDA.JJCO, 
	c_VALEXTENDIDA.JJCOTIZ, 
	c_VALEXTENDIDA.JJDE, 
	c_VALEXTENDIDA.JJFE, 
	c_VALEXTENDIDA.JJFECHA, 
	c_VALEXTENDIDA.JJM, 
	c_VALEXTENDIDA.JJNUM, 
	c_VALEXTENDIDA.JJT, 
	c_VALEXTENDIDA.JJTOTFAC, 
	c_VALEXTENDIDA.JJRECIB, 	
	c_VALEXTENDIDA.JJTURNO, 
	c_VALEXTENDIDA.JJVEN, 
	c_VALEXTENDIDA.LETRA, 
	c_VALEXTENDIDA.NROCHEQUE,
	c_VALEXTENDIDA.NROCHPROP,
	c_CUPONES.NUMERO as NROCUPON, 
	c_VALEXTENDIDA.NRODOC,
	c_VALEXTENDIDA.NROINTERNO, 
	c_VALEXTENDIDA.NROITEM, 
	c_CUPONES.ULTDIG as NROTARJETA, 
	c_VALEXTENDIDA.NUMCOMPR, 
	c_VALEXTENDIDA.PERMVUELTO, 
	c_VALEXTENDIDA.PERSCOMP, 
	c_VALEXTENDIDA.PESOS, 
	c_VALEXTENDIDA.RECPESOS, 
	c_VALEXTENDIDA.MONTOSISTE,
	c_VALEXTENDIDA.PTOVENTA, 
	c_VALEXTENDIDA.RECMONTO, 
	c_VALEXTENDIDA.RECPORC, 
	c_VALEXTENDIDA.RECSINIMP, 
	c_VALEXTENDIDA.RECSINPER, 
	c_VALEXTENDIDA.REDONDEO, 
	c_VALEXTENDIDA.SIGNO, 
	c_VALEXTENDIDA.TIPCOMP, 
	c_VALEXTENDIDA.TIPODOC, 
	c_VALEXTENDIDA.VALECAMBIO, 
	c_VALEXTENDIDA.AUTORIZADO, 
	c_VALEXTENDIDA.IDITEM, 
	c_VALEXTENDIDA.DESCMONTO, 
	c_VALEXTENDIDA.DESCPORC, 
	c_VALEXTENDIDA.DESCSINIMP, 
	c_VALEXTENDIDA.MONDESPES, 
	c_VALEXTENDIDA.MONDESREC, 
	c_VALEXTENDIDA.MONRECPES, 
	c_VALEXTENDIDA.PORCDESREC,
	c_CUPONES.CUOTAS,
	c_CUPONES.LOTE,
	c_VALEXTENDIDA.ESVUELTO,
	c_VALEXTENDIDA.faltafw,
	c_VALEXTENDIDA.HALTAFW,
	c_VALEXTENDIDA.BDALTAFW,
	c_VALEXTENDIDA.BDMODIFW,
	c_VALEXTENDIDA.ESTTRANS,
	c_VALEXTENDIDA.fecexpo,
	c_VALEXTENDIDA.fecimpo, 
	c_VALEXTENDIDA.fmodifw,
	c_VALEXTENDIDA.fectrans,
	c_VALEXTENDIDA.HORAEXPO,
	c_VALEXTENDIDA.HORAIMPO,
	c_VALEXTENDIDA.HMODIFW,
	c_VALEXTENDIDA.SALTAFW, 
	c_VALEXTENDIDA.SMODIFW, 
	c_VALEXTENDIDA.UALTAFW, 
	c_VALEXTENDIDA.UMODIFW, 
	c_VALEXTENDIDA.VALTAFW, 
	c_VALEXTENDIDA.VMODIFW, 
	c_VALEXTENDIDA.ZADSFW 
from (
	select MARCATEMPORAL, ORDEN, COTIZA, CUPON, FECHCOTI, GUIDCUPON, IDCAJA, JJCO, JJCOTIZ, JJDE, JJFE, JJFECHA, JJM, JJNUM, JJT, JJTOTFAC, JJRECIB, JJTURNO, JJVEN, LETRA, NROCHEQUE, NROCHPROP, NRODOC, NROINTERNO, NROITEM, NUMCOMPR, PERMVUELTO, PERSCOMP, PESOS, RECPESOS, PTOVENTA, RECMONTO, RECPORC, RECSINIMP, RECSINPER, REDONDEO, SIGNO, TIPCOMP, TIPODOC, VALECAMBIO, AUTORIZADO, IDITEM, DESCMONTO, DESCPORC, DESCSINIMP, MONDESPES, MONDESREC, MONRECPES, PORCDESREC, ESVUELTO, MONTOSISTE, faltafw, HALTAFW, BDALTAFW, BDMODIFW, ESTTRANS, fecexpo, fecimpo, fmodifw, fectrans, HORAEXPO, HORAIMPO, HMODIFW,  SALTAFW, SMODIFW, UALTAFW, UMODIFW, VALTAFW, VMODIFW, ZADSFW 
	 from Listados.VAL_ITEMVALORES_CON_VUELTO( @ITEMVALORES_FECHA_DESDE, @ITEMVALORES_FECHA_HASTA )
	union all
	select MARCATEMPORAL, ORDEN, COTIZA, CUPON, FECHCOTI, GUIDCUPON, IDCAJA, JJCO, JJCOTIZ, JJDE, JJFE, JJFECHA, JJM, JJNUM, JJT, JJTOTFAC, JJRECIB, JJTURNO, JJVEN, LETRA, NROCHEQUE, NROCHPROP, NRODOC, NROINTERNO, NROITEM, NUMCOMPR, PERMVUELTO, PERSCOMP, PESOS, RECPESOS, PTOVENTA, RECMONTO, RECPORC, RECSINIMP, RECSINPER, REDONDEO, SIGNO, TIPCOMP, TIPODOC, VALECAMBIO, AUTORIZADO, IDITEM, DESCMONTO, DESCPORC, DESCSINIMP, MONDESPES, MONDESREC, MONRECPES, PORCDESREC, ESVUELTO, MONTOSISTE, faltafw, HALTAFW, BDALTAFW, BDMODIFW, ESTTRANS, fecexpo, fecimpo, fmodifw, fectrans, HORAEXPO, HORAIMPO, HMODIFW,  SALTAFW, SMODIFW, UALTAFW, UMODIFW, VALTAFW, VMODIFW, ZADSFW 
	 from Listados.VAL_ITEMVALORESAENT( @ITEMVALORES_FECHA_DESDE, @ITEMVALORES_FECHA_HASTA )
	union all
	select MARCATEMPORAL, ORDEN, COTIZA, CUPON, FECHCOTI, GUIDCUPON, IDCAJA, JJCO, JJCOTIZ, JJDE, JJFE, JJFECHA, JJM, JJNUM, JJT, JJTOTFAC, JJRECIB, JJTURNO, JJVEN, LETRA, NROCHEQUE, NROCHPROP, NRODOC, NROINTERNO, NROITEM, NUMCOMPR, PERMVUELTO, PERSCOMP, PESOS, RECPESOS, PTOVENTA, RECMONTO, RECPORC, RECSINIMP, RECSINPER, REDONDEO, SIGNO, TIPCOMP, TIPODOC, VALECAMBIO, AUTORIZADO, IDITEM, DESCMONTO, DESCPORC, DESCSINIMP, MONDESPES, MONDESREC, MONRECPES, PORCDESREC, ESVUELTO, MONTOSISTE, faltafw, HALTAFW, BDALTAFW, BDMODIFW, ESTTRANS, fecexpo, fecimpo, fmodifw, fectrans, HORAEXPO, HORAIMPO, HMODIFW,  SALTAFW, SMODIFW, UALTAFW, UMODIFW, VALTAFW, VMODIFW, ZADSFW 
	 from Listados.VAL_ITEMVALORESAREC( @ITEMVALORES_FECHA_DESDE, @ITEMVALORES_FECHA_HASTA )
	) as c_VALEXTENDIDA
	left join ZooLogic.CUPONES as c_CUPONES on c_CUPONES.CODIGO = c_VALEXTENDIDA.CUPON
)