IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Listados].[HER_ADT_STOCKCOMBINACION_ADT_STOCKCOMBINACION]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Listados].[HER_ADT_STOCKCOMBINACION_ADT_STOCKCOMBINACION];
GO;

CREATE FUNCTION [listados].[HER_ADT_STOCKCOMBINACION_ADT_STOCKCOMBINACION]
( @BaseDeDatos varchar(8),
	@PROVEEDOR_777777_NOMBRE_DESDE varchar(60),
	@PROVEEDOR_777777_NOMBRE_HASTA varchar(60),
	@ADT_STOCKCOMBINACION_ADT_ENT_DESDE varchar(40),
	@ADT_STOCKCOMBINACION_ADT_ENT_HASTA varchar(40),
	@ADT_STOCKCOMBINACION_CODIGO_DESDE varchar(26),
	@ADT_STOCKCOMBINACION_CODIGO_HASTA varchar(26),
	@ADT_STOCKCOMBINACION_CANTIDADORIGINAL_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_CANTIDADORIGINAL_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTRANSITOORIGINAL_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTRANSITOORIGINAL_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTREGAPEN_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTREGAPEN_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTREGAPENORIGINAL_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTREGAPENORIGINAL_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_COMPRAPEN_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_COMPRAPEN_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_COMPRAPENORIGINAL_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_COMPRAPENORIGINAL_HASTA numeric(16, 3),
	@ARTICULO_777872_DESCRIPCION_DESDE varchar(70),
	@ARTICULO_777872_DESCRIPCION_HASTA varchar(70),
	@ARTICULO_777872_TEMPORADA_DESDE varchar(5),
	@ARTICULO_777872_TEMPORADA_HASTA varchar(5),
	@ARTICULO_777872_UNIDADDEMEDIDA_DESDE varchar(3),
	@ARTICULO_777872_UNIDADDEMEDIDA_HASTA varchar(3),
	@ARTICULO_777872_FAMILIA_DESDE varchar(10),
	@ARTICULO_777872_FAMILIA_HASTA varchar(10),
	@ARTICULO_777872_MATERIAL_DESDE varchar(10),
	@ARTICULO_777872_MATERIAL_HASTA varchar(10),
	@ARTICULO_777872_LINEA_DESDE varchar(10),
	@ARTICULO_777872_LINEA_HASTA varchar(10),
	@ARTICULO_777872_GRUPO_DESDE varchar(10),
	@ARTICULO_777872_GRUPO_HASTA varchar(10),
	@ARTICULO_777872_CATEGORIADEARTICULO_DESDE varchar(10),
	@ARTICULO_777872_CATEGORIADEARTICULO_HASTA varchar(10),
	@ARTICULO_777872_CLASIFICACION_DESDE varchar(10),
	@ARTICULO_777872_CLASIFICACION_HASTA varchar(10),
	@ARTICULO_777872_ANO_DESDE numeric(4, 0),
	@ARTICULO_777872_ANO_HASTA numeric(4, 0),
	@ARTICULO_777872_TIPODEARTICULO_DESDE varchar(10),
	@ARTICULO_777872_TIPODEARTICULO_HASTA varchar(10),
	@ARTICULO_777872_COMPORTAMIENTO numeric(1, 0),
	@ARTICULO_777872_IMAGEN_DESDE varchar(70),
	@ARTICULO_777872_IMAGEN_HASTA varchar(70),
	@ARTICULO_777872_PROVEEDOR_DESDE varchar(10),
	@ARTICULO_777872_PROVEEDOR_HASTA varchar(10),
	@ADT_STOCKCOMBINACION_ADT_FECHA_DESDE datetime,
	@ADT_STOCKCOMBINACION_ADT_FECHA_HASTA datetime,
	@ADT_STOCKCOMBINACION_ADT_HORA_DESDE varchar(8),
	@ADT_STOCKCOMBINACION_ADT_HORA_HASTA varchar(8),
	@ADT_STOCKCOMBINACION_ADT_SERIE_DESDE varchar(20),
	@ADT_STOCKCOMBINACION_ADT_SERIE_HASTA varchar(20),
	@ADT_STOCKCOMBINACION_ADT_USR_DESDE varchar(100),
	@ADT_STOCKCOMBINACION_ADT_USR_HASTA varchar(100),
	@ADT_STOCKCOMBINACION_ADT_COMP_DESDE varchar(254),
	@ADT_STOCKCOMBINACION_ADT_COMP_HASTA varchar(254),
	@ADT_STOCKCOMBINACION_ADT_VERS_DESDE varchar(13),
	@ADT_STOCKCOMBINACION_ADT_VERS_HASTA varchar(13),
	@ADT_STOCKCOMBINACION_ARTICULO_DESDE varchar(15),
	@ADT_STOCKCOMBINACION_ARTICULO_HASTA varchar(15),
	@ADT_STOCKCOMBINACION_COLOR_DESDE varchar(6),
	@ADT_STOCKCOMBINACION_COLOR_HASTA varchar(6),
	@ADT_STOCKCOMBINACION_TALLE_DESDE varchar(5),
	@ADT_STOCKCOMBINACION_TALLE_HASTA varchar(5),
	@ADT_STOCKCOMBINACION_CANTIDAD_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_CANTIDAD_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTRANSITO_DESDE numeric(16, 3),
	@ADT_STOCKCOMBINACION_ENTRANSITO_HASTA numeric(16, 3),
	@ADT_STOCKCOMBINACION_PEDCOMP_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDCOMP_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDCOMPORIGINAL_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDCOMPORIGINAL_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDIDO_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDIDO_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDIDOORIGINAL_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PEDIDOORIGINAL_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PREPARADO_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PREPARADO_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PREPARADOORIGINAL_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PREPARADOORIGINAL_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PRESUPUESTADO_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PRESUPUESTADO_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_PRESUPUESTADOORIGINAL_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_PRESUPUESTADOORIGINAL_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_SENIADO_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_SENIADO_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_SENIADOORIGINAL_DESDE numeric(15, 2),
	@ADT_STOCKCOMBINACION_SENIADOORIGINAL_HASTA numeric(15, 2),
	@ADT_STOCKCOMBINACION_ADT_EXT bit,
	@STOCKCOMBINACION_777873_CODIGO_CANTIDAD_DESDE numeric(16, 3),
	@STOCKCOMBINACION_777873_CODIGO_CANTIDAD_HASTA numeric(16, 3),
	@COLOR_777874_COLOR_DESCRIPCION_DESDE varchar(50),
	@COLOR_777874_COLOR_DESCRIPCION_HASTA varchar(50),
	@TALLE_777875_TALLE_DESCRIPCION_DESDE varchar(50),
	@TALLE_777875_TALLE_DESCRIPCION_HASTA varchar(50),
	@SEGMENTACION_778030_SEGMENTACION_DESCRIPCION_DESDE varchar(50),
	@SEGMENTACION_778030_SEGMENTACION_DESCRIPCION_HASTA varchar(50),
	@LINEASUCURSAL_778029_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEASUCURSAL_778029_LINEA_DESCRIPCION_HASTA varchar(50),
	@TIPOSUCURSAL_778028_TIPO_DESCRIPCION_DESDE varchar(50),
	@TIPOSUCURSAL_778028_TIPO_DESCRIPCION_HASTA varchar(50),
	@TEMPORADA_9315_TEMPORADA_DESCRIPCION_DESDE varchar(50),
	@TEMPORADA_9315_TEMPORADA_DESCRIPCION_HASTA varchar(50),
	@UNIDADDEMEDIDA_9320_UNIDADDEMEDIDA_DESCRIPCION_DESDE varchar(50),
	@UNIDADDEMEDIDA_9320_UNIDADDEMEDIDA_DESCRIPCION_HASTA varchar(50),
	@FAMILIA_9325_FAMILIA_DESCRIPCION_DESDE varchar(50),
	@FAMILIA_9325_FAMILIA_DESCRIPCION_HASTA varchar(50),
	@MATERIAL_9330_MATERIAL_DESCRIPCION_DESDE varchar(40),
	@MATERIAL_9330_MATERIAL_DESCRIPCION_HASTA varchar(40),
	@LINEA_9335_LINEA_DESCRIPCION_DESDE varchar(50),
	@LINEA_9335_LINEA_DESCRIPCION_HASTA varchar(50),
	@GRUPO_9340_GRUPO_DESCRIPCION_DESDE varchar(50),
	@GRUPO_9340_GRUPO_DESCRIPCION_HASTA varchar(50),
	@CATEGORIADEARTICULO_9345_CATEGORIADEARTICULO_DESCRIPCION_DESDE varchar(50),
	@CATEGORIADEARTICULO_9345_CATEGORIADEARTICULO_DESCRIPCION_HASTA varchar(50),
	@CLASIFICACIONARTICULO_9350_CLASIFICACION_DESCRIPCION_DESDE varchar(50),
	@CLASIFICACIONARTICULO_9350_CLASIFICACION_DESCRIPCION_HASTA varchar(50),
	@TIPODEARTICULO_9360_TIPODEARTICULO_DESCRIPCION_DESDE varchar(50),
	@TIPODEARTICULO_9360_TIPODEARTICULO_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_778025_SEGMENTACION_DESDE varchar(10),
	@SUCURSAL_778025_SEGMENTACION_HASTA varchar(10),
	@SUCURSAL_778025_LINEA_DESDE varchar(10),
	@SUCURSAL_778025_LINEA_HASTA varchar(10),
	@SUCURSAL_778025_TIPO_DESDE varchar(10),
	@SUCURSAL_778025_TIPO_HASTA varchar(10),
	@SUCURSAL_778025_DESCRIPCION_DESDE varchar(50),
	@SUCURSAL_778025_DESCRIPCION_HASTA varchar(50),
	@SUCURSAL_778025_CODIGO_DESDE varchar(10),
	@SUCURSAL_778025_CODIGO_HASTA varchar(10) )
RETURNS TABLE
AS
RETURN
(
select cast( funciones.padr( @basededatos, 8, ' ' ) + funciones.padr( c_adt_stockcombinacion.adt_cod, 38, ' ' ) as varchar( 46 ) ) as ADT_STOCKCOMBINACION__Grupo,
	@basededatos as ADT_STOCKCOMBINACION__BD,
	c_ADT_STOCKCOMBINACION.ADT_ADN as ADT_STOCKCOMBINACION_ADT_ADN,
	C_ARTICULO.ARTFAB as ARTICULO_ARTFAB,
	C_PROVEEDOR.CLNOM as PROVEEDOR_CLNOM,
	cast( funciones.obtenerresultado(c_adt_stockcombinacion.cocant+c_adt_stockcombinacion.corig) as numeric( 16, 3 ) ) as ADT_STOCKCOMBINACION_STOCK,
	c_ADT_STOCKCOMBINACION.ADT_COD as ADT_STOCKCOMBINACION_ADT_Cod,
	case when c_adt_stockcombinacion.adt_fecha = '01/01/1900 00:00:00' then null else c_adt_stockcombinacion.adt_fecha end as ADT_STOCKCOMBINACION_ADT_Fecha,
	c_ADT_STOCKCOMBINACION.ADT_HORA as ADT_STOCKCOMBINACION_ADT_Hora,
	c_ADT_STOCKCOMBINACION.ADT_SERIE as ADT_STOCKCOMBINACION_ADT_Serie,
	c_ADT_STOCKCOMBINACION.ADT_USR as ADT_STOCKCOMBINACION_ADT_Usr,
	c_ADT_STOCKCOMBINACION.ADT_ENT as ADT_STOCKCOMBINACION_ADT_Ent,
	c_ADT_STOCKCOMBINACION.ADT_COMP as ADT_STOCKCOMBINACION_ADT_Comp,
	c_ADT_STOCKCOMBINACION.ADT_VERS as ADT_STOCKCOMBINACION_ADT_Vers,
	c_ADT_STOCKCOMBINACION.ADT_EXT as ADT_STOCKCOMBINACION_ADT_Ext,
	c_ADT_STOCKCOMBINACION.COART as ADT_STOCKCOMBINACION_COART,
	c_ADT_STOCKCOMBINACION.COCOD as ADT_STOCKCOMBINACION_COCOD,
	c_ADT_STOCKCOMBINACION.COCOL as ADT_STOCKCOMBINACION_COCOL,
	c_ADT_STOCKCOMBINACION.TALLE as ADT_STOCKCOMBINACION_Talle,
	c_ADT_STOCKCOMBINACION.COCANT as ADT_STOCKCOMBINACION_COCANT,
	c_ADT_STOCKCOMBINACION.CORIG as ADT_STOCKCOMBINACION_CORIG,
	c_ADT_STOCKCOMBINACION.ENTRANSITO as ADT_STOCKCOMBINACION_EnTransito,
	c_ADT_STOCKCOMBINACION.ENTRANORIG as ADT_STOCKCOMBINACION_EnTranOrig,
	c_ADT_STOCKCOMBINACION.ENTREGAPEN as ADT_STOCKCOMBINACION_EntregaPen,
	c_ADT_STOCKCOMBINACION.CORIGENTRE as ADT_STOCKCOMBINACION_cOrigEntre,
	c_ADT_STOCKCOMBINACION.COMPRAPEN as ADT_STOCKCOMBINACION_CompraPen,
	c_ADT_STOCKCOMBINACION.CORIGCOPEN as ADT_STOCKCOMBINACION_cOrigCoPen,
	c_ADT_STOCKCOMBINACION.PEDCOMP as ADT_STOCKCOMBINACION_PEDCOMP,
	c_ADT_STOCKCOMBINACION.CORIGPEDCO as ADT_STOCKCOMBINACION_cOrigPEDCO,
	c_ADT_STOCKCOMBINACION.PEDIDO as ADT_STOCKCOMBINACION_PEDIDO,
	c_ADT_STOCKCOMBINACION.CORIGPEDID as ADT_STOCKCOMBINACION_cOrigPEDID,
	c_ADT_STOCKCOMBINACION.PREPARADO as ADT_STOCKCOMBINACION_PREPARADO,
	c_ADT_STOCKCOMBINACION.CORIGPREPA as ADT_STOCKCOMBINACION_cOrigPREPA,
	c_ADT_STOCKCOMBINACION.PRESUPUEST as ADT_STOCKCOMBINACION_PRESUPUEST,
	c_ADT_STOCKCOMBINACION.CORIGPRESU as ADT_STOCKCOMBINACION_cOrigPRESU,
	c_ADT_STOCKCOMBINACION.SENIADO as ADT_STOCKCOMBINACION_SENIADO,
	c_ADT_STOCKCOMBINACION.CORIGSENIA as ADT_STOCKCOMBINACION_cOrigSENIA,
	C_SUCURSAL.SEG as SUCURSAL_seg,
	C_SUCURSAL.LINEA as SUCURSAL_Linea,
	C_SUCURSAL.TIPO as SUCURSAL_Tipo,
	C_SUCURSAL.DESCRIP as SUCURSAL_descrip,
	C_SUCURSAL.CODIGO as SUCURSAL_codigo,
	cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) as ADT_STOCKCOMBINACION__SUCURSAL,
	cast( c_adt_stockcombinacion.cocant as numeric( 16, 3 ) ) as ADT_STOCKCOMBINACION_CantidadVirtual,
	cast( case when c_adt_stockcombinacion.cocant> 0 then  c_adt_stockcombinacion.cocant else  0 end as numeric( 16, 3 ) ) as ADT_STOCKCOMBINACION_Entradas,
	cast( case when c_adt_stockcombinacion.cocant< 0 then  c_adt_stockcombinacion.cocant else  0 end as numeric( 16, 3 ) ) as ADT_STOCKCOMBINACION_Salidas,
	cast( c_adt_stockcombinacion.cocant as numeric( 16, 3 ) ) as ADT_STOCKCOMBINACION_Diferencia,
	cast( funciones.obtenernombredecomprobanteauditoria(c_adt_stockcombinacion.adt_comp) as varchar( 40 ) ) as ADT_STOCKCOMBINACION_Entidad,
	cast( funciones.obtenertipodecomprobanteasociadoalaentidad(funciones.obtenernombredecomprobanteauditoria(c_adt_stockcombinacion.adt_comp)) as numeric( 2, 0 ) ) as ADT_STOCKCOMBINACION_TipoComprobanteVirtual,
	cast( funciones.obtenerletradeuncomprobanteenlaauditoriacomb(c_adt_stockcombinacion.adt_comp) as varchar( 1 ) ) as ADT_STOCKCOMBINACION_LetraComprobanteVirtual,
	cast( funciones.obtenerpuntoventadeuncomprobanteenlaauditoriacomb(c_adt_stockcombinacion.adt_comp) as numeric( 4, 0 ) ) as ADT_STOCKCOMBINACION_PtoVtaComprobanteVirtual,
	cast( funciones.obtenernumerodeuncomprobanteenlaauditoriacomb(c_adt_stockcombinacion.adt_comp) as numeric( 8, 0 ) ) as ADT_STOCKCOMBINACION_NroComprobanteVirtual,
	cast( funciones.obteneridentificadordeentidad(case when substring(c_adt_stockcombinacion.adt_comp,1,13) = 'AJUSTEDESTOCK' THEN funciones.alltrim(substring(c_adt_stockcombinacion.adt_comp,1,13)) else funciones.obtenernombredecomprobanteauditoria(c_adt_stockcombinacion.adt_comp ) end ) as varchar( 6 ) ) as ADT_STOCKCOMBINACION_IdentificadorDeEntidadVirtual,
	case 
	when c_adt_stockcombinacion.ADT_COMP like 'MERCADERIAENTRANSITO%' and c_adt_stockcombinacion.ENTRANORIG = (c_adt_stockcombinacion.ENTRANSITO * (-1)) and C_MERCADERIAENTRANSITO.MOVGEN = 2 and upper(substring(C_MERCADERIAENTRANSITO.COMPGEN,1,25)) = upper('Mercadería en tránsito Nº') then FUNCIONES.PADL(substring(FUNCIONES.ALLTRIM(C_MERCADERIAENTRANSITO.COMPGEN),27,9),8,'0') 
	when c_adt_stockcombinacion.ADT_COMP like 'MERCADERIAENTRANSITO%' and c_adt_stockcombinacion.ENTRANORIG = 0 and c_adt_stockcombinacion.ENTRANSITO > 0 and C_MERCADERIAENTRANSITO.MOVGEN = 2 and upper(substring(C_MERCADERIAENTRANSITO.COMPGEN,1,25)) = upper('Mercadería en tránsito Nº') then funciones.obtenernumeraciondecomprobanteauditoria(c_adt_stockcombinacion.adt_comp)
	else cast( funciones.obtenernumeraciondecomprobanteauditoria(c_adt_stockcombinacion.adt_comp) as varchar( 20 ) ) 
	end as ADT_STOCKCOMBINACION_ReferenciaAComprobanteVirtual,
	cast( funciones.obtenerinformaciondecomprobantesdeauditoria(c_adt_stockcombinacion.adt_comp, 'motivo') as varchar( 3 ) ) as ADT_STOCKCOMBINACION_CodMotivo,
	cast( funciones.obtenerinformaciondecomprobantesdeauditoria(c_adt_stockcombinacion.adt_comp, 'descripcion') as varchar( 30 ) ) as ADT_STOCKCOMBINACION_DescripcionMotivo,
	cast( funciones.obtenerinformaciondecomprobantesdeauditoria(c_adt_stockcombinacion.adt_comp, 'cliente') as varchar( 10 ) ) as ADT_STOCKCOMBINACION_CodigoCliente,
	cast( funciones.obtenerinformaciondecomprobantesdeauditoria(c_adt_stockcombinacion.adt_comp, 'nombre') as varchar( 40 ) ) as ADT_STOCKCOMBINACION_NombreCliente,
	C_MSTOCK.REMITO as ADT_STOCKCOMBINACION_RemitoVirtual,
	C_MSTOCK.ORIGDEST as ADT_STOCKCOMBINACION_OrigenDestinoVirtual,
	C_MSTOCK.DIRMOV as ADT_STOCKCOMBINACION_TipoVirtual,
	C_VENDEDOR.CLNOM as ADT_STOCKCOMBINACION_VendedorVirtual,
	C_MSTOCK.NUMERO as ADT_STOCKCOMBINACION_NumeroVirtual,
	c_ADT_STOCKCOMBINACION.FECHATRANSACCION as ADT_STOCKCOMBINACION_FechaComprobanteVirtual,
	C_ARTICULO.ARTDES as ARTICULO_ARTDES,
	C_ARTICULO.ATEMPORADA as ARTICULO_ATEMPORADA,
	C_ARTICULO.UNIMED as ARTICULO_UniMed,
	C_ARTICULO.FAMILIA as ARTICULO_Familia,
	C_ARTICULO.MAT as ARTICULO_Mat,
	C_ARTICULO.LINEA as ARTICULO_Linea,
	C_ARTICULO.GRUPO as ARTICULO_Grupo,
	C_ARTICULO.CATEARTI as ARTICULO_CateArti,
	C_ARTICULO.CLASIFART as ARTICULO_ClasifArt,
	C_ARTICULO.ANO as ARTICULO_Ano,
	C_ARTICULO.TIPOARTI as ARTICULO_TipoArti,
	C_ARTICULO.ASTOCK as ARTICULO_ASTOCK,
	C_ARTICULO.ARIMAGEN as ARTICULO_ARIMAGEN,
	cast( 0 as numeric( 1, 0 ) ) as ADT_STOCKCOMBINACION_ExcluirMercTransito,
	funciones.obtenersiescomprobantequemodificastockparaauditoria(c_adt_stockcombinacion.adt_comp, c_adt_stockcombinacion.cocant) as ADT_STOCKCOMBINACION_ExcluirComprobantesSinMovimientoStock,
	C_STOCKCOMBINACION.COCANT as STOCKCOMBINACION_COCANT,
	C_COLOR.COLDES as COLOR_COLDES,
	C_TALLE.DESCRIP as TALLE_Descrip,
	C_SEGMENTACION.SDES as SEGMENTACION_SDES,
	C_LINEASUCURSAL.LSDES as LINEASUCURSAL_LSDES,
	C_TIPOSUCURSAL.TDES as TIPOSUCURSAL_TDES,
	C_TEMPORADA.TDES as TEMPORADA_TDES,
	C_UNIDADDEMEDIDA.DESCRIP as UNIDADDEMEDIDA_Descrip,
	C_FAMILIA.DESCRIP as FAMILIA_Descrip,
	C_MATERIAL.MATDES as MATERIAL_MATDES,
	C_LINEA.DESCRIP as LINEA_Descrip,
	C_GRUPO.DESCRIP as GRUPO_Descrip,
	C_CATEGORIADEARTICULO.DESCRIP as CATEGORIADEARTICULO_Descrip,
	C_CLASIFICACIONARTICULO.DESCRIP as CLASIFICACIONARTICULO_DESCRIP,
	C_TIPODEARTICULO.DESCRIP as TIPODEARTICULO_Descrip,
	C_ARTICULO.ARTCOD as ARTICULO_ARTCOD,
	C_CATEGORIADEARTICULO.COD as CATEGORIADEARTICULO_Cod,
	C_CLASIFICACIONARTICULO.CODIGO as CLASIFICACIONARTICULO_CODIGO,
	C_COLOR.COLCOD as COLOR_COLCOD,
	C_FAMILIA.COD as FAMILIA_Cod,
	C_GRUPO.COD as GRUPO_Cod,
	C_LINEA.COD as LINEA_Cod,
	C_LINEASUCURSAL.LSCOD as LINEASUCURSAL_LSCOD,
	C_MATERIAL.MATCOD as MATERIAL_MATCOD,
	C_PROVEEDOR.CLCOD as PROVEEDOR_CLCOD,
	C_SEGMENTACION.SCOD as SEGMENTACION_SCOD,
	C_STOCKCOMBINACION.COCOD as STOCKCOMBINACION_COCOD,
	C_TALLE.CODIGO as TALLE_Codigo,
	C_TEMPORADA.TCOD as TEMPORADA_TCOD,
	C_TIPODEARTICULO.COD as TIPODEARTICULO_Cod,
	C_TIPOSUCURSAL.TCOD as TIPOSUCURSAL_TCOD,
	C_UNIDADDEMEDIDA.COD as UNIDADDEMEDIDA_Cod
 from ( select cast( COCANT + CORIG as Numeric(16, 3) ) as CantidadResultante, cast( Funciones.ObtenerFechaDelComprobanteDeOrigenDelRegistroDeAuditoria( ADT_COMP, ADT_FECHA ) as DateTime ) as FechaTransaccion, * 
		from ZooLogic.ADT_COMB where adt_ext = 0 and 
		(case
			when (ADT_COMP LIKE 'MERCADERIAENTRANSITO%' and ZooLogic.ADT_COMB.entransito >= 0 and ENTRANORIG <> 0) then 1
			when (ADT_COMP NOT LIKE 'MERCADERIAENTRANSITO%' and ( cocant <> 0 or ZooLogic.ADT_COMB.entransito > 0 )) then 1
			else 0 end 
		) = 1
	  ) as c_ADT_STOCKCOMBINACION
 left join ZooLogic.ART as C_ARTICULO on C_ARTICULO.ARTCOD = C_ADT_STOCKCOMBINACION.COART and 0 = Funciones.empty( C_ADT_STOCKCOMBINACION.COART )
 left join ZooLogic.CATEGART as C_CATEGORIADEARTICULO on C_CATEGORIADEARTICULO.COD = C_ARTICULO.CATEARTI and 0 = Funciones.empty( C_ARTICULO.CATEARTI )
 left join ZooLogic.CLASIFART as C_CLASIFICACIONARTICULO on C_CLASIFICACIONARTICULO.CODIGO = C_ARTICULO.CLASIFART and 0 = Funciones.empty( C_ARTICULO.CLASIFART )
 left join ZooLogic.COL as C_COLOR on C_COLOR.COLCOD = C_ADT_STOCKCOMBINACION.COCOL and 0 = Funciones.empty( C_ADT_STOCKCOMBINACION.COCOL )
 left join ZooLogic.FAMILIA as C_FAMILIA on C_FAMILIA.COD = C_ARTICULO.FAMILIA and 0 = Funciones.empty( C_ARTICULO.FAMILIA )
 left join ZooLogic.GRUPO as C_GRUPO on C_GRUPO.COD = C_ARTICULO.GRUPO and 0 = Funciones.empty( C_ARTICULO.GRUPO )
 left join ZooLogic.LINEA as C_LINEA on C_LINEA.COD = C_ARTICULO.LINEA and 0 = Funciones.empty( C_ARTICULO.LINEA )
 left join ZooLogic.MAT as C_MATERIAL on C_MATERIAL.MATCOD = C_ARTICULO.MAT and 0 = Funciones.empty( C_ARTICULO.MAT )
 left join ZooLogic.PROV as C_PROVEEDOR on C_PROVEEDOR.CLCOD = C_ARTICULO.ARTFAB and 0 = Funciones.empty( C_ARTICULO.ARTFAB )
 left join ZooLogic.COMB as C_STOCKCOMBINACION on C_STOCKCOMBINACION.COCOD = C_ADT_STOCKCOMBINACION.COCOD and 0 = Funciones.empty( C_ADT_STOCKCOMBINACION.COCOD )
 left join ORGANIZACION.SUC as C_SUCURSAL on C_SUCURSAL.CODIGO = cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) and 0 = Funciones.empty( cast( funciones.obtenercodigodesucursaldeunabase(@basededatos) as varchar( 10 ) ) )
 left join ZooLogic.TALLE as C_TALLE on C_TALLE.CODIGO = C_ADT_STOCKCOMBINACION.TALLE and 0 = Funciones.empty( C_ADT_STOCKCOMBINACION.TALLE )
 left join ZooLogic.TEMPORADA as C_TEMPORADA on C_TEMPORADA.TCOD = C_ARTICULO.ATEMPORADA and 0 = Funciones.empty( C_ARTICULO.ATEMPORADA )
 left join ZooLogic.TIPOART as C_TIPODEARTICULO on C_TIPODEARTICULO.COD = C_ARTICULO.TIPOARTI and 0 = Funciones.empty( C_ARTICULO.TIPOARTI )
 left join ORGANIZACION.TSUCUR as C_TIPOSUCURSAL on C_TIPOSUCURSAL.TCOD = C_SUCURSAL.TIPO and 0 = Funciones.empty( C_SUCURSAL.TIPO )
 left join ZooLogic.UNMED as C_UNIDADDEMEDIDA on C_UNIDADDEMEDIDA.COD = C_ARTICULO.UNIMED and 0 = Funciones.empty( C_ARTICULO.UNIMED )
 left join ORGANIZACION.LSUCUR as C_LINEASUCURSAL on C_LINEASUCURSAL.LSCOD = C_SUCURSAL.LINEA and 0 = Funciones.empty( C_SUCURSAL.LINEA )
 left join ORGANIZACION.SECOD as C_SEGMENTACION on C_SEGMENTACION.SCOD = C_SUCURSAL.SEG and 0 = Funciones.empty( C_SUCURSAL.SEG )
 left join ZooLogic.MSTOCK as C_MSTOCK on C_MSTOCK.DESCFW = C_ADT_STOCKCOMBINACION.ADT_COMP and 0 = Funciones.empty( C_ADT_STOCKCOMBINACION.ADT_COMP )
 left join ZooLogic.VEN as C_VENDEDOR on C_VENDEDOR.CLCOD = C_MSTOCK.VENDEDOR and 0 = Funciones.empty( C_MSTOCK.VENDEDOR )
 left join ZooLogic.MTRANS as C_MERCADERIAENTRANSITO on C_MERCADERIAENTRANSITO.DESCFW = C_ADT_STOCKCOMBINACION.ADT_COMP and 0 = Funciones.empty( C_ADT_STOCKCOMBINACION.ADT_COMP )
 where ( not 1 = funciones.empty( c_adt_stockcombinacion.adt_cod ) ) and 
	( ( @PROVEEDOR_777777_NOMBRE_DESDE is null ) OR ( C_PROVEEDOR.CLNOM >= @PROVEEDOR_777777_NOMBRE_DESDE ) ) and 
	( ( @PROVEEDOR_777777_NOMBRE_HASTA is null ) OR ( C_PROVEEDOR.CLNOM <= @PROVEEDOR_777777_NOMBRE_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_ENT_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Ent >= @ADT_STOCKCOMBINACION_ADT_ENT_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_ENT_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Ent <= @ADT_STOCKCOMBINACION_ADT_ENT_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_CODIGO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.COCOD >= @ADT_STOCKCOMBINACION_CODIGO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_CODIGO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.COCOD <= @ADT_STOCKCOMBINACION_CODIGO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_CANTIDADORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.CORIG >= @ADT_STOCKCOMBINACION_CANTIDADORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_CANTIDADORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.CORIG <= @ADT_STOCKCOMBINACION_CANTIDADORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTRANSITOORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.EnTranOrig >= @ADT_STOCKCOMBINACION_ENTRANSITOORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTRANSITOORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.EnTranOrig <= @ADT_STOCKCOMBINACION_ENTRANSITOORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTREGAPEN_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.EntregaPen >= @ADT_STOCKCOMBINACION_ENTREGAPEN_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTREGAPEN_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.EntregaPen <= @ADT_STOCKCOMBINACION_ENTREGAPEN_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTREGAPENORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigEntre >= @ADT_STOCKCOMBINACION_ENTREGAPENORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTREGAPENORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigEntre <= @ADT_STOCKCOMBINACION_ENTREGAPENORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_COMPRAPEN_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.CompraPen >= @ADT_STOCKCOMBINACION_COMPRAPEN_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_COMPRAPEN_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.CompraPen <= @ADT_STOCKCOMBINACION_COMPRAPEN_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_COMPRAPENORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigCoPen >= @ADT_STOCKCOMBINACION_COMPRAPENORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_COMPRAPENORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigCoPen <= @ADT_STOCKCOMBINACION_COMPRAPENORIGINAL_HASTA ) ) and 
	( ( @ARTICULO_777872_DESCRIPCION_DESDE is null ) OR ( C_ARTICULO.ARTDES >= @ARTICULO_777872_DESCRIPCION_DESDE ) ) and 
	( ( @ARTICULO_777872_DESCRIPCION_HASTA is null ) OR ( C_ARTICULO.ARTDES <= @ARTICULO_777872_DESCRIPCION_HASTA ) ) and 
	( ( @ARTICULO_777872_TEMPORADA_DESDE is null ) OR ( C_ARTICULO.ATEMPORADA >= @ARTICULO_777872_TEMPORADA_DESDE ) ) and 
	( ( @ARTICULO_777872_TEMPORADA_HASTA is null ) OR ( C_ARTICULO.ATEMPORADA <= @ARTICULO_777872_TEMPORADA_HASTA ) ) and 
	( ( @ARTICULO_777872_UNIDADDEMEDIDA_DESDE is null ) OR ( C_ARTICULO.UniMed >= @ARTICULO_777872_UNIDADDEMEDIDA_DESDE ) ) and 
	( ( @ARTICULO_777872_UNIDADDEMEDIDA_HASTA is null ) OR ( C_ARTICULO.UniMed <= @ARTICULO_777872_UNIDADDEMEDIDA_HASTA ) ) and 
	( ( @ARTICULO_777872_FAMILIA_DESDE is null ) OR ( C_ARTICULO.Familia >= @ARTICULO_777872_FAMILIA_DESDE ) ) and 
	( ( @ARTICULO_777872_FAMILIA_HASTA is null ) OR ( C_ARTICULO.Familia <= @ARTICULO_777872_FAMILIA_HASTA ) ) and 
	( ( @ARTICULO_777872_MATERIAL_DESDE is null ) OR ( C_ARTICULO.Mat >= @ARTICULO_777872_MATERIAL_DESDE ) ) and 
	( ( @ARTICULO_777872_MATERIAL_HASTA is null ) OR ( C_ARTICULO.Mat <= @ARTICULO_777872_MATERIAL_HASTA ) ) and 
	( ( @ARTICULO_777872_LINEA_DESDE is null ) OR ( C_ARTICULO.Linea >= @ARTICULO_777872_LINEA_DESDE ) ) and 
	( ( @ARTICULO_777872_LINEA_HASTA is null ) OR ( C_ARTICULO.Linea <= @ARTICULO_777872_LINEA_HASTA ) ) and 
	( ( @ARTICULO_777872_GRUPO_DESDE is null ) OR ( C_ARTICULO.Grupo >= @ARTICULO_777872_GRUPO_DESDE ) ) and 
	( ( @ARTICULO_777872_GRUPO_HASTA is null ) OR ( C_ARTICULO.Grupo <= @ARTICULO_777872_GRUPO_HASTA ) ) and 
	( ( @ARTICULO_777872_CATEGORIADEARTICULO_DESDE is null ) OR ( C_ARTICULO.CateArti >= @ARTICULO_777872_CATEGORIADEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_777872_CATEGORIADEARTICULO_HASTA is null ) OR ( C_ARTICULO.CateArti <= @ARTICULO_777872_CATEGORIADEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_777872_CLASIFICACION_DESDE is null ) OR ( C_ARTICULO.ClasifArt >= @ARTICULO_777872_CLASIFICACION_DESDE ) ) and 
	( ( @ARTICULO_777872_CLASIFICACION_HASTA is null ) OR ( C_ARTICULO.ClasifArt <= @ARTICULO_777872_CLASIFICACION_HASTA ) ) and 
	( ( @ARTICULO_777872_ANO_DESDE is null ) OR ( C_ARTICULO.Ano >= @ARTICULO_777872_ANO_DESDE ) ) and 
	( ( @ARTICULO_777872_ANO_HASTA is null ) OR ( C_ARTICULO.Ano <= @ARTICULO_777872_ANO_HASTA ) ) and 
	( ( @ARTICULO_777872_TIPODEARTICULO_DESDE is null ) OR ( C_ARTICULO.TipoArti >= @ARTICULO_777872_TIPODEARTICULO_DESDE ) ) and 
	( ( @ARTICULO_777872_TIPODEARTICULO_HASTA is null ) OR ( C_ARTICULO.TipoArti <= @ARTICULO_777872_TIPODEARTICULO_HASTA ) ) and 
	( ( @ARTICULO_777872_COMPORTAMIENTO is null ) OR ( C_ARTICULO.ASTOCK = @ARTICULO_777872_COMPORTAMIENTO ) ) and 
	( ( @ARTICULO_777872_IMAGEN_DESDE is null ) OR ( C_ARTICULO.ARIMAGEN >= @ARTICULO_777872_IMAGEN_DESDE ) ) and 
	( ( @ARTICULO_777872_IMAGEN_HASTA is null ) OR ( C_ARTICULO.ARIMAGEN <= @ARTICULO_777872_IMAGEN_HASTA ) ) and 
	( ( @ARTICULO_777872_PROVEEDOR_DESDE is null ) OR ( C_ARTICULO.ARTFAB >= @ARTICULO_777872_PROVEEDOR_DESDE ) ) and 
	( ( @ARTICULO_777872_PROVEEDOR_HASTA is null ) OR ( C_ARTICULO.ARTFAB <= @ARTICULO_777872_PROVEEDOR_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_FECHA_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Fecha >= @ADT_STOCKCOMBINACION_ADT_FECHA_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_FECHA_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Fecha <= @ADT_STOCKCOMBINACION_ADT_FECHA_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_HORA_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Hora >= @ADT_STOCKCOMBINACION_ADT_HORA_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_HORA_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Hora <= @ADT_STOCKCOMBINACION_ADT_HORA_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_SERIE_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Serie >= @ADT_STOCKCOMBINACION_ADT_SERIE_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_SERIE_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Serie <= @ADT_STOCKCOMBINACION_ADT_SERIE_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_USR_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Usr >= @ADT_STOCKCOMBINACION_ADT_USR_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_USR_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Usr <= @ADT_STOCKCOMBINACION_ADT_USR_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_COMP_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Comp >= @ADT_STOCKCOMBINACION_ADT_COMP_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_COMP_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Comp <= @ADT_STOCKCOMBINACION_ADT_COMP_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_VERS_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Vers >= @ADT_STOCKCOMBINACION_ADT_VERS_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_VERS_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Vers <= @ADT_STOCKCOMBINACION_ADT_VERS_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ARTICULO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.COART >= @ADT_STOCKCOMBINACION_ARTICULO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ARTICULO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.COART <= @ADT_STOCKCOMBINACION_ARTICULO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_COLOR_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.COCOL >= @ADT_STOCKCOMBINACION_COLOR_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_COLOR_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.COCOL <= @ADT_STOCKCOMBINACION_COLOR_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_TALLE_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.Talle >= @ADT_STOCKCOMBINACION_TALLE_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_TALLE_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.Talle <= @ADT_STOCKCOMBINACION_TALLE_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_CANTIDAD_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.COCANT >= @ADT_STOCKCOMBINACION_CANTIDAD_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_CANTIDAD_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.COCANT <= @ADT_STOCKCOMBINACION_CANTIDAD_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTRANSITO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.EnTransito >= @ADT_STOCKCOMBINACION_ENTRANSITO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_ENTRANSITO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.EnTransito <= @ADT_STOCKCOMBINACION_ENTRANSITO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDCOMP_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.PEDCOMP >= @ADT_STOCKCOMBINACION_PEDCOMP_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDCOMP_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.PEDCOMP <= @ADT_STOCKCOMBINACION_PEDCOMP_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDCOMPORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPEDCO >= @ADT_STOCKCOMBINACION_PEDCOMPORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDCOMPORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPEDCO <= @ADT_STOCKCOMBINACION_PEDCOMPORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDIDO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.PEDIDO >= @ADT_STOCKCOMBINACION_PEDIDO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDIDO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.PEDIDO <= @ADT_STOCKCOMBINACION_PEDIDO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDIDOORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPEDID >= @ADT_STOCKCOMBINACION_PEDIDOORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PEDIDOORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPEDID <= @ADT_STOCKCOMBINACION_PEDIDOORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PREPARADO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.PREPARADO >= @ADT_STOCKCOMBINACION_PREPARADO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PREPARADO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.PREPARADO <= @ADT_STOCKCOMBINACION_PREPARADO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PREPARADOORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPREPA >= @ADT_STOCKCOMBINACION_PREPARADOORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PREPARADOORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPREPA <= @ADT_STOCKCOMBINACION_PREPARADOORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PRESUPUESTADO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.PRESUPUEST >= @ADT_STOCKCOMBINACION_PRESUPUESTADO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PRESUPUESTADO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.PRESUPUEST <= @ADT_STOCKCOMBINACION_PRESUPUESTADO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_PRESUPUESTADOORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPRESU >= @ADT_STOCKCOMBINACION_PRESUPUESTADOORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_PRESUPUESTADOORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigPRESU <= @ADT_STOCKCOMBINACION_PRESUPUESTADOORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_SENIADO_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.SENIADO >= @ADT_STOCKCOMBINACION_SENIADO_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_SENIADO_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.SENIADO <= @ADT_STOCKCOMBINACION_SENIADO_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_SENIADOORIGINAL_DESDE is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigSENIA >= @ADT_STOCKCOMBINACION_SENIADOORIGINAL_DESDE ) ) and 
	( ( @ADT_STOCKCOMBINACION_SENIADOORIGINAL_HASTA is null ) OR ( c_ADT_STOCKCOMBINACION.cOrigSENIA <= @ADT_STOCKCOMBINACION_SENIADOORIGINAL_HASTA ) ) and 
	( ( @ADT_STOCKCOMBINACION_ADT_EXT is null ) OR ( c_ADT_STOCKCOMBINACION.ADT_Ext = @ADT_STOCKCOMBINACION_ADT_EXT ) ) and 
	( ( @STOCKCOMBINACION_777873_CODIGO_CANTIDAD_DESDE is null ) OR ( C_STOCKCOMBINACION.COCANT >= @STOCKCOMBINACION_777873_CODIGO_CANTIDAD_DESDE ) ) and 
	( ( @STOCKCOMBINACION_777873_CODIGO_CANTIDAD_HASTA is null ) OR ( C_STOCKCOMBINACION.COCANT <= @STOCKCOMBINACION_777873_CODIGO_CANTIDAD_HASTA ) ) and 
	( ( @COLOR_777874_COLOR_DESCRIPCION_DESDE is null ) OR ( C_COLOR.COLDES >= @COLOR_777874_COLOR_DESCRIPCION_DESDE ) ) and 
	( ( @COLOR_777874_COLOR_DESCRIPCION_HASTA is null ) OR ( C_COLOR.COLDES <= @COLOR_777874_COLOR_DESCRIPCION_HASTA ) ) and 
	( ( @TALLE_777875_TALLE_DESCRIPCION_DESDE is null ) OR ( C_TALLE.Descrip >= @TALLE_777875_TALLE_DESCRIPCION_DESDE ) ) and 
	( ( @TALLE_777875_TALLE_DESCRIPCION_HASTA is null ) OR ( C_TALLE.Descrip <= @TALLE_777875_TALLE_DESCRIPCION_HASTA ) ) and 
	( ( @SEGMENTACION_778030_SEGMENTACION_DESCRIPCION_DESDE is null ) OR ( C_SEGMENTACION.SDES >= @SEGMENTACION_778030_SEGMENTACION_DESCRIPCION_DESDE ) ) and 
	( ( @SEGMENTACION_778030_SEGMENTACION_DESCRIPCION_HASTA is null ) OR ( C_SEGMENTACION.SDES <= @SEGMENTACION_778030_SEGMENTACION_DESCRIPCION_HASTA ) ) and 
	( ( @LINEASUCURSAL_778029_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEASUCURSAL.LSDES >= @LINEASUCURSAL_778029_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEASUCURSAL_778029_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEASUCURSAL.LSDES <= @LINEASUCURSAL_778029_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @TIPOSUCURSAL_778028_TIPO_DESCRIPCION_DESDE is null ) OR ( C_TIPOSUCURSAL.TDES >= @TIPOSUCURSAL_778028_TIPO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPOSUCURSAL_778028_TIPO_DESCRIPCION_HASTA is null ) OR ( C_TIPOSUCURSAL.TDES <= @TIPOSUCURSAL_778028_TIPO_DESCRIPCION_HASTA ) ) and 
	( ( @TEMPORADA_9315_TEMPORADA_DESCRIPCION_DESDE is null ) OR ( C_TEMPORADA.TDES >= @TEMPORADA_9315_TEMPORADA_DESCRIPCION_DESDE ) ) and 
	( ( @TEMPORADA_9315_TEMPORADA_DESCRIPCION_HASTA is null ) OR ( C_TEMPORADA.TDES <= @TEMPORADA_9315_TEMPORADA_DESCRIPCION_HASTA ) ) and 
	( ( @UNIDADDEMEDIDA_9320_UNIDADDEMEDIDA_DESCRIPCION_DESDE is null ) OR ( C_UNIDADDEMEDIDA.Descrip >= @UNIDADDEMEDIDA_9320_UNIDADDEMEDIDA_DESCRIPCION_DESDE ) ) and 
	( ( @UNIDADDEMEDIDA_9320_UNIDADDEMEDIDA_DESCRIPCION_HASTA is null ) OR ( C_UNIDADDEMEDIDA.Descrip <= @UNIDADDEMEDIDA_9320_UNIDADDEMEDIDA_DESCRIPCION_HASTA ) ) and 
	( ( @FAMILIA_9325_FAMILIA_DESCRIPCION_DESDE is null ) OR ( C_FAMILIA.Descrip >= @FAMILIA_9325_FAMILIA_DESCRIPCION_DESDE ) ) and 
	( ( @FAMILIA_9325_FAMILIA_DESCRIPCION_HASTA is null ) OR ( C_FAMILIA.Descrip <= @FAMILIA_9325_FAMILIA_DESCRIPCION_HASTA ) ) and 
	( ( @MATERIAL_9330_MATERIAL_DESCRIPCION_DESDE is null ) OR ( C_MATERIAL.MATDES >= @MATERIAL_9330_MATERIAL_DESCRIPCION_DESDE ) ) and 
	( ( @MATERIAL_9330_MATERIAL_DESCRIPCION_HASTA is null ) OR ( C_MATERIAL.MATDES <= @MATERIAL_9330_MATERIAL_DESCRIPCION_HASTA ) ) and 
	( ( @LINEA_9335_LINEA_DESCRIPCION_DESDE is null ) OR ( C_LINEA.Descrip >= @LINEA_9335_LINEA_DESCRIPCION_DESDE ) ) and 
	( ( @LINEA_9335_LINEA_DESCRIPCION_HASTA is null ) OR ( C_LINEA.Descrip <= @LINEA_9335_LINEA_DESCRIPCION_HASTA ) ) and 
	( ( @GRUPO_9340_GRUPO_DESCRIPCION_DESDE is null ) OR ( C_GRUPO.Descrip >= @GRUPO_9340_GRUPO_DESCRIPCION_DESDE ) ) and 
	( ( @GRUPO_9340_GRUPO_DESCRIPCION_HASTA is null ) OR ( C_GRUPO.Descrip <= @GRUPO_9340_GRUPO_DESCRIPCION_HASTA ) ) and 
	( ( @CATEGORIADEARTICULO_9345_CATEGORIADEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_CATEGORIADEARTICULO.Descrip >= @CATEGORIADEARTICULO_9345_CATEGORIADEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @CATEGORIADEARTICULO_9345_CATEGORIADEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_CATEGORIADEARTICULO.Descrip <= @CATEGORIADEARTICULO_9345_CATEGORIADEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @CLASIFICACIONARTICULO_9350_CLASIFICACION_DESCRIPCION_DESDE is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP >= @CLASIFICACIONARTICULO_9350_CLASIFICACION_DESCRIPCION_DESDE ) ) and 
	( ( @CLASIFICACIONARTICULO_9350_CLASIFICACION_DESCRIPCION_HASTA is null ) OR ( C_CLASIFICACIONARTICULO.DESCRIP <= @CLASIFICACIONARTICULO_9350_CLASIFICACION_DESCRIPCION_HASTA ) ) and 
	( ( @TIPODEARTICULO_9360_TIPODEARTICULO_DESCRIPCION_DESDE is null ) OR ( C_TIPODEARTICULO.Descrip >= @TIPODEARTICULO_9360_TIPODEARTICULO_DESCRIPCION_DESDE ) ) and 
	( ( @TIPODEARTICULO_9360_TIPODEARTICULO_DESCRIPCION_HASTA is null ) OR ( C_TIPODEARTICULO.Descrip <= @TIPODEARTICULO_9360_TIPODEARTICULO_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_778025_SEGMENTACION_DESDE is null ) OR ( C_SUCURSAL.seg >= @SUCURSAL_778025_SEGMENTACION_DESDE ) ) and 
	( ( @SUCURSAL_778025_SEGMENTACION_HASTA is null ) OR ( C_SUCURSAL.seg <= @SUCURSAL_778025_SEGMENTACION_HASTA ) ) and 
	( ( @SUCURSAL_778025_LINEA_DESDE is null ) OR ( C_SUCURSAL.Linea >= @SUCURSAL_778025_LINEA_DESDE ) ) and 
	( ( @SUCURSAL_778025_LINEA_HASTA is null ) OR ( C_SUCURSAL.Linea <= @SUCURSAL_778025_LINEA_HASTA ) ) and 
	( ( @SUCURSAL_778025_TIPO_DESDE is null ) OR ( C_SUCURSAL.Tipo >= @SUCURSAL_778025_TIPO_DESDE ) ) and 
	( ( @SUCURSAL_778025_TIPO_HASTA is null ) OR ( C_SUCURSAL.Tipo <= @SUCURSAL_778025_TIPO_HASTA ) ) and 
	( ( @SUCURSAL_778025_DESCRIPCION_DESDE is null ) OR ( C_SUCURSAL.descrip >= @SUCURSAL_778025_DESCRIPCION_DESDE ) ) and 
	( ( @SUCURSAL_778025_DESCRIPCION_HASTA is null ) OR ( C_SUCURSAL.descrip <= @SUCURSAL_778025_DESCRIPCION_HASTA ) ) and 
	( ( @SUCURSAL_778025_CODIGO_DESDE is null ) OR ( C_SUCURSAL.codigo >= @SUCURSAL_778025_CODIGO_DESDE ) ) and 
	( ( @SUCURSAL_778025_CODIGO_HASTA is null ) OR ( C_SUCURSAL.codigo <= @SUCURSAL_778025_CODIGO_HASTA ) )

)