USE [ZL]
GO

/****** Object:  UserDefinedFunction [dbo].[func_RRHH_ReporteLIHL]    Script Date: 08/02/2013 14:54:46 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[func_RRHH_ReporteLIHL]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[func_RRHH_ReporteLIHL]
GO

USE [ZL]
GO

/****** Object:  UserDefinedFunction [dbo].[func_RRHH_ReporteLIHL]    Script Date: 08/02/2013 14:54:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- ==========================================================
-- Author:		Daniel Correa
-- Create date: 02/08/2013
-- Description:	Retorna los datos para el reporte:
--              Listado de incumplimientos al horario laboral	   
-- ==========================================================
CREATE FUNCTION [dbo].[func_RRHH_ReporteLIHL]
(	
	@FECHADESDE DATETIME
	, @FECHAHASTA DATETIME
)
RETURNS TABLE 
AS
RETURN 
(
SELECT
	DISTINCT
	top 1
	[FICHAJES].LEGAJO
	, [FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3) AS FECHA
	, [FICHAJES].HORAREG
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
		ELSE NULL
	END AS [TIPO]
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN DATOS.[INGRESOESQUEMA] 
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATOS.[EGRESOESQUEMA]  
		ELSE NULL
	END AS 'HORARIOESQUEMA'
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN DATOS.TOLERANCIA
		ELSE 0
	END AS [TOLERANCIA]
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN DATOS.MINUTOS - DATOS.TOLERANCIA
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATEDIFF(MINUTE, EGRESOS.EGRESO, DATOS.[EGRESOESQUEMA]) 
		ELSE 0
	END AS DESVIO
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN CASE
															WHEN (DATOS.MINUTOS - DATOS.TOLERANCIA) > 0 THEN 'Tarde'
															WHEN (DATOS.MINUTOS - DATOS.TOLERANCIA) <= 0 THEN 'Temprano'
															ELSE ''
														END
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN	CASE
															WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, DATOS.[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
															WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, DATOS.[EGRESOESQUEMA]) <= 0 THEN 'Salida correcta'
															ELSE ''
														END
		ELSE NULL
	END AS 'TIPOINCUMPLIMIENTO'
	, DATOS.CODPUESTO as CODPUESTO
	, DATOS.AREA as AREA 
	, DATOS.SECTOR as SECTOR 
	, DATOS.ESQUEMA as  ESQUEMA
	, DATOS.ASIGESQ as ASIGESQ
	, DATOS.INGRESOESQUEMA as INGRESOESQUEMA
	, DATOS.EGRESOESQUEMA as EGRESOESQUEMA
	, DATOS.MINUTOS as MINUTOS
	, YEAR([FICHAJES].FCHREG) as ANIO
	, MONTH([FICHAJES].FCHREG) as MES
	, DAY([FICHAJES].FCHREG)  as DIA
FROM
	[ZL].[ZNFICHAJE] AS [FICHAJES]
	LEFT JOIN (SELECT * FROM [Objetivos].[func_RRHH_FichajeAplicarEsquemas](CONVERT(VARCHAR(8), @FECHADESDE, 112), CONVERT(VARCHAR(8), @FECHAHASTA, 112))) AS DATOS ON DATOS.COD = [FICHAJES].[COD]
	LEFT JOIN [ZL].[ZNPCONTROL] AS [PTOCONTROL] ON [PTOCONTROL].[COD] = [FICHAJES].[PCONTROL]
	LEFT JOIN (SELECT LEGAJO, MIN(HORAREG) AS INGRESO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112) AS FECHA FROM ZL.ZNFICHAJE GROUP BY LEGAJO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112)) AS INGRESOS ON INGRESOS.LEGAJO = [FICHAJES].[LEGAJO] AND INGRESOS.FECHA = DATOS.[FECHA]
	LEFT JOIN (SELECT LEGAJO, MAX(HORAREG) AS EGRESO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112) AS FECHA FROM ZL.ZNFICHAJE GROUP BY LEGAJO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112)) AS EGRESOS ON EGRESOS.LEGAJO = [FICHAJES].[LEGAJO] AND EGRESOS.FECHA = DATOS.[FECHA]
	LEFT JOIN (SELECT
					NUMERO
					, LEG
					, CASE INCHLAB
						WHEN 'AUS' THEN 'Ausencia'
						WHEN 'LLT' THEN 'Tarde'
						WHEN 'SAT' THEN 'Salida temprana'
						ELSE ''
					END AS MOTIVO
					, JUSTIFICA
					, FECHAF
					, FECHAI
					--, *
				FROM 
					ZL.GESINC) AS GESINC ON GESINC.LEG = FICHAJES.LEGAJO AND GESINC.FECHAI >= DATOS.FECHA AND GESINC.FECHAF <= DATOS.FECHA
WHERE
	CONVERT(DATETIME, CONVERT(VARCHAR(8), [FICHAJES].FCHREG, 112), 112) >= @FECHADESDE 
	AND CONVERT(DATETIME, CONVERT(VARCHAR(8), [FICHAJES].FCHREG, 112), 112) <= @FECHAHASTA 
	AND	CASE 
			WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
			WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
			ELSE NULL
		END IS NOT NULL
	AND 
	(CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN DATOS.MINUTOS - DATOS.[TOLERANCIA]
		ELSE 0
	END	> 0
	OR CASE 
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATEDIFF(MINUTE, DATOS.[EGRESOESQUEMA], EGRESOS.EGRESO) 
		ELSE 0
	END	< 0)
	AND (ISNULL(GESINC.JUSTIFICA, 0) = 0
	OR	CASE 
			WHEN (DATOS.MINUTOS - DATOS.[TOLERANCIA]) > 0 THEN 'Tarde'
			WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, DATOS.[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
			ELSE ''
	END <> ISNULL(GESINC.MOTIVO, ''))
	--AND DATOS.CODPUESTO IN (@PUESTOS)
	--AND DATOS.AREA IN (@AREAS)
	--AND DATOS.SECTOR IN (@SECTORES)
	AND DATOS.[MINUTOS] > DATOS.[TOLERANCIA] 
	--AND CASE 
	--	WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN CASE
	--								WHEN (DATOS.MINUTOS - DATOS.[TOLERANCIA]) > 0 THEN 'Tarde'
	--								WHEN (DATOS.MINUTOS - DATOS.[TOLERANCIA]) <= 0 THEN 'Temprano'
	--								ELSE ''
	--							END
	--	WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN	CASE
	--								WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, DATOS.[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
	--								WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, DATOS.[EGRESOESQUEMA]) <= 0 THEN 'Salida correcta'
	--								ELSE ''
	--							END
	--	ELSE NULL
	--END IN (@TIPOINCUMPLIMIENTO)
	--AND [FICHAJES].LEGAJO IN (@LEGAJO)
	--AND	CASE 
	--		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
	--		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
	--		ELSE NULL
	--	END IN (@TIPO)
GROUP BY
	FICHAJES.HORAREG
	, [FICHAJES].LEGAJO
	, INGRESOS.INGRESO
	, EGRESOS.EGRESO
	, [FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3)
	, DATOS.INGRESOESQUEMA
	, DATOS.TOLERANCIA
	, DATOS.MINUTOS
	, DATOS.[EGRESOESQUEMA]
	, DATOS.ESQUEMA
	, DATOS.CODPUESTO 
	, DATOS.AREA  
	, DATOS.SECTOR 
	, DATOS.ESQUEMA 
	, DATOS.ASIGESQ 

UNION ALL

	SELECT 
		top 1
		AUSENCIAS.LEGAJO
		, AUSENCIAS.APELLIDOYNOMBRES 
		, NULL
		, AUSENCIAS.FECHA 
		, NULL
		, NULL
		, NULL
		, NULL
		, NULL
		, AUSENCIAS.TIPOINCUMPLIMPIENTO 
		, DATOS.CODPUESTO
		, DATOS.AREA
		, DATOS.SECTOR
		, DATOS.ESQUEMA
		, DATOS.ASIGESQ
		, DATOS.INGRESOESQUEMA
		, DATOS.EGRESOESQUEMA
		, NULL
		, NULL
		, NULL
		, NULL
	FROM 
		[OBJETIVOS].[FUNC_RRHH_INCUMPLIMIENTOSAUSENCIAS]( '', @FECHADESDE , @FECHAHASTA  ) AS AUSENCIAS
		LEFT JOIN (SELECT * FROM [Objetivos].[func_RRHH_FichajeAplicarEsquemas](CONVERT(VARCHAR(8), @FECHADESDE, 112), CONVERT(VARCHAR(8), @FECHAHASTA, 112))) AS DATOS ON DATOS.LEGAJO = [AUSENCIAS].[LEGAJO]
	--ORDER BY
	--	[FICHAJES].[CAPENOM]
	--	, [FICHAJES].FCHREG
	--	, [FICHAJES].LEGAJO
	--	, [FICHAJES].HORAREG
	--	, TIPO
	--	, DATOS.ESQUEMA
	)

GO


