USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[func_ListObjetivosxPuesto]    Script Date: 04/26/2013 10:54:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[func_ListObjetivosxPuesto]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Objetivos].[func_ListObjetivosxPuesto]
GO

USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[func_ListObjetivosxPuesto]    Script Date: 04/26/2013 10:54:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================================
-- Author:		Héctor Daniel Correa
-- Create date: 18/04/2013
-- Description:	Obtiene los objetivos para uno o varios puestos
--              para una fecha dada
-- =============================================================
CREATE FUNCTION [Objetivos].[func_ListObjetivosxPuesto] (@PUESTO VARCHAR(4), @Fecha DATETIME)
	RETURNS @PUESTOS TABLE (
		--DATOS DE CABECERA
		CODIGO INT
		, DESCRIP VARCHAR(100)
		, DESDE DATETIME
		, HASTA DATETIME
		, PUESTO VARCHAR(4)
		, PUESTODESCR VARCHAR(100)
		, SECTOR VARCHAR(4)
		, AREA VARCHAR(4)
		, REPORTAA VARCHAR(4)
		, ACC VARCHAR(MAX)
		, OBS VARCHAR(MAX)
		--OBJETIVOS EN DETALLE
		, CODOBJE INT
		, DESCOBJE VARCHAR(100)
		, PESOOBJE NUMERIC(10,5)
		, TIPOOBJE INT
		, DESCTIPO VARCHAR(100)
		, PESOTIPO NUMERIC(10,5)
		, COMENT VARCHAR(250)
		--ESCALA
		, ESCDESDE NUMERIC(10,5)
		, ESCHASTA NUMERIC(10,5)
		, ESCVALOR NUMERIC(10,5)
		--FILTROS
		, CODFILT INT
		, DESCFILT VARCHAR(100)
		--INFO ADICIONAL
		, AREADESCRIP VARCHAR(100)
		, SECTDESCRIP VARCHAR(100)
		, REPORTAADESCR VARCHAR(100)
		, SUMPESOSOBJETIVOS NUMERIC(10,5)
		, SUMPESOSTIPOS NUMERIC(10,5))
AS
BEGIN
	IF (@PUESTO = '')
		BEGIN
			INSERT INTO @PUESTOS
				SELECT
					--DATOS DE CABECERA
					OBJETIVOS.CODIGO
					, RTRIM(LTRIM(OBJETIVOS.DESCRIP))
					, OBJETIVOS.DESDE
					, OBJETIVOS.HASTA
					, OBJETIVOS.PUESTO
					, RTRIM(LTRIM(PUESTOS.DESCR))
					, OBJETIVOS.SECTOR
					, OBJETIVOS.AREA
					, OBJETIVOS.REPORTAA 
					, RTRIM(LTRIM(CONVERT(VARCHAR(MAX), OBJETIVOS.ACC)))
					, RTRIM(LTRIM(CONVERT(VARCHAR(MAX), OBJETIVOS.OBS)))
					--OBJETIVOS EN DETALLE
					, DETALLE.CODOBJE
					, RTRIM(LTRIM(DETALLE.DESCOBJE))
					, DETALLE.PESOOBJE
					, DETALLE.TIPOOBJE
					, RTRIM(LTRIM(DETALLE.DESCTIPO))
					, DETALLE.PESOTIPO
					, RTRIM(LTRIM(DETALLE.COMENT))
					--ESCALA
					, ISNULL(ESCALA.DESDE, 0)
					, ISNULL(ESCALA.HASTA, 0)
					, ISNULL(ESCALA.VALOR, 0)
					--FILTROS
					, ISNULL(FILTROS.CODFILT, 0)
					, ISNULL(RTRIM(LTRIM(FILTROS.DESCFILT)), '')
					--INFO ADICIONAL
					, RTRIM(LTRIM(AREA.DESCRIP))
					, RTRIM(LTRIM(SECTORES.DESCRIP))
					, RTRIM(LTRIM(REPORTAA.DESCR))
					, SUMPESOSOBJETIVOS.SUMA
					, PESOSTIPOSOBJETIVOS.SUMA
				FROM 
					ZL.OBJEXPTO AS OBJETIVOS
					LEFT JOIN ZL.OBJEXPTODET AS DETALLE ON DETALLE.CODIGO = OBJETIVOS.CODIGO
					LEFT JOIN ZL.OBJEESVADE AS ESCALA ON ESCALA.CODIGO = OBJETIVOS.CODIGO
					LEFT JOIN ZL.FILTDET AS FILTROS ON FILTROS.CODIGO = OBJETIVOS.CODIGO
					--INFO ADICIONAL
					LEFT JOIN ZL.AREA ON AREA.CODIGO = OBJETIVOS.AREA
					LEFT JOIN ZL.SECTORES ON SECTORES.CODIGO = OBJETIVOS.SECTOR
					LEFT JOIN ZL.PUESTOSRH AS PUESTOS ON PUESTOS.COD = OBJETIVOS.PUESTO
					LEFT JOIN ZL.PUESTOSRH AS REPORTAA ON REPORTAA.COD = OBJETIVOS.REPORTAA
					
					LEFT JOIN (SELECT
									SUM(SUMAPESOSOBJETIVOS.PESO) AS SUMA
									, PUESTO
								FROM
									ZL.OBJEXPTO
									INNER JOIN ZL.OBJEXPTODET ON ZL.OBJEXPTODET.CODIGO = ZL.OBJEXPTO.CODIGO
									LEFT JOIN (SELECT PESO, COD FROM ZL.OBJET GROUP BY COD, PESO) AS SUMAPESOSOBJETIVOS ON SUMAPESOSOBJETIVOS.COD = ZL.OBJEXPTODET.CODOBJE
								GROUP BY
									ZL.OBJEXPTO.PUESTO
								) AS SUMPESOSOBJETIVOS ON SUMPESOSOBJETIVOS.PUESTO = OBJETIVOS.PUESTO
					LEFT JOIN (SELECT SUM(PESO) AS SUMA, PUESTO FROM (	SELECT
																			DISTINCT
																			ZL.OBJEXPTO.PUESTO
																			, ZL.TIPOOBJE.CODIGO
																			, ZL.TIPOOBJE.PESO
																		FROM
																			ZL.OBJEXPTO
																			LEFT JOIN ZL.OBJEXPTODET ON ZL.OBJEXPTODET.CODIGO = ZL.OBJEXPTO.CODIGO
																			INNER JOIN ZL.TIPOOBJE ON ZL.TIPOOBJE.CODIGO = ZL.OBJEXPTODET.TIPOOBJE
																		GROUP BY
																			ZL.OBJEXPTO.PUESTO
																			, ZL.TIPOOBJE.CODIGO
																			, ZL.TIPOOBJE.PESO) AS PESOS
																		GROUP BY
																			PESOS.PUESTO) AS PESOSTIPOSOBJETIVOS ON PESOSTIPOSOBJETIVOS.PUESTO = OBJETIVOS.PUESTO
				WHERE
					@FECHA BETWEEN OBJETIVOS.DESDE AND OBJETIVOS.HASTA
				ORDER BY
					OBJETIVOS.CODIGO
					, ESCALA.NITEM
					, FILTROS.NITEM;

		END
	ELSE
		BEGIN
			INSERT INTO @PUESTOS
				SELECT
					--DATOS DE CABECERA
					OBJETIVOS.CODIGO
					, RTRIM(LTRIM(OBJETIVOS.DESCRIP))
					, OBJETIVOS.DESDE
					, OBJETIVOS.HASTA
					, OBJETIVOS.PUESTO
					, RTRIM(LTRIM(PUESTOS.DESCR))
					, OBJETIVOS.SECTOR
					, OBJETIVOS.AREA
					, OBJETIVOS.REPORTAA 
					, RTRIM(LTRIM(CONVERT(VARCHAR(MAX), OBJETIVOS.ACC)))
					, RTRIM(LTRIM(CONVERT(VARCHAR(MAX), OBJETIVOS.OBS)))
					--OBJETIVOS EN DETALLE
					, DETALLE.CODOBJE
					, RTRIM(LTRIM(DETALLE.DESCOBJE))
					, DETALLE.PESOOBJE
					, DETALLE.TIPOOBJE
					, RTRIM(LTRIM(DETALLE.DESCTIPO))
					, DETALLE.PESOTIPO
					, RTRIM(LTRIM(DETALLE.COMENT))
					--ESCALA
					, ISNULL(ESCALA.DESDE, 0)
					, ISNULL(ESCALA.HASTA, 0)
					, ISNULL(ESCALA.VALOR, 0)
					--FILTROS
					, ISNULL(FILTROS.CODFILT, 0)
					, ISNULL(RTRIM(LTRIM(FILTROS.DESCFILT)), '')
					--INFO ADICIONAL
					, RTRIM(LTRIM(AREA.DESCRIP))
					, RTRIM(LTRIM(SECTORES.DESCRIP))
					, RTRIM(LTRIM(REPORTAA.DESCR))
					, SUMPESOSOBJETIVOS.SUMA
					, PESOSTIPOSOBJETIVOS.SUMA
				FROM 
					ZL.OBJEXPTO AS OBJETIVOS
					LEFT JOIN ZL.OBJEXPTODET AS DETALLE ON DETALLE.CODIGO = OBJETIVOS.CODIGO
					LEFT JOIN ZL.OBJEESVADE AS ESCALA ON ESCALA.CODIGO = OBJETIVOS.CODIGO
					LEFT JOIN ZL.FILTDET AS FILTROS ON FILTROS.CODIGO = OBJETIVOS.CODIGO
					--INFO ADICIONAL
					LEFT JOIN ZL.AREA ON AREA.CODIGO = OBJETIVOS.AREA
					LEFT JOIN ZL.SECTORES ON SECTORES.CODIGO = OBJETIVOS.SECTOR
					LEFT JOIN ZL.PUESTOSRH AS PUESTOS ON PUESTOS.COD = OBJETIVOS.PUESTO
					LEFT JOIN ZL.PUESTOSRH AS REPORTAA ON REPORTAA.COD = OBJETIVOS.REPORTAA
					
					LEFT JOIN (SELECT
									SUM(SUMAPESOSOBJETIVOS.PESO) AS SUMA
									, PUESTO
								FROM
									ZL.OBJEXPTO
									INNER JOIN ZL.OBJEXPTODET ON ZL.OBJEXPTODET.CODIGO = ZL.OBJEXPTO.CODIGO
									LEFT JOIN (SELECT PESO, COD FROM ZL.OBJET GROUP BY COD, PESO) AS SUMAPESOSOBJETIVOS ON SUMAPESOSOBJETIVOS.COD = ZL.OBJEXPTODET.CODOBJE
								GROUP BY
									ZL.OBJEXPTO.PUESTO
								) AS SUMPESOSOBJETIVOS ON SUMPESOSOBJETIVOS.PUESTO = OBJETIVOS.PUESTO
					LEFT JOIN (SELECT SUM(PESO) AS SUMA, PUESTO FROM (	SELECT
																			DISTINCT
																			ZL.OBJEXPTO.PUESTO
																			, ZL.TIPOOBJE.CODIGO
																			, ZL.TIPOOBJE.PESO
																		FROM
																			ZL.OBJEXPTO
																			LEFT JOIN ZL.OBJEXPTODET ON ZL.OBJEXPTODET.CODIGO = ZL.OBJEXPTO.CODIGO
																			INNER JOIN ZL.TIPOOBJE ON ZL.TIPOOBJE.CODIGO = ZL.OBJEXPTODET.TIPOOBJE
																		GROUP BY
																			ZL.OBJEXPTO.PUESTO
																			, ZL.TIPOOBJE.CODIGO
																			, ZL.TIPOOBJE.PESO) AS PESOS
																		GROUP BY
																			PESOS.PUESTO) AS PESOSTIPOSOBJETIVOS ON PESOSTIPOSOBJETIVOS.PUESTO = OBJETIVOS.PUESTO
				WHERE
					@FECHA BETWEEN OBJETIVOS.DESDE AND OBJETIVOS.HASTA
					AND OBJETIVOS.PUESTO IN (@PUESTO)
				ORDER BY
					OBJETIVOS.CODIGO
					, ESCALA.NITEM
					, FILTROS.NITEM;
		END
	RETURN	
END




GO


