USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[func_CalculodeObjetivosxLegajo]    Script Date: 04/22/2013 15:15:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[func_CalculodeObjetivosxLegajo]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Objetivos].[func_CalculodeObjetivosxLegajo]
GO

USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[func_CalculodeObjetivosxLegajo]    Script Date: 04/22/2013 15:15:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Hector Daniel Correa
-- Create date: 22-04-2013
-- Description:	Función que devuelve un recordset con todos
--              los objetivos individuales calculados para todos
--              los legajos que tengan objeivos por puesto
-- =============================================
CREATE FUNCTION [Objetivos].[func_CalculodeObjetivosxLegajo]
(
	@FECHA DATETIME = GETDATE, 
	@LEGAJO VARCHAR(4) = ''
)
RETURNS 
@DETALLE TABLE (
	ID INT 
	, CodLegajo VARCHAR(25)
	, Legajo VARCHAR(4)
	, Nombre VARCHAR(151)
	, CodPuesto VARCHAR(4)
	, Puesto VARCHAR(60) 
	, FechaInicio DATETIME
	, FechaFinal DATETIME
	, CodArea VARCHAR(4)
	, Area VARCHAR(60)
	, CodSector VARCHAR(4)
	, Sector VARCHAR(60)
	, CodObjetivo INT
	, Objetivo VARCHAR(100)
	, PesoObjetivo NUMERIC(10,5)
	, TipoObjetivo INT
	, OBSQLOBJE NVARCHAR(MAX)
	, ROBSQLOBJE NUMERIC(10,5)
	, EscObjeDesde NUMERIC(10,5)
	, EscObjeHasta NUMERIC(10,5)
	, EscObjeValor NUMERIC(10,5)
	, CodTipoObjetivo INT
	, DescrTipoObjetivo VARCHAR(60)
	, PesoTipoObjetivo NUMERIC(10,5)
	, PesoRelObjetivo NUMERIC(10,5)
	, ValorFinalObjetivo NUMERIC(10,5)
	, CodFiltro INT
	, Filtro VARCHAR(100)
	, OBSQLFILT NVARCHAR(MAX)
	, ROBSQLFILT NUMERIC(10,5)
	, EscFiltroDesde NUMERIC(10,5)
	, EscFiltroHasta NUMERIC(10,5)
	, EscFiltroValor NUMERIC(10,5)
	, PesoRelFiltro NUMERIC(10,5)
	--OBJETIVO POR PUESTO
	, ObjexPuestoCod INT 
	, ObjexPuestodesc VARCHAR(MAX) 
	, ObjexPuestodesde DATETIME 
	, ObjexPuestoHasta DATETIME
)
AS
BEGIN
	DECLARE 
		@ID AS INT
		, @OBSQLOBJE AS NVARCHAR(MAX)
		, @OBSQLFILT AS NVARCHAR(MAX)
		, @PesoObjetivo AS NUMERIC(10,5)
		, @PesoTipoObjetivo AS NUMERIC(10,5)
		, @tmpValor AS NUMERIC(10,5);

	-- CREAMOS UN TABLA TEMPORAL VARIABLE PARA LAS OPERACIONES DE CLACULO
	DECLARE @OBJETIVOS TABLE (
		ID INT IDENTITY PRIMARY KEY
		, CodLegajo VARCHAR(25)
		, Legajo VARCHAR(4)
		, Nombre VARCHAR(151)
		, CodPuesto VARCHAR(4)
		, Puesto VARCHAR(60) 
		, FechaInicio DATETIME
		, FechaFinal DATETIME
		, CodArea VARCHAR(4)
		, Area VARCHAR(60)
		, CodSector VARCHAR(4)
		, Sector VARCHAR(60)
		, CodObjetivo INT
		, Objetivo VARCHAR(100)
		, PesoObjetivo NUMERIC(10,5)
		, TipoObjetivo INT
		, OBSQLOBJE NVARCHAR(MAX)
		, ROBSQLOBJE NUMERIC(10,5)
		, EscObjeDesde NUMERIC(10,5)
		, EscObjeHasta NUMERIC(10,5)
		, EscObjeValor NUMERIC(10,5)
		, CodTipoObjetivo INT
		, DescrTipoObjetivo VARCHAR(60)
		, PesoTipoObjetivo NUMERIC(10,5)
		, PesoRelObjetivo NUMERIC(10,5)
		, ValorFinalObjetivo NUMERIC(10,5)
		, CodFiltro INT
		, Filtro VARCHAR(100)
		, OBSQLFILT NVARCHAR(MAX)
		, ROBSQLFILT NUMERIC(10,5)
		, EscFiltroDesde NUMERIC(10,5)
		, EscFiltroHasta NUMERIC(10,5)
		, EscFiltroValor NUMERIC(10,5)
		, PesoRelFiltro NUMERIC(10,5)
		--OBJETIVO POR PUESTO
		, ObjexPuestoCod INT 
		, ObjexPuestodesc VARCHAR(MAX) 
		, ObjexPuestodesde DATETIME 
		, ObjexPuestoHasta DATETIME
	);
	IF @LEGAJO <> ''
	BEGIN
		INSERT INTO @OBJETIVOS
			SELECT 
				LEGAJOS.CCOD
				, LEGAJOS.CLEGAJO
				, LEGAJOS.CCORTESIA
				, CARRERA.CPUESTO
				, PUESTO.DESCR
				, CARRERA.FINICIO
				, CARRERA.FFIN
				, PUESTO.AREA
				, AREAS.DESCRIP
				, AREAS.SECTOR
				, SECTOR.DESCRIP
				--OBJETIVOS DEL PUESTO
				, OBJETIVO.COD
				, OBJETIVO.DESCR
				, OBJETIVO.PESO
				, ISNULL(OBJETIVO.TIPO, 0)
				, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL)
				, 0.00
				, ISNULL(ESCOBJETIVO.DESDE, 0)
				, ISNULL(ESCOBJETIVO.HASTA, 0)
				, ESCOBJETIVO.VALOR
				, TIPOS.CODIGO
				, TIPOS.DESCRIP
				, TIPOS.PESO
				, 0.00
				, 0.00
				--FILTROS DEL PUESTO
				, FILTROS.COD
				, FILTROS.DESCRIP
				, CONVERT(NVARCHAR(MAX), FILTROS.OBSQL)
				, 0.00
				, ISNULL(ESCFILTRO.DESDE, 0)
				, ISNULL(ESCFILTRO.HASTA, 0)
				, ISNULL(ESCFILTRO.VALOR, 0)
				, 0.00
				--OBJETIVO POR PUESTO
				, OBJINDIVIDUALES.CODIGO
				, OBJINDIVIDUALES.DESCRIP
				, OBJINDIVIDUALES.DESDE
				, OBJINDIVIDUALES.HASTA
			FROM 
				ZL.ZL.LEGOPS AS LEGAJOS
				LEFT JOIN ZL.ZL.CARRZL AS CARRERA ON CARRERA.CCOD = LEGAJOS.CLEGAJO
					AND ISNULL(CARRERA.CPUESTO, '') <> ''
				LEFT JOIN ZL.ZL.PUESTOSRH AS PUESTO ON PUESTO.COD = CARRERA.CPUESTO
				LEFT JOIN ZL.ZL.AREA AS AREAS ON AREAS.CODIGO = PUESTO.AREA
				LEFT JOIN ZL.ZL.SECTORES AS SECTOR ON SECTOR.CODIGO = AREAS.SECTOR  
				--OBJETIVOS POR PUESTO
				LEFT JOIN ZL.ZL.OBJEXPTO AS OBJINDIVIDUALES ON OBJINDIVIDUALES.PUESTO = PUESTO.COD
					AND @FECHA BETWEEN OBJINDIVIDUALES.DESDE AND OBJINDIVIDUALES.HASTA
				LEFT JOIN ZL.ZL.OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJINDIVIDUALES.CODIGO
				-- DETALLES DE CADA OBJETIVO
				LEFT JOIN ZL.ZL.OBJET AS OBJETIVO ON OBJETIVO.COD = OBJETIVOS.CODOBJE 
				LEFT JOIN ZL.ZL.OBJETDET AS ESCOBJETIVO ON ESCOBJETIVO.NUMERO = OBJETIVO.COD
				LEFT JOIN ZL.ZL.TIPOOBJE AS TIPOS ON TIPOS.CODIGO = OBJETIVO.TIPO 
				--FILTROS POR PUESTO
				LEFT JOIN ZL.ZL.FILTOBJE AS FILTROS ON FILTROS.PUESTO = OBJINDIVIDUALES.PUESTO
				LEFT JOIN ZL.ZL.FILTOBJEDET AS ESCFILTRO ON ESCFILTRO.NUMERO = FILTROS.COD 
			WHERE
				LEGAJOS.CLEGAJO = @LEGAJO;
	END
	ELSE
	BEGIN
		INSERT INTO @OBJETIVOS
			SELECT 
				LEGAJOS.CCOD
				, LEGAJOS.CLEGAJO
				, LEGAJOS.CCORTESIA
				, CARRERA.CPUESTO
				, PUESTO.DESCR
				, CARRERA.FINICIO
				, CARRERA.FFIN
				, PUESTO.AREA
				, AREAS.DESCRIP
				, AREAS.SECTOR
				, SECTOR.DESCRIP
				--OBJETIVOS DEL PUESTO
				, OBJETIVO.COD
				, OBJETIVO.DESCR
				, OBJETIVO.PESO
				, ISNULL(OBJETIVO.TIPO, 0)
				, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL)
				, 0.00
				, ISNULL(ESCOBJETIVO.DESDE, 0)
				, ISNULL(ESCOBJETIVO.HASTA, 0)
				, ESCOBJETIVO.VALOR
				, TIPOS.CODIGO
				, TIPOS.DESCRIP
				, TIPOS.PESO
				, 0.00
				, 0.00
				--FILTROS DEL PUESTO
				, FILTROS.COD
				, FILTROS.DESCRIP
				, CONVERT(NVARCHAR(MAX), FILTROS.OBSQL)
				, 0.00
				, ISNULL(ESCFILTRO.DESDE, 0)
				, ISNULL(ESCFILTRO.HASTA, 0)
				, ISNULL(ESCFILTRO.VALOR, 0)
				, 0.00
				--OBJETIVO POR PUESTO
				, OBJINDIVIDUALES.CODIGO
				, OBJINDIVIDUALES.DESCRIP
				, OBJINDIVIDUALES.DESDE
				, OBJINDIVIDUALES.HASTA
			FROM 
				ZL.ZL.LEGOPS AS LEGAJOS
				LEFT JOIN ZL.ZL.CARRZL AS CARRERA ON CARRERA.CCOD = LEGAJOS.CLEGAJO
					AND ISNULL(CARRERA.CPUESTO, '') <> ''
				LEFT JOIN ZL.ZL.PUESTOSRH AS PUESTO ON PUESTO.COD = CARRERA.CPUESTO
				LEFT JOIN ZL.ZL.AREA AS AREAS ON AREAS.CODIGO = PUESTO.AREA
				LEFT JOIN ZL.ZL.SECTORES AS SECTOR ON SECTOR.CODIGO = AREAS.SECTOR  
				--OBJETIVOS POR PUESTO
				LEFT JOIN ZL.ZL.OBJEXPTO AS OBJINDIVIDUALES ON OBJINDIVIDUALES.PUESTO = PUESTO.COD
					AND @FECHA BETWEEN OBJINDIVIDUALES.DESDE AND OBJINDIVIDUALES.HASTA
				LEFT JOIN ZL.ZL.OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJINDIVIDUALES.CODIGO
				-- DETALLES DE CADA OBJETIVO
				LEFT JOIN ZL.ZL.OBJET AS OBJETIVO ON OBJETIVO.COD = OBJETIVOS.CODOBJE 
				LEFT JOIN ZL.ZL.OBJETDET AS ESCOBJETIVO ON ESCOBJETIVO.NUMERO = OBJETIVO.COD
				LEFT JOIN ZL.ZL.TIPOOBJE AS TIPOS ON TIPOS.CODIGO = OBJETIVO.TIPO 
				--FILTROS POR PUESTO
				LEFT JOIN ZL.ZL.FILTOBJE AS FILTROS ON FILTROS.PUESTO = OBJINDIVIDUALES.PUESTO
				LEFT JOIN ZL.ZL.FILTOBJEDET AS ESCFILTRO ON ESCFILTRO.NUMERO = FILTROS.COD 
	END
	--CREAMOS UN CURSOR PARA RECORRER Y AGREGAR Y MODIFICAR DATOS COMO PESO Y RESULTADO DE LOS OBJETOS SQL
	DECLARE DETALLE CURSOR FOR SELECT ID, OBSQLOBJE, OBSQLFILT FROM @OBJETIVOS;
	OPEN DETALLE;
	FETCH NEXT FROM DETALLE INTO @ID, @OBSQLOBJE, @OBSQLFILT;
	CREATE TABLE [Objetivos].VALOR(
		ID INT
		, OBSQLOBJE NVARCHAR(MAX)
		, OBSQLFILT NVARCHAR(MAX)
		, VALOR NUMERIC(10, 5));
	--CREATE TABLE #VALOR (VALOR NUMERIC(10, 5));
	--DELETE FROM [Objetivos].valor;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		INSERT INTO [Objetivos].VALOR(ID, OBSQLOBJE, OBSQLFILT, VALOR) VALUES (@ID, @OBSQLOBJE, @OBSQLFILT, 0.00);
		--SET @OBSQLOBJE = CONVERT(NVARCHAR(MAX), 'sp_devolverOBSQL'+@OBSQLOBJE);

		--INSERT INTO [Objetivos].valor EXEC sp_executesql @OBSQLOBJE;
		--UPDATE @OBJETIVOS SET ROBSQLOBJE = (SELECT * FROM [zl].[Objetivos].valor) WHERE ID = @ID;

		--SET @OBSQLFILT = CONVERT(NVARCHAR(MAX), 'sp_devolverOBSQL'+@OBSQLFILT);
		--EXEC sp_executesql @OBSQLFILT;

		--UPDATE @OBJETIVOS SET ROBSQLFILT = (SELECT * FROM [zl].[Objetivos].valor) WHERE ID = @ID;

		--SELECT @tmpValor = EscObjeValor FROM @OBJETIVOS WHERE ROBSQLOBJE >= EscObjeDesde AND ROBSQLOBJE <= EscObjeHasta AND ID = @ID
		--UPDATE @OBJETIVOS SET EscObjeValor = ISNULL(@tmpValor, 0) WHERE ID = @ID

		--SELECT @tmpValor = EscFiltroValor FROM @OBJETIVOS WHERE ROBSQLFILT >= EscFiltroDesde AND ROBSQLFILT <= EscFiltroHasta AND ID = @ID
		--UPDATE @OBJETIVOS SET EscFiltroValor = ISNULL(@tmpValor, 0) WHERE ID = @ID

		--SELECT @tmpValor = (SELECT EscObjeValor * PesoObjetivo FROM @OBJETIVOS WHERE ID = @ID AND ROBSQLOBJE >= EscObjeDesde AND ROBSQLOBJE <= EscObjeHasta)
		--UPDATE @OBJETIVOS SET PesoRelObjetivo = ISNULL(@tmpValor, 0) WHERE ID = @ID
		--SET @tmpValor = 0;

		--SELECT @tmpValor = (SELECT PesoRelObjetivo * PesoTipoObjetivo FROM @OBJETIVOS WHERE ID = @ID AND ROBSQLOBJE >= EscObjeDesde AND ROBSQLOBJE <= EscObjeHasta)
		--UPDATE @OBJETIVOS SET ValorFinalObjetivo = ISNULL(@tmpValor, 0) WHERE ID = @ID
		--SET @tmpValor = 0;

		--SELECT @tmpValor = (SELECT EscFiltroValor * ROBSQLFILT FROM @OBJETIVOS WHERE ID = @ID AND ROBSQLFILT >= EscFiltroDesde AND ROBSQLFILT <= EscFiltroHasta)
		--UPDATE @OBJETIVOS SET PesoRelFiltro = ISNULL(@tmpValor, 0) WHERE ID = @ID

		SET @tmpValor = 0;
		SET @ID = NULL;
		SET @OBSQLOBJE = NULL;
		SET @OBSQLFILT = NULL;
		FETCH NEXT FROM DETALLE INTO @ID, @OBSQLOBJE, @OBSQLFILT;
	END
	EXEC sp_executesql 'sp_devolverOBSQL';
	INSERT INTO @DETALLE
	SELECT 
		--DISTINCT 
		* 
	FROM 
		@OBJETIVOS 
	WHERE 
		(ValorFinalObjetivo <> 0 
		OR PesoRelFiltro <> 0)
		AND (EscObjeDesde < ROBSQLOBJE AND EscObjeHasta >= ROBSQLOBJE)
		AND (EscFiltroDesde < ROBSQLFILT AND EscFiltroHasta >= ROBSQLFILT);

	CLOSE DETALLE;
	DEALLOCATE DETALLE;
	RETURN 
END
GO

SELECT * FROM [Objetivos].func_CalculodeObjetivosxLegajo('04-22-2013', '')
go