USE [ZL]
GO

/****** OBJECT:  USERDEFINEDFUNCTION [OBJETIVOS].[GradoDeServicio]    SCRIPT DATE: 05/02/2013 11:41:40 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[OBJETIVOS].[GradoDeServicio]') AND TYPE IN (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [OBJETIVOS].GradoDeServicio
GO

USE [ZL]
GO

/****** OBJECT:  USERDEFINEDFUNCTION [OBJETIVOS].[GradoDeServicio]    SCRIPT DATE: 05/02/2013 11:41:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE FUNCTION [OBJETIVOS].[GradoDeServicio] 
(	@FECHAINICIO AS DATETIME,
	@FECHAFIN AS DATETIME )
  
  RETURNS @GradoDeServicio TABLE (
		VALOR NUMERIC(10,4)
	)
AS
BEGIN
	INSERT INTO @GradoDeServicio	
	SELECT
		ROUND((CONVERT(NUMERIC(10,2), SUM([LLAMADAS ATENDIDAS EN 60]))/(SUM([LLAMADAS ATENDIDAS])+SUM([LLAMADAS PERDIDAS]))), 4) VALOR
	FROM
		TECNOVOZ.DBO.VISTAACD
	WHERE
		[LLAMADAS EXTERNAS] = 1
		AND [AÑO] BETWEEN YEAR(@FechaInicio) AND YEAR(@FechaFin)
		AND [MES] BETWEEN MONTH (@FechaInicio) AND MONTH (@FechaFin)

RETURN

END


GO


