
BEGIN TRANSACTION;

UPDATE ZL.NUMERACIONES WITH (ROWLOCK) SET NUMERO = 0 WHERE ENTIDAD = 'RRHHFICHARENNOMBREDE';

TRUNCATE TABLE [ZL].[FICHNOMDE];

DECLARE @COMPTES INT;
SELECT @COMPTES = NUMERO FROM ZL.NUMERACIONES WITH (ROWLOCK) WHERE ENTIDAD = 'RRHHFICHARENNOMBREDE';

INSERT INTO [ZL].[ZL].[FICHNOMDE] (
	[BDALTAFW]
	,[BDMODIFW]
	,[CAPENOM]
	,[COD]
	,[ESTTRANS]
	,[FALTAFW]
	,[FCHREG]
	,[FECEXPO]
	,[FECHREG]
	,[FECIMPO]
	,[FECTRANS]
	,[FMODIFW]
	,[HALTAFW]
	,[HHREG]
	,[HHSSREG]
	,[HMODIFW]
	,[HORAEXPO]
	,[HORAIMPO]
	,[LEGAJO]
	,[MOT]
	,[OBS]
	,[REGPOR]
) 
SELECT
	 'ZNUBE' AS BDALTAFW
	, '' AS BDMODIFW
	, LTRIM(RTRIM(B.LASTNAME)) + ' ' + LTRIM(RTRIM(B.SURNAME)) AS CAPENOM
	, (ROW_NUMBER() OVER (ORDER BY [ENNOMBREDE].[DATE] ASC))+@COMPTES AS COD
	, '' AS ESTTRANS
	, GETDATE() AS FALTAFW
	, [ENNOMBREDE].[DATE] AS FCHREG
	, CONVERT(DATETIME, 0, 102) AS FECEXPO
	, [ENNOMBREDE].[DATE] AS FECHREG
	, GETDATE() AS FECIMPO
	, CONVERT(DATETIME, 0, 102) AS FECTRANS
	, NULL AS FMODIFW
	, NULL AS HALTAFW
	, CONVERT(VARCHAR(8), A.[DATE], 108) AS HHREG
	, CONVERT(VARCHAR(8), [ENNOMBREDE].[DATE], 108) AS HHSSREG
	, CONVERT(VARCHAR(8), [ENNOMBREDE].[DATE], 108) AS HMODIFW
	, NULL AS HORAEXPO
	, CONVERT(VARCHAR(8), GETDATE(), 108) AS HORAIMPO
	, LEFT(LTRIM(B.IDPROFILE), 4) AS LEGAJO
	, NULL AS MOT /*motivo para probar*/
 	, convert(varchar(255), [ENNOMBREDE].[OBSERVATIONS]) AS OBS
	, left(USUARIOS.USERNAME, 25) AS REGPOR
FROM 
	ZNUBE_HUB01.[D1ADA87A-240B-46D6-966E-5D493172F723_TM].[DBO].[EVENTONBEHALF] AS [ENNOMBREDE]
	LEFT JOIN ZNUBE_HUB01.[D1ADA87A-240B-46D6-966E-5D493172F723_TM].DBO.[EVENT] AS A ON A.ID = [ENNOMBREDE].ID
	LEFT JOIN ZNUBE_HUB01.[D1ADA87A-240B-46D6-966E-5D493172F723_TM].DBO.[PROFILE] AS B ON B.ID = A.IDPROFILE
	LEFT JOIN ZNUBE_HUB01.ZNUBE.DBO.[USER] AS USUARIOS ON USUARIOS.USERID = [ENNOMBREDE].[USERID]
	LEFT JOIN [ZNUBE_HUB01].[D1ADA87A-240B-46D6-966E-5D493172F723_TM].[DBO].[CONNECTIONSTATUS] AS STAT ON STAT.ID = A.[CONNECTIONSTATUS]
ORDER BY
	[ENNOMBREDE].[DATE] ASC

	--rollback
	
	UPDATE ZL.NUMERACIONES SET NUMERO = (SELECT MAX(COD) FROM ZL.FICHNOMDE) WHERE ENTIDAD = 'RRHHFICHARENNOMBREDE';
	COMMIT TRANSACTION;
GO

--SELECT * FROM [ZL].[ZL].[FICHNOMDE]

--select * from [ZNUBE_HUB01].[D1ADA87A-240B-46D6-966E-5D493172F723_TM].[DBO].[CONNECTIONSTATUS]