SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =================================================
-- Author:		HECTOR DANIEL CORREA
-- Create date: 11-06-2013
-- Description:	HERRAMIENTA DE MIGRACION DE FICHAJES
--              DE ZNUBE A ZL
-- =================================================
CREATE PROCEDURE stp_MigracionFichajes
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [ZL].[ZNFICHAJE] (
		[BDALTAFW]
		, [BDMODIFW]
		, [CAPENOM]
		, [COD]
		, [ESTCONEX]
		, [ESTTRANS]
		, [FALTAFW]
		, [FCHREG]
		, [FECEXPO]
		, [FECIMPO]
		, [FECTRANS]
		, [FMODIFW]
		, [HALTAFW]
		, [HMODIFW]
		, [HORAEXPO]
		, [HORAIMPO]
		, [LEGAJO] --ESTE CAMPO ES VARCHAR(4)
		, [OBS]
		, [PCONTROL]
		, [SALTAFW]
		, [SMODIFW]
		, [UALTAFW]
		, [UMODIFW]
		, [VALTAFW]
		, [VMODIFW]
		, [HORAREG]
		, [CODZNUBE]
		, [CODPUESTO]
		) 
	SELECT 
		'ZL' [BDALTAFW]
		, 'ZL' [BDMODIFW]
		, CONVERT(VARCHAR(80), LTRIM(RTRIM([PROFILES].[LASTNAME]))+' '+LTRIM(RTRIM([PROFILES].[SURNAME]))) [CAPENOM]
		, CONVERT(UNIQUEIDENTIFIER, [EVENTS].ID) [COD]
		, [EVENTS].[CONNECTIONSTATUS] [ESTCONEX]
		, CONVERT(VARCHAR(20), [CONNECTIONSTATUS].[CONNECTIONSTATUS]) [ESTRANS]
		, GETDATE() [FALTAFW]
		, [EVENTS].[DATE] [FCHREG]
		, GETDATE() [FECEXPO]
		, GETDATE() [FECIMPO]
		, GETDATE() [FECTRANS]
		, GETDATE() [FMODIFW]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HALTAFW]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HMODIFW]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HORAEXPO]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HORAIMPO]
		, CONVERT(VARCHAR(4), LTRIM(RTRIM([PROFILES].[IDPROFILE]))) [LEGAJO]
		, CONVERT(TEXT, 'Migración ZNube->DataWeb / Automático desde SP') [OBS]
		, [ZNPCONTROL].[COD] AS [PCONTROL]
		, 'ZL' [SALTAFW]
		, 'ZL' [SMODIFW]
		, 'ZL' [UALTAFW]
		, 'ZL' [UMODIFW]
		, 'ZL' [VALTAFW]
		, 'ZL' [VMODIFW]
		, CONVERT(VARCHAR(8), [EVENTS].[DATE], 108) [HORAREG]
		, [EVENTS].[APPLICATIONVALIDATORID]
		, (SELECT CODPUESTO FROM [Objetivos].[func_RRHH_UpdateFichaje](CONVERT(VARCHAR(4), LTRIM(RTRIM([PROFILES].[IDPROFILE]))), GETDATE()))
	FROM 
		[zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[EVENT] AS [EVENTS]
		LEFT JOIN [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[Profile] AS [PROFILES] ON [PROFILES].[Id] = [EVENTS].[IDPROFILE]
		LEFT JOIN [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[ConnectionStatus] AS [CONNECTIONSTATUS] ON
			 [CONNECTIONSTATUS].[ID] = [EVENTS].[CONNECTIONSTATUS]
		LEFT JOIN [zNube_Hub01].[D1ADA87A-240B-46D6-966E-5D493172F723_TM].[DBO].[APPLICATIONVALIDATOR] AS [PCONTROL] ON [PCONTROL].[ID] = [EVENTS].[APPLICATIONVALIDATORID]
		LEFT JOIN [ZL].[ZNPCONTROL] ON [ZL].[ZNPCONTROL].[CODZNUBE] = [EVENTS].[APPLICATIONVALIDATORID]
	ORDER BY
		[EVENTS].[DATE];
	
	
END
GO
/*
truncate table [ZL].[ZNFICHAJE]
go
exec stp_MigracionFichajes
go
*/