USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[MonitoreosDeCalidad]    Script Date: 05/02/2013 12:17:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[MonitoreosDeCalidad]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Objetivos].[MonitoreosDeCalidad]
GO

USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[MonitoreosDeCalidad]    Script Date: 05/02/2013 12:17:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE FUNCTION [Objetivos].[MonitoreosDeCalidad] 
(	@LEGAJO AS VARCHAR(4), 
	@FECHAINICIO AS DATETIME,
	@FECHAFIN AS DATETIME )
  
  RETURNS @LLAMADASNOATENDIDAS TABLE (
		VALOR NUMERIC(10,4)
	)
AS
BEGIN
	INSERT INTO @LLAMADASNOATENDIDAS	
	SELECT
		AVG([QUERY].[VALOR]) AS [VALOR]
	FROM
		(SELECT
			SUM( CUENTAXGRUPO ) AS [VALOR]
		 FROM
			(SELECT
				(( SUM((CAST (LTRIM(RTRIM(REPLACE(ZL.DREGESC.PESO, ',', '.'))) AS NUMERIC(5,2)) * CAST (LTRIM(RTRIM(ZL.DREGESC.PUNTA)) AS INT)  )/5 )
				/SUM(CAST (LTRIM(RTRIM(REPLACE(ZL.DREGESC.PESO, ',', '.'))) AS NUMERIC(5,2)) ))
				* (CAST (LTRIM(RTRIM(REPLACE(ZL.GREVESMA.PESO, ',', '.'))) AS NUMERIC(5,2)) )) AS [CUENTAXGRUPO]
				FROM
					ZL.REGESC
					INNER JOIN ZL.DREGESC ON ZL.REGESC.CODIN = ZL.DREGESC.CNUMERO
					INNER JOIN ZL.ITEVESMA INNER JOIN ZL.GREVESMA ON ZL.ITEVESMA.GRUPO = ZL.GREVESMA.CCOD ON ZL.DREGESC.CTIPCONT = ZL.ITEVESMA.CCOD
					INNER JOIN ZL.ZL.LEGOPS L ON L.CCOD = REGESC.INREGPOR
				WHERE
					(ZL.REGESC.INFECINI BETWEEN @FECHAINICIO AND @FECHAFIN)
					AND L.CLEGAJO = @LEGAJO
				GROUP BY
					ZL.ITEVESMA.GRUPO
					, (CAST(LTRIM(RTRIM(REPLACE(ZL.GREVESMA.PESO, ',', '.'))) AS NUMERIC(5,2)))) AS [VALORESDESGLOSEXGRUPO]) AS [QUERY]		

RETURN

END



GO


