USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[PorcentajeLlamadasNoAtendidas]    Script Date: 05/02/2013 11:57:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[PorcentajeLlamadasNoAtendidas]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Objetivos].[PorcentajeLlamadasNoAtendidas]
GO

USE [ZL]
GO

/****** Object:  UserDefinedFunction [Objetivos].[PorcentajeLlamadasNoAtendidas]    Script Date: 05/02/2013 11:57:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE FUNCTION [Objetivos].[PorcentajeLlamadasNoAtendidas] 
(	@LEGAJO AS VARCHAR(4), 
	@FECHAINICIO AS DATETIME,
	@FECHAFIN AS DATETIME )
  
  RETURNS @LLAMADASNOATENDIDAS TABLE (
		VALOR NUMERIC(10,4)
	)
AS
BEGIN
	INSERT INTO @LLAMADASNOATENDIDAS	
	SELECT
		(SUM(CONVERT(NUMERIC(10,4), CONVERT(INT, [TECNOVOZ].[DBO].[SESSION].[CANTIDAD DE LLAMADAS NO RESPONDIDAS]))))
		/(SUM(CONVERT(NUMERIC(10,4), CONVERT(INT, [TECNOVOZ].[DBO].[SESSION].[CANTIDAD DE LLAMADAS ATENDIDAS]))))
	FROM
		[ZL].[ZL].[LEUSTEV]
		INNER JOIN [TECNOVOZ].[DBO].[SESSION] ON [TECNOVOZ].[DBO].[SESSION].[NOMBRE DEL AGENTE] = [ZL].[ZL].[LEUSTEV].[USTECNO]
		INNER JOIN [ZL].[ZL].[LEGOPS] ON [ZL].[ZL].[LEGOPS].[CCOD] = [ZL].[ZL].[LEUSTEV].[DUENO]
			AND [ZL].[ZL].[LEGOPS].[CLEGAJO] = @LEGAJO
	WHERE
		[TECNOVOZ].[DBO].[SESSION].[FECHA DE LOGIN] BETWEEN CONVERT (NVARCHAR(50), @FECHAINICIO, 112) AND CONVERT (NVARCHAR(50), @FECHAFIN, 112);
		

RETURN

END



GO


