DECLARE @FechaInicio datetime, @FechaFin datetime, @Legajo varchar(25);
SET @FechaInicio = '20110401';
SET @FechaFin = GETDATE();
SET @Legajo = '0091';


SELECT 
	(SUM(CONVERT(NUMERIC(10,4), CONVERT(INT, [SESSION].[CANTIDAD DE LLAMADAS NO RESPONDIDAS]))))
	/(SUM(CONVERT(NUMERIC(10,4), CONVERT(INT, [SESSION].[Cantidad de llamadas atendidas]))))
FROM 
	ZL.ZL.LEUSTEV
	INNER JOIN [SESSION] ON [SESSION].[Nombre del agente] = ZL.ZL.LEUSTEV.USTECNO
	INNER JOIN ZL.ZL.LEGOPS ON ZL.ZL.LEGOPS.CCOD = ZL.ZL.LEUSTEV.DUENO
		AND ZL.ZL.LEGOPS.CLEGAJO = @Legajo
WHERE 
	[SESSION].[FECHA DE LOGIN] BETWEEN CONVERT (NVARCHAR(50), @FechaInicio, 112) AND CONVERT (NVARCHAR(50), @FechaFin, 112);
