DECLARE @LEGAJO AS VARCHAR(4), 
	@FECHAINICIO AS DATETIME,
	@FECHAFIN AS DATETIME
	
SET @LEGAJO = '0091'
SET @FECHAINICIO = '20110401'
SET @FECHAFIN = GETDATE()

SELECT 
	AVG(VALOR) AS VALOR
FROM  
	(SELECT 
		SUM( CUENTAXGRUPO ) AS VALOR
	 FROM 
		(SELECT 
			(( SUM((CAST (LTRIM(RTRIM(REPLACE(ZL.DREGESC.PESO, CHAR(44),CHAR(46)))) AS NUMERIC(5,2)) * CAST (LTRIM(RTRIM(ZL.DREGESC.PUNTA)) AS INT)  )/5 )
			/SUM(CAST (LTRIM(RTRIM(REPLACE(ZL.DREGESC.PESO, CHAR(44),CHAR(46)))) AS NUMERIC(5,2)) ))
			* (CAST (LTRIM(RTRIM(REPLACE(ZL.GREVESMA.PESO, CHAR(44),CHAR(46)))) AS NUMERIC(5,2)) )) AS CUENTAXGRUPO
			FROM 
				ZL.REGESC
				INNER JOIN ZL.DREGESC ON ZL.REGESC.CODIN = ZL.DREGESC.CNUMERO
				INNER JOIN ZL.ITEVESMA INNER JOIN ZL.GREVESMA ON ZL.ITEVESMA.GRUPO = ZL.GREVESMA.CCOD ON ZL.DREGESC.CTIPCONT = ZL.ITEVESMA.CCOD
				INNER JOIN ZL.ZL.LEGOPS L ON L.CCOD = REGESC.INREGPOR
			WHERE 
				(ZL.REGESC.INFECINI BETWEEN @FECHAINICIO AND @FECHAFIN) 
				AND L.CLEGAJO = @LEGAJO
			GROUP BY      
				ZL.ITEVESMA.GRUPO
				, (CAST(LTRIM(RTRIM(REPLACE(ZL.GREVESMA.PESO, CHAR(44),CHAR(46)))) AS NUMERIC(5,2)))) AS VALORESDESGLOSEXGRUPO) AS QUERY