SELECT 
	LTRIM(RTRIM(M.EMAIL)) AS EMAIL
	, M.TIPO
	, TIPMAIL.DESCR AS TIPODESCRIPCION
	, ULTASIGNA.ASIGNACION
	, M.CONTACTO
	, C.CCLIENTE AS CLIENTE
	, ULTASIGNA.RZCOD
	, ULTASIGNA.TIPOACCION
	, ULTASIGNA.TIPOACCIONDESCRIPCION
FROM 
	ZL.MAILS AS M
	JOIN ZL.CONTACT AS C ON M.CONTACTO = C.CODIGO
	LEFT JOIN ZL.TIPMAI AS TIPMAIL ON M.TIPO = TIPMAIL.CCOD
	LEFT JOIN ( SELECT 
					LTRIM(RTRIM(A.EMAIL)) AS EMAIL
					, A.RZCOD,A.ACCMAIL AS TIPOACCION
					, ACC.DESCR AS TIPOACCIONDESCRIPCION
					, A.NUMERO AS ASIGNACION 
				FROM  
					ZL.ASESRZMAIL  AS A 
					JOIN (	SELECT  
								MAX(NUMERO) AS NUMERO 
							FROM 
								ZL.ASESRZMAIL 
							GROUP BY 
								EMAIL
								, ACCMAIL
								, RZCOD) AS U ON U.NUMERO = A.NUMERO 
					LEFT JOIN ZL.ACCMAIL AS ACC ON ACC.CCOD = A.ACCMAIL
				WHERE 
					A.ACCION = 1) AS ULTASIGNA ON ULTASIGNA.EMAIL = LTRIM(RTRIM(M.EMAIL)) 
where cliente = '00133'
go

select * from zl.vmails where cliente = '00133'
go
--select * from zl.vmailsfacturacion where cliente = '00133'
go