USE ZL
SELECT
	distinct
	HS.NUME [HS NÚMERO]
	, MAILS.EMAIL [MAIL]
	, 'hcorrea@zoologic.com.ar' AS [mailPrueba]
	, 'sdisanzo@zoolgic.com.ar' AS [mailAuditor]
FROM 
	ZL.DACMDA AS ACCIONES
	INNER JOIN ZL.HOJSERV AS HS ON HS.NUME = ACCIONES.CODIGO
	INNER JOIN ZL.CLIENTES AS CLIENTES ON CLIENTES.CMPCODIGO = HS.CCLIENTE
	INNER JOIN ZL.VMAILS AS MAILS ON MAILS.CLIENTE = CLIENTES.CMPCODIGO
		AND MAILS.TIPOACCION IN (1, 6)
WHERE
	ACCIONES.TACCIO = '0012'
	AND CONVERT(DATETIME, CONVERT(VARCHAR(10), ACCIONES.FECHA, 120)+' '+CONVERT(VARCHAR(10), ACCIONES.HORA, 120), 120)
		BETWEEN DATEADD(DAY, 0, CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 120)+' 12:00:00.000', 120))
		AND DATEADD(DAY, 0, CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 120)+' 17:59:59.999', 120))
GROUP BY
	MAILS.EMAIL
	, HS.CCLIENTE
	, HS.NUME
	, ACCIONES.FECHA
	, ACCIONES.HORA
	
----SELECT * FROM 
--	ZL.DACMDA 
----WHERE
----	ZL.DACMDA.TACCIO = '0012'
--ORDER BY FECHA DESC
----SELECT * FROM ZL.VMAILS