/**********************************************************************************************************************
*                                                                                                                     *
*                                                 ARMAMOS TODOS LOS FILTROS                                           *
*                                        PARA PODER EJECUTAR EL QUERY FUERA DEL REPORTE                               *
*                                                                                                                     *
**********************************************************************************************************************/
DECLARE @FechaDesde AS DATETIME
        ,@FechaHasta  AS DATETIME
        ,@FechaEstadoDesde  AS DATETIME
        ,@FechaEstadoHasta  AS DATETIME
        ,@FechaEtapaDesde  AS DATETIME
        ,@FechaEtapaHasta  AS DATETIME;
		
SET @FechaDesde       = DATEADD(MONTH, -6, GETDATE());
SET @FechaHasta       = GETDATE();
SET @FechaEstadoDesde = CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE()-5, 103), 103);
SET @FechaEstadoHasta = CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 103), 103);
SET @FechaEtapaDesde  = CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE()-5, 103), 103);
SET @FechaEtapaHasta  = CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 103), 103);

create table #RegistPor (RegPor varchar(50) not null);
insert intO #RegistPor SELECT
	RTRIM([REQ REGPOR]) AS REGPOR
FROM
	(SELECT 
		ZL.PNCEREQ.REGPOR AS [REQ REGPOR]
	 FROM
	    ZL.PNCEREQ 
	    LEFT OUTER JOIN ZL.REQCLIDET ON ZL.PNCEREQ.CODIN = ZL.REQCLIDET.NUMERO
	 WHERE
		(ZL.REQCLIDET.FUNC IS NOT NULL) 
		OR (ZL.REQCLIDET.BUG IS NOT NULL) 
		OR (ZL.PNCEREQ.NAPROV = 0) 
		AND (ZL.PNCEREQ.CMPFECINI > '20111001') 
		AND (ZL.PNCEREQ.FALTAFW BETWEEN @FECHADESDE AND @FECHAHASTA)
UNION
SELECT
	ZL.REQUER.REGPOR AS [REQ REGPOR]
FROM
	ZL.REQUER 
	LEFT OUTER JOIN ZL.REQIDDET ON ZL.REQUER.CODIGO = ZL.REQIDDET.REQID 
		AND ZL.REQUER.FALTAFW BETWEEN @FECHADESDE AND @FECHAHASTA
UNION
SELECT
	R.REGPOR AS [REQ REGPOR]
FROM
	ZL.INCIDS 
	INNER JOIN ZL.IYDREQUERIMIENTOSINCIDENTES AS R ON R.NUMERO = ZL.INCIDS.CODIN 
		AND ZL.INCIDS.CMPFECINI BETWEEN @FECHADESDE AND @FECHAHASTA) AS REQUERIMIENTOS	
UNION
	SELECT 
		''
ORDER BY
	1;

create table #RequerPor (codigo varchar(10) null, Contacto varchar(50) null);
INSERT INTO #RequerPor SELECT [CONTACT].codigo, LTRIM(RTRIM([CONTACT].apell))+ ', ' + LTRIM(RTRIM([CONTACT].pnom)) + ' ' + LTRIM(RTRIM([CONTACT].snom)) as Contacto
FROM [ZL].[CONTACT]
	INNER JOIN [ZL].[ZL].[PNCEREQ] ON [ZL].[ZL].[PNCEREQ].CONTACTO = [CONTACT].codigo
		AND [PNCEREQ].[NAPROV] = 0  
		AND [PNCEREQ].[CMPFECINI] > '20111001'
		AND [PNCEREQ].[FALTAFW] BETWEEN @FechaDesde AND @FechaHasta
UNION
SELECT
	''
	,'' AS Contacto
order by 2;

CREATE TABLE #Clientes (CCLIENTE VARCHAR(10) NULL, NOMBRE VARCHAR(50) NULL);
INSERT INTO #Clientes SELECT
	[PNCEREQ].[CCLIENTE] AS [REQ CCLIENTE]
	,[CLIENTES].[CMPNOMBRE] AS [REQ CLIENTE NOMBRE]
FROM 
	[ZL].[ZL].[PNCEREQ] 
	LEFT JOIN [ZL].[REQCLIDET] ON [PNCEREQ].[CODIN] = [REQCLIDET].[NUMERO]
	LEFT JOIN [ZL].[ZL].[CLIENTES] AS [CLIENTES] ON [CLIENTES].[CMPCODIGO] = [PNCEREQ].[CCLIENTE]
WHERE
	( (  [REQCLIDET].FUNC IS NOT NULL OR [REQCLIDET].BUG IS NOT NULL) 
		OR 
	  ( [PNCEREQ].[NAPROV] = 0  AND  [PNCEREQ].[CMPFECINI] > '20111001' ) )
	AND [PNCEREQ].[FALTAFW] BETWEEN @FECHADESDE AND @FECHAHASTA  
UNION 
SELECT
	'' AS CLIENTE
	,'' AS CIENTENOMBRE		
UNION 
SELECT
	[INCIDS].[CCLIENTE]
	,[CLIENTES].[CMPNOMBRE] AS [CLIENTE NOMBRE]
FROM
	[ZL].[ZL].[INCIDS]
	JOIN ZL.IYDREQUERIMIENTOSINCIDENTES AS R ON R.NUMERO = INCIDS.CODIN
	LEFT JOIN [ZL].[ZL].[CLIENTES] ON [CLIENTES].[CMPCODIGO] = [INCIDS].[CCLIENTE]
WHERE 
	[INCIDS].[CMPFECINI] BETWEEN @FECHADESDE AND @FECHAHASTA           
ORDER BY 2;

CREATE TABLE #Proyectos (ENTIDADRELACIONADAPROYECTOACTUAL VARCHAR(50) NULL);
INSERT INTO #Proyectos SELECT 
	DISTINCT
	CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ' SIN PRE-ANÁLISIS '
		ELSE CASE 
				WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ISNULL(REQUERIMIENTOS.PROYECTOPREANALISIS,' SIN EQUIPO ')
				ELSE CASE 
						WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(BUP.PROYECTO, ' SIN EQUIPO ') 
						ELSE ISNULL(FUP.PROYECTO,' SIN EQUIPO')  
					END 
			END 
	END AS ENTIDADRELACIONADAPROYECTOACTUAL
FROM
	(SELECT
		[REQCLIDET].FUNC AS FUNCIONALIDAD
		,[REQCLIDET].BUG AS BUG
		,ESTDET.DESCR AS ESTADOPREANALISIS
		,PROY.DESCRIP AS PROYECTOPREANALISIS
	FROM [ZL].[ZL].[PNCEREQ] 
		LEFT JOIN		
			(SELECT REQCLIDET.CODIGO, REQCLIDET.NUMERO, REQCLIDET.FUNCEST, REQCLIDET.PROY, REQCLIDET.FUNC, REQCLIDET.BUG 
			 FROM
				(SELECT MAX(CODIGO) AS CODIGO, NUMERO,  FUNC, BUG 
				 FROM [ZL].[REQCLIDET]
				 GROUP BY  NUMERO, FUNC, BUG ) AS U JOIN ZL.REQCLIDET ON REQCLIDET.CODIGO = U.CODIGO 
					AND U.NUMERO = REQCLIDET.NUMERO 
					AND REQCLIDET.FUNC = U.FUNC 
					AND REQCLIDET.BUG = U.BUG) AS [REQCLIDET] ON [PNCEREQ].[CODIN] = [REQCLIDET].[NUMERO]
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQCLIDET].[FUNCEST] = [ESTDET].[CODIGO]
		LEFT JOIN [ZL].[ZL].[PROY] ON [REQCLIDET].[PROY] = [PROY].[CODIGO]
	WHERE
		( ([REQCLIDET].FUNC IS NOT NULL OR [REQCLIDET].BUG IS NOT NULL) 
		   OR 
		  ([PNCEREQ].[NAPROV] = 0  AND  [PNCEREQ].[CMPFECINI] > '20111001') )
		AND [PNCEREQ].[FALTAFW] BETWEEN @FECHADESDE AND @FECHAHASTA  
UNION ALL
SELECT
	[REQIDDET].[FUNC] AS FUNCIONALIDAD
	,0 AS BUG
	,ESTDET.DESCR AS ESTADOPREANALISIS
	,PROY.DESCRIP AS PROYECTOPREANALISIS
FROM 
	[ZL].[REQUER] 
	LEFT JOIN  
		(SELECT REQIDDET.CODIGO, REQIDDET.FUNCEST, REQIDDET.PROY, REQIDDET.REQID, REQIDDET.FUNC 
         FROM [ZL].[REQIDDET] 
			 JOIN (SELECT MAX(CODIGO) AS CODIGO, REQID, FUNC 
				   FROM [ZL].[ZL].[REQIDDET] 
				   GROUP BY REQID, FUNC) AS ULT ON ULT.REQID = [REQIDDET].[REQID] 
					AND ULT.CODIGO = [REQIDDET].CODIGO 
					AND  ULT.FUNC =[REQIDDET].FUNC) AS REQIDDET ON [REQUER].[CODIGO] = [REQIDDET].[REQID]                
 			 LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQIDDET].[FUNCEST] = [ESTDET].[CODIGO]
			 LEFT JOIN [ZL].[ZL].[PROY] ON [REQIDDET].[PROY] = [PROY].[CODIGO]       
		 WHERE 
			[REQUER].[FALTAFW] BETWEEN @FECHADESDE AND @FECHAHASTA  
UNION ALL
SELECT
	[REQINCDET].[FUNC] AS FUNCIONALIDAD
	,[REQINCDET].[BUG] AS BUG
	,ESTDET.DESCR AS ESTADOPREANALISIS
	,PROY.DESCRIP AS PROYECTOPREANALISIS
FROM
	[ZL].[ZL].[INCIDS]
	JOIN ZL.IYDREQUERIMIENTOSINCIDENTES AS R ON R.NUMERO = INCIDS.CODIN
	LEFT JOIN     
		(SELECT REQINCDET.CODIGO,  REQINCDET.[INC_ID], REQINCDET.FUNC, [REQINCDET].BUG , REQINCDET.FUNCEST, REQINCDET.PROY
         FROM [ZL].[REQINCDET]  
			JOIN (SELECT MAX(CODIGO) AS CODIGO, [INC_ID], FUNC, BUG
				  FROM [ZL].[REQINCDET]
				  GROUP BY [INC_ID] , FUNC , BUG ) AS ULT ON ULT.[INC_ID] = [REQINCDET].[INC_ID] 
					AND ULT.CODIGO = [REQINCDET].CODIGO 
					AND ULT.FUNC =[REQINCDET].FUNC 
					AND ULT.BUG =[REQINCDET].BUG) AS REQINCDET ON [INCIDS].[CODIN] = [REQINCDET].[INC_ID]
			LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQINCDET].[FUNCEST] = [ESTDET].[CODIGO]
			LEFT JOIN [ZL].[ZL].[PROY] ON [REQINCDET].[PROY] = [PROY].[CODIGO]       
		 WHERE 
			[INCIDS].[CMPFECINI] BETWEEN @FECHADESDE AND @FECHAHASTA           
	) AS REQUERIMIENTOS 
	LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOPROYECTO AS FUP ON FUP.FUNCIONALIDAD = REQUERIMIENTOS.FUNCIONALIDAD
	LEFT JOIN ZL.IYDBUGULTIMOPROYECTO AS BUP ON BUP.BUG = [REQUERIMIENTOS].[BUG]
ORDER BY 
	1;

CREATE TABLE #Estados (ENTIDADRELACIONADAESTADOACTUAL VARCHAR(50) NULL);
INSERT INTO #Estados SELECT 
	DISTINCT
	CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ' SIN PRE-ANÁLISIS '
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN REQUERIMIENTOS.ESTADOPREANALISIS
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(BUE.ESTADO,' SIN ESTADO ') 
				ELSE ISNULL(FUE.ESTADO,' SIN ESTADO ') 
			END 
		END 
	END AS ENTIDADRELACIONADAESTADOACTUAL
FROM
	(SELECT
		[REQCLIDET].FUNC AS FUNCIONALIDAD
		,[REQCLIDET].BUG AS BUG
		,ESTDET.DESCR AS ESTADOPREANALISIS
		,PROY.DESCRIP AS PROYECTOPREANALISIS
	 FROM 
		[ZL].[ZL].[PNCEREQ] 
		LEFT JOIN		
			(SELECT REQCLIDET.CODIGO, REQCLIDET.NUMERO, REQCLIDET.FUNCEST, REQCLIDET.PROY, REQCLIDET.FUNC, REQCLIDET.BUG 
			 FROM
				(SELECT MAX(CODIGO) AS CODIGO, NUMERO, FUNC, BUG 
				 FROM [ZL].[REQCLIDET]
				 GROUP BY NUMERO, FUNC, BUG) AS U JOIN ZL.REQCLIDET ON REQCLIDET.CODIGO = U.CODIGO 
					AND U.NUMERO = REQCLIDET.NUMERO 
					AND REQCLIDET.FUNC = U.FUNC 
					AND REQCLIDET.BUG = U.BUG) AS [REQCLIDET] ON [PNCEREQ].[CODIN] = [REQCLIDET].[NUMERO]
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQCLIDET].[FUNCEST] = [ESTDET].[CODIGO]
		LEFT JOIN [ZL].[ZL].[PROY] ON [REQCLIDET].[PROY] = [PROY].[CODIGO]
	WHERE
		( ([REQCLIDET].FUNC IS NOT NULL OR [REQCLIDET].BUG IS NOT NULL) 
		OR 
		([PNCEREQ].[NAPROV] = 0  AND  [PNCEREQ].[CMPFECINI] > '20111001') )
		AND [PNCEREQ].[FALTAFW] BETWEEN @FECHADESDE AND @FECHAHASTA  
	UNION ALL
	SELECT
		[REQIDDET].[FUNC] AS FUNCIONALIDAD
		,0 AS BUG
		,ESTDET.DESCR AS ESTADOPREANALISIS
		,PROY.DESCRIP AS PROYECTOPREANALISIS
	FROM 
		[ZL].[REQUER] 
		LEFT JOIN
			(SELECT REQIDDET.CODIGO, REQIDDET.FUNCEST, REQIDDET.PROY, REQIDDET.REQID, REQIDDET.FUNC 
			 FROM [ZL].[REQIDDET]
				JOIN 
					(SELECT MAX(CODIGO) AS CODIGO,  REQID, FUNC 
					 FROM [ZL].[ZL].[REQIDDET] 
					 GROUP BY REQID, FUNC) AS ULT ON ULT.REQID = [REQIDDET].[REQID] 
						AND ULT.CODIGO = [REQIDDET].CODIGO 
						AND ULT.FUNC =[REQIDDET].FUNC) AS REQIDDET ON [REQUER].[CODIGO] = [REQIDDET].[REQID]                
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQIDDET].[FUNCEST] = [ESTDET].[CODIGO]
		LEFT JOIN [ZL].[ZL].[PROY] ON [REQIDDET].[PROY] = [PROY].[CODIGO]       
	WHERE 
		[REQUER].[FALTAFW] BETWEEN @FECHADESDE AND @FECHAHASTA  
	UNION ALL
	SELECT
		[REQINCDET].[FUNC] AS FUNCIONALIDAD
		,[REQINCDET].[BUG] AS BUG
		,ESTDET.DESCR AS ESTADOPREANALISIS
		,PROY.DESCRIP AS PROYECTOPREANALISIS
	FROM
		[ZL].[ZL].[INCIDS]
		JOIN ZL.IYDREQUERIMIENTOSINCIDENTES AS R ON R.NUMERO = INCIDS.CODIN
		LEFT JOIN     
			(SELECT REQINCDET.CODIGO, REQINCDET.[INC_ID], REQINCDET.FUNC, [REQINCDET].BUG, REQINCDET.FUNCEST, REQINCDET.PROY
			 FROM [ZL].[REQINCDET] 
				JOIN
					(SELECT MAX(CODIGO) AS CODIGO, [INC_ID], FUNC, BUG
					 FROM [ZL].[REQINCDET]
					 GROUP BY [INC_ID], FUNC, BUG) AS ULT ON ULT.[INC_ID] = [REQINCDET].[INC_ID] 
						AND ULT.CODIGO = [REQINCDET].CODIGO 
						AND ULT.FUNC = [REQINCDET].FUNC 
						AND ULT.BUG = [REQINCDET].BUG) AS REQINCDET ON [INCIDS].[CODIN] = [REQINCDET].[INC_ID]
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQINCDET].[FUNCEST] = [ESTDET].[CODIGO]
		LEFT JOIN [ZL].[ZL].[PROY] ON [REQINCDET].[PROY] = [PROY].[CODIGO]       
	WHERE 
		[INCIDS].[CMPFECINI] BETWEEN @FECHADESDE AND @FECHAHASTA) AS REQUERIMIENTOS 
	LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOESTADO AS FUE ON FUE.FUNCIONALIDAD = REQUERIMIENTOS.FUNCIONALIDAD
	LEFT JOIN ZL.IYDBUGULTIMOESTADO AS BUE ON BUE.BUG = [REQUERIMIENTOS].[BUG]
ORDER BY 1;




/**********************************************************************************************************************
*                                                                                                                     *
*                                                    1ER QUERY PRINCIPAL                                              *
*                                                                                                                     *
**********************************************************************************************************************/

SELECT
	REQUERIMIENTOS.[TIPO DE REQUERIMIENTO]
	, REQUERIMIENTOS.[REQ NÚMERO]
	, REQUERIMIENTOS.[REQ ALTA]
	, REQUERIMIENTOS.[REQ REGPOR]
	, REQUERIMIENTOS.[REQ ASUNTO/TÍTULO]
	, REQUERIMIENTOS.[REQ DETALLE]
	, REQUERIMIENTOS.[REQ OBSERVACIÓN]
	, REQUERIMIENTOS.[REQ CCLIENTE]
	, REQUERIMIENTOS.[REQ CLIENTE NOMBRE]
	, ISNULL(REQUERIMIENTOS.CONTACTO, '') AS [CONTACTO]
 	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL OR (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ''
		ELSE CASE 
			WHEN  REQUERIMIENTOS.BUG <> 0 THEN 'BUG' 
			ELSE 'FUNCIONALIDAD' 
		END 
	END AS ENTIDADRELACIONADA
		  
	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL OR (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN 0
		ELSE CASE 
			WHEN REQUERIMIENTOS.BUG <> 0 THEN REQUERIMIENTOS.BUG 
			ELSE REQUERIMIENTOS.FUNCIONALIDAD 
		END 
	END AS ENTIDADRELACIONADANUMERO	
		
	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ' SIN PRE-ANÁLISIS '
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ISNULL(REQUERIMIENTOS.ESTADOPREANALISIS,' SIN ESTADO ')
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(BUE.ESTADO,' SIN ESTADO ') 
				ELSE ISNULL(REQUERIMIENTOS.ESTADO,' SIN ESTADO ') 
			END 
		END 
	END AS ENTIDADRELACIONADAESTADOACTUAL
		 	
	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ' SIN PRE-ANÁLISIS '
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ISNULL(REQUERIMIENTOS.PROYECTOPREANALISIS,' SIN EQUIPO ')
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(BUP.PROYECTO, ' SIN EQUIPO ') 
				ELSE ISNULL(FUP.PROYECTO,' SIN EQUIPO ')  
			END 
		END 
	END AS ENTIDADRELACIONADAPROYECTOACTUAL

	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL OR (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ''
		ELSE CASE 
			WHEN REQUERIMIENTOS.BUG <> 0 THEN B.TITULO 
			ELSE F.NOMBRE 
		END 
	END AS ENTIDADRELACIONADANOMBRE

	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ''
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN 'PRE-ANÁLISIS' 
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(BEU.COMPROBANTE, '') 
				ELSE ISNULL(REQUERIMIENTOS.COMPROBANTE, '')
			END 
		END 
	END AS ENTIDADRELACIONADAULTIMAETAPACOMPROBANTE

	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ''
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN CONVERT(VARCHAR, REQUERIMIENTOS.PREANALISIS)
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN CONVERT(VARCHAR, BEU.NUMERO)
				ELSE ISNULL(REQUERIMIENTOS.COMPROBANTE, '')
			END 
		END 
	END AS ENTIDADRELACIONADAULTIMAETAPACOMPROBANTENUMERO

	,CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL OR (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ISNULL(REQUERIMIENTOS.FECHAPREANALISIS, '')
		ELSE CASE 
			WHEN REQUERIMIENTOS.BUG <> 0 THEN CONVERT(VARCHAR, BEU.FECHA, 103)
			ELSE ISNULL(REQUERIMIENTOS.UltimaEtapaFecha, '')
		END 
	END AS ENTIDADRELACIONADAULTIMAETAPACOMPROBANTEFECHA

	--,REQUERIMIENTOS.Estado AS 'Estado'
	--,REQUERIMIENTOS.UltimoEstadoFecha AS 'UltimoEstadoFecha'
	--,REQUERIMIENTOS.COMPROBANTE AS 'COMPROBANTE'
	,ISNULL(REQUERIMIENTOS.UltimaEtapaFecha, '') AS 'ULTIMAETAPAFECHA'
FROM
	(SELECT 
		'Req. Cliente' as [Tipo de Requerimiento]
		,[PNCEREQ].[Codin] as [Req Número]
		,CONVERT(VARCHAR, [PNCEREQ].[Faltafw], 103) as [Req Alta]
		,[ZL].[ZL].[PNCEREQ].[REGPOR] AS [REQ REGPOR]
		,[ZL].[REQCLIDET].FUNC AS FUNCIONALIDAD
		,[ZL].[REQCLIDET].BUG
		,[PNCEREQ].[ASUNTO] as [Req Asunto/Título]
		,cast([PNCEREQ].[Cmpconsult]as varchar(max)) as [Req Detalle]
		,'' as [Req Observación]
		,[PNCEREQ].[Ccliente] as [Req Ccliente]
		,[ZL].[REQCLIDET].[Clidesc] as [Req Cliente nombre]
		,[Prodzl].[Descr] as [Req Producto]
		,RTRIM([CONTACT].pnom) + ' ' + RTRIM([CONTACT].snom) + RTRIM([CONTACT].apell) as Contacto
		,[REQCLIDET].codigo as Preanalisis          
		,CONVERT(VARCHAR, [PRE_ANAL].Faltafw, 103) as FechaPreAnalisis
		,EstDet.Descr as EstadoPreAnalisis
		,Proy.Descrip as ProyectoPreAnalisis
		,ULTEST.Estado AS 'Estado'
		,CONVERT(VARCHAR, ULTEST.Fecha, 103) AS 'UltimoEstadoFecha'
		,ULTETAP.COMPROBANTE as 'COMPROBANTE'
		,CONVERT(VARCHAR, ULTETAP.Fecha, 103) as 'UltimaEtapaFecha'
	FROM 
		[ZL].[REQCLIDET]
		INNER JOIN [ZL].[ZL].[PNCEREQ] ON [ZL].[ZL].[PNCEREQ].CODIN = [ZL].[REQCLIDET].NUMERO
			AND [PNCEREQ].[NAPROV] = 0  
			AND [PNCEREQ].[CMPFECINI] > '20111001'
			AND [PNCEREQ].[REGPOR] IS NOT NULL
			AND [PNCEREQ].[REGPOR] IN (select regpor from #RegistPor) 
			AND [PNCEREQ].[CCLIENTE] IN (SELECT CCLIENTE FROM #Clientes)
		LEFT JOIN	
		(SELECT FUNCIONALIDAD, FECHA, ESTADO FROM ZL.IYDFUNCIONALIDADULTIMOESTADO 
		 WHERE 
			IYDFUNCIONALIDADULTIMOESTADO.FECHA BETWEEN @FechaEstadoDesde AND @FechaEstadoHasta
			AND ESTADO IS NOT NULL AND ESTADO <> ' Sin Estado '
			AND ESTADO IN (SELECT ENTIDADRELACIONADAESTADOACTUAL FROM #Estados)) AS ULTEST 
				ON ULTEST.FUNCIONALIDAD = [ZL].[REQCLIDET].FUNC OR ULTEST.FUNCIONALIDAD = [ZL].[REQCLIDET].BUG
		LEFT JOIN
		(SELECT FUNCIONALIDAD, FECHA, COMPROBANTE FROM ZL.IYDFUNCIONALIDADETAPAULTIMA 
		 WHERE 
			IYDFUNCIONALIDADETAPAULTIMA.FECHA BETWEEN @FechaEtapaDesde AND @FechaEtapaHasta
			AND COMPROBANTE IS NOT NULL AND COMPROBANTE <> ' Sin Estado ') AS ULTETAP
			ON ULTETAP.FUNCIONALIDAD = [ZL].[REQCLIDET].FUNC OR ULTETAP.FUNCIONALIDAD = [ZL].[REQCLIDET].BUG
		LEFT JOIN [ZL].[ZL].[Prodzl] ON [Prodzl].[Ccod] = [PNCEREQ].[CPCOD]
		LEFT JOIN [ZL].[CONTACT] ON [CONTACT].codigo = [PNCEREQ].contacto
			AND [CONTACT].codigo IN (SELECT codigo FROM #RequerPor)
		LEFT JOIN [ZL].[PRE_ANAL] ON [PRE_ANAL].[Codigo] = [REQCLIDET].[Codigo]
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [ESTDET].[Codigo] = [REQCLIDET].[Funcest]
		LEFT JOIN [ZL].[ZL].[PROY] ON [PROY].[Codigo] = [REQCLIDET].[Proy]
			AND [ZL].[ZL].[PROY].[DESCRIP] IN (SELECT ENTIDADRELACIONADAPROYECTOACTUAL FROM #Proyectos)
	WHERE
		([ZL].[REQCLIDET].FUNC <> 0 OR [ZL].[REQCLIDET].BUG <> 0)
	--ORDER BY
	--	[PNCEREQ].[Faltafw]



	/**********************************************************************************************************************
	*                                                                                                                     *
	*                                                    2DO QUERY PRINCIPAL                                              *
	*                                                                                                                     *
	**********************************************************************************************************************/
	UNION ALL
	SELECT
		'Req. I+D' AS TIPO
		,[REQUER].[CODIGO] AS [REQ NÚMERO]
		,CONVERT(VARCHAR, [REQUER].[FALTAFW], 103) AS [REQ ALTA]
		,[REQUER].[REGPOR] AS [REQ REGPOR]
		,[REQIDDET].[FUNC] AS FUNCIONALIDAD
		,0 AS BUG
		,[REQUER].[TITULO] AS [REQ ASUNTO/TÍTULO]
		,[REQUER].DESCR AS DESCRIPCION
		,REQUER.OBS 
		,'' AS CLIENTE
		,'' AS CIENTENOMBRE
		,'' AS PRODUCTO
		,REQUER.REQID AS REQUERIDOPORCONTACTO 
		,[REQIDDET].[CODIGO] AS PREANALISIS		  
		,CONVERT(VARCHAR, [PRE_ANAL].FALTAFW, 103) AS FECHAPREANALISIS
		,ESTDET.DESCR AS ESTADOPREANALISIS
		,PROY.DESCRIP AS PROYECTOPREANALISIS
		,ULTEST.Estado AS 'Estado'
		,CONVERT(VARCHAR, ULTEST.Fecha, 103) AS 'UltimoEstadoFecha'
		,ULTETAP.COMPROBANTE as 'Etapa'
		,CONVERT(VARCHAR, ULTETAP.Fecha, 103) as 'UltimaEtapaFecha'
	FROM 
		[ZL].[REQUER] 
		LEFT JOIN 
		(SELECT 
			REQIDDET.CODIGO
			,REQIDDET.FUNCEST
			,REQIDDET.PROY
			,REQIDDET.REQID
			,REQIDDET.FUNC 
		 FROM 
			[ZL].[REQIDDET]
			JOIN 
				(SELECT MAX(CODIGO) AS CODIGO, REQID, FUNC 
				 FROM [ZL].[ZL].[REQIDDET] 
				 GROUP BY REQID, FUNC) AS ULT ON ULT.REQID = [REQIDDET].[REQID] 
					AND ULT.CODIGO = [REQIDDET].CODIGO 
					AND ULT.FUNC =[REQIDDET].FUNC) AS REQIDDET ON [REQUER].[CODIGO] = [REQIDDET].[REQID]
		LEFT JOIN ZL.[PRE_ANAL] ON [PRE_ANAL].[CODIGO]  = [REQIDDET].[CODIGO] 
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [ESTDET].[CODIGO] = [REQIDDET].[FUNCEST]
		LEFT JOIN [ZL].[ZL].[PROY] ON [PROY].[CODIGO] = [REQIDDET].[PROY]
		LEFT JOIN	
		(SELECT FUNCIONALIDAD, FECHA, ESTADO FROM ZL.IYDFUNCIONALIDADULTIMOESTADO 
		 WHERE 
			IYDFUNCIONALIDADULTIMOESTADO.FECHA BETWEEN @FechaEstadoDesde AND @FechaEstadoHasta
			AND ESTADO IS NOT NULL AND ESTADO <> ' Sin Estado '
			AND ESTADO IN (SELECT ENTIDADRELACIONADAESTADOACTUAL FROM #Estados)) AS ULTEST 
				ON ULTEST.FUNCIONALIDAD = REQIDDET.FUNC
		LEFT JOIN
		(SELECT FUNCIONALIDAD, FECHA, COMPROBANTE FROM ZL.IYDFUNCIONALIDADETAPAULTIMA 
		 WHERE 
			IYDFUNCIONALIDADETAPAULTIMA.FECHA BETWEEN @FechaEtapaDesde AND @FechaEtapaHasta
			AND COMPROBANTE IS NOT NULL AND COMPROBANTE <> ' Sin Estado ') AS ULTETAP
			ON ULTETAP.FUNCIONALIDAD = REQIDDET.FUNC
	WHERE 
		[REQUER].[FALTAFW] BETWEEN @FECHADESDE AND @FECHAHASTA  
		AND RTRIM([REQUER].[REGPOR]) IN (SELECT RegPor FROM #RegistPor)
		AND '' IN (SELECT CCLIENTE FROM #Clientes)
		AND RTRIM(REQUER.REQID) IN (SELECT codigo FROM #RequerPor)
		
		
	/**********************************************************************************************************************
	*                                                                                                                     *
	*                                                    3ER QUERY PRINCIPAL                                              *
	*                                                                                                                     *
	**********************************************************************************************************************/
	UNION ALL
	SELECT
		'Incidente' AS [TIPO DE REQUERIMIENTO]
		,[INCIDS].[CODIN] AS [REQ NÚMERO]
		,CONVERT(VARCHAR, [INCIDS].[CMPFECINI], 103) AS [REQ ALTA]
		,R.REGPOR AS [REQ REGPOR]
		,[REQINCDET].[FUNC] AS FUNCIONALIDAD
		,[REQINCDET].[BUG] AS BUG
		,R.[REQ ASUNTO/TÍTULO]
		,CAST(R.[REQ DETALLE] AS VARCHAR(MAX)) AS [REQ DETALLE]
		,'' AS [REQ OBSERVACIÓN]
		,[INCIDS].[CCLIENTE]
		,[CLIENTES].[CMPNOMBRE] AS [CLIENTE NOMBRE]
		,[PRODZL].[DESCR] AS PRODUCTO
		,'' AS CONTACTO
		,[REQINCDET].CODIGO AS PREANALISIS
		,CONVERT(VARCHAR, [PRE_ANAL].FALTAFW, 103) AS FECHAPREANALISIS
		,ESTDET.DESCR AS ESTADOPREANALISIS
		,PROY.DESCRIP AS PROYECTOPREANALISIS
		,ULTEST.Estado AS 'Estado'
		,CONVERT(VARCHAR, ULTEST.Fecha, 103) AS 'UltimoEstadoFecha'
		,ULTETAP.COMPROBANTE as 'Etapa'
		,CONVERT(VARCHAR, ULTETAP.Fecha, 103) as 'UltimaEtapaFecha'
	FROM
		[ZL].[ZL].[INCIDS]
		JOIN ZL.IYDREQUERIMIENTOSINCIDENTES AS R ON R.NUMERO = INCIDS.CODIN
		LEFT JOIN [ZL].[ZL].[TIPIF] ON [INCIDS].[CMPTIPIF] = [TIPIF].[CCOD]
		LEFT JOIN [ZL].[ZL].[TIPIF2] ON [INCIDS].[CMPSTIP] = [TIPIF2].[CCOD]
		LEFT JOIN
			(SELECT REQINCDET.CODIGO, REQINCDET.[INC_ID], REQINCDET.FUNC, [REQINCDET].BUG, REQINCDET.FUNCEST, REQINCDET.PROY
			 FROM [ZL].[REQINCDET] 
				JOIN (SELECT MAX(CODIGO) AS CODIGO, [INC_ID], FUNC, BUG
					  FROM [ZL].[REQINCDET]
					  GROUP BY [INC_ID], FUNC, BUG) AS ULT ON ULT.[INC_ID] = [REQINCDET].[INC_ID] 
						AND ULT.CODIGO = [REQINCDET].CODIGO 
						AND ULT.FUNC = [REQINCDET].FUNC 
						AND ULT.BUG = [REQINCDET].BUG) AS REQINCDET ON [INCIDS].[CODIN] = [REQINCDET].[INC_ID]
		LEFT JOIN ZL.[PRE_ANAL] ON [PRE_ANAL].[CODIGO]  = [REQINCDET].[CODIGO] 
		LEFT JOIN [ZL].[ZL].[CLIENTES] ON [CLIENTES].[CMPCODIGO] = [INCIDS].[CCLIENTE]
		LEFT JOIN [ZL].[ZL].[PRODZL] ON [INCIDS].[CPROD] = [PRODZL].[CCOD]  
		LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQINCDET].[FUNCEST] = [ESTDET].[CODIGO]
		LEFT JOIN [ZL].[ZL].[PROY] ON [REQINCDET].[PROY] = [PROY].[CODIGO]       
		LEFT JOIN	
		(SELECT FUNCIONALIDAD, FECHA, ESTADO FROM ZL.IYDFUNCIONALIDADULTIMOESTADO 
		 WHERE 
			IYDFUNCIONALIDADULTIMOESTADO.FECHA BETWEEN @FechaEstadoDesde AND @FechaEstadoHasta
			AND ESTADO IS NOT NULL AND ESTADO <> ' Sin Estado '
			AND ESTADO IN (SELECT ENTIDADRELACIONADAESTADOACTUAL FROM #Estados)) AS ULTEST 
				ON ULTEST.FUNCIONALIDAD =[REQINCDET].[FUNC] OR ULTEST.FUNCIONALIDAD =[REQINCDET].[BUG]
		LEFT JOIN
		(SELECT FUNCIONALIDAD, FECHA, COMPROBANTE FROM ZL.IYDFUNCIONALIDADETAPAULTIMA 
		 WHERE 
			IYDFUNCIONALIDADETAPAULTIMA.FECHA BETWEEN @FechaEtapaDesde AND @FechaEtapaHasta
			AND COMPROBANTE IS NOT NULL AND COMPROBANTE <> ' Sin Estado ') AS ULTETAP
			ON ULTETAP.FUNCIONALIDAD =[REQINCDET].[FUNC] OR ULTETAP.FUNCIONALIDAD =[REQINCDET].[BUG]
	WHERE 
		[INCIDS].[CMPFECINI] BETWEEN @FECHADESDE AND @FECHAHASTA           
		AND RTRIM(R.REGPOR) IN (SELECT RegPor FROM #RegistPor)
		AND [INCIDS].[CCLIENTE] IN (SELECT CCLIENTE FROM #Clientes)
		AND '' IN (SELECT codigo FROM #RequerPor)
	) AS REQUERIMIENTOS
	LEFT JOIN ZL.FCOMER AS F ON F.CODIGO = REQUERIMIENTOS.FUNCIONALIDAD
	LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOPROYECTO AS FUP ON FUP.FUNCIONALIDAD = F.CODIGO
	LEFT JOIN ZL.REGBUG AS B ON B.[CODIN] = [REQUERIMIENTOS].[BUG] 
	LEFT JOIN ZL.IYDBUGULTIMOESTADO AS BUE ON BUE.BUG = B.CODIN
	LEFT JOIN ZL.IYDBUGULTIMOPROYECTO AS BUP ON BUP.BUG = B.CODIN
	LEFT JOIN ZL.IYDBUGETAPAULTIMA AS BEU ON BEU.BUG = B.CODIN
WHERE 
	CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ' SIN PRE-ANÁLISIS '
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN REQUERIMIENTOS.ESTADOPREANALISIS
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(REQUERIMIENTOS.ESTADO,' SIN ESTADO ') 
				ELSE ISNULL(REQUERIMIENTOS.ESTADO,' SIN ESTADO ') 
			END 
		END 
	END IN (SELECT ENTIDADRELACIONADAESTADOACTUAL FROM #Estados)
	AND 
	CASE 
		WHEN REQUERIMIENTOS.FUNCIONALIDAD IS NULL THEN ' SIN PRE-ANÁLISIS '
		ELSE CASE 
			WHEN (REQUERIMIENTOS.FUNCIONALIDAD = 0 AND REQUERIMIENTOS.BUG = 0) THEN ISNULL(REQUERIMIENTOS.PROYECTOPREANALISIS,' SIN EQUIPO ')
			ELSE CASE 
				WHEN REQUERIMIENTOS.BUG <> 0 THEN ISNULL(BUP.PROYECTO, ' SIN EQUIPO ') 
				ELSE ISNULL(FUP.PROYECTO,' SIN EQUIPO ')  
			END 
		END 
	END IN (SELECT ENTIDADRELACIONADAPROYECTOACTUAL FROM #Proyectos)
	AND (REQUERIMIENTOS.FUNCIONALIDAD <> 0 OR REQUERIMIENTOS.BUG <> 0)
ORDER BY
	CONVERT(DATETIME, REQUERIMIENTOS.[REQ ALTA], 103);

/**********************************************************************************************************************
*                                                                                                                     *
*                                              ELIMINAMOS TODOS LOS FILTROS                                           *
*                                    PARA PODER EJECUTAR EL QUERY DE NUEVO EL REPORTE                                 *
*                                                                                                                     *
**********************************************************************************************************************/
DROP TABLE #REGISTPOR;
DROP TABLE #REQUERPOR;
DROP TABLE #CLIENTES;
DROP TABLE #PROYECTOS;
DROP TABLE #ESTADOS;
