SELECT
	Legajo.Ccod AS 'Legajo'
	, ACTIVOS.Legajo AS 'Operador ZL'
	, ACTIVOS.Puesto AS 'Puesto'
	, PUESTOS.AREA AS 'Área'
	, PUESTOS.Sector AS 'Sector'
	, RTRIM(PUESTOS.Descr) AS 'Descripción'
	, RTRIM(Legajo.Capellido)+' '+
	  RTRIM(Legajo.Cprinombre)+' '+
	  RTRIM(Legajo.CSegnombre)  AS 'Nombre'
	-- ESQUEMA POR PUESTO
	, ISNULL(CONVERT(VARCHAR(2), ESQASIGPTO.ESQLAB), 'NO') AS 'Esquema x Pto'
	, ISNULL(CONVERT(VARCHAR(10), ESQASIGPTO.FECDESDE, 103), '') AS 'Desde'
	, CASE
		WHEN ISNULL(CONVERT(VARCHAR(10), ESQASIGPTO.FECHASTA, 103), '') = '01/01/1900' THEN ''
		ELSE ISNULL(CONVERT(VARCHAR(10), ESQASIGPTO.FECHASTA, 103), '')
	END AS 'Hasta'
	, ISNULL(CASE 
		WHEN ESQASIGPTO.FECHASTA = '19000101' THEN 'Actual'
		WHEN ESQASIGPTO.FECHASTA > '19000101' AND ESQASIGPTO.FECHASTA < GETDATE() THEN 'Vencido'
		ELSE CONVERT(VARCHAR(10), ESQASIGPTO.FECHASTA, 103)
	END, '') AS 'Estado'
	-- ESQUEMA POR LEGAJO
	, ISNULL(CONVERT(VARCHAR(2), ESQASIGLEG.ESQLAB), 'NO') AS 'Esquema x Legajo'
	, ISNULL(CONVERT(VARCHAR(10), ESQASIGLEG.FECDESDE, 103), '') AS 'Desde'
	, CASE
		WHEN ISNULL(CONVERT(VARCHAR(10), ESQASIGLEG.FECHASTA, 103), '') = '01/01/1900' THEN ''
		ELSE ISNULL(CONVERT(VARCHAR(10), ESQASIGLEG.FECHASTA, 103), '')
	END AS 'Hasta'
	, ISNULL(CASE
		WHEN ESQASIGLEG.FECHASTA = '19000101' THEN 'Actual'
		WHEN ESQASIGLEG.FECHASTA >= GETDATE() THEN 'Actual'
		WHEN ESQASIGLEG.FECHASTA > '19000101' AND ESQASIGLEG.FECHASTA < GETDATE() THEN 'Vencido'
		ELSE CONVERT(VARCHAR(10), ESQASIGLEG.FECHASTA, 103)
	END, '') AS 'Estado'
FROM
	ZL.Legajo
	, (SELECT * FROM [ZL].[Objetivos].LegajoActivo('', CONVERT(VARCHAR(8), GETDATE(), 112))) AS ACTIVOS
	LEFT JOIN ZL.ASIGESQJLAP AS ESQASIGPTO ON ESQASIGPTO.PUESTO = ACTIVOS.Puesto 
	LEFT JOIN ZL.ASIGESQJLAB AS ESQASIGLEG ON ESQASIGLEG.LEG    = ACTIVOS.CLegajo 
	LEFT JOIN ZL.puestosrh   AS PUESTOS    ON PUESTOS.Cod       = ACTIVOS.Puesto 
WHERE
	ZL.Legajo.Ccod = ACTIVOS.CLegajo 

