SELECT 
  ZL.EVALBUGS.CODIGO AS [EVALUACION DE BUGS NRO.]
  , DETALLES.BUG AS [BUG]
  , ZL.EVALBUGS.REGPOR AS[REGISTRADO POR]
  , DETALLES.TITULO AS [TÍTULO]
  , CASE
      WHEN DETALLES.BUGASO <> 0 THEN 'BUG'
      WHEN DETALLES.FUNC <> 0 THEN 'FUNCIONALIDAD'
      ELSE ''
    END 'ORIGEN'
  , DETALLES.BUGASO AS [BUG ORIGEN]
  , DETALLES.TITASO AS [TÍTULO BUG ORIGEN]
  , DETALLES.FUNC AS [FUNCIONALIDAD ORIGEN]
  , DETALLES.NOMBRE AS [TÍTULO FUNCIONALIDAD ORIGEN]
  , DETALLES.PROY AS [ID PROYECTO]
  , ASISTENTES.ASIST
FROM 
  ZL.EVALBUGS
  LEFT JOIN ZL.DETEVBUGS AS DETALLES ON DETALLES.CODIGO = ZL.EVALBUGS.CODIGO
    AND DETALLES.BUG <> 0
  LEFT JOIN (SELECT
              ZL.DETEVBGASIS.CODIGO
              , C.ASIST
             FROM
              ZL.DETEVBGASIS
              INNER JOIN
                (SELECT 
                  DISTINCT
                  B.[CODIGO]
                  ,STUFF((SELECT ', ' + RTRIM(A.LEGAJO) FROM ZL.ZL.DETEVBGASIS AS A WHERE A.CODIGO = B.CODIGO group BY A.CODIGO, A.LEGAJO FOR XML PATH ('')) , 1, 1, '') AS ASIST
		             FROM
			            ZL.ZL.DETEVBGASIS AS B) AS C ON C.CODIGO = ZL.DETEVBGASIS.CODIGO
            GROUP BY
              ZL.DETEVBGASIS.CODIGO
              , C.ASIST) AS ASISTENTES ON ASISTENTES.CODIGO =   ZL.EVALBUGS.CODIGO
WHERE
  ZL.EVALBUGS.CODIGO = 297
  AND DETALLES.BUG IS NOT NULL
ORDER BY
  ZL.EVALBUGS.CODIGO
  , DETALLES.NITEM

/*
SELECT
  'ISSUE' 
  , DETALLES.ISSUE AS [ISSUE]
  , DETALLES.TITISSUE AS [TITULO ISSUE]
  , DETALLES.BUG AS [BUG NUEVO]
  , DETALLES.TITULO AS [TITULO BUG NUEVO]
  , DETALLES.FUNC AS [FUNC NUEVA]
  , DETALLES.NOMBRE AS [TITULO FUNC NUEVA]
  , DETALLES.BUGO AS [BUG DE ORIGEN]
  , DETALLES.NOMBREO AS [TITULOBUG ORIGEN]
  , DETALLES.FUNCO AS [FUNCIONALIDAD ORIGEN]
  , DETALLES.REGPOR AS [REG POR]
  , DETALLES.PROY AS [ID PROYECTO]
FROM 
  ZL.EVALISSUES
  LEFT JOIN ZL.DETEVISS AS DETALLES ON DETALLES.CODIGO = ZL.EVALISSUES.CODIGO
WHERE
  ZL.EVALISSUES.CODIGO = 120
  --AND DETALLES.ISSUE = 364
  */