DECLARE @FECHADESDE DATETIME, @FECHAHASTA DATETIME;
SET @FECHADESDE = '20130725';
SET @FECHAHASTA = '20130725';


SELECT
	DISTINCT
	[FICHAJES].LEGAJO
	, [FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3) AS FECHA
	, [FICHAJES].HORAREG
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
		ELSE NULL
	END AS [TIPO]
	--, [FICHAJES].ESTTRANS
	--, [FICHAJES].PCONTROL
	--, LTRIM(RTRIM([PTOCONTROL].[DESCR])) AS PTOCONTROL
	--, [FICHAJES].CODPUESTO AS [CODPUESTO]
	--, LTRIM(RTRIM([PUESTOS].[DESCR])) AS DESCR 
	--, [FICHAJES].AREA AS [AREA] 
	--, [FICHAJES].SECTOR AS [SECTOR] 
	--, [FICHAJES].[INGRESOESQUEMA]
	--, [FICHAJES].[EGRESOESQUEMA]
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].[INGRESOESQUEMA] 
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN [FICHAJES].[EGRESOESQUEMA]  
		ELSE NULL
	END AS 'HORARIOESQUEMA'
	--, FICHAJES.TOLERANCIA AS TMPTOLERANCIA
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].[TOLERANCIA]
		ELSE 0
	END AS [TOLERANCIA]
	--, [FICHAJES].MINUTOS AS 'MINUTOS'			
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) 
		ELSE 0
	END AS DESVIO
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN CASE
															WHEN ([FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]) > 0 THEN 'Tarde'
															WHEN ([FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]) <= 0 THEN 'Temprano'
															ELSE ''
														END
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN	CASE
															WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
															WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) <= 0 THEN 'Salida correcta'
															ELSE ''
														END
		ELSE NULL
	END AS 'TIPOINCUMPLIMIENTO'
	, GESINC.MOTIVO 
	, [FICHAJES].ASIGESQ
FROM
	[ZL].[ZNFICHAJE] AS [FICHAJES]
	LEFT JOIN [ZL].[ZNPCONTROL] AS [PTOCONTROL] ON [PTOCONTROL].[COD] = [FICHAJES].[PCONTROL]
	--LEFT JOIN [ZL].[puestosrh] AS PUESTOS ON PUESTOS.Cod = [FICHAJES].[CODPUESTO]
	INNER JOIN (SELECT LEGAJO, FECHA, MIN(HORAREG) AS INGRESO FROM [ZL].[ZNFICHAJE] GROUP BY LEGAJO, FECHA) AS INGRESOS ON INGRESOS.LEGAJO = [FICHAJES].[LEGAJO] AND INGRESOS.FECHA = [FICHAJES].[FECHA]
	INNER JOIN (SELECT LEGAJO, FECHA, MAX(HORAREG) AS EGRESO FROM [ZL].[ZNFICHAJE] GROUP BY LEGAJO, FECHA) AS EGRESOS ON EGRESOS.LEGAJO = [FICHAJES].[LEGAJO] AND INGRESOS.FECHA = [FICHAJES].[FECHA]
	LEFT JOIN (SELECT
					NUMERO
					, LEG
					, CASE INCHLAB
						WHEN 'AUS' THEN 'Ausencia'
						WHEN 'LLT' THEN 'Tarde'
						WHEN 'SAT' THEN 'Salida temprana'
						ELSE ''
					END AS MOTIVO
					, JUSTIFICA
					, FECHAF
					, FECHAI
					--, *
				FROM 
					ZL.GESINC
				WHERE
					FECHAI >= @FECHADESDE 
					AND FECHAF <= @FECHAHASTA) AS GESINC ON GESINC.LEG = FICHAJES.LEGAJO
WHERE
	[FICHAJES].FECHA >= @FECHADESDE 
	AND [FICHAJES].FECHA <= @FECHAHASTA 
	AND	CASE 
			WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
			WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
			ELSE NULL
		END IS NOT NULL
	AND 
	(CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]
		ELSE 0
	END	> 0
	OR CASE 
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATEDIFF(MINUTE, [FICHAJES].[EGRESOESQUEMA], EGRESOS.EGRESO) 
		ELSE 0
	END	< 0)
	--AND [FICHAJES].CODPUESTO IN (@PUESTOS)
	--AND [FICHAJES].AREA IN (@AREAS)
	--AND [FICHAJES].SECTOR IN (@SECTORES)
	--AND [FICHAJES].[MINUTOS] > [FICHAJES].[TOLERANCIA] 
	AND (ISNULL(GESINC.JUSTIFICA, 0) = 0
	OR	CASE 
			WHEN ([FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]) > 0 THEN 'Tarde'
			WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
			ELSE ''
	END <> ISNULL(GESINC.MOTIVO, ''))
GROUP BY
	FICHAJES.HORAREG
	, [FICHAJES].LEGAJO
	, INGRESOS.INGRESO
	, EGRESOS.EGRESO
	, [FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3)
	--, [FICHAJES].ESTTRANS
	--, [FICHAJES].PCONTROL
	--, LTRIM(RTRIM([PTOCONTROL].[DESCR]))
	--, [FICHAJES].CODPUESTO
	--, LTRIM(RTRIM([PUESTOS].[DESCR]))
	--, [FICHAJES].AREA
	--, [FICHAJES].SECTOR
	, [FICHAJES].INGRESOESQUEMA
	, FICHAJES.TOLERANCIA
	, [FICHAJES].MINUTOS
	, [FICHAJES].[EGRESOESQUEMA]
	, GESINC.MOTIVO
	, [FICHAJES].ASIGESQ
ORDER BY
	[FICHAJES].LEGAJO
	--, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3)
	, [FICHAJES].FCHREG
	, [FICHAJES].HORAREG
	, [FICHAJES].[CAPENOM]
	, TIPO
	, [FICHAJES].ASIGESQ
	--, [FICHAJES].ESTTRANS
	--, [FICHAJES].PCONTROL
	--, LTRIM(RTRIM([PTOCONTROL].[DESCR]))
	--, [FICHAJES].CODPUESTO
	--, LTRIM(RTRIM([PUESTOS].[DESCR]))
	--, [FICHAJES].AREA
	--, [FICHAJES].SECTOR
	--, [FICHAJES].INGRESOESQUEMA
	--, FICHAJES.TOLERANCIA
	--, [FICHAJES].MINUTOS			
	--, [FICHAJES].[EGRESOESQUEMA]
	

