--SELECT CODDIAS, DESCR FROM ZL.DIASDEPERMISO

SELECT 
  ZL.Aatmda.Razonsoc AS RS
  , ZL.Aatmda.Regpor REGPOR
  , ZL.Aatmda.CODIN COMPROBANTE
  , convert(varchar, ZL.Aatmda.FALTAFW, 103) FECHA
  , convert(varchar, ZL.Aatmda.CMPFECFIN, 103) FECHAPERMISO
  , ZL.DIASDEPERMISO.DESCR CANTDIASPERMISO
FROM 
  ZL.Aatmda
  LEFT JOIN ZL.DIASDEPERMISO ON ZL.DIASDEPERMISO.CODDIAS = ZL.Aatmda.CODDIAS
WHERE 
  ZL.Aatmda.CODDIAS <> 0
  AND (ZL.Aatmda.FALTAFW+CONVERT(INT, ZL.DIASDEPERMISO.DESCR)) <> ZL.Aatmda.CMPFECFIN

update ZL.Aatmda set
  ZL.Aatmda.CMPFECFIN = dateadd(day, (select ZL.DIASDEPERMISO.DESCR from ZL.DIASDEPERMISO where ZL.DIASDEPERMISO.coddias = zl.Aatmda.CODDIAS), zl.Aatmda.faltafw)
  WHERE ZL.Aatmda.CODDIAS > 0