DECLARE @FECHADESDE DATETIME, @FECHAHASTA DATETIME;
SET @FECHADESDE = '20130731'; SET @FECHAHASTA = '20130731';

SELECT
	DISTINCT
	[FICHAJES].LEGAJO
	, [FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3) AS FECHA
	, [FICHAJES].HORAREG
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
		ELSE NULL
	END AS [TIPO]
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].[INGRESOESQUEMA] 
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN [FICHAJES].[EGRESOESQUEMA]  
		ELSE NULL
	END AS 'HORARIOESQUEMA'
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN DATOS.TOLERANCIA
		ELSE 0
	END AS [TOLERANCIA]
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].MINUTOS - DATOS.TOLERANCIA
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) 
		ELSE 0
	END AS DESVIO
	, CASE 
		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN CASE
															WHEN (DATOS.MINUTOS - DATOS.TOLERANCIA) > 0 THEN 'Tarde'
															WHEN (DATOS.MINUTOS - DATOS.TOLERANCIA) <= 0 THEN 'Temprano'
															ELSE ''
														END
		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN	CASE
															WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
															WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) <= 0 THEN 'Salida correcta'
															ELSE ''
														END
		ELSE NULL
	END AS 'TIPOINCUMPLIMIENTO'
	, DATOS.CODPUESTO as CODPUESTO
	, DATOS.AREA as AREA 
	, DATOS.SECTOR as SECTOR 
	, DATOS.ESQUEMA as  ESQUEMA
	, DATOS.ASIGESQ as ASIGESQ
	, DATOS.INGRESOESQUEMA as INGRESOESQUEMA
	, DATOS.EGRESOESQUEMA as EGRESOESQUEMA
	--,  as TOLERANCIA
	, DATOS.MINUTOS as MINUTOS
	, CONVERT(DATETIME, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 120), 102) as FECHA
	, YEAR([FICHAJES].FCHREG) as ANIO
	, MONTH([FICHAJES].FCHREG) as MES
	, DAY([FICHAJES].FCHREG)  as DIA
FROM
	[ZL].[ZNFICHAJE] AS [FICHAJES]
	LEFT JOIN (SELECT * FROM [Objetivos].[func_RRHH_FichajeAplicarEsquemas](CONVERT(VARCHAR(8), @FECHADESDE, 112), CONVERT(VARCHAR(8), @FECHAHASTA, 112))) AS DATOS ON DATOS.COD = [FICHAJES].[COD]
	LEFT JOIN [ZL].[ZNPCONTROL] AS [PTOCONTROL] ON [PTOCONTROL].[COD] = [FICHAJES].[PCONTROL]
	LEFT JOIN (SELECT LEGAJO, MIN(HORAREG) AS INGRESO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112) AS FECHA FROM ZL.ZNFICHAJE GROUP BY LEGAJO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112)) AS INGRESOS ON INGRESOS.LEGAJO = [FICHAJES].[LEGAJO] AND INGRESOS.FECHA = [FICHAJES].[FECHA]
	LEFT JOIN (SELECT LEGAJO, MAX(HORAREG) AS EGRESO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112) AS FECHA FROM ZL.ZNFICHAJE GROUP BY LEGAJO, CONVERT(DATETIME, CONVERT(VARCHAR(8), FCHREG, 112), 112)) AS EGRESOS ON EGRESOS.LEGAJO = [FICHAJES].[LEGAJO] AND EGRESOS.FECHA = [FICHAJES].[FECHA]
	LEFT JOIN (SELECT
					NUMERO
					, LEG
					, CASE INCHLAB
						WHEN 'AUS' THEN 'Ausencia'
						WHEN 'LLT' THEN 'Tarde'
						WHEN 'SAT' THEN 'Salida temprana'
						ELSE ''
					END AS MOTIVO
					, JUSTIFICA
					, FECHAF
					, FECHAI
					--, *
				FROM 
					ZL.GESINC) AS GESINC ON GESINC.LEG = FICHAJES.LEGAJO AND GESINC.FECHAI >= [FICHAJES].FECHA AND GESINC.FECHAF <= [FICHAJES].FECHA
WHERE
	[FICHAJES].FECHA >= @FECHADESDE 
	AND [FICHAJES].FECHA <= @FECHAHASTA 
	--AND	CASE 
	--		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
	--		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
	--		ELSE NULL
	--	END IS NOT NULL
	--AND 
	--(CASE 
	--	WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN [FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]
	--	ELSE 0
	--END	> 0
	--OR CASE 
	--	WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN DATEDIFF(MINUTE, [FICHAJES].[EGRESOESQUEMA], EGRESOS.EGRESO) 
	--	ELSE 0
	--END	< 0)
	--AND (ISNULL(GESINC.JUSTIFICA, 0) = 0
	--OR	CASE 
	--		WHEN ([FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]) > 0 THEN 'Tarde'
	--		WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
	--		ELSE ''
	--END <> ISNULL(GESINC.MOTIVO, ''))
	--AND [FICHAJES].CODPUESTO IN (@PUESTOS)
	--AND [FICHAJES].AREA IN (@AREAS)
	--AND [FICHAJES].SECTOR IN (@SECTORES)
	--AND [FICHAJES].[MINUTOS] > [FICHAJES].[TOLERANCIA] 
	--AND CASE 
	--	WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN CASE
	--								WHEN ([FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]) > 0 THEN 'Tarde'
	--								WHEN ([FICHAJES].MINUTOS - [FICHAJES].[TOLERANCIA]) <= 0 THEN 'Temprano'
	--								ELSE ''
	--							END
	--	WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN	CASE
	--								WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) >  0 THEN 'Salida temprana'
	--								WHEN DATEDIFF(MINUTE, EGRESOS.EGRESO, [FICHAJES].[EGRESOESQUEMA]) <= 0 THEN 'Salida correcta'
	--								ELSE ''
	--							END
	--	ELSE NULL
	--END IN (@TIPOINCUMPLIMIENTO)
	--AND [FICHAJES].LEGAJO IN (@LEGAJO)
	--AND	CASE 
	--		WHEN [FICHAJES].HORAREG = INGRESOS.INGRESO THEN 'Entrada'
	--		WHEN [FICHAJES].HORAREG = EGRESOS.EGRESO THEN 'Salida'
	--		ELSE NULL
	--	END IN (@TIPO)
GROUP BY
	FICHAJES.HORAREG
	, [FICHAJES].LEGAJO
	, INGRESOS.INGRESO
	, EGRESOS.EGRESO
	, [FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, CONVERT(VARCHAR(10), [FICHAJES].FCHREG, 3)
	, [FICHAJES].INGRESOESQUEMA
	, FICHAJES.TOLERANCIA
	, [FICHAJES].MINUTOS
	, [FICHAJES].[EGRESOESQUEMA]
	, DATOS.ESQUEMA --[FICHAJES].[ESQUEMA]
	, DATOS.CODPUESTO 
	, DATOS.AREA  
	, DATOS.SECTOR 
	, DATOS.ESQUEMA 
	, DATOS.ASIGESQ 
	, DATOS.INGRESOESQUEMA 
	, DATOS.EGRESOESQUEMA 
	, DATOS.TOLERANCIA 
	, DATOS.MINUTOS
--UNION
--	SELECT 
--		LEGAJO
--		, APELLIDOYNOMBRES 
--		,NULL
--		, FECHA 
--		,NULL
--		, NULL
--		, NULL
--		, NULL
--		, NULL
--		, TIPOINCUMPLIMPIENTO 
--		, NULL 
--	FROM 
--		[OBJETIVOS].[FUNC_RRHH_INCUMPLIMIENTOSAUSENCIAS]( '', @FECHADESDE , @FECHAHASTA  )      

ORDER BY
	[FICHAJES].[CAPENOM]
	, [FICHAJES].FCHREG
	, [FICHAJES].LEGAJO
	, [FICHAJES].HORAREG
	, TIPO
	, DATOS.ESQUEMA --[FICHAJES].[ESQUEMA]
