DECLARE @ESQUEMA INT; SET @ESQUEMA = 3;

SELECT
	[JORNADALABORAL].CODIN AS 'Esquema'
	, RTRIM(LTRIM([JORNADALABORAL].DESCR)) AS 'Descripcion'
	, [JORNADALABORAL].AREA AS 'Area'
	, [JORNADALABORAL].SECTOR AS 'Sector'
	, [JORNADALABORAL].TMAXLLEGTJ AS 'Tolerancia'
	, [JORNADALABORAL].Obs AS 'Observacion'
	, CASE (DATENAME(DW, [DETALLEJORNADALABORAL].DIA))
		WHEN 'Monday'    THEN 'Lunes'
		WHEN 'Tuesday'   THEN 'Martes'
		WHEN 'Wednesday' THEN 'Miércoles'
		WHEN 'Thursday'  THEN 'Jueves'
		WHEN 'Friday'    THEN 'Viernes'
		WHEN 'Saturday'  THEN 'Sábado'
		WHEN 'Sunday'    THEN 'Domingo'
	END AS 'Dia'
	, [DETALLEJORNADALABORAL].HORAING AS 'HoraIngreso'
	, [DETALLEJORNADALABORAL].HORAEGR AS 'HoraEgreso'
	, [DETALLEJORNADALABORAL].HORLAB AS 'HorasLaborables'
	, CASE [DETALLEJORNADALABORAL].FERIADOS 
		WHEN 0 THEN 'No'
		ELSE 'Sí'
	END AS 'Feriados'
	, [DETALLEJORNADALABORAL].OBS AS 'Notas'
FROM
	[ZL].[SALRGDH] AS [JORNADALABORAL]
	LEFT JOIN (SELECT 
					[ZL].[DTSALRGDH].Codint 
					, [ZL].[DTSALRGDH].DIA
					, [ZL].[DTSALRGDH].HORAING 
					, [ZL].[DTSALRGDH].HORAEGR 
					, [ZL].[DTSALRGDH].HORLAB 
					, [ZL].[DTSALRGDH].FERIADOS
					, [ZL].[DTSALRGDH].OBS 
				FROM 
					[ZL].[DTSALRGDH]) AS [DETALLEJORNADALABORAL] ON [DETALLEJORNADALABORAL].CODINT = [JORNADALABORAL].CODIN
WHERE
	[JORNADALABORAL].CODIN = @ESQUEMA
	
/*SELECT
	DISTINCT
	[JORNADALABORAL].CODIN AS 'ESQUEMA'
FROM
	[ZL].[SLARGDH] AS [JORNADALABORAL]
ORDER BY
	[JORNADALABORAL].CODIN*/
	
SELECT * FROM [ZL].[DTSALRGDH]