SELECT
	RESULTADOS.HOY
	, RESULTADOS.NUMERO
	, RESULTADOS.REGPOR
FROM (
	SELECT
		DISTINCT
		A.HOY AS HOY
		, ISNULL(ZL.IYDFUNCIONALIDADULTIMOESTADO.FUNCIONALIDAD, ZL.IYDFUNCIONALIDADETAPAULTIMA.FUNCIONALIDAD) AS NUMERO
		, ISNULL(ZL.IYDFUNCIONALIDADULTIMOESTADO.ESTADO, ZL.IYDFUNCIONALIDADETAPAULTIMA.COMPROBANTE) AS MARCA
		, ISNULL(RTRIM(F.REGPOR), '') + ISNULL(RTRIM(G.REGPOR), '') + ISNULL(RTRIM(H.REGPOR), '') + ISNULL(RTRIM(I.REGPOR), '') AS REGPOR
	FROM
		(SELECT CONVERT(VARCHAR, GETDATE()-1, 103) AS HOY) AS A
		LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOESTADO ON CONVERT(VARCHAR, ZL.IYDFUNCIONALIDADULTIMOESTADO.FECHA, 103) = A.HOY
		LEFT JOIN ZL.IYDFUNCIONALIDADETAPAULTIMA ON CONVERT(VARCHAR, ZL.IYDFUNCIONALIDADETAPAULTIMA.FECHA, 103) = A.HOY
		LEFT JOIN (SELECT MAX(CODIGO) AS CODIGO, NUMERO, FUNC FROM ZL.REQCLIDET GROUP BY NUMERO, FUNC) AS B ON B.FUNC = ZL.IYDFUNCIONALIDADULTIMOESTADO.FUNCIONALIDAD
		LEFT JOIN (SELECT MAX(CODIGO) AS CODIGO, NUMERO, FUNC FROM ZL.REQCLIDET GROUP BY NUMERO, FUNC) AS C ON C.FUNC = ZL.IYDFUNCIONALIDADETAPAULTIMA.FUNCIONALIDAD
		LEFT JOIN (SELECT MAX(CODIGO) AS CODIGO, REQID, FUNC FROM [ZL].[ZL].[REQIDDET] GROUP BY REQID, FUNC) AS D ON D.FUNC = ZL.IYDFUNCIONALIDADULTIMOESTADO.FUNCIONALIDAD
		LEFT JOIN (SELECT MAX(CODIGO) AS CODIGO, REQID, FUNC FROM [ZL].[ZL].[REQIDDET] GROUP BY REQID, FUNC) AS E ON E.FUNC = ZL.IYDFUNCIONALIDADETAPAULTIMA.FUNCIONALIDAD
		LEFT JOIN ZL.REQUER AS F ON F.CODIGO = D.FUNC
		LEFT JOIN ZL.REQUER AS G ON G.CODIGO = E.FUNC
		LEFT JOIN ZL.PNCEREQ AS H ON H.CODIN = B.FUNC
		LEFT JOIN ZL.PNCEREQ AS I ON I.CODIN = C.FUNC
	WHERE
		ZL.IYDFUNCIONALIDADETAPAULTIMA.FUNCIONALIDAD <> ZL.IYDFUNCIONALIDADULTIMOESTADO.FUNCIONALIDAD
	ORDER BY
		NUMERO
	UNION ALL
	SELECT
		DISTINCT
		A.HOY AS HOY
		, ISNULL(ZL.IYDBUGULTIMOESTADO.BUG, ZL.IYDBUGETAPAULTIMA.BUG) AS NUMERO
		, ISNULL(ZL.IYDBUGULTIMOESTADO.ESTADO, ZL.IYDBUGETAPAULTIMA.COMPROBANTE) AS MARCA
		, ISNULL(B.REGPOR, '') + ISNULL(C.REGPOR, '') + ISNULL(F.REGPOR, '') + ISNULL(G.REGPOR, '') + ISNULL(ZL.PNCEREQ.REGPOR, '')
	FROM
		(SELECT CONVERT(VARCHAR, GETDATE()-1, 103) AS HOY) AS A
		LEFT JOIN ZL.IYDBUGULTIMOESTADO ON CONVERT(VARCHAR, ZL.IYDBUGULTIMOESTADO.FECHA, 103) = A.HOY
		LEFT JOIN ZL.IYDBUGETAPAULTIMA ON CONVERT(VARCHAR, ZL.IYDBUGETAPAULTIMA.FECHA, 103) = A.HOY
		LEFT JOIN ZL.REQCLIDET AS B ON B.BUG = ZL.IYDBUGULTIMOESTADO.BUG
		LEFT JOIN ZL.REQCLIDET AS C ON C.BUG = ZL.IYDBUGETAPAULTIMA.BUG
		LEFT JOIN ZL.REQINCDET AS F ON F.BUG = ZL.IYDBUGETAPAULTIMA.BUG
		LEFT JOIN ZL.REQINCDET AS G ON G.BUG = ZL.IYDBUGULTIMOESTADO.BUG
		LEFT JOIN ZL.PNCEREQ ON ZL.PNCEREQ.CODIN = B.NUMERO OR ZL.PNCEREQ.CODIN = C.NUMERO
		LEFT JOIN ZL.PNCEREQ ON ZL.PNCEREQ.CODIN = B.NUMERO OR ZL.PNCEREQ.CODIN = C.NUMERO
	WHERE
		ZL.IYDBUGETAPAULTIMA.BUG <> ZL.IYDBUGULTIMOESTADO.BUG
		AND (
			B.REGPOR IS NOT NULL 
			OR C.REGPOR IS NOT NULL
			OR F.REGPOR IS NOT NULL
			OR G.REGPOR IS NOT NULL )
		) AS RESULTADOS
ORDER BY
	RESULTADOS.NUMERO
--SELECT * FROM ZL.PNCEREQ order by codin