declare @ESTADO AS INT
  ,@REGPOR AS VARCHAR(50);

/*@ESTADO = 0/1 Abiertos/Cerrados*/

SET @ESTADO = 0;
SET @REGPOR = '';

SELECT 
  [REGISSU].[CODIN]
  , [REGISSU].[CMPFECINI]
  , [REGISSU].[REGPOR]
  , '' AS [TITULO]      
  , ZL.PRODZL.[CCOD]
  , CONVERT(VARCHAR(50), PRODZL.DESCR) AS PRODUCTO
  , [REGISSU].[CBUILD]
  , CONVERT(VARCHAR(MAX), [REGISSU].[DESISSU]) AS [DESISSU]
  , [REGISSU].[MSGSIS]      
  , [REGISSU].[CSEVE]
  , ISSEVE.DES AS SEVERIDAD
  , [REGISSU].[COCURR]
  , ISSOCU.DES
  , [REGISSU].[CODEOS]
  , CEDOSS.DESCR AS EDICIONSO
  , [REGISSU].[CODESTI]
  , CESTORG.DESCR AS ESTILO      
  , [REGISSU].[CODMOTOR]
  , CMOTORG.DESCR AS MOTOR
  , [REGISSU].[CODOS]
  , COSS.DESCR
  , [REGISSU].[CODPLAT]
  , CPLATOSS.DESCR AS PLATAFORMAOS
  , DIRURL      
  --TAREASISS.ASIGNT
  , TEST.NOTA
  , TEST.LINEA
  , TEST.MENAJE
  , TEST.SOLAPA
  --BUGSASOCIDADOS
  , EVALUACIONES.*
  , ZL.estadoIssue(ZL.DTRGISS.CODIGO) AS [ESTADO]
FROM 
  ZL.REGISSU [REGISSU]
  INNER JOIN ZL.DTRGISS ON ZL.DTRGISS.CODIGO = [REGISSU].[CODIN] AND ZL.estadoIssue(ZL.DTRGISS.CODIGO) = @ESTADO
  LEFT JOIN ZL.DIssueProd ON ZL.DIssueProd.CODINT = ZL.DTRGISS.CODIGO
  LEFT JOIN ZL.PRODZL   ON PRODZL.CCOD = ZL.DIssueProd.[CODPROD]
  LEFT JOIN ZL.CMOTORG  ON CMOTORG.CCOD = [REGISSU].[CODMOTOR]
  LEFT JOIN ZL.CESTORG  ON CESTORG.CCOD = [REGISSU].[CODESTI]
  LEFT JOIN ZL.COSS     ON ZL.COSS.CCOD = [REGISSU].[CODOS]
  LEFT JOIN ZL.CPLATOSS ON CPLATOSS.CCOD = [REGISSU].[CODPLAT]
  LEFT JOIN ZL.CEDOSS   ON CEDOSS.CCOD = [REGISSU].[CODEOS]
  LEFT JOIN ZL.ISSEVE   ON ISSEVE.COD = [REGISSU].[CSEVE]
  LEFT JOIN ZL.ISSOCU   ON ISSOCU.COD = [REGISSU].[COCURR]
  --LEFT JOIN ZL.DTRGISS  AS TAREASISS ON [REGISSU].CODIN= TAREASISS.CODIGO
  LEFT JOIN ZL.DTTESTS AS TEST ON TEST.DCODIGO = [REGISSU].CODIN
  LEFT JOIN 
    (SELECT 
        D.CODIGO
        , E.FALTAFW
        , D.ISSUE
        ,	CASE 
            WHEN D.BUG <> 0 THEN 'BUG' 
            ELSE 
              CASE 
                WHEN D.BUG = 0 AND D.FUNC <> 0 THEN 'FUNC' 
                ELSE '' 
            END 
        END AS ENTIDADRELA
        , CASE 
            WHEN D.BUG <> 0 THEN D.BUG 
		        ELSE 
		          CASE 
		            WHEN D.BUG = 0 AND D.FUNC <> 0 THEN D.FUNC 
		            ELSE 0 
            END 
        END AS ENTIDADRELACODIGO
      , P.DESCRIP AS PROYECTOISSUE
      , ES.DESCR AS SUGERENCIAESTADOISSUE
      , CASE 
          WHEN D.BUG <> 0 THEN BUE.ESTADO 
          ELSE 
            CASE 
              WHEN D.BUG = 0 AND D.FUNC <> 0 THEN FUE.ESTADO 
              ELSE '' 
          END 
      END AS ENTIDADRELAESTADO
    FROM 
      ZL.DETEVISS AS D 
      JOIN ZL.EVALISSUES AS E ON E.CODIGO = D.CODIGO
      LEFT JOIN ZL.PROY AS P ON P.CODIGO = D.PROY 
      JOIN ZL.ESTDET AS ES ON ES.CODIGO = D.FUNCEST
      LEFT JOIN ZL.IYDBUGULTIMOESTADO AS BUE ON BUE.BUG = D.BUG
      LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOESTADO AS FUE ON FUE.FUNCIONALIDAD = D.FUNC) AS EVALUACIONES ON EVALUACIONES.ISSUE = [REGISSU].CODIN
WHERE 
  LTRIM(RTRIM([REGISSU].[REGPOR])) IN ('AMOLINA', 'DCASAL', 'DFERNANDEZ', 'GCORIA', 'JREBOLLEDO', 'MRUSSO', 'NAMOR', 'NREBEQUI')
  AND LTRIM(RTRIM(ZL.PRODZL.[CCOD])) IN ('0002', '0006', '0010', '0011')
  
