DECLARE @DEMO AS INT;

SET @DEMO = 163;

SELECT   
  F.CODIGO
  , F.NOMBRE
  , F.DESCRIP
  , F.OBS
  , F.REGPOR AS FUNCIONALIDADREGPOR, F.FALTAFW AS FUNCFECHAALTA
  , M.DESCRIP AS MAGNITUD
  , UP.PROY AS ULTPROYCOD, UP.PROYECTO AS ULTPROYNOMBRE ,UE.FUNCEST AS ULTFUNCESTCD, UE.ESTADO AS ULTFUNCESTADNOMBRE
  , [ANALISIS].[CODIGO] AS [ANÁLISIS NÚMERO]
  , [ANALISIS].[FALTAFW] AS [ANÁLISIS FECHA]
  , ANALISIS.REGPOR AS [ANÁLISIS REGPOR]
  , [ANALISIS].[EQUIPO] AS [ANÁLISIS EQUIPO]
  , [PROY].[DESCRIP] AS ANALISISPROYECTO
  , ANALISIS.DOCUMENTO AS ANALISISDOCUMENTOFUNCIONAL
  , EA.DESCR AS ANALISISESTADO
  , ANALISIS.CRIT AS [ANÁLISIS CRITERIO]
  , ANASIS.ASIST AS [ANALISIS ASISTENTES]
  , REQUERIMIENTOS.[TIPO DE REQUERIMIENTO]
  , REQUERIMIENTOS.[REQ NÚMERO]
  , REQUERIMIENTOS.[REQ ALTA]
  , REQUERIMIENTOS.[REQ REGPOR]
  , REQUERIMIENTOS.[REQ ASUNTO/TÍTULO]
  , REQUERIMIENTOS.[REQ DETALLE]
  , REQUERIMIENTOS.[REQ OBSERVACIÓN]
  , REQUERIMIENTOS.[CCLIENTE]
  , REQUERIMIENTOS.[CLIENTE NOMBRE]
  , REQUERIMIENTOS.PRODCOD
  , REQUERIMIENTOS.PRODUCTO
  , REQUERIMIENTOS.[PRE-ANÁLISIS]
  , REQUERIMIENTOS.[FUNCEST]
  , REQUERIMIENTOS.[PRE-ANÁLISIS SUGERENCIA ESTADO]
  , REQUERIMIENTOS.[PROY]
  , REQUERIMIENTOS.[PRE-ANÁLISIS PROYECTO]
  , [PRE_ANAL].[FALTAFW] AS [PRE-ANÁLISIS FECHA]
  , ISNULL(FUNCHORAS.SUMAESTIMADAS,0) AS SUMAESTIMADAS
  , [PRE_ANAL].REGPOR AS [PRE-ANÁLISIS REGPOR]
  , PREANASIS.ASIST AS [PRE_ANALISIS ASISTENTES]
  , DP.CCOD AS FUNCPRODCOD, DP.DESCR AS FUNCPRODDESCR
  , TEMAS.TEMAID, TEMAS.NOMBRE AS TEMANOMBRE
  , DTFCDEP.FUNC AS FUNCDEP, DTFCDEP.NOMBRE AS FUNCDEPNOMBRE
  , [FUNCFACDET].[FACTID] AS [FACTIBILIDAD NÚMERO]
  , [FACTI].[FALTAFW] AS [FACTIBILIDAD FECHA]
  , [FACTI].REGPOR AS [FACTIBILIDAD REGPOR]
  , FACTI.FACTOBS AS [FACTIBILIDAD OBS]
  , ZL.FUNCIONES.ALLTRIM([ESTDET].DESCR) AS [FACTIBILIDAD ESTADO]
  , FACTIASIS.ASIST AS [FACTIBILIDAD ASISTENTES]
  , TIPFUNCOM.DESCRIP AS TIPOFUNC
  , FCPREEST.NUMERO AS PREESTIMANUMERO
  , FCPREEST.REGPOR AS PREESTIMAREGPOR
  , FCPREEST.FECREG AS PREESTIMAFECHA
  , FCPREEST.OBS AS PREESTIMAOBS
  , DESTIM.HORAS AS PREESTIMAHORAS
	, REUNPRIO.NUMERO AS REUNPRIONUMERO
	, REUNPRIO.FECREG AS REUNPRIOFECREG
	, REUNPRIO.REGPOR AS REUNPRIOREGPOR
	, REUNPRIO.OBS AS REUNPRIOOBS
  , DETORDPRIO.NITEM AS REUNPRIOORDEN
  , PRIOASIS.ASIST AS REUNPRIOASIST
  , IDD.CODIN AS [DEMO NÚMERO]
  , IDD.FCHREUN AS [DEMO FECHA]
  , DDF.AVANCE AS [DEMO AVANCE]
  , CASE 
      WHEN DDF.ORDEN = 0 THEN DDF.NITEM 
      ELSE DDF.ORDEN 
  END AS DEMOORDEN
  , FUNCDEP2.CODINT AS FUNCDEP2,FDEP2.NOMBRE AS FUNCDEP2NOMBRE
  , DDF.COMENT AS [DEMO COMMENT]
  , ISNULL(UPREESTIM.[PREESTIMACION HORAS],0) AS [PREESTIMACION HORAS]
  , ISNULL(HORAS.HORAS,0) AS TOTALHORASZL
  , FSP.SPRINTS
  /************************** AGREGADO POR HDC 28/02/2013 ***************************/
  , ISNULL(ISSUES.CODIN, 0) AS [ISSUE NRO]
  , ISNULL('Detalle: '+CONVERT(VARCHAR(MAX), ISSUES.DESISSU), '') AS [ISSUE DETALLE]
  , ISNULL(CONVERT(VARCHAR(10), ISSUES.FALTAFW, 103), '') AS [ISSUE FECHA ALTA]
  , LTRIM(RTRIM(ISNULL(ISSUES.REGPOR, ''))) AS [ISSUE REGPOR]
  /**********************************************************************************/
FROM 
  ZL.DTIYDEMF AS DDF  	
  JOIN ZL.IYDDEMOS AS IDD ON IDD.CODIN = DDF.CODINT
  JOIN [ZL].[ZL].[FCOMER] AS F ON DDF.FUNC = F.CODIGO
  /************************** AGREGADO POR HDC 28/02/2013 ***************************/
  LEFT JOIN
    (SELECT 
      ZL.DETEVISS.FUNC
      , ZL.REGISSU.CODIN
      , ZL.REGISSU.DESISSU
      , ZL.REGISSU.FALTAFW
      , ZL.REGISSU.REGPOR
    FROM 
      ZL.FCOMER 
      INNER JOIN ZL.DETEVISS ON ZL.DETEVISS.FUNC = ZL.FCOMER.CODIGO
      INNER JOIN ZL.REGISSU ON ZL.REGISSU.CODIN = ZL.DETEVISS.ISSUE) AS ISSUES ON ISSUES.FUNC = F.CODIGO
  /**********************************************************************************/
  LEFT JOIN ZL.DTFCDEP AS FUNCDEP2 ON FUNCDEP2.FUNC = F.CODIGO
  LEFT JOIN ZL.FCOMER AS FDEP2 ON FDEP2.CODIGO = FUNCDEP2.CODINT
  LEFT JOIN ZL.MAGNITUD AS M ON M.CCOD = F.MAGN
  LEFT JOIN [ZL].[IYDFUNCIONALIDADULTIMOPROYECTO] AS UP ON UP.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOESTADO AS UE ON UE.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN ZL.IYDDURACIONSPRINTSFUNCBUGS AS FSP ON FSP.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN [ZL].[ZL].[ANALISIS] ON F.CODIGO = [ANALISIS].[FUNC]
  LEFT JOIN [ZL].[ZL].[ESTDET] AS EA ON ANALISIS.FUNCEST = EA.CODIGO
  LEFT JOIN [ZL].[ZL].[PROY] ON [ANALISIS].[PROY] = [PROY].[CODIGO]
  LEFT JOIN [ZL].[ZL].[FUNCFACDET] ON F.[CODIGO] = [FUNCFACDET].[FUNCID]
  LEFT JOIN [ZL].[ZL].[FACTI] ON [FUNCFACDET].[FACTID] = [FACTI].[CODIGO]
  LEFT JOIN [ZL].[ZL].[ESTDET] ON [FUNCFACDET].[FUNCEST] = [ESTDET].[CODIGO]
  LEFT JOIN
    (SELECT
        'Req. Cliente' AS [TIPO DE REQUERIMIENTO]
        ,[PNCEREQ].[CODIN] AS [REQ NÚMERO]
        ,[PNCEREQ].[FALTAFW]+[PNCEREQ].[HALTAFW] AS [REQ ALTA]
        ,[PNCEREQ].[REGPOR] AS [REQ REGPOR]
        ,[REQCLIDET].[FUNC] AS FUNCIONALIDAD
        ,[PNCEREQ].[ASUNTO] AS [REQ ASUNTO/TÍTULO]
        ,[PNCEREQ].[CMPCONSULT] AS [REQ DETALLE]
        ,''AS [REQ OBSERVACIÓN]
        ,[PNCEREQ].[CCLIENTE]
        ,[CLIENTES].[CMPNOMBRE] AS [CLIENTE NOMBRE]
        ,[PNCEREQ].[CPCOD] AS PRODCOD
        ,[PRODZL].[DESCR] AS PRODUCTO
        ,[REQCLIDET].[CODIGO] AS [PRE-ANÁLISIS]
        ,[REQCLIDET].[FUNCEST]
        ,[ESTDET].DESCR AS [PRE-ANÁLISIS SUGERENCIA ESTADO]
        ,[REQCLIDET].[PROY]
        ,[PROY].[DESCRIP] AS [PRE-ANÁLISIS PROYECTO]
    FROM 
        [ZL].[ZL].[PNCEREQ]
        JOIN [ZL].[ZL].[REQCLIDET] ON [PNCEREQ].[CODIN] = [REQCLIDET].[NUMERO]
        LEFT JOIN [ZL].[ZL].[CLIENTES] AS [CLIENTES] ON [CLIENTES].[CMPCODIGO] = [PNCEREQ].[CCLIENTE]
        LEFT JOIN [ZL].[ZL].[PRODZL] ON [PNCEREQ].[CPCOD] = [PRODZL].[CCOD]
        LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQCLIDET].[FUNCEST] = [ESTDET].[CODIGO]
        LEFT JOIN [ZL].[ZL].[PROY] ON [REQCLIDET].[PROY] = [PROY].[CODIGO]
    WHERE 
        [REQCLIDET].[FUNC] <> 0
    UNION ALL
    SELECT
        'Req. I+D' AS [TIPO DE REQUERIMIENTO]
        , [REQUER].[CODIGO] AS [REQ NÚMERO]
        , [REQUER].[FALTAFW]+[REQUER].[HALTAFW] AS [REQ ALTA]
        , [REQUER].[REGPOR] AS [REQ REGPOR]
        , [REQIDDET].[FUNC]  AS FUNCIONALIDAD
        , [REQUER].[TITULO] AS [REQ ASUNTO/TÍTULO]
        , [REQUER].[DESCR] AS [REQ DETALLE]
        , [REQUER].[OBS] AS [REQ OBSERVACIÓN]
        , '' AS CCLIENTE
        , '' AS [CLIENTE NOMBRE]
        , '' AS PRODUCTOCOD
        , '' AS PRODUCTO
        , [REQIDDET].[CODIGO] AS [PRE-ANÁLISIS]
        , [REQIDDET].[FUNCEST]
        , [ESTDET].DESCR AS [PRE-ANÁLISIS SUGERENCIA ESTADO]
        , [REQIDDET].[PROY]
        , [PROY].[DESCRIP] AS [PRE-ANÁLISIS PROYECTO]
    FROM 
        [ZL].[ZL].[REQUER]
        JOIN [ZL].[ZL].[REQIDDET] ON [REQUER].[CODIGO] = [REQIDDET].[REQID]
        LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQIDDET].[FUNCEST] = [ESTDET].[CODIGO]
        LEFT JOIN [ZL].[ZL].[PROY] ON [REQIDDET].[PROY] = [PROY].[CODIGO]
    WHERE 
        [REQIDDET].[FUNC] <> 0
    UNION ALL
    SELECT
        'Incidente' AS [TIPO DE REQUERIMIENTO]
        , [INCIDS].[CODIN] AS [REQ NÚMERO]
        , [INCIDS].[CMPFECINI] AS [REQ ALTA]
        , UT.REGPOR AS [REQ REGPOR]
        , [REQINCDET].[FUNC]  AS FUNCIONALIDAD
        , ZL.FUNCIONES.ALLTRIM([TIPIF].[CDESC]) + ' // ' + ZL.FUNCIONES.ALLTRIM([TIPIF2].[CDESC])  + '//' + ZL.FUNCIONES.ALLTRIM(UT.CTITULO) AS [REQ ASUNTO/TÍTULO]
        , [INCIDS].[CMPCONSULT] AS [REQ DETALLE]
        , '' AS [REQ OBSERVACIÓN]
        , [INCIDS].[CCLIENTE]
        , [CLIENTES].[CMPNOMBRE] AS [CLIENTE NOMBRE]
        , [INCIDS].[CPROD]
        , [PRODZL].[DESCR] AS PRODUCTO
        , [REQINCDET].[CODIGO] AS [PRE-ANÁLISIS]
        , [REQINCDET].[FUNCEST]
        , [ESTDET].DESCR AS [PRE-ANÁLISIS SUGERENCIA ESTADO]
        , [REQINCDET].[PROY]
        , [PROY].[DESCRIP] AS [PRE-ANÁLISIS PROYECTO]
    FROM
        [ZL].[ZL].[INCIDS]
        LEFT JOIN [ZL].[ZL].[TIPIF] ON [INCIDS].[CMPTIPIF] = [TIPIF].[CCOD]
        LEFT JOIN [ZL].[ZL].[TIPIF2] ON [INCIDS].[CMPSTIP] = [TIPIF2].[CCOD]
        JOIN [ZL].[ZL].[REQINCDET] ON [INCIDS].[CODIN] = [REQINCDET].[INC_ID]
        LEFT JOIN [ZL].[ZL].[CLIENTES] ON [CLIENTES].[CMPCODIGO] = [INCIDS].[CCLIENTE]
        LEFT JOIN [ZL].[ZL].[PRODZL] ON [INCIDS].[CPROD] = [PRODZL].[CCOD]
        LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQINCDET].[FUNCEST] = [ESTDET].[CODIGO]
        LEFT JOIN [ZL].[ZL].[PROY] ON [REQINCDET].[PROY] = [PROY].[CODIGO]
        LEFT JOIN
          (SELECT 
            ULTREGPOR.INC
            , ZL.ZLTASK.REGPOR
            , ZLTASK.CTITULO
          FROM
            ZL.ZLTASK
            JOIN
              (SELECT 
                MAX(NUMERO) AS TAREA
                , CODIGO AS INC
              FROM 
                ZL.DINCIDS
              GROUP BY 
                CODIGO) AS ULTREGPOR ON ULTREGPOR.TAREA = ZLTASK.NUMERO ) AS UT ON UT.INC = [INCIDS].[CODIN]
    WHERE [REQINCDET].[FUNC] <> 0
    UNION ALL
    SELECT 
        'SSI' AS TIPO
        , D.INFSOL_ID AS NUMERO 
        , S.FECHAI
        , S.REGPOR
        , D.FUNC AS FUNCIONALIDAD
        , '' AS TITULO--,D.BUG
        , S.DESCR AS DETALLE
        , '' AS OBSERVACION
        , '' AS CLIENTE
        , '' AS CLIENTENOMBRE
        , '' AS PRODUCTO
        , '' AS PRODUCTONOMBRE
        , A.CODIGO AS REUNION
        , D.FUNCEST
        , [ESTDET].DESCR AS [REUNION SUGERENCIA ESTADO]
        , D.PROY
        , [PROY].[DESCRIP] AS [REUNION PROYECTO]
			FROM 
        ZL.DETSSIAFUNBUG AS D 
        JOIN ZL.SSIAFUNBUG AS A ON A.CODIGO = D.CODIGO
        JOIN ZL.SOLSERV AS S ON S.NUMERO = D.INFSOL_ID
        LEFT JOIN [ZL].[ZL].[ESTDET] ON D.FUNCEST = [ESTDET].[CODIGO]
        LEFT JOIN [ZL].[ZL].[PROY] ON D.[PROY] = [PROY].[CODIGO]
      WHERE 
        D.FUNC <> 0) AS REQUERIMIENTOS ON [REQUERIMIENTOS].[FUNCIONALIDAD] = F.[CODIGO]
  LEFT JOIN [ZL].[ZL].[PRE_ANAL] ON REQUERIMIENTOS.[PRE-ANÁLISIS] = [PRE_ANAL].[CODIGO]
  LEFT JOIN ZL.DETFCPREE AS DESTIM ON DESTIM.CODIGO = F.CODIGO 
  LEFT JOIN ZL.FCPREEST ON ZL.FCPREEST.NUMERO = DESTIM.CODINT			 
  LEFT JOIN ZL.DETORDPRIO ON F.CODIGO = DETORDPRIO.FUNC
  LEFT JOIN ZL.REUNPRIO  ON DETORDPRIO.CODIGO = REUNPRIO.NUMERO
  LEFT JOIN ZL.DETHISTPUB  ON F.CODIGO = DETHISTPUB.CODIGO
  LEFT JOIN ZL.HISTAPUBLI ON  DETHISTPUB.CODINT = HISTAPUBLI.NUMERO     
  LEFT JOIN [ZL].[DTFCPR] AS DP ON F.[CODIGO] = DP.[CODINT]
  LEFT JOIN ZL.DTFCTE AS TEMAS ON TEMAS.CODINT = F.CODIGO
  LEFT JOIN ZL.DTFCDEP ON DTFCDEP.CODINT = F.CODIGO
  LEFT JOIN ZL.TIPFUNCOM   ON F.TIPO = TIPFUNCOM.CCOD
  LEFT JOIN
    (SELECT 
      CODIGO
      , (SELECT 
          LTRIM(RTRIM(FAI.LEGAJO )) + '. '
        FROM 
          ZL.FACTASIS AS FAI
        WHERE 
          FAI.CODIGO = FAE.CODIGO
          AND LTRIM(RTRIM(FAI.LEGAJO)) <> ''
        FOR XML PATH('')) AS ASIST
    FROM 
      ZL.FACTASIS AS FAE
    GROUP BY 
      FAE.CODIGO) AS FACTIASIS ON FACTIASIS.CODIGO = [FACTI].[CODIGO]
  LEFT JOIN
    (SELECT 
      CODIGO
      , (SELECT 
          LTRIM(RTRIM(AAI.LEGAJO )) + '. '
        FROM 
          ZL.ANALASIS  AS AAI
        WHERE 
          AAI.CODIGO = AAE.CODIGO
          AND LTRIM(RTRIM(AAI.LEGAJO)) <> ''
        FOR XML PATH('')) AS ASIST
    FROM 
      ZL.ANALASIS AS AAE
    GROUP BY 
      AAE.CODIGO) AS ANASIS ON ANASIS.CODIGO = [ANALISIS].[CODIGO]
  LEFT JOIN
    (SELECT 
      CODIGO
      , (SELECT 
          LTRIM(RTRIM(PAI.LEGAJO )) + '. '
        FROM 
          ZL.ASISTPREDET AS PAI
        WHERE 
          PAI.CODIGO = PAE.CODIGO
          AND LTRIM(RTRIM(PAI.LEGAJO)) <> ''
        FOR XML PATH('')) AS ASIST
    FROM 
      ZL.ASISTPREDET AS PAE
    GROUP BY 
      PAE.CODIGO) AS PREANASIS ON PREANASIS.CODIGO = [PRE_ANAL].[CODIGO]
  LEFT JOIN
    (/*HORAS POR FUNCIONALIDAD*/
    SELECT  
      ISNULL(F2.CODIGO,[FCOMER].[CODIGO]) AS FUNCIONALIDAD
      , SUM([HPIVOT].ESTIM) AS SUMAESTIMADAS
    FROM
      [ZL].[ZL].[HPIVOT]
      LEFT JOIN ZL.[EPICA]ON [EPICA].[CODIGO] = [HPIVOT].[EPICID]
      LEFT JOIN [ZL].[ZL].[FCOMER] ON [EPICA].[FUNCID] =[FCOMER].[CODIGO]
      LEFT JOIN [ZL].[ZL].[FCOMER] AS F2 ON [HPIVOT].FUNC = F2.CODIGO
    GROUP BY 
      ISNULL(F2.CODIGO,[FCOMER].[CODIGO])) AS FUNCHORAS ON FUNCHORAS.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN 
    (SELECT 
      CODIGO
      , (SELECT 
          LTRIM(RTRIM(PRIAI.LEGAJO )) + '. '
				FROM 
				  ZL.DETASISTPRIO AS PRIAI  
        WHERE 
          PRIAI.CODIGO = PRIAE.CODIGO
				  AND LTRIM(RTRIM(PRIAI.LEGAJO)) <> '' 
        FOR XML PATH('')) AS ASIST
  	FROM 
  	  ZL.DETASISTPRIO AS PRIAE               
    GROUP BY 
      PRIAE.CODIGO) AS PRIOASIS ON PRIOASIS.CODIGO = REUNPRIO.NUMERO
  LEFT JOIN 
    (SELECT 
      FUNCIONALIDAD AS FUNC
			,	SUM(HORAS) AS HORAS 
    FROM 
      ZL.IYDHORASFUNCBUG 
    WHERE 
      FUNCIONALIDAD <> 0 
      AND CLASI = 33
    GROUP BY 
      FUNCIONALIDAD) AS HORAS ON HORAS.FUNC = F.CODIGO
  LEFT JOIN [ZL].[IYDFUNCIONALIDADPREESTIMACIONULTIMA] AS UPREESTIM ON UPREESTIM.FUNCIONALIDAD = F.CODIGO
WHERE 
  IDD.CODIN = @DEMO
