USE ZL;

SELECT
	RTRIM(REQUERIMIENTOS.[REQ REGPOR]) AS [USUARIO]
	, LOWER(RTRIM(REQUERIMIENTOS.[REQ REGPOR]))+'@zoologic.com.ar' AS [REQ REGPOR]
	, CONVERT(VARCHAR, GETDATE(), 103) AS [FECHA]
	--, REQUERIMIENTOS.FUNCIONALIDAD
	--, REQUERIMIENTOS.BUG
FROM
	(SELECT
		MAX([PNCEREQ].[REGPOR]) AS [REQ REGPOR]
		,REQCLIDET.FUNC AS FUNCIONALIDAD
		,REQCLIDET.BUG AS BUG
	FROM 
		[ZL].[ZL].[PNCEREQ] 
		LEFT JOIN (SELECT
						MAX(REQCLIDET.CODIGO) AS CODIGO
						, REQCLIDET.NUMERO
						, REQCLIDET.FUNC
						, REQCLIDET.BUG 
				   FROM
						(SELECT 
							MAX(CODIGO) AS CODIGO
							,NUMERO
							,FUNC
							,BUG 
						FROM 
							[ZL].[REQCLIDET]
						GROUP BY  
							NUMERO
							,FUNC
							,BUG 
						) AS U JOIN ZL.REQCLIDET 
						ON REQCLIDET.CODIGO = U.CODIGO 
							AND U.NUMERO = REQCLIDET.NUMERO 
							AND REQCLIDET.FUNC = U.FUNC 
							AND REQCLIDET.BUG = U.BUG
							AND (U.FUNC <> 0 OR U.BUG <> 0)
			GROUP BY
						REQCLIDET.NUMERO
						,REQCLIDET.CODIGO
						,REQCLIDET.FUNC
						,REQCLIDET.BUG 
		) AS [REQCLIDET] ON [PNCEREQ].[CODIN] = [REQCLIDET].[NUMERO]
	WHERE
		([REQCLIDET].FUNC IS NOT NULL OR [REQCLIDET].BUG IS NOT NULL)
		AND ([PNCEREQ].[NAPROV] = 0  AND  [PNCEREQ].[CMPFECINI] > '20111001')
    AND (/*[PNCEREQ].[Faltafw] >= CONVERT(DATETIME, CONVERT(VARCHAR, DATEADD(YEAR, -1, GETDATE()), 103), 103) 
         AND*/ [PNCEREQ].[Faltafw] <= CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103), 103))
	GROUP BY
		[PNCEREQ].[REGPOR]
		, REQCLIDET.FUNC
		, REQCLIDET.BUG
		
	UNION ALL
	
	SELECT
		[REQUER].[REGPOR] AS [REQ REGPOR]
		, REQIDDET.FUNC
		, 0
	FROM 
		[ZL].[REQUER] 
		LEFT JOIN (SELECT 
						REQIDDET.CODIGO
						,REQIDDET.REQID
						,REQIDDET.FUNC 
				   FROM 
						[ZL].[REQIDDET]
						JOIN (SELECT 
									MAX(CODIGO) AS CODIGO
									,REQID, FUNC 
							  FROM 
									[ZL].[ZL].[REQIDDET] 
							  GROUP BY 
									REQID, FUNC) AS ULT 
							ON ULT.REQID = [REQIDDET].[REQID] 
							AND ULT.CODIGO = [REQIDDET].CODIGO 
							AND ULT.FUNC =[REQIDDET].FUNC 
					) AS REQIDDET ON [REQUER].[CODIGO] = [REQIDDET].[REQID]
	WHERE
		FUNC IS NOT NULL
		AND FUNC <> 0
		AND (/*[REQUER].[Faltafw] >= CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103), 103) 
		     AND*/ [REQUER].[Faltafw] <= CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103), 103))
	GROUP BY
		REQIDDET.FUNC
		, [REQUER].[REGPOR]
           
	UNION ALL

	SELECT
		R.REGPOR AS [REQ REGPOR]
		, REQINCDET.FUNC
		, [REQINCDET].BUG
	FROM
		[ZL].[ZL].[INCIDS]
		JOIN ZL.IYDREQUERIMIENTOSINCIDENTES AS R ON R.NUMERO = INCIDS.CODIN
		LEFT JOIN (SELECT 
						REQINCDET.CODIGO
						,REQINCDET.[INC_ID]
						,REQINCDET.FUNC
						,[REQINCDET].BUG
				   FROM 
						[ZL].[REQINCDET]  
						JOIN (SELECT 
									MAX(CODIGO) AS CODIGO
									,[INC_ID]
									, FUNC
									, BUG
							  FROM 
									[ZL].[REQINCDET]
							  GROUP BY 
									[INC_ID]
									,FUNC
									,BUG 
							  ) AS ULT 
								ON ULT.[INC_ID] = [REQINCDET].[INC_ID] 
								AND ULT.CODIGO = [REQINCDET].CODIGO 
								AND ULT.FUNC =[REQINCDET].FUNC 
								AND ULT.BUG =[REQINCDET].BUG 
					) AS REQINCDET ON [INCIDS].[CODIN] = [REQINCDET].[INC_ID]
	WHERE
		(FUNC IS NOT NULL AND FUNC <> 0)
		OR (BUG IS NOT NULL AND BUG <> 0)
		AND R.REGPOR IS NOT NULL
		AND (/*[ZL].[ZL].[INCIDS].[Faltafw] >= CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103), 103) 
		     AND*/ [ZL].[ZL].[INCIDS].[Faltafw] <= CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103), 103))
	GROUP BY 
		R.REGPOR
		,REQINCDET.FUNC
		,REQINCDET.BUG) AS REQUERIMIENTOS,
	(SELECT FUNCIONALIDAD FROM ZL.IYDFUNCIONALIDADULTIMOESTADO 
  	INNER JOIN [ZL].[ZL].[ESTDET] ON ZL.IYDFUNCIONALIDADULTIMOESTADO.[Funcest] = [ESTDET].[Codigo] 
	WHERE CONVERT(VARCHAR, IYDFUNCIONALIDADULTIMOESTADO.FECHA, 103) = CONVERT(VARCHAR, GETDATE(), 103)
		AND ESTADO IS NOT NULL AND LTRIM(RTRIM(ESTADO)) NOT IN ('Sin Estado')
	 UNION
	 SELECT FUNCIONALIDAD FROM ZL.IYDFUNCIONALIDADETAPAULTIMA WHERE CONVERT(VARCHAR, IYDFUNCIONALIDADETAPAULTIMA.FECHA, 103) = CONVERT(VARCHAR, GETDATE(), 103)
		AND COMPROBANTE IS NOT NULL AND LTRIM(RTRIM(COMPROBANTE)) NOT IN ('Sin Estado') ) AS FUNCULTETAP,
	(SELECT BUG FROM ZL.IYDBUGULTIMOESTADO 
			INNER JOIN [ZL].[ZL].[ESTDET] ON ZL.IYDBUGULTIMOESTADO.[Funcest] = [ESTDET].[Codigo] 
WHERE CONVERT(VARCHAR, IYDBUGULTIMOESTADO.FECHA, 103) = CONVERT(VARCHAR, GETDATE(), 103)
		AND ESTADO IS NOT NULL AND LTRIM(RTRIM(ESTADO)) NOT IN ('Sin Estado')
	 UNION
	 SELECT BUG FROM ZL.IYDBUGETAPAULTIMA WHERE CONVERT(VARCHAR, IYDBUGETAPAULTIMA.FECHA, 103) = CONVERT(VARCHAR, GETDATE(), 103)
		AND COMPROBANTE IS NOT NULL AND LTRIM(RTRIM(COMPROBANTE)) NOT IN ('Sin Estado') ) AS BUGULTETAP
WHERE
	(REQUERIMIENTOS.[FUNCIONALIDAD] = FUNCULTETAP.FUNCIONALIDAD
	AND FUNCULTETAP.FUNCIONALIDAD <> 0
	AND FUNCULTETAP.FUNCIONALIDAD IS NOT NULL)
	OR (REQUERIMIENTOS.[BUG] = BUGULTETAP.BUG
	AND BUGULTETAP.BUG <> 0
	AND BUGULTETAP.BUG IS NOT NULL)
GROUP BY
  REQUERIMIENTOS.[REQ REGPOR]
  --, REQUERIMIENTOS.FUNCIONALIDAD
  --, REQUERIMIENTOS.BUG
ORDER BY
	REQUERIMIENTOS.[REQ REGPOR]
	--, REQUERIMIENTOS.FUNCIONALIDAD
	--, REQUERIMIENTOS.BUG
