SELECT 
  TOP 20 
  D.CODIN
  , F.DIANOMBRE + ' ' + CONVERT(VARCHAR(5),D.FCHREUN,103) + ' - ' + LTRIM(RTRIM( P.DESCRIP)) AS LABELL
FROM 
  ZL.IYDDEMOS AS D      
  LEFT JOIN ZL.PROY AS P ON P.CODIGO = D.PROY
  JOIN DBO.FECHASCALENDARIO AS F ON F.FECHA = D.FCHREUN
ORDER BY 
  D.FCHREUN DESC
  , P.DESCRIP ASC