DECLARE @BUG AS INT;

SET @BUG = 1201;

SELECT 
  B.[CODIN]
  , B.[CMPFECINI]
  , B.[REGPOR]
  , B.[TITULO]      
  , DP.[CODPROD]
  , DP.DESPROD AS PRODUCTO
  , DP.[CBUILD]
  , V.VERSION
  , B.[DESBUG] AS [DESBUG]
  , B.[MSGSIS]      
  , B.[CSEVE]
  , ISSEVE.DES AS SEVERIDAD
  , B.[COCURR]
  , ISSOCU.DES AS OCURRENCIA
  , B.[CODEOS]
  , CEDOSS.DESCR AS EDICIONSO
  , DP.[CODESTI]
  , DP.DESESTI AS ESTILO      
  , DP.[CODMOTOR]
  , DP.DESMOTOR AS MOTOR
  , B.[CODOS]
  , COSS.DESCR AS SO
  , B.[CODPLAT]
  , CPLATOSS.DESCR AS PLATAFORMAOS
  --, B. [CVERSION]
  , HSZL.HORAS AS HORASZL
  , BUE.ESTADO AS BUGESTADOACTUAL
  , BUP.PROYECTO AS BUGPROYECTOACTUAL
  , BPUB.FECHA AS BUGFECHATERMINADA
  , CASE 
      WHEN (EVAL.FUNC = 0 AND  EVAL.BUGASO = 0) OR (EVAL.FUNC IS NULL AND EVAL.BUGASO IS NULL ) THEN 'Nada' 
      ELSE  
        CASE 
          WHEN EVAL.FUNC = 0 THEN 'Bug' 
          ELSE 'Funcionalidad' 
        END 
    END AS ENTIDRELA
  , CASE 
      WHEN(EVAL.FUNC = 0 AND  EVAL.BUGASO = 0) OR (EVAL.FUNC IS NULL AND EVAL.BUGASO IS NULL ) THEN 0 
      ELSE  
        CASE 
          WHEN EVAL.FUNC = 0 THEN EVAL.BUGASO  
          ELSE EVAL.FUNC 
        END 
    END AS ENTIDRELANUMERO
  , CASE 
      WHEN (EVAL.FUNC = 0 AND  EVAL.BUGASO = 0) OR (EVAL.FUNC IS NULL AND EVAL.BUGASO IS NULL ) THEN '' 
      ELSE  
        CASE WHEN EVAL.FUNC = 0 THEN EVAL.TITASO  
          ELSE EVAL.NOMBRE 
        END 
    END AS ENTIDRELATITULO
  , BSP.SPRINTS
  , B.IMGBUG
FROM 
  [ZL].[REGBUG] AS B
  LEFT JOIN ZL.DBUGPROD AS DP ON DP.CODINT = B.CODIN           
  LEFT JOIN [ZL].[IYDBUGVERSION] AS V ON V.BUG = B.CODIN AND DP.CODPROD = V.PRODUCTO
  LEFT JOIN ZL.DETEVBUGS AS EVAL ON EVAL.BUG = B.CODIN
  LEFT JOIN ZL.COSS ON B.[CODOS] = ZL.COSS.CCOD
  LEFT JOIN ZL.CPLATOSS  ON B.[CODPLAT] = CPLATOSS.CCOD
  LEFT JOIN ZL.CEDOSS  ON B.[CODEOS] = CEDOSS.CCOD
  LEFT JOIN ZL.ISSEVE  ON B.[CSEVE] = ISSEVE.COD
  LEFT JOIN ZL.ISSOCU  ON  B.[COCURR] = ISSOCU.COD
  LEFT JOIN ZL.IYDBUGULTIMOPROYECTO AS BUP ON BUP.BUG = B.CODIN
  LEFT JOIN ZL.IYDBUGULTIMOESTADO AS BUE ON BUE.BUG = B.CODIN
  LEFT JOIN ZL.[IYDBUGCORREGIDOSAPUBLICARPRIMERO] AS BPUB ON BPUB.BUG = B.CODIN
  LEFT JOIN (SELECT 
              [BUG]
              , CASE 
                  WHEN DATEDIFF(DAY, MIN([FECHA]), MAX([FECHA])) = 0 THEN 1 
                  ELSE 
                    CASE 
                      --DIVIDO POR 2 SEMANAS, SI HAY RESTO SE SUMA UNO.
                      WHEN ( DATEDIFF(DAY, MIN([FECHA]), MAX([FECHA])) % 14 ) = 0 THEN DATEDIFF(DAY, MIN([FECHA]), MAX([FECHA])) / 14
                      ELSE ( DATEDIFF(DAY, MIN([FECHA]), MAX([FECHA])) / 14 ) + 1 
                    END 
                END AS SPRINTS
            FROM 
              [ZL].[ZL].[DETIYDHORAS]
            WHERE 
              [BUG] = @BUG 
            GROUP BY 
              [BUG])  AS BSP ON BSP.BUG = @BUG
    LEFT JOIN ( SELECT [BUG], SUM([HORAS]) AS HORAS FROM [ZL].[ZL].[DETIYDHORAS] WHERE [BUG] = @BUG GROUP BY [BUG] ) AS HSZL ON HSZL.BUG = @BUG
WHERE 
  B.[CODIN] = @BUG
