DECLARE @FUNCIONALIDAD AS INT;

SET @FUNCIONALIDAD = 1046;


SELECT    
  F.CODIGO 
  , F.NOMBRE 
  , F.DESCRIP 
  , F.OBS
  , F.REGPOR AS FUNCIONALIDADREGPOR, F.FALTAFW AS FUNCFECHAALTA
  , M.DESCRIP AS MAGNITUD
  , UP.PROY AS ULTPROYCOD
  , UP.PROYECTO AS ULTPROYNOMBRE 
  , UE.FUNCEST AS ULTFUNCESTCD
  , UE.ESTADO AS ULTFUNCESTADNOMBRE
  , DP.CCOD AS FUNCPRODCOD
  , DP.DESCR AS FUNCPRODDESCR
  , V.VERSION
  , TEMAS.TEMAID
  , TEMAS.NOMBRE AS TEMANOMBRE
  , DTFCDEP.FUNC AS FUNCDEP
  , DTFCDEP.NOMBRE AS FUNCDEPNOMBRE
  , FUNCDEP2.CODINT AS FUNCDEP2
  , FDEP2.NOMBRE AS FUNCDEP2NOMBRE
  , TIPFUNCOM.DESCRIP AS TIPOFUNC
  , PUB.[PRIMERA LISTA PARA PUBLICAR FECHA]
  , ( SELECT SUM(HORAS) FROM  ZL.IYDHORASFUNCBUG WHERE FUNCIONALIDAD =@FUNCIONALIDAD ) AS HORASZL
  , EVAL.BUG AS BUGASOCIADO 
  , EVAL.TITULO AS BUGASOCIADOTITULO
  , EVAL.CODIGO AS EVALASOCIADOCOMPROBANTE
  , FSP.SPRINTS
  , DOC.ASIGNADOC AS DOCUMENTO_NUM
  , DOC.DOCTITULO AS DOCUMENTOTITULO
  , DOC.DOCURL
  , DOC.DOCESTADOGRALDESCRIPTIVO AS DOCUMENTOESTADO
FROM
  [ZL].[ZL].[FCOMER] AS F 
  LEFT JOIN ZL.MAGNITUD AS M ON M.CCOD = F.MAGN
  LEFT JOIN [ZL].[DTFCPR] AS DP ON F.[CODIGO] = DP.[CODINT]
  LEFT JOIN [ZL].[IYDFUNCIONALIDADVERSION] AS V ON V.FUNCIONALIDAD = F.CODIGO AND V.PRODUCTO = DP.CCOD
  LEFT JOIN ZL.DETEVBUGS AS EVAL ON EVAL.FUNC = F.CODIGO
  LEFT JOIN ZL.IYDDURACIONSPRINTSFUNCBUGS AS FSP ON FSP.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN ZL.DTFCTE AS TEMAS ON TEMAS.CODINT = F.CODIGO
  LEFT JOIN ZL.DTFCDEP ON DTFCDEP.CODINT = F.CODIGO
  LEFT JOIN ZL.DTFCDEP AS FUNCDEP2 ON FUNCDEP2.FUNC = F.CODIGO
  LEFT JOIN ZL.FCOMER AS FDEP2 ON FDEP2.CODIGO = FUNCDEP2.CODINT
  LEFT JOIN ZL.TIPFUNCOM   ON F.TIPO = TIPFUNCOM.CCOD
  LEFT JOIN [ZL].[IYDFUNCIONALIDADULTIMOPROYECTO] AS UP ON UP.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN ZL.IYDFUNCIONALIDADULTIMOESTADO AS UE ON UE.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN ZL.FUNCIYDFUNCIONALIDADESPRIMERAPARAPUBLICAR() AS PUB ON PUB.FUNCIONALIDAD = F.CODIGO
  LEFT JOIN ZL.SAL_AFU_DOCUMENTOS AS DOC ON DOC.REQDEDOCFUNC = F.CODIGO
WHERE 
  F.CODIGO = @FUNCIONALIDAD