DECLARE @DEMO AS INT;

SET @DEMO = 158;

SELECT 
  DTIYDEMB.COMENT AS DEMOCOMENT
  , DTIYDEMB.AVANCE AS DEMOAVANCE
  ,CASE 
    WHEN DTIYDEMB.ORDEN = 0 THEN DTIYDEMB.NITEM  
    ELSE DTIYDEMB.ORDEN 
  END AS DEMOORDEN
  , B.[CODIN]
  , B.[CMPFECINI]
  , B.[REGPOR]
  , B.[TITULO]      
  , DP.[CODPROD]
  , DP.DESPROD AS PRODUCTO
  , DP.[CBUILD]
  , DP.[CODESTI]
  , DP.DESESTI AS ESTILO      
  , DP.[CODMOTOR]
  , DP.DESMOTOR AS MOTOR
  , B.[DESBUG]     
  , B.[MSGSIS]      
  , B.[CSEVE]
  , ISSEVE.DES AS SEVERIDAD
  , B.[COCURR]
  , ISSOCU.DES AS OCURRENCIA
  , B.[CODEOS]
  , CEDOSS.DESCR AS EDICIONSO
  , B.[CODOS]
  , COSS.DESCR AS SO
  , B.[CODPLAT]
  , CPLATOSS.DESCR AS PLATAFORMAOS
  , BUE.ESTADO AS BUGESTADOACTUAL
  , BUP.PROYECTO AS BUGPROYECTOACTUAL
  , EVALBUGS.FALTAFW AS EVALFECHAATA
  , EVALBUGS.REGPOR AS EVALREGPOR
  , EVALUACIONES.*
  , EVASIS.ASIST AS EVALUACIONESASISTENTES
  , REQUERIMIENTOS.[TIPO DE REQUERIMIENTO]
  , ISNULL(REQUERIMIENTOS.[REQ NÚMERO], 0) AS [REQ NÚMERO]
  , REQUERIMIENTOS.[REQ ALTA]
  , REQUERIMIENTOS.[REQ REGPOR]
  , REQUERIMIENTOS.[REQ ASUNTO/TÍTULO]
  , REQUERIMIENTOS.[REQ DETALLE]
  , REQUERIMIENTOS.[REQ OBSERVACIÓN]
  , REQUERIMIENTOS.[REQ CCLIENTE]
  , REQUERIMIENTOS.[REQ CLIENTE NOMBRE]
  , REQUERIMIENTOS.[REQ PRODUCTO]
  , REQUERIMIENTOS.[PRE-ANÁLISIS]
  , REQUERIMIENTOS.[PRE-ANÁLISIS SUGERENCIA ESTADO]
  , REQUERIMIENTOS.[PRE-ANÁLISIS PROYECTO]
  , [PRE_ANAL].[FALTAFW] AS [PRE-ANÁLISIS FECHA]
  , [PRE_ANAL].REGPOR AS [PRE-ANÁLISIS REGPOR]
  , PREANASIS.ASIST AS [PRE_ANALISIS ASISTENTES]
  , ISNULL(HORAS.HORAS,0) AS TOTALHORASZL
  , BSP.SPRINTS
FROM 
  ZL.DTIYDEMB 
  JOIN [ZL].[REGBUG] AS B ON DTIYDEMB.BUG = B.CODIN
  LEFT JOIN ZL.DBUGPROD AS DP ON DP.CODINT = B.CODIN 
  LEFT JOIN ZL.PRODZL ON DP.[CODPROD] = PRODZL.CCOD
  LEFT JOIN ZL.CMOTORG ON B.[CODMOTOR] = CMOTORG.CCOD
  LEFT JOIN ZL.CESTORG ON B.[CODESTI] = CESTORG.CCOD
  LEFT JOIN ZL.COSS ON B.[CODOS] = ZL.COSS.CCOD
  LEFT JOIN ZL.CPLATOSS  ON B.[CODPLAT] = CPLATOSS.CCOD
  LEFT JOIN ZL.CEDOSS  ON B.[CODEOS] = CEDOSS.CCOD
  LEFT JOIN ZL.ISSEVE  ON B.[CSEVE] = ISSEVE.COD
  LEFT JOIN ZL.ISSOCU  ON  B.[COCURR] = ISSOCU.COD
  LEFT JOIN ZL.IYDBUGULTIMOPROYECTO AS BUP ON BUP.BUG = B.CODIN
  LEFT JOIN ZL.IYDBUGULTIMOESTADO AS BUE  ON BUE.BUG = B.CODIN
  LEFT JOIN ZL.IYDDURACIONSPRINTSFUNCBUGS AS BSP ON BSP.BUG = B.CODIN
  LEFT JOIN 
    (SELECT 
      DETEVISS.BUG
      , 'EVALUACIÓN DE ISSUES' AS TIPO 
      , DETEVISS.CODIGO AS EVALUACIONISSUE_NUMERO 
      , MAGNITUD.DESCRIP AS  EVALUACIONISSUE_MAGNNOMBRE
      , PROY.DESCRIP AS  EVALUACIONISSUE_PROYNOMBRE
      , ESTDET.DESCR AS EVALUACIONISSUE_FUNCESTNOMBRE
      , DETEVISS.COMENT AS EVALUACIONISSUE_OBS
      , DETEVISS.ISSUE AS EVALUACIONISSUE_ISSUE
      , DETEVISS.REGPOR AS EVALUACIONISSUE_ISSUEREGPOR
      /************** AGREGADO POR HDC **************/
      , ISNULL(DETEVISS.BUGO, 0) AS [BUG ORIGEN]
      , DETEVISS.TITULO AS [TIT BUG ORIGEN]
      , ISNULL(DETEVISS.FUNCO, 0) AS [FUNC ORIGEN]
      , DETEVISS.NOMBREO AS [TIT FUNC ORIGEN]
      , CONVERT(VARCHAR(10), DETEVISS.CMPFECINI, 103) AS [FECHA ALTA ORIGEN]
      , RTRIM(ZL.DETEVISS.REGPOR) AS [REGPOR ORIGEN]
      , ISNULL(ASISTENTES.ASIST, '') AS [ASISTENTES ORIGEN]
      , ISNULL(ZL.REGISSU.CODIN, 0) AS [ISSUE NRO]
      , CASE 
          WHEN ZL.REGISSU.TITULO = '' THEN ''
          ELSE 'Título: ' + RTRIM(ZL.REGISSU.TITULO) + '. '
        END + 
      CASE
        WHEN ZL.REGISSU.DESISSU IS NULL THEN ''
        ELSE 'Detalle: ' + RTRIM(CONVERT(VARCHAR(MAX), ZL.REGISSU.DESISSU))
      END AS [ISSUE TITULO]
      , CONVERT(VARCHAR(10), ZL.REGISSU.FALTAFW, 103) AS [ISSUE FECHA ALTA]
      , LTRIM(RTRIM(ISNULL(ZL.REGISSU.REGPOR, ''))) AS [ISSER REGPOR]
      
      , ISNULL(ZL.REGBUG.CODIN, 0) AS [BUG NRO]
      , CASE 
          WHEN ZL.REGBUG.TITULO = '' THEN ''
          ELSE 'Título: ' + RTRIM(ZL.REGBUG.TITULO) + '. '
        END + 
      CASE
        WHEN ZL.REGBUG.DESBUG IS NULL THEN ''
        ELSE 'Detalle: ' + RTRIM(CONVERT(VARCHAR(MAX), ZL.REGBUG.DESBUG))
      END AS [BUG TITULO]
      , CONVERT(VARCHAR(10), ZL.REGBUG.FALTAFW, 103) AS [BUG FECHA ALTA]
      , LTRIM(RTRIM(ISNULL(ZL.REGBUG.REGPOR, ''))) AS [BUG REGPOR]
      
      , ISNULL(ZL.FCOMER.CODIGO, 0) AS [FUNC NRO]
      , CASE 
          WHEN ZL.FCOMER.NOMBRE = '' THEN ''
          ELSE 'Nombre: ' + ZL.FCOMER.NOMBRE + '. '
        END + 
      CASE 
        WHEN CONVERT(VARCHAR(MAX), ZL.FCOMER.DESCRIP) = '' THEN ''
        ELSE 'Descripción: ' + CONVERT(VARCHAR(MAX), ZL.FCOMER.DESCRIP) + '. '
      END AS [FUNC DETALLE]
      , ISNULL(CONVERT(VARCHAR(10), ZL.FCOMER.FALTAFW, 103), '') AS [FUNC FECHA ALTA]
      , ISNULL(LTRIM(RTRIM(ZL.FCOMER.REGPOR)), '') AS [FUNC REG POR]
      /**********************************************/
    FROM   
      ZL.DETEVISS   
		  LEFT JOIN ZL.PROY ON DETEVISS.PROY = PROY.CODIGO
		  LEFT JOIN ZL.ESTDET ON DETEVISS.FUNCEST = ESTDET.CODIGO
		  LEFT JOIN ZL.MAGNITUD ON DETEVISS.MAGN = MAGNITUD.CCOD
		  LEFT JOIN ZL.REGISSU ON ZL.REGISSU.CODIN = DETEVISS.ISSUE
		  LEFT JOIN ZL.REGBUG ON ZL.REGBUG.CODIN = DETEVISS.BUGO
		  LEFT JOIN ZL.FCOMER ON FCOMER.CODIGO = DETEVISS.FUNCO
      LEFT JOIN 
        (SELECT
          ZL.DETEVISSASIS.CODIGO
          , C.ASIST
         FROM
          ZL.DETEVISSASIS
          INNER JOIN
            (SELECT 
              DISTINCT
              B.[CODIGO]
              ,STUFF((SELECT ', ' + RTRIM(A.LEGAJO) FROM ZL.ZL.DETEVISSASIS AS A WHERE A.CODIGO = B.CODIGO group BY A.CODIGO, A.LEGAJO FOR XML PATH ('')) , 1, 2, '') AS ASIST
             FROM
              ZL.ZL.DETEVISSASIS AS B) AS C ON C.CODIGO = ZL.DETEVISSASIS.CODIGO
        GROUP BY
          ZL.DETEVISSASIS.CODIGO
          , C.ASIST) AS ASISTENTES ON ASISTENTES.CODIGO = ZL.DETEVISS.CODIGO
		WHERE 
		  DETEVISS.BUG <> 0
	  UNION ALL
	  SELECT 
	    DETEVBUGS.BUG 
      , 'EVALUACIÓN DE BUGS' AS TIPO 
      , DETEVBUGS.CODIGO AS EVALUACIONBUG_NUMERO      
      , MAG2.DESCRIP AS EVALUACIONBUG_MGNNOMBRE
      , PROY2.DESCRIP AS  EVALUACIONBUG_PROYNOMBRE
      , ESTDET2.DESCR AS EVALUACIONBUG_FUNCESTNOMBRE
      , DETEVBUGS.COMENT AS EVALUACIONBUG_OBS
      , 0 AS ISSUE
      , '' AS ISSUEREGPOR
      /************** AGREGADO POR HDC **************/
      , ISNULL(DETEVBUGS.BUGASO, 0) AS [BUG ORIGEN]
      , DETEVBUGS.TITASO AS [TIT BUG ORIGEN]
      , ISNULL(DETEVBUGS.FUNC, 0) AS [FUNC ORIGEN]
      , DETEVBUGS.NOMBRE AS [TIT FUNC ORIGEN]
      , CONVERT(VARCHAR(10), ZL.EVALBUGS.FALTAFW, 103) AS [FECHA ALTA ORIGEN]
      , RTRIM(ZL.EVALBUGS.REGPOR) AS [REGPOR ORIGEN]
      , ISNULL(ASISTENTES.ASIST, '') AS [ASISTENTES ORIGEN]

      , ISNULL(ZL.REGISSU.CODIN, 0) AS [ISSUE NRO]
      , ZL.REGISSU.TITULO AS [ISSUE TITULO]
      , CONVERT(VARCHAR(10), ZL.REGISSU.FALTAFW, 103) AS [ISSUE FECHA ALTA]
      , LTRIM(RTRIM(ISNULL(ZL.REGISSU.REGPOR, ''))) AS [ISSUE REGPOR]

      , ISNULL(ZL.REGBUG.CODIN, 0) AS [BUG NRO]
      , CASE 
          WHEN ZL.REGBUG.TITULO = '' THEN ''
          ELSE 'Título: ' + RTRIM(ZL.REGBUG.TITULO) + '. '
        END + 
      CASE
        WHEN ZL.REGBUG.DESBUG IS NULL THEN ''
        ELSE 'Detalle: ' + RTRIM(CONVERT(VARCHAR(MAX), ZL.REGBUG.DESBUG))
      END AS [BUG TITULO]
      , CONVERT(VARCHAR(10), ZL.REGBUG.FALTAFW, 103) AS [BUG FECHA ALTA]
      , LTRIM(RTRIM(ISNULL(ZL.REGBUG.REGPOR, ''))) AS [BUG REGPOR]
      
      , ISNULL(ZL.FCOMER.CODIGO, 0) AS [FUNC NRO]
      , CASE 
          WHEN ZL.FCOMER.NOMBRE = '' THEN ''
          ELSE 'Nombre: ' + ZL.FCOMER.NOMBRE + '. '
        END + 
      CASE 
        WHEN CONVERT(VARCHAR(MAX), ZL.FCOMER.DESCRIP) = '' THEN ''
        ELSE 'Descripción: ' + CONVERT(VARCHAR(MAX), ZL.FCOMER.DESCRIP) + '. '
      END AS [FUNC DETALLE]
      , ISNULL(CONVERT(VARCHAR(10), ZL.FCOMER.FALTAFW, 103), '') AS [FUNC FECHA ALTA]
      , ISNULL(LTRIM(RTRIM(ZL.FCOMER.REGPOR)), '') AS [FUNC REG POR]
      /**********************************************/
	  FROM 
	    ZL.DETEVBUGS 
		  LEFT JOIN ZL.MAGNITUD AS MAG2 ON DETEVBUGS.MAGN = MAG2.CCOD
		  LEFT JOIN ZL.PROY AS PROY2 ON DETEVBUGS.PROY = PROY2.CODIGO
		  LEFT JOIN ZL.ESTDET AS ESTDET2 ON DETEVBUGS.FUNCEST = ESTDET2.CODIGO
      LEFT JOIN ZL.EVALBUGS ON ZL.EVALBUGS.CODIGO = ZL.DETEVBUGS.CODIGO
		  LEFT JOIN ZL.REGISSU ON ZL.REGISSU.CODIN = 0
		  LEFT JOIN ZL.REGBUG ON ZL.REGBUG.CODIN = ZL.DETEVBUGS.BUGASO
		  LEFT JOIN ZL.FCOMER ON FCOMER.CODIGO = DETEVBUGS.FUNC
      LEFT JOIN 
        (SELECT
          ZL.DETEVBGASIS.CODIGO
          , C.ASIST
         FROM
          ZL.DETEVBGASIS
          INNER JOIN
            (SELECT 
              DISTINCT
              B.[CODIGO]
              ,STUFF((SELECT ', ' + RTRIM(A.LEGAJO) FROM ZL.ZL.DETEVBGASIS AS A WHERE A.CODIGO = B.CODIGO group BY A.CODIGO, A.LEGAJO FOR XML PATH ('')) , 1, 2, '') AS ASIST
             FROM
              ZL.ZL.DETEVBGASIS AS B) AS C ON C.CODIGO = ZL.DETEVBGASIS.CODIGO
        GROUP BY
          ZL.DETEVBGASIS.CODIGO
          , C.ASIST) AS ASISTENTES ON ASISTENTES.CODIGO =   ZL.EVALBUGS.CODIGO
    WHERE 
      DETEVBUGS.BUG <> 0) AS EVALUACIONES ON EVALUACIONES.BUG = B.CODIN
  LEFT JOIN ZL.EVALBUGS ON EVALUACIONES.EVALUACIONISSUE_NUMERO  = EVALBUGS.CODIGO
  LEFT JOIN 
    (SELECT
      'REQ. CLIENTE' AS [TIPO DE REQUERIMIENTO]
      , [PNCEREQ].[CODIN] AS [REQ NÚMERO]
      , [PNCEREQ].[FALTAFW]+[PNCEREQ].[HALTAFW] AS [REQ ALTA]
      , [PNCEREQ].[REGPOR] AS [REQ REGPOR]
      , [REQCLIDET].[BUG] AS BUG
      , [PNCEREQ].[ASUNTO] AS [REQ ASUNTO/TÍTULO]
      , [PNCEREQ].[CMPCONSULT] AS [REQ DETALLE]
      , '' AS [REQ OBSERVACIÓN]
      , [PNCEREQ].[CCLIENTE] AS [REQ CCLIENTE]
      , [CLIENTES].[CMPNOMBRE] AS [REQ CLIENTE NOMBRE]
      , [PRODZL].[DESCR] AS [REQ PRODUCTO]
      , [REQCLIDET].[CODIGO] AS [PRE-ANÁLISIS]
      , [ESTDET].DESCR AS [PRE-ANÁLISIS SUGERENCIA ESTADO]
      , [PROY].[DESCRIP] AS [PRE-ANÁLISIS PROYECTO]
    FROM 
      [ZL].[ZL].[PNCEREQ]
      JOIN [ZL].[ZL].[REQCLIDET] ON [PNCEREQ].[CODIN] = [REQCLIDET].[NUMERO]
      LEFT JOIN [ZL].[ZL].[CLIENTES] AS [CLIENTES] ON [CLIENTES].[CMPCODIGO] = [PNCEREQ].[CCLIENTE]
      LEFT JOIN [ZL].[ZL].[PRODZL] ON [PNCEREQ].[CPCOD] = [PRODZL].[CCOD]
      LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQCLIDET].[FUNCEST] = [ESTDET].[CODIGO]
      LEFT JOIN [ZL].[ZL].[PROY] ON [REQCLIDET].[PROY] = [PROY].[CODIGO]
    WHERE 
      [REQCLIDET].[BUG] <> 0
    UNION ALL
    SELECT
      'INCIDENTE' AS [TIPO DE REQUERIMIENTO]
      , [INCIDS].[CODIN] AS [REQ NÚMERO]
      , [INCIDS].[CMPFECINI] AS [REQ ALTA]
      , UT.REGPOR AS [REQ REGPOR]
      , [REQINCDET].[BUG] AS BUG
      , ZL.FUNCIONES.ALLTRIM([TIPIF].[CDESC]) + ' // ' + ZL.FUNCIONES.ALLTRIM([TIPIF2].[CDESC])  + '//' + ZL.FUNCIONES.ALLTRIM(UT.CTITULO) AS [REQ ASUNTO/TÍTULO]
      , [INCIDS].[CMPCONSULT] AS [REQ DETALLE]
      , '' AS [REQ OBSERVACIÓN]
      , [INCIDS].[CCLIENTE]
      , [CLIENTES].[CMPNOMBRE] AS [CLIENTE NOMBRE]
      , [PRODZL].[DESCR] AS PRODUCTO
      , [REQINCDET].[CODIGO] AS [PRE-ANÁLISIS]
      , [ESTDET].DESCR AS [PRE-ANÁLISIS SUGERENCIA ESTADO]
      , [PROY].[DESCRIP] AS [PRE-ANÁLISIS PROYECTO]
    FROM
      [ZL].[ZL].[INCIDS]
      LEFT JOIN [ZL].[ZL].[TIPIF] ON [INCIDS].[CMPTIPIF] = [TIPIF].[CCOD]
      LEFT JOIN [ZL].[ZL].[TIPIF2] ON [INCIDS].[CMPSTIP] = [TIPIF2].[CCOD]
      JOIN [ZL].[ZL].[REQINCDET] ON [INCIDS].[CODIN] = [REQINCDET].[INC_ID]
      LEFT JOIN [ZL].[ZL].[CLIENTES] ON [CLIENTES].[CMPCODIGO] = [INCIDS].[CCLIENTE]
      LEFT JOIN [ZL].[ZL].[PRODZL] ON [INCIDS].[CPROD] = [PRODZL].[CCOD]
      LEFT JOIN [ZL].[ZL].[ESTDET] ON [REQINCDET].[FUNCEST] = [ESTDET].[CODIGO]
      LEFT JOIN [ZL].[ZL].[PROY] ON [REQINCDET].[PROY] = [PROY].[CODIGO]
      LEFT JOIN
        (SELECT 
          ULTREGPOR.INC
          , ZL.ZLTASK.REGPOR
          , ZLTASK.CTITULO
        FROM
          ZL.ZLTASK
          JOIN
            (SELECT 
              MAX(NUMERO) AS TAREA
              , CODIGO AS INC
            FROM 
              ZL.DINCIDS
            GROUP BY 
              CODIGO) AS ULTREGPOR ON ULTREGPOR.TAREA = ZLTASK.NUMERO) AS UT ON UT.INC = [INCIDS].[CODIN]
        WHERE 
          [REQINCDET].[BUG] <> 0) AS REQUERIMIENTOS ON [REQUERIMIENTOS].[BUG] = B.[CODIN]
    LEFT JOIN [ZL].[ZL].[PRE_ANAL] ON REQUERIMIENTOS.[PRE-ANÁLISIS] = [PRE_ANAL].[CODIGO]
		LEFT JOIN 
      (SELECT 
        CODIGO
        , (SELECT LTRIM(RTRIM(PAI.LEGAJO )) + '. '
      FROM 
          ZL.ASISTPREDET    AS PAI
      WHERE 
          PAI.CODIGO = PAE.CODIGO
          AND LTRIM(RTRIM(PAI.LEGAJO)) <> ''
        FOR XML PATH('')) AS ASIST 
      FROM 
        ZL.ASISTPREDET AS PAE
      GROUP BY 
        PAE.CODIGO) AS PREANASIS ON PREANASIS.CODIGO = [PRE_ANAL].[CODIGO]
    LEFT JOIN 
      (SELECT 
        CODIGO
        , (SELECT LTRIM(RTRIM(EAI.LEGAJO )) + '. '
        FROM 
          ZL.DETEVBGASIS AS EAI
        WHERE 
          EAI.CODIGO = EAE.CODIGO
          AND LTRIM(RTRIM(EAI.LEGAJO)) <>''
        FOR XML PATH('')) AS ASIST
      FROM 
        ZL.DETEVBGASIS AS EAE
      GROUP BY 
        EAE.CODIGO) AS EVASIS ON EVASIS.CODIGO = EVALUACIONES.EVALUACIONISSUE_NUMERO
  LEFT JOIN 
    (SELECT 
      BUG
      , SUM(HORAS) AS HORAS 
    FROM 
      ZL.IYDHORASFUNCBUG 
    WHERE 
      BUG <> 0 
    GROUP BY BUG) AS HORAS ON HORAS.BUG = B.CODIN
WHERE 
  DTIYDEMB.CODINT = @DEMO