SELECT 
	* 
INTO 
	#TT 
FROM 
	[DBO].[FUNC_RRHH_REPORTELIHL_FICHAJE](@FECHADESDE, @FECHAHASTA) AS FICHAJE;

INSERT INTO #TT (
	LEGAJO
	, CAPENOM
	, FECHA
	, ESQUEMA
	, AUS.Codpuesto
	, AUS.Area
	, AUS.Sector
	, AUS.AsigEsq
	, TIPOINCUMPLIMIENTO) 
SELECT 
	AUS.LEGAJO
	, AUS.CAPENOM
	, AUS.FECHA
	, AUS.ESQLAB
	, AUS.Codpuesto
	, AUS.Area
	, AUS.Sector
	, AUS.AsigEsq
	, AUS.TIPOINCUMPLIMIENTO 
FROM 
	[DBO].[FUNC_RRHH_REPORTELIHL_AUSENCIAS](@FECHADESDE, @FECHAHASTA) AS AUS;

SELECT 
	* 
FROM 
	#TT
WHERE
	#TT.CODPUESTO IN (@PUESTOS)
	AND #TT.AREA IN (@Areas)
	AND #TT.SECTOR IN (@Sectores)
	AND #TT.TIPOINCUMPLIMIENTO IN (@TIPOINCUMPLIMIENTO)
	AND #TT.LEGAJO IN (@LEGAJO)
--	AND #TT.TIPO IN (@TIPO);
