USE [ZL]
GO

/****** Object:  StoredProcedure [ZL].[sp_CalculodeObjetivosxPuesto]    Script Date: 04/11/2013 10:55:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ZL].[sp_CalculodeObjetivosxPuesto]') AND type in (N'P', N'PC'))
DROP PROCEDURE [ZL].[sp_CalculodeObjetivosxPuesto]
GO

USE [ZL]
GO

/****** Object:  StoredProcedure [ZL].[sp_CalculodeObjetivosxPuesto]    Script Date: 04/11/2013 10:55:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================================
-- Author:		Hector Daniel Correa / Gaston Malusardi
-- Create date: 10/04/2013
-- Description:	Herramienta de calculo para objetivos por puesto
-- =============================================================
CREATE PROCEDURE [ZL].[sp_CalculodeObjetivosxPuesto] 
	@FECHA AS DATETIME = GETDATE
	, @PUESTO AS VARCHAR(4)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE
		@OBJEXPTO_CODIGO AS INT
		, @OBJETIVOS_CODOBJE AS INT
		, @OBJETIVOS_PESOOBJE AS NUMERIC(10,5)
		, @OBJETIVOS_TIPOOBJE AS INT
		, @OBJETIVOS_PESOTIPO AS NUMERIC(10,5)
		, @OBJETIVO_DESCR AS VARCHAR(254)
		, @OBJSQL AS NVARCHAR(MAX)
		, @VALOR AS NUMERIC(10,5)
		, @LEGAJO AS VARCHAR(20)
		, @MULTIPLICADOR AS NUMERIC(10, 5)
		, @NUMEROOBJINDIV AS INT
		, @NITEM AS INT;
	IF (@PUESTO <> '')
	BEGIN
		DECLARE OBJETIVOS CURSOR FOR
		SELECT
			OBJEXPTO.CODIGO 
			, PUESTO.COD AS PUESTO
			, LEGAJOS.Legajo AS LEGAJO
			, OBJETIVOS.CODOBJE
			, OBJETIVO.DESCR
			, OBJETIVOS.PESOOBJE
			, OBJETIVOS.TIPOOBJE
			, OBJETIVOS.PESOTIPO
			, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL) AS [OBJSQL]
		  FROM 
			[ZL].[ZL].[OBJEXPTO] AS OBJEXPTO
			LEFT JOIN [ZL].[ZL].OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJEXPTO.CODIGO
			LEFT JOIN [ZL].[ZL].OBJET AS OBJETIVO ON OBJETIVO.COD = OBJETIVOS.CODOBJE
			LEFT JOIN [ZL].[ZL].PUESTOSRH AS PUESTO ON PUESTO.COD = OBJEXPTO.PUESTO
			LEFT JOIN (	SELECT Legajo, Puesto FROM ZL.[Funciones].[LegajoActivo]('', @FECHA)) AS LEGAJOS ON LEGAJOS.Puesto = PUESTO.COD
		WHERE
			@FECHA BETWEEN OBJEXPTO.DESDE AND OBJEXPTO.HASTA
			AND PUESTO.COD = @PUESTO
		GROUP BY
			OBJEXPTO.CODIGO
			, PUESTO.COD 
			, LEGAJOS.Legajo
			, OBJETIVO.DESCR
			, OBJETIVOS.CODOBJE
			, OBJETIVOS.PESOOBJE
			, OBJETIVOS.TIPOOBJE
			, OBJETIVOS.PESOTIPO
			, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL);
	END
	ELSE
	BEGIN
		DECLARE OBJETIVOS CURSOR FOR
		SELECT
			OBJEXPTO.CODIGO 
			, PUESTO.COD AS PUESTO
			, LEGAJOS.Legajo AS LEGAJO
			, OBJETIVOS.CODOBJE
			, OBJETIVO.DESCR
			, OBJETIVOS.PESOOBJE
			, OBJETIVOS.TIPOOBJE
			, OBJETIVOS.PESOTIPO
			, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL) AS [OBJSQL]
		  FROM 
			[ZL].[ZL].[OBJEXPTO] AS OBJEXPTO
			LEFT JOIN [ZL].[ZL].OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJEXPTO.CODIGO
			LEFT JOIN [ZL].[ZL].OBJET AS OBJETIVO ON OBJETIVO.COD = OBJETIVOS.CODOBJE
			LEFT JOIN [ZL].[ZL].PUESTOSRH AS PUESTO ON PUESTO.COD = OBJEXPTO.PUESTO
			LEFT JOIN (	SELECT Legajo, Puesto FROM ZL.[Funciones].[LegajoActivo]('', @FECHA)) AS LEGAJOS ON LEGAJOS.Puesto = PUESTO.COD
		WHERE
			@FECHA BETWEEN OBJEXPTO.DESDE AND OBJEXPTO.HASTA
		GROUP BY
			OBJEXPTO.CODIGO
			, PUESTO.COD 
			, LEGAJOS.Legajo
			, OBJETIVO.DESCR
			, OBJETIVOS.CODOBJE
			, OBJETIVOS.PESOOBJE
			, OBJETIVOS.TIPOOBJE
			, OBJETIVOS.PESOTIPO
			, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL);
	END
	OPEN OBJETIVOS;

	FETCH NEXT FROM OBJETIVOS INTO 
		@OBJEXPTO_CODIGO
		, @PUESTO
		, @LEGAJO
		, @OBJETIVOS_CODOBJE
		, @OBJETIVO_DESCR
		, @OBJETIVOS_PESOOBJE
		, @OBJETIVOS_TIPOOBJE
		, @OBJETIVOS_PESOTIPO
		, @OBJSQL;
		DELETE FROM zl.ObjeIndivalObD;
		
	WHILE @@FETCH_STATUS = 0
	BEGIN
		CREATE TABLE #VALORES (VALOR NUMERIC(10, 5));
		INSERT INTO #VALORES EXEC sp_executesql @OBJSQL;
		SET @VALOR = (SELECT VALOR FROM #VALORES);
		SET @MULTIPLICADOR = (SELECT VALOR FROM ZL.OBJETDET WHERE NUMERO = @OBJETIVOS_CODOBJE AND @VALOR >= DESDE AND @VALOR <= HASTA);
		SET @MULTIPLICADOR = (SELECT ISNULL(@MULTIPLICADOR, @VALOR));
		SET @VALOR = @MULTIPLICADOR;
		SET @VALOR = @VALOR * @OBJETIVOS_PESOOBJE;
		SET @VALOR = @VALOR * @OBJETIVOS_PESOTIPO;
		SELECT @NITEM = MAX(zl.ObjeIndivalObD.NITEM), @NUMEROOBJINDIV = OBJEINDIVAL.NUMERO
							   FROM ZL.OBJEINDIVAL 
								LEFT JOIN zl.ObjeIndivalObD ON zl.ObjeIndivalObD.CODIGO = ZL.OBJEINDIVAL.NUMERO
							   WHERE ZL.OBJEINDIVAL.LEGAJO = @LEGAJO
							   GROUP BY OBJEINDIVAL.NUMERO;

		INSERT INTO zl.ObjeIndivalObD (CODIGO, CODOBJE, DESOBJE, NITEM, VALOR) VALUES (@NUMEROOBJINDIV, @OBJETIVOS_CODOBJE, @OBJETIVO_DESCR, @NITEM+1, @VALOR);
		
		--SELECT @VALOR, @NUMEROOBJINDIV;
		
		FETCH NEXT FROM OBJETIVOS INTO 
			@OBJEXPTO_CODIGO
			, @PUESTO
			, @LEGAJO
			, @OBJETIVOS_CODOBJE
			, @OBJETIVO_DESCR
			, @OBJETIVOS_PESOOBJE
			, @OBJETIVOS_TIPOOBJE
			, @OBJETIVOS_PESOTIPO
			, @OBJSQL;
		
		DROP TABLE #VALORES;
	END

	CLOSE OBJETIVOS;
	DEALLOCATE OBJETIVOS;

END


GO


