SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Hector Daniel Correa
-- Create date: 10/04/2013
-- Description:	Herramienta de calculo para objetivos por legajo
-- =============================================
CREATE PROCEDURE sp_CalculodeObjetivo 
	@FECHA AS DATETIME
	, @PUESTO AS VARCHAR(4)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE
		@OBJEXPTO_CODIGO AS INT
		, @OBJETIVOS_CODOBJE AS INT
		, @OBJETIVOS_PESOOBJE AS NUMERIC(5,2)
		, @OBJETIVOS_TIPOOBJE AS INT
		, @OBJETIVOS_PESOTIPO AS NUMERIC(5,2)
		, @OBJETIVO_DESCR AS VARCHAR(254)
		, @OBJSQL AS NVARCHAR(MAX)
		, @VALOR AS NUMERIC(10,5)
		, @LEGAJO AS VARCHAR(20)
		, @MULTIPLICADOR AS NUMERIC(5, 2)
		, @NUMEROOBJINDIV AS INT
		, @NITEM AS INT;

	DECLARE OBJETIVOS CURSOR FOR
	SELECT
		OBJEXPTO.CODIGO 
		, PUESTO.COD AS PUESTO
		, LEGAJOS.CCOD AS LEGAJO
		, OBJETIVOS.CODOBJE
		, OBJETIVO.DESCR
		, OBJETIVOS.PESOOBJE
		, OBJETIVOS.TIPOOBJE
		, OBJETIVOS.PESOTIPO
		, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL) AS [OBJSQL]
	  FROM 
		[ZL].[ZL].[OBJEXPTO] AS OBJEXPTO
		LEFT JOIN [ZL].[ZL].OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJEXPTO.CODIGO
		LEFT JOIN [ZL].[ZL].OBJET AS OBJETIVO ON OBJETIVO.COD = OBJETIVOS.CODOBJE
		LEFT JOIN [ZL].[ZL].PUESTOSRH AS PUESTO ON PUESTO.COD = OBJEXPTO.PUESTO
		LEFT JOIN (	SELECT L.CCOD, C.CPUESTO
					FROM ZL.CARRZL C
						INNER JOIN ZL.LEGOPS AS L ON L.CLEGAJO = C.CCOD
						INNER JOIN ZL.LEGAJO J ON J.CCOD = C.CCOD      
					WHERE J.FEGRESO = '19000101'
						AND ( C.FFIN >= @FECHA OR C.FFIN = '19000101' )
						AND LTRIM(RTRIM(C.CPUESTO)) <> '' ) AS LEGAJOS ON LEGAJOS.CPUESTO = PUESTO.COD
	WHERE
		@FECHA BETWEEN OBJEXPTO.DESDE AND OBJEXPTO.HASTA
		AND PUESTO.COD = @PUESTO
	GROUP BY
		OBJEXPTO.CODIGO
		, PUESTO.COD 
		, LEGAJOS.CCOD
		, OBJETIVO.DESCR
		, OBJETIVOS.CODOBJE
		, OBJETIVOS.PESOOBJE
		, OBJETIVOS.TIPOOBJE
		, OBJETIVOS.PESOTIPO
		, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL);

	OPEN OBJETIVOS;

	FETCH NEXT FROM OBJETIVOS INTO 
		@OBJEXPTO_CODIGO
		, @PUESTO
		, @LEGAJO
		, @OBJETIVOS_CODOBJE
		, @OBJETIVO_DESCR
		, @OBJETIVOS_PESOOBJE
		, @OBJETIVOS_TIPOOBJE
		, @OBJETIVOS_PESOTIPO
		, @OBJSQL;
		
	WHILE @@FETCH_STATUS = 0
	BEGIN
		CREATE TABLE #VALORES (VALOR NUMERIC);
		INSERT INTO #VALORES EXEC sp_executesql @OBJSQL;
		SET @VALOR = (SELECT VALOR FROM #VALORES);
		SET @MULTIPLICADOR = (SELECT VALOR FROM ZL.OBJETDET WHERE NUMERO = @OBJETIVOS_CODOBJE AND @VALOR >= DESDE AND @VALOR <= HASTA);
		SET @VALOR = @MULTIPLICADOR;
		SET @VALOR = @VALOR * @OBJETIVOS_PESOOBJE;
		SET @VALOR = @VALOR * @OBJETIVOS_PESOTIPO;
		SELECT @NITEM = MAX(zl.ObjeIndivalObD.NITEM), @NUMEROOBJINDIV = OBJEINDIVAL.NUMERO
							   FROM ZL.OBJEINDIVAL 
								LEFT JOIN zl.ObjeIndivalObD ON zl.ObjeIndivalObD.CODIGO = ZL.OBJEINDIVAL.NUMERO
							   WHERE ZL.OBJEINDIVAL.LEGAJO = @LEGAJO
							   GROUP BY OBJEINDIVAL.NUMERO;

		INSERT INTO zl.ObjeIndivalObD (CODIGO, CODOBJE, DESOBJE, NITEM, VALOR) VALUES (@NUMEROOBJINDIV, @OBJETIVOS_CODOBJE, @OBJETIVO_DESCR, @NITEM+1, @VALOR);
		
		SELECT @VALOR, @NUMEROOBJINDIV;
		
		FETCH NEXT FROM OBJETIVOS INTO 
			@OBJEXPTO_CODIGO
			, @PUESTO
			, @LEGAJO
			, @OBJETIVOS_CODOBJE
			, @OBJETIVO_DESCR
			, @OBJETIVOS_PESOOBJE
			, @OBJETIVOS_TIPOOBJE
			, @OBJETIVOS_PESOTIPO
			, @OBJSQL;
		
		DROP TABLE #VALORES;
	END

	CLOSE OBJETIVOS;
	DEALLOCATE OBJETIVOS;

END
GO
