USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_CalculodeObjetivosxLegajo]    Script Date: 08/30/2013 14:45:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[sp_CalculodeObjetivosxLegajo]') AND type in (N'P', N'PC'))
DROP PROCEDURE [Objetivos].[sp_CalculodeObjetivosxLegajo]
GO

USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_CalculodeObjetivosxLegajo]    Script Date: 08/30/2013 14:45:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [Objetivos].[sp_CalculodeObjetivosxLegajo]
	@FECHA DATETIME = GETDATE
	, @LEGAJO VARCHAR(4)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE 
		@CODIGO AS UNIQUEIDENTIFIER
		, @ID AS INT
		, @OBSQLOBJE AS NVARCHAR(MAX)
		, @OBSQLFILT AS NVARCHAR(MAX)
		, @PesoObjetivo AS NUMERIC(10,5)
		, @PesoTipoObjetivo AS NUMERIC(10,5)
		, @tmpValor AS NUMERIC(10,5)
		, @CODLEGAJO AS VARCHAR(4)
		, @CODOBJEXPUESTO AS INT 
		, @DESDE AS DATETIME
		, @HASTA AS DATETIME
		, @NUMERO AS INT
		, @CODOBJETIVO AS INT
		, @OBJETIVO AS VARCHAR(100)
		, @ITEM AS INT
		, @COMP AS INT
		, @EscObjeDesde AS NUMERIC(10,5)
		, @EscObjeHasta AS NUMERIC(10,5)
		, @ApliEsc BIT
		, @ROBSQLOBJE AS NUMERIC(10,5)
		, @PUESTO AS VARCHAR(4);
		
	DECLARE @DETALLE TABLE(
		CODIGO INT IDENTITY PRIMARY KEY
		, CodLegajo VARCHAR(4)
		, CodPuesto VARCHAR(4)
		, Puesto VARCHAR(60) 
		, FechaInicio DATETIME
		, FechaFinal DATETIME
		, CodArea VARCHAR(4)
		, Area VARCHAR(60)
		, CodSector VARCHAR(4)
		, Sector VARCHAR(60)
		, CodObjetivo INT
		, Objetivo VARCHAR(100)
		, PesoObjetivo NUMERIC(10,5)
		, TipoObjetivo INT
		, OBSQLOBJE NVARCHAR(MAX)
		, ROBSQLOBJE NUMERIC(10,5)
		, EscObjeDesde NUMERIC(10,5)
		, EscObjeHasta NUMERIC(10,5)
		, EscObjeValor NUMERIC(10,5)
		, CodTipoObjetivo INT
		, DescrTipoObjetivo VARCHAR(60)
		, PesoTipoObjetivo NUMERIC(10,5)
		, PesoRelObjetivo NUMERIC(10,5)
		, ValorFinalObjetivo NUMERIC(10,5)
		, CodFiltro INT
		, Filtro VARCHAR(100)
		, OBSQLFILT NVARCHAR(MAX)
		, ROBSQLFILT NUMERIC(10,5)
		, EscFiltroDesde NUMERIC(10,5)
		, EscFiltroHasta NUMERIC(10,5)
		, EscFiltroValor NUMERIC(10,5)
		, PesoRelFiltro NUMERIC(10,5)
		, CodObjexPuesto INT
		, ApliEsc BIT);
	
	SELECT @PUESTO = Puesto FROM [ZL].[Objetivos].[LegajoActivo](@LEGAJO, @FECHA);

	INSERT INTO @DETALLE
		SELECT 
			LEGAJOS.CCOD
			, CARRERA.CPUESTO
			, PUESTO.DESCR
			, OBJINDIVIDUALES.DESDE
			, OBJINDIVIDUALES.HASTA
			, PUESTO.AREA
			, AREAS.DESCRIP
			, AREAS.SECTOR
			, SECTOR.DESCRIP
			--OBJETIVOS DEL PUESTO
			, OBJETIVO.COD
			, OBJETIVO.DESCR
			, OBJETIVO.PESO
			, ISNULL(OBJETIVO.TIPO, 0)
			, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL)
			, 0.00
			, ESCOBJETIVO.DESDE
			, ESCOBJETIVO.HASTA
			, ESCOBJETIVO.VALOR
			, TIPOS.CODIGO
			, TIPOS.DESCRIP
			, TIPOS.PESO
			, 0.00
			, 0.00
			--FILTROS DEL PUESTO
			, ISNULL(FILTROS.COD, 0)
			, ISNULL(FILTROS.DESCRIP, '')
			, ISNULL(CONVERT(NVARCHAR(MAX), FILTROS.OBSQL), '')
			, 0.00
			, ISNULL(ESCFILTRO.DESDE, 0)
			, ISNULL(ESCFILTRO.HASTA, 0)
			, ISNULL(ESCFILTRO.VALOR, 0)
			, 0.00
			, OBJINDIVIDUALES.CODIGO
			, OBJETIVO.APLIESC
		FROM 
			ZL.ZL.LEGAJO AS LEGAJOS
			LEFT JOIN ZL.ZL.CARRZL AS CARRERA ON CARRERA.CCOD = LEGAJOS.CCOD AND CARRERA.CPUESTO = @PUESTO
			INNER JOIN ZL.ZL.PUESTOSRH AS PUESTO ON PUESTO.COD = CARRERA.CPUESTO
			LEFT JOIN ZL.ZL.AREA AS AREAS ON AREAS.CODIGO = PUESTO.AREA
			LEFT JOIN ZL.ZL.SECTORES AS SECTOR ON SECTOR.CODIGO = AREAS.SECTOR  
			--OBJETIVOS POR PUESTO
			LEFT JOIN ZL.ZL.OBJEXPTO AS OBJINDIVIDUALES ON OBJINDIVIDUALES.PUESTO = PUESTO.COD
				AND @FECHA BETWEEN OBJINDIVIDUALES.DESDE AND OBJINDIVIDUALES.HASTA
			LEFT JOIN ZL.ZL.OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJINDIVIDUALES.CODIGO
			-- DETALLES DE CADA OBJETIVO
			LEFT JOIN ZL.ZL.OBJET AS OBJETIVO ON OBJETIVO.COD = OBJETIVOS.CODOBJE 
			LEFT JOIN ZL.ZL.OBJETDET AS ESCOBJETIVO ON ESCOBJETIVO.NUMERO = OBJETIVO.COD
			LEFT JOIN ZL.ZL.TIPOOBJE AS TIPOS ON TIPOS.CODIGO = OBJETIVO.TIPO 
			--FILTROS POR PUESTO
			LEFT JOIN ZL.ZL.FILTDET AS FILTRO ON FILTRO.CODIGO = OBJINDIVIDUALES.CODIGO
			LEFT JOIN ZL.ZL.FILTOBJE AS FILTROS ON FILTROS.COD = FILTRO.CODFILT
			LEFT JOIN ZL.ZL.FILTOBJEDET AS ESCFILTRO ON ESCFILTRO.NUMERO = FILTROS.COD
		WHERE
			LEGAJOS.CCOD = @LEGAJO
			;

	--CREAMOS UN CURSOR PARA RECORRER Y AGREGAR Y MODIFICAR DATOS COMO PESO Y RESULTADO DE LOS OBJETOS SQL
	DECLARE DETALLE CURSOR FOR SELECT CODIGO, CODLEGAJO, OBSQLOBJE, OBSQLFILT, FechaInicio, FechaFinal, EscObjeDesde, EscObjeHasta, ApliEsc  FROM @DETALLE;
	OPEN DETALLE;
	FETCH NEXT FROM DETALLE INTO @ID, @CODLEGAJO, @OBSQLOBJE, @OBSQLFILT, @DESDE, @HASTA, @EscObjeDesde, @EscObjeHasta, @ApliEsc;
	CREATE TABLE #VALOR (VALOR NUMERIC(10, 5));

	WHILE @@FETCH_STATUS = 0
	BEGIN

		SET @OBSQLOBJE = REPLACE(@OBSQLOBJE, 'Legajo', CHAR(39) + @CODLEGAJO + CHAR(39));
		SET @OBSQLOBJE = REPLACE(@OBSQLOBJE, '@', '');
		SET @OBSQLOBJE = REPLACE(@OBSQLOBJE, 'FechaInicio', CHAR(39) + CONVERT(VARCHAR(10), @DESDE, 112) + CHAR(39));
		SET @OBSQLOBJE = REPLACE(@OBSQLOBJE, 'FechaFin', CHAR(39) + CONVERT(VARCHAR(10), @HASTA, 112) + CHAR(39));
		SET @OBSQLOBJE = REPLACE(@OBSQLOBJE, '@', '');
		INSERT INTO #VALOR EXEC sp_executesql @OBSQLOBJE;
		UPDATE @DETALLE SET ROBSQLOBJE = (SELECT VALOR FROM #VALOR) WHERE CODIGO = @ID;
		DELETE FROM #VALOR;

		IF @ApliEsc = 1
			BEGIN
				SELECT @ROBSQLOBJE = ROBSQLOBJE FROM @DETALLE WHERE CODIGO = @ID
				IF @ROBSQLOBJE >= @EscObjeDesde AND @ROBSQLOBJE <= @EscObjeHasta
					BEGIN
						UPDATE @DETALLE SET EscObjeValor = (SELECT EscObjeValor FROM @DETALLE WHERE CODIGO = @ID) WHERE CODIGO = @ID
					END
				ELSE
					BEGIN
						UPDATE @DETALLE SET EscObjeValor = 0 WHERE CODIGO = @ID
					END
			END
		ELSE
			BEGIN
				UPDATE @DETALLE SET 
					EscObjeValor = @ROBSQLOBJE
					, EscObjeDesde = 0
					, EscObjeHasta = 99.9999
				WHERE 
					CODIGO = @ID
			END 

		SET @OBSQLFILT = REPLACE(@OBSQLFILT, 'Legajo', CHAR(39) + @CODLEGAJO + CHAR(39));
		SET @OBSQLFILT = REPLACE(@OBSQLFILT, '@', '');
		SET @OBSQLFILT = REPLACE(@OBSQLFILT, 'FechaInicio', CHAR(39) + CONVERT(VARCHAR(10), @DESDE, 112) + CHAR(39));
		SET @OBSQLFILT = REPLACE(@OBSQLFILT, 'FechaFin', CHAR(39) + CONVERT(VARCHAR(10), @HASTA, 112) + CHAR(39));
		SET @OBSQLFILT = REPLACE(@OBSQLFILT, '@', '');
		INSERT INTO #VALOR EXEC sp_executesql @OBSQLFILT;
		UPDATE @DETALLE SET ROBSQLFILT = (SELECT VALOR FROM #VALOR) WHERE CODIGO = @ID;
		DELETE FROM #VALOR;
		
		SELECT @tmpValor = EscFiltroValor FROM @DETALLE WHERE ROBSQLFILT >= EscFiltroDesde AND ROBSQLFILT <= EscFiltroHasta AND CODIGO = @ID
		UPDATE @DETALLE SET EscFiltroValor = @tmpValor WHERE CODIGO = @ID

		SELECT @tmpValor = (SELECT EscObjeValor * PesoObjetivo FROM @DETALLE WHERE CODIGO = @ID AND ROBSQLOBJE >= EscObjeDesde AND ROBSQLOBJE <= EscObjeHasta)
		UPDATE @DETALLE SET PesoRelObjetivo = ISNULL(@tmpValor, 0) WHERE CODIGO = @ID
		SET @tmpValor = 0;

		SELECT @tmpValor = (SELECT PesoRelObjetivo * PesoTipoObjetivo FROM @DETALLE WHERE CODIGO = @ID AND ROBSQLOBJE >= EscObjeDesde AND ROBSQLOBJE <= EscObjeHasta)
		UPDATE @DETALLE SET ValorFinalObjetivo = ISNULL(@tmpValor, 0) WHERE CODIGO = @ID
		SET @tmpValor = 0;

		SELECT @tmpValor = (SELECT EscFiltroValor * ROBSQLFILT FROM @DETALLE WHERE CODIGO = @ID AND ROBSQLFILT >= EscFiltroDesde AND ROBSQLFILT <= EscFiltroHasta)
		UPDATE @DETALLE SET PesoRelFiltro = ISNULL(@tmpValor, 0) WHERE CODIGO = @ID

		SET @tmpValor = 0;
		SET @ID = NULL;
		SET @OBSQLOBJE = N'';
		SET @OBSQLFILT = N'';
		SET @LEGAJO = NULL;
		SET @DESDE = NULL;
		SET @HASTA = NULL;
		FETCH NEXT FROM DETALLE INTO @ID, @CODLEGAJO, @OBSQLOBJE, @OBSQLFILT, @DESDE, @HASTA, @EscObjeDesde, @EscObjeHasta, @ApliEsc;
	END
	CLOSE DETALLE;
	DEALLOCATE DETALLE;
	
	DECLARE DETALLE CURSOR FOR
	SELECT DISTINCT 
		CodLegajo
		, CodObjexPuesto
		, FechaInicio
		, FechaFinal
	FROM 
		@DETALLE 
	OPEN DETALLE;
	FETCH NEXT FROM DETALLE INTO @CODLEGAJO, @CODOBJEXPUESTO, @DESDE, @HASTA;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @CODIGO = (SELECT ISNULL(CODIGO, '') FROM [ZL].[ZL].OBJEINDIVAL WHERE LEGAJO = @CODLEGAJO AND OBJXPTO = @CODOBJEXPUESTO);
		DELETE FROM [ZL].[ZL].OBJEINDIVAL WHERE LEGAJO = @CODLEGAJO AND OBJXPTO = @CODOBJEXPUESTO;
		DELETE FROM [ZL].[ZL].OBJEINDIVALOBD WHERE CODIGO = @CODIGO;
		DELETE FROM [ZL].[ZL].OBJEINDIVALOBF WHERE CODIGO = @CODIGO;
		IF @CODIGO IS NULL
		BEGIN
			SET @CODIGO = NEWID();
		END
		INSERT INTO [ZL].[ZL].OBJEINDIVAL(
			CODIGO
			, DESDE
			, FALTAFW
			, FECHA
			, HALTAFW
			, HASTA
			, LEGAJO
			, OBJXPTO
			, UALTAFW
			, LEGAJOOP
			, BDALTAFW
			, SALTAFW
			, BDMODIFW
			, FMODIFW
			, HMODIFW
			, SMODIFW
			, UMODIFW
		) VALUES (
			@CODIGO
			, @DESDE
			, CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 103), 103)
			, CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 103), 103)
			, CONVERT(VARCHAR(8), GETDATE(), 108)
			, @HASTA
			, @CODLEGAJO 
			--, ''
			, @CODOBJEXPUESTO
			, 'ZL'
			, ''
			, 'ZL'
			, '0000000'
			, 'ZL'
			, GETDATE()
			, CONVERT(VARCHAR(8), GETDATE(), 108)
			, '0000000'
			, 'ZL'
		);

		--INSERTAMOS EL DETALLE DE OBJETIVOS
		INSERT INTO [ZL].[ZL].OBJEINDIVALOBD (
			CODIGO
			, CODOBJE
			, DESOBJE
			, VALOR
		) 
		SELECT
			@CODIGO
			, CodObjetivo
			, Objetivo
			, ROBSQLOBJE
		FROM
			@DETALLE
		WHERE
			CodLegajo = @CODLEGAJO
			AND CodObjexPuesto = @CODOBJEXPUESTO
		GROUP BY
			CodObjetivo
			, Objetivo
			, ROBSQLOBJE
		ORDER BY
			CodObjetivo;
		--INSERTAMOS EL DETALLE DE FILTROS
		INSERT INTO [ZL].[ZL].OBJEINDIVALOBF (
			CODIGO
			, CODFIL
			, DESFIL
			, VALOR
		) 
		SELECT
			@CODIGO
			, CodFiltro
			, Filtro
			, ROBSQLFILT
		FROM
			@DETALLE
		WHERE
			CODLegajo = @CODLEGAJO
			AND CodObjexPuesto = @CODOBJEXPUESTO
		GROUP BY
			CodFiltro
			, Filtro
			, ROBSQLFILT
		ORDER BY
			CodFiltro;
		--PASAMOS AL SIGUIENTE REGISTRO DEL CURSOR
		FETCH NEXT FROM DETALLE INTO @CODLEGAJO, @CODOBJEXPUESTO, @DESDE, @HASTA;
	END

	----UPDATEAMOS ACCIONES DE LA HERRAMIENTA DE CALCULO SI EXISTIESE EL COMPROBANTE POR LEGAJO
	--UPDATE [ZL].[ZL].[CALCOBJ] SET
	--	ACC = CONVERT(VARCHAR(MAX), 'Último cálculo: '+CONVERT(VARCHAR(20), GETDATE(), 103))+' '+CONVERT(VARCHAR(8), GETDATE(), 108)
	--	+CHAR(13)+CONVERT(VARCHAR(MAX), ACC)
	--WHERE 
	--	[LEGAJO] = @CODLEGAJO; 

	----UPDATEAMOS ACCIONES DEL OBJETIVO POR PUESTO CORRESPONDIENTE
	--UPDATE [ZL].[ZL].OBJEXPTO SET
	--	ACC = CONVERT(VARCHAR(MAX), 'Último cálculo: '+CONVERT(VARCHAR(20), GETDATE(), 103))+' '+CONVERT(VARCHAR(8), GETDATE(), 108)
	--	+ ' Legajo: '+@CODLEGAJO+CHAR(13)+CONVERT(VARCHAR(MAX), ACC)
	--WHERE
	--	CODIGO IN (SELECT CODIGO FROM [ZL].[ZL].OBJEXPTO WHERE PUESTO = @PUESTO);

			
	CLOSE DETALLE;
	DEALLOCATE DETALLE;

	SELECT 
		DISTINCT 
		*
	FROM 
		@DETALLE
		
END



GO


