USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_CalculodeFiltrosxLegajo]    Script Date: 04/25/2013 14:17:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[sp_CalculodeFiltrosxLegajo]') AND type in (N'P', N'PC'))
DROP PROCEDURE [Objetivos].[sp_CalculodeFiltrosxLegajo]
GO

USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_CalculodeFiltrosxLegajo]    Script Date: 04/25/2013 14:17:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [Objetivos].[sp_CalculodeFiltrosxLegajo]
	@FECHA DATETIME = GETDATE
	, @LEGAJO VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE 
		@ID AS INT
		, @tmpValor AS NUMERIC(10,5);

	DECLARE @DETALLE TABLE(
		ID INT IDENTITY PRIMARY KEY
		, CODFIL INT
		, Filtro VARCHAR(254)
		, FiltroValor NUMERIC(10,5)
		, EscFiltroDesde NUMERIC(10,5)
		, EscFiltroHasta NUMERIC(10,5)
		, EscFiltroValor NUMERIC(10,5)
		, EscObjxPtoDesde NUMERIC(10,5)
		, EscObjxPtoHasta NUMERIC(10,5)
		, EscObjxPtoValor NUMERIC(10,5)
		, ObjeValorInicial NUMERIC(10,5)
		, PesoRelFiltro NUMERIC(10,5)
		, PesoRelEscala NUMERIC(10,5));

	IF @LEGAJO <> ''
	BEGIN
		INSERT INTO @DETALLE
			--SELECT 
			--	DISTINCT
			--	LEGAJOS.CCOD
			--	, LEGAJOS.CLEGAJO
			--	, FILTDET.CODFILT
			--	, FILTDET.DESCFILT
			--	, CONVERT(NVARCHAR(MAX), FILTROS.OBSQL)
			--	, ZL.ZL.OBJEINDIVALOBF.VALOR
			--	, ISNULL(ESCFILTRO.DESDE, 0)
			--	, ISNULL(ESCFILTRO.HASTA, 0)
			--	, ISNULL(ESCFILTRO.VALOR, 0)
			--	, 0.00
			--	, OBJINDIVIDUALES.CODIGO
			--	, ESCOBXPTO.DESDE
			--	, ESCOBXPTO.HASTA
			--	, ESCOBXPTO.VALOR
			--FROM 
			--	ZL.ZL.LEGOPS AS LEGAJOS
			--	INNER JOIN ZL.ZL.OBJEINDIVAL ON ZL.ZL.OBJEINDIVAL.LEGAJO = LEGAJOS.CLEGAJO
			--	LEFT JOIN ZL.ZL.CARRZL AS CARRERA ON CARRERA.CCOD = LEGAJOS.CLEGAJO
			--		AND ISNULL(CARRERA.CPUESTO, '''') <> ''''
			--	LEFT JOIN ZL.ZL.PUESTOSRH AS PUESTO ON PUESTO.COD = CARRERA.CPUESTO
			--	LEFT JOIN ZL.ZL.AREA AS AREAS ON AREAS.CODIGO = PUESTO.AREA
			--	LEFT JOIN ZL.ZL.SECTORES AS SECTOR ON SECTOR.CODIGO = AREAS.SECTOR  

			--	--OBJETIVOS POR PUESTO
			--	LEFT JOIN ZL.ZL.OBJEXPTO AS OBJINDIVIDUALES ON OBJINDIVIDUALES.PUESTO = PUESTO.COD
			--		AND @FECHA BETWEEN OBJINDIVIDUALES.DESDE AND OBJINDIVIDUALES.HASTA
			--	LEFT JOIN ZL.ZL.OBJEESVADE AS ESCOBXPTO ON ESCOBXPTO.CODIGO = OBJINDIVIDUALES.CODIGO

			--	--FILTROS POR PUESTO
			--	LEFT JOIN ZL.ZL.OBJEINDIVALOBF ON ZL.ZL.OBJEINDIVALOBF.CODIGO = ZL.ZL.OBJEINDIVAL.CODIGO
			--	LEFT JOIN ZL.ZL.FILTDET AS FILTDET ON FILTDET.CODIGO = ZL.ZL.OBJEINDIVALOBF.CODFIL
			--	LEFT JOIN ZL.ZL.FILTOBJE AS FILTROS ON FILTROS.PUESTO = FILTDET.CODFILT
			--	LEFT JOIN ZL.ZL.FILTOBJEDET AS ESCFILTRO ON ESCFILTRO.NUMERO = FILTDET.CODFILT
			--WHERE
			--	LEGAJOS.CLEGAJO IN (@LEGAJO);
			SELECT 
				DISTINCT
				ZL.OBJEINDIVALOBF.CODFIL
				, ZL.OBJEINDIVALOBF.DESFIL [Filtro]
				, ZL.OBJEINDIVALOBF.VALOR [FiltroValor]
				, ZL.ZL.FILTOBJEDET.DESDE [EscFiltroDesde]
				, ZL.ZL.FILTOBJEDET.HASTA [EscFiltroHasta]
				, ZL.ZL.FILTOBJEDET.VALOR [EscFiltroValor]
				, ZL.OBJEESVADE.DESDE [EscObjxPtoDesde]
				, ZL.OBJEESVADE.HASTA [EscObjxPtoHasta]
				, ZL.OBJEESVADE.VALOR [EscObjxPtoValor]
				, ZL.OBJEINDIVALOBD.VALOR [ObjeValorInicial]
				, 0.00
				, 0.00
			FROM 
				--NOS FIJAMOS SI ESTÁ VIGENTE A LA FECHA PARAMETRIZADA Y DE AQUÍ SACAMOS A QUE PUESTO PERTENECE
				ZL.CARRZL
				--CON EL LEGAJO TENEMOS LOS OBJETIVOS Y FILTROS CALCULADOS INDIVIDUALMENTE
				LEFT JOIN ZL.OBJEINDIVAL ON ZL.OBJEINDIVAL.LEGAJO = ZL.CARRZL.CCOD
				--LEVANTAMOS CADA FILTRO INDIVIDUAL	
				LEFT JOIN ZL.OBJEINDIVALOBF ON ZL.OBJEINDIVALOBF.CODIGO = ZL.OBJEINDIVAL.CODIGO
				--LEVANTAMOS LA ESCALA PARA CADA FILTRO INDIVIDUAL
				LEFT JOIN ZL.FILTOBJE ON ZL.FILTOBJE.COD = ZL.OBJEINDIVALOBF.CODFIL
				LEFT JOIN ZL.FILTOBJEDET ON ZL.FILTOBJEDET.NUMERO = ZL.FILTOBJE.COD
					AND ZL.FILTOBJEDET.HASTA <> 0
				--LEVANTAMOS LA ESCALA DEL OBJETIVO POR PUESTO PARA EL RESULTADO FINAL
				LEFT JOIN ZL.OBJEXPTO ON ZL.OBJEXPTO.PUESTO = ZL.CARRZL.CPUESTO
				LEFT JOIN ZL.OBJEESVADE ON ZL.OBJEESVADE.CODIGO = ZL.OBJEXPTO.CODIGO
					AND ZL.OBJEESVADE.HASTA <> 0
				--LEVANTAMOS LOS OBJETIVOS INDIVIDUALES PARA SABER SU VALOR INICIAL
				LEFT JOIN ZL.OBJEINDIVALOBD ON ZL.OBJEINDIVALOBD.CODIGO = ZL.OBJEINDIVAL.CODIGO
			WHERE
				ZL.CARRZL.CCOD = @LEGAJO
				AND @FECHA BETWEEN ZL.CARRZL.FINICIO AND CASE ZL.CARRZL.FFIN WHEN 0 THEN GETDATE() ELSE ZL.CARRZL.FFIN END
				
	END
	ELSE
	BEGIN
		INSERT INTO @DETALLE
			SELECT 
				DISTINCT
				ZL.OBJEINDIVALOBF.CODFIL
				, ZL.OBJEINDIVALOBF.DESFIL [Filtro]
				, ZL.OBJEINDIVALOBF.VALOR [FiltroValor]
				, ZL.ZL.FILTOBJEDET.DESDE [EscFiltroDesde]
				, ZL.ZL.FILTOBJEDET.HASTA [EscFiltroHasta]
				, ZL.ZL.FILTOBJEDET.VALOR [EscFiltroValor]
				, ZL.OBJEESVADE.DESDE [EscObjxPtoDesde]
				, ZL.OBJEESVADE.HASTA [EscObjxPtoHasta]
				, ZL.OBJEESVADE.VALOR [EscObjxPtoValor]
				, ZL.OBJEINDIVALOBD.VALOR [ObjeValorInicial]
				, 0.00
				, 0.00
			FROM 
				--NOS FIJAMOS SI ESTÁ VIGENTE A LA FECHA PARAMETRIZADA Y DE AQUÍ SACAMOS A QUE PUESTO PERTENECE
				ZL.CARRZL
				--CON EL LEGAJO TENEMOS LOS OBJETIVOS Y FILTROS CALCULADOS INDIVIDUALMENTE
				LEFT JOIN ZL.OBJEINDIVAL ON ZL.OBJEINDIVAL.LEGAJO = ZL.CARRZL.CCOD
				--LEVANTAMOS CADA FILTRO INDIVIDUAL	
				LEFT JOIN ZL.OBJEINDIVALOBF ON ZL.OBJEINDIVALOBF.CODIGO = ZL.OBJEINDIVAL.CODIGO
				--LEVANTAMOS LA ESCALA PARA CADA FILTRO INDIVIDUAL
				LEFT JOIN ZL.FILTOBJE ON ZL.FILTOBJE.COD = ZL.OBJEINDIVALOBF.CODFIL
				LEFT JOIN ZL.FILTOBJEDET ON ZL.FILTOBJEDET.NUMERO = ZL.FILTOBJE.COD
					AND ZL.FILTOBJEDET.HASTA <> 0
				--LEVANTAMOS LA ESCALA DEL OBJETIVO POR PUESTO PARA EL RESULTADO FINAL
				LEFT JOIN ZL.OBJEXPTO ON ZL.OBJEXPTO.PUESTO = ZL.CARRZL.CPUESTO
				LEFT JOIN ZL.OBJEESVADE ON ZL.OBJEESVADE.CODIGO = ZL.OBJEXPTO.CODIGO
					AND ZL.OBJEESVADE.HASTA <> 0
				--LEVANTAMOS LOS OBJETIVOS INDIVIDUALES PARA SABER SU VALOR INICIAL
				LEFT JOIN ZL.OBJEINDIVALOBD ON ZL.OBJEINDIVALOBD.CODIGO = ZL.OBJEINDIVAL.CODIGO
	END
	--CREAMOS UN CURSOR PARA RECORRER Y AGREGAR Y MODIFICAR DATOS COMO PESO Y RESULTADO DE LOS OBJETOS SQL
	DECLARE DETALLE CURSOR FOR SELECT ID FROM @DETALLE;
	OPEN DETALLE;

	FETCH NEXT FROM DETALLE INTO @ID;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		--SELECT @tmpValor = EscFiltroValor FROM @DETALLE WHERE ObjeValorInicial >= EscFiltroDesde AND ObjeValorInicial <= EscFiltroHasta AND ID = @ID
		--UPDATE @DETALLE SET EscFiltroValor = ISNULL(@tmpValor, 0) WHERE ID = @ID

		SELECT @tmpValor = (SELECT EscFiltroValor * ObjeValorInicial FROM @DETALLE WHERE ID = @ID AND ObjeValorInicial >= EscFiltroDesde AND ObjeValorInicial <= EscFiltroHasta)
		UPDATE @DETALLE SET PesoRelFiltro = ISNULL(@tmpValor, 0) WHERE ID = @ID

		SET @tmpValor = 0;
		SET @ID = NULL;
		FETCH NEXT FROM DETALLE INTO @ID;
	END

	SELECT
		DISTINCT
		* 
	FROM 
		@DETALLE
	--WHERE 
	--	ObjexPuestoCod IS NOT NULL
	--	AND 
	--CodFil <> 0
	-- OR ROBSQLFILT = 0)
	-- PesoRelFiltro <> 0
	-- OR (EscFiltroDesde <= FiltroValor AND EscFiltroHasta >= FiltroValor))
	--OR (EscObjxPtoDesde = 0 AND EscObjxPtoHasta <> 0)

	CLOSE DETALLE;
	DEALLOCATE DETALLE;
		
END

GO

DECLARE @FECHA DATETIME, @LEGAJO VARCHAR(4);
SET @FECHA = GETDATE(); SET @LEGAJO = '';
EXEC [Objetivos].sp_CalculodeFiltrosxLegajo @FECHA, @LEGAJO;

