USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_ListadoObjetivosxPuesto]    Script Date: 04/19/2013 10:57:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[sp_ListadoObjetivosxPuesto]') AND type in (N'P', N'PC'))
DROP PROCEDURE [Objetivos].[sp_ListadoObjetivosxPuesto]
GO

USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_ListadoObjetivosxPuesto]    Script Date: 04/19/2013 10:57:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =======================================================
-- Author:		Hector Daniel Correa
-- Create date: 19/04/2013
-- Description:	Lista los Objetivos por puesto
--              para uno o varios puesto en una fecha dada
-- =======================================================
CREATE PROCEDURE [Objetivos].sp_ListadoObjetivosxPuesto
	@PUESTO VARCHAR(1000), 
	@FECHA DATETIME = GETDATE
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		--DATOS DE CABECERA
		OBJETIVOS.CODIGO AS [CODIGO]
		, OBJETIVOS.DESCRIP AS [DESCRIP]
		, OBJETIVOS.DESDE AS [DESDE]
		, OBJETIVOS.HASTA AS [HASTA]
		, OBJETIVOS.PUESTO AS [PUESTO]
		, PUESTOS.DESCR AS [PUESTODESCR]
		, OBJETIVOS.SECTOR AS [SECTOR]
		, OBJETIVOS.AREA AS [AREA]
		, OBJETIVOS.REPORTAA  AS [REPORTAA]
		, OBJETIVOS.ACC AS [ACC]
		, OBJETIVOS.OBS AS [OBS]
		--OBJETIVOS EN DETALLE
		, DETALLE.CODOBJE AS [CODOBJE]
		, DETALLE.DESCOBJE AS [DESCOBJE]
		, DETALLE.PESOOBJE AS [PESOOBJE]
		, DETALLE.TIPOOBJE AS [TIPOOBJE]
		, DETALLE.DESCTIPO AS [DESCTIPO]
		, DETALLE.PESOTIPO AS [PESOTIPO]
		, DETALLE.COMENT AS [COMENT]
		--ESCALA
		, ESCALA.DESDE AS [ESCDESDE]
		, ESCALA.HASTA AS [ESCHASTA]
		, ESCALA.VALOR AS [ESCVALOR]
		--FILTROS
		, FILTROS.CODFILT AS [CODFILT]
		, FILTROS.DESCFILT AS [DESCFILT]
		--INFO ADICIONAL
		, AREA.DESCRIP AS [AREADESCRIP]
		, SECTORES.DESCRIP AS [SECTDESCRIP]
		, REPORTAA.DESCR AS [REPORTAADESCR]
	FROM 
		ZL.OBJEXPTO AS OBJETIVOS
		LEFT JOIN ZL.OBJEXPTODET AS DETALLE ON DETALLE.CODIGO = OBJETIVOS.CODIGO
		LEFT JOIN ZL.OBJEESVADE AS ESCALA ON ESCALA.CODIGO = OBJETIVOS.CODIGO
		LEFT JOIN ZL.FILTDET AS FILTROS ON FILTROS.CODIGO = OBJETIVOS.CODIGO
		--INFO ADICIONAL
		LEFT JOIN ZL.AREA ON AREA.CODIGO = OBJETIVOS.AREA
		LEFT JOIN ZL.SECTORES ON SECTORES.CODIGO = OBJETIVOS.SECTOR
		LEFT JOIN ZL.PUESTOSRH AS PUESTOS ON PUESTOS.COD = OBJETIVOS.PUESTO
		LEFT JOIN ZL.PUESTOSRH AS REPORTAA ON REPORTAA.COD = OBJETIVOS.REPORTAA
	WHERE
		@FECHA BETWEEN OBJETIVOS.DESDE AND OBJETIVOS.HASTA
		AND OBJETIVOS.PUESTO IN (@PUESTO)
	ORDER BY
		OBJETIVOS.CODIGO
		, ESCALA.NITEM
		, FILTROS.NITEM;
END
GO
