USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_ReporteObjetivosxLegajo]    Script Date: 07/08/2013 11:30:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Objetivos].[sp_ReporteObjetivosxLegajo]') AND type in (N'P', N'PC'))
DROP PROCEDURE [Objetivos].[sp_ReporteObjetivosxLegajo]
GO

USE [ZL]
GO

/****** Object:  StoredProcedure [Objetivos].[sp_ReporteObjetivosxLegajo]    Script Date: 07/08/2013 11:30:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [Objetivos].[sp_ReporteObjetivosxLegajo]
	@FECHA DATETIME = GETDATE
	, @LEGAJO VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE 
		@ID AS INT
		, @OBSQLOBJE AS NVARCHAR(MAX)
		, @OBSQLFILT AS NVARCHAR(MAX)
		, @PesoObjetivo AS NUMERIC(10,5)
		, @PesoTipoObjetivo AS NUMERIC(10,5)
		, @tmpValor AS NUMERIC(10,5)
		, @ROBSQLOBJE AS NUMERIC(10, 5)
		, @EscObjeDesde AS NUMERIC(10, 5)
		, @EscObjeHasta AS NUMERIC(10, 5)
		, @APLICAESCALA AS BIT;

	DECLARE @DETALLE TABLE(
		ID INT IDENTITY PRIMARY KEY
		, CodLegajo VARCHAR(25)
		, Legajo VARCHAR(4)
		, Nombre VARCHAR(151)
		, CodPuesto VARCHAR(4)
		, Puesto VARCHAR(60) 
		, FechaInicio DATETIME
		, FechaFinal DATETIME
		, CodArea VARCHAR(4)
		, Area VARCHAR(60)
		, CodSector VARCHAR(4)
		, Sector VARCHAR(60)
		, CodObjetivo INT
		, Objetivo VARCHAR(100)
		, PesoObjetivo NUMERIC(10,5)
		, TipoObjetivo INT
		, OBSQLOBJE NVARCHAR(MAX)
		, ROBSQLOBJE NUMERIC(10,5)
		, EscObjeDesde NUMERIC(10,5)
		, EscObjeHasta NUMERIC(10,5)
		, EscObjeValor NUMERIC(10,5)
		, CodTipoObjetivo INT
		, DescrTipoObjetivo VARCHAR(60)
		, PesoTipoObjetivo NUMERIC(10,5)
		, PesoRelObjetivo NUMERIC(10,5)
		, ValorFinalObjetivo NUMERIC(10,5)
		--OBJETIVO POR PUESTO
		, ObjexPuestoCod INT 
		, ObjexPuestodesc VARCHAR(MAX) 
		, ObjexPuestodesde DATETIME 
		, ObjexPuestoHasta DATETIME
		, ApliEsc bit
		, SumPesosTipos NUMERIC(10,5));
	IF @LEGAJO <> ''
	BEGIN
		INSERT INTO @DETALLE
			SELECT 
				DISTINCT
				LEGAJOS.CCOD
				, LEGAJOS.CLEGAJO
				, LEGAJOS.CCORTESIA
				, CARRERA.CPUESTO
				, PUESTO.DESCR
				, CARRERA.FINICIO
				, CARRERA.FFIN
				, PUESTO.AREA
				, AREAS.DESCRIP
				, AREAS.SECTOR
				, SECTOR.DESCRIP
				--OBJETIVOS DEL PUESTO
				, OBJETIVO.COD
				, OBJETIVO.DESCR
				, OBJETIVO.PESO
				, ISNULL(OBJETIVO.TIPO, 0)
				, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL)
				, ISNULL(ZL.OBJEINDIVALOBD.VALOR, 0) as [RESOBSQL]
				, ISNULL(ESCOBJETIVO.DESDE, 0)
				, ISNULL(ESCOBJETIVO.HASTA, 99.9999)
				, ISNULL(ESCOBJETIVO.VALOR, 0)
				, TIPOS.CODIGO
				, TIPOS.DESCRIP
				, TIPOS.PESO
				, 0.00
				, 0.00
				--OBJETIVO POR PUESTO
				, OBJINDIVIDUALES.CODIGO
				, OBJINDIVIDUALES.DESCRIP
				, OBJINDIVIDUALES.DESDE
				, OBJINDIVIDUALES.HASTA
				, OBJETIVO.APLIESC
				, SUMPESOSTIPOS.SUMAPESOS
			FROM 
				ZL.ZL.LEGOPS AS LEGAJOS
				INNER JOIN ZL.ZL.OBJEINDIVAL ON ZL.ZL.OBJEINDIVAL.LEGAJO = LEGAJOS.CLEGAJO
				LEFT JOIN ZL.ZL.CARRZL AS CARRERA ON CARRERA.CCOD = LEGAJOS.CLEGAJO
					AND ISNULL(CARRERA.CPUESTO, '''') <> ''''
				LEFT JOIN ZL.ZL.PUESTOSRH AS PUESTO ON PUESTO.COD = CARRERA.CPUESTO
				LEFT JOIN ZL.ZL.AREA AS AREAS ON AREAS.CODIGO = PUESTO.AREA
				LEFT JOIN ZL.ZL.SECTORES AS SECTOR ON SECTOR.CODIGO = AREAS.SECTOR  

				-- DETALLES DE CADA OBJETIVO
				LEFT JOIN ZL.ZL.OBJEINDIVALOBD ON ZL.ZL.OBJEINDIVALOBD.CODIGO = ZL.ZL.OBJEINDIVAL.CODIGO
				LEFT JOIN ZL.ZL.OBJET AS OBJETIVO ON OBJETIVO.COD = ZL.ZL.OBJEINDIVALOBD.CODOBJE 
				LEFT JOIN ZL.ZL.OBJETDET AS ESCOBJETIVO ON ESCOBJETIVO.NUMERO = OBJETIVO.COD
					AND ZL.ZL.OBJEINDIVALOBD.VALOR >= ESCOBJETIVO.DESDE
					AND ZL.ZL.OBJEINDIVALOBD.VALOR <= ESCOBJETIVO.HASTA
				LEFT JOIN ZL.ZL.TIPOOBJE AS TIPOS ON TIPOS.CODIGO = OBJETIVO.TIPO 
				--OBJETIVOS POR PUESTO
				INNER JOIN ZL.ZL.OBJEXPTO AS OBJINDIVIDUALES ON OBJINDIVIDUALES.PUESTO = PUESTO.COD
					AND @FECHA BETWEEN OBJINDIVIDUALES.DESDE AND OBJINDIVIDUALES.HASTA
				INNER JOIN ZL.ZL.OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJINDIVIDUALES.CODIGO
				INNER JOIN (SELECT
								SPT.CODIGO
								, SUM(SPT.PESOTIPO) AS SUMAPESOS
							FROM
								(SELECT 
									DISTINCT
									ZL.ZL.OBJEXPTODET.CODIGO
									, ZL.ZL.OBJEXPTODET.TIPOOBJE 
									, ZL.ZL.OBJEXPTODET.PESOTIPO
								FROM 
									ZL.ZL.OBJEXPTODET
									INNER JOIN (SELECT DISTINCT PESOTIPO, TIPOOBJE, CODIGO FROM ZL.ZL.OBJEXPTODET GROUP BY TIPOOBJE, CODIGO, PESOTIPO) AS PESOSTIPOSDETALLE ON PESOSTIPOSDETALLE.CODIGO = ZL.ZL.OBJEXPTODET.CODIGO)
									AS SPT
							GROUP BY
								SPT.CODIGO) AS SUMPESOSTIPOS ON SUMPESOSTIPOS.CODIGO = OBJINDIVIDUALES.CODIGO
			WHERE
				LEGAJOS.CLEGAJO IN (@LEGAJO)
	END
	ELSE
	BEGIN
		INSERT INTO @DETALLE
			SELECT 
				DISTINCT
				LEGAJOS.CCOD
				, LEGAJOS.CLEGAJO
				, LEGAJOS.CCORTESIA
				, CARRERA.CPUESTO
				, PUESTO.DESCR
				, CARRERA.FINICIO
				, CARRERA.FFIN
				, PUESTO.AREA
				, AREAS.DESCRIP
				, AREAS.SECTOR
				, SECTOR.DESCRIP
				--OBJETIVOS DEL PUESTO
				, OBJETIVO.COD
				, OBJETIVO.DESCR
				, OBJETIVO.PESO
				, ISNULL(OBJETIVO.TIPO, 0)
				, CONVERT(NVARCHAR(MAX), OBJETIVO.OBSQL)
				, ISNULL(ZL.OBJEINDIVALOBD.VALOR, 0) as [RESOBSQL]
				, ISNULL(ESCOBJETIVO.DESDE, 0)
				, ISNULL(ESCOBJETIVO.HASTA, 99.9999)
				, ISNULL(ESCOBJETIVO.VALOR, 0)
				, TIPOS.CODIGO
				, TIPOS.DESCRIP
				, TIPOS.PESO
				, 0.00
				, 0.00
				--OBJETIVO POR PUESTO
				, OBJINDIVIDUALES.CODIGO
				, OBJINDIVIDUALES.DESCRIP
				, OBJINDIVIDUALES.DESDE
				, OBJINDIVIDUALES.HASTA
				, OBJETIVO.APLIESC
				, SUMPESOSTIPOS.SUMAPESOS
			FROM 
				ZL.ZL.LEGOPS AS LEGAJOS
				INNER JOIN ZL.ZL.OBJEINDIVAL ON ZL.ZL.OBJEINDIVAL.LEGAJO = LEGAJOS.CLEGAJO
				LEFT JOIN ZL.ZL.CARRZL AS CARRERA ON CARRERA.CCOD = LEGAJOS.CLEGAJO
					AND ISNULL(CARRERA.CPUESTO, '''') <> ''''
				LEFT JOIN ZL.ZL.PUESTOSRH AS PUESTO ON PUESTO.COD = CARRERA.CPUESTO
				LEFT JOIN ZL.ZL.AREA AS AREAS ON AREAS.CODIGO = PUESTO.AREA
				LEFT JOIN ZL.ZL.SECTORES AS SECTOR ON SECTOR.CODIGO = AREAS.SECTOR  

				-- DETALLES DE CADA OBJETIVO
				LEFT JOIN ZL.ZL.OBJEINDIVALOBD ON ZL.ZL.OBJEINDIVALOBD.CODIGO = ZL.ZL.OBJEINDIVAL.CODIGO
				LEFT JOIN ZL.ZL.OBJET AS OBJETIVO ON OBJETIVO.COD = ZL.ZL.OBJEINDIVALOBD.CODOBJE 
				LEFT JOIN ZL.ZL.OBJETDET AS ESCOBJETIVO ON ESCOBJETIVO.NUMERO = OBJETIVO.COD
					AND ZL.ZL.OBJEINDIVALOBD.VALOR >= ESCOBJETIVO.DESDE
					AND ZL.ZL.OBJEINDIVALOBD.VALOR <= ESCOBJETIVO.HASTA
				LEFT JOIN ZL.ZL.TIPOOBJE AS TIPOS ON TIPOS.CODIGO = OBJETIVO.TIPO 

				--OBJETIVOS POR PUESTO
				INNER JOIN ZL.ZL.OBJEXPTO AS OBJINDIVIDUALES ON OBJINDIVIDUALES.PUESTO = PUESTO.COD
					AND @FECHA BETWEEN OBJINDIVIDUALES.DESDE AND OBJINDIVIDUALES.HASTA
				INNER JOIN ZL.ZL.OBJEXPTODET AS OBJETIVOS ON OBJETIVOS.CODIGO = OBJINDIVIDUALES.CODIGO
				INNER JOIN (SELECT
								SPT.CODIGO
								, SUM(SPT.PESOTIPO) AS SUMAPESOS
							FROM
								(SELECT 
									DISTINCT
									ZL.ZL.OBJEXPTODET.CODIGO
									, ZL.ZL.OBJEXPTODET.TIPOOBJE 
									, ZL.ZL.OBJEXPTODET.PESOTIPO
								FROM 
									ZL.ZL.OBJEXPTODET
									INNER JOIN (SELECT DISTINCT PESOTIPO, TIPOOBJE, CODIGO FROM ZL.ZL.OBJEXPTODET GROUP BY TIPOOBJE, CODIGO, PESOTIPO) AS PESOSTIPOSDETALLE ON PESOSTIPOSDETALLE.CODIGO = ZL.ZL.OBJEXPTODET.CODIGO)
									AS SPT
							GROUP BY
								SPT.CODIGO) AS SUMPESOSTIPOS ON SUMPESOSTIPOS.CODIGO = OBJINDIVIDUALES.CODIGO
	END
	--CREAMOS UN CURSOR PARA RECORRER Y AGREGAR Y MODIFICAR DATOS COMO PESO Y RESULTADO DE LOS OBJETOS SQL
	DECLARE DETALLE CURSOR FOR SELECT ID, ROBSQLOBJE, EscObjeDesde, EscObjeHasta, ApliEsc FROM @DETALLE;
	OPEN DETALLE;
	FETCH NEXT FROM DETALLE INTO @ID, @ROBSQLOBJE, @EscObjeDesde, @EscObjeHasta, @APLICAESCALA;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @APLICAESCALA = 1
		BEGIN
			IF @ROBSQLOBJE >= @EscObjeDesde AND @ROBSQLOBJE <= @EscObjeHasta
			BEGIN
				UPDATE @DETALLE SET EscObjeValor = (SELECT EscObjeValor FROM @DETALLE WHERE ID = @ID) WHERE ID = @ID
			END
			ELSE
			BEGIN
				UPDATE @DETALLE SET EscObjeValor = 0 WHERE ID = @ID
			END
		END
		ELSE
		BEGIN
			UPDATE @DETALLE SET 
				EscObjeValor = @ROBSQLOBJE
				, EscObjeDesde = 0
				, EscObjeHasta = 99.9999
			WHERE 
				ID = @ID
		END 
		UPDATE @DETALLE SET PesoRelObjetivo = (SELECT EscObjeValor * PesoObjetivo FROM @DETALLE WHERE ID = @ID) WHERE ID = @ID
		UPDATE @DETALLE SET ValorFinalObjetivo = (SELECT PesoRelObjetivo * PesoTipoObjetivo FROM @DETALLE WHERE ID = @ID) WHERE ID = @ID

		SET @ID = NULL;
		SET @ROBSQLOBJE = 0.00;
		FETCH NEXT FROM DETALLE INTO @ID, @ROBSQLOBJE, @EscObjeDesde, @EscObjeHasta, @APLICAESCALA;
	END
	
	SELECT
		* 
	FROM 
		@DETALLE		
	WHERE 
		CodTipoObjetivo IS NOT NULL
		AND (EscObjeDesde <= ROBSQLOBJE AND EscObjeHasta >= ROBSQLOBJE)
		;

	CLOSE DETALLE;
	DEALLOCATE DETALLE;
		
END



GO


