use zl
go

DECLARE 
	@DELAYLIBRE INT
	, @DELAYEXCLU INT
	, @ENVIAR BIT
	, @FECHAPARALIBRE DATETIME
	, @FECHAPARAEXCLU DATETIME;
DECLARE
	@ESTADO AS VARCHAR(25)
	, @LIBERADO AS DATETIME
	, @VERSION AS VARCHAR(13)
	, @DESCARGA AS VARCHAR(MAX)
	, @CODCLIVERSION AS VARCHAR(5)
	, @CLIENTEVERSION AS VARCHAR(100)
	, @CODCLISERIE AS VARCHAR(5)
	, @CLIENTESERIR AS VARCHAR(100)
	, @MAIL AS VARCHAR(MAX)
	, @PRODUCTO AS VARCHAR(MAX)
	, @HISTORIA AS VARCHAR(MAX)
	, @HISTORIAS AS VARCHAR(MAX)
	, @MAILANTERIOR AS VARCHAR(MAX)
	, @ASUNTO AS VARCHAR(MAX)
	, @nromail AS INT;
	
SET @DELAYLIBRE = 30;--SOLO PARA SETEAR UN VALOR VA POR PARAMETRO
SET @DELAYEXCLU = 30;--SOLO PARA SETEAR UN VALOR VA POR PARAMETRO
SET @ENVIAR     = 1; --VERDADERO, SE ENVIAN LOS MAILS, VA POR PARAMETRO

SET @FECHAPARALIBRE = CONVERT(DATETIME, CONVERT(VARCHAR(10), DATEADD(DAY, @DELAYLIBRE * -1, GETDATE()), 102)); --CALCULAMOS EL DIA A PROCESAR Y LE QUITAMOS LA HORA

SET @FECHAPARAEXCLU = CONVERT(DATETIME, CONVERT(VARCHAR(10), DATEADD(DAY, @DELAYEXCLU * -1, GETDATE()), 102)); --CALCULAMOS EL DIA A PROCESAR Y LE QUITAMOS LA HORA

IF @ENVIAR = 1
BEGIN
	DECLARE ENVIOS CURSOR FOR
	SELECT 
		* 
	FROM (	SELECT
				'LIBRE' AS [ESTADO]
				, ASIGNACIONES.CMPFECINI AS [LIBERADO]
				, ISNULL(ASIGNACIONES.CVERSION, '') AS [VERSION]
				, LIBERACIONES.URLDESC AS [DESCARGA]
				, CLIENTESVERSIONES.CCODCLI AS [CODCLIVERSION]
				, CLIENTESVERSIONES.DESCRIP AS [CLIENTEVERSION]
				, CLIENTES.CMPCODIGO AS [CODCLISERIE]
				, CLIENTES.CMPNOMBRE AS [CLIENTESERIR]
				, ISNULL(MAILS.DIREC, '') AS [MAIL]
				, ISNULL(PRODUCTO.DESCR, '') AS [PRODUCTO]
				, HISTORIAS.NOMBRE AS [HISTORIA]
			FROM
				ZL.ASIGESTVER AS ASIGNACIONES
				INNER JOIN ZL.LIBERAVER AS LIBERACIONES ON LIBERACIONES.CCOD = ASIGNACIONES.LIBERACION
				LEFT JOIN  ZL.DETCLIVER AS CLIENTESVERSIONES ON CLIENTESVERSIONES.LIBERACION = LIBERACIONES.CCOD
					AND CLIENTESVERSIONES.CCODCLI <> '00001' --ZOOLOGIC
					AND CLIENTESVERSIONES.CCODCLI IS NOT NULL
				LEFT JOIN  ZL.DETSERVER AS CLIENTESSERIES ON CLIENTESSERIES.LIBERACION = LIBERACIONES.CCOD
					AND CLIENTESSERIES.CMPCODIGO <> '00001' --ZOOLOGIC
					AND CLIENTESSERIES.CMPCODIGO IS NOT NULL
				LEFT JOIN ZL.CLIENTES AS CLIENTES ON CLIENTES.CMPCODIGO = CLIENTESVERSIONES.CCODCLI
					OR CLIENTES.CMPCODIGO = CLIENTESSERIES.CMPCODIGO
				LEFT JOIN ZL.CONTACT AS CONTACTO ON CONTACTO.CCLIENTE = CLIENTES.CMPCODIGO
				LEFT JOIN ZL.CMAILS AS MAILS ON MAILS.CODMAIL = CONTACTO.CODIGO
				LEFT JOIN ZL.PRODZL AS PRODUCTO ON PRODUCTO.CCOD = LIBERACIONES.CPCOD
				LEFT JOIN ZL.IDASGVEFUYBUG AS ASIGHIST ON ASIGHIST.CVCOD = LIBERACIONES.CVERSION
				LEFT JOIN ZL.DETIDASGVEHISPU AS HISTORIAS ON HISTORIAS.CODINT = ASIGHIST.CODIN
			WHERE
				ASIGNACIONES.CMPFECINI >= @FECHAPARALIBRE --QUITAR PARA PUBLICAR DEBE SER = Y NO >=
				AND ASIGNACIONES.ESTADO = 2
				AND MAILS.DIREC IS NOT NULL
		UNION
			SELECT
				'EXCLUSIVA'
				, ASIGNACIONES.CMPFECINI
				, ISNULL(ASIGNACIONES.CVERSION, '')
				, LIBERACIONES.URLDESC
				, CLIENTESVERSIONES.CCODCLI
				, CLIENTESVERSIONES.DESCRIP
				, CLIENTES.CMPCODIGO
				, CLIENTES.CMPNOMBRE
				, ISNULL(MAILS.DIREC, '')
				, ISNULL(PRODUCTO.DESCR, '') 
				, HISTORIAS.NOMBRE
			FROM
				ZL.ASIGESTVER AS ASIGNACIONES
				INNER JOIN ZL.LIBERAVER AS LIBERACIONES ON LIBERACIONES.CCOD = ASIGNACIONES.LIBERACION
				LEFT JOIN  ZL.DETCLIVER AS CLIENTESVERSIONES ON CLIENTESVERSIONES.LIBERACION = LIBERACIONES.CCOD
					AND CLIENTESVERSIONES.CCODCLI <> '00001' --ZOOLOGIC
					AND CLIENTESVERSIONES.CCODCLI IS NOT NULL
				LEFT JOIN  ZL.DETSERVER AS CLIENTESSERIES ON CLIENTESSERIES.LIBERACION = LIBERACIONES.CCOD
					AND CLIENTESSERIES.CMPCODIGO <> '00001' --ZOOLOGIC
					AND CLIENTESSERIES.CMPCODIGO IS NOT NULL
				LEFT JOIN ZL.CLIENTES AS CLIENTES ON CLIENTES.CMPCODIGO = CLIENTESVERSIONES.CCODCLI
					OR CLIENTES.CMPCODIGO = CLIENTESSERIES.CMPCODIGO
				LEFT JOIN ZL.CONTACT AS CONTACTO ON CONTACTO.CCLIENTE = CLIENTES.CMPCODIGO
				LEFT JOIN ZL.CMAILS AS MAILS ON MAILS.CODMAIL = CONTACTO.CODIGO
				LEFT JOIN ZL.PRODZL AS PRODUCTO ON PRODUCTO.CCOD = LIBERACIONES.CPCOD
				LEFT JOIN ZL.IDASGVEFUYBUG AS ASIGHIST ON ASIGHIST.CVCOD = LIBERACIONES.CVERSION
				LEFT JOIN ZL.DETIDASGVEHISPU AS HISTORIAS ON HISTORIAS.CODINT = ASIGHIST.CODIN
			WHERE
				ASIGNACIONES.CMPFECINI >= @FECHAPARAEXCLU --QUITAR PARA PUBLICAR DEBE SER = Y NO >=
				AND ASIGNACIONES.ESTADO = 1
				AND MAILS.DIREC IS NOT NULL
			GROUP BY
				MAILS.DIREC
				, ASIGNACIONES.CMPFECINI
				, ASIGNACIONES.CVERSION
				, LIBERACIONES.URLDESC
				, CLIENTESVERSIONES.CCODCLI
				, CLIENTESVERSIONES.DESCRIP
				, CLIENTES.CMPCODIGO
				, CLIENTES.CMPNOMBRE
				, PRODUCTO.DESCR 
				, HISTORIAS.CODIGO
				, HISTORIAS.NOMBRE) AS ENVIOS
			ORDER BY 
				ENVIOS.CODCLISERIE
				, ENVIOS.MAIL;
	
	OPEN ENVIOS;
	FETCH NEXT FROM ENVIOS INTO
		@ESTADO
		, @LIBERADO
		, @VERSION
		, @DESCARGA
		, @CODCLIVERSION
		, @CLIENTEVERSION
		, @CODCLISERIE
		, @CLIENTESERIR
		, @MAIL
		, @PRODUCTO
		, @HISTORIA;
	SET @MAILANTERIOR = '';
	SET @HISTORIAS = '<div><h3 style="font-family: Verdana, Arial, sans-serif; font-size: 1.2em; color:#000000;">Nueva Versi&oacute;n '+@VERSION+'</h3></div>';
	SET @HISTORIAS = @HISTORIAS+'<div style="font-family: Verdana, Arial, sans-serif; font-size: 0.8em; color:#404040;"><p>';
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @MAIL = @MAILANTERIOR
			BEGIN
				SET @HISTORIAS = @HISTORIAS+'</p><p>'+@HISTORIA;
			END
		ELSE
			BEGIN
				SET @HISTORIAS = @HISTORIAS+'</p></div>'; --CERRAMOS EL HTML DEL BODY
				SET @ASUNTO = 'Nueva versión de '+RTRIM(LTRIM(@PRODUCTO));
				SELECT @MAILANTERIOR, @ASUNTO, @HISTORIAS;
				--ENVIAMOS EL MAIL
				IF @MAILANTERIOR <> '' OR @MAILANTERIOR IS NOT NULL
				BEGIN
					EXEC msdb.dbo.sp_send_dbmail
					@profile_name = 'ZL Avisos'
					--,@recipients = @MAILANTERIOR
					,@recipients = 'hcorrea@zoologic.com.ar'
					,@copy_recipients = '' --'sdisanzo@zoologic.com.ar' 
					,@body = @HISTORIAS  
					,@subject = @ASUNTO 
					,@body_format = 'HTML' 
					,@mailitem_id = @nromail OUTPUT ;
				END
				--EMPEZAMOS DE NUEVO
				SET @HISTORIAS = '<div><h3 style="font-family: Verdana, Arial, sans-serif; font-size: 1.2em; color:#000000;">Nueva Versi&oacute;n '+@VERSION+'</h3></div>';
				SET @HISTORIAS = @HISTORIAS+'<div style="font-family: Verdana, Arial, sans-serif; font-size: 0.8em; color:#404040;"><p>'+@HISTORIA;
			END
		SET @MAILANTERIOR = @MAIL;
		FETCH NEXT FROM ENVIOS INTO
			@ESTADO
			, @LIBERADO
			, @VERSION
			, @DESCARGA
			, @CODCLIVERSION
			, @CLIENTEVERSION
			, @CODCLISERIE
			, @CLIENTESERIR
			, @MAIL
			, @PRODUCTO
			, @HISTORIA;
	END

	CLOSE ENVIOS;
	DEALLOCATE ENVIOS;
END
GO
