use ZL

SELECT 
	ZL.ASESRZMAIL.CLIENTE
	,ZL.ASESRZMAIL.CONTACTO
	,ZL.ASESRZMAIL.EMAIL
	,ZL.CONTACTOS.Apellido
 FROM ZL.ASESRZMAIL 
	inner join zl.ACCMAIL on ZL.ACCMAIL.CCOD = ZL.ASESRZMAIL.ACCMAIL and ZL.ACCMAIL.DESCR like ('%campus virtual%')
	LEFT JOIN ZL.CONTACTOS on ZL.CONTACTOS.Mail = ZL.ASESRZMAIL.EMAIL 
where
	ZL.ASESRZMAIL.ACCION < 2
GROUP BY 
	ZL.ASESRZMAIL.CONTACTO
	,ZL.ASESRZMAIL.CLIENTE
	,ZL.ASESRZMAIL.EMAIL
	,ZL.CONTACTOS.Apellido

