USE [ZL]
GO

/****** Object:  StoredProcedure [dbo].[stp_MigracionFichajes]    Script Date: 08/12/2013 09:49:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stp_MigracionFichajes]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[stp_MigracionFichajes]
GO

USE [ZL]
GO

/****** Object:  StoredProcedure [dbo].[stp_MigracionFichajes]    Script Date: 08/12/2013 09:49:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[stp_MigracionFichajes]

AS
BEGIN
      SET NOCOUNT ON;

      
      DECLARE @FECHAULTIMAMIGRACION DATETIME
      SET @FECHAULTIMAMIGRACION = ( SELECT top 1 max( FCHREG ) as FCHREG from ZL.ZNFICHAJE WHERE ESTCONEX = 1 )
      IF @FECHAULTIMAMIGRACION IS NULL
      BEGIN
		SET @FECHAULTIMAMIGRACION = 0;
      END

      -- Elimino el ultimo evento por si existe uno o mas con la misma Fecha/Hora de registro
      DELETE FROM [ZL].[ZNFICHAJE] WHERE [FCHREG] >= @FECHAULTIMAMIGRACION AND ESTCONEX = 1
      -- select *  from [ZL].[ZNFICHAJE] where [FCHREG] >= @FECHAULTIMAMIGRACION

      INSERT INTO [ZL].[ZNFICHAJE] (
            [BDALTAFW]
            , [BDMODIFW]
            , [CAPENOM]
            , [COD]
            , [ESTCONEX]
            , [ESTTRANS]
            , [FALTAFW]
            , [FCHREG]
            , [FECEXPO]
            , [FECIMPO]
            , [FECTRANS]
            , [FMODIFW]
            , [HALTAFW]
            , [HMODIFW]
            , [HORAEXPO]
            , [HORAIMPO]
            , [LEGAJO] --ESTE CAMPO ES VARCHAR(4)
            , [OBS]
            , [PCONTROL]
            , [SALTAFW]
            , [SMODIFW]
            , [UALTAFW]
            , [UMODIFW]
            , [VALTAFW]
            , [VMODIFW]
            , [HORAREG]
            , [CODZNUBE]
            ) 
      SELECT 
            'ZL' [BDALTAFW]
            , 'ZL' [BDMODIFW]
            , CONVERT(VARCHAR(80), LTRIM(RTRIM([PROFILES].[LASTNAME]))+' '+LTRIM(RTRIM([PROFILES].[SURNAME]))) [CAPENOM]
            , CONVERT(UNIQUEIDENTIFIER, [EVENTS].ID) [COD]
            , [EVENTS].[CONNECTIONSTATUS] [ESTCONEX]
            , CONVERT(VARCHAR(20), [CONNECTIONSTATUS].[CONNECTIONSTATUS]) [ESTRANS]
            , GETDATE() [FALTAFW]
            , [EVENTS].[DATE] [FCHREG]
            , GETDATE() [FECEXPO]
            , GETDATE() [FECIMPO]
            , GETDATE() [FECTRANS]
            , GETDATE() [FMODIFW]
            , CONVERT(VARCHAR(8), GETDATE(), 108) [HALTAFW]
            , CONVERT(VARCHAR(8), GETDATE(), 108) [HMODIFW]
            , CONVERT(VARCHAR(8), GETDATE(), 108) [HORAEXPO]
            , CONVERT(VARCHAR(8), GETDATE(), 108) [HORAIMPO]
            , CONVERT(VARCHAR(4), LTRIM(RTRIM([PROFILES].[IDPROFILE]))) [LEGAJO]
            , CONVERT(TEXT, 'Migración ZNube->DataWeb / Automático desde SP') [OBS]
            , [ZNPCONTROL].[COD] AS [PCONTROL]
            , 'ZL' [SALTAFW]
            , 'ZL' [SMODIFW]
            , 'ZL' [UALTAFW]
            , 'ZL' [UMODIFW]
            , 'ZL' [VALTAFW]
            , 'ZL' [VMODIFW]
            , CONVERT(VARCHAR(8), [EVENTS].[DATE], 108) [HORAREG]
            , [EVENTS].[APPLICATIONVALIDATORID]
      FROM 
            [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[EVENT] AS [EVENTS]
            LEFT JOIN [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[Profile] AS [PROFILES] ON [PROFILES].[Id] = [EVENTS].[IDPROFILE]
            LEFT JOIN [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[ConnectionStatus] AS [CONNECTIONSTATUS] ON
                  [CONNECTIONSTATUS].[ID] = [EVENTS].[CONNECTIONSTATUS]
            LEFT JOIN [zNube_Hub01].[D1ADA87A-240B-46D6-966E-5D493172F723_TM].[DBO].[APPLICATIONVALIDATOR] AS [PCONTROL] ON [PCONTROL].[ID] = [EVENTS].[APPLICATIONVALIDATORID]
            LEFT JOIN [ZL].[ZNPCONTROL] ON [ZL].[ZNPCONTROL].[CODZNUBE] = [EVENTS].[APPLICATIONVALIDATORID]
      WHERE
            [EVENTS].[DATE] >=  @FECHAULTIMAMIGRACION 
            AND [EVENTS].[CONNECTIONSTATUS] = 1
      ORDER BY
            [EVENTS].[DATE];
      
	IF	CONVERT(DATETIME, CONVERT(VARCHAR(8), GETDATE(), 8), 120) >= CONVERT(DATETIME, CONVERT(VARCHAR(8), '00:00:00', 8), 120)
		AND CONVERT(DATETIME, CONVERT(VARCHAR(8), GETDATE(), 8), 120) <= CONVERT(DATETIME, CONVERT(VARCHAR(8), '00:05:00', 8), 120)
		BEGIN
			-- NOS ASEGURAMOS LA MIGRACION DE LOS 'DIFERIDOS', 'DESCONECTADOS' Y 'EN NOMBRE DE' DE LOS ULTIMOS 30 DIAS
			-- CADA NOCHE EN LA CORRIDA DE LAS 00:00 HORAS
			SET @FECHAULTIMAMIGRACION = @FECHAULTIMAMIGRACION - 30;
		END
	ELSE
		BEGIN
			-- NOS ASEGURAMOS LA MIGRACION DE LOS 'DIFERIDOS', 'DESCONECTADOS' Y 'EN NOMBRE DE' DE LAS ULTIMAS 24 HORAS
			-- EN LAS CORRIDAS DE CADA 15 MINUTOS
			SET @FECHAULTIMAMIGRACION = @FECHAULTIMAMIGRACION - 1;
		END

	DELETE FROM [ZL].[ZNFICHAJE] WHERE [FCHREG] >= @FECHAULTIMAMIGRACION AND ESTCONEX <> 1;

	INSERT INTO [ZL].[ZNFICHAJE] (
		[BDALTAFW]
		, [BDMODIFW]
		, [CAPENOM]
		, [COD]
		, [ESTCONEX]
		, [ESTTRANS]
		, [FALTAFW]
		, [FCHREG]
		, [FECEXPO]
		, [FECIMPO]
		, [FECTRANS]
		, [FMODIFW]
		, [HALTAFW]
		, [HMODIFW]
		, [HORAEXPO]
		, [HORAIMPO]
		, [LEGAJO] --ESTE CAMPO ES VARCHAR(4)
		, [OBS]
		, [PCONTROL]
		, [SALTAFW]
		, [SMODIFW]
		, [UALTAFW]
		, [UMODIFW]
		, [VALTAFW]
		, [VMODIFW]
		, [HORAREG]
		, [CODZNUBE]
		) 
	SELECT 
		'ZL' [BDALTAFW]
		, 'ZL' [BDMODIFW]
		, CONVERT(VARCHAR(80), LTRIM(RTRIM([PROFILES].[LASTNAME]))+' '+LTRIM(RTRIM([PROFILES].[SURNAME]))) [CAPENOM]
		, CONVERT(UNIQUEIDENTIFIER, [EVENTS].ID) [COD]
		, [EVENTS].[CONNECTIONSTATUS] [ESTCONEX]
		, CONVERT(VARCHAR(20), [CONNECTIONSTATUS].[CONNECTIONSTATUS]) [ESTRANS]
		, GETDATE() [FALTAFW]
		, [EVENTS].[DATE] [FCHREG]
		, GETDATE() [FECEXPO]
		, GETDATE() [FECIMPO]
		, GETDATE() [FECTRANS]
		, GETDATE() [FMODIFW]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HALTAFW]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HMODIFW]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HORAEXPO]
		, CONVERT(VARCHAR(8), GETDATE(), 108) [HORAIMPO]
		, CONVERT(VARCHAR(4), LTRIM(RTRIM([PROFILES].[IDPROFILE]))) [LEGAJO]
		, CONVERT(TEXT, 'Migración ZNube->DataWeb / Automático desde SP') [OBS]
		, [ZNPCONTROL].[COD] AS [PCONTROL]
		, 'ZL' [SALTAFW]
		, 'ZL' [SMODIFW]
		, 'ZL' [UALTAFW]
		, 'ZL' [UMODIFW]
		, 'ZL' [VALTAFW]
		, 'ZL' [VMODIFW]
		, CONVERT(VARCHAR(8), [EVENTS].[DATE], 108) [HORAREG]
		, [EVENTS].[APPLICATIONVALIDATORID]
	FROM 
		[zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[EVENT] AS [EVENTS]
		LEFT JOIN [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[Profile] AS [PROFILES] ON [PROFILES].[Id] = [EVENTS].[IDPROFILE]
		LEFT JOIN [zNube_Hub01].[d1ada87a-240b-46d6-966e-5d493172f723_TM].[dbo].[ConnectionStatus] AS [CONNECTIONSTATUS] ON
			  [CONNECTIONSTATUS].[ID] = [EVENTS].[CONNECTIONSTATUS]
		LEFT JOIN [zNube_Hub01].[D1ADA87A-240B-46D6-966E-5D493172F723_TM].[DBO].[APPLICATIONVALIDATOR] AS [PCONTROL] ON [PCONTROL].[ID] = [EVENTS].[APPLICATIONVALIDATORID]
		LEFT JOIN [ZL].[ZNPCONTROL] ON [ZL].[ZNPCONTROL].[CODZNUBE] = [EVENTS].[APPLICATIONVALIDATORID]
	WHERE
		[EVENTS].[DATE] >=  @FECHAULTIMAMIGRACION 
		AND [EVENTS].[CONNECTIONSTATUS] <> 1
	ORDER BY
		[EVENTS].[DATE];

	--AGREGAMOS INFORMACION COMPLEMENTARIA A LA FICHADA
	--EXEC [dbo].[stp_MigracionFichajes_INFORMACION_COMPLEMENTARIA] @FECHAULTIMAMIGRACION 
      
END

GO


