IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[ZL].[MAILUSUARIOCAMPUSVIRTUAL]'))
DROP TRIGGER [ZL].[MAILUSUARIOCAMPUSVIRTUAL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		DANIEL CORREA
-- CREATE DATE: 03/01/2013
-- DESCRIPTION:	TRIGGER QUE DISPARA UN MAIL PARA INSERT CUANDO SE ASIGNA
--              USUARIO DE CAMPUS VIRTUAL COMO ACCIÓN DE MAIL
-- MOFIFICADO: 18/02/2013 - DANIEL CORREA
-- =============================================
CREATE TRIGGER [ZL].[MAILUSUARIOCAMPUSVIRTUAL] 
   ON  [ZL].[ASESRZMAIL] 
   AFTER INSERT
AS 
BEGIN

	SET NOCOUNT ON;

  DECLARE @TABLE VARCHAR(100)

  DECLARE @REGISTRADOPOR VARCHAR(50)
  DECLARE @NUMERO INT
  DECLARE @ACCMAIL INT
  DECLARE @ALTA INT

	SELECT 
		@ACCMAIL = I.ACCMAIL
		,@ALTA = I.ACCION
	FROM 
		INSERTED I;
	  
	IF @ACCMAIL = 8 AND @ALTA = 1
		BEGIN

      SET @TABLE = 'ASESRZMAIL' 
      SET @REGISTRADOPOR = (SELECT LTRIM(RTRIM(I.REGPOR)) FROM INSERTED I) 
      SET @NUMERO = (SELECT I.NUMERO FROM INSERTED I)

      EXEC ZL.INSERTARLOGAVISOS 
        @REGPOR= @REGISTRADOPOR,
        @TABLA =@TABLE,
        @NROCOMPROB =@NUMERO;
		END
END

GO
