USE [ZL]
GO

/****** Object:  View [ZL].[IyDHorasDesarrollo]  Script Date: 06/14/2013 16:18:21 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[ZL].[IyDHorasDesarrollo]'))
DROP VIEW [ZL].[IyDHorasDesarrollo]
GO

USE [ZL]
GO

/****** Object:  View [ZL].[IyDHorasDesarrollo]    Script Date: 06/14/2013 16:18:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [ZL].[IyDHorasDesarrollo] AS

/*
Fecha: 14/06/2013
Autor: HECTOR DANIEL CORREA
*/

SELECT
	LTRIM(RTRIM([PRODUCTOS].[DESCR])) AS [Producto]
	, [FUNCIONALIDADES].[VERSION] [Versión]
	, 'Fun' AS [Tipo]
	, CASE ZL.DETIYDHORAS.FUN
		WHEN NULL THEN HISTORIAS.FUNC
		WHEN 0 THEN HISTORIAS.FUNC
		ELSE ZL.DETIYDHORAS.FUN
	END AS [Número]
	, ZL.DETIYDHORAS.CODIGO [CompZL]
	, ZL.DETIYDHORAS.HORAS [Horas]
	, CONVERT(VARCHAR(10), ZL.DETIYDHORAS.FECHA, 103) [Fecha]
	, CONVERT(VARCHAR(10), [VERSIONES].[ESTADO FECHA], 103) AS [Fecha Publicación]
	, REPLACE(ZL.DETIYDHORAS.HISDES, ',', ' ') [Descripción]
FROM 
	ZL.DETIYDHORAS
	LEFT JOIN ZL.HPIVOT AS HISTORIAS ON HISTORIAS.CODIGO = ZL.DETIYDHORAS.HISTID
	
	LEFT JOIN [ZL].[IYDFUNCIONALIDADVERSION] AS [FUNCIONALIDADES] ON [FUNCIONALIDADES].FUNCIONALIDAD = ZL.DETIYDHORAS.FUN 
	LEFT JOIN ZL.PRODZL AS [PRODUCTOS] ON [PRODUCTOS].CCOD = [FUNCIONALIDADES].[PRODUCTO]
	INNER JOIN [ZL].[IYDPUBLICACIONVERSIONES] AS [VERSIONES] ON [VERSIONES].[CVERSION] = [FUNCIONALIDADES].[VERSION]
	
WHERE
	ZL.DETIYDHORAS.CLASI = 33
	AND ZL.DETIYDHORAS.FUN IS NOT NULL
	AND ZL.DETIYDHORAS.FUN <> 0

UNION ALL

SELECT
	LTRIM(RTRIM([PRODUCTOS].[DESCR])) AS [Producto]
	, [BUGS].[VERSION] [Versión]
	, 'Bug' AS [Tipo]
	, CASE ZL.DETIYDHORAS.BUG
		WHEN NULL THEN HISTORIAS.BUG
		WHEN 0 THEN HISTORIAS.BUG
		ELSE ZL.DETIYDHORAS.BUG
	END AS [Número]
	, ZL.DETIYDHORAS.CODIGO [Comp]
	, ZL.DETIYDHORAS.HORAS [Horas]
	, CONVERT(VARCHAR(10), ZL.DETIYDHORAS.FECHA, 103) [Fecha]
	, CONVERT(VARCHAR(10), [VERSIONES].[ESTADO FECHA], 103) AS [Fecha Publicación]
	, REPLACE(ZL.DETIYDHORAS.HISDES, ',', ' ') [Descripción]
FROM 
	ZL.DETIYDHORAS
	LEFT JOIN ZL.HPIVOT AS HISTORIAS ON HISTORIAS.CODIGO = ZL.DETIYDHORAS.HISTID

	LEFT JOIN [ZL].[IyDBugVersion] AS [BUGS] ON [BUGS].BUG = ZL.DETIYDHORAS.BUG
	LEFT JOIN ZL.PRODZL AS [PRODUCTOS] ON [PRODUCTOS].CCOD = [BUGS].[PRODUCTO]
	INNER JOIN [ZL].[IYDPUBLICACIONVERSIONES] AS [VERSIONES] ON [VERSIONES].[CVERSION] = [BUGS].[VERSION]

WHERE
	ZL.DETIYDHORAS.CLASI = 33
	AND ZL.DETIYDHORAS.BUG IS NOT NULL
	AND ZL.DETIYDHORAS.BUG <> 0
GO


