#DEFINE  NO_ACOMODAR 0

#DEFINE  ORDEN_IZQ_ALINEADO 1
#DEFINE  ORDEN_IZQ_PEGADO 2
#DEFINE  ORDEN_IZQ_ESPACIADO 3
#DEFINE  ORDEN_IZQ_SANGRADO 4
#DEFINE  ORDEN_DER_PEGADO 5
#DEFINE  ORDEN_DER_MITAD_COLUMNA 6
#DEFINE  ORDEN_DER_NO_ACOMODAR 7
#DEFINE  ORDEN_IZQ_MITAD_COLUMNA 8
#DEFINE  ORDEN_DER_ALINEADO 9

#DEFINE  ORDEN_SUP_ETIQUETA_ALINEADA 1
#DEFINE  ORDEN_SUP_LINEA_CENTRADA 2
#DEFINE  ORDEN_SUP_CENTRADO 3

#DEFINE  TIPO_SUBGRUPO_MEDIANO 1
#DEFINE  TIPO_SUBGRUPO_CHICO 2
#DEFINE  TIPO_SUBGRUPO_GRANDE 3