IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Funciones].[ObtenerLetraComprobantesYGruposDeCaja]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Funciones].[ObtenerLetraComprobantesYGruposDeCaja];
GO;

CREATE FUNCTION [Funciones].[ObtenerLetraComprobantesYGruposDeCaja]
( @TipoDeComprobante varchar(2) )
RETURNS char (1)
AS
BEGIN
declare @retorno char (1)
set @retorno = 
case @TipoDeComprobante
	 when '00' then 'A'
	 when '01' then 'B'
	 when '23' then 'C'
	 when '02' then 'A'
	 when '03' then 'B'
	 when '24' then 'C'
	 when '04' then 'A'
	 when '05' then 'B'
	 when '25' then 'C'
	 when '07' then 'A'
	 when '08' then 'B'
	 when '26' then 'C'
	 when '40' then ''
	 when '09' then 'A'
	 when '10' then 'B'
	 when '27' then 'C'
	 when '41' then ''
	 when '11' then 'A'
	 when '12' then 'B'
	 when '28' then 'C'
	 when '50' then 'A'
	 when '51' then 'B'
	 when '52' then 'C'
	 when '70' then 'M'
	 when '42' then ''
	 when '44' then 'E'
	 when '63' then 'A'
	 when '64' then 'B'
	 when '65' then 'C'
	 when '71' then 'M'
	 when '45' then 'E'
	 when '66' then 'A'
	 when '67' then 'B'
	 when '68' then 'C'
	 when '72' then 'M'
	 when '43' then ''
	 when '46' then 'E'
	 when '53' then 'A'
	 when '54' then 'B'
	 when '55' then 'C'
	 when '56' then 'A'
	 when '57' then 'B'
	 when '58' then 'C'
	 when '59' then 'A'
	 when '60' then 'B'
	 when '61' then 'C'
	 when '76' then 'E'
	 when '77' then 'E'
	 when '78' then 'E'
	 when '79' then 'E'
	 when '80' then 'E'
	 when '81' then 'E'
	 when '13' then 'X'
	 when '06' then ''
	 when '62' then 'X'
	 when '69' then 'X'
	 when '82' then 'X'
	 when '99' then ''
	 when '96' then ''
	 when '97' then 'X'
	 when '31' then 'M'
	 when '32' then 'M'
	 when '33' then 'M'
	 when '34' then 'M'
	 when '35' then 'M'
	 when '36' then 'M'
	 when '37' then 'M'
	 when '38' then 'M'
	 when '39' then 'M'
	else ''
end
return @retorno
END