define class DetalleModificacionDeCostosDeProduccionModcostos as din_DetalleModificacionDeCostosDeProduccionModcostos of din_DetalleModificacionDeCostosDeProduccionModcostos.prg

	#if .f.
		local this as DetalleModificacionDeCostosDeProduccionModcostos of DetalleModificacionDeCostosDeProduccionModcostos.prg
	#endif

enddefine
