IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Funciones].[ObtenerTablaDeOrigenDelRegistroComprobantesYGruposDeCaja]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Funciones].[ObtenerTablaDeOrigenDelRegistroComprobantesYGruposDeCaja];
GO;

CREATE FUNCTION [Funciones].[ObtenerTablaDeOrigenDelRegistroComprobantesYGruposDeCaja]
( @TipoDeComprobante varchar(2) )
RETURNS varchar (50)
AS
BEGIN
declare @retorno varchar (50)
set @retorno = 
case @TipoDeComprobante
	 when '00' then 'COMPROBANTEV'
	 when '01' then 'COMPROBANTEV'
	 when '23' then 'COMPROBANTEV'
	 when '02' then 'COMPROBANTEV'
	 when '03' then 'COMPROBANTEV'
	 when '24' then 'COMPROBANTEV'
	 when '04' then 'COMPROBANTEV'
	 when '05' then 'COMPROBANTEV'
	 when '25' then 'COMPROBANTEV'
	 when '07' then 'COMPROBANTEV'
	 when '08' then 'COMPROBANTEV'
	 when '26' then 'COMPROBANTEV'
	 when '40' then 'COMPROBANTEV'
	 when '09' then 'COMPROBANTEV'
	 when '10' then 'COMPROBANTEV'
	 when '27' then 'COMPROBANTEV'
	 when '41' then 'COMPROBANTEV'
	 when '11' then 'COMPROBANTEV'
	 when '12' then 'COMPROBANTEV'
	 when '28' then 'COMPROBANTEV'
	 when '50' then 'FACCOMPRA'
	 when '51' then 'FACCOMPRA'
	 when '52' then 'FACCOMPRA'
	 when '70' then 'FACCOMPRA'
	 when '42' then 'FACCOMPRA'
	 when '44' then 'FACCOMPRA'
	 when '64' then 'NDCOMPRA'
	 when '65' then 'NDCOMPRA'
	 when '66' then 'NDCOMPRA'
	 when '71' then 'NDCOMPRA'
	 when '45' then 'NDCOMPRA'
	 when '67' then 'NCCOMPRA'
	 when '68' then 'NCCOMPRA'
	 when '69' then 'NCCOMPRA'
	 when '72' then 'NCCOMPRA'
	 when '43' then 'NCCOMPRA'
	 when '46' then 'NCCOMPRA'
	 when '53' then 'COMPROBANTEV'
	 when '54' then 'COMPROBANTEV'
	 when '55' then 'COMPROBANTEV'
	 when '56' then 'COMPROBANTEV'
	 when '57' then 'COMPROBANTEV'
	 when '58' then 'COMPROBANTEV'
	 when '59' then 'COMPROBANTEV'
	 when '60' then 'COMPROBANTEV'
	 when '61' then 'COMPROBANTEV'
	 when '83' then 'COMPROBANTEV'
	 when '84' then 'COMPROBANTEV'
	 when '85' then 'COMPROBANTEV'
	 when '86' then 'COMPROBANTEV'
	 when '87' then 'COMPROBANTEV'
	 when '88' then 'COMPROBANTEV'
	 when '89' then 'COMPROBANTEV'
	 when '90' then 'COMPROBANTEV'
	 when '91' then 'COMPROBANTEV'
	 when '76' then 'COMPROBANTEV'
	 when '77' then 'COMPROBANTEV'
	 when '78' then 'COMPROBANTEV'
	 when '79' then 'COMPROBANTEV'
	 when '80' then 'COMPROBANTEV'
	 when '81' then 'COMPROBANTEV'
	 when '13' then 'RECIBO'
	 when '14' then 'COMPROBANTEV'
	 when '15' then 'COMPROBANTEV'
	 when '16' then 'COMPROBANTEV'
	 when '17' then 'COMPROBANTEV'
	 when '18' then 'COMPROBANTEV'
	 when '20' then 'COMPROBANTEV'
	 when '21' then 'COMPROBANTEV'
	 when '06' then 'COMCAJ'
	 when '63' then 'ORDPAGO'
	 when '62' then 'PAGO'
	 when '82' then 'COMPPAGO'
	 when '99' then ''
	 when '96' then ''
	 when '97' then 'CANJECUPONES'
	 when '31' then 'COMPROBANTEV'
	 when '32' then 'COMPROBANTEV'
	 when '33' then 'COMPROBANTEV'
	 when '34' then 'COMPROBANTEV'
	 when '35' then 'COMPROBANTEV'
	 when '36' then 'COMPROBANTEV'
	 when '37' then 'COMPROBANTEV'
	 when '38' then 'COMPROBANTEV'
	 when '39' then 'COMPROBANTEV'
	else ''
end
return @retorno
END