IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Funciones].[ObtenerDescripcionDelComprobanteComprobantesYGruposDeCaja]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Funciones].[ObtenerDescripcionDelComprobanteComprobantesYGruposDeCaja];
GO;

CREATE FUNCTION [Funciones].[ObtenerDescripcionDelComprobanteComprobantesYGruposDeCaja]
( @TipoDeComprobante varchar(2) )
RETURNS varchar (50)
AS
BEGIN
declare @retorno varchar (50)
set @retorno = 
case @TipoDeComprobante
	 when '00' then 'Factura manual de venta'
	 when '01' then 'Factura manual de venta'
	 when '23' then 'Factura manual de venta'
	 when '02' then 'Nota de crédito manual de venta'
	 when '03' then 'Nota de crédito manual de venta'
	 when '24' then 'Nota de crédito manual de venta'
	 when '04' then 'Nota de débito manual de venta'
	 when '05' then 'Nota de débito manual de venta'
	 when '25' then 'Nota de débito manual de venta'
	 when '07' then 'Factura fiscal de venta'
	 when '08' then 'Factura fiscal de venta'
	 when '26' then 'Factura fiscal de venta'
	 when '40' then 'Factura fiscal de venta'
	 when '09' then 'Nota de crédito fiscal de venta'
	 when '10' then 'Nota de crédito fiscal de venta'
	 when '27' then 'Nota de crédito fiscal de venta'
	 when '41' then 'Nota de crédito fiscal de venta'
	 when '11' then 'Nota de débito fiscal de venta'
	 when '12' then 'Nota de débito fiscal de venta'
	 when '28' then 'Nota de débito fiscal de venta'
	 when '50' then 'Factura de compra'
	 when '51' then 'Factura de compra'
	 when '52' then 'Factura de compra'
	 when '70' then 'Factura de compra'
	 when '42' then 'Factura de compra'
	 when '44' then 'Factura de compra'
	 when '64' then 'Nota de débito de compra'
	 when '65' then 'Nota de débito de compra'
	 when '66' then 'Nota de débito de compra'
	 when '71' then 'Nota de débito de compra'
	 when '45' then 'Nota de débito de compra'
	 when '67' then 'Nota de crédito de compra'
	 when '68' then 'Nota de crédito de compra'
	 when '69' then 'Nota de crédito de compra'
	 when '72' then 'Nota de crédito de compra'
	 when '43' then 'Nota de crédito de compra'
	 when '46' then 'Nota de crédito de compra'
	 when '53' then 'Factura electrónica de venta'
	 when '54' then 'Factura electrónica de venta'
	 when '55' then 'Factura electrónica de venta'
	 when '56' then 'Nota de crédito electrónica de venta'
	 when '57' then 'Nota de crédito electrónica de venta'
	 when '58' then 'Nota de crédito electrónica de venta'
	 when '59' then 'Nota de débito electrónica de venta'
	 when '60' then 'Nota de débito electrónica de venta'
	 when '61' then 'Nota de débito electrónica de venta'
	 when '83' then 'Factura de crédito electrónica MiPyME de venta'
	 when '84' then 'Factura de crédito electrónica MiPyME de venta'
	 when '85' then 'Factura de crédito electrónica MiPyME de venta'
	 when '86' then 'Nota de crédito electrónica MiPyME de venta'
	 when '87' then 'Nota de crédito electrónica MiPyME de venta'
	 when '88' then 'Nota de crédito electrónica MiPyME de venta'
	 when '89' then 'Nota de débito electrónica MiPyME de venta'
	 when '90' then 'Nota de débito electrónica MiPyME de venta'
	 when '91' then 'Nota de débito electrónica MiPyME de venta'
	 when '76' then 'Factura electrónica exportación de venta'
	 when '77' then 'Nota de crédito electrónica exportación de venta'
	 when '78' then 'Nota de débito electrónica exportación de venta'
	 when '79' then 'Factura de exportación de venta'
	 when '80' then 'Nota de crédito de exportación de venta'
	 when '81' then 'Nota de débito de exportación de venta'
	 when '13' then 'Recibo'
	 when '14' then 'Boleta Fiscal'
	 when '15' then 'Factura'
	 when '16' then 'Notas de crédito'
	 when '17' then 'Boleta Preimpresa'
	 when '18' then 'Nota de crédito preimpresa'
	 when '20' then 'Factura Electrónica'
	 when '21' then 'Nota de Crédito'
	 when '06' then 'Comprobantes de caja'
	 when '63' then 'Orden de pago'
	 when '62' then 'Pago'
	 when '82' then 'Otros pagos'
	 when '99' then 'Apertura de Caja'
	 when '96' then 'Ajuste de Caja'
	 when '97' then 'Canje de valores'
	 when '31' then 'Factura manual de venta'
	 when '32' then 'Nota de crédito manual de venta'
	 when '33' then 'Nota de débito manual de venta'
	 when '34' then 'Factura electrónica de venta'
	 when '35' then 'Nota de crédito electrónica de venta'
	 when '36' then 'Nota de débito electrónica de venta'
	 when '37' then 'Factura fiscal de venta'
	 when '38' then 'Nota de crédito fiscal de venta'
	 when '39' then 'Nota de débito fiscal de venta'
	else ''
end
return @retorno
END