IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Funciones].[ObtenerIdentificadorComprobanteComprobantesYGruposDeCaja]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Funciones].[ObtenerIdentificadorComprobanteComprobantesYGruposDeCaja];
GO;

CREATE FUNCTION [Funciones].[ObtenerIdentificadorComprobanteComprobantesYGruposDeCaja]
( @TipoDeComprobante varchar(2) )
RETURNS varchar (3)
AS
BEGIN
declare @retorno varchar (3)
set @retorno = 
case @TipoDeComprobante
	 when '00' then 'FAC'
	 when '01' then 'FAC'
	 when '23' then 'FAC'
	 when '02' then ' NC'
	 when '03' then ' NC'
	 when '24' then ' NC'
	 when '04' then ' ND'
	 when '05' then ' ND'
	 when '25' then ' ND'
	 when '07' then ' TF'
	 when '08' then ' TF'
	 when '26' then ' TF'
	 when '40' then ' TF'
	 when '09' then 'TNC'
	 when '10' then 'TNC'
	 when '27' then 'TNC'
	 when '41' then 'TNC'
	 when '11' then 'TND'
	 when '12' then 'TND'
	 when '28' then 'TND'
	 when '50' then 'FDC'
	 when '51' then 'FDC'
	 when '52' then 'FDC'
	 when '70' then 'FDC'
	 when '42' then 'FDC'
	 when '44' then 'FDC'
	 when '64' then 'NDC'
	 when '65' then 'NDC'
	 when '66' then 'NDC'
	 when '71' then 'NDC'
	 when '45' then 'NDC'
	 when '67' then 'NCC'
	 when '68' then 'NCC'
	 when '69' then 'NCC'
	 when '72' then 'NCC'
	 when '43' then 'NCC'
	 when '46' then 'NCC'
	 when '53' then 'FEN'
	 when '54' then 'FEN'
	 when '55' then 'FEN'
	 when '56' then 'CEN'
	 when '57' then 'CEN'
	 when '58' then 'CEN'
	 when '59' then 'DEN'
	 when '60' then 'DEN'
	 when '61' then 'DEN'
	 when '83' then 'FEL'
	 when '84' then 'FEL'
	 when '85' then 'FEL'
	 when '86' then 'NCE'
	 when '87' then 'NCE'
	 when '88' then 'NCE'
	 when '89' then 'NDE'
	 when '90' then 'NDE'
	 when '91' then 'NDE'
	 when '76' then 'FEE'
	 when '77' then 'NCE'
	 when '78' then 'NDE'
	 when '79' then 'FMX'
	 when '80' then 'NCM'
	 when '81' then 'NDM'
	 when '13' then 'REC'
	 when '14' then 'BFL'
	 when '15' then 'FEC'
	 when '16' then 'NCC'
	 when '17' then 'BPC'
	 when '18' then 'NCP'
	 when '20' then 'FEC'
	 when '21' then 'NCH'
	 when '06' then ' CC'
	 when '63' then 'ODP'
	 when '62' then 'PAG'
	 when '82' then 'COP'
	 when '99' then 'ADC'
	 when '96' then 'AJC'
	 when '97' then 'CDC'
	 when '31' then 'FAC'
	 when '32' then ' NC'
	 when '33' then ' ND'
	 when '34' then 'FEL'
	 when '35' then 'NCE'
	 when '36' then 'NDE'
	 when '37' then ' TF'
	 when '38' then 'TNC'
	 when '39' then 'TND'
	else ''
end
return @retorno
END