IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Funciones].[ObtenerEntidadDeOrigenDelRegistroComprobantesYGruposDeCaja]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Funciones].[ObtenerEntidadDeOrigenDelRegistroComprobantesYGruposDeCaja];
GO;

CREATE FUNCTION [Funciones].[ObtenerEntidadDeOrigenDelRegistroComprobantesYGruposDeCaja]
( @TipoDeComprobante varchar(2) )
RETURNS varchar (50)
AS
BEGIN
declare @retorno varchar (50)
set @retorno = 
case @TipoDeComprobante
	 when '00' then 'FACTURA'
	 when '01' then 'FACTURA'
	 when '23' then 'FACTURA'
	 when '02' then 'NOTADECREDITO'
	 when '03' then 'NOTADECREDITO'
	 when '24' then 'NOTADECREDITO'
	 when '04' then 'NOTADEDEBITO'
	 when '05' then 'NOTADEDEBITO'
	 when '25' then 'NOTADEDEBITO'
	 when '07' then 'TICKETFACTURA'
	 when '08' then 'TICKETFACTURA'
	 when '26' then 'TICKETFACTURA'
	 when '40' then 'TICKETFACTURA'
	 when '09' then 'TICKETNOTADECREDITO'
	 when '10' then 'TICKETNOTADECREDITO'
	 when '27' then 'TICKETNOTADECREDITO'
	 when '41' then 'TICKETNOTADECREDITO'
	 when '11' then 'TICKETNOTADEDEBITO'
	 when '12' then 'TICKETNOTADEDEBITO'
	 when '28' then 'TICKETNOTADEDEBITO'
	 when '50' then 'FACTURADECOMPRA'
	 when '51' then 'FACTURADECOMPRA'
	 when '52' then 'FACTURADECOMPRA'
	 when '70' then 'FACTURADECOMPRA'
	 when '42' then 'FACTURADECOMPRA'
	 when '44' then 'FACTURADECOMPRA'
	 when '64' then 'NOTADEDEBITOCOMPRA'
	 when '65' then 'NOTADEDEBITOCOMPRA'
	 when '66' then 'NOTADEDEBITOCOMPRA'
	 when '71' then 'NOTADEDEBITOCOMPRA'
	 when '45' then 'NOTADEDEBITOCOMPRA'
	 when '67' then 'NOTADECREDITOCOMPRA'
	 when '68' then 'NOTADECREDITOCOMPRA'
	 when '69' then 'NOTADECREDITOCOMPRA'
	 when '72' then 'NOTADECREDITOCOMPRA'
	 when '43' then 'NOTADECREDITOCOMPRA'
	 when '46' then 'NOTADECREDITOCOMPRA'
	 when '53' then 'FACTURAELECTRONICA'
	 when '54' then 'FACTURAELECTRONICA'
	 when '55' then 'FACTURAELECTRONICA'
	 when '56' then 'NOTADECREDITOELECTRONICA'
	 when '57' then 'NOTADECREDITOELECTRONICA'
	 when '58' then 'NOTADECREDITOELECTRONICA'
	 when '59' then 'NOTADEDEBITOELECTRONICA'
	 when '60' then 'NOTADEDEBITOELECTRONICA'
	 when '61' then 'NOTADEDEBITOELECTRONICA'
	 when '83' then 'FACTURAELECTRONICADECREDITO'
	 when '84' then 'FACTURAELECTRONICADECREDITO'
	 when '85' then 'FACTURAELECTRONICADECREDITO'
	 when '86' then 'NOTADECREDITOELECTRONICADECREDITO'
	 when '87' then 'NOTADECREDITOELECTRONICADECREDITO'
	 when '88' then 'NOTADECREDITOELECTRONICADECREDITO'
	 when '89' then 'NOTADEDEBITOELECTRONICADECREDITO'
	 when '90' then 'NOTADEDEBITOELECTRONICADECREDITO'
	 when '91' then 'NOTADEDEBITOELECTRONICADECREDITO'
	 when '76' then 'FACTURAELECTRONICAEXPORTACION'
	 when '77' then 'NOTADECREDITOELECTRONICAEXPORTACION'
	 when '78' then 'NOTADEDEBITOELECTRONICAEXPORTACION'
	 when '79' then 'FACTURADEEXPORTACION'
	 when '80' then 'NOTADECREDITODEEXPORTACION'
	 when '81' then 'NOTADEDEBITODEEXPORTACION'
	 when '13' then 'RECIBO'
	 when '14' then ''
	 when '15' then ''
	 when '16' then ''
	 when '17' then ''
	 when '18' then ''
	 when '20' then ''
	 when '21' then ''
	 when '06' then 'COMPROBANTEDECAJA'
	 when '63' then 'ORDENDEPAGO'
	 when '62' then 'PAGO'
	 when '82' then 'COMPROBANTEPAGO'
	 when '99' then ''
	 when '96' then ''
	 when '97' then 'CANJEDECUPONES'
	 when '31' then 'FACTURA'
	 when '32' then 'NOTADECREDITO'
	 when '33' then 'NOTADEDEBITO'
	 when '34' then 'FACTURAELECTRONICA'
	 when '35' then 'NOTADECREDITOELECTRONICA'
	 when '36' then 'NOTADEDEBITOELECTRONICA'
	 when '37' then 'TICKETFACTURA'
	 when '38' then 'TICKETNOTADECREDITO'
	 when '39' then 'TICKETNOTADEDEBITO'
	else ''
end
return @retorno
END