IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Funciones].[ObtenerGrupoDeInformeComprobantesYGruposDeCaja]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [Funciones].[ObtenerGrupoDeInformeComprobantesYGruposDeCaja];
GO;

CREATE FUNCTION [Funciones].[ObtenerGrupoDeInformeComprobantesYGruposDeCaja]
( @TipoDeComprobante varchar(2) )
RETURNS varchar (10)
AS
BEGIN
declare @retorno varchar (10)
set @retorno = 
case @TipoDeComprobante
	 when '00' then 'VENTAS'
	 when '01' then 'VENTAS'
	 when '23' then 'VENTAS'
	 when '02' then 'VENTAS'
	 when '03' then 'VENTAS'
	 when '24' then 'VENTAS'
	 when '04' then 'VENTAS'
	 when '05' then 'VENTAS'
	 when '25' then 'VENTAS'
	 when '07' then 'VENTAS'
	 when '08' then 'VENTAS'
	 when '26' then 'VENTAS'
	 when '40' then 'VENTAS'
	 when '09' then 'VENTAS'
	 when '10' then 'VENTAS'
	 when '27' then 'VENTAS'
	 when '41' then 'VENTAS'
	 when '11' then 'VENTAS'
	 when '12' then 'VENTAS'
	 when '28' then 'VENTAS'
	 when '50' then 'COMPRAS'
	 when '51' then 'COMPRAS'
	 when '52' then 'COMPRAS'
	 when '70' then 'COMPRAS'
	 when '42' then 'COMPRAS'
	 when '44' then 'COMPRAS'
	 when '64' then 'COMPRAS'
	 when '65' then 'COMPRAS'
	 when '66' then 'COMPRAS'
	 when '71' then 'COMPRAS'
	 when '45' then 'COMPRAS'
	 when '67' then 'COMPRAS'
	 when '68' then 'COMPRAS'
	 when '69' then 'COMPRAS'
	 when '72' then 'COMPRAS'
	 when '43' then 'COMPRAS'
	 when '46' then 'COMPRAS'
	 when '53' then 'VENTAS'
	 when '54' then 'VENTAS'
	 when '55' then 'VENTAS'
	 when '56' then 'VENTAS'
	 when '57' then 'VENTAS'
	 when '58' then 'VENTAS'
	 when '59' then 'VENTAS'
	 when '60' then 'VENTAS'
	 when '61' then 'VENTAS'
	 when '83' then 'VENTAS'
	 when '84' then 'VENTAS'
	 when '85' then 'VENTAS'
	 when '86' then 'VENTAS'
	 when '87' then 'VENTAS'
	 when '88' then 'VENTAS'
	 when '89' then 'VENTAS'
	 when '90' then 'VENTAS'
	 when '91' then 'VENTAS'
	 when '76' then 'VENTAS'
	 when '77' then 'VENTAS'
	 when '78' then 'VENTAS'
	 when '79' then 'VENTAS'
	 when '80' then 'VENTAS'
	 when '81' then 'VENTAS'
	 when '13' then 'FONDOS'
	 when '14' then 'VENTAS'
	 when '15' then 'VENTAS'
	 when '16' then 'VENTAS'
	 when '17' then 'VENTAS'
	 when '18' then 'VENTAS'
	 when '20' then 'VENTAS'
	 when '21' then 'VENTAS'
	 when '06' then 'FONDOS'
	 when '63' then 'FONDOS'
	 when '62' then 'FONDOS'
	 when '82' then 'FONDOS'
	 when '99' then 'FONDOS'
	 when '96' then 'FONDOS'
	 when '97' then 'FONDOS'
	 when '31' then 'VENTAS'
	 when '32' then 'VENTAS'
	 when '33' then 'VENTAS'
	 when '34' then 'VENTAS'
	 when '35' then 'VENTAS'
	 when '36' then 'VENTAS'
	 when '37' then 'VENTAS'
	 when '38' then 'VENTAS'
	 when '39' then 'VENTAS'
	else ''
end
return @retorno
END