[DATOS]
; RutaDataConfig=C:\ZooLogicSA.Repos\GIT\Organic\Organic.ZL\bin\Exe\
RutaDataConfig=.
[SETEOSAPLICACION]
NombreAplicacion=ZL
NombreProducto=ZL
NombreComercial=Zoo Logic ZL
ComplejidadEnConsultas=2040
PAQUETEADN=
Serie=
UtilizarWinExec=SI
[ADNIMPLANT]
RutaZipGenerados=
VERSIONADNIMPLANT=.NET
[SEGURIDAD]
UltimoUsuarioLogueado=
[POOLDEOBJETOS]
Habilitado=SI
SegundosFrecuenciaDeMonitoreo=1
PorcentajeUsoCPU=8
NumeroMaximoDeVerificacionesDeInactividadDeCPU=2
SegundosDeUltimaEntradaUsuario=10
MinimoRAMFisicaLibre=256
HabilitadoBeta=NO
ClasesBase=NO
ClasesVisuales=SI
ClasesDeNegocio=NO
[POOLDEAPLICACIONES]
Habilitado=SI
PDA_Habilitado=SI
[EXPERIENCIADEUSUARIO]
Habilitada=NO
Comprobantes=
