[Explicaciones]
;;;[Backup]
;;;Cambia Carpeta Destino: indica si el programa permite seleccionar otra ruta de destino 
;;;     para el resguardo. Por default esta en "Si".
;;;Carpeta destino: indica la ruta que el programa sugiere para colocar el resguardo. 
;;;     A su vez también almacena la última ruta utilizada. Por default esta en A:\
;;;Resguardo: indica el nombre del agrupamiento o sucursal que el programa sugiere para 
;;;     resguardar. También almacena la última selección realizada. Por default esta vacio.
;;;QueEs: indica el tipo de la última selección: “Agrupamiento” o “Sucursal”. Por default esta vacio.
;;;Carpeta de la aplicación: Especifica mediante la palabra ACTUAL, si debe levantar la tabla emp.dbf de
;;;		la carpeta actual o la superior.
;;;Nombre de la aplicación: Nombre completo de aplicación a la que se le hará backup.
;;;Nombre corto de la aplicación: Nombre corto de aplicación a la que se le hará backup.
;;;
;;;[LinceDbf]
;;;File1: …
;;;File2: …
;;;FileN-1: …
;;;FileN: se indican los archivos del sistema que se desean resguardar, además de los de 
;;;     las sucursales seleccionadas. Por default estan todos los archivos DBF del Lincev3,
;;;     el intermec.txt y las etiquetas del LBX.


[Backup]
Carpeta Destino=C:\Dragonfish\Backups
Resguardo=
QueEs=Sucursal
Cambia Carpeta Destino=Si
TmpFile=
Usa archivo Temporario=SI
Testear Backup al finalizar=NO
Carpeta de la aplicación=Actual
Nombre de la aplicación=Dragonfish Color y Talle
Nombre corto de la aplicación=Dragonfish
Porcentaje de espacio libre requerido=10

[LinceDbf]
